### ISSUE TITLE
HTseq module brakes if 0 counts

### ISSUE THREAD

**Issue by SemiQuant** [ewels/MultiQC#1006]
**Description of bug:**
If a htseq count file is present with all 0s, an error is thrown. Not a huge issue but thought I'd post it.

**MultiQC Error log:**
```
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    path/file.HTSeq.counts
============================================================
Module htseq raised an exception: Traceback (most recent call last):
  File "/usr/local/bin/multiqc", line 440, in multiqc
    output = mod()
  File "/usr/local/lib/python2.7/dist-packages/multiqc/modules/htseq/htseq.py", line 31, in __init__
    parsed_data = self.parse_htseq_report(f)
  File "/usr/local/lib/python2.7/dist-packages/multiqc/modules/htseq/htseq.py", line 70, in parse_htseq_report
    parsed_data['percent_assigned'] = (float(parsed_data['assigned']) / float(parsed_data['total_count'])) * 100.0
ZeroDivisionError: float division by zero
============================================================
```

**MultiQC run details (please complete the following):**
multiqc "path"
MultiQC v1.7
Ubuntu Singularity container
Python 2.7.15rc1

**Comment by ewels** [comment]
Hi @SemiQuant,

Thanks for this! Do you have an example file that I can use to confirm any bugfix?

Phil

**Comment by ewels** [comment]
Should be an easy fix, just catching the `ZeroDivisionError` here... https://github.com/ewels/MultiQC/blob/68fc58f7c35afdf0795b40b3b71ec6288d7411fa/multiqc/modules/htseq/htseq.py#L70

**Comment by ewels** [comment]
ok, as it was such a simple fix I've pushed it without testing - if you could confirm that this solves the problem @SemiQuant, that would be great!

Cheers,

Phil

**Comment by SemiQuant** [comment]
Hi Phil

The fix is working perfectly, thanks!

I used MultiQC v1.8.dev0 to check.

**Comment by ewels** [comment]
Great! Thanks for checking :)
