### ISSUE TITLE
more colours for fastq_screen?

### ISSUE THREAD

**Issue by RichardCorbett** [ewels/MultiQC#1007]
Hi there,

This is minor and I have a workaround, but I'm wondering how difficult it would be to allow more colours in the fastq_screen images?    My current fastq_screen setup uses 18 sequence sets and I get the same colour associated with human and pseudomonas which makes it hard to see if there is pseudomonas contamination.

Either more colours, or a way to associate the colours I want with the genomes I want would work.

thanks,
Richard

![Screenshot from 2019-08-27 16-26-10](https://user-images.githubusercontent.com/9285915/63815027-e1096280-c8e7-11e9-91e7-38dbb696ef8d.png)

**Comment by ewels** [comment]
I think that more colours will be difficult (or at least difficult to do it usefully). Once you have many more it gets pretty difficult for the eye to discern the different categories. However, having a config option to allow you to choose your own colours for a given species should be no problem.

Phil

**Comment by ewels** [comment]
Hi @RichardCorbett,

I've just updated the FastQ Screen module a little. It now sorts the categories based on the total read counts and hides any genomes that have zero counts. I'm hoping that this will make the plot a lot easier to read and will hopefully avoid the need for more colours.

I'll close this issue now, but let me know if you'd still like the configuration to specify custom colours for a given genome.

Phil
