### ISSUE TITLE
deeptools plotProfile error when parsing reference-point mode output

### ISSUE THREAD

**Issue by Adrien-Evo** [ewels/MultiQC#1011]
**Description of bug:**
Hi,
The deeptools module breaks when parsing the text output from deeptools plotProfile when in reference point. In this case, there is no `--endLabel` options so there is no key `TES` in the `bin_labels` dictionary

Also, there is was an error in the `parsePlotProfileData` function :

```python
    bins.append(int(col))
ValueError: invalid literal for int() with base 10: '1.0'
```

because the plotProfile tools outputs the bin number as float (1.0) which causes this error. But that's easily solvable with `sed 's/\.0\t/\t/g' `

**MultiQC Error log:**

```python
Module deeptools raised an exception: Traceback (most recent call last):
  File "/sandbox/users/foucal-a/miniconda3/envs/deeptools/bin/multiqc", line 440, in multiqc
    output = mod()
  File "/sandbox/users/foucal-a/miniconda3/envs/deeptools/lib/python3.6/site-packages/multiqc/modules/deeptools/deeptools.py", line 75, in __init__
    n['plotProfile'] = self.parse_plotProfile()
  File "/sandbox/users/foucal-a/miniconda3/envs/deeptools/lib/python3.6/site-packages/multiqc/modules/deeptools/plotProfile.py", line 36, in parse_plotProfile
    {'from': converted_bin_labels[bin_labels.index('TES')], 'to': converted_bin_labels[-1], 'color': '#f7cfcf'},
ValueError: 'TES' is not in list
```

**File that triggers the error:**
[test.plotProfile.txt](https://github.com/ewels/MultiQC/files/3600900/test.plotProfile.txt)

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC: [`multiqc test.plotProfile`]
 - MultiQC Version: [eg. MultiQC v1.7]
 - Operating System: [unix]
 - Python Version: [eg. Python 3.6]

**Comment by ewels** [comment]
Hi @Adrien-Evo,

Sorry for the delay and thanks for reporting this. With the help of your example file I figured out what was going on and have just pushed a fix. With your data you sadly won't get the nice coloured background bands behind the plot, but you will still get a plot and it won't crash any more.

Let me know how you get on!

Phil
