### ISSUE TITLE
FastQC: Per Base Sequence Content DOM bug

### ISSUE THREAD

**Issue by skchronicles** [ewels/MultiQC#1012]
**Description of bug:**
If you overwrite the anchor for FastQC using a config file, it will cause the following buttons to break in *Per Base Sequence Content*: `Back to overview heatmap`, `Prev`, and `Next`.

![image](https://user-images.githubusercontent.com/18038345/64983847-81bbc400-d88f-11e9-93ab-0454d4d2237f.png)

Because the button is no longer working, you must reload the page to go *Back to overview heatmap*.

Here is an example of a config file that creates the problem. **Note**: If you remove the `anchor` line everything works fine.
```
# USAGE: multiqc -f -c multiqc_config.yaml --interactive  -d .  -n multiqc_report.html

# custom_logo: '/path/to/ccbr/logo.png'

fastqscreen_simpleplot: true

module_order:
# Pre-alignment QC
    - 'fastq_screen'
    - 'fastqc':
        name: 'FastQC'
        anchor: 'before_after'
        info: 'This section of the report shows FastQC results before and after adapter trimming.'

```

**MultiQC Error log:**
No explicit errors when running `multiqc`.
```
[WARNING]         multiqc : MultiQC Version v1.7 now available!
[INFO   ]         multiqc : This is MultiQC v1.6
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Prepending directory to sample names
[INFO   ]         multiqc : Searching '.'
Searching 40 files..  [####################################]  100%          
[INFO   ]           bcbio : Found 0 reports
[INFO   ]    fastq_screen : Found 8 reports
[INFO   ]          fastqc : Found 8 reports
[INFO   ]            star : Found 2 reports
[INFO   ]          picard : Found 2 MarkDuplicates reports
[INFO   ]          picard : Found 2 RnaSeqMetrics reports
[INFO   ]         multiqc : Compressing plot data
[WARNING]         multiqc : Deleting    : multiqc_report.html   (-f was specified)
[WARNING]         multiqc : Deleting    : multiqc_report_data   (-f was specified)
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_report_data
[INFO   ]         multiqc : MultiQC complete
```

**File that triggers the error:**
Tarball containing example data (generated from randomly sub-sampling FastQ files-- ignore interpretation of the results) and the problematic `multiqc_report.html`. 
[multiqc-1.6_fastqc_bug.tar.gz](https://github.com/ewels/MultiQC/files/3617619/multiqc-1.6_fastqc_bug.tar.gz)
```
data/
├── CCBR_LOGO.png
├── FQscreen
│   ├── I1.R1.trimmed_db1_screen.txt
│   ├── I1.R2.trimmed_db1_screen.txt
│   ├── T1.R1.trimmed_db1_screen.txt
│   └── T1.R2.trimmed_db1_screen.txt
├── FQscreen2
│   ├── I1.R1.trimmed_db2_screen.txt
│   ├── I1.R2.trimmed_db2_screen.txt
│   ├── T1.R1.trimmed_db2_screen.txt
│   └── T1.R2.trimmed_db2_screen.txt
├── logfiles
│   ├── I1.p2.Log.final.out
│   ├── I1.RnaSeqMetrics.txt
│   ├── I1.star.duplic
│   ├── T1.p2.Log.final.out
│   ├── T1.RnaSeqMetrics.txt
│   └── T1.star.duplic
├── multiqc_config_BUG.yaml    # Config file that causes the problem
├── multiqc_config.yaml        # Config file that works as expected
├── multiqc_report_data
│   ├── multiqc_bcbio_metrics.txt
│   ├── multiqc_data.json
│   ├── multiqc_fastqc.txt
│   ├── multiqc_fastq_screen.txt
│   ├── multiqc_general_stats.txt
│   ├── multiqc.log
│   ├── multiqc_picard_dups.txt
│   ├── multiqc_picard_RnaSeqMetrics.txt
│   ├── multiqc_sources.txt
│   ├── multiqc_star.txt
│   ├── seqbuster_isomirs.txt
│   └── seqbuster_mirs.txt
├── multiqc_report.html
├── QC
│   ├── getme
│   ├── I1.R1.trimmed_fastqc.zip
│   ├── I1.R2.trimmed_fastqc.zip
│   ├── T1.R1.trimmed_fastqc.zip
│   └── T1.R2.trimmed_fastqc.zip
└── rawQC
    ├── getme
    ├── I1.R1_fastqc.zip
    ├── I1.R2_fastqc.zip
    ├── T1.R1_fastqc.zip
    └── T1.R2_fastqc.zip

```

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC: [eg. `multiqc -f -c multiqc_config_BUG.yaml --interactive  -d .  -n multiqc_report.html`]
 - MultiQC Version: [eg. MultiQC v1.6], also seems to cause a problem in `1.7` as well but the problem is slightly different. 
 - Operating System: [eg. centOS 7]
 - Python Version: [eg. Python 2.7.15]
 - Method of MultiQC installation: [eg. conda]

 **Additional context**
I have also provided to multiqc config files for the your testing: `multiqc_config_BUG.yaml` and `multiqc_config.yaml`. Please let me know if you have any questions.

**Comment by ewels** [comment]
Thanks for reporting this @skchronicles - the FastQC module was written well before it was possible to (a) have multiple FastQC sections in a single report or (b) change the anchor.

There has been some progress on this recently, and your bug seems to vary quite a bit on version as you say at the end of your issue. When I try your config file in v1.8dev there are no longer and samples found for the heatmap (and the status summary buttons all disappear). @lukaw3d has refactored a lot of this code in #920 and when I tried his branch I get the plot back, but it's empty. And the status summary buttons are still gone 😓 

Anyway, I will finally be back at work next week (50%) and will start working through PRs and then issues. I'll get to this as soon as I can. @lukaw3d - I will hopefully get to merging your PR very soon! If you're able to take a look at this bug before I get there then that would be fantastic though 😉 

Phil

**Comment by lukaw3d** [comment]
I'm back from vacation :) Maybe the only issue was unreliable element selector:
`$('.mqc-module-section[id^="mqc-module-section-fastqc"]')`

I'm not completely happy with my solution to find all FastQC modules: `$('.fastqc_passfails').closest('.mqc-module-section')` it depends on a child element
