### ISSUE TITLE
FreeBSD port now available

### ISSUE THREAD

**Issue by outpaddling** [ewels/MultiQC#1014]
FYI:

py-multiqc has been committed to the FreeBSD ports collection.
It might be helpful to users if you could post a message like
the following on your website:

Thanks!

===

py36-multiqc can be installed on FreeBSD via the FreeBSD ports system.

To install via the binary package, simply run:

    `pkg install py36-multiqc`

(or py27-multiqc, py37-multiqc, or any other currently mainstream python version)

This will very quickly install a prebuilt binary using only highly-portable
optimizations, much like apt, yum, etc.

FreeBSD ports can just as easily be built and installed from source,
although it will take longer (for the computer, not for you):

```
cd /usr/ports/biology/py-multiqc
make install
```

Building from source allows installing to a different prefix, compiling with
native optimizations, and in some cases, building with non-default options
such as different compilers or dependencies.  For example, adding

    `CFLAGS+=-march=native`

to /etc/make.conf will cause compiled ports built from source to use all native
optimizations known to the compiler for the local CPU, resulting in faster
but less portable binaries.

To report issues with a FreeBSD port, please submit a PR at:

    https://www.freebsd.org/support/bugreports.html

For more information, visit https://www.freebsd.org/ports/index.html.

**Comment by ewels** [comment]
Very nice, thank you! 👍

**Comment by ewels** [comment]
Added: https://multiqc.info/docs/#installing-from-freebsd

Thanks again!

**Comment by outpaddling** [comment]
Awesome, thanks.  :-)
