### ISSUE TITLE
Remove requirement for image files to contain _mqc suffix

### ISSUE THREAD

**Issue by sfrenk** [ewels/MultiQC#1016]
I'm currently building a plugin for a custom module that requires insertion of PNG files. Currently, image files must have the "_mqc" suffix in order to be located by the find_log_files() method:

https://github.com/ewels/MultiQC/blob/master/multiqc/utils/report.py#L198

While it's possible to work around this issue by copying the relevant file and adding the _mqc suffix to the filename, it would be nice to not have to do this.

**Comment by ewels** [comment]
Hmm, downside of this is that some of the more generic search patterns could then start returning images... eg:
https://github.com/ewels/MultiQC/blob/26076d71a0d7c65f8f189765b2ec82f454306706/multiqc/utils/search_patterns.yaml#L255-L256

https://github.com/ewels/MultiQC/blob/26076d71a0d7c65f8f189765b2ec82f454306706/multiqc/utils/search_patterns.yaml#L491-L492

How about I instead make a config option called `config.ignore_images` which is set to `True` by default? Then you can disable that in your plugin and that test will just be skipped entirely..

**Comment by sfrenk** [comment]
Sounds Great @ewels, thanks for the swift response!

**Comment by ewels** [comment]
No problem! If you could let me know whether it works / breaks everything, then that would be fab 👍
