### ISSUE TITLE
bamtools stats

### ISSUE THREAD

**Issue by KeyTals** [ewels/MultiQC#103]
Is it possible add Bamtools 'stats' module  and Picard CollectRnaSeqMetrics?

Bamtools stats log file look like this

```
**********************************************
Stats for BAM file(s): 
**********************************************

Total reads:       339957930
Mapped reads:      316585701	(93.125%)
Forward strand:    181666967	(53.4381%)
Reverse strand:    158290963	(46.5619%)
Failed QC:         0	(0%)
Duplicates:        0	(0%)
Paired-end reads:  339957930	(100%)
'Proper-pairs':    312895116	(92.0394%)
Both pairs mapped: 314020716	(92.3705%)
Read 1:            169978965
Read 2:            169978965
Singletons:        2564985	(0.754501%)
```

Thanks,
Keyur

**Comment by ewels** [comment]
Hi Keyur,

Thanks for the suggestion and the example output! I've added your Picard request to issue #12 (with a list of other Picard modules to support).

Does the Bamtools output have a consistent file name, or mention the input filename anywhere? 

Phil

**Comment by KeyTals** [comment]
Bamtools ‘stats’ has stdout but one needs to mention the input file name.

Command: bamtools stats -in <filename.bam>

Let me know if need more information.

Keyur

**Comment by ewels** [comment]
Yup - but does it print this information in the log anywhere, or is what you pasted above the full extent of the output? The reason I ask is that MultiQC needs to get a sample name for each output somehow.

**Comment by KeyTals** [comment]
I pasted the full extent of output. We put sample name as log file name to capture the alignment of samples together.

Keyur

**Comment by ewels** [comment]
Ok, I'll just look at the filename for the sample name then (that's the only thing we can do I think). Thanks!

**Comment by ewels** [comment]
Added example output in ewels/MultiQC_TestData@d6b9d351f6841c4d196480097468e101513468a9

**Comment by ewels** [comment]
Hi @KeyTals,

I've just written this module - if you could have a play and try to find any bugs, that would be great! Also, the log file you posted looks like it's for paired end data, so if you have any examples for single-end bam files that would be good too.

Cheers,

Phil

**Comment by KeyTals** [comment]
Phil,

Thank you for adding this module. I will run this module and inform you if i find any bog. Here is the example of single end bam.


**********************************************
Stats for BAM file(s): 
**********************************************

Total reads:       105094847
Mapped reads:      103235572	(98.2309%)
Forward strand:    53566247	(50.9694%)
Reverse strand:    51528600	(49.0306%)
Failed QC:         0	(0%)
Duplicates:        0	(0%)
Paired-end reads:  0	(0%)

**Comment by ewels** [comment]
Great, thanks! I'll add support for single end too.

**Comment by KeyTals** [comment]
Phil,

I do have a question regarding the salmon module results, I ran 7 samples with salmon, trimmomatic and fastqc I am getting the correct numbers of samples for others but salmon is showing just one sample. Does it mean salmon is overwriting the results under just one name “salmon”.

Here is output log.

[INFO   ]         multiqc : This is MultiQC v0.7.dev0
[INFO   ]         multiqc : Searching './'
[INFO   ]          salmon : Found 1 meta reports
[INFO   ]          salmon : Found 1 fragment length distributions
[INFO   ]     trimmomatic : Found 7 logs
[INFO   ]    fastq_screen : Found 14 reports
[INFO   ]          fastqc : Found 28 reports

Thanks,
Keyur

**Comment by ewels** [comment]
Hi @KeyTals,

I wrote some documentation about this a few days ago!

> [Troubleshooting: Not enough samples found](http://multiqc.info/docs/#not-enough-samples-found)

_(which basically just leads to the previously written docs about [clashing sample names](http://multiqc.info/docs/#clashing-sample-names))._

You're using a collection of the newest and least tested modules there though, so it's good to hear. I haven't used Salmon much myself yet - I was under the impression that each results directory was given the name of the input file / sample name.

If that's not the case, then I should probably take the [input filename](https://github.com/ewels/MultiQC_TestData/blob/master/data/modules/salmon/sample_1/cmd_info.json#L5) instead. Should be an easy change.

Phil

**Comment by KeyTals** [comment]
Phil,

Structure of the salmon files is $output_folder/aux/meta_info.json , even output folder name should work fine.

Keyur

**Comment by KeyTals** [comment]
Phil,

Actually the software works fine. It was my fault, giving the same output folder name. Sorry for that.

Keyur

**Comment by ewels** [comment]
Ok good, I was getting confused as it was working for me with the test dataset :)

Phil

**Comment by ewels** [comment]
Just looked into the bamtools single end output - it's exactly the same as paired end except without the last few fields. So no MultiQC extension required, it already supports single end logs.

I added your log file to the test dataset anyway though. Thanks!

Phil

**Comment by KeyTals** [comment]
Phil,

Is there any way to generate the graphs as images from command line? Right now data folder has text files but it would be nice if there is a option to create graph images from the command line.

Keyur



On May 3, 2016, at 10:24 AM, Phil Ewels <notifications@github.com<mailto:notifications@github.com>> wrote:


Just looked into the bamtools single end output - it's exactly the same as paired end except without the last few fields. So no MultiQC extension required, it already supports single end logs.

I added your log file to the test dataset anyway though. Thanks!

Phil

**Comment by ewels** [comment]
Hi @KeyTals,

Apologies for the slow reply, just found your mail in my inbox. There is _sort of_ a way to do what you're asking. MultiQC can create static image plots for line graphs and bar charts, this is designed for when it's run with massive numbers of samples where the interactive plots crash the browser. You can force MultiQC to use these flat image plots by specifying the flag `--flat` when you run it. When such flat plots are generated, they're saved in `multiqc_data/multiqc_plots` as well as being embedded into the report.

Note that not all plots have code to generate flat versions though (yet), so this won't work for everything. It also forces you to have flat plots in the report.

Phil
