### ISSUE TITLE
HiSAT2 .summary file not recognised

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#1036]
_Originally posted by @marcos-lozalva in https://github.com/ewels/MultiQC/issues/765#issuecomment-544441776_

---

Hi Phil,

Firstly thank you for this great tool, please I have an issue regarding my `.summary` output files from HISAT2, they're not recognized by MultiQC, I show you an example of this files:

```
Total_fragments	62736799
Mapped_fragments	61845090
Uniquely_mapped_fragments	55601438
Multi_mapping_fragments	6243652
Unmapped_fragments	891709
Properly_paired_fragments	52083870
Singleton_fragments	2908999
More_than_one_chr_fragments	2255641
Unexpected_strandness_fragments	113039
Unexpected_template_length	4402557
Inversed_mapping	80984
Indels	504889
```

Please can you help me?

Thank you

Marcos

**Comment by ewels** [comment]
Hi @marcos-lozalva,

Sorry to hear that you're having problems. Please could you attach the `.summary` file to the issue as a file, so that the whitespace is not affected? Also please provide more details about how you're running MultiQC - the command, the version and the log output.

Thanks,

Phil

**Comment by marcos-lozalva** [comment]
Hi Phil,

Github doesn't allow me attach the .summary file, should I change the extension to .log?. I run MultiQC on the terminal in iOS as you can see above
MacBook-Pro-de-marcos:output marcos$ multiqc *.summary
/usr/local/lib/python3.7/site-packages/multiqc/utils/config.py:45: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  configs = yaml.load(f)
/usr/local/lib/python3.7/site-packages/multiqc/utils/config.py:51: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  sp = yaml.load(f)
[INFO   ]         multiqc : This is MultiQC v1.7
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching 'out.18NR0293_S1_R1_001.fastq.gz.subread.BAM.summary'
[INFO   ]         multiqc : Searching 'out.18NR0295_S2_R1_001.fastq.gz.subread.BAM.summary'
[INFO   ]         multiqc : Searching 'out.18NR0297_S3_R1_001.fastq.gz.subread.BAM.summary'
[INFO   ]         multiqc : Searching 'out.18NR0299_S4_R1_001.fastq.gz.subread.BAM.summary'
[INFO   ]         multiqc : Searching 'out.18NR0301_S5_R1_001.fastq.gz.subread.BAM.summary'
[INFO   ]         multiqc : Searching 'out.18NR0303_S6_R1_001.fastq.gz.subread.BAM.summary'
[INFO   ]         multiqc : Searching 'out.18NR0305_S7_R1_001.fastq.gz.subread.BAM.summary'
[INFO   ]         multiqc : Searching 'out.18NR0307_S8_R1_001.fastq.gz.subread.BAM.summary'
[INFO   ]         multiqc : Searching 'out.18NR0309_S9_R1_001.fastq.gz.subread.BAM.summary'
[INFO   ]         multiqc : Searching 'out.18NR0311_S10_R1_001.fastq.gz.subread.BAM.summary'
[INFO   ]         multiqc : Searching 'out.18NR0313_S11_R1_001.fastq.gz.subread.BAM.summary'
[INFO   ]         multiqc : Searching 'out.18NR0315_S12_R1_001.fastq.gz.subread.BAM.summary'
/usr/local/bin/multiqc:495: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logger.warn("No analysis results found. Cleaning up..")
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete

Do you need any more details?

Thank you

Marcos

**Comment by ewels** [comment]
Yes, if you could rename the extension that would be great 👍  How did you run HiSAT to get the output file?

**Comment by marcos-lozalva** [comment]
OK, here is the file and the loop I used in HISAT2.

for i in $(ls | grep 'R1')
do
	echo 'Aligning' ${i%_S*}'...'
	R2=$(echo ${i} | sed 's/R1/R2/g')
 	hisat2 -p 8 -x ~/TFM/rnaseq_marcos/input/grch38_snp_tran/genome_snp_tran -1 ./${i} -2 ./$R2 -S ./${i%_S*}.sam 
	echo  ${i%_S*}.sam 'to' ${i%_S*}.bam 'conversion...'
	samtools sort -o ${i%_S*}.bam ./${i%_S*}.sam
	rm ${i%_S*}.sam 
	echo 'File' ${i%_S*}.sam 'eliminated'
	echo ${i%_S*} 'alignment completed'


[out.18NR0293_summary.log](https://github.com/ewels/MultiQC/files/3750627/out.18NR0293_summary.log)


Marcos

**Comment by ewels** [comment]
Nice, thanks! If you use the `--summary-file [PATH]` flag for HiSAT2 then it will save a file which MultiQC can understand more easily. See https://multiqc.info/docs/#hisat2

Strangely, your output does not look like the example output that I already have from HiSAT2, see https://github.com/ewels/MultiQC_TestData/tree/master/data/modules/hisat2 - I also can't see in your commands where the `.summary` file is being generated.

If I google for the term `More_than_one_chr_fragments` then I get a help PDF for the [Rsubread](https://bioconductor.org/packages/release/bioc/html/Rsubread.html) package. This log output looks very much like what you've pasted. Are you sure this isn't where your summary files are coming from? MultiQC does not (yet) support the Subread aligner.

Side note: you might be interested in https://nf-co.re/rnaseq 😄

**Comment by marcos-lozalva** [comment]
Sorry Phil, the ouput files were indeed from Rsubread. Unfortunately I can't repeat the alignment in HISAT2 with the --summary-file flag and I missed the .summary files. Anyways I will have to use MultiQC only for FastQC. It's a shame, this is a wonderful tool.
Thank you very much for your help!

**Comment by ewels** [comment]
No problem! Note that MultiQC does still work for HISAT2 without the summary flag, but it shows up as Bowtie2 because the output is identical. Also, you have to capture the STDERR log messages from HISAT2 at run time, as it doesn’t save this information to a file by default.

If you just want to know about the alignment metrics and you have the BAM files still, you can run `samtools stat` on them. MultiQC understands output from that and you can see the alignment rates that way. That’s what I usually do when I forget to save the stderr to a file! :grin:

Phil
