### ISSUE TITLE
Ability to compile information from multiple sources for the same sample and metric

### ISSUE THREAD

**Issue by shyama-mama** [ewels/MultiQC#1037]
**Is your feature request related to a problem? Please describe.**
If 'SampleA' has been sequenced with 2 different indexes. bcl2fastq (run with lane merging) would create two pairs of fastqs such as SampleA_S1_R[12]_001.fastq.gz and SampleA_S2_R[12]_001.fastq.gz
If FastQC was run then you would get 2 pairs of SampleA_S[12]_R[12]_001_fastqc.[html,zip] files. 

When running multiqc it only accounts for 1 of these two pairs. It only gets the yield for one of the indexes i.e in the multiqc_data/multiqc_sources.txt only one off these fastqc pairs is referenced either S1 or S2. Hence the yield for only 1 index shows. 

**Describe the solution you'd like**
Depending on the situation is there a way for multiqc to behave one of two ways:

1. Merge the two metric values into 1 so it adds the yields for SampleA_S1 and SampleA_S2 from both fastqcs and averages the Q30 and merges the other metrics appropriately
2. Have separate instances for each index. SampleA_S1 and SampleA_S2. 

**Describe alternatives you've considered**
Currently I'm manually parsing fastqc metrics to create a csv file that automatically merges the metrics appropriately into one sample name. 
Sorry if this behaviour already exists in MultiQC.

**Comment by ewels** [comment]
See the docs for avoiding the overwrite:

* https://multiqc.info/docs/#not-enough-samples-found
* https://multiqc.info/docs/#clashing-sample-names

Regarding merging the metrics, this is not current possible. It is however something that I've been working on and hope to get back to soon. See https://github.com/ewels/MultiQC/pull/576

**Comment by shyama-mama** [comment]
Thank you very much for that :)

**Comment by ewels** [comment]
No problem! Let me know if you run in to any trouble..
