### ISSUE TITLE
Option to hide sidebar

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#104]
Add option to hide the navigation sidebar.

**Comment by ewels** [comment]
Maybe something like [this](http://ironsummitmedia.github.io/startbootstrap-simple-sidebar/)? ([code here](https://github.com/IronSummitMedia/startbootstrap-simple-sidebar))

**Comment by avilella** [comment]
Yes, that would work well :-)

**Comment by ewels** [comment]
Closed in PR #105
