### ISSUE TITLE
Sample names changes

### ISSUE THREAD

**Issue by nservant** [ewels/MultiQC#1045]
Hi,
Following the manual, I try to set up the buttons to swtich from sample ID (default) to sample name.
In my config, I just add these few lines ;

```
sample_names_rename_buttons:
    - 'Sample ID'
    - 'Sample Name'
sample_names_rename:
    - ["SRR1106775_1","sample_test1"]
    - ["SRR1106776_1","sample_test2"]
```
In the report ;
- All my plots (but a stat table) now use by default the "Sample Name", whereas I would expect to keep the multiQC sample ID by default ?
- From this, when I click on "Sample Name", the toolbox is well defined ;
 SRR1106775_1 > sample_test1
but nothing happen since the sample are already names by the 'Sample Name' column.

Did I miss something ?
Thanks

**Comment by nservant** [comment]
Sorry my fault. I made a mistake in the pipeline before.

**Comment by ewels** [comment]
No problem! Always a relief to hear that it's not my fault 😅
