### ISSUE TITLE
MultiQC not exporting fastp plots

### ISSUE THREAD

**Issue by nicolettacommins** [ewels/MultiQC#1047]
**Description of bug:**
I have about 2000 samples but can't get multiQC html reports to load in a way that isn't extremely slow, even when using the `--flat` flag. Using with fastp reports. I'm also having trouble getting certain figures to export. For example, with sequence quality histograms, I can only export _"Read 1: before filtering"_ but none of the other three. And when I use the `-p` flag, only one plot is exported and none of the others. 

**MultiQC run details (please complete the following):**
- Command used to run MultiQC: 
    ```bash
    multiqc . -n multiqc_fastp_flat -o my_output_dir/multiqc_reports/ --flat -p
    ```
- MultiQC Version: v1.7
- Example report: [multiqc_fastp_cut_right_flat.html.zip](https://github.com/ewels/MultiQC/files/3811260/multiqc_fastp_cut_right_flat.html.zip)

> **The MultiQC report is extremely slow to load in my browser. The toolbox will also only export certain plots, for example, "Read 1: before filtering" but not "Read 2: before filtering"**

**multiQC log (excluded full log but possibly relevant errors):**
```
[2019-11-05 11:03:00,113] multiqc.modules.fastp.fastp                        [INFO   ]  Found 2090 reports
[2019-11-05 11:03:38,382] multiqc.plots.bargraph                             [ERROR  ]  ############### Error making MatPlotLib figure! Falling back to HighCharts.
[2019-11-05 11:03:44,773] multiqc.plots.linegraph                            [ERROR  ]  ############### Error making MatPlotLib figure! Falling back to HighCharts.
[2019-11-05 11:03:56,245] multiqc.plots.linegraph                            [ERROR  ]  ############### Error making MatPlotLib figure! Falling back to HighCharts.
[2019-11-05 11:04:07,437] multiqc.plots.linegraph                            [ERROR  ]  ############### Error making MatPlotLib figure! Falling back to HighCharts.
[2019-11-05 11:04:19,303] multiqc.plots.linegraph                            [ERROR  ]  ############### Error making MatPlotLib figure! Falling back to HighCharts.
[2019-11-05 11:04:29,630] multiqc.plots.linegraph                            [ERROR  ]  ############### Error making MatPlotLib figure! Falling back to HighCharts.
```

Exported plots using `-p` flag: when I try to export using the `-p` flag I get output like this, where only one of the figures is exported in each format: [multiqc_after_fastp_plots.zip](https://github.com/ewels/MultiQC/files/3811271/multiqc_after_fastp_plots.zip)

**Comment by ewels** [comment]
Thank you for the issue @nicolettacommins! If possible, could you please attach the full verbose log file (`multiqc_data/multiqc.log`). There will hopefully be a bunch of debug messages surrounding those `ERROR` logs which will help me with debugging.

Phil

**Comment by nicolettacommins** [comment]
I have attached the log. Thank you!


[multiqc.log](https://github.com/ewels/MultiQC/files/3816828/multiqc.log)

**Comment by ewels** [comment]
So re-reading your issue, I guess that the reports are crashing your browser because there is a problem generating flat images with matplotlib. MultiQC is falling back to interactive plots due to this, making the report super huge with all of the embedded data. This explains both the report and the exported plots.

I just double checked that the fastp module works as expected for me. Sure enough, if I run `multiqc . --flat -p` with the [fastp example data](https://github.com/ewels/MultiQC_TestData/tree/master/data/modules/fastp) it works fine. I don't get any error messages and the report loads fine with all flat images. I also get all exported plots properly (only png saved for brevity):

```
multiqc_plots/png/
├── mqc_fastp-duprates-plot_1.png
├── mqc_fastp-insert-size-plot_1.png
├── mqc_fastp-seq-content-gc-plot_Read_1_After_filtering.png
├── mqc_fastp-seq-content-gc-plot_Read_1_Before_filtering.png
├── mqc_fastp-seq-content-gc-plot_Read_2_After_filtering.png
├── mqc_fastp-seq-content-gc-plot_Read_2_Before_filtering.png
├── mqc_fastp-seq-content-n-plot_Read_1_After_filtering.png
├── mqc_fastp-seq-content-n-plot_Read_1_Before_filtering.png
├── mqc_fastp-seq-content-n-plot_Read_2_After_filtering.png
├── mqc_fastp-seq-content-n-plot_Read_2_Before_filtering.png
├── mqc_fastp-seq-quality-plot_Read_1_After_filtering.png
├── mqc_fastp-seq-quality-plot_Read_1_Before_filtering.png
├── mqc_fastp-seq-quality-plot_Read_2_After_filtering.png
├── mqc_fastp-seq-quality-plot_Read_2_Before_filtering.png
├── mqc_fastp_filtered_reads_plot_1.png
└── mqc_fastp_filtered_reads_plot_1_pc.png
```

Please could you try running with that example dataset? That should isolate whether it's a problem with your installation or something specific to your data.

**Comment by ewels** [comment]
Also, the log file was sadly not much more informative. I've just pushed a change to the code which gets MultiQC to log more information when stuff breaks in the way you've seen (debug level, so will go to `multiqc.log` and only show on the terminal if you used `-v`).

If you could pull the latest development code and rerun, that would help to try to track down what is going on.

**Comment by nicolettacommins** [comment]
Everything works after I pulled the development version. Thank you so much!

**Comment by ewels** [comment]
Huh, ok! Well that's good I guess 😆 

Let me know if you hit any problems again.. And thanks for getting back to me!
