### ISSUE TITLE
Number of reads above Q-score of 29

### ISSUE THREAD

**Issue by AllisonStander** [ewels/MultiQC#1048]
Good day,

I am working on a plant genome, three Illumina libraries: 1 PE, 2 MP.
I would like to report on the percentage of reads with a Phred score of 30 and above for each library.

Would the following method work: 1. Generate a MultiQC report from FastQC output. 2. Use the data from the per sequence quality scores plot to determine what percent is of a Phred score of 30 and above.

Kind regards,
Allison

**Comment by ewels** [comment]
Yup, should do! 👍 

Remember that MultiQC creates files in a `multiqc_data` directory. You should be able to load the relevant FastQC data into Excel to quickly calculate this number precisely if you want (easier than trying to figure it out from the plots in the report).

Shout if you run in to any problems..

**Comment by AllisonStander** [comment]
Thank you for the reply. So, just to make sure... 

If I download the data .tsv file from MultiQC of the per sequence quality plot, and get the following, I can calculate the sum of the reads from 30 and above, and divide by the sum of all reads. Am I understanding it correctly?

![Selection_999(421)](https://user-images.githubusercontent.com/35597033/68331179-337fb000-00dd-11ea-9963-667b9fb41ff7.png)
