### ISSUE TITLE
Illumina DRAGEN On-Premise

### ISSUE THREAD

**Issue by pellonen** [ewels/MultiQC#1055]
**Tool Details**
 - Name of tool: Dragen Bio-it on-premise
 - Tool homepage: https://emea.illumina.com/products/by-type/informatics-products/dragen-bio-it-platform.html#learn-more-onprem
 - Tool description: accelerated software/hardware package for alignment & variant calling
Dragen Enrichment, Dragen Germline, Dragen RNA pipe, Dragen Somatic pipe

 - Data suitable for MultiQC plot(s): GATK/SAMTOOLS equivalents
 - Most interesting data for General Stats table: SAMTOOL equivalents

Demo data available in BaseSpace, RNA example:
https://basespace.illumina.com/s/LucXlKME2uYC
Thanks, -pekka

**Comment by ewels** [comment]
I can't use the crappy BaseSpace downloader tool because it won't ask MacOS Catalina for permission to access the disk properly, so it says that I have 0 bytes available.

If you can download the log files locally, could you please make a pull-request to https://github.com/ewels/MultiQC_TestData with them please? (in a folder `data/modules/dragen`).

Thanks!

**Comment by ewels** [comment]
(not big BAM files etc, but all log files is fine)

**Comment by pellonen** [comment]
Hi,
Sorry, haven’t had time for this. Is this still relevant? Met John Wilson today at FIMM, he was presenting Dragen here, great stuff!
-Pekka

**Comment by ewels** [comment]
I can't write the module without example data, and I can't currently download the example data myself.. So this issue will be on hold until I can get a copy.. :)

Looking forward to hearing more about it in person!

**Comment by vladsaveliev** [comment]
Hi @ewels, we are started evaluating Dragen as well, and I was looking up if there is is a MultiQC module for it, so ended u here :) Attaching an example output for tumor/normal alignment and variant calling Dragen pipeline. 

[T_SRR7890936_50pc.tar.gz](https://github.com/ewels/MultiQC/files/3895507/T_SRR7890936_50pc.tar.gz)

I'm gonna take look if I can write up a module for this pipeline. I don't have an example for RNA yet - that's gonna be next.

Vlad

**Comment by ewels** [comment]
Ok fantastic! Thanks @vladsaveliev, looking forward to it..

**Comment by vladsaveliev** [comment]
Created a pull request, initiated the module with the support of tumor/normal variant calling pipeline: reporting on mapping metrics similar to `samtools stats`, coverage stats similar to `mosdepth` and `qualimap bamqc`, variant calling QC, runtime metrics, fragment size metrics and ploidy estimation.

**Comment by ewels** [comment]
Finished in #1098
