### ISSUE TITLE
RNA-SeQC output has changed

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#1059]
_Originally posted by @adomingues in https://github.com/ewels/MultiQC/issues/394#issuecomment-554961704_

---

Hi @ewels,

I am coming back to this issue because `RNAeq-QC` has been re-written in python, with some added functionality (https://github.com/broadinstitute/rnaseqc). Somehow the output directory structure also changed, which means that `multiqc` not longer produces a report:

```bash
multiqc .

[INFO   ]         multiqc : This is MultiQC v1.7
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
Searching 45 files..  [####################################]  100%          
/projects/conda/envs/multiqc/bin/multiqc:495: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logger.warn("No analysis results found. Cleaning up..")
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete

rnaseqc --version
RNASeQC 2.3.4
```
Are there any plans to modify multiqc's parsing to adapt to these changes?

cheers

**Comment by ewels** [comment]
Hi @adomingues,

I moved your reply in to a new issue to keep things separate, I hope that’s ok. Do you have a copy of the new output that I could see please? You should be able to zip a report and drop it on to this issue to upload.

Thanks,

Phil

**Comment by adomingues** [comment]
thanks for you patience @ewels. RNAseq-QC provides an example for the output in the repo:

https://github.com/broadinstitute/rnaseqc/tree/master/test_data/downsampled.output

It will generate of of those folders per bam file.

I hope this helps.

António

**Comment by m-ish** [comment]
Hey there!

I am working on a module for RNA-Seqc version 2 now - hope to have a PR soon.

Cheers!

Hamish

**Comment by ewels** [comment]
Ok great! Thanks for letting me know - looking forward to the PR  😀

**Comment by m-ish** [comment]
Here is the pull request! Feel free to rip it apart :) 
https://github.com/ewels/MultiQC/pull/1064

Cheers,

Hamish

**Comment by bw2** [comment]
+1 for merging this

**Comment by ewels** [comment]
I will do when I get to it :) I have a lot of open PRs at the moment and am working through them steadily from oldest to newest. When I'm back up to date I will do a new release. Reviewing PRs unfortunately can often take a lot of time and effort.

**Comment by ewels** [comment]
Rewritten and merged 🚀
