### ISSUE TITLE
Fastq Screen summation is messed up.

### ISSUE THREAD

**Issue by s-andrews** [ewels/MultiQC#106]
In your example report at:

http://multiqc.info/examples/rna-seq/multiqc_report.html#fastq_screen

..the fastq_screen report is messed up.  The "no hits" section has values of several thousand percent in it, which can't be right.

**Comment by ewels** [comment]
Hah, yes something is wrong there. Confusingly, the text output shows a zero count for `no hits`: http://multiqc.info/examples/rna-seq/multiqc_report_data/multiqc_fastq_screen.txt

This module generally needs a bit of a clean up - I made it display a different style of plots for reports with many samples, which shows the percentage of reads that align to each species. These are allowed to sum to > 100%, which is kind of confusing.

**Comment by ewels** [comment]
Ok, fixed in 7b5ed3024171e150467c890ae73640c35336a7a6 (example report you linked to is now fixed).

Actually found a worrying number of bugs in that module, so was well worth looking into. Thanks for reporting it!
