### ISSUE TITLE
Deeptools plotFingerprint: No analysis results found. Cleaning up.. 

### ISSUE THREAD

**Issue by castaway1990** [ewels/MultiQC#1062]
Hi everyone,

I am running MultiQC on `deeptools plotFingerprint --outRawCounts` file and it seems parser is not able to properly recognize [Fingerprint.txt](https://github.com/ewels/MultiQC/files/3867897/Fingerprint.txt) file as deeptools output.

**MultiQC Error log:**
```
/usr/local/lib/python3.6/dist-packages/multiqc/utils/config.py:45: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  configs = yaml.load(f)
/usr/local/lib/python3.6/dist-packages/multiqc/utils/config.py:51: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  sp = yaml.load(f)
[INFO   ]         multiqc : This is MultiQC v1.7
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
```

**MultiQC run details :**
 - Command used to run MultiQC: `multiqc . --filename outputTest`
 - MultiQC Version: 1.7
 - Operating System: CentOS Linux 7 (Core) / Ubuntu18.04
 - Python Version: Python 3.6
 - Method of MultiQC installation: conda

 **Additional context**
I am having the issue with both CentOS Linux 7 running on HPC and Ubuntu 18.04 singularity image running on the same HPC. Interestingly you can bypass the problem running MultiQC on the first 493007 rows of the file or removing 1 random column.

**Comment by ewels** [comment]
Hi @castaway1990,

Took me a little while to figure this out, but it's because your file is pretty large (`9.7MB`) so MultiQC is skipping it. You can override this behaviour by modifying your MultiQC config though: https://multiqc.info/docs/#big-log-files

This works fine:

```console
$ multiqc -f Fingerprint.txt --cl_config "log_filesize_limit: 2000000000"
[INFO   ]         multiqc : This is MultiQC v1.8.dev0 (bb2cdb0)
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching   : Fingerprint.txt
[INFO   ]       deeptools : Found 7 total deepTools samples
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete
```

**Comment by castaway1990** [comment]
Thanks ewels! Problem Solved
