### ISSUE TITLE
Custom content in general statistics table

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [ewels/MultiQC#1069]
I couldn't find it in the docs, but I want to add my own custom content, and have it displayed in the general statistics table at the start. Is this possible?

I tried adding a table like so:

```yaml
# section_name: 'Custom data file'
# description: 'This output is described in the file header. Any MultiQC installation will understand it without prior configuration.'
# format: 'csv'
# plot_type: 'table'
# pconfig:
#    id: 'custom_bargraph_w_header'
#    ylab: 'Number of things'
Sample Name,some feature
GSM2219688_pass_1,42
```

But then the resulting multiqc looks like this:
![image](https://user-images.githubusercontent.com/15323399/69862115-0d8f9a80-129a-11ea-984e-3af2d48fde4a.png)

Where unfortunately these tables are separate.

**Comment by ewels** [comment]
Sure - you want `plot_type: 'generalstats'`

There is a mention of this in the docs, but it's pretty well buried in an example: https://multiqc.info/docs/#data-as-part-of-multiqc-config

I need to rewrite the custom content docs, they're pretty terrible. I've made a new issue for this: https://github.com/ewels/MultiQC/issues/1070

Let me know how you get on!

Phil

**Comment by Maarten-vd-Sande** [comment]
Thanks for the reply. I'll know how to reach you if it doesn't work :see_no_evil:
