### ISSUE TITLE
Options for multiqc data

### ISSUE THREAD

**Issue by s-andrews** [ewels/MultiQC#107]
It would be nice if there were a couple of options for the multiqc data output to make it play more nicely with file base LIMS systems (like ours!)

1) An option to not generate this at all (which should be the default when doing STDOUT writing)

2) An option to zip this dir into a single file

Pretty please :-)

**Comment by ewels** [comment]
Yes - I've been thinking the same thing recently. I used to make a zip of the entire report but got rid of it when I made the HTML stand alone. I'll put it back in for the data as an option like you suggest.

**Comment by ewels** [comment]
I was just thinking about this and remembered that part 1) is already the case...

```
multiqc data/ -n stdout
```

For me, this doesn't save any files.. So I think I'll skip part 1) (people can always redirect stdout to a file if they want just the HTML without the data).

Part 2) - I think I'll include the HTML file in the zip as well if this is flagged so that the whole thing is bundled together. Any complaints?

**Comment by s-andrews** [comment]
I¹d probably prefer keeping the html file out of the zip to keep the
presentation and data separate, but actually if we can just skip the data
generation then that would probably do.

From:  Phil Ewels <notifications@github.com>
Reply-To:  ewels/MultiQC
<reply+007c7ae3b040ecc9a17718747a2139ddcb99e1dca35ddc6792cf00000001125c7d659
2a169ce06f2ba4f@reply.github.com>
Date:  Thursday, 12 November 2015 16:16
To:  ewels/MultiQC <MultiQC@noreply.github.com>
Cc:  Simon Andrews <simon@proteo.me.uk>
Subject:  Re: [MultiQC] Options for multiqc data (#107)


I was just thinking about this and remembered that part 1) is already the
case...
multiqc data/ -n stdout
For me, this doesn't save any files.. So I think I'll skip part 1) (people
can always redirect stdout to a file if they want just the HTML without the
data).

Part 2) - I think I'll include the HTML file in the zip as well if this is
flagged so that the whole thing is bundled together. Any complaints?


Reply to this email directly or view it on GitHub
<https://github.com/ewels/MultiQC/issues/107#issuecomment-156152656> .

**Comment by ewels** [comment]
Ok cool - in that case I'll close this issue as what you wanted is already done.

Best kind of feature request!

**Comment by s-andrews** [comment]
Is there an option to not generate data if not going straight to stdout then?  I didn't see that in the docs?

**Comment by ewels** [comment]
This should work:
```
multiqc data -n stdout > multiqc_report.html
```

Ok ok, I'll stop being lazy and reopen the issue... When would you want to use this option?

**Comment by ewels** [comment]
Hi @s-andrews - new option:

* Data directory is still created by default out of the box
* Default can be changed by modifying the `make_data_dir` option in a MultiQC config YAML files.
  * I realised these weren't documented anywhere. Now [written](http://multiqc.info/docs/#multiqc-config-settings)
* `--data-dir` and `--no-data-dir` command line options to override defaults

**Comment by ewels** [comment]
Oops, forgot the bit about zipping..

**Comment by ewels** [comment]
Ok, that should do it.. `-z` / `--zip-data-dir` creates a zip of the data directory and deletes the uncompressed dir.
