### ISSUE TITLE
Module for pycoQC

### ISSUE THREAD

**Issue by ssjunnebo** [ewels/MultiQC#1075]
**Tool Details**
 - Name of tool: pycoQC
 - Tool homepage: https://a-slide.github.io/pycoQC/
 - Tool description: PycoQC computes metrics and generates interactive QC plots for Oxford Nanopore technologies sequencing data
 - Data suitable for MultiQC plot(s): Plots related to read lengths
 - Most interesting data for General Stats table: read length N50, med read length and med read quality, number of reads

**Comment by ewels** [comment]
Thanks! You guys are actively working on this new module, right?

**Comment by ssjunnebo** [comment]
Yes, we got maybe halfway through during the hackathon. Will pick it up again soon.

**Comment by ewels** [comment]
Added in https://github.com/ewels/MultiQC/pull/1108

**Comment by caspargross** [comment]
Thanks for the implementation of the module.

Currently read length distribution has a linear scale
![grafik](https://user-images.githubusercontent.com/10211013/83491239-c33ddf00-a4b1-11ea-9902-c91a0c7f2ea7.png)

Personally, I think it would be better to display the read lenghts on logarithmic scale, similar to the internal PycoQC report:

![grafik](https://user-images.githubusercontent.com/10211013/83491412-013b0300-a4b2-11ea-86e8-cfa6ce32a0e2.png)

What is your opinion on this?

**Comment by hoelzer** [comment]
Hi, thanks for integrating pycoQC into MultiQC! But I think the module is not working at the moment? I tried to provide the HTML output of pycoQC to MultiQC v1.9 but this did not work

**Comment by ewels** [comment]
Hi @hoelzer,

PycoQC has not yet made it to a stable release of MultiQC I'm afraid (I'm struggling with the maintenance load currently, hoping to get a release out when I can though).

You can see it in the changelog for v1.10dev here: https://github.com/ewels/MultiQC/blob/master/CHANGELOG.md#multiqc-v110dev

You can install the development version with `pip` as follows:

```
pip install --force git+https://github.com/ewels/MultiQC.git
```

Phil

**Comment by hoelzer** [comment]
@ewels thanks for the information and for working on it. Totally understandable!
