### ISSUE TITLE
MultiQC is not plotting Mean and Median coverage for Qualimap

### ISSUE THREAD

**Issue by CuriusScientist** [ewels/MultiQC#1077]
**Description of the bug:**

MultiQC is not plotting Mean and Median coverage for Qualimap, which is surely present as shown by the Qualimap report for one of the samples

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC:  `multiqc ./`
 - MultiQC Version:  MultiQC v1.8
 - Quyalimap Version:  v.2.2.2-dev
 - Operating System: Ubuntu
 - Python Version: Python 3.7.3
 - Method of MultiQC installation: Conda

 **Additional context**
![M - 1](https://user-images.githubusercontent.com/9574057/70427528-2dcb1080-1a75-11ea-9626-63112fc3c33e.jpeg)
![Q - 1](https://user-images.githubusercontent.com/9574057/70427530-2dcb1080-1a75-11ea-96c2-477c25fcae09.jpeg)

**Comment by ewels** [comment]
Thanks for this @CuriusScientist - I think that there is something wrong with this code. See also https://github.com/ewels/MultiQC/issues/1082

I'm away for Christmas holidays now but @apeltzer (who wrote the new code for the mean coverage calculation) is hoping to have a look. Otherwise I'll look in to this as soon as I get a chance.

Is it possible for you to attach one of these Qualimap reports? The more examples we have where this is failing the better.

Thanks,

Phil

**Comment by apeltzer** [comment]
Hi @CuriusScientist ! I'll communicate the bugfixing in the other thread - if you want /  can share some data, please do 👍

**Comment by apeltzer** [comment]
Please see #1085 for a proposed fix for this.

**Comment by CuriusScientist** [comment]
@ewels I see that you have fixed and merged the branch "apeltzer:fix-qualimap" #1085

In order to get the latest version, I followed the following steps

-  Downloaded MultiQC from github

- Ran successfully "pip install MultiQC-master.zip"
Successfully built multiqc
Installing collected packages: multiqc
Successfully installed multiqc-1.9.dev0

- multiqc ./
[INFO ] multiqc : This is MultiQC v1.9.dev0
[INFO ] multiqc : Template : default
[WARNING] multiqc : You are running MultiQC with Python 2.7.16
[WARNING] multiqc : Please upgrade! MultiQC will soon drop support for Python < 3.6
[INFO ] multiqc : Searching : /Users/nitinsharma/Documents/00_Work_Projects/ULP-WGS_Bravo/QualiMap
Searching 801 files.. [####################################] 100%
[INFO ] qualimap : Found 8 BamQC reports
[INFO ] multiqc : Compressing plot data
[INFO ] multiqc : Report : multiqc_report.html
[INFO ] multiqc : Data : multiqc_data
[INFO ] multiqc : MultiQC complete

**But I can't get the mean coverage** 
<img width="1911" alt="Screenshot 2020-04-30 at 10 08 00" src="https://user-images.githubusercontent.com/9574057/80687788-1f849c00-8acb-11ea-8104-7829e250981e.png">

what am I missing here

**Comment by ewels** [comment]
Hi @CuriusScientist,

No need to download like that, you can just run `pip install --upgrade --force-reinstall git+https://github.com/ewels/MultiQC.git` ([readme](https://github.com/ewels/MultiQC#installation), [docs](https://multiqc.info/docs/#updating-multiqc)).

Can you please attach a single Qualimap report where this isn't working so that we can replicate your problem? In my testing for #1085 the fix worked fine.

Thanks,

Phil

**Comment by CuriusScientist** [comment]
@ewels what files shall I send you in order for you check if there is an error or if I am doing something wrong

**Comment by apeltzer** [comment]
The `multiqc_report.html` would be great to see :+1:

**Comment by CuriusScientist** [comment]
[multiqc.zip](https://github.com/ewels/MultiQC/files/4624377/multiqc.zip)

.html files are not supported by Github so I have added all the files and zipped it

**Comment by apeltzer** [comment]
Can you also share the `genome_stats.txt` files from QualiMap?

**Comment by CuriusScientist** [comment]
[genome_results1.txt](https://github.com/ewels/MultiQC/files/4624439/genome_results1.txt)
[genome_results2.txt](https://github.com/ewels/MultiQC/files/4624441/genome_results2.txt)
[genome_results3.txt](https://github.com/ewels/MultiQC/files/4624442/genome_results3.txt)
[genome_results4.txt](https://github.com/ewels/MultiQC/files/4624443/genome_results4.txt)

@apeltzer I have attached 4 sample files. I think that should be good enough but do let me know if you need anything else

**Comment by apeltzer** [comment]
Found the problem. The regex doesn't work if its too low coverage. I'll push a fix in a separate PR for you to test and also include one of your example files in the MultiQC_TestData repository.

**Comment by apeltzer** [comment]
Would be cool to get the other test files (html report, etc pp from qualimap too to include in the testdata).

**Comment by ewels** [comment]
Hopefully fixed now ✅ Thanks both!
