### ISSUE TITLE
QualiMap mean coverage

### ISSUE THREAD

**Issue by BaiqiFu** [ewels/MultiQC#1082]
**Description of bug:**
Qualimap: mean coverage computation for general statistics seems incorrect.

**MultiQC Error log:**
MultiQC Report: 
![image](https://user-images.githubusercontent.com/24837267/70895665-4e253d00-202a-11ea-863c-f577c0691dd0.png)

QualiMap Report (CG_R): 
![image](https://user-images.githubusercontent.com/24837267/70895714-5e3d1c80-202a-11ea-9fb0-dc23a793578e.png)

**File that triggers the error:**
see [example_data.zip](https://github.com/ewels/MultiQC/files/3967176/example_data.zip)

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC: `/data1/software/python/3.8.0/bin/multiqc --force --filename xx --outdir . bamqc/*_bamqc`
 - MultiQC Version: [MultiQC v1.8]
 - Operating System: [CentOS 7]
 - Python Version: [Python 3.8.0]
 - Method of MultiQC installation: [pip]

**Comment by ewels** [comment]
Hmm, @apeltzer - any ideas what is going on here?

**Comment by apeltzer** [comment]
Not really but I can check - code doesn't show this behaviour easily...

**Comment by apeltzer** [comment]
Ok, just so to give an update on this one here. I double-checked using the https://github.com/ewels/MultiQC_TestData/tree/master/data/modules/qualimap testdata:

QualiMap Report:
<img width="800" alt="Bildschirmfoto 2019-12-18 um 09 36 19" src="https://user-images.githubusercontent.com/2359510/71070153-79b73d00-217a-11ea-8770-8065bb209a9e.png">

MultiQC Report:
<img width="1581" alt="Bildschirmfoto 2019-12-18 um 09 36 25" src="https://user-images.githubusercontent.com/2359510/71070025-3361de00-217a-11ea-8974-4890ab4935d9.png">

Other sample:
<img width="805" alt="Bildschirmfoto 2019-12-18 um 09 36 46" src="https://user-images.githubusercontent.com/2359510/71070104-555b6080-217a-11ea-8625-6bd5a47acd6e.png">
<img width="1104" alt="Bildschirmfoto 2019-12-18 um 09 39 56" src="https://user-images.githubusercontent.com/2359510/71070117-5e4c3200-217a-11ea-963e-c1e10ff470a1.png">

As QualiMap doesn't provide `median` values, I can't compare these directly to what it computes but the outputs don't look weird/off for me 👎 

Maybe QualiMap produces slightly different output now and didn't in the past? Need to check that too...

**Comment by apeltzer** [comment]
Please see #1085 for a proposed fix for this.

**Comment by BaiqiFu** [comment]
Hello!

Thank you very much for your reply！

But this bug seems to still exist in my other projects.

BamQC:
[bamqc.zip](https://github.com/ewels/MultiQC/files/4033409/bamqc.zip)

MultiQC:
[multiqc.zip](https://github.com/ewels/MultiQC/files/4033414/multiqc.zip)

Command:
/data1/software/python/3.8.0/bin/multiqc --force --filename wheat_multi-bamqc --outdir multiqc bamqc/*_bamqc

MultiQC Version: 

1) pip install --upgrade --force-reinstall git+https://github.com/ewels/MultiQC.git

2) https://github.com/apeltzer/MultiQC/tree/fix-qualimap

The above two versions are not correct.

So how do I choose the version?

**Comment by ewels** [comment]
Hi @BaiqiFu,

The PR to fix this was only merged a few weeks ago - I'm not entirely sure which version you were running, but either way it seems fixed to me now. See an example report that I just generated with the latest version of the code using your `bamqc.zip` data: [multiqc_report.html.zip](https://github.com/ewels/MultiQC/files/4671777/multiqc_report.html.zip)

This should now work with the latest v1.9dev code (the install command `1` from your post above will install this now), and will be released properly soon.

Let me know if you're still having problems,

Phil

**Comment by BaiqiFu** [comment]
Hi

Now I am using the v1.9，this version works very well without problems!
Thank you very much for your work!

**Comment by ewels** [comment]
Ok great! Thanks for letting us know :)
