### ISSUE TITLE
Reads vs. Fragments vs. Seqs: inconsistent usage

### ISSUE THREAD

**Issue by freekvh** [ewels/MultiQC#1088]
**Is your feature request related to a problem? Please describe.**
The terms Reads and Fragments are not consistently used throughout MultiQC.

**Describe the solution you'd like**
When doing paired-end sequencing, the number of reads is twice the number of fragments sequenced, some QC modules (like RSEM: Mapped reads) actually report fragments, these fragments are called "Seqs" (of M Seqs) in "General Statistics". The RSeQC module "Read Distribution" does report reads, as its title suggests. It can be confusing of you are not aware of this.

**Describe alternatives you've considered**
I have been making tables manually listing everything as fragments (I was checking where I "loose" fragments/reads).

**Comment by ewels** [comment]
Whilst I appreciate that this can be confusing, I have a policy here already: I try to maintain consistency with the underlying tool. I think that this is better and certainly easier for developing code. It can be very easy to make errors when converting between the two if you’re not totally sure of exactly what the tool is doing.
