### ISSUE TITLE
Multiqc does not report reverse strand QC from fastp 

### ISSUE THREAD

**Issue by ndu-UCSD** [ewels/MultiQC#1093]
I used fastp for QC/trimming paired end RNA seq fastq files and only forward strand QC showed up

![Picture1](https://user-images.githubusercontent.com/23390377/72005576-c387c600-3202-11ea-8408-640d71b1bd43.png)

[fastp.json.zip](https://github.com/ewels/MultiQC/files/4036728/fastp.json.zip)

Multiqc version 1.8

**Comment by ewels** [comment]
Hi @ndu-UCSD,

Fastp JSON files contain data for both reads if you run it in paired-end mode. I checked a report with your file and I get a section for insert size, so it must have data for both reads. I think that this is just a sample naming issue.

You can remove the `_R1` from your sample names with the following MultiQC config:

```yaml
extra_fn_clean_trim:
    - '_R1'
```

See https://multiqc.info/docs/#sample-name-cleaning for more.

Let me know if you have any problems with this and I can reopen the issue. Sorry for the slow response.

Phil
