### ISSUE TITLE
General stats and bcl2fastq

### ISSUE THREAD

**Issue by nservant** [ewels/MultiQC#1094]
Hi @ewels,
We have a different behavior in the multiqc report using version 1.6dev and 1.7/1.8, and the `bcl2fastq` module. The difference occurs in the general stats table.

We have a single sample, with 4 barcodes.
Using multiqc 1.6dev, the general stats table reported the 4 barcodes independantly.

![image](https://user-images.githubusercontent.com/10778219/72078808-109a9380-32fa-11ea-9482-bb253d69af8c.png)

With the multiqc 1.7 and 1.8, the barcodes are merged (as the belong to the same sample), but the number are false. It display the last barcodes only.

![image](https://user-images.githubusercontent.com/10778219/72078861-2c059e80-32fa-11ea-97e9-985c075f5f8d.png)

Did you already observed that before ? and would have any idea of what's going wrong ?
Many thanks

**Comment by nservant** [comment]
I'm adding the bcl2fastq zip files if it helps
[Stats.json.zip](https://github.com/ewels/MultiQC/files/4041037/Stats.json.zip)

**Comment by matrulda** [comment]
I've encountered this problem too and found a bug in the code. 
https://github.com/ewels/MultiQC/blob/964e9993505c64ad95a7914a8c4f60eed499aa0d/multiqc/modules/bcl2fastq/bcl2fastq.py#L177
It should compare `SampleName` with `SampleId`, not `SampleName` with `SampleName` which always is true. I'll submit at PR to fix this.

**Comment by nservant** [comment]
wonderful ! Thanks

**Comment by ewels** [comment]
Sorry for the slow response @nservant and thanks for the fix @matrulda - now merged so should be fixed in the dev version 👍🏻

**Comment by matrulda** [comment]
No problem! :)
