### ISSUE TITLE
Run multiqc with samblaster

### ISSUE THREAD

**Issue by efratushava** [ewels/MultiQC#1097]
Hello,

I couldn't understand from the documentation- which files are required for running multiqc on samblaster results?

Thank you!

**Comment by ewels** [comment]
Hi @efratushava,

I guess that it's just the standard-out from the tool. You can see example files here: https://github.com/ewels/MultiQC_TestData/tree/master/data/modules/samblaster

You can redirect stdout to a file using the `>` character. See [this blog post](https://thoughtbot.com/blog/input-output-redirection-in-the-shell) for more details.

I you found this confusing then I can almost guarantee that some other people have also found it confusing 😄 Would be great if you could open a pull-request to improve the [samblaster documentation](https://multiqc.info/docs/#samblaster)! You can find the source file [here](https://github.com/ewels/MultiQC/blob/master/docs/modules/samblaster.md).

Closing the issue now, but let me know if this didn't solve your problem and I can reopen. Apologies for the slow response time.

Phil
