### ISSUE TITLE
The FastQC module broke

### ISSUE THREAD

**Issue by silvia-s** [ewels/MultiQC#1100]
**Description of bug:**
While running MultiQC on 242 reports I got the following error (N.B. I've replaced the my very long paths with "/path/to/ for brevity):

```
[INFO   ]          fastqc : Found 242 reports
[ERROR  ]         multiqc : Oops! The 'fastqc' MultiQC module broke... 
                    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
                    (if possible, include a log file that triggers the error) 
============================================================
Module fastqc raised an exception: Traceback (most recent call last):
  File "/path/to/multiqc", line 346, in multiqc
    output = mod()
  File "/path/to/fastqc.py", line 91, in __init__
    self.fastqc_general_stats()
  File "/path/to/fastqc.py", line 200, in fastqc_general_stats
    'avg_sequence_length': bs['avg_sequence_length'],
KeyError: 'avg_sequence_length'
============================================================
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
```

**File that triggers the error:**
I can't share the fastqc files I was processing, sorry.

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC: `multiqc -l filelist.txt -n multiqc_ouput.html --no-data-dir --interactive`
 - MultiQC Version: version 1.0.dev0
 - Operating System: Ubuntu 18.04.3 LTS
 - Python Version: Python 2.7.17
 - Method of MultiQC installation: conda

 **Additional context**
I managed to run MultiQC in the past with an even larger number of input FastQC reports, so that's not probably the reason that broke it. Any idea?

Thanks!

**Comment by ewels** [comment]
Hi @silvia-s,

I guess that your FastQ file is empty and the report is a bit odd as a result. Also reported in https://github.com/ewels/MultiQC/issues/1129

Let me know if this is not the case and I will reopen the issue. I intend to add a nicer warning message / simply skip the file if this is found in a future release.

Phil

**Comment by silvia-s** [comment]
Hi @ewels,

You're right, I seem to remember that in the end the error was probably caused by one of the 242 FASTQ files being empty. Something must have failed already during sequencing for that sample (which had very few reads) and when I ran MultiQC after the adapter/quality trimming step there were no reads left. 

I think both adding a warning message and skipping any empty files would be very helpful, thank you!

Best,
Silvia

**Comment by ewels** [comment]
Great, thanks for getting back to me and confirming!
