### ISSUE TITLE
hicexplorer updated report

### ISSUE THREAD

**Issue by LeilyR** [ewels/MultiQC#1103]
Hi @ewels ,
Last year, we were dynamically updating hicexplorer QC report. That was also the reason for the #1061 issue. In fact with hicexplorer > 3 we have a new format which I have already taken care of its multiqc report in my local fork. I wonder If you expect us to keep support for all the older reports too, or it is fine by you if we only mention in the documentation that which versions of hicexplorer are compatible with which multiqc versions. 
Best,
Leily

**Comment by LeilyR** [comment]
We updated our report in way to be able to handle all different versions of hicexplorer and sent  #1109. So I close this issue.

**Comment by ewels** [comment]
Hi @LeilyR,

Sorry for the slow reply. Generally I prefer to maintain support for older versions of tools where practical. However if the expectation is that there will be very few users of the old version (eg. it wasn’t out for long) or it’s too much work then I’m happy to skip that.

Sounds like you managed to maintain support though, which is great! Thanks!

Phil
