### ISSUE TITLE
typo in multiqc_picard_varientCalling outputs

### ISSUE THREAD

**Issue by mgonzalezporta** [ewels/MultiQC#1105]
**Description of bug:**
Picard variant calling metrics are correctly parsed by multiqc but there is a typo in the outputs: module string is `multiqc_picard_varientCalling` instead of `multiqc_picard_varientCalling`.
The error is triggered here:
https://github.com/ewels/MultiQC/blob/master/multiqc/modules/picard/VariantCallingMetrics.py#L29

**MultiQC Error log:**
NA

**File that triggers the error:**
NA

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC: [eg. `multiqc .`]
 - MultiQC Version: MultiQC v1.8
 - Operating System: CentOS 6
 - Python Version: Python 3.7.6
 - Method of MultiQC installation: conda

 **Additional context**
NA

**Comment by ewels** [comment]
Good spot, thank you @mgonzalezporta! Would be fab if you could open a pull-request to fix this, otherwise I will get to it when I can.

Phil

**Comment by cpavanrun** [comment]
I take solace in that the report had the typo twice as well =P
