### ISSUE TITLE
Allow specifying files as well as directories

### ISSUE THREAD

**Issue by s-andrews** [ewels/MultiQC#111]
Would it be possible to specify a set of files rather than (or as well as) directories.

I've had a couple of times now where I only want to process one subset of files in a folder and couldn't see an easy way to do that.

**Comment by ewels** [comment]
Yup, I think this should be possible. Will need to have a think about how to implement it though.

What happens when you give it files instead of directories now? Not sure that I've ever tried it..

**Comment by ewels** [comment]
Answer to my own question - nothing, they were just skipped.

Anyway, this update makes MultiQC work with files and directories @s-andrews - let me know if you find any problems with it...
