### ISSUE TITLE
Samtools Idxstats - Additional Normalisation Plot

### ISSUE THREAD

**Issue by StephenRicher** [ewels/MultiQC#1118]
Hi,

First off thanks very much for this fantastic tool! I was wondering if it would it be possible to represent the `samtools idxstats` output with an additional plot normalised by chromosome/contig length and by total read count?

As I understand the current normalised count is normalised by sequencing depth for comparison between samples.

However, I think it would be really cool to have an additional normalisation plot that also normalises by contig length in addition to total read count.  This would enable comparison between samples but also enable a quick assessment of any contigs that have higher coverage than expected.

Thanks and I look forward to hearing your thoughts,

Stephen

**Comment by ewels** [comment]
Hi @StephenRicher,

I think this is a great idea! We already have a plot normalising by total read count, so I guess you mean normalising both of those measures at once? Essentially adding a third plot tab here:

![image](https://user-images.githubusercontent.com/465550/77843582-e214b200-719e-11ea-8020-faaf0c205014.png)

I agree that this would be more helpful as it's typically what people are looking for in this plot 👍 

Fancy having a stab at it? 😉 

Phil

**Comment by StephenRicher** [comment]
Hi Phil,

Thanks very much for your email, sure I am happy to have a go! :)

Thanks,
Stephen

**Comment by ewels** [comment]
Closed in #1140
