### ISSUE TITLE
SortMeRNA log format changed in 4+

### ISSUE THREAD

**Issue by bschiffthaler** [ewels/MultiQC#1121]
**Description of bug:**
SortMeRNA module fails due to log file parser in SortMeRNA 4+

**MultiQC Error log:**
```

Oops! The 'sortmerna' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issu
es 
  If possible, please include a log file that triggers the error - the last file found was:
    ./sortmerna/out/aligned.log
============================================================
Module sortmerna raised an exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/multiqc-1.9.dev0-py3.6.egg/multiqc/multiqc.py
", line 546, in run
    output = mod()
  File "/usr/local/lib/python3.6/dist-packages/multiqc-1.9.dev0-py3.6.egg/multiqc/modules/so
rtmerna/sortmerna.py", line 30, in __init__
    self.parse_sortmerna(f)
  File "/usr/local/lib/python3.6/dist-packages/multiqc-1.9.dev0-py3.6.egg/multiqc/modules/so
rtmerna/sortmerna.py", line 85, in parse_sortmerna
    self.sortmerna[s_name]["rRNA_pct"] = float(self.sortmerna[s_name]["rRNA"]) / float(self.
sortmerna[s_name]["total"]) * 100
KeyError: 'total'
============================================================
Collapse

```

**File that triggers the error:**
[P11562_110_S9_L001_subset-aligned.log](https://github.com/ewels/MultiQC/files/4307973/P11562_110_S9_L001_subset-aligned.log)

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC: `multiqc .`
 - MultiQC Version: MultiQC v1.9-dev
 - Operating System: `Linux 4.15.0-88-generic #88-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux`
 - Python Version: 3.6
 - Method of MultiQC installation: manual

I am aware of this and opening an issue for this. I will fix it whenever I have time (which might honestly be not happen before June, due to an already very dense schedule). Should be an easy fix 1-2h max if anyone else wants to have a go.

**Comment by ewels** [comment]
Thanks for reporting this @bschiffthaler - so you're saying that the problem is that the log file format has changed? A PR would be great when you have time 👍

**Comment by zh542370159** [comment]
I have the same problem. So I  modified the sortmerna parse module file:
**~/anaconda3/pkgs/multiqc-1.8-py_2/site-packages/multiqc/modules/sortmerna/sortmerna.py**
Below is the modified code.
[sortmerna.py.txt](https://github.com/ewels/MultiQC/files/4426041/sortmerna.py.txt)

**Comment by ewels** [comment]
Nice - thank you @zh542370159! If you're able to make a pull-request with those changes that would be great, then we can discuss using GitHub's review tools 👍 

See https://guides.github.com/activities/forking/ if you're new to this 👨‍🎓 

Phil
