### ISSUE TITLE
RSeqC junction saturation onclick behavior is "incompatible" with toolbox (rename,highlight,hide)

### ISSUE THREAD

**Issue by sergpolly** [ewels/MultiQC#1133]
**Description of bug:**
RSeqC junction saturation section has an interactive `onclick` functionality - but it is incompatible with the MultiQC toolbox:
1. `renaming samples` renames them in the overview only - in the `onclick` they are not renamed
2. when toolbox operation is applied while "side-by-side" view is active, overview gets redrawn but "side-by-side" stays there
2. same applies for highlight/hide

please checkout this gif for clarification:
![newnew](https://user-images.githubusercontent.com/6790270/77709362-305c6200-6fa1-11ea-9428-24175ef057fd.gif)

in this gif I check out untouched overview first, check unperturbed side-by-side, and after that try to apply some renaming and also clear the renaming while side-by-side is open

**MultiQC Error log:**

does not apply - I guess as it is just the interactive javascript issue

**File that triggers the error:**
I use test data for RSeqC: `MultiQC_TestData/data/modules/rseqc`

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC: `multiqc --module rseqc --outdir ./ ./MultiQC_TestData/data/modules/rseqc`
 - MultiQC Version: v1.9.dev0 (2e16d7e) [latest from `master`]
 - Operating System: Ubuntu 18.04.1
 - Python Version: Python 3.7.2
 - Method of MultiQC installation: pip

 **Additional context**
First of, thank you for developing MultiQC - it is a really great tool/platform ! great docs !
I'm actually trying to develop a new module - and I was going to copy/paste some of that JavaScript stuff from RSeqC for my module (e.g. http://ummsres37.ad.umassmed.edu:8080/trash/multiqc_report.html#scalings-plots) - doing this I discovered reported misbehavior.

I'm going to PR a fix for this minor RSeqC issue, and see how my JavaScript understanding aligns with "reality"

**Comment by ewels** [comment]
Thanks @sergpolly - you're finding quite a few good ones here!

**Comment by ewels** [comment]
Fixed in #1134
