### ISSUE TITLE
heatmap plotting function is incompatible with toolbox's hide/highlight

### ISSUE THREAD

**Issue by sergpolly** [ewels/MultiQC#1136]
**Description of bug:**
built-in `heatmap` plotting function is incompatible with the MultiQC toolbox, specifically `highlight` and `hide` functionality - at times it wouldn't hide anything or wouldn't hide what it is supposed to hide, and highlight seem to "break" heatmap altogether sometimes - please check out screencast for clarification:
![heatmap_bug](https://user-images.githubusercontent.com/6790270/77838790-017ef100-7145-11ea-8bb3-aa51f784b984.gif)

in this gif I try to hide `SRR` pattern (nothing gets hidden apart from broken labels), then undo it, then try to hide other pattern - something "bad" happens)) i undo it; then i try to highlight a couple of groups, first nothing happens, then it "breaks", then I try to sort - it just goes crazy at that point .

**MultiQC Error log:**
does not apply - it is just an interactive javascript issue

**File that triggers the error:**
This bug is relevant for any report using the built-in [`heatmap`](https://multiqc.info/docs/#heatmaps) function - I used "FastQC Status Check" for demonstration: `MultiQC_TestData/data/modules/fastqc`

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC: `multiqc --module fastqc --outdir ./ ./MultiQC_TestData/data/modules/fastqc`
 - MultiQC Version: v1.9.dev0 (2e16d7e) [latest from `master`]
 - Operating System: Ubuntu 18.04.1
 - Python Version: Python 3.7.2
 - Method of MultiQC installation: pip

**Additional context:**
I think i was able to figure it out, so PR is coming ...

**Comment by ewels** [comment]
Fixed in #1137
