### ISSUE TITLE
MarkDuplicates/biobambam2 metrics interpretation issue

### ISSUE THREAD

**Issue by gt1** [ewels/MultiQC#1142]
**Description of bug:**
The metrics tables produced by Picard's MarkDuplicates and biobambam2's bamsormadup contain some columns referring to read pairs and some which refer to single reads. MultiQC currently does not distinguish between these and puts them together in a single bar plot.

**MultiQC Error log:**
There is no error in the output file. The result plot is wrong.

**File that triggers the error:**
[metrics.txt](https://github.com/ewels/MultiQC/files/4407747/metrics.txt)

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC: multiqc
 - MultiQC Version: 1.9
 - Operating System: Ubuntu 19.10
 - Python Version: Python 3.7.5
 - Method of MultiQC installation: manual via git clone

 **Additional context**

* Referring to single reads:
    * `UNPAIRED_READS`
    * `UNMAPPED_READS`
    * `UNPAIRED_READ_DUPLICATES`
* Referring to read pairs:
    * `READ_PAIRS_EXAMINED`
    * `READ_PAIR_DUPLICATES`
    * `READ_PAIR_OPTICAL_DUPLICATES`

**Comment by ewels** [comment]
Ah, the code comment that I wrote 4 years ago finally comes around 😅 

https://github.com/ewels/MultiQC/blob/9cf37d7d2302dcd349c97bea27599c757c1e8f54/multiqc/modules/picard/MarkDuplicates.py#L94-L101

So I guess the fix is to divide `UNPAIRED_READS`, `UNMAPPED_READS` and `UNPAIRED_READ_DUPLICATES` by two?

Is there a reliable way to know whether the log file is from a paired-end or single-end dataset?

Phil

**Comment by gt1** [comment]
I would suggest to multiply the PAIR fields by two as the graph reports actual numbers as well as percentages and half a read sounds weird.

I don't think there is an absolutely reliable way to determine from the metrics file wether the data is paired-end or single-end. But you could always take a chance and assume that it is highly unlikely for a dataset to be paired end but the READ_PAIRS_EXAMINED field still being zero (i.e. sequencing was paired end but not a single read pair has both ends aligned).

Best,
German

**Comment by ewels** [comment]
> Is there a reliable way to know whether the log file is from a paired-end or single-end dataset?

Looking at your code in #1143, I don't think that we need to know. As long as we are doubling and not halving then the unpaired read counts are unaffected so totally valid for single-end data.. 👍

**Comment by ewels** [comment]
Closed in #1143
