### ISSUE TITLE
Report Recreation with multiqc-parsed data in '--data-dir'

### ISSUE THREAD

**Issue by your-highness** [ewels/MultiQC#1145]
**Is your feature request related to a problem? Please describe.**
In our routine diagnostic setting we are obliged to save as minimal data as possible for a tested indivdual. Sophisticated QC reports from multiple tools are generated during bioinformatic analysis and combined to one custom MultiQC report. The QC reports output from the original tools are not archived. When running multiqc in the parsed `--data-dir` I get the following output and no multiqc report is generated`because no analysis results are found:

```{bash}
multiqc_report_data$ multiqc .
[WARNING]         multiqc : MultiQC Version v1.8 now available!
[INFO   ]         multiqc : This is MultiQC v1.7
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
Searching 6 files..  [####################################]  100%          
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
```

**Describe the solution you'd like**
I would like to be able to re-generate the original multiqc report with the already parsed data in `--data-dir`. All the needed data is already parsed into `--data-dir`.

**Describe alternatives you've considered**
Alternatively, I could re-create all QC reports and combine them again with multiqc. However, this is a timely endavour. All the needed data is already parsed into `--data-dir`.

**Additional context**
Thanks @ewels for your efforts in developing this great program ! It means alot to the whole community !

**Comment by ewels** [comment]
Hi @your-highness,

You're not the first person to ask for this, but unfortunately it is not a trivial thing to write. Probably the easiest way to do this is to use [MegaQC](https://github.com/ewels/MegaQC) which takes the `multiqc_data.json` file and replicates plots and data. Currently there is no way to regenerate a MultiQC report from this file though. It should be possible I _think_, but it would need a lot of new code.

I don't completely understand your use case to be honest. Why do you need to regenerate the report? I don't really get why you have the data directory from the initial run and not the HTML report?

Phil

**Comment by your-highness** [comment]
Ok. This feature sounds like alot of work - unfortunately. I thought the data_dir is kind of a proxy between steps "gather the data from available reports" and "combine the data to html". 

Going to check out MegaQC.

I keep the multiqc html and data directory to regenerate reports if needed, _e.g._ when grouping several samples for validation purposes of a new diagnostic test.

**Comment by ewels** [comment]
Unfortunately not. The JSON file mentioned does capture most, if not all, of the intermediate data state you describe but when you start getting into the details it gets complicated. MultiQC modules generate plots and report sections as they run, so if you merge multiple runs then you'd end up with the same module section repeated in the report a bunch of times which is probably not what is wanted. To combine those plots you have to recompute everything in the module, which requires saving all of the original data. If you're saving all of the original data, then, well, you may as well just save all of the original data 😄 

The other files in the `multiqc_data` directory do save some summary data, but it's very often not all of the data used by the module in the report - just summary metrics. This is partially limited by the fact that it's a flat CSV file by default, so difficult to handle more complex data structures.

Sorry I can't be more help - let me know if you run into problems and there's anything I can do.

Phil
