### ISSUE TITLE
Docker ewels/multiqc

### ISSUE THREAD

**Issue by modihardik** [ewels/MultiQC#1157]
Hi,
I am running latest version of ewels/multiqc, v1.8. Seems like it did run fine and got following log:

```
[INFO   ]         multiqc : This is MultiQC v1.8
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Report title: Data_Report
[INFO   ]         multiqc : Searching   : /home/Data/ProcessedData
[INFO   ]          picard : Found 10 AlignmentSummaryMetrics reports
[INFO   ]          picard : Found 10 InsertSizeMetrics reports
[INFO   ]          picard : Found 10 MarkDuplicates reports
[INFO   ]          picard : Found 10 RnaSeqMetrics reports
[INFO   ]          salmon : Found 10 meta reports
[INFO   ]          salmon : Found 10 fragment length distributions
[INFO   ]            star : Found 10 reports and 10 gene count files
[INFO   ]        cutadapt : Found 17 reports
[INFO   ]          fastqc : Found 17 reports
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : Data_Report_multiqc_report.html
[INFO   ]         multiqc : Data        : Data_Report_multiqc_report_data
```

It did generated "report" folder, but got following log

```
[INFO   ]         multiqc : This is MultiQC v1.8
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Report title: Data_Report
[INFO   ]         multiqc : Searching   : /home/Data/ProcessedData/report
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
```

Seems like this might be related to `log_filesize_limit: 2000000000`.

So my question is _"Is this related to file size and if so how to set this parameter in docker file?"_
Sorry this might seem trivial and newbie question.

Thank you for your help and great work.

**Comment by ewels** [comment]
Hi @modihardik,

I'm slightly confused about the steps that you are taking here. You mean that MultiQC is picking up some files correctly but not the logs from the `/home/Data/ProcessedData/report` folder? What is in there?

The docs for this kind of problem are here: https://multiqc.info/docs/#not-enough-samples-found - I guess this is what you found. Are you getting the verbose log messages `Ignoring file as too large`?

Details about how to configure MultiQC are here: https://multiqc.info/docs/#configuring-multiqc - for Docker remember that you have to be careful about bind paths. If you'd like more help then please post the commands that you are using.

Thanks,

Phil

**Comment by modihardik** [comment]
Hi Phil,

I was using latest version of docker ewels/multiqc. As you suggested it was bind path problem. It did ran and generated full HTML report.

Thank you for quick reply.
Best,
Hardik

**Comment by ewels** [comment]
Great, glad you got it sorted!
