### ISSUE TITLE
MultiQC docker container fails using Nextflow with AWS but works locally

### ISSUE THREAD

**Issue by avsastry** [ewels/MultiQC#1165]
**Description of bug:**
I've noticed a weird issue with the ewels/MultiQC docker image. When I run the process locally, there is no issue. When I run it using AWS batch as the executor, the external process fails without giving any indication of what went wrong. The .command.sh file is exactly what I'd expect, and there is no .command.out or .command.err file.

In addition, if I change the container to biocontainers quay.io container it works fine on AWS batch: https://quay.io/repository/biocontainers/multiqc

I know a simple work-around would be to use that image, but I have a custom module that I'd like to include in my MultiQC output, and I don't think quay reports the Dockerfile so I'm not sure what base image would work.

I also tried rebuilding the image using python:3.8-slim as the base image and it still failed.

Any idea of what could be happening here?

**MultiQC Error log:**
None

**File that triggers the error:**
Here is a simple pipeline that works when using "-profile local" but fails when using "-profile aws":

main.nf:

```
#!/usr/bin/env nextflow

process multiqc {

    container 'ewels/multiqc:latest'

    script:
    """ 
    multiqc -f .
    """
}
```
nextflow.config
```
docker.enabled = true
profiles {
    
    local {
        process.executor = 'local'
    }   


    aws {
        process.executor = 'awsbatch'
        process.queue = 'nextflow-default' // Need to update this for your queue
        aws.region = 'us-east-2'
        batch.cliPath = '/home/ec2-user/miniconda/bin/aws'
    }
}
```

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC: `nextflow run main.nf -profile aws`
 - MultiQC Version: [MultiQC v1.8]
 - Operating System: [Ubuntu 18.04]
 - Python Version: [Python 3.8]
 - Method of MultiQC installation: docker `ewels/MultiQC:1.8`

 **Additional context**

**Comment by avsastry** [comment]
I made a new container here using python:3.8-slim and removing the ENTRYPOINT. Not sure why, but I needed to do both in order for the container to work on AWS

https://hub.docker.com/r/avsastry/multiqc-rockhopper

**Comment by ewels** [comment]
Cool, glad you got it working! I have no explanation for this weirdness I'm afraid.
