### ISSUE TITLE
CollectRnaSeqMetrics not recognized when obtained from CollectMultipleMetrics

### ISSUE THREAD

**Issue by uros-sb** [ewels/MultiQC#1168]
**Description of bug:**
Hi, when running Picard CollectMultupleMetrics, and selecting programs to run, one of the programs is "RnaSeqMetrics". The name of the program is different than when running the standalone app Picard CollectRnaSeqMetrics. As such, the logs aren't recognized by MultiQC.
If I edit the Picard results, by changing the "RnaSeqMetrics" to "CollectRnaSeqMetrics" in the command line that was used, the file is recognized properly. 

**MultiQC Error log:**
```
No analysis results found. Cleaning up..
```

**File that triggers the error:**
[sample.rna.metrics.txt](https://github.com/ewels/MultiQC/files/4532859/sample.rna.metrics.txt)

**MultiQC run details (please complete the following):**
 - Command line: multiqc .
 - MultiQC Version: 1.7
 - Operating System: ubuntu:16.04
 - Python Version: python 3.5
 - Method of MultiQC installation: pip

 **Additional context**
Perhaps allowing both "CollectRnaSeqMetrics" and "RnaSeqMetrics" will do the job here!

**Comment by ewels** [comment]
Many thanks for reporting this @uros-sb - I suspect that this is could actually be due to the recent GATK integration? This has changed many of the search strings (see for example #1120 and other recent PRs / issues also).

Updated and tested in 153fbac, now should work in v1.9dev 👍 

Phil

**Comment by uros-sb** [comment]
Awesome Phil, thanks!
Just of our curiosity, any timeline on when you had 1.9 planned for release?
Thanks again for the MultiQC btw, countless hours saved :))

**Comment by ewels** [comment]
> Just out of curiosity, any timeline on when you had 1.9 planned for release?

Hopefully fairly soon now - MultiQC cycles in my list of priorities and it's currently at the top. I'm working my way through the open pull-requests at the moment, then I'll go through the important issues and finally see if I can squeeze in one or two feature requests. How long this takes me is tricky to estimate (sometimes PRs can be merged in a few minutes, sometimes they take me a day or two as I end up doing a lot of refactoring). But hopefully in a couple of weeks or so.

Phil
