### ISSUE TITLE
Avoid overwriting of files in multiqc_data

### ISSUE THREAD

**Issue by drpatelh** [ewels/MultiQC#1175]
I tend to extensively use the great functionality offered by MultiQC for creating custom config files to create reports for the pipelines I write. However, I routinely use the same module in the config file and this means that the data in `multiqc_data` is overwritten instead of being saved in separate files.

For example, if I have multiple sections that use the  `samtools` module as highlighted [here](https://github.com/nf-core/viralrecon/blob/de17a0c1ffccff67f592a2b3ae9dfcac4a212034/assets/multiqc_config.yaml#L52-L61)

But on completion I only have a single `multiqc_samtools_flagstat.txt` file in `multiqc_data`. It would be great if there was a way to be able to reconstitute the data used by MultiQC after it has been run too.

**Comment by ewels** [comment]
> It would be great if there was a way to be able to reconstitute the data used by MultiQC after it has been run too.

This will never happen, sorry.

Having multiple data files should be ok 👍🏻

**Comment by drpatelh** [comment]
> This will never happen, sorry

Okkkkk then. I will find other ways to sleep at night. 

But will I be able to consistently/reproducibly track which of these data files would have been used for any given section in the report Otherwise I don't think it would be worth the effort?

**Comment by ewels** [comment]
Sure, there will be ways to do that. We just have to get the appropriate IDs in place.

But reconstituting (recreating) the original input file afterwards from what MultiQC parsed? Maybe I’m misunderstanding what you mean, but that would be a huge effort for not much gain I think..

**Comment by drpatelh** [comment]
> Sure, there will be ways to do that. We just have to get the appropriate IDs in place.

This is what I mean 👍 :)
 
> But reconstituting (recreating) the original input file afterwards from what MultiQC parsed? Maybe I’m misunderstanding what you mean, but that would be a huge effort for not much gain I think..

This is definitely not what I mean 👎

**Comment by ewels** [comment]
Ok, this is a quick fix. Now you should get:

* `multiqc_samtools_flagstat.txt`
* `multiqc_samtools_flagstat-1.txt`
* `multiqc_samtools_flagstat-2.txt`

..and so on.

It's not as nice as having a more useful proper identifier, passed through from the module. But doing that will require quite a lot of rewriting.

The above numbering _should_ be done in the same order each time - the order that modules are run. So hopefully it should be reproducible in a pipeline. I think.

Phil
