### ISSUE TITLE
Collect tool citations

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#1177]
It would be nice if there was a clear citation for specific tools in MultiQC so that users benefiting from somalier or peddy output could (be reminded to) cite the tool(s) they are using in addition to MultiQC.

_Originally posted by @brentp in https://github.com/ewels/MultiQC/pull/1155#issuecomment-623495132_

**Comment by ewels** [comment]
Suggestions for how this could be rendered in the report are welcome!

**Comment by ewels** [comment]
I think that this would be best done by adding in a new optional argument to [`BaseMultiqcModule`](https://github.com/ewels/MultiQC/blob/29bccd8c0d71149e4e2b18a0e95621177f92298b/multiqc/modules/base_module.py#L21) called `doi`. This can then be added into `self.intro` if it is set, using a doi.org URL:

https://github.com/ewels/MultiQC/blob/29bccd8c0d71149e4e2b18a0e95621177f92298b/multiqc/modules/base_module.py#L64-L65

**Comment by ewels** [comment]
As a bonus, would also be nice to save a citations file into `multiqc_data` with all of the citation info collected into one location. Could think about various formats for this.

Would be nice to include bonus content about the manuscripts, but that will require an internet connection so it must be an add on that does not degrade performance if not available. Would be fun to be able to get a pop-over when hovering on the DOI with the manuscript title / Dimensions.ai badge etc. But that's low priority compared to the rest.

**Comment by ewels** [comment]
@brentp - thanks again for the original suggestion, this is now implemented and merged. It'll be generally available in the next release. Let me know if you have any feedback or suggestions!

**Comment by brentp** [comment]
wow! excellent work!
