### ISSUE TITLE
Question - how to separate fastqc_before and fastqc_after as separate sections

### ISSUE THREAD

**Issue by tamuanand** [ewels/MultiQC#1183]
Hi

I have a question: When I am doing a rnaseq analysis say using nf-core/rnaseq, I want to run fastqc before the qc/trimming etc and then fastqc after. In this scenario, the fastqc reports in MultiQC get collapsed into 1 section and when you have lots of records (from say SRA), it becomes difficult to look through.

Right now, I do a fastqc_before and generate a multiQC report in a different folder from the other analyses.

Hence wondering if it is possible to have a different section in the multiQC report that is fastqc_before and fastqc_after.

Thanks,

**Comment by ewels** [comment]
Yup - see the [nf-core/atacseq MultiQC config](https://github.com/nf-core/atacseq/blob/fa1e3f8993cd20e249b9df09d29c5498eff311d2/assets/multiqc/multiqc_config.yaml#L21-L39) for an example of this.

Documentation: https://multiqc.info/docs/#running-modules-multiple-times

Note that I've had new functionality in the works to handle this in a better way for years now. It might get finished and merged one day: https://github.com/ewels/MultiQC/pull/576

Phil

**Comment by tamuanand** [comment]
Hi @ewels 

Thanks for pointing me to [atacseq multiqc config](https://github.com/nf-core/atacseq/blob/fa1e3f8993cd20e249b9df09d29c5498eff311d2/assets/multiqc/multiqc_config.yaml#L21-L39) 

Some questions:

1. in the module order, do I have to explicitly list out all modules for which I expect to use multiQC? In other words, I do want fastqc_before and fastqc_after as separate sections in my multiQC output and I will model my config file on the example you pointed. I really do not care about the ordering of say the remaining 8 different software I use (fastp, bbtools, salmon, etc). Do I have to explicitly list all of them in the config.yaml or can I do

``` custom_content -m fastqc -m * ```

2. Is it possible to share a multiQC report using the above prototype (fastqc_before and fastqc_after) 

Thanks again

**Comment by tamuanand** [comment]
Hi Phil

I need some help here - I have changed my multiqc config code based on the  [atacseq config example](https://github.com/nf-core/atacseq/blob/fa1e3f8993cd20e249b9df09d29c5498eff311d2/assets/multiqc/multiqc_config.yaml#L21-L39)

I am probably missing something very obvious (and silly) - not sure why I am unable to get this to work. 

Thanks in advance.

My **_new config file_** looks like this:

```
report_comment: >
    This report has been generated by ..<snipped>

module_order:
    - fastqc:
        name: 'FastQC (library; raw)'
        info: 'This section of the report shows FastQC results before adapter trimming.'
        path_filters:
            - '*_fastqc.zip'
        path_filters_exclude:
            - '*trimmed_clean_fastqc.zip'
    - bbmap
    - fastp
    - fastqc:
        name: 'FastQC (library; trimmed)'
        info: 'This section of the report shows FastQC results after adapter trimming.'
        path_filters:
            - '*trimmed_clean_fastqc.zip'
    - salmon

report_section_order:
    salmon:
        order: -1000

export_plots: true
```

My multiqc call from within Nextflow is something like:

```
script:
    rtitle = custom_runName ? "--title \"$custom_runName\"" : ''
    rfilename = custom_runName ? "--filename " + custom_runName.replaceAll('\\W','_').replaceAll('_+','_') + "_multiqc_report" : ''

    """
    multiqc . -f $rtitle $rfilename --config $multiqc_config  \\
           -m custom_content -m fastqc  -m bbmap -m fastp  -m salmon --interactive
    """
```

However, **_multiqc never gets invoked_** with the above. 

The fastqc files (before and after) have this naming convention
```
sample1_fastqc.zip
sample1_trimmed_clean_fastqc.zip
```

**_Note: This below works_** - before the trials that I mention above, this was how my config file was looking like: 

```
report_comment: >
    This report has been generated by .....<snipped>.
report_section_order:
    steadyflow-software-versions:
        order: -1000
```

And my multiqc call from Nextflow was 

```
 multiqc . -f $rtitle $rfilename --config $multiqc_config  --interactive
```

**Comment by ewels** [comment]
> in the module order, do I have to explicitly list out all modules for which I expect to use multiQC?

No - see the docs: https://multiqc.info/docs/#running-modules-multiple-times

For fixing your nextflow pipeline, I'd recommend changing just one bit at a time until it stops working. It's difficult to know what's wrong from what you've posted (there are a lot of steps in that chain), so my best advice is to just break it down to as minimal example as you can and then work stepwise through the changes to isolate the problem.

The easiest way to do this is by avoiding nextflow for a bit and just manually running MultiQC in the pipeline's work directory. Then it's just a few seconds for each change.

Phil
