### ISSUE TITLE
BISCUIT regex breaks with "-nan" values

### ISSUE THREAD

**Issue by ekushele** [ewels/MultiQC#1188]
Hello,
Just wanted to report a bug...

I'm getting the following error message when running MultiQC on biscuit module:

```python
Module biscuit raised an exception: Traceback (most recent call last):
  File "/lib/python3.7/site-packages/multiqc/multiqc.py", line 546, in run
    output = mod()
  File "/lib/python3.7/site-packages/multiqc/modules/biscuit/biscuit.py", line 96, in __init__
    self.mdata[k][s_name] = getattr(self, 'parse_logs_%s' % k)(f['f'], f['fn'])
  File "/lib/python3.7/site-packages/multiqc/modules/biscuit/biscuit.py", line 771, in parse_logs_retention_rate_byread
    data['ca'] = float(m.group(1))*100.0
AttributeError: 'NoneType' object has no attribute 'group'
```

It comes from the file `    ./biscuit_QC/biscuitQC/file_totalReadConversionRate.txt`, which is:

```
BISCUITqc Conversion Rate by Read Average Table
CpA     CpC     CpG     CpT
-nan    -nan    -nan    -nan
```

**Comment by ewels** [comment]
Thanks 👍 

Note that the BISCUIT module has been heavily rewritten in https://github.com/ewels/MultiQC/pull/1167 (currently waiting to be reviewed and merged). So there's a good chance that this will go away after that. But needs testing.

**Comment by ewels** [comment]
Hi @ekushele,

Same as the other issue - if you could please attach a zip with all BISCUIT logs for this sample, that would be great.

Thanks!

Phil

**Comment by ewels** [comment]
Ok, running on this file along gives me an error but it's a different one:

```python
Module biscuit raised an exception: Traceback (most recent call last):
  File "/Users/philewels/GitHub/MultiQC/multiqc/multiqc.py", line 556, in run
    output = mod()
  File "/Users/philewels/GitHub/MultiQC/multiqc/modules/biscuit/biscuit.py", line 137, in __init__
    getattr(self, 'chart_{}'.format(k))()
  File "/Users/philewels/GitHub/MultiQC/multiqc/modules/biscuit/biscuit.py", line 1056, in chart_read_avg_retention_rate
    pdata[s_name] = dict(list(dd.items()) + list(mdata_bybase[s_name].items()))
KeyError: 'file'
```

I think that this is related to running on a single file instead of a folder of logs, so probably unrelated to the issue you describe here. I'll look into resolving it with a warning instead of an exception anyway.

Phil

**Comment by ewels** [comment]
Yeah, I get the same `KeyError` if I run on the other existing logs with `*_totalReadConversionRate.txt`, so pretty sure I'm right that it's just the lone log file for this problem.

**Comment by ewels** [comment]
Ok, fixed my problem with a log message.

If I now paste the contents of your file into one from my complete log set, Biscuit runs fine without a problem. So I think this issue is also solved by the recent rewrite.

Please let me know if you still have problems, include a complete log set so I can replicate and I can reopen.

Thanks!

Phil
