### ISSUE TITLE
Bismark: missing columns (% mCpG, % mCHG, % mCHH, M C's, % Dups...) in General Statistics 

### ISSUE THREAD

**Issue by luuloi** [ewels/MultiQC#1191]
Hi Multiqc Developers,
![Screenshot from 2020-05-14 21-54-00](https://user-images.githubusercontent.com/9794812/81932671-548a0600-9616-11ea-94d3-522822cc2137.png)

I used Bismark/0.22.3 to generate *_SE_report.txt. Then I ran multiqc version 1.8 on these report. However, the multiqc html is missing columns (% mCpG, % mCHG, % mCHH, M C's, % Dups...) in General Statistics.

Here is the example of the Bismark report
[001-P3_SE_report.txt](https://github.com/ewels/MultiQC/files/4628125/001-P3_SE_report.txt)

Here is the snapshot of multiqc html

Could you please help me on this problem?

Thanks,
Loi

**Comment by ewels** [comment]
Hi @luuloi,

The MultiQC module for Bismark parses several different log files: https://multiqc.info/docs/#bismark

Specifically:

```
*_[SP]E_report.txt
*.deduplication_report.txt
*_splitting_report.txt
*M-bias.txt
*.nucleotide_stats.txt
```

The file you sent is an alignment report, so MultiQC is just showing you the alignment results. If you give the other report types to MultiQC as well then you should get the other columns.

Let me know if you run into any problems,

Phil

**Comment by luuloi** [comment]
Hi Ewels,

Thank you for your quick response. I put  *_[SP]E_report.txt, *_splitting_report.txt and *M-bias.txt. I generate more columns in the statistics but still missing some columns and samples are split each metrics. I prefer the same sample are one row rather than one row is one metrics. Please see figure below.
[001-P3.M-bias.txt](https://github.com/ewels/MultiQC/files/4631621/001-P3.M-bias.txt)
[001-P3_splitting_report.txt](https://github.com/ewels/MultiQC/files/4631622/001-P3_splitting_report.txt)
![Screenshot from 2020-05-15 10-09-57](https://user-images.githubusercontent.com/9794812/81997879-399dad00-967b-11ea-8ea6-a3490ceec61a.png)

Could you please help me on it?

Thank you.

Loi

**Comment by ewels** [comment]
Hi @luuloi,

I usually just give the whole analysis folder to MultiQC, then it will find all of the Bismark reports that it needs (it ignores files it doesn't recognise).

Please see the documentation for "cleaning" sample names, to make them sit on the same table rows: https://multiqc.info/docs/#sample-name-cleaning

Phil

**Comment by ewels** [comment]
Note that the Bismark report names are usually based on the input filenames. So for example, if you run Bismark on `test_data_trimmed.fq.gz` you get `test_data_trimmed.fq.gz_bismark_SE_report.txt`.

This means that the default filename cleaning usually works by itself, as it goes from `_trimmed` or `.fq.gz` etc.

I'm not entirely sure how your reports end up with filenames like `001-P3_splitting_report.txt` - maybe you are cleaning them somehow in your analysis? Anyway, this is the reason that MultiQC isn't putting the results on the same table row by default.

It should be easy to overcome with a custom MultiQC config file, as described in the above link.

Phil

**Comment by luuloi** [comment]
Thanks Phil. Problem solved!

**Comment by ewels** [comment]
Great! 👍🏻
