### ISSUE TITLE
BISCUIT module breaks

### ISSUE THREAD

**Issue by ekushele** [ewels/MultiQC#1193]
I know the Biscuit module was re-written, but I want to report my problem (maybe another bug?)
(I don't know even what title to give the issue, because I have no idea what caused the problem)

I'm getting the following error:

```python
 Module biscuit raised an exception: Traceback (most recent call last):
    File "/lib/python3.7/site-packages/multiqc/multiqc.py", line 546, in run
      output = mod()
    File "/lib/python3.7/site-packages/multiqc/modules/biscuit/biscuit.py", line 113, in __init__
      getattr(self, 'chart_{}'.format(k))()
    File "/lib/python3.7/site-packages/multiqc/modules/biscuit/biscuit.py", line 373, in chart_covdist
      basecov[sid]['uniq'] = float(dd[1])/float(dd[0])*100.0
  KeyError: 1
```

The file that raised the error have the following values:
```
BISCUITqc Conversion Rate by Base Average Table
CA      CC      CG      CT
0.022574        0.0181495       0.799459 
```

**Comment by ewels** [comment]
Hi @ekushele,

I've only just merged the rewritten BISCUIT module a few minutes ago (#1167), so if this is from a recent version of BISCUIT then please try again with the latest MultiQC development version.

If you're still having problems, could you please attach a zip with all BISCUIT logs for this sample? The module parses all of the files together so it's difficult to test with just a single file.

Beyond this, maybe @jamorrison has some ideas as to what's going on here.

Phil

**Comment by ewels** [comment]
I just tried running on this single file. I don't get a useful report, but it doesn't throw any errors. Closing now with the assumption that this has been fixed with the merged rewrite.

If you're still having trouble let me know and I can reopen (please provide a complete set of BISCUIT logs if so though).

Phil
