### ISSUE TITLE
Generate custom content files for all plots, not just tables

### ISSUE THREAD

**Issue by drpatelh** [ewels/MultiQC#1194]
Would it be possible to add the section `anchor` or `id` to name the custom content files in `multiqc_data/`

e.g. `mqc_mqc_mplplot_kgrbwiulmq_1.txt` could use [this](https://github.com/nf-core/viralrecon/blob/56e7d84b62f80575b14e3c0d1ccdbb8fd51ff73e/assets/headers/ivar_variants_header_mqc.txt#L1) and be called `mqc_mqc_mplplot_ivar_variants.txt` instead.

**Comment by drpatelh** [comment]
Having played with this a little more it seems that custom content files are not saved to `multiqc_data/` by default. I was wondering for the longest minute until I had a light bulb moment as to why I couldn't suddenly see them anymore. Basically, I removed `export_plots: true` from my config file. Would it be too painful to have these saved even if `export_plots: false`?

**Comment by ewels** [comment]
No, I have thought previously that it wouldn't be too bad to always dump plot data to text files..
