### ISSUE TITLE
Alternative bargraph plot for Bowtie 2 - contaminant removal

### ISSUE THREAD

**Issue by skrakau** [ewels/MultiQC#1199]
I am using Bowtie 2 to remove contaminant reads, i.e. only unmapped reads are kept. For this I would like an alternative plot only focusing on the information "not mapped concordantly" or "mapped concordantly". This would mean different categories (`paired_aligned_none` vs. `paired_aligned_one`, `paired_aligned_multi`), a different order and colors.  

As far as I understood changing categories and their order can not be solved with `custom_plot_config` parameters, or did I miss something? Internally I solved this by searching in `parse_bowtie2_logs()` for the pattern "contaminant removal" which I previously added to the log file and then added a corresponding option to `bowtie2_alignment_plot()`. 

I would create a PR since it might be useful for others too, but I guess this way (expecting some additional custom pattern in the log file) is not the ideal solution, otherwise you would have done it to distinguish between Bowtie 2 / HiSAT2 as well :)
How should this be handled best?

**Comment by ewels** [comment]
Correct, this level of customisation is not possible with `custom_plot_config`. We have three options for this kind of thing:

1. Edit the main module to make a new plot for everyone
2. Make your own module in a [MultiQC plugin](https://multiqc.info/docs/#multiqc-plugins)
3. Write a custom script and use [Custom Content](https://multiqc.info/docs/#custom-content)

I'm not totally clear on the plot you want - have you already generated it? Could you post an image? I'm wondering whether it would be generally useful for all Bowtie2 users or not.

Phil

**Comment by skrakau** [comment]
Thanks for your quick answer!

Something like this:
![bowtie2_pe_plot-1](https://user-images.githubusercontent.com/1982769/82886934-8b7de700-9f47-11ea-9fb8-c9981ec74bf5.png)

maybe both types of mapped reads somehow merged (both get discarded), but the category `paired_aligned_none` would replace `paired_aligned_discord_one`, `paired_aligned_mate_one_halved`, `paired_aligned_mate_multi_halved` and `paired_aligned_mate_none_halved`. All other information could be provided via the `custom_plot_config`.

I use it when removing host reads from metagenomic data, and would try to include it into the MAG pipeline. But it could be useful for other contaminant removal steps as well.

**Comment by ewels** [comment]
Ok, gotcha. I think that this is probably too much of an edge case to be a general feature for core MultiQC to be honest. The info is technically already in the report and I think that it would be confusing for the majority of users.

The good news is that this should be relatively easy to generate. @drpatelh has recently been doing this with the viralrecon pipeline: running MultiQC to parse log files into a more sensible format (you really want to avoid having to parse bowtie2 logs yourself if you can), then manipulating these files in a short script and giving to MultiQC a second time as a Custom Content file.

I'll close this issue now, but feel free to ping me on the nf-core `#mag` Slack channel if you need help.

Phil

**Comment by drpatelh** [comment]
Yep. The implementation for parsing the `yaml` files in `multiqc_data/` is in [this](https://github.com/nf-core/viralrecon/blob/dev/bin/multiqc_to_custom_tsv.py) script @skrakau 

Should be quite straightforward to just replace this Python list with one thats relevant in your use case.

https://github.com/nf-core/viralrecon/blob/f3fed12270e4e8ee020ef04bc56bd2a2e35b0995/bin/multiqc_to_custom_tsv.py#L95-L120 

Note: I avoided parsing the bowtie2 yaml file too 😅 and just parsed the `samtools flagstat` output instead:
https://github.com/nf-core/viralrecon/blob/f3fed12270e4e8ee020ef04bc56bd2a2e35b0995/bin/multiqc_to_custom_tsv.py#L98

**Comment by skrakau** [comment]
Thanks @drpatelh !  I will check
