### ISSUE TITLE
Add Picard support

### ISSUE THREAD

**Issue by remiolsen** [ewels/MultiQC#12]
The Picard modules I would be interested in are
- [x] CollectInsertSizeMetrics
- [x] CollectGcBiasMetrics
- [x] CollectAlignmentSummaryMetrics
- [x] CalculateHsMetrics _(see example from Pekka)_
- [x] CollectRnaSeqMetrics
- [x] CollectOxoGMetrics
- [x] BaseDistributionByCycleMetrics
- [x] CollectWgsMetrics
- [x] RrbsSummaryMetrics
- [ ] QualityByCycleMetrics
- [ ] QualityDistributionMetrics

Any other (picard) modules that are interesting to have?

**Comment by ewels** [comment]
Those are the two I was thinking of. I think that the existing [Picard module](https://github.com/ewels/MultiQC/blob/master/multiqc/picard/__init__.py) can be extended to support these metrics as well.

I'm not working on them yet, I was just _planning_ to work on the Insert Size script - very different :wink:

**Comment by ewels** [comment]
Added `CollectAlignmentSummaryMetrics` to your to-do list..

**Comment by ewels** [comment]
Added `CalculateHsMetrics`

**Comment by ewels** [comment]
Added `CollectRnaSeqMetrics`

**Comment by ewels** [comment]
One down... (Insert size metrics)

**Comment by ewels** [comment]
Two down... (GC Bias plot)

**Comment by avilella** [comment]
I just tried it, and got a complain about GC bias Metrics ( I am using
version picard-tools-1.134):

============================================================
Module picard raised an exception: Traceback (most recent call last):
  File "/bi/home/rocks-av/bin/mqc", line 228, in multiqc
    report.modules_output.append(mod())
  File
"/bi/home/rocks-av/.local/lib/python2.7/site-packages/multiqc/modules/picard/picard.py",
line 50, in __init__
    self.parse_picard_GCbiasMetrics(f)
  File
"/bi/home/rocks-av/.local/lib/python2.7/site-packages/multiqc/modules/picard/picard.py",
line 212, in parse_picard_GCbiasMetrics
    self.picard_GCbias_data[s_name][ int(s[0]) ] = float(s[4])
ValueError: invalid literal for int() with base 10: 'All Reads'
============================================================

Any ideas?

**Comment by ewels** [comment]
Yeah, I kind of figured that it wouldn't work first time - Picard seems to have quite a bit of variability in it's output file structure. Could you send through the picard file so I can see what's different in your version please?

**Comment by ewels** [comment]
Ok, fix pushed in 1a8b102dc191ecacf167859763aa4786fb6fe560

**Comment by ewels** [comment]
Another module added - `CalculateHsMetrics`

**Comment by dakl** [comment]
I'd love to see support for `CollectOxoGMetrics`. I've no experience with javascript so I'm unfortunately not much help there. I can provide example data though.

**Comment by dakl** [comment]
(great tool btw! :+1: )

**Comment by ewels** [comment]
Hi @dakl - no problem, if you send me an example file I can add it. I've noted the name in the checklist at the top...

**Comment by dakl** [comment]
Great! Example data is [here](https://gist.github.com/dakl/aaa9578574712bd4c6f3).

**Comment by ewels** [comment]
Key metric for OxoGMetrics is `OXIDATION_ERROR_RATE`. Would be nice to plot a heatmap - HighCharts [can do it](http://www.highcharts.com/demo/heatmap), but would require yet another javascript file to be included. Easy option would be to plot a line graph using categories for the x axis.

**Comment by ewels** [comment]
Added extra to-do modules from #215 (`BaseDistributionByCycleMetrics`, `QualityByCycleMetrics` and `QualityDistributionMetrics`). Test data in  ewels/MultiQC_TestData@11fdddac69ded8c6118b4d586a7059878c917e23 (`data/modules/picard/CollectMultipleMetrics/`)

**Comment by ewels** [comment]
`QualityByCycleMetrics` and `QualityDistributionMetrics` are basically identical to the FastQC plots. So not in a huge rush to write those modules. Comment if you want to see them done!

**Comment by ewels** [comment]
Support for `CollectRnaSeqMetrics` added. See #273 for more details.

**Comment by snashraf** [comment]
Thanks for a wonderful tools. You don't know how much this tool is being helping me now days. 

Any chance of extending support for CollectWgsMetrics as well. This is a much used metric for WGS data.

Collect metrics about coverage and performance of whole genome sequencing (WGS) experiments.

This tool collects metrics about the fractions of reads that pass base- and mapping-quality filters as well as coverage (read-depth) levels for WGS analyses. Both minimum base- and mapping-quality values as well as the maximum read depths (coverage cap) are user defined.

Note: Metrics labeled as percentages are actually expressed as fractions!

Thanks
Najeeb

**Comment by snashraf** [comment]
[PMC01-01_AB082422_S5_L005_R1_001.txt](https://github.com/ewels/MultiQC/files/737457/PMC01-01_AB082422_S5_L005_R1_001.txt)
Here is an example file from CollectWgsMetrics output.
Thanks
Najeeb

**Comment by ewels** [comment]
Hi Najeeb - many thanks for the file. I'll add CollectWgsMetrics to the list..

**Comment by annavt** [comment]
I'd love http://broadinstitute.github.io/picard/picard-metric-definitions.html#RrbsSummaryMetrics
[example1.rrbsMetrics_summary_metrics.txt](https://github.com/ewels/MultiQC/files/790400/example1.rrbsMetrics_summary_metrics.txt)
(n.b. original file name had no extension but added that for uploading)

**Comment by ewels** [comment]
Great stuff, thanks @annavt.

**Comment by ewels** [comment]
Hi @annavt,

I've just written a new picard submodule for `RrbsSummaryMetrics`. If you could download the latest version and give it a go that would be great!

Cheers,

Phil

**Comment by ewels** [comment]
@snashraf - I'm just looking over the [Picard docs](http://broadinstitute.github.io/picard/picard-metric-definitions.html#CollectWgsMetrics.WgsMetrics) for `CollectWgsMetrics.WgsMetrics` and thinking about what should go into the MultiQC report. My suggestion would be:

* General Stats table
  * `MEDIAN_COVERAGE`
  * `PCT_30X`
    * Use 30X as the default, but make this configurable as with the Picard HsMetrics module. See the [MultiQC docs](http://multiqc.info/docs/#picard)
* Excluded bases plot
  * A bar plot showing the proportion of bases excluded (`PCT_EXC_MAPQ`, `PCT_EXC_DUPE`, `PCT_EXC_UNPAIRED`, `PCT_EXC_BASEQ`, `PCT_EXC_OVERLAP`, `PCT_EXC_CAPPED`)

How does this sound? Is there anything I've missed that you would want to see in the report? Anything that isn't useful and that I can drop?

**Comment by snashraf** [comment]
Hi Ewels,

Thanks alot!! 
I think a graph like this will
![download](https://cloud.githubusercontent.com/assets/4346935/23178473/95e20fda-f87b-11e6-9033-1ecec21a6cc5.png)
 be great as well.

**Comment by ewels** [comment]
Ah yeah, sorry - I meant to say that. The file has histogram data as well so I will plot that as you say (though a value for every 1X on the x axis).

**Comment by snashraf** [comment]
Thanks Ewels!! 
Please let me know whenever its done !! 
Thanks for developing a wonderful tools.
Thanks
Najeeb

**Comment by ewels** [comment]
Ok, it's done! I just pushed the code. Have a play and let me know what you think..

Phil

**Comment by snashraf** [comment]
Hi Ewels, 
Thanks 
Its great but for some reason I am getting RRBS Converted Bases metrics as well while i don't have any such results .
May be you can have an additional general stats column with value greater then 20X and 10X as well as that would pretty awesome for low coverage data as well.

**Comment by ewels** [comment]
Ah, busted! I copied the code for the second plot from the Picard RRBS module but apparently forgot to change the report section header, well spotted! The plot and data are actually from the Wgs report, it was just the header that was wrong. This is fixed, thanks.

You can configure which coverage columns you would like in the General Stats table in your MultiQC config file - see [the docs](http://multiqc.info/docs/#picard) for instructions on how to do this. I've found that everyone has their own preferences for which coverage levels are most important. As a general rule I now use 30X as a default but try to make it simple to customise.

Phil

**Comment by ewels** [comment]
Ok, closing this issue now - it is huge and will stay forever otherwise. Nearly everything on it has been done, please request any new Picard submodule support in dedicated issues.
