### ISSUE TITLE
Add Kraken2 results to General Stats table

### ISSUE THREAD

**Issue by drpatelh** [ewels/MultiQC#1202]
Given the recent and boombastic addition of Kraken 2 in https://github.com/ewels/MultiQC/pull/1161 it would be nice to parse and output some values to the `General Statistics` table. As discussed on Slack @ewels this could be maybe:

*  `Unclassified`
* `top %` (not `Unclassifed`)
* `top 5 %` values (not `Unclassifed`)

By default, I think this could be taken from the lowest-level in the taxonomic tree 🤔 because I dont think this will always be species in the case of microbes. 

This also means the relevant data should be stored in `multiqc_data/` which can then be parsed to create custom tables using those values if required! 😎

**Comment by ewels** [comment]
![image](https://user-images.githubusercontent.com/465550/83323054-85944880-a25c-11ea-86a6-74d20fcddc12.png)

**Comment by ewels** [comment]
![image](https://user-images.githubusercontent.com/465550/83323111-f89dbf00-a25c-11ea-9072-0d161bad0ed9.png)

**Comment by ewels** [comment]
![image](https://user-images.githubusercontent.com/465550/83323276-e4a68d00-a25d-11ea-97d6-09593548fcaf.png)
