### ISSUE TITLE
deeptools max number of samples

### ISSUE THREAD

**Issue by nservant** [ewels/MultiQC#1203]
Hi @ewels 

I tried to make deeptools fingerPrints in multiqc but it seems that it works only for a limited number of samples. Here is the file I'm using ;

http://xfer.curie.fr/get/ja0JQtrtF1K/plotFingerprint.raw.txt

If I subset to the 5 first columns, it's ok.
Thanks

**Comment by nservant** [comment]
I'm using multiqc 1.8

**Comment by ewels** [comment]
I think that you are probably hitting the maximum file-size. See the docs: https://multiqc.info/docs/#big-log-files

If I make a `multiqc_config.yaml` file with the following it works fine for me:

```yaml
log_filesize_limit: 2000000000
```

```console
$ multiqc .
[INFO   ]         multiqc : This is MultiQC v1.9.dev0 (558003d)
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching   : /Users/philewels/GitHub/MultiQC_TestData/data/modules/deeptools/issue_1203
Searching 3 files..  [####################################]  100%
[INFO   ]       deeptools : Found 26 total deepTools samples
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete
```

**Comment by ewels** [comment]
Without that config file it skips the file when searching for matching files and MultiQC doesn't find any samples at all.

**Comment by nservant** [comment]
wonderfull ! it works :)
Thanks again for your quick help !

**Comment by ewels** [comment]
Great stuff! No problem :)
