### ISSUE TITLE
Kraken module contains 'uncustomisable' dynamically generated column names

### ISSUE THREAD

**Issue by jfy133** [ewels/MultiQC#1228]
**Description of bug:**

Originally reported on gitter: https://gitter.im/ewels/MultiQC?at=5ee0edd4035dfa1261112e3f

The Kraken module will report a '%' of the top taxonomic hit in the general stats table. The key is then 'dynamically generated', which means if you have different samples/data, you cannot use a common key to place the column in the desired position in the table with a `config.yml`, as this column will be named differently in each dataset.

Example
![image](https://user-images.githubusercontent.com/17950287/84878185-c6c48f00-b089-11ea-8a4d-39b2767c2eea.png)

**MultiQC run details (please complete the following):**
* Command used to run MultiQC: 
```bash
cd MultiQC_TestData/data/modules/kraken/
multiqc .
## dynamic ID will be: % Peptoclostridium difficile 
```
* MultiQC Version: 1.9
* Operating System: Ubuntu 18.04
* Method of MultiQC installation: pip

**Comment by vladsavelyev** [comment]
Fixed by https://github.com/ewels/MultiQC/pull/2205 - thank a lot @gsmashd!
