### ISSUE TITLE
Java - international issues

### ISSUE THREAD

**Issue by colindaven** [ewels/MultiQC#123]
Hi,

I had an issue with a float with value 0,48 instead of 0.48 produced by a german java version (used to create the FastQC and or Picard reports). We try to avoid this but it does creep in. Any chance multiqc (which is really timely and much needed by the way!) can check for the comma instead of dot problem and correct for it ? 
I 'm sure a lot of bug reports could be prevented by doing that.

cheers,
Colin

```
Traceback (most recent call last):
  File "/usr/local/bin/multiqc", line 294, in <module>
    multiqc()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/bin/multiqc", line 226, in multiqc
    report.general_stats_build_html()
  File "/usr/local/lib/python2.7/dist-packages/multiqc/utils/report.py", line 82, in general_stats_build_html
    val = headers[k]['modify'](val)
  File "/usr/local/lib/python2.7/dist-packages/multiqc/modules/picard/picard.py", line 100, in <lambda>
    'modify': lambda x: float(x) * 100
ValueError: invalid literal for float(): 0,481067
```

**Comment by ewels** [comment]
Hi Colin,

Thanks for the suggestion - we actually had exactly the same problem on Friday with a different repository (not involving Java). This is a bit of a dull manual task, as the parsing for each module is different, but I'll have a go through to fix this as I agree that it should be able to cope with the differences. I'll start with FastQC and Picard.

Phil

**Comment by ewels** [comment]
Note to self - the traceback seems to suggest that the regexes are pulling out the strings without any problem, it's the `float()` call which is causing the error. Could catch the `ValueError` and try to use [`locale.atof`](https://docs.python.org/2/library/locale.html#locale.atof) instead. Something like this:

```python
try:
    num = float(strval)
except ValueError:
    if ',' in strval and '.' not in strval:
        loc = locale.getlocale() # get current locale
        locale.setlocale(locale.LC_ALL, 'de_DE')
        num = locale.atof(strval)
        locale.setlocale(locale.LC_ALL, loc) # restore saved locale
```

Not very pretty, but should then cope with mixtures of files using different locales and other messy stuff.

Only other solution I can think of is to replace commas with decimals, but that can then cause problems if commas are used to separate thousands, eg. `102,932.24`

**Comment by colindaven** [comment]
The second answer in this might be helpful, using the locale setting.

http://stackoverflow.com/questions/6633523/how-can-i-convert-a-string-with-dot-and-comma-into-a-float-number-in-python

Sorry about this, we have (unfortunately) servers running different languages.

**Comment by ewels** [comment]
Sorry @colindaven - I can't figure out a way to fix this in a nice way. Quite a lot of modules output numbers with thousands separators and there just isn't a good way that I can think of to tell whether the comma in `123,456` is a decimal place or a thousands separator.

Based on the website traffic, the majority of users are based in countries which do not use commas for decimal places. Combined with the fact that tools are inconsistent in their behaviour within comma countries, I think that doing anything here will cause more errors than it solves.

As such, for now at least, I'm marking this as a `won't fix` and closing it. Suggestions for a better solution welcome!

Phil
