### ISSUE TITLE
HISAT2: Unaligned Reads do not show in paired-end mode only

### ISSUE THREAD

**Issue by FelixKrueger** [ewels/MultiQC#1230]
**Description of bug:**

We found that MultiQC seems to miss out the Unaligned reads statistics for HISAT2 in paired-end mode (PE) only, but works fine in single-end mode (SE). Bowtie2 statistics are gathered correctly in both cases.

Here is an example SE plot:
![bowtie2_hisat2_se_plot](https://user-images.githubusercontent.com/5870509/85058591-9cb2c000-b1a2-11ea-9400-e8fa3e521367.png)

And here is the PE version:
![bowtie2_hisat2_pe_plot](https://user-images.githubusercontent.com/5870509/85059228-94a75000-b1a3-11ea-970b-f232bcdf24a6.png)

This can obviously be quite misleading at times.

This happens despite the logs looking fairly similar (the programs were run with somewhat different 

**Bowtie2 report**

```
2022172 reads; of these:
  2022172 (100.00%) were paired; of these:
    494895 (24.47%) aligned concordantly 0 times
    925333 (45.76%) aligned concordantly exactly 1 time
    601944 (29.77%) aligned concordantly >1 times
    ----
    494895 pairs aligned concordantly 0 times; of these:
      105774 (21.37%) aligned discordantly 1 time
    ----
    389121 pairs aligned 0 times concordantly or discordantly; of these:
      778242 mates make up the pairs; of these:
        444082 (57.06%) aligned 0 times
        204517 (26.28%) aligned exactly 1 time
        129643 (16.66%) aligned >1 times
89.02% overall alignment rate
```

**HISAT2 report**
```
2025528 reads; of these:
  2025528 (100.00%) were paired; of these:
    464484 (22.93%) aligned concordantly 0 times
    1458868 (72.02%) aligned concordantly exactly 1 time
    102176 (5.04%) aligned concordantly >1 times
77.07% overall alignment rate
```

**File that triggers the error:**
[PlateE_H12_S192_merged_L001_GRCh38_bowtie2_stats.txt](https://github.com/ewels/MultiQC/files/4800514/PlateE_H12_S192_merged_L001_GRCh38_bowtie2_stats.txt)
[PlateE_H12_S192_merged_L001_GRCh38_hisat2_stats.txt](https://github.com/ewels/MultiQC/files/4800515/PlateE_H12_S192_merged_L001_GRCh38_hisat2_stats.txt)

**MultiQC run details (please complete the following):**
* Command used to run MultiQC: `multiqc .`
* MultiQC Version: 1.9
* Operating System: Linux
* Python Version: 3.7.3
* Method of MultiQC installation: manual

**Additional context**
Thanks very much!

**Comment by ewels** [comment]
I’m confused - the screen grabs both look fine here again? The category names are different for SE and PE, but both have unaligned reads (`SE not aligned`, `PE neither mate aligned`).

What are you expecting to see here?

**Comment by ewels** [comment]
Ahh sorry, I see - it’s the HISAT2 logs mixed in with bowtie2. Gotcha.

**Comment by ewels** [comment]
Ok, fixed I think. Very hacky though, as is most of the Bowtie2 parsing code. Please test and test and test to make sure that I haven't messed anything up - I find it extremely difficult to tell whether the numbers are adding up properly.

Reminder that you can run HiSAT2 with the `--new-summary` option. This gives a more sane YAML output file.

**Comment by FelixKrueger** [comment]
Thanks Phil, I have now added `--new-summary` to our pipelines, will do some testing soon.
