### ISSUE TITLE
Split happy section into two; enable different conditional formatting for SNPs & indels

### ISSUE THREAD

**Issue by woook** [ewels/MultiQC#1233]
**Is your feature request related to a problem? Please describe.**
As SNP recall is usually higher than for indels, it would be useful to have separate conditional formatting rules for these two types of variants.

**Describe the solution you'd like**
Split the happy section into two tables, one for SNPs and another for indels.

**Describe alternatives you've considered**
A helper script to take happy output and split it into two output files.

**Additional context**
Can submit a PR if this seems a sensible approach.

@sophie22

**Comment by ewels** [comment]
Added in #1241 👍🏻
