### ISSUE TITLE
Module request: Pychopper

### ISSUE THREAD

**Issue by caspargross** [ewels/MultiQC#1235]
**Tool Details**
* Name of tool: Pychopper
* Tool homepage: https://github.com/nanoporetech/pychopper
* Tool description: A tool to identify, orient, trim and rescue full length Nanopore cDNA reads 
* Data suitable for MultiQC plot(s): 
  - Read Classification
  - Strand
  - ReadStats
  - Additionals stats could be added, but are imo not as important

* Most interesting data for General Stats table: 
  - Percentage of full length transcripts

**Tool output:**

[20035Ia01_stats.txt](https://github.com/ewels/MultiQC/files/4818931/20035Ia01_stats.txt)

* Log filename pattern: User defined
* File contents:  Read Stats, Read Classification, Strand Orientation in a three column tsv file (Category -> Name -> Value)

**Comment by caspargross** [comment]
I will start working on this.

**Comment by caspargross** [comment]
Created Pull Request 
https://github.com/ewels/MultiQC/pull/1236

**Comment by caspargross** [comment]
Pull request was merged 3 years ago :D

**Comment by ewels** [comment]
ah nice, this is the kind of GitHub issue notification I _like_ to see 😆
