### ISSUE TITLE
Module request: Bracken

### ISSUE THREAD

**Issue by angelovangel** [ewels/MultiQC#1238]
**Tool Details**
* Name of tool: Bracken
* Tool homepage: https://ccb.jhu.edu/software/bracken/
* Tool description: Bracken computes the abundance of species (and other taxonomic levels) in DNA sequences from a metagenomics sample, using the taxonomy labels assigned by Kraken
* Data suitable for MultiQC plot(s): Barplots, identical to the ones used for Kraken
* Most interesting data for General Stats table: % Top5 Species

**Tool output:**

[minigut_sample1_kraken2_bracken_species.txt](https://github.com/ewels/MultiQC/files/4842387/minigut_sample1_kraken2_bracken_species.txt)

_kraken2 output for the same sample, to be used as a comparison_
[minigut_sample1_kraken2.txt](https://github.com/ewels/MultiQC/files/4842390/minigut_sample1_kraken2.txt)

* Log filename pattern: specified by user

**Comment by ewels** [comment]
x-ref to original Gitter thread: [link](https://gitter.im/ewels/MultiQC?at=5ef4ea4ac223cc536a360c4a)

> Hi all!
>
> While I enjoy the new kraken2 module in MultiQC and find it a very good way to drill down such data, I think it may be leading to misconceptions and improper use/interpretation of the kraken2 results. kraken2 should not (in my opinion) be used for relative abundance estimation, it assigns taxonomy to sequencing reads. See discussions DerrickWood/kraken2#32 or the kraken2 paper.
>
> It would be more appropriate to use bracken for this, which is written exactly for this - relative abundance estimation using the labels assigned by kraken. I was about to open a MultiQC issue for bracken support, but then I thought it may be actually better to “replace” kraken with bracken in the list of tools that MultiQC supports. The output of bracken is very similar to that of kraken2, yet there are some subtle differences, so it should be pretty straightforward to do.
>
> Anyway, thought it is worth discussing

**Comment by dfornika** [comment]
The regex to detect a kraken file is: `^\s{1,2}(\d{1,2}\.\d{1,2})\t(\d+)\t(\d+)\t([\dUDKPCOFGS-]{1,3})\t(\d+)(\s+)(.+)`

The difference between `kraken` and the adjusted report that `bracken` outputs seems to be:

- The first column of `bracken` output is not left-padded with whitespace
- The first column of `bracken` output may be `100.00`, so there may be three digits left of the decimal
- The taxonomic 'rank code' of `bracken` output may contain the character `R`.

So I believe that a regex of `^(\d{1,3}\.\d{1,2})\t(\d+)\t(\d+)\t([\dRUDKPCOFGS-]{1,3})\t(\d+)(\s+)(.+)` should match `bracken` output.

There is also a bracken output with format:

```
name	taxonomy_id	taxonomy_lvl	kraken_assigned_reads	added_reads	new_est_reads	fraction_total_reads
Salmonella enterica	28901	S	759772	411842	1171614	0.98589
Salmonella bongori	54736	S	3778	53	3831	0.00322
Salmonella sp. SSDFZ54	2500542	S	56	195	251	0.00021
Salmonella sp. HNK130	2664291	S	3	38	41	0.00004
Salmonella sp. SJTUF14178	2745895	S	3	319	322	0.00027
Salmonella sp. SJTUF14152	2745892	S	2	45	47	0.00004
Salmonella sp. SSDFZ69	2500543	S	1	19	20	0.00002
Salmonella sp. SCFS4	2725417	S	1	12	13	0.00001
Enterobacter cloacae	550	S	3271	313	3584	0.00302
```

...which might be a bit easier to parse.

**Comment by dfornika** [comment]
I've submitted a bracken module (linked above). I think it would make sense to offer both kraken and bracken modules. It might even help people to make comparisons between the two tools to better understand how bracken is a more appropriate tool for abundance estimation.

Maybe a small disclaimer could be added to the output from the kraken module, warning against improper interpretation and pointing out the availability of bracken?
