### ISSUE TITLE
Picard HS ? values

### ISSUE THREAD

**Issue by avilella** [ewels/MultiQC#124]
https://github.com/ewels/MultiQC/commit/069eff4d4578dc8be140465c2c5ca748c17ac52f

**Comment by avilella** [comment]
Github pull request pulls a lot of crap from my previous attempts, the link above is a 2-line change to fix a bug in Picard HS.

**Comment by ewels** [comment]
Quite confused about how you created that commit on my repo without it being there? That was weird. Anyway, thanks for reporting! Will copy the change and push it now.

**Comment by avilella** [comment]
I clicked on the hash of the pull request that was pointed your way, that's
why the url points to your repo, I think.

**Comment by ewels** [comment]
That's what I thought - but then I can't find a PR anywhere?

**Comment by avilella** [comment]
The PR included a bunch of unrelated stuff I wouldn't want polluting the
merge history, from when I was trying to write the calculate_clip_overlap
parser... So I didn't submit it as PR.

I submitted it now, feel free to ignore.

**Comment by ewels** [comment]
Hah, thanks - was just curious!
