### ISSUE TITLE
Switching datasets for scatter plots

### ISSUE THREAD

**Issue by caspargross** [ewels/MultiQC#1245]
Hi,

I am trying to switch datasets in a scatterplot. When I use the dataformat suggested in the lineplot section (list of dictionaries)  just get multiple points for my sample.

In my case I want to create Precision/Recall plots for different categories. Each sample has exactly one point per category.
Is there a way to do this easily?

**Comment by ewels** [comment]
It should work the same as line graphs ([looking at the code, anyway](https://github.com/ewels/MultiQC/blob/96d0a2f73472bbe60a28d217cd9811e2ed86ceca/multiqc/plots/scatter.py#L105)).

Could you post a snippet of your code that's not working?

**Comment by caspargross** [comment]
I think I might have the dataformat wrong.

Is this correct:

**Comment by ewels** [comment]
Details here: https://multiqc.info/docs/#switching-datasets-1

> To do this, just supply a list of data dicts

So the second one basically. If you have one scatter plot working it's the same data structure, just repeated in a list for as many plots as you want.

However, `missed` and `found` are not the right keys for a scatter plot. They should be `x` and `y` ([docs](https://multiqc.info/docs/#scatter-plots)). So maybe this is what you're looking for:

```python
[
    {"sample1": {'x': 14848, 'y': 246728}}, 
    {"sample1":  {'x': 5479, 'y': 187685}}, 
    {"sample1":  {'x': 0, 'y': 30389}}
]
```

You'll then also want to define `config['data_labels']` to customise the buttons that switch between the plots.

I hope that makes sense!

**Comment by caspargross** [comment]
Thanks again Phil. It is working now. Maybe it would help to add an example of a multi-category dataset somewhere in the documentation.

**Comment by ewels** [comment]
Good idea, that's done. Glad you got it working 👍
