### ISSUE TITLE
bamtools output files not seen

### ISSUE THREAD

**Issue by bioinfowheat** [ewels/MultiQC#1247]
**Description of bug:**

I really don't think this is a bug, but something is strange to this 1st time user.
I did try your test dataset and got perfect results

```bash
wget http://multiqc.info/SBW/data/basic_RNAseq.tar.gz
tar xzf basic_RNAseq.tar.gz
cd basic_RNAseq
multiqc .
```

But when I try and run with `bamtools stats` results, MultiQC can't find the files

I'm using:

```bash
cat testset_bamfiles | parallel '/data/programs/bamtools-2.5.1/bin/bamtools stats -in {} > bamtools/{/.}.stats.log'
```

which executes

```bash
/data/programs/bamtools-2.5.1/bin/bamtools stats -in ../SRR6837585.sorted.rg.bam > bamtools/SRR6837585.sorted.rg.stats.log
/data/programs/bamtools-2.5.1/bin/bamtools stats -in ../SRR6837586.sorted.rg.bam > bamtools/SRR6837586.sorted.rg.stats.log
/data/programs/bamtools-2.5.1/bin/bamtools stats -in ../SRR6837587.sorted.rg.bam > bamtools/SRR6837587.sorted.rg.stats.log
```

resulting files are fine (shown below), but MultiQC doesn't see them .... I'm running `multiqc .` in the directory with the files.

```console
$ head bamtools/*log
==> bamtools/SRR6837585.sorted.rg.stats.log <==

**********************************************
Stats for BAM file(s): 
**********************************************

Total reads:       17682914
Mapped reads:      16907391     (95.6143%)
Forward strand:    9246731      (52.2919%)
Reverse strand:    8436183      (47.7081%)
Failed QC:         0    (0%)

==> bamtools/SRR6837586.sorted.rg.stats.log <==

**********************************************
Stats for BAM file(s): 
**********************************************

Total reads:       24388376
Mapped reads:      22931632     (94.0269%)
Forward strand:    12939145     (53.0546%)
Reverse strand:    11449231     (46.9454%)
Failed QC:         0    (0%)
```

**Comment by ewels** [comment]
Hi @bioinfowheat,

This is odd - you can see how MultiQC searches for `bamtools stats` files in the docs: https://multiqc.info/docs/#bamtools - it  looks for the string `Stats for BAM file(s):`, which you have.

If I try to make a copy of your files locally, it seems to work fine:

```console
$ cat SRR683758*
───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: SRR6837585.sorted.rg.stats.log
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ **********************************************
   2   │ Stats for BAM file(s):
   3   │ **********************************************
   4   │
   5   │ Total reads:       17682914
   6   │ Mapped reads:      16907391     (95.6143%)
   7   │ Forward strand:    9246731      (52.2919%)
   8   │ Reverse strand:    8436183      (47.7081%)
   9   │ Failed QC:         0    (0%)
───────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: SRR6837586.sorted.rg.stats.log
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ **********************************************
   2   │ Stats for BAM file(s):
   3   │ **********************************************
   4   │
   5   │ Total reads:       24388376
   6   │ Mapped reads:      22931632     (94.0269%)
   7   │ Forward strand:    12939145     (53.0546%)
   8   │ Reverse strand:    11449231     (46.9454%)
   9   │ Failed QC:         0    (0%)
───────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

$ multiqc -f .
[INFO   ]         multiqc : This is MultiQC v1.10.dev0 (b0fac8b)
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching   : /Users/philewels/GitHub/MultiQC_TestData/data/modules/bamtools/stats/issue_1247
[INFO   ]        bamtools : Found 2 bamtools stats reports
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete
```

So basically, everything looks fine and I'm not quite sure why MultiQC isn't working for you here. Could you please add a little more information about your run - what version you're trying to use, the log output and so on.

Thanks,

Phil

**Comment by bioinfowheat** [comment]
morning Phil,

thanks for the quick response.

here’s what I get on a run in the folder with the files

multiqc .                                                                   │
/usr/local/bin/multiqc:229: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead                                                        │
  logger.warn('MultiQC Version {} now available!'.format(remote_version))                                                                                     │
[WARNING]         multiqc : MultiQC Version v1.9 now available!                                                                                               │
[INFO   ]         multiqc : This is MultiQC v1.7                                                                                                              │
[INFO   ]         multiqc : Template    : default                                                                                                             │
[INFO   ]         multiqc : Searching '.'                                                                                                                     │
/usr/local/bin/multiqc:495: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead                                                        │
  logger.warn("No analysis results found. Cleaning up..")                                                                                                     │
[WARNING]         multiqc : No analysis results found. Cleaning up..                                                                                          │
[INFO   ]         multiqc : MultiQC complete

**Comment by bioinfowheat** [comment]
huh ….

just ran samtools idxstats and flagstat, and upon those multiqc ran great … but still didn’t find the bamtools stat output …. 

:-(


chrwhe@duke:/cerberus/projects/chrwhe/Pieris_rapae_WGS/bamfiles/multiqc$ multiqc .                                                                            │
/usr/local/bin/multiqc:229: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead                                                        │
  logger.warn('MultiQC Version {} now available!'.format(remote_version))                                                                                     │
[WARNING]         multiqc : MultiQC Version v1.9 now available!                                                                                               │
[INFO   ]         multiqc : This is MultiQC v1.7                                                                                                              │
[INFO   ]         multiqc : Template    : default                                                                                                             │
[INFO   ]         multiqc : Searching '.'                                                                                                                     │
[INFO   ]  feature_counts : Found 8 reports                                                                                                                   │
[INFO   ]        samtools : Found 3 flagstat reports                                                                                                          │
[INFO   ]        samtools : Found 3 idxstats reports                                                                                                          │
[INFO   ]            star : Found 8 reports                                                                                                                   │
[INFO   ]        cutadapt : Found 8 reports                                                                                                                   │
[INFO   ]          fastqc : Found 8 reports                                                                                                                   │
[INFO   ]         multiqc : Compressing plot data                                                                                                             │
[INFO   ]         multiqc : Report      : multiqc_report.html                                                                                                 │
[INFO   ]         multiqc : Data        : multiqc_data                                                                                                        │
[INFO   ]         multiqc : MultiQC complete

**Comment by bioinfowheat** [comment]
OK, 

so I installed using pip and sudo, and things seem to work now that I’m running 
MultiQC v1.10.dev0

although the html report is strange for the samtools and bamtools stats


and I get an error now in the log file:
multiqc : This is MultiQC v1.10.dev0
[INFO   ]         multiqc : Template    : default
[WARNING]         multiqc : You are running MultiQC with Python 2.7.16
[WARNING]         multiqc : Please upgrade! MultiQC no longer officially supports Python < 3.6
[INFO   ]         multiqc : Searching   : /cerberus/projects/chrwhe/Pieris_rapae_WGS/bamfiles/multiqc
Searching 14 files..  [####################################]  100%          
##### ERROR! MatPlotLib library could not be loaded!    #####
##### Flat plots will instead be plotted as interactive #####
No module named functools_lru_cache
##### ERROR! MatPlotLib library could not be loaded!    #####
##### Flat plots will instead be plotted as interactive #####
cannot import name cbook
[ERROR  ]         multiqc : Oops! The 'somalier' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    None
============================================================
Module somalier raised an exception: Traceback (most recent call last):
  File "/home/chrwhe/.local/lib/python2.7/site-packages/multiqc/multiqc.py", line 567, in run
    mod = config.avail_modules[this_module].load()
  File "/home/chrwhe/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/chrwhe/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/chrwhe/.local/lib/python2.7/site-packages/multiqc/modules/somalier/__init__.py", line 3, in <module>
    from .somalier import MultiqcModule
  File "/home/chrwhe/.local/lib/python2.7/site-packages/multiqc/modules/somalier/somalier.py", line 698
    cols_return.append('rgba({},{},{},{})'.format(*cols_rgb, alpha))
SyntaxError: only named arguments may follow *expression
============================================================
[INFO   ]        samtools : Found 3 stats reports
[INFO   ]        samtools : Found 3 flagstat reports
[INFO   ]        samtools : Found 3 idxstats reports
[INFO   ]        bamtools : Found 3 bamtools stats reports
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete

**Comment by ewels** [comment]
Ok, so I guess that the support for `bamtools stats` was added after MultiQC v1.7 which is why it only found the reports after you upgraded.

Installing MultiQC with `sudo` is basically always a bad idea. Check the docs for how to install MultiQC: https://multiqc.info/docs/#installing-multiqc

Also your (presumably system) Python is 2.7, with MultiQC no longer officially supports. So it's really best to use Conda or something here instead.

Phil

**Comment by bioinfowheat** [comment]
thanks Phil,

should I uninstall using pip and then reinstall using conda or pip3, without sudo?

**Comment by ewels** [comment]
It doesn't really matter whether you uninstall or not. But yes I'd recommend setting up conda.

The MultiQC docs describes how to set up a new Python environment with miniconda: https://multiqc.info/docs/#installing-python

Once you have conda running with that custom version of Python running, which is separate from your system Python, you should never need `sudo` again for Python stuff. You can then install MultiQC with either conda or pip, it doesn't really matter which (pip will install into the conda Python environment).

Does that make sense?

Phil
