### ISSUE TITLE
"Somalier" MultiQC module broke

### ISSUE THREAD

**Issue by mqfitzgerald** [ewels/MultiQC#1252]
**Description of bug:**
When I try to run MultiQC on my transcriptome-mapped `kallisto.log` files, I get the following error

**MultiQC Error log:**

```console
$ multiqc .
[INFO   ]         multiqc : This is MultiQC v1.9
[INFO   ]         multiqc : Template    : default
[WARNING]         multiqc : You are running MultiQC with Python 2.7.15
[WARNING]         multiqc : Please upgrade! MultiQC will soon drop support for Python < 3.6
[INFO   ]         multiqc : Searching   : /oasis/tscc/scratch/mfitzgerald/GSE95343
Searching 95 files..  [####################################]  100%
[ERROR  ]         multiqc : Oops! The 'somalier' MultiQC module broke...
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues
  If possible, please include a log file that triggers the error - the last file found was:
    None
============================================================
Module somalier raised an exception: Traceback (most recent call last):
  File "/home/mfitzgerald/miniconda2/lib/python2.7/site-packages/multiqc/multiqc.py", line 567, in run
    mod = config.avail_modules[this_module].load()
  File "/home/mfitzgerald/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/home/mfitzgerald/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/mfitzgerald/miniconda2/lib/python2.7/site-packages/multiqc/modules/somalier/__init__.py", line 3, in <module>
    from .somalier import MultiqcModule
  File "/home/mfitzgerald/miniconda2/lib/python2.7/site-packages/multiqc/modules/somalier/somalier.py", line 698
    cols_return.append('rgba({},{},{},{})'.format(*cols_rgb, alpha))
SyntaxError: only named arguments may follow *expression
============================================================
[INFO   ]        cutadapt : Found 14 reports
[INFO   ]          fastqc : Found 14 reports
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete
```

**File that triggers the error:**
RNA-seq data

**MultiQC run details (please complete the following):**
* Command used to run MultiQC: multiqc .
* MultiQC Version: MultiQC v1.9
* Operating System: Linux
* Python Version: 2.7.15
* Method of MultiQC installation: pip

**Additional context**
From the MultiQC documentation:

> "Somalier can be used to find sample swaps or duplicates in cancer projects, where there is often no jointly-called VCF across samples. It is also extremely efficient and so can be used to find all-vs-all relatedness estimates for thousands of samples. It also outputs information on sex, depth, heterozgyosity, and ancestry to be use for general QC."

**Comment by ewels** [comment]
Hi @mqfitzgerald,

Please see the top lines of the log:

```
[WARNING]         multiqc : You are running MultiQC with Python 2.7.15
[WARNING]         multiqc : Please upgrade! MultiQC will soon drop support for Python < 3.6
```

I suspect that this is a problem with Python 2. Please try running MultiQC again with Python 3.6+.

See the changelog for the v1.9 release of MultiQC for more details: https://github.com/ewels/MultiQC/blob/master/CHANGELOG.md#dropped-official-support-for-python-2

Let me know if you still get this error with Python 3 and I will re-open the issue. See the [docs](https://multiqc.info/docs/#installing-multiqc) for details on different ways to install MultiQC (for example, using conda makes it easy to switch to a different version of Python).

Phil
