### ISSUE TITLE
Print a log message about flat images

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#1254]
It's not uncommon for people to think that MultiQC doesn't work above a certain sample size, or be confused why they suddenly lose the interactive features when they hit the [`plots_flat_numseries` threshold](https://multiqc.info/docs/#flat--interactive-plots).

A simple way to help here would be to print a log message to the console at the end of the run warning that flat plots were used and explaining that the `--interactive` flag can be used to avoid this behaviour (maybe with a URL for the docs).

It may also be possible to add to the warning in the report, but I have a feeling that there is already something printed there and we don't want to interfere with the report too much for the people who are ok with the flat plots.

**Comment by ewels** [comment]
Looking at the code, it seems that we already have an attribute to count the number of flat-image plots: `report.num_mpl_plots`. However, it's not very useful currently because if the person running MultiQC chooses `--export-plots` then it will count those images, even though they are not in the report.

So, this counter needs to be moved from where it currently sits (find all occurrences of `report.num_mpl_plots += 1`) to where the code decides to put flat-image plots in the report:

https://github.com/ewels/MultiQC/blob/0d00f369158bfb58944fe8cb9dec1710a95d1960/multiqc/plots/bargraph.py#L180-L182

https://github.com/ewels/MultiQC/blob/0d00f369158bfb58944fe8cb9dec1710a95d1960/multiqc/plots/linegraph.py#L175-L177

Once we have that counter working as expected, we can check if it is greater than zero [at the end of report generation](https://github.com/ewels/MultiQC/blob/1bbd2a28f7e5787544f4151e2a119e9f2b377c7a/multiqc/multiqc.py#L908) and print a log message.

**Comment by BrendanNug** [comment]
Thanks for the insight, I'll give it a try.

**Comment by myiwt** [comment]
Hi, would you like some more help on this?

**Comment by ewels** [comment]
Hi @myiwt - I can't see any open PRs from @BrendanNug, so if he doesn't reply then I think it's fine for you to have a stab at this if you fancy it.

Phil

**Comment by pratheekcr** [comment]
Hi, I am a first timer. Can I work on this ticket, please?

**Comment by ewels** [comment]
Sure! Just open a pull request when you have your changes working. Shout if you need any help.

**Comment by megumi-mori** [comment]
Hello! I'm a first timer. Would it be alright for me to take a stab at it?

**Comment by ewels** [comment]
Go for it 👍🏻  First person to get a PR in / merged wins 😅

**Comment by ewels** [comment]
Thanks again @megumi-mori!
