### ISSUE TITLE
Qualimap gene body coverage

### ISSUE THREAD

**Issue by jessakay** [ewels/MultiQC#1258]
**Is your feature request related to a problem? Please describe.**
The gene coverage plot as produced by Qualimap's RNA-seq module is in units of "counts" but are displayed as "%". This also makes comparisons across samples with varying library sizes somewhat difficult
https://github.com/ewels/MultiQC/blob/8fcd6552d8b98220dad13561b37d004424ba02dd/multiqc/modules/qualimap/QM_RNASeq.py#L197

**Describe the solution you'd like**
Replicate what was done for RSeQC's gene body coverage module, having the option to show both absolute counts and scaled %
https://github.com/ewels/MultiQC/blob/8fcd6552d8b98220dad13561b37d004424ba02dd/multiqc/modules/rseqc/gene_body_coverage.py#L84-L89

**Describe alternatives you've considered**
It would be possible to replace Qualimap with RSeQC in our pipeline, but the latter is considerably slower and would necessitate requesting much longer walltimes when submitting jobs

**Additional context**

**Comment by ewels** [comment]
Many thanks for reporting this @jessakay!

This has now been done by @ErikDanielsson in #1473 and will be included in the upcoming v1.11 release. If you get a chance to test it on dev (or after release) and confirm that it's now working as you expect, that would be amazing 👍🏻 

Phil
