### ISSUE TITLE
multiqc : No analysis results found. 

### ISSUE THREAD

**Issue by Jomagrax** [ewels/MultiQC#1259]
**Description of bug:**
As I run multiqc the following error message appears leading to no finding any analysis results.

**MultiQC Error log:**

```

$ multiqc  fastqc .
[INFO   ]         multiqc : This is MultiQC v1.9
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching   : /home/superuser/jose/rna-seq_documentation/tutorial_griffith
[INFO   ]         multiqc : Only using modules fastqc

Bad key "text.kerning_factor" on line 4 in
/home/superuser/miniconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test_patch.mplstyle.
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.1.3/matplotlibrc.template
or from the matplotlib source distribution
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete


```

**File that triggers the error:**

[fastqc_report.zip](https://github.com/ewels/MultiQC/files/4987183/fastqc_report.zip)

**MultiQC run details (please complete the following):**
* Command used to run MultiQC:  multiqc .
* MultiQC Version:  MultiQC v1.9
* Operating System:   Ubuntu 16.04.6
* Python Version:  python 3.7
* Method of MultiQC installation:  conda

**Additional context**

**Comment by ewels** [comment]
Hi @Jomagrax - have you tried following the instructions in the error message, and updating matplotlib?

See https://multiqc.info/docs/#installing-multiqc for the recommended installation methods for MultiQC - for example, using `conda` very often solves these kinds of problems.

Phil

**Comment by Jomagrax** [comment]
Hi @ewels, thanks for your quick response.

I have traied re-instaling multiqc manually and from conda, but the error persist. The thing is I don´t know how to update the matplotlibrc file

**Comment by ewels** [comment]
This error comes from matplotlib and not MultiQC itself, so it's new to me as well. A quick google suggests that it's likely due to conflicting matplotlib installations, so I would start by manually reinstalling matplotlib:

```bash
pip install --force-reinstall --upgrade matplotlib
```

You could also try installing MultiQC into a fresh conda environment.

Note that this error message could be a red-herring and not causing the problem. Matplotlib isn't always used in a MultiQC run and it looks like the MultiQC execution is getting to the end without finding any input log files.

I guess that you have manually edited the command above (should be `-m fastqc` not just `fastqc` based on the log output). Could you confirm the command that you're using and the files that you're running on?

Thanks,

Phil

**Comment by Jomagrax** [comment]
Sorry about the command, I have been using both (multiqc -m fastqc and multiqc .) and I obtain the same result.

I have reinstalled matplotlib  and I get a new error message:
```

 multiqc .
[INFO   ]         multiqc : This is MultiQC v1.10.dev0
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching   : /home/superuser/jose/rna-seq_documentation/tutorial_griffith/fastqc
In /home/superuser/miniconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The text.latex.preview rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /home/superuser/miniconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The mathtext.fallback_to_cm rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /home/superuser/miniconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: Support for setting the 'mathtext.fallback_to_cm' rcParam is deprecated since 3.3 and will be removed two minor releases later; use 'mathtext.fallback : 'cm' instead.
In /home/superuser/miniconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The validate_bool_maybe_none function was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /home/superuser/miniconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The savefig.jpeg_quality rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /home/superuser/miniconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The keymap.all_axes rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /home/superuser/miniconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The animation.avconv_path rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /home/superuser/miniconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The animation.avconv_args rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete


```

**Comment by ewels** [comment]
Different error messages, but the same cause I think - conflicting matplotlib installations.

Still no logs found though: `No analysis results found. Cleaning up..`

Are you running this on the FastQC `.zip` output files? Not just directly on `.fastq.gz` sequence files?

Phil

**Comment by Jomagrax** [comment]
I am running It on the fastqc .html report files I attached earlier

**Comment by ewels** [comment]
Yeah, you need a zip file or the `fastqc_data.txt` file. Docs: https://multiqc.info/docs/#fastqc

**Comment by Jomagrax** [comment]
I get It now, I hope I'm not bothering you too much, but do you know how to obtain de ```fastqc_data.txt  ```file?
Because all I can get from Fastqc is the html report.

**Comment by ewels** [comment]
Off the top of my head, I think FastQC should usually generate both a HTML file and a zip file alongside one another by default.. The zip file should contain `fastqc_data.txt`. MultiQC can work with the zip file or the extracted contents, either is fine.
