### ISSUE TITLE
Add button to copy table contents

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#126]
Add a GitHub style button to copy the contents of the general statistics table. Maybe also one to trigger a download.

**Comment by avilella** [comment]
+1. It was mentioned as a useful feature to me recently.

**Comment by ewels** [comment]
Yup, I have been thinking about it for a different project but figured it could be useful here too. Should be relatively easy to implement using [clipboard.js](https://zenorocha.github.io/clipboard.js/)
