### ISSUE TITLE
FixedFormatter should only be used together with FixedLocator

### ISSUE THREAD

**Issue by sunta3iouxos** [ewels/MultiQC#1260]
**Description of bug:**
while running multiQC in for generating an condensed fastqc report I got the following:

**MultiQC Error log:**

```
miniconda3/envs/py3.7/bin/multiqc --force --outdir /data/html/ngs_reports/qc/200702_A00620_0096_BHCY3JDSXY_Juli1/COVIDWGS /data/html/ngs_reports/qc/200702_A00620_0096_BHCY3JDSXY_Juli1/COVIDWGS
[INFO   ]         multiqc : This is MultiQC v1.9
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching   : /data/html/ngs_reports/qc/200702_A00620_0096_BHCY3JDSXY_Juli1/COVIDWGS
[INFO   ]          fastqc : Found 168 reports
miniconda3/envs/py3.7/lib/python3.7/site-packages/multiqc/plots/bargraph.py:451: UserWarning: FixedFormatter should only be used together with FixedLocator
  axes.set_xticklabels(['{:.0f}%'.format(x) for x in vals])
[ERROR  ]       linegraph : ############### Error making MatPlotLib figure! Falling back to HighCharts.
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : ../../../../../data/html/ngs_reports/qc/200702_A00620_0096_BHCY3JDSXY_Juli1/COVIDWGS/multiqc_report.html
[INFO   ]         multiqc : Data        : None
[INFO   ]         multiqc : MultiQC complete
```

```

```

**File that triggers the error:**

**MultiQC run details (please complete the following):**
* Command used to run MultiQC: multiqc --force --outdir /path/to /path/in 
* MultiQC Version: MultiQC v1.9
* Operating System: Linux anubis2.ccg.uni-koeln.de 2.6.32-573.22.1.el6.x86_64 #1 SMP Thu Mar 17 03:23:39 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux

* Python Version:  Python 3.7
* Method of MultiQC installation: conda

**Additional context**

**Comment by sunta3iouxos** [comment]
Hi,
and sorry for the trouble, apparently the error arrived not correctly loading the python/conda environment on remote server. As soon, as the env was loading the error stopped showing up.
If the problem persists I will return with further information on the matter.
Thank you.

**Comment by ewels** [comment]
Thanks for letting me know!
