### ISSUE TITLE
Handling reports with the same name in subfolders

### ISSUE THREAD

**Issue by Caffeinated-Code** [ewels/MultiQC#1262]
Hi, 
I have one directory for each sample that contains all the reports and processed data for that particular sample. 
However, the names of these reports are the same within all sample directories. So MultiQC recognizes it as only one report.

![image](https://user-images.githubusercontent.com/47283105/89048650-1e5b4900-d31e-11ea-84a7-197514e9de8f.png)

Can we have an option where MultiQC can recognize them as distinct reports by conjugating report names with sample directory names?

I could try renaming all these reports with sample names as prefix but we have a lot of data already processed and saved this way. It would be easier if I could find a way to get MultiQC to recognize them.

**Comment by ewels** [comment]
Maybe take a bit of a closer look at the documentation ;)

You’re looking for `-d` 👍🏻
