### ISSUE TITLE
Request for Module BCL Convert.

### ISSUE THREAD

**Issue by PaulAONeill** [ewels/MultiQC#1266]
**Tool Details**
* Name of tool: BCL Convert
* Tool homepage: https://support.illumina.com/sequencing/sequencing_software/bcl-convert/documentation.html?langsel=/us/
* Tool description: Illumina's replacement for bcl2fastq
* Data suitable for MultiQC plot(s): see bcl2fastq module + index hopping stats
* Most interesting data for General Stats table: see bcl2fastq module + index hopping stats is interesting for us.

**Tool output:**

files are put into 2 directories Logs and Reports non of these names are variable or specified at runtime.
Logs/
Logs/Errors.log
Logs/Warnings.log
Logs/Info.log
Logs/FastqComplete.txt
Reports/
Reports/SampleSheet.csv
Reports/RunInfo.xml
Reports/fastq_list.csv
Reports/IndexMetricsOut.bin
Reports/Demultiplex_Stats.csv
Reports/Adapter_Metrics.csv
Reports/Index_Hopping_Counts.csv
Reports/Top_Unknown_Barcodes.csv

[bcl-convert.output.zip](https://github.com/ewels/MultiQC/files/5040976/bcl-convert.output.zip)

Hi Phil,

Please let me know if you need any more details. The files included are from a v simple run.
If you need me to do some testing on more complex runs let me know.

v best

Paul

**Comment by matthdsm** [comment]
xref #1381
