### ISSUE TITLE
Adding a column in Statistics table of a Module in Multiqc

### ISSUE THREAD

**Issue by humbleflowers** [ewels/MultiQC#1267]
I am working with quast data. I see some of the data in report.tsv of quast is not being added on multiqc quast statistics table.
Can I know anyway to add it? couldn't find right information on documentation.
Thanks. Any help is appreciated.

**Comment by ewels** [comment]
Hi @humbleflowers,

Sorry for the slow response. I'm afraid that it is not possible to add columns to tables from MultiQC modules without editing the source code.

If you're still interested in this, please submit a new issue describing what additional columns you would like and for what reasons. We can then look into either adding them for all users or in a configurable way.

Phil
