### ISSUE TITLE
Homozygous and Heterozygous sites from Bcftools

### ISSUE THREAD

**Issue by TomaszSuchan** [ewels/MultiQC#1272]
**Description of bug:**

- Number of **Hom**ozygous and **Het**erozygous sites from Bcftools stats in the table are based on the last sample only.
- Homozygotes concordant with the reference are not counted towards homozygotes in the table

This is from the report table:
```
Sample Name | Vars | **Hom** | **Het** | SNP | Indel | Ts/Tv | % Dups | Error rate | M Non-Primary | M Reads Mapped | % Mapped | M Total seqs | % Duplication | GC content | % PF
139 | **48** | **3** | 112 | 16 | 1.10 |   |   |   |   |   |   |   |   |  
```

The relevant section of bcftools stats report:
```
# PSC	[2]id	[3]sample	[4]nRefHom	[5]nNonRefHom	[6]nHets	[7]nTransitions	[8]nTransversions	[9]nIndels	[10]average depth	[11]nSingletons	[12]nHapRef	[13]nHapAlt	[14]nMissing
PSC	0	PT2_taa_port	14	66	29	47	48	15	5.3	37	0	0	5
PSC	0	PT3_taa_port	19	41	16	31	26	9	3.7	8	0	0	48
PSC	0	PT1_taa_port	19	**48**	**3**	25	26	5	3.1	5	0	0	60
```

**File that triggers the error:**
[vcf_summary_filtered.txt.zip](https://github.com/ewels/MultiQC/files/5087284/vcf_summary_filtered.txt.zip)

**MultiQC run details:**
* Command used to run MultiQC: `multiqc . --ignore .snakemake -f`
* MultiQC Version: MultiQC v1.10.dev0
* Operating System: macOS Catalina 10.15
* Python Version: Python 3.7.3 (conda-forge)
* Method of MultiQC installation: manual

**Comment by ewels** [comment]
Thanks for reporting this @TomaszSuchan!

Side note: I guess `--ignore .snakemake` will be the same for all Snakemake users? Should I add that to the default list of MultiQC ignore paths?

**Comment by TomaszSuchan** [comment]
Happy to help!

> Side note: I guess --ignore .snakemake will be the same for all Snakemake users? Should I add that to the default list of MultiQC ignore paths?

Yes, I think so, processing it takes a lot of time and there should not be any log files there.

**Comment by ewels** [comment]
ok nice, added to the list of paths to ignore by default in the dev version on `master`. If you could [try out the dev version](https://github.com/ewels/MultiQC#installation) and confirm that it works as expected then that would be brilliant 👍🏻

**Comment by ewels** [comment]
@TomaszSuchan I've come back to look at this a few times but been scared off each time, I fear that it's not a trivial fix. Your example file looks quite different to the [examples I already have](https://github.com/ewels/MultiQC_TestData/tree/master/data/modules/bcftools), and I think the module code will probably need a fair bit of work to handle multi-sample VCF files properly.

If you think you know how to resolve this, a PR would be much appreciated!

**Comment by ewels** [comment]
Ah, just rediscovered duplicate issue #1087 and associated PR #1271 for exactly this issue! They were on hold as they needed some example data, which you have happily provided in this issue 🎉 

I'll close this now as a duplicate note in the others that we now have example data.

**Comment by ewels** [comment]
I see now that I was getting confused about authors (late-night code review is risky!) - you made the PR and the issue with the example data, I'd just never joined the dots. Apologies for being slow here.
