### ISSUE TITLE
Toggle button for plot y axis limits

### ISSUE THREAD

**Issue by avilella** [ewels/MultiQC#128]
Would it be possible to have a vertical range zoom for the M-Bias plots, so that one can zoom in to, say, the 80-60% methylation range in the vertical axis of an existing page. Currently there is a horizontal range zoom as per the other plots, which is still useful.

**Comment by ewels** [comment]
I've tried putting in x-y zooms on plots before, but I find that it usually makes the interface more confusing (especially as all other plots only have an x zoom).

What I could do is remove the 0-100% range fix on the plot, then zooming will autoscale the y axis. However, I'm wary of doing this as it makes the plot harder to interpret quickly if you're used to looking at a lot of these.

I guess one way to satisfy both of these would be to add a button which toggles the y axis limits. Would that work?

Phil

**Comment by avilella** [comment]
Yep, extra toggle button would work.

**Comment by avilella** [comment]
There is another plot that would benefit from this, like the Genome Fraction Coverage. Maybe it could be done for all of them and let the user decide where to apply it.

**Comment by ewels** [comment]
Yup, that's what I was thinking - show the toggle whenever there is a y axis range set.

**Comment by ewels** [comment]
Hi @avilella,

Maybe you could give this for a spin? Seems to work well in my hands, hopefully it does what you were looking for..

Phil

**Comment by avilella** [comment]
Installing head master now for testing...

**Comment by avilella** [comment]
I tried it on a couple of reports, and it works as advertised! Thanks ;-)

**Comment by ewels** [comment]
Great, thanks for testing!
