### ISSUE TITLE
feature request: flip order in bismark deduplication barplots

### ISSUE THREAD

**Issue by avilella** [ewels/MultiQC#129]
This is a small feature request to flip the order of the two segments of the barplots in the bismark deduplication section, so that the black (or dark) segment for duplicated fraction appears on the left, and the usable fraction in blue appears on the right. That would make it slightly more readable to the user in my opinion, even on a small screen.

**Comment by ewels** [comment]
Is this because of the colours or because of what the segments represent? Personally, I prefer having the usable segment on the left, with other unused segments to the right of that. All of the other bar plots follow this method.

**Comment by avilella** [comment]
It's more because if the duplicated fraction is small, the sample labels
are on the left, and the small differences are on the right of the plot,
and one has to jump from left to right to link sample names to size of the
dark segment.

Not all sample preps give good deduplicated fractions with small duplicated
dark segments, but some do ;-)

**Comment by ewels** [comment]
Ok, I see where you're coming from. But I think I'd rather leave it as it is and keep the same pattern as the rest of the plots. Some of my duplication plots have very tiny numbers of unique reads anyway :wink:

You can always use sample highlighting and mouse hover tooltips to help with bar identification.
