### ISSUE TITLE
MultiQC--dragen-exon erro

### ISSUE THREAD

**Issue by fanyucai1** [ewels/MultiQC#1290]
hi team:
 
I am from illumina. when i run the MultiQC using WGS data, there is no problem.

But when i run using WES data(or taeget), the dragen outfile lists should be as following:
```
*.target_bed_contig_mean_cov.csv
*.target_bed_contig_mean_cov.csv
*.target_bed_coverage_metrics.csv
*.target_bed_fine_hist.csv
*.target_bed_hist.csv
*.target_bed_overall_mean_cov.csv
```

It is different from:
```
*.wgs_contig_mean_cov.csv
*.wgs_coverage_metrics.csv
*.wgs_fine_hist.csv
*.wgs_hist.csv
*.wgs_overall_mean_cov.csv
```

**Comment by ewels** [comment]
Thanks for reporting this @fanyucai1. Do you have any example files that we could use for testing?

@vladsaveliev have you tried running the MultiQC module with these files?

Phil

**Comment by fanyucai1** [comment]
> Thanks for reporting this @fanyucai1. Do you have any example files that we could use for testing?
> 
> @vladsaveliev have you tried running the MultiQC module with these files?
> 
> Phil

Thanks @ewels for your reply. 
Public example files link:https://github.com/fanyucai1/dragen_v3.7/tree/master/dragen_example_outfile

**Comment by vladsaveliev** [comment]
Hi @fanyucai1 and Phil! 

I haven't tested the module with exome sequencing runs before. Thanks for the examples @fanyucai1 shared, added a few adjustments to support QC files with the `target_bed_` prefix. Also added those into MultiQC_TestData at https://github.com/ewels/MultiQC_TestData/pull/182 if you don't mind.

**Comment by ewels** [comment]
Thanks both! That's merged. @fanyucai1 if you could test out the development version on some data to confirm that the code now works, that would be brilliant.

Phil
