### ISSUE TITLE
Add support for CollectIlluminaLaneMetrics

### ISSUE THREAD

**Issue by aledj2** [ewels/MultiQC#1291]
**Tool Details**
* Name of tool: Picard CollectIlluminaLaneMetrics
* Tool homepage: https://gatk.broadinstitute.org/hc/en-us/articles/360042477172-CollectIlluminaLaneMetrics-Picard-
* Tool description: Picard function to calculate cluster density
* Data suitable for MultiQC plot(s): One value per lane. The illumina SAS software rounds this to the nearesr 1000
* Most interesting data for General Stats table: Not sure general stats table is relevant as not sample specific

**Tool output:**

[999999_NB552085_0077_AHYNCMAFXY.illumina_lane_metrics.zip](https://github.com/ewels/MultiQC/files/5209612/999999_NB552085_0077_AHYNCMAFXY.illumina_lane_metrics.zip)

* Log filename pattern: `*.illumina_lane_metrics`

I believe there is a range for ideal densities (> 170 K/mm2 and < than 250 K/mm) but not sure if this is an internal range or suggested by Illumina.

**Comment by aledj2** [comment]
Hi Phil. I've made a start to this but I'd like some advice as to how to structure this/where to put the code. I was following the documentation about creating new modules but then realised how the existing picard modules have been written.
The metrics produced by this tool doesn't really sit with the usual post alignment picard stats but it is a picard tool...

**Comment by ewels** [comment]
Hi @aledj2,

Sorry for the slow reply. Any Picard tool should be part of the Picard module. The pre- / post-alignment categories are a bit dated now to be honest and will probably be removed soon.

Are you sure that the filenames are really called `*.illumina_lane_metrics` for all users? Picard doesn't usually set filename suffixes does it?

Phil

**Comment by matthdsm** [comment]
xref #1336
