### ISSUE TITLE
Expose additional statistics in Picard Alignment Summary

### ISSUE THREAD

**Issue by Redmar-van-den-Berg** [ewels/MultiQC#1293]
**Is your feature request related to a problem? Please describe.**
The Picard Alignment Summary currently only shows the number of aligned reads in the barchart. This makes sense for Illumina data, where all reads are the same size. However, for long read sequencing, the number of aligned reads is not so relevant, and the number of aligned bases or the mean read size is more relevant.

**Describe the solution you'd like**
Add additional datasets to the picard Alignment Summary section. This way, the default behaviour will be the same (show the number of aligned reads), but users can switch over to number of aligned bases or mean read length, if this is more relevant for them.

**Describe alternatives you've considered**
I was also considering adding additional Read based statistics to the graph but making them invisible by default (like they are when you click on the legend in the HTML report), but I could not find a way to do this in the documentation.

**Comment by ewels** [comment]
There could also be a config option for this to allow it to be set as default when running routinely with this kind of data.

**Comment by Redmar-van-den-Berg** [comment]
I'm not sure if a configuration setting to change the default is a good solution. Even for long reads, you still want to have an idea of the number of aligned reads. Having buttons to switch to the additional data is also easier to use then having a config option. 

Depending on the experimental setup, having the mean read length and total number of aligned bases might also be relevant for people working with Illumina data, so it would be nice to have this data available for all users.
