### ISSUE TITLE
Strange error message FixedFormatter should only be used together with FixedLocator

### ISSUE THREAD

**Issue by sofiahaglund** [ewels/MultiQC#1297]
Hi!

I got a strange error message while creating a MultiQC report (v.1.9) using our staging environment, `FixedFormatter should only be used together with FixedLocator` from bargraph.py:

```
/lupus/ngi/staging/200918.3b4d297/sw/anaconda/envs/NGI_py3/lib/python3.8/site-packages/multiqc/plots/bargraph.py:451: UserWarning: FixedFormatter should only be used together with FixedLocator
 axes.set_xticklabels(['{:.0f}%'.format(x) for x in vals])
```
The plots were generated and everything looks good, except I got this message, not sure what it means. It's a minor issue I'm sure...

**Comment by guidohooiveld** [comment]
To keep the issue tracker 'clean': please be informed that the same issue has again been reported; see here: https://github.com/ewels/MultiQC/issues/1323

**Comment by ewels** [comment]
Thanks both - closing in favour of #1323
