### ISSUE TITLE
 Oops! The 'snpsplit' MultiQC module broke... 

### ISSUE THREAD

**Issue by FelixKrueger** [ewels/MultiQC#1298]
**Description of bug:**
MultiQC fails to parse SNPsplit yaml files. The MultiQC report is generated, but lacks the SNPsplit section.

**MultiQC Error log:**

```
 multiqc .
[INFO   ]         multiqc : This is MultiQC v1.9
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching   : /bi/group/bioinf/Irene_Herraez/200915_Sanger_download/hybrid
Searching 9224 files..  [####################################]  100%          
[INFO   ]         bowtie2 : Found 384 reports
[ERROR  ]         multiqc : Oops! The 'snpsplit' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    ./lane1_WT_E10.5_Hybrid_B6_Cast_B11_GAGCCAAT_L001_4198STDY8721569_CAST_EiJ_N-masked_GRCm38_hisat2.SNPsplit_report.yaml
============================================================
Module snpsplit raised an exception: Traceback (most recent call last):
  File "/bi/apps/multiqc/1.9/lib/python3.7/site-packages/multiqc-1.9-py3.7.egg/multiqc/multiqc.py", line 569, in run
    output = mod()
  File "/bi/apps/multiqc/1.9/lib/python3.7/site-packages/multiqc-1.9-py3.7.egg/multiqc/modules/snpsplit/snpsplit.py", line 29, in __init__
    parsed_log = self.parse_new_snpsplit_log(f)
  File "/bi/apps/multiqc/1.9/lib/python3.7/site-packages/multiqc-1.9-py3.7.egg/multiqc/modules/snpsplit/snpsplit.py", line 58, in parse_new_snpsplit_log
    data = next(yaml.load_all(f['f'], Loader=yaml.SafeLoader))
StopIteration
============================================================
[INFO   ]        cutadapt : Found 768 reports
[INFO   ]    fastq_screen : Found 384 reports
[INFO   ]          fastqc : Found 1536 reports
[INFO   ]         multiqc : Compressing plot data
[WARNING]         multiqc : Previous MultiQC output found! Adjusting filenames..
[WARNING]         multiqc : Use -f or --force to overwrite existing reports instead
[INFO   ]         multiqc : Report      : multiqc_report_1.html
[INFO   ]         multiqc : Data        : multiqc_data_1
[INFO   ]         multiqc : MultiQC complete
```

**File that triggers the error:**
Might have to do a test tomorrow to find the culprit.

**MultiQC run details (please complete the following):**
* Command used to run MultiQC: 
* MultiQC Version: 
* Operating System: 
* Python Version: 
* Method of MultiQC installation: 

**Additional context**
I just read on Gitter that that you are back from holidays and are keen to work on MultiQC :) (before fixing SRA-explorer.

Welcome back, and thanks!
Felix

**Comment by ewels** [comment]
You have the likely candidate in the log:

```
  If possible, please include a log file that triggers the error - the last file found was:
    ./lane1_WT_E10.5_Hybrid_B6_Cast_B11_GAGCCAAT_L001_4198STDY8721569_CAST_EiJ_N-masked_GRCm38_hisat2.SNPsplit_report.yaml
```

SRA-explorer is fixed! See https://github.com/ewels/sra-explorer/pull/27

**Comment by FelixKrueger** [comment]
Awesome news about SRA-Explorer! I tried to find the issue with the yaml file, and I assume it must have been a buffering issue for writing out the yaml files (3 out of 1153 files were 0-sized...). Let me take this off the list of things you need to look at, and assume MultiQC works flawlessly (and why wouldn't it?). 

If you could take another look at the missing unmapped statistic for paired-end alignments with Bowtie2 and HISAT2 for a new release, that would be much appreciated!

Cheers, Felix

**Comment by ewels** [comment]
Might be nice to check for 0-sized files in the module to avoid this ugly error - could be an easy first PR if you fancy it..? 😉

**Comment by FelixKrueger** [comment]
Yes, I think I could do that... Now that I am 'proficient' in :Python: 😺
