### ISSUE TITLE
Displaying a table as it is with multiqc

### ISSUE THREAD

**Issue by sdjebali** [ewels/MultiQC#1299]
Dear all,

Thanks for the very nice tool ! It is very very useful to have it in a pipeline !

I have a question more than an issue.

I want to display some summary statistics tables that I have.

I have seen it was possible to do it like in this example 
https://github.com/ewels/MultiQC_TestData/blob/master/data/custom_content/embedded_config/table_headers_mqc.txt

however in my case the rows from my table do not represent sequencing samples

Is it still possible to display the table ?

FYI my table is like this
```tsv
trset     nbex     nbdistinctex  nbtr   nbgn   nbintrons  nbdistinctintrons  nbexpertr  nbexpergn  nbdistinctexpergn  nbtrpergn  nbintronpertr  nbintronpergn  nbdistinctintronpergn
ref       536859   262635        49448  25880  487411     217796             10.857     20.7442    10.1482            1.91066    9.85704        18.8335        8.41561
ref_expr  357234   194945        29715  15646  327519     167254             12.022     22.8323    12.4597            1.89921    11.022         20.9331        10.6899
str       1009341  315571        88266  26559  921075     256531             11.4352    38.0037    11.8819            3.32339    10.4352        34.6803        9.65891
str_expr  805853   254904        66446  17277  739407     212563             12.1279    46.6431    14.754             3.84592    11.1279        42.7972        12.3032
```

Best regards,
Sarah Djebali

**Comment by ewels** [comment]
Hi @sdjebali,

In short, yes!  You can plot whatever data you want 😀 

I pasted your example into a file called [issue_1299_mqc.txt](https://github.com/ewels/MultiQC/files/5748924/issue_1299_mqc.txt) (note the `_mqc` suffix) and MultiQC ran fine:

```console
$ multiqc issue_1299_mqc.txt
[INFO   ]         multiqc : This is MultiQC v1.10.dev0 (a946dc1)
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching   : /Users/ewels/Downloads/mqc_test/issue_1299_mqc.txt
[INFO   ]  custom_content : issue_1299: Found 4 samples (bargraph)
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete
```

![mqc_hcplot_yhkplnscfo](https://user-images.githubusercontent.com/465550/103246102-91ff9180-4962-11eb-9681-86dc535afa5b.png)


See report: [multiqc_report.html.zip](https://github.com/ewels/MultiQC/files/5748929/multiqc_report.html.zip)

Phil
