### ISSUE TITLE
Add Trimmomatic support

### ISSUE THREAD

**Issue by remiolsen** [ewels/MultiQC#13]
Trimmomatic, yes. Also one of those tools that writes to stdout or a user-given log file.

**Comment by ewels** [comment]
Hey @remiolsen,

Do you have any example reports that you could send to me for this? Preferably ok to publish in the public test data repo, but you can just e-mail me private reports otherwise.

Phil

**Comment by ewels** [comment]
No worries, found some..

**Comment by ewels** [comment]
@remiolsen: I have log file output from Trimmomatic in paired end mode, but not single end. Do you have an example single end log file output?

**Comment by ewels** [comment]
See [example](http://www.usadellab.org/cms/?page=trimmomatic) Trimmomatic command:
```
java -jar trimmomatic-0.35.jar \
    PE \
    -phred33 \
    input_forward.fq.gz \
    input_reverse.fq.gz \
    output_forward_paired.fq.gz \
    output_forward_unpaired.fq.gz \
    output_reverse_paired.fq.gz \
    output_reverse_unpaired.fq.gz \
    ILLUMINACLIP:TruSeq3-PE.fa:2:30:10 \
    LEADING:3 \
    TRAILING:3 \
    SLIDINGWINDOW:4:15 \
    MINLEN:36
```

Single end is similar:
```
java -jar trimmomatic-0.35.jar \
    SE \
    -phred33 \
    input.fq.gz \
    output.fq.gz \
    ILLUMINACLIP:TruSeq3-SE:2:30:10 \
    LEADING:3 \
    TRAILING:3 \
    SLIDINGWINDOW:4:15 \
    MINLEN:36
```

The [stdErr output](https://github.com/ewels/MultiQC_TestData/blob/a240950909d2b36acc47e3887eb40bddde8ddbb9/data/modules/trimmomatic/paired_end/1_P1888_101_1_trimmomatic.stdErr) contains the command that has been run in the first line, so we can get `s_name` from the first fastq filename found.

**Comment by remiolsen** [comment]
Makes sense. Sorry, I lost attention to this but I don't run this on single ends.

**Comment by ewels** [comment]
No problem! Ok, written at last! 7th september... it's been a while coming :)
