### ISSUE TITLE
feature request: coverage histogram barplot vs lines switch

### ISSUE THREAD

**Issue by avilella** [ewels/MultiQC#130]
This is a feature request to add a switch to the coverage histogram where it flips between a clustered barplot or the current lines histogram at the user's request. There are datasets that look more discrete in nature and the lines histogram plots type are difficult to read.

**Comment by ewels** [comment]
Barplots are difficult when representing multiple datasets in one plot, as they will overlap. This is why I have used line plots for all x-y datasets. I can't see an elegant way to get around this I'm afraid.
