### ISSUE TITLE
Add horizontal line to scatter plot

### ISSUE THREAD

**Issue by syan1** [ewels/MultiQC#1301]
**Is your feature request related to a problem? Please describe.**

Add horizontal and vertical line to scatter plot

Apologies for my ignorance but I couldn't find how this could be done in the docs? Tried adding extra series like a lineplot but couldn't get it to display. Thanks!

**Comment by ewels** [comment]
Hi @syan1,

If you're talking about in a MultiQC module / code that you're writing, then yes - the docs are in under [line graph](https://multiqc.info/docs/#line-graphs) (scatter plots share most of the code). You're looking for `yPlotLines` and `xPlotLines`:

```python
    'yPlotLines': None,          # Highlighted background lines. See http://api.highcharts.com/highcharts#yAxis.plotLines
    'xPlotLines': None,          # Highlighted background lines. See http://api.highcharts.com/highcharts#xAxis.plotLines
```

They aren't used by loads of MultiQC modules, but you should be able to find a few examples. eg:

https://github.com/ewels/MultiQC/blob/696cb1b8f5c2eec2258ac608098e5658cafefec0/multiqc/modules/deeptools/plotProfile.py#L37

I hope this helps!

Phil
