### ISSUE TITLE
GATK VariantEval uses the full filename as sample

### ISSUE THREAD

**Issue by uros-sipetic** [ewels/MultiQC#1307]
**Description of bug:**
When providing GATK VariantEval results to MultiQC, it treats the full filename as the sample name. So, if combined with additional report files from other tools, the MultiQC report will essentially treat them as two different samples instead of one. 

For example, providing MultiQC with these three files:

1. `my_sample.insert_size_metrics.txt` (from Picard)
2. `my_sample.rna_metrics.txt` (from Picard)
3. `my_sample.var_eval.txt` (from GATK VariantEval)

will result in MultiQC treating this a having two different samples: `my_sample` and `my_sample.var_eval`.

The VariantEval table doesn't really offer much as to how to best tackle this if running for a single sample. 
Perhaps doing the same thing as with the GATK BQSR module (just stripping the extension of) would be more suitable here?

Or is this current behavior expected? Or I'm misusing it somehow :) 

NOTE: the extension for VariantEval is user-defined (doesn't necessarily have to be `.var_eval.txt`)

**File that triggers the error:**
[my_sample.insert_size_metrics.txt](https://github.com/ewels/MultiQC/files/5302025/my_sample.insert_size_metrics.txt)
[my_sample.rna_metrics.txt](https://github.com/ewels/MultiQC/files/5302026/my_sample.rna_metrics.txt)
[my_sample.var_eval.txt](https://github.com/ewels/MultiQC/files/5302027/my_sample.var_eval.txt)

**MultiQC run details:**
* Command used to run MultiQC: `multiqc .`
* MultiQC Version: MultiQC 1.9
* Operating System: ubuntu 14.04
* Python Version: Python 3.5
* Method of MultiQC installation: pip

EDIT: I attached these 3 files as an example for testing this out to see what I mean

**Comment by uros-sipetic** [comment]
Also just one more question, while we're on the topic of VariantEval
The MultiQC module will work with the default VariantEval parameters, i.e. it won't/can't summarize/plot any additional --eval-module or --stratification-module results?

**Comment by ewels** [comment]
Hi @uros-sipetic,

Please see the documentation about sample name cleaning: https://multiqc.info/docs/#sample-name-cleaning

In short, using the following config should get your samples to line up properly in your table:

```yaml
extra_fn_clean_exts:
  - '.var_eval'
```

I don't know about your second question sorry. Give it a try! Just make sure to check whatever MultiQC reports against the original data to make sure that it's giving you sensible results before trusting it across a lot of samples :)

I'll close this now, but feel free to comment or create a new issue if you hit any problems or think any MultiQC defaults should be tweaked.

Thanks,

Phil
