### ISSUE TITLE
Top left corner hyperlink

### ISSUE THREAD

**Issue by davetang** [ewels/MultiQC#1311]
The hyperlink on the top left corner seems to be automatically generated each time I copy the MultiQC HTML file from one place to another.

Is there a way of turning this feature off? I would like the link to remain static and linked to the directory where the HTML was first generated.

I went through the [documentation](https://multiqc.info/docs/) but couldn't find any information on this.

I'm using `multiqc, version 1.10.dev0`.

Thanks!
Dave

**Comment by ewels** [comment]
Hi @davetang,

I'm a little confused sorry - could you provide a little more info?

If you're talking about the MultiQC logo in the top of the left sidebar, that links to `#` - that's a softlink that makes the browser scroll to the top of the page. It is relative only to the current page and doesn't link anywhere external.

Phil

**Comment by ewels** [comment]
Closing this issue now, if it's not resolved then please create a new issue with a screenshot of the part of the report that you're talking about and some examples of the links that it goes to and what you would like instead.

Thanks,

Phil

**Comment by davetang** [comment]
Hi @ewels,

thanks for the reply and sorry for not being clear. I had scp'ed a MultiQC report from the compute server to my web server and when I downloaded it from my web server and opened it locally, the hyperlink from the MultiQC logo was still using the URL from my website. In the screenshot below, I am opening the report downloaded to my desktop but the hyperlink from the MultiQC logo (shown at the bottom of the page) is to the location I had scp'ed the report.

<img width="585" alt="Screen Shot 2020-12-29 at 08 49 43" src="https://user-images.githubusercontent.com/2980289/103249524-06fab780-49b3-11eb-857c-3ec017ab9413.png">

I was just wondering if I could simply turn this hyperlink off, so it doesn't show where I had uploaded the file.

Cheers,
Dave

**Comment by ewels** [comment]
Hi Dave,

This is super strange. You can see the code for the link here: https://github.com/ewels/MultiQC/blob/aa7a88a22d8abc11a9d1f2047464769c5e7c520a/multiqc/templates/default/nav.html#L18

MultiQC does not know and cannot know the past locations of the report.

My guess is that something external to MultiQC is messing with the link to make it absolute like that. How are you downloading it? Is it possible to make a link that I could test, and/or attach a report to this issue that is affected (zip it to get GitHub to allow the file type).

Phil

**Comment by davetang** [comment]
Hi Phil,

I think the problem is caused by using the "Save Page As" function of my web browser when saving the MultiQC report from my web server. I will just download the file from my server in another manner to avoid this problem.

Thanks for your help,
Dave

**Comment by ewels** [comment]
aaaah right, yeah you can't do that 😅 Web browsers do all kinds of weird things when they save web pages. The report should be self-contained and portable if downloaded directly as you say though 👍🏻
