### ISSUE TITLE
Save each plot separately as independent interactive html

### ISSUE THREAD

**Issue by Nitin123-4** [ewels/MultiQC#1315]
Can we somehow save each plot separately? Maybe multiple separate interactive images ??

**Comment by ewels** [comment]
Hi @Nitin123-4,

In short, yes. Try `-p`. Docs: https://multiqc.info/docs/#exporting-plots

Plots are saved as images and are not interactive. If you want them to be interactive then you have to just use the MultiQC report (or the exported data in excel).

Note that I am intending to make MultiQC compatible with usage within scripts / Jupyter Notebooks soon. One of the main reasons for this is to allow interactive plots to be generated as required within an analysis notebook. This is on the roadmap but not done yet.

Phil
