### ISSUE TITLE
DamgeProfiler module broke due to invalid literal

### ISSUE THREAD

**Issue by lczech** [ewels/MultiQC#1318]
**Description of bug:**
Using [DamageProfiler 0.5.0](https://github.com/Integrative-Transcriptomics/DamageProfiler), I get a result file that breaks MultiQC, see below.

**MultiQC Error log:**
```
[INFO   ]         multiqc : This is MultiQC v1.9 (0a4d1d2)
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching   : /home/lczech/Projects/grenepipe/test/qc/fastqc
[INFO   ]         multiqc : Searching   : /home/lczech/Projects/grenepipe/test/qc/samtools-flagstats
[INFO   ]         multiqc : Searching   : /home/lczech/Projects/grenepipe/test/qc/samtools-stats
[INFO   ]         multiqc : Searching   : /home/lczech/Projects/grenepipe/test/qc/qualimap
[INFO   ]         multiqc : Searching   : /home/lczech/Projects/grenepipe/test/damageprofiler/A-1
[INFO   ]         multiqc : Searching   : /home/lczech/Projects/grenepipe/test/mapdamage/B-1
[INFO   ]         multiqc : Searching   : /home/lczech/Projects/grenepipe/test/snpeff
[INFO   ]         multiqc : Searching   : /home/lczech/Projects/grenepipe/test/qc/dedup
[INFO   ]         multiqc : Searching   : /home/lczech/Projects/grenepipe/test/damageprofiler/B-1
[INFO   ]         multiqc : Searching   : /home/lczech/Projects/grenepipe/test/damageprofiler/B-2
[INFO   ]         multiqc : Searching   : /home/lczech/Projects/grenepipe/test/trimmed
[INFO   ]         multiqc : Searching   : /home/lczech/Projects/grenepipe/test/mapdamage/A-1
[INFO   ]         multiqc : Searching   : /home/lczech/Projects/grenepipe/test/mapdamage/B-2
[INFO   ]        qualimap : Found 3 BamQC reports
[INFO   ]          snpeff : Found 1 reports
[ERROR  ]         multiqc : Oops! The 'damageprofiler' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    damageprofiler/B-2/dmgprof.json
============================================================
Module damageprofiler raised an exception: Traceback (most recent call last):
  File "/home/lczech/Projects/grenepipe/conda-env/19f011f0/lib/python3.7/site-packages/multiqc/multiqc.py", line 569, in run
    output = mod()
  File "/home/lczech/Projects/grenepipe/conda-env/19f011f0/lib/python3.7/site-packages/multiqc/modules/damageprofiler/damageprofiler.py", line 85, in __init__
    plot = self.lgdistplot(self.lgdist_fw_data, 'Forward')
  File "/home/lczech/Projects/grenepipe/conda-env/19f011f0/lib/python3.7/site-packages/multiqc/modules/damageprofiler/damageprofiler.py", line 225, in lgdistplot
    data[s_name] = {int(d): int (dict_to_use[s_name][d]) for d in dict_to_use[s_name]}
  File "/home/lczech/Projects/grenepipe/conda-env/19f011f0/lib/python3.7/site-packages/multiqc/modules/damageprofiler/damageprofiler.py", line 225, in <dictcomp>
    data[s_name] = {int(d): int (dict_to_use[s_name][d]) for d in dict_to_use[s_name]}
ValueError: invalid literal for int() with base 10: '31.0'
============================================================
[INFO   ]          picard : Found 3 MarkDuplicates reports
[INFO   ]        samtools : Found 3 stats reports
[INFO   ]        samtools : Found 3 flagstat reports
[INFO   ]           fastp : Found 3 reports
[INFO   ]          fastqc : Found 2 reports
[INFO   ]         multiqc : Compressing plot data
[WARNING]         multiqc : Deleting    : qc/multiqc_data   (-f was specified)
[INFO   ]         multiqc : Report      : qc/multiqc.html
[INFO   ]         multiqc : Data        : qc/multiqc_data
[INFO   ]         multiqc : MultiQC complete
```

**File that triggers the error:**
[dmgprof.json.zip](https://github.com/ewels/MultiQC/files/5382300/dmgprof.json.zip)

**MultiQC run details (please complete the following):**
* Command used to run MultiQC: [Snakemake wrapper](https://snakemake-wrappers.readthedocs.io/en/stable/wrappers/multiqc.html)
* MultiQC Version: MultiQC v1.9
* Operating System: Ubuntu 18.04.5 LTS
* Python Version: Python 3.7 (probably - managed by Snakemake)
* Method of MultiQC installation: conda via Snakemake wrappers

**Additional context**

**Comment by apeltzer** [comment]
@jfy133 are we affected of this too?

**Comment by jfy133** [comment]
We've not integrated it into eager2 yet because of the whole java incompatibilites, so currently not but with 2.3 we will be.

**Comment by lczech** [comment]
@jfy133 , thanks for the quick reply! You find the json file above in my initial post, under "File that triggers the error".

Thanks for the hint to revert to 0.4.9, but it's not urgent for me, so I can wait for this to be solved properly ;-)
Let me know if you need any more of my input.

**Comment by lczech** [comment]
Addendum: Over at DamageProfiler, I had also [opened an issue about this](https://github.com/Integrative-Transcriptomics/DamageProfiler/issues/46) to make sure that all relevant people are involved. @JudithNeukamm mentioned there that the issue was recently introduced by a change in an output variable, and will be again fixed soon. 

So, if MultiQC wants to work with all versions of DamageProfiler, just reading either int or double there should fix the issue. But if waiting for the next release is also an option, maybe no change is needed at all ;-)

**Comment by jfy133** [comment]
Thanks for the JSON! Indeed it looks like it's something that should be fixed with DamageProfiler given number of basepairs shoul be integers not floats. 

Given it's fixed over at DamageProfiler, and just needs a bioconda bump once it's released (see https://github.com/Integrative-Transcriptomics/DamageProfiler/issues/45), I think we can close this for now.

**Comment by JudithNeukamm** [comment]
> But @lczech you can also revert to DamageProfiler 0.4.9 if you need results fast/is possible, there is not significant differences between 0.4.9 and 0.5.0 I believe (right JudithNeukamm?)

Right

**Comment by lczech** [comment]
Perfect, thanks all!
