### ISSUE TITLE
Adding columns to general stats

### ISSUE THREAD

**Issue by serpei** [ewels/MultiQC#1319]
Good afternoon,

It is that possible to add columns to the General stats table? I would like to see also parameters from Picard (like `PCT_UTR_BASES`, `PCT_INTRONIC_BASES`) and RSeQC (like `pe_sense` and `pe_antisense`).

Thank you

**Comment by ewels** [comment]
Hi @serpei,

I'm afraid that this is not possible without modification of the MultiQC code (pull-requests welcome).

Note that if you're desperate, you can use custom scripts to pull these metrics out yourself and format them into [Custom Content files](https://multiqc.info/docs/#custom-content) for incorporation into the General Stats table, but it's a bit of a nasty hack.

Phil
