### ISSUE TITLE
Error creating pdf in --pdf mode

### ISSUE THREAD

**Issue by nhihin** [ewels/MultiQC#1330]
**Description of bug:**
 When I run ` multiqc . --pdf -f`, it will not make the pdf file, saying that xelatex is not found. 

**MultiQC Error log:**

```
[INFO   ]         multiqc : This is MultiQC v1.9
[INFO   ]         multiqc : --pdf specified. Using non-interactive HTML template.
[INFO   ]         multiqc : Template    : simple
[INFO   ]         multiqc : Searching   : /cancer/storage/shared/Illumina_data/0_rawData/fastqc
Searching 43 files..  [####################################]  100%
[INFO   ]          fastqc : Found 14 reports
/homes/nhi.hin/.conda/envs/MULTIQC2/lib/python3.9/site-packages/multiqc/plots/bargraph.py:451: UserWarning: FixedFormatter should only be used together with FixedLocator
  axes.set_xticklabels(['{:.0f}%'.format(x) for x in vals])
[INFO   ]         multiqc : Compressing plot data
[WARNING]         multiqc : Deleting    : multiqc_report.html   (-f was specified)
[WARNING]         multiqc : Deleting    : multiqc_data   (-f was specified)
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
xelatex not found. Please select a different --pdf-engine or install xelatex
[ERROR  ]         multiqc : Error creating PDF! Pandoc returned a non-zero exit code.
[INFO   ]         multiqc : MultiQC complete
```

**File that triggers the error:**

**MultiQC run details (please complete the following):**
* Command used to run MultiQC: `multiqc . --pdf -f`
* MultiQC Version: MultiQC v.1.9
* Operating System: Linux edp-prd-lin-hpc01 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux
* Python Version: Python 3.9
* Method of MultiQC installation: conda

**Additional context**
I am running multiqc on a Conda environment that also has pandoc installed.

**Comment by ewels** [comment]
Hi @nhihin,

Do you have xelatex installed too? 😄  Maybe that should be more explicit in the docs..

See also https://github.com/ewels/MultiQC/issues/1250 for an issue about making this process easier.

Note that MultiQC reports in PDF are pretty rubbish in comparison to their HTML counterparts. I would always advise avoiding them if possible.

Phil

**Comment by ewels** [comment]
Ok, I tweaked the docs a little to explicitly say that xelatex is also installed and to quote the example error message that you got in 8df26af93398aa4a650df65fe207f8c46f03ee47 - hopefully this will be helpful for future users googling such problems.

I'll close this issue now as this isn't to do with MultiQC per-se, but rather Pandoc / LaTeX installation. I hope you got it working, apologies for the slow reply!

Phil
