### ISSUE TITLE
Expand picard metrics module with Base Calling Metrics

### ISSUE THREAD

**Issue by matthdsm** [ewels/MultiQC#1332]
Hi,

Would you be interested in expanding the support for different picard metrics? At the moment I'm particularly interested in having the outputs from  `ExtractIlluminaBarcodes`, `CollectIlluminaBasecallingMetrics` and `CollectIlluminaLaneMetrics`.

If needed I can upload examples of the output files for reference.

Thanks
Matthias

**Comment by matthdsm** [comment]
xref https://github.com/ewels/MultiQC_TestData/pull/173

**Comment by ewels** [comment]
It's always good to support more outputs! Picard is a beast of a tool so it's a bit of an impossible task to try to support all outputs it generates. So yes, generally there have been bits and pieces of support added to it as people need them.

Test data merged, would be fab if you fancy writing a PR to add support 😄 Shout if you need any pointers..

**Comment by matthdsm** [comment]
Hi Phil,

A pr is already done. You should be able to check it out in the list op PR's

Cheers
M

**Comment by matthdsm** [comment]
Xref #1336

**Comment by ewels** [comment]
Thanks @matthdsm - sorry for the very slow response times here, I've been struggling to keep up with MultiQC maintenance lately 😥 (I have a plan..).

I'm working through issues and PRs in roughly date order, starting with the oldest. I'll get to yours ASAP.

Phil
