### ISSUE TITLE
HSmetrics PCT_USABLE_BASES_ON_TARGET column

### ISSUE THREAD

**Issue by sophie22** [ewels/MultiQC#1338]
**Description of bug:**

Values in the picard output hsmetrics.tsv are (correctly) between 0 and 1 in this column. However, in the html report in the HSmetrics table, these values are not displayed as a percentage but instead on the scale of base_counts indicated by the 'Mb' in the column title and visible when configuring columns to be displayed in the html report. See screenshots attached.

Possible explanation is that this column undergoes both conversion to % as `PCT` is in the column name, but also values get multiplied by `config.base_count_multiplier` making them tiny, and only `0.0` gets displayed in the report (without the % sign). 

https://github.com/ewels/MultiQC/blob/a5168f8f490986204053fc1c524d49fddd733dfc/multiqc/modules/picard/HsMetrics.py#L281

Similarly with `PCT_USABLE_BASES_ON_BAIT`. And slightly related issue is that `ON_BAIT_VS_SELECTED` is a percentage but displayed as a decimal (as it doesn't have 'PCT' in the column name)

![pct_mb_hsmetrics](https://user-images.githubusercontent.com/15593138/98385979-8f11b000-2047-11eb-8737-8d50958e0aa4.PNG)

**MultiQC run details (please complete the following):**
* Command used to run MultiQC:  multiqc with custom config file (no changes related to HSmetrics)
* MultiQC Version:  MultiQC v1.9
* Operating System:  ubuntu 16.04
* Python Version: 3.8.1 
* Method of MultiQC installation:  running the dockerised version

**Comment by sophie22** [comment]
A related question: in the meantime is it possible to change the scale for a specific column in the config file?

**Comment by ewels** [comment]
I'm afraid not, no. You can change the `config.base_count_multiplier` of course, but that applies across the entire report.

**Comment by sophie22** [comment]
Thank you.

**Comment by ErikDanielsson** [comment]
This should be fixed in #1212. You should get the correct result if running version 1.10 or later of MultiQC.
