### ISSUE TITLE
Show plots based on GNUplot files

### ISSUE THREAD

**Issue by matthdsm** [ewels/MultiQC#1339]
Hi,

We're trying to replicate some features from the Illumina SAV using the Interop executables. Some of these produce GNUplot text files for plots. Is there a way to easily integrate these into MultiQC?

Thanks
M

**Comment by ewels** [comment]
Hi @matthdsm,

I've never really come across GNUplot files before. Doing a quick google makes me think that it is quite unlikely that MultiQC will ever properly support them as some look crazy complicated.

There is a [py-gnuplot](https://pypi.org/project/py-gnuplot/) package, so I'm not saying never, but I would put this one in the "lots of work for limited gain" category personally. MultiQC plots are very highly customised so it's not simple to convert one to the other.

Of course if these are standardised files that look similar every time and don't need full GNUplot support, then it should be comparatively trivial to with a MultiQC module that pulls out the important bits and creates a MultiQC plot using these numbers.

Phil

**Comment by ewels** [comment]
I'm going to close this as I can't see myself ever writing in this support. But feel free to shout if you'd like it to remain open.
