### ISSUE TITLE
picard WgsMetrics 

### ISSUE THREAD

**Issue by alexandregilardet** [ewels/MultiQC#1348]
Hi,

I get some error with MultiQC and Picard, and couldn't spot comma replacing dot as in previous bugs.

```python
[ERROR  ]         multiqc : Oops! The 'picard' MultiQC module broke... 
 ============================================================
Module picard raised an exception: Traceback (most recent call last):
    File "/camp/apps/eb/software/MultiQC/1.7-foss-2018b-Python-3.6.6-matplotlib-2.2.3/bin/multiqc", line 440, in multiqc
      output = mod()
    File "/camp/apps/eb/software/MultiQC/1.7-foss-2018b-Python-3.6.6-matplotlib-2.2.3/lib/python3.6/site-packages/multiqc/modules/picard/picard.py", line 99, in __init__
      n['WgsMetrics'] = WgsMetrics.parse_reports(self)
    File "/camp/apps/eb/software/MultiQC/1.7-foss-2018b-Python-3.6.6-matplotlib-2.2.3/lib/python3.6/site-packages/multiqc/modules/picard/WgsMetrics.py", line 201, in parse_reports
      pdata[s_name]['PCT_EXC_MAPQ'] = data['PCT_EXC_MAPQ'] * 100.0
  TypeError: can't multiply sequence by non-int of type 'float'
 ============================================================

```

**File that triggers the error:**

[SKO719A247.wgs_metrics_lib.txt](https://github.com/ewels/MultiQC/files/5565929/SKO719A247.wgs_metrics_lib.txt)

**MultiQC run details:**
* Command used to run MultiQC: 
multiqc -f -c multiqc_config.yml -o qc qc/data
* MultiQC Version: 
MultiQC/1.7-foss-2018b-Python-3.6.6-matplotlib-2.2.3  
* Operating System: 
CentOS Linux 7 (Core)
(on a cluster and as part of a nextflow pipeline)

Thanks!

**Comment by ewels** [comment]
Hi @alexandregilardet,

I just tried your file on my system and it worked fine:

```console
$ multiqc -f ../SKO719A247.wgs_metrics_lib.txt
[INFO   ]         multiqc : This is MultiQC v1.10.dev0 (8df26af)
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching   : /Users/ewels/Downloads/SKO719A247.wgs_metrics_lib.txt
[INFO   ]          picard : Found 1 WgsMetrics reports
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete
```

Report: [multiqc_report.html.zip](https://github.com/ewels/MultiQC/files/5749084/multiqc_report.html.zip)

MultiQC v1.7 is pretty old now (released Dec 2018) so I guess the error has been fixed. Try updating to the latest version and hopefully it'll work for you.

Phil
