### ISSUE TITLE
MultiQC only reporting one of two read pairs cut using Cutadapt

### ISSUE THREAD

**Issue by andradejon** [ewels/MultiQC#1349]
**Description of bug:**
Couldn't find this in other posted issues, so please let me know if I missed this somewhere. 

I ran cutadapt 1.8 on a set of paired-end reads, but MultiQC seems to only pull information from read 2. My report only lists read 2 in both the General Statistics and Cutadapt: Length of Trimmed Sequences sections. I verified that 299380 sequences had 76bp trimmed from read 1, 9101478 from read 2, and 9101478 is the number reported on MultiQC (just to make sure these weren't summed or averaged or something). Any thoughts?

**MultiQC run details (please complete the following):**
* Command used to run MultiQC: multiqc .
* MultiQC Version: MultiQC v 1.0
* Operating System: CentOS Linux 7 (Core)
* Python Version: Python 3.7.9
* Method of MultiQC installation: conda

**Comment by ewels** [comment]
Hi @andradejon,

Please attach some example files so that I can replicate this problem to investigagte (I'm pretty sure that it usually works fine for me).

Thanks,

Phil

**Comment by ewels** [comment]
Closing due to lack of example data / response.
