### ISSUE TITLE
Parser for qualimap's RNAseq report breaks for paired-end data

### ISSUE THREAD

**Issue by tomsing1** [ewels/MultiQC#135]
It seems that the `QM_RNASeq.py` parser for qualimap's RNAseq report does not work for output from paired-end data. Specifically, for paired-end data the "reads aligned" row contains two numbers, one for each read in the pair, e.g.

```
reads aligned (left/right) = 3,295,794 / 3,295,797
```

This breaks line 45 of `QM_RNASeq.py`
```python
self.general_stats[s_name]['reads_aligned'] = float( num )
```

There may be additional differences between output files, but that's the first error.

An example of qualimap's output for a paired-end sample can be found [here](https://gist.github.com/tomsing1/aeafe10793074d6386f7#file-rnaseq_qc_results-txt)

**Comment by ewels** [comment]
Aha, thanks for the detailed bug report - I'll take a look!

**Comment by ewels** [comment]
Hi @tomsing1,

See commit above, that should fix it (works for me now). Note that I chose to just ignore the number of alignments for each read and instead just took the `read pairs aligned` line. Hope that's ok! Let me know if you think it should be done differently.

Phil
