### ISSUE TITLE
How to avoid multiQC filename collision with Quast report.tsv files

### ISSUE THREAD

**Issue by tamuanand** [ewels/MultiQC#1351]
Hi @ewels @drpatelh @apeltzer 

I am using multiQC within a Nextflow pipeline where Quast is run on many files.

However, I run into filename collision issues as reported below at the multiQC step
```
Caused by:  Process `multiqc` input file name collision 
-- There are multiple input files for each of the following file names: spades/QUAST_OUTPUT/report.tsv
```
This below is my `nextflow quast + multiqc process`

```
process quast {
  tag "${sample_id}_QUAST"
  publishDir "${params.outdir}/QUAST_OUTPUT", mode: 'copy'

  input:
  set sample_id, file(fasta) from quast_ch

  output:
  file("${sample_id}_assembly_QC/")
  file("${sample_id}_assembly_QC/report.tsv") into ch_quast_mqc

  script:
  """
  quast -t 16 -o ${sample_id}_assembly_QC ${fasta}
  ln -s ${sample_id}_assembly_QC/report.tsv
  """
}

process multiqc {
    publishDir "${params.outdir}/multiqc/", mode: 'copy'

    input:
    file multiqc_config from ch_config_for_multiqc
    path ('trimmomatic/*') from ch_trimmomatic_mqc.collect().ifEmpty([])
    file ('spades/QUAST_OUTPUT/*/*') from ch_quast_mqc.collect().ifEmpty([])
    path ('minimap/samtools/*') from ch_minimap_mqc.collect().ifEmpty([])
    file ('software_versions/*') from software_versions_yaml

    output:
    path "*multiqc_report.html" into ch_multiqc_report
    path "*_data"

    script:
    rtitle = custom_runName ? "--title \"$custom_runName\"" : ''
    rfilename = custom_runName ? "--filename " + "multiqc_report" : ''
    """
    multiqc . -f $rtitle $rfilename --config $multiqc_config --interactive
    """
}
```

**_However,_** In the above scenario, if I go to the nextflow workdir and invoke `multiqc . ` on the command line, it works fine. Is there something I am missing?

I have been trying to work around the above and  I happened to come across what @apeltzer did with `bacass` - when I try this approach, multiQC does not find the files for QUAST

- https://github.com/nf-core/bacass/blob/master/main.nf#L531-L552 

Thanks in advance,

**Comment by drpatelh** [comment]
Hi @tamuanand. Another example is what I have implemented in viralrecon. See [here](https://github.com/nf-core/viralrecon/blob/75a2f9763e9b4c1aa20ad342ae3ce148c33cc65a/main.nf#L1498) and [here](https://github.com/nf-core/viralrecon/blob/75a2f9763e9b4c1aa20ad342ae3ce148c33cc65a/main.nf#L3331).

**Comment by tamuanand** [comment]
Thanks @drpatelh for your tips

**Comment by apeltzer** [comment]
> Hi @tamuanand. Another example is what I have implemented in viralrecon. See [here](https://github.com/nf-core/viralrecon/blob/75a2f9763e9b4c1aa20ad342ae3ce148c33cc65a/main.nf#L1498) and [here](https://github.com/nf-core/viralrecon/blob/75a2f9763e9b4c1aa20ad342ae3ce148c33cc65a/main.nf#L3331). Here, I have run QUAST across all samples to have them in a single report which means I won't get any file name clashes.
> 
> If you want to run it per sample then you will have to name the report by the sample id? e.g. `${sample_id}.report.tsv` and then it should be fine when you stage it in MultiQC.
> 
> This isn't really a problem with MultiQC but the implementation you decide to use in Nextflow.

I agree - this is something not being a bug in MultiQC but rather an implementation approach. Thanks for pointing me to the issue that this isn't properly shown in bacass - I'll adjust it. Harshils approach might be fine for viral (=> small) genomes, but for the bacterial ones it already takes quite a while and thus should be parallelized across samples. I might have to adjust to `${sample_id}.report.tsv` (with a `.` instead of my current `_` ) or maybe configure a custom file name for the multiqc quast module, but that should do the trick here 👍🏼 https://github.com/nf-core/bacass/issues/35
