### ISSUE TITLE
macs2 output format has changed

### ISSUE THREAD

**Issue by alexyfyf** [ewels/MultiQC#1355]
**Description of bug:**
multiqc 1.9 cannot read output xls file from macs2

The new output xls file has different header lines compare to the example data: https://github.com/ewels/MultiQC_TestData/tree/master/data/modules/macs2
```
# This file is generated by MACS version 2.2.7.1
# Command line: callpeak -t ../result_atac/shiftedbamfiles/atac-6mL1_S4_L002_shifted_sorted.bam -n test_bam -f BAM -g mm -q 0.01 --nomodel --shift -75 --extsize 150 --call-summits --keep-dup all
# ARGUMENTS LIST:
# name = test_bam
# format = BAM
# ChIP-seq file = ['../result_atac/shiftedbamfiles/atac-6mL1_S4_L002_shifted_sorted.bam']
# control file = None
# effective genome size = 1.87e+09
# band width = 300
# model fold = [5, 50]
# qvalue cutoff = 1.00e-02
# The maximum gap between significant sites is assigned as the read length/tag size.
# The minimum length of peaks is assigned as the predicted fragment length "d".
# Larger dataset will be scaled towards smaller dataset.
# Range for calculating regional lambda is: 10000 bps
# Broad region calling is off
# Paired-End mode is off
# Searching for subpeak summits is on

# tag size is determined as 46 bps
# total tags in treatment: 34522161
# Sequencing ends will be shifted towards 5' by 75 bp(s)
# d = 150
```
when I run multiqc, it doesn't read this file
```
(/home/fyan0011/mx82/fyan0011/conda_env/chipseq) [fyan0011@m3a009 test_macs2]$ multiqc .
[INFO   ]         multiqc : This is MultiQC v1.9
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching   : /fs03/ls25/feng.yan/Lmo2_ATAC/test_macs2
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
```

**Comment by ewels** [comment]
Thanks for reporting this @alexyfyf - I think that MultiQC isn't finding your file because it doesn't have the expected `_peaks.xls` filename perhaps? If I save your example to a file called 
[`test_peaks.xls`](https://github.com/ewels/MultiQC/files/5749098/test_peaks.xls.zip) then MultiQC finds it:

```console
$ multiqc -f .
[INFO   ]         multiqc : This is MultiQC v1.10.dev0 (8df26af)
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching   : /Users/ewels/GitHub/MultiQC/TestData/data/modules/macs2
[INFO   ]           macs2 : Found 3 logs
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete
```

However, the resulting report has almost nothing in it: [multiqc_report.html](https://github.com/ewels/MultiQC/files/5749099/multiqc_report.html.zip)

So yes, definitely needs updating 👍🏻

**Comment by ErikDanielsson** [comment]
I don't think the issue is with MultiQC since we are missing some of the headers in the report which needed to generate the bar graph. A similar issue has already been discussed in #758.

**Comment by ewels** [comment]
Right, yes agreed. @alexyfyf maybe you truncated the log file that you pasted which is why the report has only the Fragment Length and nothing else when I run it?

Ok, so sounds like MultiQC is working fine then. Thanks for checking @ErikDanielsson 👍🏻 Shout if you think something needs changing @alexyfyf 

Phil

**Comment by alexyfyf** [comment]
> Right, yes agreed. @alexyfyf maybe you truncated the log file that you pasted which is why the report has only the Fragment Length and nothing else when I run it?
> 
> Ok, so sounds like MultiQC is working fine then. Thanks for checking @ErikDanielsson 👍🏻 Shout if you think something needs changing @alexyfyf
> 
> Phil

Thanks for the message. Yes, you are right, seems the xls file is missing the information multiqc need, such as redundancy rate and the number of peaks. But this is the whole header. 
I found I used `--keep-dup all`, and compared to other macs2 output without this flag, the one without showed the redundancy rate.
However, I did not find any macs2 output from my previous analysis containing the number of peaks. Not sure if which situation it will report that, if you could give an example, that would be appreciated.
I guess the message here is that the macs2 output header is highly dependent on the parameters used (such as keep-dup), posing a difficulty for multiqc to be compatible with all scenarios.
