### ISSUE TITLE
Sample name sort order in "featureCounts: Biotype" plot

### ISSUE THREAD

**Issue by myoshimura080822** [ewels/MultiQC#1361]
**Description of issue:**
A request for the "featureCounts: Biotype" of the MultiQC report that we usually use.

The current version (Strange order; I'm not sure how this order is determined)
<img src="https://user-images.githubusercontent.com/8693179/103525321-5a449c80-4ec2-11eb-945b-32e9a85426bd.png" height=400>

**Desired function (Controlled order):**
We would like to control the sample order (e.g., alphabetically) in any way possible.

**Supplementary note:**
- The mqc_featureCounts_biotype_plot_1.txt file in the multiqc_data directory is sorted by sample name.
![image](https://user-images.githubusercontent.com/8693179/103525381-75171100-4ec2-11eb-90be-642295459052.png)
- Renaming the sample name by multiqc_config does not change this order.
- The MultiQC documentation does not mention any options for controlling sample name order in the plot.

**Comment by ewels** [comment]
Could you please attach the exact file that you're working with to this issue (you can compress it to a zip file if GitHub doesn't like the extension). Presumably `mqc_featureCounts_biotype_plot_1.txt`?

Thanks

**Comment by myoshimura080822** [comment]
Thanks for the answer. I attached the example data.
[mqc_featureCounts_biotype_plot_1.txt](https://github.com/ewels/MultiQC/files/5805865/mqc_featureCounts_biotype_plot_1.txt)

**Comment by ewels** [comment]
Solved in https://github.com/ewels/MultiQC/pull/1530 - sorry it took a while! Let me know if you hit any problems.
