### ISSUE TITLE
STAR-fusion

### ISSUE THREAD

**Issue by rpauly** [ewels/MultiQC#1365]
Does multiqc support visualization of gene-fusion results? Something like circos plots.
For example : STAR-Fusion (https://github.com/STAR-Fusion/STAR-Fusion)
Thanks!

**Comment by ewels** [comment]
No, I'm afraid that MultiQC doesn't support STAR-Fusion. You can see a list of supported tools on the MultiQC homepage: https://multiqc.info/#supported-tools

If you'd like it to be added, please create an issue using the "Module request" template and fill in all of the sections and attach some example data: https://github.com/ewels/MultiQC/issues/new?assignees=&labels=&template=module-request.md

Note that Circos plots are very unlikely to ever make it in to MultiQC as they would not scale well for large numbers of samples.

Many thanks in advance,

Phil
