### ISSUE TITLE
Parse featureCounts results when run on multiple input files

### ISSUE THREAD

**Issue by avilella** [ewels/MultiQC#137]
how does one run featureCounts to have it parsed by MultiQC? is it expecting special flags or a bam file with special tags?

**Comment by ewels** [comment]
featureCounts usually creates a summary file called `[input]_counts.txt.summary` - see the [new parsing config file](https://github.com/ewels/MultiQC/blob/master/multiqc/utils/search_patterns.yaml#L32-L33).

There's a copy of it in the test repository [here](https://github.com/ewels/MultiQC_TestData/blob/master/data/SRR1067503_1_trimmed_star_aligned.bam_counts.txt.summary). See discussion of the file [here](https://groups.google.com/forum/#!topic/subread/JPPw9lVfgpw).

**Comment by avilella** [comment]
Working now thanks.

**Comment by Bianca-T** [comment]
Does MultiQC read featureCounts output that summarise data on several samples?

**Comment by ewels** [comment]
Hi @Bianca-T,

I wasn't aware that featureCounts was able to run on several samples at once, I've only ever run it on a single BAM file.

MultiQC is able to process any number of `*_counts.txt.summary` files to summarise several samples if that's what you mean.

Phil

**Comment by ewels** [comment]
Ah you're right, [it can](http://bioinf.wehi.edu.au/featureCounts/) process multiple files at once:

> Summarize multiple datasets at the same time:
> `featureCounts -t exon -g gene_id -a annotation.gtf -o counts.txt library1.bam library2.bam library3.bam`

Apologies, I've never run it like this. Do you have an example log file so that I can see what the output looks like? I'll update the module so that it can understand this output as well.

Thanks for bringing this up.

Phil

**Comment by Bianca-T** [comment]
Hi Phil,

Please find attached an example output.

Thanks!!

/Bianca

**Comment by Bianca-T** [comment]
sorry it didn't attached properly.
I renamed it with .txt as suffix

[all.counts.txt.summary.txt](https://github.com/ewels/MultiQC/files/215094/all.counts.txt.summary.txt)

**Comment by ewels** [comment]
Ok great, thanks! Are you happy for me to add this to the [MultiQC_TestData](https://github.com/ewels/MultiQC_TestData) GitHub repository? I'm trying to collect example log files there which are used for automated testing every time I push an update.

**Comment by Bianca-T** [comment]
Maybe I will change the file names. Will send you a new one!

**Comment by ewels** [comment]
No problem - I can just switch out the filenames if you like. Format looks pretty simple..

**Comment by ewels** [comment]
Ok, updated an anonymised version [here](https://github.com/ewels/MultiQC_TestData/blob/7c10a8a0d0b564015ad4f3c3fc579fe5d79de3ba/data/modules/featureCounts/multiple_files.counts.txt.summary) and deleted your comment with the original version. Hope this is ok. Thanks!

**Comment by Bianca-T** [comment]
Thank you!

**Comment by ewels** [comment]
Hi @Bianca-T,

I've just rewritten the module and pushed the update above. It should work now, let me know if you run into any difficulties.

Thanks!

Phil

**Comment by Bianca-T** [comment]
Great, I was using the version in UPPMAX but I will try to install new own and pull the changes.

/Bianca

**Comment by ewels** [comment]
Yup - see [the docs](http://multiqc.info/docs/#installing-multiqc) for help with installation if you need it. These changes will go out on UPPMAX when I release v0.6.

**Comment by ewels** [comment]
Hi @gadepallivs,

No, I'm afraid that this isn't possible. I'm not sure that it's really a good idea either, as the bar totals won't add up to your total read count any more. So it may look like you have more reads assigned as a proportion of your total dataset than you really do.

Why do you want to remove these categories?

Phil

**Comment by ewels** [comment]
ps. It's better to create a new issue for this kind of question, or to ask on Gitter (https://gitter.im/ewels/MultiQC). Closed issues like this are much easier for me to miss or forget, plus we're currently spamming the other people on this issue with an unrelated question.
