### ISSUE TITLE
MultiQC issue with dragen fastqc

### ISSUE THREAD

**Issue by mengxiao-he** [ewels/MultiQC#1371]
**Description of bug:**

Tried to use multiqc on the fastqc files that was created from dragen automatically after demultiplexing. Not sure if that is supported.

**MultiQC Error log:**

```
[INFO   ]         multiqc : This is MultiQC v1.9
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching   : /Users/mengxiao.he/Google_Drive/Spatial_Prostate/OrganScale2/fastqc
Searching 224 files..  [####################################]  100%          
[ERROR  ]         multiqc : Oops! The 'dragen' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    ./V10L27-043_A1/fastqc/V10L27-043_A1.mapping_metrics.csv
============================================================
Module dragen raised an exception: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/multiqc/multiqc.py", line 569, in run
    output = mod()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/multiqc/modules/dragen/dragen.py", line 59, in __init__
    samples_found |= self.add_mapping_metrics()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/multiqc/modules/dragen/mapping_metrics.py", line 26, in add_mapping_metrics
    data_by_readgroup, data_by_phenotype = parse_mapping_metrics_file(f)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/multiqc/modules/dragen/mapping_metrics.py", line 325, in parse_mapping_metrics_file
    data['Q30 bases (excl. dups & clipped bases) pct'] = data['Q30 bases (excl. dups & clipped bases)'] / data['Total bases'] * 100.0
KeyError: 'Q30 bases (excl. dups & clipped bases)'
============================================================
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete

```

**File that triggers the error:**

[V10L27-043_A1.mapping_metrics.csv.zip](https://github.com/ewels/MultiQC/files/5951655/V10L27-043_A1.mapping_metrics.csv.zip)
Not sure it is this file but this is the last file found mentioned in the error message

Zip file of the fastqc output from dragen that I'm trying to run multiqc on.
[fastqc.zip](https://github.com/ewels/MultiQC/files/5951683/fastqc.zip)

**MultiQC run details (please complete the following):**

- Command used to run MultiQC:  multiqc .
- MultiQC Version:  1.9
- Operating System:  macOS Catalina 10.15.7
- Python Version:  3.8.5
- Method of MultiQC installation:  pip

**Additional context**

Tried on a server running Scientific 7.9 as well with same result.

**Comment by alexiswl** [comment]
I think this https://github.com/ewels/MultiQC/pull/1232/files may fix the issue - see line https://github.com/ewels/MultiQC/pull/1232/files#diff-96ec4c6cd11235ded265cf616501c3ecc3adf9fd724e450c4c302627f673e3cbL389

**Comment by ewels** [comment]
Thank you @alexiswl ! The second URL doesn't work for me, just gives the entire diff still. Could you link to the commit on the base fork instead maybe? That is usually more stable..

**Comment by ewels** [comment]
Tried running the test data and it generated a report with no issues, so closing as I assume that this is fixed.
