### ISSUE TITLE
running multiqc in python script -save multiqc_report.html in different folder

### ISSUE THREAD

**Issue by kate-simonova** [ewels/MultiQC#1373]
In python script multiqc is running in the following way:

```python
def run_multiqc(fastqc_path):
    try:
        multiqc.run(fastqc_path)
    except:
        print('Multiqc analysis failed!')
    else:
        print("Multiqc analysis successfully completed!")


```
Is it possible to save `multiqc_data` folder and `multiqc_report.html` into `fastqc_path` folder?

**Comment by ewels** [comment]
Sure, you can see all of the function arguments here: https://github.com/ewels/MultiQC/blob/8e9986f445cf7537fc32b5759de365cfe1197371/multiqc/multiqc.py#L255-L293

You're looking for `outdir`, e.g: `multiqc.run(fastqc_path, outdir=fastqc_path)`

I _think_ that should work 😄 Shout if not and I can reopen.
