### ISSUE TITLE
numeric sample sort in general stats

### ISSUE THREAD

**Issue by mpozuelo** [ewels/MultiQC#1375]
Hi!

Is there a way to numerically sort the sample names in the general stats table?
Now for example I'm having this problem when my samples appear: 

```
1
10
10_R1
10_R2
11
11_R1
11_R2
1_R1
1_R2
```

I'd like to have:

```
1
1_R1
1_R2
10
10_R1
10_R2
11
11_R1
11_R2
```

I cannot find the way to do this but maybe you have already implement it.
Marta

**Comment by ewels** [comment]
There's no simple to do this in MultiQC currently I'm afraid. If it's possible to edit your input filenames then making them zero-padded should work (eg. `01_R1`) but I appreciate that this is not ideal.

Phil
