### ISSUE TITLE
Ordering of Samples in Reported Plots

### ISSUE THREAD

**Issue by danphillips28** [ewels/MultiQC#1401]
Hi!

Thanks for producing this tool. I use it all the time!

I'm wanting to use the Reads per Sample plot but for some reason the samples aren't in the "correct" order. I renamed them with prefixes so samples from different tissues would cluster together, but only two of my 5 tissues were clustered. I then noticed the rest were being ordered by a number in the middle of their name, rather than alphabetically by their prefix, so I renamed every sample in each tissue to e.g. Liver. They still do not cluster together.  How can I get it such that samples from the same tissue are clustered together in the plot? 

Thanks again,
Daniel

**Comment by ewels** [comment]
Hi @danphillips28,

Where is the data coming from? Could you attach a zip of some example files so that I can try to replicate what you're seeing please?

Thanks,

Phil

**Comment by ewels** [comment]
Closing as I need example data to replicate this.
