### ISSUE TITLE
Error making MatPlotLib figure! Falling back to HighCharts.

### ISSUE THREAD

**Issue by marwa38** [ewels/MultiQC#1404]
**Description of bug:**

 Error making MatPlotLib figure! Falling back to HighCharts.

**MultiQC Error log:**

```
[r01mt19@maxlogin1 trimGalored]$ multiqc .
/opt/software/uoa/2019/conda/anaconda3/envs/multiqc-1.7/lib/python3.6/site-packages/multiqc/utils/config.py:45: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  configs = yaml.load(f)
/opt/software/uoa/2019/conda/anaconda3/envs/multiqc-1.7/lib/python3.6/site-packages/multiqc/utils/config.py:51: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  sp = yaml.load(f)
[WARNING]         multiqc : MultiQC Version v1.10 now available!
[INFO   ]         multiqc : This is MultiQC v1.7
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
Searching 1736 files..  [####################################]  100%
[INFO   ]        cutadapt : Found 434 reports
[ERROR  ]       linegraph : ############### Error making MatPlotLib figure! Falling back to HighCharts.
[INFO   ]          fastqc : Found 434 reports
[ERROR  ]        bargraph : ############### Error making MatPlotLib figure! Falling back to HighCharts.
[ERROR  ]       linegraph : ############### Error making MatPlotLib figure! Falling back to HighCharts.
[ERROR  ]       linegraph : ############### Error making MatPlotLib figure! Falling back to HighCharts.
[ERROR  ]       linegraph : ############### Error making MatPlotLib figure! Falling back to HighCharts.
[ERROR  ]       linegraph : ############### Error making MatPlotLib figure! Falling back to HighCharts.
[ERROR  ]       linegraph : ############### Error making MatPlotLib figure! Falling back to HighCharts.
[ERROR  ]       linegraph : ############### Error making MatPlotLib figure! Falling back to HighCharts.
[ERROR  ]        bargraph : ############### Error making MatPlotLib figure! Falling back to HighCharts.
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete

```

**File that triggers the error:**

**MultiQC run details (please complete the following):**

- Command used to run MultiQC:  multiqc .
- MultiQC Version:  
[1_S1_L001_R1_001_val_1_fastqc.zip](https://github.com/ewels/MultiQC/files/6215343/1_S1_L001_R1_001_val_1_fastqc.zip)
[1_S1_L001_R2_001_val_2_fastqc.zip](https://github.com/ewels/MultiQC/files/6215344/1_S1_L001_R2_001_val_2_fastqc.zip)

multiqc-1.7
- Operating System:  HPC of the University (I am using Windows 10)
- Python Version: 
- Method of MultiQC installation:  already installed beforehand, I just run the module (module load multiqc-1.7)

**Additional context**

 I attached some files (but not all of them because they are many), anyway others are the same extensions but for different samples. 
[1_S1_L001_R1_001.fastq.gz_trimming_report.txt](https://github.com/ewels/MultiQC/files/6215336/1_S1_L001_R1_001.fastq.gz_trimming_report.txt)
[1_S1_L001_R1_001_val_1.fq.gz](https://github.com/ewels/MultiQC/files/6215337/1_S1_L001_R1_001_val_1.fq.gz)

![image](https://user-images.githubusercontent.com/68851733/112714097-8de6ff80-8ed0-11eb-8d35-a47eb189610e.png)

same.

**Comment by ewels** [comment]
MultiQC v1.7 is super old (December 2018), could you first try to update to the latest v1.10 release?

The warning `Error making MatPlotLib figure! Falling back to HighCharts.` just means that your installation of the [matplotlib library](https://matplotlib.org/) is broken. MultiQC tolerates this and generates a report with interactive graphs instead of flat images. It should still work ok, but the file size could be fairly huge and the report slow to load in your browser.

Phil

**Comment by ewels** [comment]
Closing as I think that this is an installation error and not to do with the MultiQC code itself. Let me know how you get on though, happy to reopen if we settle on a problem in the codebase.
