### ISSUE TITLE
Custom content - png files

### ISSUE THREAD

**Issue by matthdsm** [ewels/MultiQC#1405]
**Description of bug:**
I'm trying to add custom data in the form of `png` files, but without modifying the filenames (so no appending `_mqc`).
The images are workflow outputs where I have little control over the filenames.

I'm using the custom config below, following the [manual](https://multiqc.info/docs/#separate-configuration-and-data-files), but this doesn't seem to work for images.

```yaml
custom_data:
  clustercount_by_lane:
    section_name: "Cluster Count By Lane"
    description: "Flowcell Cluster Count by Lane"
  intensity_by_cycle:
    section_name: "Intensity By Cycle"
    description: "Flowcell Intensities by Cycle per channel"
  flowcell_intensity:
    section_name: "Flowcell Intensity"
  qscore_heatmap:
    section_name: "Qscore Heatmap"
  qscore_histogram:
    section_name: "Qscore Histogram"
sp:
  clustercount_by_lane:
    fn: "*_ClusterCount-by-lane.png"
  intensity_by_cycle:
    fn: "*_Intensity-by-cycle_Intensity.png"
  flowcell_intensity:
    fn: "*_flowcell-Intensity.png"
  qscore_heatmap:
    fn: "*_q-heat-map.png"
  qscore_histogram:
    fn: "*_q-histogram.png"
```

**MultiQC Error log:**
```
[ERROR  ]          config : Config 'custom_logo' path not found, skipping (/resources/cmgg_logo.png)
[WARNING]         multiqc : MultiQC Version v1.10 now available!
[INFO   ]         multiqc : This is MultiQC v1.9
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Report title: 210204_J00178_0747_AHKVVLBBXY
[INFO   ]         multiqc : Searching   : /projects/demultiplex/development/210204_J00178_0747_AHKVVLBBXY/output
Searching 151 files..  [####################################]  100%          
[INFO   ]           bcbio : Found 0 reports
[INFO   ]        mosdepth : Found 8 reports
[INFO   ]      biobambam2 : Found 8 bamsormadup reports
[INFO   ]          picard : Found 8 AlignmentSummaryMetrics reports
[INFO   ]          picard : Found 8 WgsMetrics reports
[INFO   ]        samtools : Found 8 stats reports
[INFO   ]        samtools : Found 8 idxstats reports
[INFO   ]          fastqc : Found 8 reports
[INFO   ]         interop : Found 1 reports
[INFO   ]         multiqc : Compressing plot data
[WARNING]         multiqc : Deleting    : 210204_J00178_0747_AHKVVLBBXY_multiqc_report.html   (-f was specified)
[INFO   ]         multiqc : Report      : 210204_J00178_0747_AHKVVLBBXY_multiqc_report.html
[INFO   ]         multiqc : Data        : 210204_J00178_0747_AHKVVLBBXY_multiqc_report_data
[INFO   ]         multiqc : MultiQC complete
```

**File that triggers the error:**
None
**MultiQC run details (please complete the following):**

- Command used to run MultiQC: `multiqc --force --title 210204_J00178_0747_AHKVVLBBXY --zip-data-dir --config multiqc_config.yaml  .`
- MultiQC Version: v1.9
- Operating System: Ubuntu 18.04
- Python Version: Python 3.6
- Method of MultiQC installation: conda

**Comment by ewels** [comment]
ok, it took me a little while, but I finally figured this out.. The key is to add `ignore_images: false` to your MultiQC config.

Basically MultiQC does a pre-run through of all supplied files, skipping images and binary files to speed up the search. Any images that end in `_mqc` are a special case and not ignored because of custom content. However, yours don't have this extension and so are being skipped. Adding `ignore_images: false` turns this off so the images are kept in the search base and then later picked up by your search pattern.

I should add something to the docs about this, as it took me a while to figure it out.. 😁

**Comment by ewels** [comment]
ok done. Let me know how you get on!

**Comment by ewels** [comment]
I didn't actually fix anything, just had to rediscover a fix that I added previously 😅 The good news is that this means that you don't have to wait for a release 😉

**Comment by matthdsm** [comment]
That's true. All the better!
Seems to work like a charm, thanks again!
