### ISSUE TITLE
Picard RnaSeqMetrics Assignment plot has incorrect x-axis label

### ISSUE THREAD

**Issue by laurakirby4** [ewels/MultiQC#1408]
**Description of bug:**

The RnaSeqMetrics Assignment plot has the x-axis labeled as Number of Reads when the description of the plot says "Number of bases in primary alignments that align to regions in the reference genome." The values shown on the plot do match up with the number of bases.  

![picard_rnaseqmetrics_assignment_plot (1)](https://user-images.githubusercontent.com/24215775/114081343-6bfb5e80-987a-11eb-8d96-b02ecca4913a.png)

**MultiQC run details (please complete the following):**

- Command used to run MultiQC: multiqc . --interactive --force -c multiqc_config.yaml -n scrna-qc_report.html
- MultiQC Version: MultiQC v1.10.1
- Operating System: ubuntu
- Python Version: Python 3.9.2
- Method of MultiQC installation: conda

**Comment by ewels** [comment]
Agreed - changed to bases (also in the plot title) in c395cee. Thanks for reporting!

If you fancy suggesting any descriptions + help text for these three plots that would be great too - especially the gene body coverage plot that has nothing. Plagiarising + linking to the picard docs is recommended. Markdown is fine.
