### ISSUE TITLE
snfEff module not available

### ISSUE THREAD

**Issue by mprabha2** [ewels/MultiQC#1409]
**Tool Details**

- Name of tool: 
- Tool homepage: 
- Tool description: 
- Data suitable for MultiQC plot(s): 
- Most interesting data for General Stats table: 

**Tool output:**

- Log filename pattern: 
- File contents:

**Comment by ewels** [comment]
There is already a MultiQC module for SnpEff: https://multiqc.info/docs/#snpeff
