### ISSUE TITLE
ImportError: cannot import name 'gcd' from 'fractions'

### ISSUE THREAD

**Issue by Ni-Ar** [ewels/MultiQC#1413]
**Description of bug:**

I have a miniconda env with Python3.9 installed and I just installed `multiqc` v:1.10.1 with:

```console
$ conda activate chipseq

$ python --version
Python 3.9.2

$ conda install -c bioconda multiqc
```

The installation went fine. 

Then when I run:

```bash
multiqc --version   # (or --help)
```
I get this error message which I believe it is related to [this](https://stackoverflow.com/a/66175057/9938003) python3.9 issue.

```python
Traceback (most recent call last):
  File "/path/to/software/miniconda/envs/chipseq/bin/multiqc", line 6, in <module>
    from multiqc.__main__ import multiqc
  File "/path/to/software/miniconda/envs/chipseq/lib/python3.9/site-packages/multiqc/__init__.py", line 16, in <module>
    from .multiqc import run
  File "/path/to/software/miniconda/envs/chipseq/lib/python3.9/site-packages/multiqc/multiqc.py", line 39, in <module>
    from .plots import table
  File "/path/to/software/miniconda/envs/chipseq/lib/python3.9/site-packages/multiqc/plots/table.py", line 9, in <module>
    from multiqc.utils import config, report, util_functions, mqc_colour
  File "/path/to/software/miniconda/envs/chipseq/lib/python3.9/site-packages/multiqc/utils/mqc_colour.py", line 7, in <module>
    import spectra
  File "/path/to/software/miniconda/envs/chipseq/lib/python3.9/site-packages/spectra/__init__.py", line 1, in <module>
    from .core import COLOR_SPACES, Color, Scale
  File "/path/to/software/miniconda/envs/chipseq/lib/python3.9/site-packages/spectra/core.py", line 1, in <module>
    from colormath import color_objects, color_conversions
  File "/path/to/software/miniconda/envs/chipseq/lib/python3.9/site-packages/colormath/color_conversions.py", line 13, in <module>
    import networkx
  File "/path/to/software/miniconda/envs/chipseq/lib/python3.9/site-packages/networkx/__init__.py", line 114, in <module>
    import networkx.generators
  File "/path/to/software/miniconda/envs/chipseq/lib/python3.9/site-packages/networkx/generators/__init__.py", line 14, in <module>
    from networkx.generators.intersection import *
  File "/path/to/software/miniconda/envs/chipseq/lib/python3.9/site-packages/networkx/generators/intersection.py", line 13, in <module>
    from networkx.algorithms import bipartite
  File "/path/to/software/miniconda/envs/chipseq/lib/python3.9/site-packages/networkx/algorithms/__init__.py", line 16, in <module>
    from networkx.algorithms.dag import *
  File "/path/to/software/miniconda/envs/chipseq/lib/python3.9/site-packages/networkx/algorithms/dag.py", line 23, in <module>
    from fractions import gcd
ImportError: cannot import name 'gcd' from 'fractions' (/path/to/software/miniconda/envs/chipseq/lib/python3.9/fractions.py)
```

Outside of the conda env I have

```console
$ python --version
Python 3.4.5
```
and it works fine as:

```console
$ multiqc --version
multiqc, version 1.6
```
 
Thanks,
Nicco

**Comment by Ni-Ar** [comment]
By the way, the same problem persists if I downgrade to `multiqc` v1.9 with:

```
 conda install -c bioconda multiqc=1.9
```

**Comment by ewels** [comment]
Please do not use the `conda install -c bioconda` method - this is outdated. See the bioconda docs for setup instructions: https://bioconda.github.io/user/install.html#set-up-channels

```bash
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
conda install multiqc
```

However, this may not be the cause of the issue. I haven't yet started routinely testing MultiQC with Python 3.9 yet (I guess I should now since the end of last year..) so there's a chance it's related to that - I would also try using Python 3.8 for now.

Let me know how you get on..

Phil

**Comment by ewels** [comment]
> which I believe it is related to [this](https://stackoverflow.com/a/66175057/9938003) python3.9 issue.

Ah I just saw this after I posted my reply. Yes this looks likely. Unfortunately the error is not coming from the MultiQC codebase but rather several layers down inside some dependencies, so could be difficult to fix.

Could you please check what version of the `networkx` package you have installed?

**Comment by ewels** [comment]
Apparently the current release of `networkx` does not support Python 3.9. The upcoming `2.6` version will do, so I think we probably just have to wait for that: https://github.com/networkx/networkx/issues/4503#issuecomment-753024850

I'd still be curious to hear what version of `networkx` you have though, and whether updating to `2.5.1` fixes this particular problem.

**Comment by Ni-Ar** [comment]
Hi, 

I was not aware of the installation instruction, thanks for mentioning it. I reinstalled `multiqc` v1.10.1 following your instruction.

I have the v2.3 of the package `networkx`.

```
conda list -n chipseq | grep networkx    

networkx                  2.3                        py_0    conda-forge

```

Let's wait :)

**Comment by ewels** [comment]
Ok interesting, thanks! What happens if you update `networkx` to the latest version and try again?

```bash
conda install networkx=2.5.1
```

**Comment by Ni-Ar** [comment]
It did fix it!

Just do:

```
conda install networkx=2.5.1

## Package Plan ##

  environment location: /path/to/software/miniconda/envs/chipseq

  added / updated specs:
    - networkx=2.5.1
    - 
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    decorator-4.4.2            |             py_0          11 KB  conda-forge
    networkx-2.5.1             |     pyhd8ed1ab_0         1.2 MB  conda-forge
    ------------------------------------------------------------
                                           Total:         1.2 MB

The following packages will be UPDATED:

  networkx                                         2.3-py_0 --> 2.5.1-pyhd8ed1ab_0

The following packages will be DOWNGRADED:

  decorator                              5.0.7-pyhd8ed1ab_0 --> 4.4.2-py_0

```

and then 

```
multiqc --version 

multiqc, version 1.10.1

```

**Comment by ewels** [comment]
Ok brilliant! Thanks for testing! Ok great then I will bump the minimum required `networkx` version for MultiQC and add automated testing for Python 3.9 👍🏻

**Comment by ewels** [comment]
Python 3.9 CI tests passing: https://github.com/ewels/MultiQC/runs/2394918337

**Comment by drpatelh** [comment]
`networkx` bumped to `>=2.5.1` on Bioconda here https://github.com/bioconda/bioconda-recipes/pull/28375
