### ISSUE TITLE
`table_cond_formatting_rules` breaks table sorting

### ISSUE THREAD

**Issue by matthdsm** [ewels/MultiQC#1422]
**Description of bug:**

Table sorting on columns "Crosschecks"(General Stats) and "Categorical Result" (Module) doesn't seem to work

**MultiQC Error log:**

```
NA
```

**File that triggers the error:**
[mqc.zip](https://github.com/ewels/MultiQC/files/6420410/mqc.zip)

**MultiQC run details (please complete the following):**

- Command used to run MultiQC: `multiqc -f .`
- MultiQC Version: v1.10.1
- Operating System: Ubuntu 1.04
- Python Version: py3.8
- Method of MultiQC installation: pip

**Comment by ewels** [comment]
Ah, yeah I guess that the common feature here is that both are using the _"Conditional formatting"_ labels. I imagine that the additional HTML messes with the table sort.

**Comment by vladsavelyev** [comment]
Sorting of any text columns was broken - but apparently it was fixed in 1.14: https://github.com/ewels/MultiQC/blob/master/CHANGELOG.md#multiqc-updates-5

Tested it, it works now :)
