### ISSUE TITLE
Feature request - boxplot

### ISSUE THREAD

**Issue by matthdsm** [ewels/MultiQC#1424]
**Is your feature request related to a problem? Please describe.**

Hi,
I'm writing a MultiQC plugin to replicate some plots and tables from the Illumina SAV. To do this, I'm going to need some boxplots.

**Describe the solution you'd like**

Add a boxplot `plot` type

**Describe alternatives you've considered**

I could insert pregenerated PNG's, but that not really as nice as having native plots.

**Additional context**
I've added an example of the plot's I'd like to get in a MultiQC report.
You can also follow to WIP at https://github.com/CenterForMedicalGeneticsGhent/MultiQC_SAV
[200108.HiSeq4000.FCA_runreport.pdf]

plot examples
(https://github.com/ewels/MultiQC/files/6441561/200108.HiSeq4000.FCA_runreport.pdf)

**Comment by ewels** [comment]
I believe that these have been added in https://github.com/ewels/MultiQC/pull/1232 - it's a beast of a PR that I have been feeling increasingly guilty about for ages now. It's so huge that I need a large block of time to sit down and work through and I haven't been able to make this happen yet 😞 

It's getting to the point that I should probably consider merging all of the Dragen stuff blind and just reviewing the code that affects the core MultiQC execution though. Then we could at least get the new functionality in.

**Comment by ewels** [comment]
Also note that we already have beeswarm plots, which can show a distribution quite well.

**Comment by ewels** [comment]
ps. A module for SAV would be great! Is your plan to port the module to a PR for core MultiQC once it's up and running?

**Comment by ewels** [comment]
Ah right, yes those are all a bit outside the scope of core MultiQC 👍🏻  I'd be happy to have it as part of the https://github.com/MultiQC organisation as an optional plugin if you want? To make it more findable. In the long run it's my hope to move all modules to their own repos.

> Any tips or tricks to validate the inputs using search patterns would already be a big step forward.

You mean how to put together the directory structure with the regular search? It's not pretty, but I've just done a search pattern for something like `InterOp/*.bin` and then done `os.path.dirname(os.path.dirname(os.path.dirname()))` on the results for example. Crude but functional.

**Comment by matthdsm** [comment]
Hi Phil,

Sorry to branch out this issue, but is there a way to force a scatterplot to be a flat plot instead of interactive?
I've got a plot with a huge amount of datapoints that crashes the browser, so I'd like to make in flat by default.

Thanks
M

**Comment by ewels** [comment]
To follow up - my apologies, I don't think that scatter plots have a flat image equivalent yet, so this won't work. It's only for bar plots and line graphs.

Writing the matplotlib code to emulate the interactive plots is hugely time consuming, so sadly hasn't happened for all plot types yet 😞

**Comment by ewels** [comment]
I think that boxplots are covered in existing issues / PRs, so will close this now.
