### ISSUE TITLE
Feature request: plot entrypoints

### ISSUE THREAD

**Issue by matthdsm** [ewels/MultiQC#1425]
**Is your feature request related to a problem? Please describe.**
Hi Phil,

Would you be able to add an entrypoint for plots? Same is for templates/modules/hooks/etc.
Relates to #1424

**Describe the solution you'd like**

A setuptools entrypoint to add custom plots

**Describe alternatives you've considered**

NA

**Additional context**

example:
```python
   ...
   entry_points={
        ....
        "multiqc.plots.v1": ["boxplot = multiqc_sav.plots.boxplot",],
    },
   ....

**Comment by ewels** [comment]
What would the benefit be for this?

**Comment by matthdsm** [comment]
We’d be able to plug in new plots when writing plugins, in conjunction with custom templates.

Idk, but it seems nice to have if it isn’t too much of a hassle.

M

Op 10 mei 2021 om 19:14 heeft Phil Ewels ***@***.***> het volgende geschreven:

﻿

What would the benefit be for this?

**Comment by matthdsm** [comment]
Right, when you put it that way, it makes no sense to have custom plots plug into core MultiQC.

My bad! Thanks for explaining.

M

Op 10 mei 2021 om 20:50 heeft Phil Ewels ***@***.***> het volgende geschreven:

﻿

The reason for having the entry points for modules and templates is that MultiQC itself calls those chunks of code. Plots are never called by core MultiQC though, they are always used by modules or templates. That means that you can just import the plot code yourself into the module / template if you need it. That's what I mean by not understanding when you would use it, and not just import the plot into your custom code that is using it..
