### ISSUE TITLE
Plots don't seem to resize on page resize

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#143]
Looks like the plots no longer resize themselves when the window width changes..

**Comment by avilella** [comment]
Yes, I can confirm that. Only fixable by resizing to smaller window, then
resizing again to bigger window.

Also, the header of the table on top gets chopped off as one scrolls down,
when there are many columns and the table width is longer than the width of
the screen.

**Comment by ewels** [comment]
@avilella: Do you have a screen grab of the table thing? I don't really understand what you mean.

**Comment by ewels** [comment]
Ah, you mean when the sidebar is collapsed? Got it, I think that's a special case due to the left-side offset changing.

**Comment by ewels** [comment]
See #144 for the header issue.

**Comment by ewels** [comment]
Ok, this is super weird. For some reasons, a `highcharts().reflow()` event isn't being triggered when the page resizes. Which it should, because it's default. Also it used to work. If you call it manually: `$('#plot_id').highcharts().reflow()` then the plot sorts itself out.

Second weird thing - if you use the `default_dev` template instead of `default`, some (but not all - the `fastq_screen` plot doesn't respond) plots _do_ reflow themselves. But not when the sidebar is toggled (which triggers `$(document).resize();`)

I can fix it by manually calling the reflow events:
```javascript
$(window).on('resize', function(){
  $('.hc-plot').each(function(){
    try {
      $(this).highcharts().reflow();
    } catch(e) {
      // Ignore plots that can't reflow
    }
  });
});
```

But this is horrible and hacky / slow and shouldn't be necessary.

Tune in tomorrow to see if I can figure out what the hell is going on after some sleep..

**Comment by ewels** [comment]
Potentially not the end of this story, please re-open the issue if more evidence of buggy behaviour found.
