### ISSUE TITLE
Javascript crash during plotting

### ISSUE THREAD

**Issue by matthdsm** [ewels/MultiQC#1430]
**Description of bug:**

Javascript crashes when rendering heatmap/line graph

**MultiQC Error log:**

```js
//heatmap
TypeError: undefined is not an object (evaluating 'mqc_plots[target]["xcats"][0].length')

// line graph
TypeError: undefined is not an object (evaluating 'mqc_plots[target]["datasets"][0].length')
```

**File that triggers the error:**

https://github.com/CenterForMedicalGeneticsGhent/MultiQC_SAV/files/6499614/mqc_reports.zip

**MultiQC run details (please complete the following):**

- Command used to run MultiQC: `multiqc -f  test_data/NextSeq500`
- MultiQC Version: MultiQC v1.10.1
- Operating System: macOS 11.3.1
- Python Version: Python 3.7
- Method of MultiQC installation: pip

**Additional context**
xref https://github.com/CenterForMedicalGeneticsGhent/MultiQC_SAV/issues/1

**Comment by matthdsm** [comment]
Turns out this was a user error, see linked issue for solution

RTFM

**Comment by ewels** [comment]
The best kind of bug fix 😆
