### ISSUE TITLE
Feature: configurable plot size

### ISSUE THREAD

**Issue by matthdsm** [ewels/MultiQC#1432]
**Is your feature request related to a problem? Please describe.**

Heatmaps  can be a bit awkwardly placed and pulled to the left. It's also hard to see the cells when there's a lot of datapoints.
I'm aware I can disable the square format, but that doesn't really help much for visibility. It would be nice to be able to set the size of a plot.

**Describe the solution you'd like**

Plot config option to adjust the default plot size.

**Describe alternatives you've considered**

Dragging the little gray bar underneath the plot

**Additional context**

xref: https://github.com/CenterForMedicalGeneticsGhent/MultiQC_SAV/issues/1#issuecomment-844140500

**Comment by ewels** [comment]
I guess that this is a case of adding a new plot config option for a non-default height at init, and then setting that in a `style` attribute (eg. `style="height:{custom_height}px"`) in this element at run time:

https://github.com/ewels/MultiQC/blob/b63160afafa4b46112f8b8ca6a875f5601de0853/multiqc/plots/heatmap.py#L92

I think that it's this `div` which sets the height anyway, relevant CSS is here:

https://github.com/ewels/MultiQC/blob/26177e92726be92a65d90427fc5829e9e8eb221b/multiqc/templates/default/assets/css/default_multiqc.css#L795-L797

Will need adding to each plot type, not just heatmaps. And a bit of testing to confirm that it works as expected.

Phil

**Comment by ewels** [comment]
@matthdsm done! Have a play and let us know if you have any feedback 😀
