### ISSUE TITLE
Granular disabling of Picard modules

### ISSUE THREAD

**Issue by matthdsm** [ewels/MultiQC#1434]
Hi Phil,
* Question
I'm writing some customized version of plugins available in core (neutered versions, stuff that's no good to merge).
Is there a way to programatically disable the module I'm overwriting? I know I can remove the module from the config object, but in the case of the picard module, this approach isn't viable, since I'm disabling the entire module, instead of just the tools I'm rewriting.

* What I've tried
https://github.com/CenterForMedicalGeneticsGhent/MultiQC_CMGG/blob/main/multiqc_cmgg/multiqc_cmgg.py#L36

**Comment by ewels** [comment]
Hmm, disabling just a sub-module might be tough. The core MultiQC codebase effectively doesn't know about them, they're loaded in https://github.com/ewels/MultiQC/blob/master/multiqc/modules/picard/picard.py

So not sure sorry. You might have to just copy the entire module and change what you want..

**Comment by matthdsm** [comment]
Okay, thanks, I'll try some stuff and get back to you if I figure something out.

M

**Comment by matthdsm** [comment]
Turns out overwriting the searchs patterns is the key
eg.
```python
        # add new key
        config.update_dict(
            config.sp,
            {"sampletracking/crosscheckfingerprints": {"contents": "CrosscheckFingerprints", "shared": False}},
        )
        # overwrite old key
        config.update_dict(
            config.sp, {"picard/crosscheckfingerprints": {"fn": "nonexistent", "shared": False}},
        )
```

**Comment by ewels** [comment]
Smart 👍🏻
