### ISSUE TITLE
The 'cutadapt' MultiQC module broke

### ISSUE THREAD

**Issue by SylviaBG** [ewels/MultiQC#1435]
I am trying to run MultiQC in trimmed fastqc files and I get this error: 

```
[ERROR  ]         multiqc : Oops! The 'cutadapt' MultiQC module broke... 

Module cutadapt raised an exception: Traceback (most recent call last):
  File "/Users/sbasb9/ENTER/lib/python3.8/site-packages/multiqc/multiqc.py", line 592, in run
    mod = config.avail_modules[this_module].load()
  File "/Users/sbasb9/ENTER/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2472, in load
    return self.resolve()
  File "/Users/sbasb9/ENTER/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2478, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'multiqc.modules.cutadapt'
```

**MultiQC run details (please complete the following):**

- Command used to run MultiQC: `multiqc .`
- MultiQC Version: MultiQC v1.10.1
- Operating System: macOS Mojave v 10.14.6
- Python Version: Python 3.8
- Method of MultiQC installation: pip

**Comment by ewels** [comment]
This is an interesting one - could you give any more information about how you installed MultiQC? It sounds like an installation error..

**Comment by SylviaBG** [comment]
I have uninstalled and installed again with pip and it works now... Thanks.

**Comment by ewels** [comment]
Ok great, thanks for letting me know!
