### ISSUE TITLE
vep html not found

### ISSUE THREAD

**Issue by lczech** [ewels/MultiQC#1438]
**Description of bug:**

When running MultiQC v1.10.1 with files produced by VEP 104, the vep html report is not found and not part of the MultiQC report.

**MultiQC Error log:**

```
[INFO   ]         multiqc : This is MultiQC v1.10.1
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching   : /home/lucas/Dropbox/GitHub/grenepipe/test/out-base/qc/qualimap
[INFO   ]         multiqc : Searching   : /home/lucas/Dropbox/GitHub/grenepipe/test/out-base/qc/fastqc
[INFO   ]         multiqc : Searching   : /home/lucas/Dropbox/GitHub/grenepipe/test/out-base/trimmed
[INFO   ]         multiqc : Searching   : /home/lucas/Dropbox/GitHub/grenepipe/test/out-base/annotated
[INFO   ]         multiqc : Searching   : /home/lucas/Dropbox/GitHub/grenepipe/test/out-base/qc/dedup
[INFO   ]         multiqc : Searching   : /home/lucas/Dropbox/GitHub/grenepipe/test/out-base/qc/picard
[INFO   ]         multiqc : Searching   : /home/lucas/Dropbox/GitHub/grenepipe/test/out-base/qc/samtools-flagstats
[INFO   ]         multiqc : Searching   : /home/lucas/Dropbox/GitHub/grenepipe/test/out-base/qc/samtools-stats
Searching   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 301/301  [INFO   ]        qualimap : Found 4 BamQC reports
[INFO   ]          snpeff : Found 1 reports
[INFO   ]          picard : Found 4 AlignmentSummaryMetrics reports
[INFO   ]          picard : Found 7 BaseDistributionByCycleMetrics reports
[INFO   ]          picard : Found 4 GcBiasMetrics reports
[INFO   ]          picard : Found 3 InsertSizeMetrics reports
[INFO   ]          picard : Found 4 MarkDuplicates reports
[INFO   ]          picard : Found 4 QualityByCycleMetrics reports
[INFO   ]          picard : Found 4 QualityScoreDistributionMetrics reports
[INFO   ]          picard : Found 4 QualityYieldMetrics reports
[INFO   ]        samtools : Found 4 stats reports
[INFO   ]        samtools : Found 4 flagstat reports
[INFO   ]     trimmomatic : Found 3 logs
[INFO   ]          fastqc : Found 4 reports
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : qc/multiqc.html
[INFO   ]         multiqc : Data        : qc/multiqc_data
[INFO   ]         multiqc : MultiQC complete
```

The directory with the vep files is:
```
ll /home/lucas/Dropbox/GitHub/grenepipe/test/out-base/annotated
total 1860
drwxrwxr-x  2 lucas lucas   4096 May 24 13:31 ./
drwxrwxr-x 13 lucas lucas   4096 May 24 11:53 ../
-rw-rw-r--  1 lucas lucas  38633 May 24 11:53 snpeff.csv
-rw-rw-r--  1 lucas lucas 725939 May 24 11:53 snpeff.genes.txt
-rw-rw-r--  1 lucas lucas 338619 May 24 11:53 snpeff.html
-rw-rw-r--  1 lucas lucas 429045 May 24 11:53 snpeff.vcf.gz
-rw-rw-r--  1 lucas lucas  14114 May 24 13:21 vep_summary.html
-rw-rw-r--  1 lucas lucas 338915 May 24 13:21 vep.vcf.gz
```
which clearly is scanned by MultiQC, as it does find the SnpEff files in there. The vep file is named according to [the MultiQC documentation](https://multiqc.info/docs/#vep). However, looking at the actual file patterns used by MultiQC, it seems that any `.html` file should also be found.

**File that triggers the error:**

The respective vep file (called `vep_summary.html`, but zipped here for GitHub): [vep_summary.zip](https://github.com/ewels/MultiQC/files/6534834/vep_summary.zip)

**MultiQC run details (please complete the following):**

- Command used to run MultiQC: run via the [Snakemake wrapper](https://snakemake-wrappers.readthedocs.io/en/stable/wrappers/multiqc.html)
- MultiQC Version: MultiQC v1.10.1
- Operating System: Ubuntu 20.04.2 LTS
- Python Version: Not sure which version is run within the conda environment of the wrapper script, but I guess it's Python 3.9.4
- Method of MultiQC installation: Conda, automatically via the Snakemake wrapper

**Comment by ewels** [comment]
Hi @lczech,

The VEP module was only added very recently and is not yet in the stable v1.10.1 release that you are running. It will be in v1.11 - see the changelog here: https://github.com/ewels/MultiQC/blob/master/CHANGELOG.md#multiqc-v111dev

Until then, please try running with the v1.11 dev version:

```bash
pip install --upgrade --force-reinstall git+https://github.com/ewels/MultiQC.git
```

Phil

**Comment by lczech** [comment]
Oooh that makes sense, thanks for the clarification! I was searching for VEP in the change log to see what the status of VEP was, but could not find it there. Makes sense if it hasn't even been added to the stable branch :-D
