### ISSUE TITLE
General stats table floating header when page sidebar collapsed

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#144]
The general stats floating header gets incorrectly truncated when the left sidebar is hidden. This will be due to an incorrect left-offset.

![image](https://cloud.githubusercontent.com/assets/465550/12961831/b59a7536-d042-11e5-9e0a-6e7cf7bb2e22.png)

**Comment by ewels** [comment]
Turns out that it was due to several things..

**Comment by avilella** [comment]
this is the behaviour I was mentioning in the other ticket, thanks for
fixing it :-)
