### ISSUE TITLE
ZeroDivisionError - Kraken2 module breaks when you have 0 unclassified reads

### ISSUE THREAD

**Issue by drpatelh** [ewels/MultiQC#1440]
I tested with MultiQC `v1.10.1`. Creating a fresh folder with just the file below and running `multiqc .` should reproduce the error below:

```console
[ERROR  ] multiqc : Oops! The 'kraken' MultiQC module broke... 
    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
    If possible, please include a log file that triggers the error - the last file found was:
      ./hCoV-19_2021.kraken2.report.txt
  ============================================================
  Module kraken raised an exception: Traceback (most recent call last):
    File "/usr/local/lib/python3.9/site-packages/multiqc/multiqc.py", line 594, in run
      output = mod()
    File "/usr/local/lib/python3.9/site-packages/multiqc/modules/kraken/kraken.py", line 70, in __init__
      self.sum_sample_counts()
    File "/usr/local/lib/python3.9/site-packages/multiqc/modules/kraken/kraken.py", line 237, in sum_sample_counts
      row["counts_rooted"] / self.kraken_sample_total_readcounts[s_name]
  ZeroDivisionError: division by zero
```

The log above didn't point to the erroring file but the correct one is attached below:

[test.kraken2.report.txt](https://github.com/ewels/MultiQC/files/6585047/test.kraken2.report.txt)

**Comment by ewels** [comment]
> The log above didn't point to the erroring file

Yes it did?

```
the last file found was:
      ./hCoV-19_2021.kraken2.report.txt
```

**Comment by ewels** [comment]
ah you mean the one it pointed to was not actually the one that caused the error maybe? Yeah that happens sometimes.

**Comment by ewels** [comment]
Fixed - should be solved in 1.11dev.

Thanks for providing the test data, I thought I fixed it in a about 2 lines but when I tested it, turned out to be a little more involved. Should now work though I think 👍🏻

**Comment by drpatelh** [comment]
Thanks for the quick fix 🙇🏽

**Comment by ewels** [comment]
Oops sorry, just realised that my force-push didn't go through last night. Should now be in place in 3cb88c4d82b0d0e5337d9e105db1e093644bde5f so should now work 🤞🏻
