### ISSUE TITLE
Quast L75 is not in divided by 1000 (K) in the html result.

### ISSUE THREAD

**Issue by GGSonoda** [ewels/MultiQC#1442]
Hello,
I just ran the multiqc in some quast outputs and I noticed the L75 displayed in the html is the actual number of contigs instead of the number of thousands of contigs (K). This is not a serious issue, but seems easy to correct.

The quast version used is QUAST v5.0.2
And the multiqc version is MultiQC v1.10.1
Python version is 3.8
Installed with conda
running on a ubuntu server

**Comment by ewels** [comment]
Great spot @GGSonoda - I can see why that went unnoticed for so long!

This has been fixed by @ErikDanielsson in #1452 (it was due to a typo) and is now available in version 1.11dev. Let me know if you hit any other issues.

Thanks!
