### ISSUE TITLE
RSeQC module: results  junction_annotation.py not included

### ISSUE THREAD

**Issue by guidohooiveld** [ewels/MultiQC#1445]
**Description of bug:**

The results of `junction_annotation.py `(from RSeQC) is not included in the MultiQC report. 

**MultiQC Error log:**

There is no error, but the results from `junction_annotation.py` are not found. However, results from the other RSeQC functions are! Version of RSeQC used is v4.0.0. http://rseqc.sourceforge.net/#junction-annotation-py

Please paste your MultiQC log within the triple backticks below for code formatting
(use a blank line before and after your log)

```
|           multiqc | Search path : /mnt/files/guido//STAR_out
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 44/44  
|             rseqc | Found 1 read_distribution reports
|             rseqc | Found 1 gene_body_coverage reports
|             rseqc | Found 1 inner_distance reports
|             rseqc | Found 1 junction_saturation reports
|             rseqc | Found 1 infer_experiment reports
|             rseqc | Found 1 bam_stat reports

```

**File that triggers the error:**
This ZIP contains the results of `junction_annotation.py` for a single BAM file.
[output_junction_annotation.py.zip](https://github.com/ewels/MultiQC/files/6627354/output_junction_annotation.py.zip)

**MultiQC run details (please complete the following):**

- Command used to run MultiQC:  `multiqc ./STAR_out --filename multiqc_report_Test.html --title "ExperimentTest" --export`
- MultiQC Version:  `v1.11.dev0`
- Operating System:  `Fedora 34`
- Python Version:  `Python 3.9.5`
- Method of MultiQC installation:  `Manual, directly from Github`

**Additional context**
Command to start `junction_annotation.py` in DIR containing the BAM file, and subsequent printed output:
```console
[guidoh@localhost P15-1-6h]$ junction_annotation.py -i P15-1-6h_Aligned.sortedByCoord.out.bam -r  /mnt/files/guido/INDEX/STAR/gencode.v38.primary_assembly.bed -o P15-1-6h.rseqc
Reading reference bed file:  /mnt/files/guido/INDEX/STAR/gencode.v38.primary_assembly.bed  ...  Done
Load BAM file ...  Done

===================================================================
Total splicing  Events: 13560283
Known Splicing Events:  13396049
Partial Novel Splicing Events:  78060
Novel Splicing Events:  78587
Filtered Splicing Events:       7587

Total splicing  Junctions:      201802
Known Splicing Junctions:       137725
Partial Novel Splicing Junctions:       26890
Novel Splicing Junctions:       37187

===================================================================
Create BED file ...
Create Interact file ...
[guidoh@localhost P15-1-6h]$ 
```

Interestingly, this bug has been reported before in December 2019, but apparently no follow up was given because that poster did not respond anymore.
https://github.com/ewels/MultiQC/issues/844#issuecomment-562060621

**Comment by guidohooiveld** [comment]
Well, after finally finding the example output file from` junction_annotation.py` you used to test the parsing ([here](https://github.com/ewels/MultiQC_TestData/blob/master/data/modules/rseqc/junction_annotation/rseqc_junction_annotation.err)), I had a 'brain wave' and was able to solve the problem! My bad that I didn't find that example file earlier...

The solution is that you have to redirect the printed output from `junction_annotation.py` to a txt file. Please note that just using `>` doesn't result in redirecting the correct output, but `2>` does!

Thus, for the archive, the function call below produces a file that can be correctly parsed by MultiQC. (Note the use of `2>` in the 3rd line to redirect the printed output to a txt file; this is the only difference compared to the call I copied in the first post.)
```
[guidoh@localhost P15-1-6h]$ junction_annotation.py -i P15-1-6h_Aligned.sortedByCoord.out.bam \
-r  /mnt/files/guido/INDEX/STAR/gencode.v38.primary_assembly.bed \
-o P15-1-6h.rseqc 2> P15-1-6h.junction_annotation_log.txt
total = 13560283
null device 
          1 
null device 
          1 
[guidoh@localhost P15-1-6h]$ 
```

**Comment by ewels** [comment]
Right, glad you figured it out @guidohooiveld! Yes, `>` just redirects the standard out stream, `2>` redirects standard error. If in doubt you can also do `2>&1 >` which redirects stderr to stdout and then stdout to a file as normal. Then you scoop everything into a single file.

This is true for a lot of tools that MultiQC supports, but still - I'll add a note to the documentation for the RSeQC module about this. Thanks for reporting back 👍🏻 

Phil

**Comment by ewels** [comment]
Added a sentence to the docs: https://multiqc.info/docs/#rseqc
