### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by anamariaUIC** [ewels/MultiQC#1447]
Hello,

I was trying to install MultiQC via:

```bash
module load compilers/python-3.7.3

git clone https://github.com/ewels/MultiQC.git
cd MultiQC
python setup.py install --user
```

I got this message after installation:

```
Using /home/anamaria/.local/lib/python3.7/site-packages
Finished processing dependencies for multiqc==1.11.dev0

--------------------------------
 MultiQC installation complete!
```

therefore I did:

```bash
export PYTHONPATH=/home/anamaria/.local/lib/python3.7/site-packages
```

But when I did:

```console
$ multiqc --version
-bash: multiqc: command not found
```

Can you please help me resolve this?

Thanks
Ana

**Comment by ewels** [comment]
Hi Ana,

This is quite a strange way to install MultiQC. Is there a reason that you can't just use `pip` or `conda`? You don't normally ever need to download / `git clone` the repository unless you intend to do development work with it.

See https://multiqc.info/docs/#installing-multiqc

Phil

**Comment by anamariaUIC** [comment]
Hi Phil,

You are so right, I used pip and worked as a charm.
Just a quick question: which files from STAR output multiQC uses to generate report?
I have these files:
MG-AB-81_S74_RAligned.sortedByCoord.out.bam  MG-AB-81_S74_RLog.out           MG-AB-81_S74_RSJ.out.tab
MG-AB-81_S74_RLog.final.out                  MG-AB-81_S74_RLog.progress.out

I am wondering which one I should keep in one folder in order do to MultiQC analyis.

Thanks
Ana
________________________________

**Comment by ewels** [comment]
Ok brilliant! The docs tell you the file search patterns for every module: https://multiqc.info/docs/#star

So the `Log.final.out` one is the main one here.

Note that it doesn't hurt to run MultiQC on the whole folder though. It just ignores any files it doesn't need - this is the typical way to run it.
