### ISSUE TITLE
difference between qualimap bamqc insert size shape and picard insert size shape

### ISSUE THREAD

**Issue by avilella** [ewels/MultiQC#145]
I am running qualimap bamqc on paired-end datasets aligned from 2x150 sequencing after trimming.
When looking at the distribution of insert sizes, as plotted by MultiQC, I see a difference in shape between the qualimap plots and the plots coming from running Picard InsertSize on the same bams: at around size 149-150 there is drop in both, but then some of the samples in qualimap continue into shorter sizes at a lower level than the same samples on the Picard plot.
I highlighted one of the most affected ones in blue.
Any ideas where this may come from? What data would it be needed to disentangle this difference?
Thanks in advance
![mqc_hcplot_xzktcijsgo 1](https://cloud.githubusercontent.com/assets/158007/12980676/6caea142-d0d5-11e5-8d59-cd72ba50314f.png)
![picard_insert_size 1](https://cloud.githubusercontent.com/assets/158007/12980677/6caec988-d0d5-11e5-9fcf-25f262cfb478.png)
![picard_insert_size](https://cloud.githubusercontent.com/assets/158007/12980675/6cae4e54-d0d5-11e5-8361-7ce7e9ce19af.png)
![mqc_hcplot_xzktcijsgo](https://cloud.githubusercontent.com/assets/158007/12980678/6cb01414-d0d5-11e5-9da4-32ecfae2c2a4.png)

**Comment by ewels** [comment]
This isn't really a MultiQC issue, so may be better suited to somewhere like SeqAnswers ;)

But, my suspicion would be that it has something to do with the way that the two programs are treating overlapping reads (as it only happens below the read length). But whatever it is must be subtle as it doesn't look like a precise / systematic difference.

I would calculate the same plot with as many other tools as possible to work out which is the odd one out - you can do it with [SeqMonk](http://www.bioinformatics.babraham.ac.uk/projects/seqmonk/) and [BamQC](https://github.com/s-andrews/BamQC) to start with.

We had a sort of related conversation about insert sizes on a [BamQC issue](https://github.com/s-andrews/BamQC/issues/14) recently which could give you some more ideas too. For instance, plotting the `TLEN` scores from the `BAM`/`SAM` files..

Phil
