### ISSUE TITLE
Add Pangolin support

### ISSUE THREAD

**Issue by drpatelh** [ewels/MultiQC#1454]
**Tool Details**

- Name of tool: `Pangolin`
- Tool homepage: `https://github.com/cov-lineages/pangolin`
- Tool description: `Software package for assigning SARS-CoV-2 genome sequences to global lineages.`
- Data suitable for MultiQC plot(s): `table`
- Most interesting data for General Stats table: `lineage`

**Tool output:**

- Log filename pattern: ~~`*.pangolin.*`~~ _[none]_
- File contents: Full example output files can be obtained from [here](https://nf-co.re/viralrecon/results#viralrecon/results-f0171324a60d1759ca7f5d02351372d97d22cc12/platform_illumina/variants/ivar/pangolin/)

**Comment by ewels** [comment]
[SAMPLE_01.pangolin.csv](https://github.com/ewels/MultiQC/files/6663938/SAMPLE_01.pangolin.csv)

@drpatelh - can there be more than one sample in these files sometimes? (generally, not just within viralrecon). Or is it always just two lines?

And is it the tool that has the `*.pangolin.*` filename, or is that the pipeline? ie. can we be sure that all pangolin users will have these filenames for the outputs?

**Comment by drpatelh** [comment]
There can indeed be more than one sample in that file - we just so happen to run it on a fasta file with a single entry. Sorry should have mentioned.

The output file can be called whatever you want too as indicated [here](https://github.com/nf-core/modules/blob/c8168bc3516d6f8c3dc6d47c5142073cee82934e/software/pangolin/main.nf#L34) but I put `*.pangolin.*` as a sensible default to sanitise maybe?

**Comment by ewels** [comment]
If there is no standard, then I usually try to find files based on their file contents instead. eg. here probably could do:

```yaml
pangolin:
    contents: pangolin_version
    num_lines: 1
```

**Comment by ewels** [comment]
@ErikDanielsson - fancy taking a crack at this?

**Comment by ewels** [comment]
Merged - will be part of the next release 👍🏻
