### ISSUE TITLE
Add Nextclade support

### ISSUE THREAD

**Issue by drpatelh** [ewels/MultiQC#1455]
**Tool Details**

- Name of tool: `Nextclade`
- Tool homepage: `https://github.com/nextstrain/nextclade`
- Tool description: `Viral genome alignment, clade assignment, mutation calling, and quality checks`
- Data suitable for MultiQC plot(s): `table`
- Most interesting data for General Stats table: `clade`

**Tool output:**

- Log filename pattern: ~~`*.nextclade.*`~~ _[none]_
- File contents: Full example output files can be obtained from [here](https://nf-co.re/viralrecon/results#viralrecon/results-f0171324a60d1759ca7f5d02351372d97d22cc12/platform_illumina/variants/ivar/nextclade/).

Nextclade can output various file formats as listed [here](https://github.com/nf-core/modules/blob/c8168bc3516d6f8c3dc6d47c5142073cee82934e/software/nextclade/main.nf#L26-L30) but adding `csv` support would be a good start.

**Comment by ewels** [comment]
[SAMPLE_01.csv](https://github.com/ewels/MultiQC/files/6663949/SAMPLE_01.csv)

Same questions as in https://github.com/ewels/MultiQC/issues/1454#issuecomment-862456067

> @drpatelh - can there be more than one sample in these files sometimes? (generally, not just within viralrecon). Or is it always just two lines?
> 
> And is it the tool that has the `*. nextclade.*` filename, or is that the pipeline? ie. can we be sure that all Nextclade users will have these filenames for the outputs?

**Comment by drpatelh** [comment]
Same answers as https://github.com/ewels/MultiQC/issues/1454#issuecomment-862465024 :)

**Comment by drpatelh** [comment]
Will try and generate a multi-line file for you to test. Ping me on Slack if I forget.
