### ISSUE TITLE
RSeQC: `read_distribution.py` bar graph double-counts some categories

### ISSUE THREAD

**Issue by blavetn** [ewels/MultiQC#1457]
The RSeQC read distribution plot is using the value reported by the tool as they are but a computing step need to be done because, according to RSeQC manual:

> Tags assigned to `TSS_up_1kb` were also assigned to `TSS_up_5kb` and `TSS_up_10kb`, tags assigned to `TSS_up_5kb` were also assigned to `TSS_up_10kb`.
>
> Therefore:
> ```
> Total Assigned Tags = CDS_Exons + 5’UTR_Exons + 3’UTR_Exons + Introns + TSS_up_10kb + TES_down_10kb
> ```

So it is needed to recompute:

* `new_TES_down_10kb = TES_down_10kb - TES_down_5kb`
* `new_TES_down_5kb = TES_down_5kb - TES_down_1kb`
* `new_TSS_up_10kb = TSS_up_10kb - TSS_up_5kb`
* `new_TSS_up_5kb = TSS_up_5kb - TSS_up_1kb`

Only then does:

```
Total Assigned Tags = CDS_Exons + 5’UTR_Exons + 3’UTR_Exons + Introns + TSS_up_1kb + new_TSS_up_5kb + new_TSS_up_10kb + TES_down_1kb + new_TES_down_5kb + new_TES_down_10kb
```

Otherwise the percentage of all the features can be >= 100% !

**Comment by ewels** [comment]
Example tool output:

https://github.com/ewels/MultiQC_TestData/blob/master/data/modules/rseqc/read_distribution/RSeQC_rd_P2005_102.out.txt

```
read_distribution.py 2.6.1
Total Reads                   71859250
Total Tags                    83076623
Total Assigned Tags           79927698
=====================================================================
Group               Total_bases         Tag_count           Tags/Kb             
CDS_Exons           94670410            41691981            440.39            
5'UTR_Exons         7515324             295162              39.27             
3'UTR_Exons         27691393            4991227             180.24            
Introns             1502423972          30914721            20.58             
TSS_up_1kb          33825059            425459              12.58             
TSS_up_5kb          150279744           617325              4.11              
TSS_up_10kb         268263971           785889              2.93              
TES_down_1kb        35625947            302610              8.49              
TES_down_5kb        154052043           994449              6.46              
TES_down_10kb       270854584           1248718             4.61              
=====================================================================
```

Right, so to rewrite your suggestion in my own words to be sure that I understand it: we basically need to make new variables to use in the bar graph that are:

* `TES_down_5kb-10kb` (`TES_down_10kb` - `TES_down_5kb`)
* `TES_down_1kb-5kb` (`TES_down_5kb` - `TES_down_1kb`)
* `TES_down_1kb` (unchanged)

(and equivalent for `TSS_up`).

Makes sense 👍🏻  Thanks for reporting! Good spot..

Phil

**Comment by blavetn** [comment]
Exactly !

**Comment by ewels** [comment]
Thanks for letting us know!
