### ISSUE TITLE
beehive plot for samtools stats is not interactive

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [ewels/MultiQC#1491]
### Description of bug

The beehive plot for samtools stats is **not** interactive, even though the text surrounding it indicates that it should be. 

https://user-images.githubusercontent.com/15323399/125311749-efbe5e80-e333-11eb-8f51-b6f5ea0e8571.mp4

**Comment by ewels** [comment]
It is for me! Please could you attach a HTML report and let me know which web browser you're using?

**Comment by Maarten-vd-Sande** [comment]
This is an example of one that isn't working for me:

http://ocimum.science.ru.nl/multiqc_GRCm38.p6.html#samtools-stats

However when I check on my partner's mac+safari it works. So it doesn't seem to be this specific report. My browser is:

```
Mozilla Firefox for Ubuntu
canonical - 1.0
96.0 (64-bit)
```

**Comment by Maarten-vd-Sande** [comment]
It works the first 0.5 second I open the notebook :see_no_evil:

**Comment by siebrenf** [comment]
same on Windows 10:
- with Firefox 96.0.3 (64-bit), the plot works for a split second on (re)load. 
- with Chrome it works.

**Comment by ewels** [comment]
Uck, browser specific issues are the worst 🤦‍♂️ 

I only have a mac and can't easily test on windows, so this is going to be very difficult to fix. If anyone can help that would be much appreciated 🙏

**Comment by Maarten-vd-Sande** [comment]
I'm guessing it is firefox related. I'm not sure if this is faulty on the multiqc side, seeing as it is browser specific it seems to be more highcharts related....

**Comment by ewels** [comment]
I wouldn't be surprised if this would resolve itself if I updated HighCharts though.. 👀  I'm hoping to find time to do a major update and overhaul of the front-end libraries this year (Bootstrap, HighCharts and more).

I'll close this issue for now if that's ok, as I _think_ that it's outside the scope of MultiQC and I can't replicate it (though admittedly I haven't tried super hard). Happy to reopen if anyone has any insights of things we could do to address it.
