### ISSUE TITLE
Conda installation Issues

### ISSUE THREAD

**Issue by sanyalab** [ewels/MultiQC#1505]
### Description of bug

Hello,

I have installed python=3.6 in conda under a new environment. I am unable to install multiqc using the `conda install multiqc` command. Attached is the error.

[Conda_installation_error.txt](https://github.com/ewels/MultiQC/files/6891811/Conda_installation_error.txt)

I can install multiQC with python2, but we are moving to python3 and so I wanted to upgrade multiqc.

Please Advice
Thanks
Abhijit

**Comment by ewels** [comment]
Hi @sanyalab,

Conda can be a strange a mysterious beast sometimes, occasionally hitting weird conflicts with underlying base packages and the like. Is it an option to use `pip` to install MultiQC into your conda environment? That often works, even when conda refuses to play ball. Mamba is often more successful too, and can at least give more helpful error messages. Also please be sure that your installation of conda is up to date, and that you have your conda channels configured exactly [as described in the bioconda docs](https://bioconda.github.io/user/install.html#set-up-channels).

MultiQC now only supports python 3, so py2 is definitely a bad idea :)

Phil
