### ISSUE TITLE
Add all filename search patterns to default name cleaning

### ISSUE THREAD

**Issue by a-frantz** [ewels/MultiQC#1506]
### Description of feature

I encountered this using the Picard `ValidateSamFile` module, but I imagine it's present for other modules as well.

In order to get my result files into MultiQC I added the extension `.ValidateSamFile.txt` to my files (basename of the file being the proper sample name), but now they appear inside the report as `[real sample name].ValidateSamFile`. So I have 2 entries in the general stats table for each sample. One entry with every other module stats, and one dedicated the Picard.

This is easily fixable on my end by just adding `.ValidateSamFile` under `extra_fn_clean_exts` in my config, but IMO any triggering search pattern should already be cleansed.

**Comment by ewels** [comment]
I kind of like the idea, but I think in practice this might be quite difficult to do. We can't remove the matching pattern from the sample name as that usually matches the entire filename (`*.suffix.txt`) and whilst many have a simple plaintext ending not all do. For example, what do we do for patterns with `?` or the more complicated regular expressions? I wonder if it's just a little bit too much down the "black box magic" path.

In this case, I think I would prefer to keep things more explicit and leave the behaviour as it is. Like you say, it's quite easy to fix and I think the automatic behaviour could lead to confusion and unexpected problems.

Thanks for the suggestion anyway!
