### ISSUE TITLE
Show the overrep. and adapter sequences

### ISSUE THREAD

**Issue by arnikz** [ewels/MultiQC#1507]
### Description of feature

Hi,
Thanks for developing this very useful tool. I couldn't find in the doc etc. if it's possible to view all the overrep. and adapter sequences in a set of FASTQ files without peeking into the original FASTQC reports back-and-forth. Thanks for help!

**Comment by ewels** [comment]
Hi @arnikz,

The short answer is no, sorry. Very early versions of MultiQC had this information but it's a lot of data and it very quickly bloats the generated HTML report. It soon became that if you ran on ~100 samples (which is very common) then it would crash the browser.

Hopefully the MultiQC plots are enough to flag your attention if you have a serious problem with either, but then you'll need to go back to the original reports to dig into the details.

Phil
