### ISSUE TITLE
search patterns match file ending

### ISSUE THREAD

**Issue by dakl** [ewels/MultiQC#151]
In the fastqc step in my upstream pipeline, `_fastqc.zip` files are generated, but also `_fastqc.zip.done`. 

When I run MultiQC, both the `zip` and the `zip.done` files are matched by the file name pattern in `search_patterns.yaml` and therefore reported in the resulting `multiqc_sources.txt` file. 

The `.done` files are empty, so they don't affect the actual report, and therefore (i think) should not be written to `multiqc_sources.txt`. 

I tried altering `search_patterns.yaml` to `_fastqc.zip$` (note trailing `$`) but that just caused no files to match. 

snippet from `multiqc_sources.txt`:

```
FastQC  all_sections    n_1     /Users/dankle/vms/fairbanks/p2/qc/fastqc/n_1_fastqc.zip
FastQC  all_sections    n_2     /Users/dankle/vms/fairbanks/p2/qc/fastqc/n_2_fastqc.zip
FastQC  all_sections    .t_2_fastqc.zip.done    /Users/dankle/vms/fairbanks/p2/qc/fastqc/.t_2_fastqc.zip.done
FastQC  all_sections    .n_2_fastqc.zip.done    /Users/dankle/vms/fairbanks/p2/qc/fastqc/.n_2_fastqc.zip.done
```

**Comment by dakl** [comment]
Whoa! That was quick :) :+1:

**Comment by ewels** [comment]
Hi @dakl - this should fix it.

The FastQC module is a bit of a mess really, needs some proper refactoring to clean it up...
