### ISSUE TITLE
Picard insert size plot in MultiQC occasionally has an unexpected behaviour

### ISSUE THREAD

**Issue by Lori-tan** [ewels/MultiQC#1525]
### Description of bug

I filtered a bam file based on the insert sizes and run picard to get the insert size histogram for both unfiltered and filtered (<= 120 bp, to be specific) fragments. Then I run MultiQC to generate the report. 

Ideally, I should get plots like the one below, where blue line represents the histogram of unfiltered fragments and black line is the histogram of filtered (<= 120bp) fragments: 
<img width="1003" alt="Screen Shot 2021-08-16 at 2 45 20 PM" src="https://user-images.githubusercontent.com/61303400/129614202-a7a32387-f365-4a4b-a943-c747c1fc50ef.png">

However, with some other data, I got the plot below, where blue and black lines don't overlap for the part <= 120bp. 
<img width="999" alt="Screen Shot 2021-08-16 at 2 45 39 PM" src="https://user-images.githubusercontent.com/61303400/129614474-a89249ee-3422-42a0-82b2-f5c5667eda4c.png">

I check the Picard output files that was used by MultiQC (insert_size_metrics.txt file), and those files matches perfectly (showing part of them below, left: unfiltered, right: filtered). And I noticed that the blue line in the above histogram seems to have an unexpectedly high y-value, which doesn't match the metrics file.
<img width="1215" alt="Screen Shot 2021-08-16 at 2 53 53 PM" src="https://user-images.githubusercontent.com/61303400/129615442-872c14d0-0fdf-4dbf-abfb-063e95089fa0.png">

I have no idea what's going on and whether or not it is a MultiQC error or not.  Please take a look.

Thanks a lot.

**Comment by ewels** [comment]
Ok, so this is a really tricky one. What's happening here is that MultiQC is subsampling the plot when it gets more than 500 data points. These plots can be many thousands of data points on the x-axis which can really bloat the MultiQC report filesize if there are lots of samples. So we automatically bin the data at a certain point.

I guess what's happening here is that one sample is being subsampled and the truncated one isn't. As such, the counts for each point end up being different. It's possible that the smoothing code could be improved to better maintain the y values, but it's not trivial to get a generalised solution.

Probably the easiest solution for you is to disable the smoothing, or at least bump up the threshold at which it happens. This is [described in the docs](https://multiqc.info/docs/#insertsizemetrics):

```yaml
picard_config:
  insertsize_smooth_points: 999999999999
```

I suspect that if you apply this config then your lines will match up again.

Closing now, but if you have any suggestions on changes we can make to the MultiQC code then let me know and I can reopen.

Phil
