### ISSUE TITLE
The 'picard' MultiQC module broke - KeyError

### ISSUE THREAD

**Issue by RachelDuffin** [ewels/MultiQC#1544]
### Description of bug

When running multiqc the picard MultiQC module breaks and no multiqc report is output. I am using Ubuntu 20.04 (Python 3.8.10). I have tried running with multiqc v1.10.1 docker and it completes with no errors. I have tried with both the official multiqc docker image (v1.11) and building my own docker image using the github repo - both of these output the same error . 

The Picard module breaks due to `collectilluminabasecalling.py` script, I think because it is unable to find the file/key it is looking for - this is because Picard CollectIlluminaBasecallingMetrics was never run on the sample in the first place. I am looking to update to the newer version due to the added support for CollectIlluminaLaneMetrics. 

If there was a way to prevent this script from running or stop the error if it can't find the file it is looking for it should fix the problem. Unless I am missing something!

The files that I am using are as follows, all Picard outputs:
- .alignment_summary_metrics 
- .base_distribution_by_cycle.pdf 
- .base_distribution_by_cycle_metrics 
- .hsmetrics.tsv 
- .insert_size_histogram.pdf 
- .insert_size_metrics 
- .pertarget_coverage.tsv
- .quality_by_cycle.pdf 
- .quality_by_cycle_metrics 
- .quality_distribution.pdf 
- .quality_distribution_metrics 

### File that triggers the error

Absence of Picard collectilluminabasecallingmetrics output files. 

```
### MultiQC Error log

  /// MultiQC 🔍 | v1.11

|           multiqc | Excluding modules 'gatk'
|           multiqc | Search path : /usr/src/multiqc/multiqc
|           multiqc | Search path : /home/dnanexus
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 453/453  
|            picard | Found 1 AlignmentSummaryMetrics reports
|            picard | Found 2 BaseDistributionByCycleMetrics reports
|            picard | Found 1 HsMetrics reports
|            picard | Found 1 InsertSizeMetrics reports
|            picard | Found 1 QualityByCycleMetrics reports
|            picard | Found 1 QualityScoreDistributionMetrics reports
╭───────────────── Oops! The 'picard' MultiQC module broke... ─────────────────╮
│ Please copy this log and report it at                                        │
│ Traceback (most recent call last):                                           │
│   File "/usr/lib/python3.8/site-packages/multiqc/modules/picard/picard.py",  │
│     n["CollectIlluminaBasecallingMetrics"] = CollectIlluminaBasecallingMetri │
│   File "/usr/lib/python3.8/site-packages/multiqc/modules/picard/CollectIllum │
│     if not data["MOLECULAR_BARCODE_SEQUENCE_1"]:                             │
│ KeyError: 'MOLECULAR_BARCODE_SEQUENCE_1'                                     │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯
|            snippy | Found 2 reports
|          bargraph | Tried to make bar plot, but had no data
|           multiqc | Compressing plot data
|           multiqc | Report      : ../../../home/dnanexus/out/multiqc/QC/multiqc/003_210907_multiqc_v1.14.0-multiqc.html
|           multiqc | Data        : ../../../home/dnanexus/out/multiqc/QC/multiqc/003_210907_multiqc_v1.14.0-multiqc_data
|           multiqc | MultiQC complete
```

**Comment by RachelDuffin** [comment]
Or is there a way for me to just exclude the multiqc picard/collectilluminabasecallingmetrics? As I don't actually need this but it is breaking multiqc

**Comment by RachelDuffin** [comment]
Seems like the issue was with the official docker image. Creating my own docker image seems to have fixed the problem.

**Comment by ewels** [comment]
Strange! Ok, well please let me know if you hit the issue again. I need some example files to replicate the error in order to help really.

Thanks,

Phil
