### ISSUE TITLE
Nanostat - ignores some output styles

### ISSUE THREAD

**Issue by ceolder** [ewels/MultiQC#1547]
### Description of bug

Hi, first thank you for adding a module for nanostat output! 
I ran nanostat on several files and am now attemping to run multiqc and running into the issue "No analysis results found. Cleaning up..."
Version 1.11
Command I'm running:
`multiqc NanoStat/*.txt -n NanoStat_multiqc --m nanostat`

I have tried without the *.txt (only the output txt files are in this directory) and the -m nanostat, but adding those on in case.

I've attached two files of the 32 that I am trying to use multiqc on.

I have looked at the search patterns specifically for the NanoStat module. My files were generated using the default parameters for NanoStat (version 1.5.0) and I checked to see if there's any parameters I could mess with to change the output and there are not. The search parameters say it should have 20 lines, but my output has 27 and while it does not start with the text listed under contents "Number, percentage ...", they are in my files on line 10. So I'm not sure if I'm supposed to modify the resulting files to be accessible for MultiQC? 

### File that triggers the error

[10X_Pond1_1525_filt.txt](https://github.com/ewels/MultiQC/files/7145666/10X_Pond1_1525_filt.txt)
[10X_Pond1_1492_filt.txt](https://github.com/ewels/MultiQC/files/7145667/10X_Pond1_1492_filt.txt)

### MultiQC Error log

```console
multiqc NanoStat/*.txt -n NanoStat_multiqc -m nanostat

  /// ;id=61841;https://multiqc.infoMultiQC;;  | v1.11

|           multiqc | Only using modules: nanostat
|           multiqc | Search path : /home/caitlin/OttPonds/NanoStat/10X_Pond1_1492_filt.txt
|           multiqc | Search path : /home/caitlin/OttPonds/NanoStat/10X_Pond1_1525_filt.txt
|           multiqc | Search path : /home/caitlin/OttPonds/NanoStat/10X_Pond2_1492_filt.txt
|           multiqc | Search path : /home/caitlin/OttPonds/NanoStat/10X_Pond2_1525_filt.txt
|           multiqc | Search path : /home/caitlin/OttPonds/NanoStat/10X_Pond3_1492_filt.txt
|           multiqc | Search path : /home/caitlin/OttPonds/NanoStat/10X_Pond3_1525_filt.txt
|           multiqc | Search path : /home/caitlin/OttPonds/NanoStat/10X_Pond4_1492_filt.txt
|           multiqc | Search path : /home/caitlin/OttPonds/NanoStat/10X_Pond4_1525_filt.txt
|           multiqc | Search path : /home/caitlin/OttPonds/NanoStat/10X_Pond5_1492_filt.txt
|           multiqc | Search path : /home/caitlin/OttPonds/NanoStat/10X_Pond5_1525_filt.txt
|           multiqc | Search path : /home/caitlin/OttPonds/NanoStat/10X_Pond6_1492_filt.txt
|           multiqc | Search path : /home/caitlin/OttPonds/NanoStat/10X_Pond6_1525_filt.txt
|           multiqc | Search path : /home/caitlin/OttPonds/NanoStat/10X_Pond7_1492_filt.txt
|           multiqc | Search path : /home/caitlin/OttPonds/NanoStat/10X_Pond7_1525_filt.txt
|           multiqc | Search path : /home/caitlin/OttPonds/NanoStat/10X_Pond8_1492_filt.txt
|           multiqc | Search path : /home/caitlin/OttPonds/NanoStat/10X_Pond8_1525_filt.txt
|           multiqc | Search path : /home/caitlin/OttPonds/NanoStat/35X_Pond1_1492_filt.txt
|           multiqc | Search path : /home/caitlin/OttPonds/NanoStat/35X_Pond1_1525_filt.txt
|           multiqc | Search path : /home/caitlin/OttPonds/NanoStat/35X_Pond2_1492_filt.txt
|           multiqc | Search path : /home/caitlin/OttPonds/NanoStat/35X_Pond2_1525_filt.txt
|           multiqc | Search path : /home/caitlin/OttPonds/NanoStat/35X_Pond3_1492_filt.txt
|           multiqc | Search path : /home/caitlin/OttPonds/NanoStat/35X_Pond3_1525_filt.txt
|           multiqc | Search path : /home/caitlin/OttPonds/NanoStat/35X_Pond4_1492_filt.txt
|           multiqc | Search path : /home/caitlin/OttPonds/NanoStat/35X_Pond4_1525_filt.txt
|           multiqc | Search path : /home/caitlin/OttPonds/NanoStat/35X_Pond5_1492_filt.txt
|           multiqc | Search path : /home/caitlin/OttPonds/NanoStat/35X_Pond5_1525_filt.txt
|           multiqc | Search path : /home/caitlin/OttPonds/NanoStat/35X_Pond6_1492_filt.txt
|           multiqc | Search path : /home/caitlin/OttPonds/NanoStat/35X_Pond6_1525_filt.txt
|           multiqc | Search path : /home/caitlin/OttPonds/NanoStat/35X_Pond7_1492_filt.txt
|           multiqc | Search path : /home/caitlin/OttPonds/NanoStat/35X_Pond7_1525_filt.txt
|           multiqc | Search path : /home/caitlin/OttPonds/NanoStat/35X_Pond8_1492_filt.txt
|           multiqc | Search path : /home/caitlin/OttPonds/NanoStat/35X_Pond8_1525_filt.txt
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 32/32
|           multiqc | No analysis results found. Cleaning up..
|           multiqc | MultiQC complete
```

**Comment by sherryxuePKU** [comment]
I've encountered the same problem.

**Comment by MillironX** [comment]
Same problem here.

- MultiQC v1.11 (conda)
- Fedora 34

Example file: [f479_nanostat.log](https://github.com/ewels/MultiQC/files/7479446/f479_nanostat.log)

**Comment by ewels** [comment]
Right, so I tested your file @MillironX and the verbose log (`-v`) shows that it's being ignored by this code:

https://github.com/ewels/MultiQC/blob/a259b0890a6e0706a4440b1438a25e21cb3b6962/multiqc/modules/nanostat/nanostat.py#L108-L116

The file indeed does not contain either of these strings. All of the outputs that we have in the [test data repo](https://github.com/ewels/MultiQC_TestData/tree/master/data/modules/nanostat) do though.

Presumably this is another flavour of of Nanostat output. The module needs updating to handle this style.

> The search parameters say it should have 20 lines,

Right, this is a little confusing @ceolder - the search parameters say that the `content` string that it's looking for should be within the first 20 lines. Not that the file itself should have no more than 20 lines. (I had to check [my own docs](https://multiqc.info/docs/#step-1-find-log-files) to clear this one up for myself..!)

**Comment by ceolder** [comment]
@ewels Thank you for spending some time looking into this and explaining the issue. 
@MillironX is correct, my logs also came from fastq files.

**Comment by ewels** [comment]
Sounds good, thanks both - and thanks for the tests and example files @MillironX. Let's go for option 1, get the module to recognise everything and plot what it can.

If you fancy making a pull request, it would be nice to reorganise the test data in ewels/MultiQC_TestData into subfolders based on what it ran on so that this is clear for the future. Then of course the updates to the module. Otherwise I'll get to it when I can 👍
