### ISSUE TITLE
Preventing submodules from running

### ISSUE THREAD

**Issue by RachelDuffin** [ewels/MultiQC#1549]
From the documentation I can see that a whole module can be prevented from running by using `exclude_modules` - however this doesn't seem to have an option to prevent a specific submodule from running. I am trying to update to MultiQC v1.11 however some of the newly added Picard modules (specifically `CollectIlluminaBasecallingMetrics`) are breaking - I don't actually need these new sub modules so would like to prevent them from running altogether - have I missed something or is this not currently possible?

**Comment by sophie22** [comment]
I think that running of a submodule can be prevented by not providing the associated metric files to MultiQC and/or by setting the sp for that module to null.

**Comment by ewels** [comment]
Exactly as @sophie22 says - you can do this by telling MultiQC to not look for those submodule files. This isn't super clear in the documentation, so I'll add a note and an example.

**Comment by ewels** [comment]
Whilst looking at [the docs](https://multiqc.info/docs/#removing-modules-or-sections), I was reminded that you can also remove the section of the report. 

So for `CollectIlluminaBasecallingMetrics` if you click the sidebar navigation for that section you'll see `multiqc_report.html#picard-illuminabasecallingmetrics` in the browser address bar. You can then tell MultiQC to remove that section from future reports with the following config:

```yaml
remove_sections:
  - picard-illuminabasecallingmetrics
```

**Comment by ewels** [comment]
Added a paragraph and example in f4cf31d137c0a786ff14921944064c56b3b3fc07 for the [Removing modules or sections](https://multiqc.info/docs/#removing-modules-or-sections) section of the docs:

> Finally, you can prevent MultiQC from finding the files for a module or submodule by customising
> its search pattern. For example, to skip Picard Base Calling metrics, you could use the following:
> 
> ```yaml
> sp:
> picard/collectilluminabasecallingmetrics:
> skip: true
> ```
> 
> The search pattern identifiers can be found in the documentation below for each module.
