### ISSUE TITLE
Custom Content: Section name and description based on filename for `.txt` files

### ISSUE THREAD

**Issue by BELKHIR** [ewels/MultiQC#1550]
Hi,

Actually, the section name and description are automatically based on the filename for png, jpeg and jpg files with `_mqc` at the end of the filename.

Is it possible to extend this behavior to filenames ending with `*_mqc.(yaml|yml|json|txt|csv|tsv|log|out|png|jpg|jpeg|html)` ?

Many thanks

**Comment by ewels** [comment]
Hi @BELKHIR,

Could you please provide a little more detail and ideally an example file? When I test with [one of my example `.txt` files](https://github.com/ewels/MultiQC_TestData/blob/master/data/custom_content/no_config/issue_1091_mqc.txt) it does set the section name as the filename.

Phil

**Comment by BELKHIR** [comment]
Hi @ewels,

I tested with your provided txt file and the result was fine !
However, it seems that this problem is related to the lack of header line in txt files.
ex  this file of PCA eigenvalues will reproduce the problem : 
axis1	3.65933584612439
axis2	1.548253919225
axis3	0.461137974231304
axis4	0.417858586883222
axis5	0.407933212752084
axis6	0.385368911026864
axis7	0.370025550609452
axis8	0.358294662093722
 
While if we add a header line there is no more problem with section name and description generation : 
Axis	        Value
axis1	3.65933584612439
axis2	1.548253919225
axis3	0.461137974231304
axis4	0.417858586883222
axis5	0.407933212752084
axis6	0.385368911026864
axis7	0.370025550609452
axis8	0.358294662093722

Thank's a lot,

Khalid,

**Comment by ewels** [comment]
Thanks, confirmed my end - I'll take a look 👍🏻

**Comment by ewels** [comment]
ok, found the culprit. Should be fixed in 01457ca23ed841f4cbcdf10fc72e6fff3083eb2c
