### ISSUE TITLE
Add CheckQC module

### ISSUE THREAD

**Issue by maleasy** [ewels/MultiQC#1551]
### Name of the tool

CheckQC

### Tool homepage

https://github.com/Molmed/checkQC

### Tool description

CheckQC is a program designed to check a set of quality criteria against an Illumina runfolder

### Tool output

CheckQC's `--json` flag prints JSON formatted results to the stdout, see this example:
[checkqc.json.zip](https://github.com/ewels/MultiQC/files/7184631/checkqc.json.zip)

### Data suitable for MultiQC plot(s)

CheckQC includes up to six QC checks (handlers), and only lists the samples/lanes that to not pass a check. There could be one plot per check

### Most interesting data for the General Stats table

Samples with too few reads, listed in the JSON output in the "ReadsPerSampleHandler" section:

```json
  "ReadsPerSampleHandler": [
    {
      "type": "error",
      "message": "Number of reads for sample 4 was too low on lane 1, it was: 17.456 M",
      "data": {
        "lane": 1,
        "number_of_samples": 6,
        "sample_name": "4",
        "sample_reads": 17.455795,
        "threshold": 22.5
      }
    }
  ]
```

**Comment by maleasy** [comment]
Created a pull request for such a module #1552

**Comment by ewels** [comment]
PR merged. Thanks!

**Comment by maleasy** [comment]
👍
