### ISSUE TITLE
`--ignore` does not work properly

### ISSUE THREAD

**Issue by nikalfa11** [ewels/MultiQC#1558]
### Description of bug

Hi,
in the directory containing FastQC outputs where I am running multiqc there are 2 files called:

* `Undetermined_S0_R1_001_fastqc.zip`
* `Undetermined_S0_R2_001_fastqc.zip`

besides the FastQC of all other samples. I would like to run multiqc ignoring the 2 Undetermined files. So I ran inside this directory:

```console
> multiqc . --ignore Undetermined*
> multiqc . --ignore Undetermined_S0_R1_001_fastqc.zip,Undetermined_S0_R2_001_fastqc.zip
```

Any of these options worked and the Undetermined files were included. Only when I tried one file name at the time, it worked:

```console
> multiqc . --ignore Undetermined_S0_R1_001_fastqc.zip
```

MultiQC ignored the Undetermined R1 file. Why the first two commands didn't work? Shouldn't the command with the `*` work for both files? And how to ignore multiple files at once?

Thank you very much in advance

Niccolò

**Comment by ewels** [comment]
My first guess is that you need to enclose the `*` in quotes:

```bash
multiqc . --ignore "Undetermined*"
```

Without this, `bash` will be expanding the glob before it gets to MultiQC. MultiQC will actually receive the following:

```bash
multiqc . --ignore Undetermined_S0_R1_001_fastqc.zip Undetermined_S0_R2_001_fastqc.zip
```

This will be treating the second filename (`Undetermined_S0_R2_001_fastqc.zip`) as an input search path. In this case that would have no effect. I suspect if you check again that _one_ of the undetermined files is always skipped?

If I'm right and the documentation needs fixing, or I'm wrong and it's something else. Either way, thanks for reporting 😀

**Comment by MatthiasZepper** [comment]
@nikalfa11 Thank you for bringing this issue to our attention. 

I have now updated [the documentation](https://multiqc.info/docs/#choosing-where-to-scan) to clarify how the `--ignore` option can be used with multiple files. Subject to approval, it will in the future explicitly cover an example how to specify multiple files as the option's argument. Briefly, either use a quoted wildcard argument: 

`multiqc . --ignore "Undetermined*"` 

or specify the option multiple times: 

`multiqc . --ignore "Undetermined_S0_R1_001_fastqc.zip" --ignore "Undetermined_S0_R2_001_fastqc.zip"` 

Lycka till!

**Comment by ewels** [comment]
Great! Thanks for confirming @nikalfa11 👍🏻
