### ISSUE TITLE
DRAGEN does not use `self.clean_s_name()`

### ISSUE THREAD

**Issue by jamigo** [ewels/MultiQC#1559]
### Description of feature

I was having problems trying to unsuccessfully clean sample names from my DRAGEN files, but I came across a bugfix (#1537) that made me realize that MultiQC was looking to full file names `f["fn"]` rather than cleaned ones `f["s_name"]` on purpose.

What I first thought was a bug I realized that it was meant to be that way, so I'm currently asking if there can be an option to choose which source to use for extracting data from DRAGEN files. Thank you in advance.

**Comment by jamigo** [comment]
What I meant is that I, as a user, would like to keep everything tidy, and therefore cleaning the sample names is crucial for our end-users that receive these reports. I can see that you, as a developer, may prefer dealing with DRAGEN's raw file names without being cleaned, so this may not be a bug but a decision. I'm just asking for the possibility of using that self.clean_s_name() function because it would work for us, without knowing exactly all the reasons why you would have decided not to use it. And yes, the solution would be as simple as just calling that function.

**Comment by ewels** [comment]
Fixed in a066edd - see also duplicate issue #1610
