### ISSUE TITLE
Cannot parse header in gffCompare module

### ISSUE THREAD

**Issue by nservant** [ewels/MultiQC#1580]
### Description of bug

The `gffCompare` module in Multiqc v1.11 is crashing.
According to the error, it seems to come from the gffcompare.stats header.

Note that I renamed here the `.stats` file in `.stats.txt` to upload it

### File that triggers the error

[gffcompare.stats.txt](https://github.com/ewels/MultiQC/files/7512164/gffcompare.stats.txt)

### MultiQC Error log

```console
/// MultiQC 🔍 | v1.11

|           multiqc | Report title: clever_monod
|           multiqc | Only using modules: custom_content, preseq, rseqc, bowtie1, hisat2, star, cutadapt, fastqc, qualimap, salmon, gffcompare
|           multiqc | Search path : /bioinfo/users/nservant/GitLab/RNA-seq/work/4e/57b3fafb0512d8637ba76ce3a4050c
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 140/140  
|    custom_content | Could not parse comment file header for MultiQC custom content: gffcompare.stats
```

**Comment by ewels** [comment]
This log says it's coming from the `custom_content` module, not `gffcompare`.

Are you sure you don't have any configs set up that are telling custom content to parse `.stats` files or something?

**Comment by nservant** [comment]
well done. Sorry for that !

**Comment by ewels** [comment]
Great 😁 No worries!
