### ISSUE TITLE
Fastqc reporting doesn't work for me (possibly due to my malpractice)

### ISSUE THREAD

**Issue by alneberg** [ewels/MultiQC#16]
Hi again,

I seem to be naughty and rename the output .zip archives from fastqc (its done by our workflow to avoid outputfiles be named P1994_101_R1.fq_fastqc.html, but instead P1994_101_R1_fastqc.html when running on .fq.gz files), this causes confusion in multiqc since the dirname within the zip archive is still the old one... 

When multiqc tries to look for the fastqc_data.txt file within the .zip it results in a KeyError since the directory name within the zip is wrong. I guess one could argue this is malpractice or a problem with fastqc, but it would be nice if multiqc could be tolerant of renaming the zip archives. I think I can sketch on a pull request for this if you may assist with comments and you think its a good idea.

Thanks,
Johannes

**Comment by ewels** [comment]
Aha, I see! Yes, I hadn't thought of that. I guess renaming the zip files won't be _that_ uncommon, and as you say it should be a fairly easy fix (just searching for any file called `fastqc_data.txt` without tying this to a directory name).

I'm actually rewriting the code that does the file imports at the moment, so I can pop this in now if you like..

**Comment by alneberg** [comment]
Ah, excellent! I didnt fully grasp the whole flow of the imports anyway.
Den 10 sep 2015 14:42 skrev "Phil Ewels" <notifications@github.com>:

**Comment by ewels** [comment]
Yeah, it was a little complicated and pretty much the same in each module. So made sense to refactor and put that code in the base module. Should be quite a bit clearer now hopefully..

**Comment by alneberg** [comment]
Great! I guess its bad practice to add another issue here, but since we're discussing file reading. I commonly have multiple reports for the same sample (i.e. fastqc before and after running cutadapt). These are only distinguished by the path and not the file name, which have caused multiqc to only read in one of them. Do you see any possibility to add more than one fastqc result for a single sample in this way?

Thanks,
Johannes

**Comment by ewels** [comment]
# Yes
Try the `-d` command line option :wink: 

..I _like_ those kinds of issues :grinning:

**Comment by ewels** [comment]
Did it do what you wanted @alneberg?

**Comment by alneberg** [comment]
It might, but I'm having troubles trying it out due to the first issue.. haha.

**Comment by ewels** [comment]
Ok, try that!

**Comment by alneberg** [comment]
It works! Excellent! :+1:
