### ISSUE TITLE
Don't postfix sample name with "wg" for dragen coverage in general stats

### ISSUE THREAD

**Issue by WimSpee** [ewels/MultiQC#1610]
### Description of feature

Hi @ewels 

Thank you for the very nice multiqc tool and support for dragen QC CSV files. 

One thing that could be improved is not adding the "wg" postfix to sample names in the general stats table. 

This doubles the size of the general stats table and makes is difficult to use that table. 

See this example table for 2 WGS samples analyzed via dragen. 
<img width="950" alt="dragen_multiqc_wg_sample_postifx" src="https://user-images.githubusercontent.com/34706930/148574522-c4fb3c44-3a38-4d1c-93ab-c55e77c37e5a.png">

The table general stats table should have 2 rows, but somehow has 4 rows.  
Sorting the table is also not intuitive with because of the empty values in the columns. 
With 2 samples this is not that big an issue, but with many samples the table becomes very large and difficult to use (e.g. sort on a column).

I am not sure where the wg postfix comes from. It is not in the content of the `XXDA_762_05.wgs_coverage_metrics.csv` file. 
I guess this is parsed from the `XXDA_762_05.wgs_coverage_metrics.csv` file name here. 

Maybe here:

https://github.com/ewels/MultiQC/blob/3a697a43fd63b14f1d036c617cf1d01531b1d4e6/multiqc/modules/dragen/coverage_metrics.py#L397

The only reasons I would see for needing to add the `wg` postfix is if the same sample would be sequenced both whole genome and targeted. i.e. to prevent a collision of the coverage stats values.  But in that case I think it would make more sense to require users  to use unique sample names for both wgs and targeted.  

Thank you for your thoughts on this.

**Comment by ewels** [comment]
Hi @WimSpee,

Thanks for letting me know. You can clean these off yourself fairly easily using the `extra_fn_clean_exts` or `extra_fn_clean_trim` configuration options. See https://multiqc.info/docs/#sample-name-cleaning

Hopefully that helps. I can also look into applying this as a default if it's affecting all / many users.

Phil

**Comment by WimSpee** [comment]
Hi @ewels  Thank you for the quick and very helpful answer.  I hadn't seen that option in the MultiQC docs/CLI. 

I'll give that option a try. 

It might make sense to have an improved default for parsing sample names from dragen files. 
The QC file name postfixes that dragen applies after the user supplied `--output-file-prefix DA_762_05`  are very systematic. 

Thank again.

**Comment by WimSpee** [comment]
Hi @ewels  Somehow I am unable to trim the `.wg` postfix from the sample names. 

I tried both using `extra_fn_clean_exts` and `extra_fn_clean_trim` in my config file `~/.multiqc_config.yaml` .
Both with and without double quotes around `.wg`

```
extra_fn_clean_exts:
  - ".wg"

extra_fn_clean_trim:
  - ".wg"
```

I also tried to add the config line on the command line. 
`multiqc  ./ -c ~/.multiqc_config.yaml  --cl-config "extra_fn_clean_trim: { '.wg'}"`

Still I have the `.wg` postfix in the sample names in the resulting report. 

Maybe I am doing something , or maybe the `extra_fn_clean_exts` and `extra_fn_clean_trim` arguments are now applied in the dragen CSV parsing code?

Thank you for your thoughts / help on this.

**Comment by WimSpee** [comment]
Thank you @ewels   for the quick fix.  The sample names are now trimmed using the auto detected config file and the resulting general stats table looks as expected. 

![image](https://user-images.githubusercontent.com/34706930/151030497-d25282bd-a1c6-49d2-a28d-66f8f732e24f.png)
