### ISSUE TITLE
bowtie1 log has been changed

### ISSUE THREAD

**Issue by nservant** [ewels/MultiQC#1615]
### Description of bug

Hi,
It seems that the bowtie1 log has been changed in the latest version (>1.3.0)

```
# reads processed: 16515809
# reads with at least one alignment: 1070136 (6.48%)
# reads that failed to align: 15445673 (93.52%)
# reads with alignments suppressed due to -m: 1531 (0.01%)
```

The number of aligned reads is defined in the module as 

```python
"reads_aligned": r"# reads with at least one reported alignment:\s+(\d+)",
"reads_aligned_percentage": r"# reads with at least one reported alignment:\s+\d+\s+\(([\d\.]+)%\)",
```
 and so is no longer recognized by MultiQC.
Thanks

**Comment by ewels** [comment]
Thanks for letting me know @nservant - should be fixed in 18c9faa7611437c5ed425a97cb924612aaefaaf9
