### ISSUE TITLE
MultiQC issue

### ISSUE THREAD

**Issue by Marica-CRUK** [ewels/MultiQC#1616]
### Description of bug

`multiqc . 2>&1` is the command that has been executed. There is also a seqyclean exception raised but the error is very cryptic.

### File that triggers the error

I am not able to find it as all files used are ok. Fastq files, fastqc output has been generated ok.

### MultiQC Error log

![image](https://user-images.githubusercontent.com/73942707/151344096-f0e9855a-8462-4bdf-abd4-0dffc4a276c6.png)

**Comment by ewels** [comment]
Hi @Marica-CRUK,

My best guess is that this is an installation problem. How are you providing MultiQC to the pipeline? I would recommend trying to reinstall it again.

If you continue to hit this error, please go to the work directory described in the Nextflow log and running MultiQC yourself manually. Then narrow down which files trigger the error and please attach them to this issue. Without some example files for me to replicate the problem myself there's not much that I can do to help I'm afraid.

I'll close this issue for now, but happy to reopen if you're able to provide a minimal example.

Phil
