### ISSUE TITLE
ZeroDivisionError in Skewer module

### ISSUE THREAD

**Issue by silvia-s** [ewels/MultiQC#1622]
### Description of bug

Hi, I just got the same error (`Oops! The 'skewer' MultiQC module broke...` [...] `ZeroDivisionError: float division by zero`) as issue #1586 using Skewer with MultiQC v1.12.dev0. While waiting for this to be fixed, is there perhaps any workaround or previous version of MultiQC without this bug that I can use?

Many thanks,
Silvia

**Comment by ewels** [comment]
It [should already be fixed](https://github.com/ewels/MultiQC/commit/1058c590c7ca78a1738e10cb7176289535bd8066) on `master` already, so if your v1.12.dev0 installation is relatively recently installed (after 15th Nov 2021) then you shouldn't be getting this error...

If you are getting this with a fresh install then please attach the output and example files, it's possible that it's a similar but different bug..

**Comment by silvia-s** [comment]
I'm afraid I can't share the input files, as it's a set of sensitive samples from a collaborator. Here's a screenshot (with light blue boxes masking the paths) of the stdout/stderr from MultiQC, hope it's helpful: 

![Screenshot_MultiQC](https://user-images.githubusercontent.com/9861211/152573696-f718c984-999a-4604-ac2f-bee6de51e292.png)

I downloaded that version today, using:
`git clone --branch zero-div-rnaseq --single-branch https://github.com/ewels/MultiQC.git`

...and my MultiQC command was the following:
`multiqc InputFolderName -n Final_QC_report.html --no-data-dir --interactive --config MyConfigFile.yaml`

Silvia

**Comment by MatthiasZepper** [comment]
Thank you for reporting this issue. Technically, that is a straightforward fix. In the skewer module, the percent calculation will fail if there are no available reads:

https://github.com/ewels/MultiQC/blob/7117ab7197a074b0154202ebd22c0239c120ddaa/multiqc/modules/skewer/skewer.py#L152-L153

I have now created a PR (#1623) that should prevent this error in the future. However, you might also want to check why so many of your samples have no reads and either relax the filtering criteria or double check the barcode reference used for de-multiplexing?

Lycka till from the NGI team!
Thias

**Comment by silvia-s** [comment]
Many thanks for fixing that and for the pull request, Matthias! I just tested MultiQC in this branch (zero-div-rnaseq) and it works fine. Do you have an approximate date for the integration of these changes into the master, as part of a new release? My pipeline uses conda to automatically download -and run- MultiQC's latest version (currently v1.11), but until that bug will be fixed in the master I'll have to run the MultiQC step manually using this dev branch, which is quite unpractical and slow.

Cheers,
Silvia

**Comment by silvia-s** [comment]
Thanks, that would be really great! I'll check again tomorrow then ;-)
