### ISSUE TITLE
Plot titles should conform with module name

### ISSUE THREAD

**Issue by schorlton** [ewels/MultiQC#1625]
### Description of bug

As always, thank you to the MultiQC team for your amazing work.
Minor bug/feature request: If I update the `name` of a module, should the name not update in the plot for that module too? We're hitting this where we use a tool's output format but not the actual tool to generate the data, then input to MultiQC. It's somewhat confusing for the report reader if the tool was not appropriate for the task but its format was used:

![image](https://user-images.githubusercontent.com/10245822/153258918-5e0f34fd-3a07-452c-b8f7-e26094bb5405.png)

Thanks again!

### File that triggers the error

Input:
[test_fastp.json.gz](https://github.com/ewels/MultiQC/files/8035080/test_fastp.json.gz)

```bash
gunzip test_fastp.json.gz
multiqc --cl_config "module_order: [{fastp: {name: Preprocessing}}]" test_fastp.json
```

**Comment by ewels** [comment]
Plot titles are currently hardcoded, rather than autogenerated by the module title.

You can customise plot titles as well, so the solution is just to set both:  https://multiqc.info/docs/#customising-plots

**Comment by schorlton** [comment]
Thanks! Missed that in the docs, really helpful. Long term would be nice not to duplicate the code by renaming each plot, but this is a great solution for now and I'm just asking for too much.
