### ISSUE TITLE
DupRadar section in MultiQC report is duplicated for each sample

### ISSUE THREAD

**Issue by drpatelh** [ewels/MultiQC#1629]
### Description of bug

When using MultiQC v1.12 the custom content we use for `dupRadar` in nf-core/rnaseq seems to be duplicated once for each sample. This doesn't occur with v1.11 and the content is correctly rendered in the same plot / portion of the General Stats table.

![image](https://user-images.githubusercontent.com/23529759/153915534-5920cd8e-e0b1-48b0-9c7d-86a2f5b3e38f.png)

### File that triggers the error

You should be able to reproduce by downloading the files below, untarring and running `multiqc .` in the folder.

[test.tar.gz](https://github.com/ewels/MultiQC/files/8062767/test.tar.gz)

### MultiQC Error log

```console
There is no explicit error as it appears to be a rendering issue in the report.
```

**Comment by idot** [comment]
[1634](https://github.com/ewels/MultiQC/pull/1634)

id is overwritten even if its in metadata, pull request fixes that
