### ISSUE TITLE
Plot labels for FastQ Scan

### ISSUE THREAD

**Issue by holtgrewe** [ewels/MultiQC#163]
Hi, I think that the plot labels for FastQ Scan should be different. Instead of Libraries, it should probably read "genomes", here is the snippet from FastQ Scan:

```
 750     $graph->set_legend( 'One hit\one genome', 'Multiple hits\one genome', 'One hit\multiple genomes', 'Multiple hits\multiple genomes' );                                                                                                 
```

**Comment by ewels** [comment]
Hi @holtgrewe,

I presume you mean FastQ Screen (not Scan)? I took the naming from the output that the program gives, I try to stay consistent with the original data where I can. However, I agree with you here - I think `genome` would be clearer than `Library`. I'll have a look at updating these labels soon.

Phil

**Comment by holtgrewe** [comment]
Hi, maybe "database" or "reference" would be even clearer (in the case of using Univec as the reference, e.g.).

**Comment by ewels** [comment]
Sorry @holtgrewe, I'd already made the change to Genomes before I saw this. Agree again - reference is better still.

**Comment by ewels** [comment]
No, I take it back - I tried references in the report but it didn't feel right somehow. I've left it as genomes. Hope this is ok!
