### ISSUE TITLE
MultiQC v1.6, Two green areas in plots

### ISSUE THREAD

**Issue by Darya-oveisi** [ewels/MultiQC#1636]
### Description of bug

I am new in RNA-seq analysis and I realized in my multiQC result I have two green parts in the Sequence Quality Histograms plot. As far as I know, the green part shows a good quality and usually for Phred scores higher than 25 it must be the case. I'm wondering what could be an explanation for this that I have two green parts in the plot? Unfortunately I'm not allowed to share my reports due to data confidentiality. But I attatched an screenshot which shows the problem.

![image](https://user-images.githubusercontent.com/64738288/154707878-c4b459c5-490c-4dd0-a453-455b8934d019.png)

**Comment by ewels** [comment]
Version 1.6 is very old (August 2018). We're on v1.12 now. If you can replicate the problem in the latest version let me know and I will reopen the issue, but I'm pretty sure that this was fixed years ago already 👍🏻
