### ISSUE TITLE
search progress bar is still running when using --quiet option 

### ISSUE THREAD

**Issue by kim-fehl** [ewels/MultiQC#1638]
### Description of bug

Neither `-q` or `--quiet` option does not hide this part of log:
 ```
   /// MultiQC 🔍 | v1.11
|           multiqc | MultiQC Version v1.12 now available!
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 191/191  
```

**Comment by ewels** [comment]
Ah good spot 👍🏻 This is a new addition and uses a separate logging system to the rest of the log. I noticed a few days ago that it also ignores `--no-ansi`. I'll try to sort both issues out..
