### ISSUE TITLE
custom_content sometimes does not find non _mqc files

### ISSUE THREAD

**Issue by cnluzon** [ewels/MultiQC#1645]
### Description of bug

I am missing a custom table on the top of my MultiQC report. MultiQC does not crash but it does not find the file path of my `custom_data`. This does not happen with an older version (v1.9), and I have seen that there have been changes in the custom_content module since, so maybe it is related. I am running MultiQC v1.12 on Ubuntu 20.04.4 LTS.

I have been investigating and produced a minimal example that reproduces this behavior. 

How to reproduce it: 
Unpack the attached .zip file in a clean directory. 
Run from there: `multiqc . -o . -c multiqc_config.yaml`

I get an output that it does not find any files. However, if I put a dummy `file_mqc.txt` in the directory:
`echo "Hello world" > file_mqc.txt` and then run the same command again on a clean directory: `multiqc . -o . -c multiqc_config.yaml`, the file `table.tsv` is found and shown in the resulting `multiqc_report.html`.

It seems to me that the presence of any `_mqc.*` file in the search path somehow triggers the search of other files with names that do not match this pattern. If my files have the `_mqc.*` extension, they are found regardless, so this would be a workaround for me. However, I am not totally sure if this is a misconfiguration on my side with an odd side effect. 

I saw in some of the MultiQC_TestData repo that some of the custom files are not necessarily called `_mqc*`, so I assumed that this is only done for MultiQC to find them without too much configuration, but any explicit other name should work? It seems to be a rare edge case, since I am guessing for large reports with custom stuff there are probably some `_mqc*` files lying around.

Thanks in advance! MultiQC is a great tool! :)

### File that triggers the error

[config_and_table.zip](https://github.com/ewels/MultiQC/files/8223283/config_and_table.zip)

### MultiQC Error log

```console
$ multiqc . -o . -c multiqc_config.yaml 

  /// MultiQC 🔍 | v1.12

|           multiqc | Only using modules: custom_content
|           multiqc | Search path : /home/carmen/work/experiments/220310_multiqc_config
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 2/2  
|           multiqc | No analysis results found. Cleaning up..
|           multiqc | MultiQC complete

$ echo "Hello world" > file_mqc.txt
$ multiqc . -o . -c multiqc_config.yaml 

  /// MultiQC 🔍 | v1.12

|           multiqc | Only using modules: custom_content
|           multiqc | Search path : /home/carmen/work/experiments/220310_multiqc_config
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 3/3  
|    custom_content | Not able to parse custom data in file_mqc.txt
|    custom_content | stats: Found 3 samples (table)
|           multiqc | Compressing plot data
|           multiqc | Report      : multiqc_report.html
|           multiqc | Data        : multiqc_data
|           multiqc | MultiQC complete
```

**Comment by ewels** [comment]
Hi @cnluzon,

Thanks for reporting this and sorry it's taken me so long to get to your issue. I'm just trying to reproduce it now but everything seems to be working fine for me:

```console
$ multiqc . -o . -c multiqc_config.yaml

  /// MultiQC 🔍 | v1.14.dev0 (abf02c7)

|           multiqc | Only using modules: custom_content
|           multiqc | Search path : /Users/ewels/Downloads/config_and_table
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 2/2
|    custom_content | stats: Found 3 samples (table)
|           multiqc | Compressing plot data
|           multiqc | Report      : multiqc_report.html
|           multiqc | Data        : multiqc_data
|           multiqc | MultiQC complete
```

If I install MultiQC v1.12 I get the same log output as you, but in v1.13 or the current v1.14dev they both work fine. So I guess that this bug was resolved at some point.

Please let me know if you're able to reproduce it still with the latest version of MultiQC.

Side note: `-c multiqc_config.yaml` is not needed as MultiQC finds this file by default ([docs](https://multiqc.info/docs/#configuring-multiqc)). Also `-o . ` is the default too. So `multiqc .` should be identical in this case.

Thanks,

Phil
