### ISSUE TITLE
MultiQC v1.12 ignores config file given via `-c`

### ISSUE THREAD

**Issue by subwaystation** [ewels/MultiQC#1649]
### Description of bug

MultiQC v1.12 ignores the config file I add via the command line.

### File that triggers the error

https://fex.belwue.de/fop/ug3PCHXy/Mambo3.tar

All files are reachable via this link for the next 10 days.

### MultiQC Error log

```console
# MultQC v1.12
Mambo3$ multiqc -s -c multiqc_config.yaml  .

  /// MultiQC 🔍 | v1.12

|           multiqc | Not cleaning sample names
|           multiqc | Search path : /mnt/vol1/data/assemblies/e_coli/test/Mambo3
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 20/20  
|              odgi | Found 2 reports
|           multiqc | Compressing plot data
|           multiqc | Report      : multiqc_report.html
|           multiqc | Data        : multiqc_data
|           multiqc | MultiQC complete

#MultiQC v1.11
Mambo3$ multiqc -s -c multiqc_config.yaml .

  /// MultiQC 🔍 | v1.11

|           multiqc | MultiQC Version v1.12 now available!
|           multiqc | Not cleaning sample names
|           multiqc | Search path : /home/heumos/Downloads/Mambo3
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 20/20  
|              odgi | Found 2 reports
|    custom_content | odgi_viz: Found 1 sample (image)
|    custom_content | odgi_viz_pos: Found 1 sample (image)
|    custom_content | odgi_viz_inv: Found 1 sample (image)
|    custom_content | odgi_viz_depth: Found 1 sample (image)
|    custom_content | odgi_draw: Found 1 sample (image)
|           multiqc | Compressing plot data
|           multiqc | Report      : multiqc_report.html
|           multiqc | Data        : multiqc_data
|           multiqc | MultiQC complete
```

**Comment by subwaystation** [comment]
Maybe related to #1645?

**Comment by ewels** [comment]
Verbose logs / log files would be useful for this kind of thing if possible.. `multiqc_data/multiqc.log` or running `multiqc -v`. It should say if it finds and parses any config files.

I'll try to find time to look into this ASAP.

**Comment by subwaystation** [comment]
https://fex.belwue.de/fop/AmgHJhzv/multiqc.log.

Here the log file. Looks good to me. I can't see any obvious problems. Thanks for making this high priority!

**Comment by subwaystation** [comment]
Any updates @ewels ?

**Comment by ewels** [comment]
Hi @subwaystation,

Just coming back to this (sorry, been bad timing - was between jobs and then had the summer + parental leave).

> All files are reachable via this link for the next 10 days.

Only just noticed this, that was always ambitious 😅 I don't suppose you still have the files kicking around? I'm not really sure what was wrong / can't spot any problems with loading config files currently.

Phil

**Comment by subwaystation** [comment]
Hi @ewels!

I don't know why, but the problem only arose with v1.12. I just used v1.13 and got the desired result :)

**Comment by ewels** [comment]
Hooray! 🎉 

Hah, makes me a little nervous but ok 😅 Glad it was resolved!

**Comment by subwaystation** [comment]
I am as confused as you!
