### ISSUE TITLE
produce report from data files

### ISSUE THREAD

**Issue by avilella** [ewels/MultiQC#165]
This is a feature request against the master branch:

This may have been solved already elsewhere, I remember seen coments alluding to it here.

Would it be possible to have a `--report-from-data-dir` option where the input is the collection of `multiqc_module.txt` files for a collection of `multiqc --no-data-dir` runs, and the output is the html page and the aggregation of all those results.

This is for cases where the pipeline would run independently each step on each sample, then it's more convenient to run `multiqc --module module_name sample1/` and aggregate at the end with all the samples in the project.

**Comment by ewels** [comment]
I'm afraid that this isn't at all easy - firstly not all modules save all of their parsed data: much of the plotted data isn't saved in the data directory (this may change in the future). Secondly, the data structure will be different, so it would need to have a second set of data parsers to write the report.

Instead, as MultiQC is fast to run, I'd recommend just re-running MultiQC after each step of the pipeline. Use `-f` to overwrite the previous report. This is what I do :)

**Comment by avilella** [comment]
That was the alternative.

For cloud environments that need to present the data to all samples within
a project to the running instance, it takes time (and money) to make all
those files available, but I presume with adequate file size limits, it
shouldn't be too much.

A.

**Comment by ewels** [comment]
Yup - you can also look into the [search patterns config file](https://github.com/ewels/MultiQC/blob/master/multiqc/utils/search_patterns.yaml) to see exactly which log files MultiQC is using. Then you can show only these files, which should have a very minimal filesize.
