### ISSUE TITLE
memory requirements

### ISSUE THREAD

**Issue by sunta3iouxos** [ewels/MultiQC#1650]
Is there a way to restrict the memory usage?
I have 280 fastq files and the process is killed without any message. I suspect is due to lack of memory, that reached the highest available.
Thank you

**Comment by ewels** [comment]
Not that I'm aware of sorry. MultiQC typically doesn't use a lot of memory though, and 280 FastQC reports is not that much, so I'd be fairly surprised if it's really hogging all that much.
