### ISSUE TITLE
Division by Zero in Sambamba Markdup

### ISSUE THREAD

**Issue by epruesse** [ewels/MultiQC#1654]
### Description of bug

In file `sambamba/sambamba.py` line 93:

https://github.com/ewels/MultiQC/blob/45ce9ae0160c38e250e3e0e4a9335adc5af26b6b/multiqc/modules/sambamba/markdup.py#L93

A simple `try/except` should do it. May want to check every place in every module divisions occur. If you have a division, you'll eventually have a division by zero...

### File that triggers the error

Simple all empty (previously filtered to nothing) file:

```
finding positions of the duplicate reads in the file...
  sorted 0 end pairs
     and 0 single ends (among them 0 unmatched pairs)
  collecting indices of duplicate reads...   done in 0 ms
  found 0 duplicates
collected list of positions in 0 min 0 sec
removing duplicates...
collected list of positions in 0 min 0 sec
```

**Comment by aidaanva** [comment]
Hi,
I also had the same error running nf-core/eager and affecting MALT, in this case there was one sample with 0 reads assigned. 

The error looks like this: 

`  /// MultiQC 🔍 | v1.11

|           multiqc | MultiQC Version v1.12 now available!
|           multiqc | Only using modules: adapterRemoval, bowtie2, custom_content, damageprofiler, dedup, fastp, fastqc, gatk, kraken, malt, mtnucratio, multivcfanalyzer, picard, preseq, qualimap, samtools, sexdeterrmine, hops, bcftools
|           multiqc | Search path : /mnt/archgen/MICROSCOPE/pathogen_screening/2021-03-09-keltenfuersten_BW/fullbacetvir2017/work/5c/a5b3dca9f4b85354e0b9529b211141/multiqc_config.yaml
|           multiqc | Search path : /mnt/archgen/MICROSCOPE/pathogen_screening/2021-03-09-keltenfuersten_BW/fullbacetvir2017/work/5c/a5b3dca9f4b85354e0b9529b211141
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1006/1006  
╭────────────────── Oops! The 'malt' MultiQC module broke... ──────────────────╮
│ Please copy this log and report it at                                        │
│ https://github.com/ewels/MultiQC/issues                                      │
│ Please attach a file that triggers the error. The last file found was:       │
│ ./malt/malt.log                                                              │
│                                                                              │
│ Traceback (most recent call last):                                           │
│   File "/opt/conda/envs/nf-core-eager-2.4.2/lib/python3.9/site-packages/mult │
│     output = mod()                                                           │
│   File "/opt/conda/envs/nf-core-eager-2.4.2/lib/python3.9/site-packages/mult │
│     self.parse_logs(f)                                                       │
│   File "/opt/conda/envs/nf-core-eager-2.4.2/lib/python3.9/site-packages/mult │
│     float(self.malt_data[s_name]["Assig. Taxonomy"])                         │
│ ZeroDivisionError: float division by zero                                    │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯
|              hops | Found 58 samples
|          samtools | Found 62 flagstat reports
|          samtools | Found 62 flagstat reports
|    custom_content | software_versions: Found 1 sample (html)
|    custom_content | nf-core-eager-summary: Found 1 sample (html)
|           multiqc | Compressing plot data
|           multiqc | Report      : multiqc_report.html
|           multiqc | Data        : multiqc_data
|           multiqc | Plots       : multiqc_plots
|           multiqc | MultiQC complete`

@ewels would you advise to open a separate issue? 

I think @epruesse is right that this should apply to all divisions.

**Comment by ewels** [comment]
@aidaanva please make a new issue for that as it's a different module.

I agree that these errors are very common, but going through all code for all modules is a mammoth task. It's not a trivial find + replace as each case needs bespoke handling. For example should it use `None` or `0` in its place? Also when fixed they very often lead to downstream errors where later parts of the code also expect totals to be non-zero. This is why example data is so important for testing when fixing these bugs.

**Comment by aidaanva** [comment]
@ewels sorry it took so long to reply. It makes sense. I have now create a new issue: #1683

**Comment by gartician** [comment]
I can elect to follow up in this since I made the Sambamba markdup module. Can I assign myself to this issue? And when it's fixed, should I initiate a new PR for this fix?

**Comment by ewels** [comment]
That would be brilliant @gartician - yes please! Thanks!
