### ISSUE TITLE
NanoStat Error

### ISSUE THREAD

**Issue by EngyNasr** [ewels/MultiQC#1663]
### Description of bug

Dear All,

Kindly I need your help to run MultiQC with a NanoStat input report. I am using the MultiQC conda package and I got the error shown the Error Log section. 

Thank a lot,
Engy

### File that triggers the error

[statreport.zip](https://github.com/ewels/MultiQC/files/8441815/statreport.zip)

### MultiQC Error log

```console
│ Please copy this log and report it at https://github.com/ewels/MultiQC/issues           │
│ Please attach a file that triggers the error. The last file found was:                  │
│ /home/nasr/Downloads/statreport/statreport                                              │
│                                                                                         │
│ Traceback (most recent call last):                                                      │
│   File "/home/nasr/miniconda3/envs/multiqc/lib/python3.10/site-packages/multiqc/multiqc │
│     output = mod()                                                                      │
│   File "/home/nasr/miniconda3/envs/multiqc/lib/python3.10/site-packages/multiqc/modules │
│     self.parse_nanostat_log(f)                                                          │
│   File "/home/nasr/miniconda3/envs/multiqc/lib/python3.10/site-packages/multiqc/modules │
│     line = jinja2.escape(line)                                                          │
│ AttributeError: module 'jinja2' has no attribute 'escape'
```

**Comment by ewels** [comment]
See https://github.com/ewels/MultiQC/pull/1655 - already fixed in https://github.com/ewels/MultiQC/pull/1659

Please run the development version for now, I will be releasing a new version of MultiQC with this fix included soon.

Alternatively, downgrade the `jinja2` library to < 3.1 (3.0 should be fine). That should also solve the issue.
