### ISSUE TITLE
multiple logos

### ISSUE THREAD

**Issue by sunta3iouxos** [ewels/MultiQC#1675]
### Description of feature

Is it possible to inject more than one logos with the "custom_logo" filed.
Will it be possible to implement such.

**Comment by ewels** [comment]
Hi @sunta3iouxos,

It's not currently possible and as far as I remember you're the first person to request it in over 6 years, so I can't say that it's a very high priority (though it wouldn't be too difficult to do technically).

What's your use case? How come you can't stitch the logos into one image?

Phil

**Comment by sunta3iouxos** [comment]
No worries, it can be done. I thought it could be an option that I missed. It's just that our core facility has a couple of different affiliations.
Thank you

**Comment by ewels** [comment]
Also, remember that you can always make your own template - this is the old way of doing this. You could make a copy of `header.html` and add in whatever images you want and then use it as a child theme that inherits all other files from `default`.

Docs on this here: https://multiqc.info/docs/#writing-new-templates
Code base doing basically that here: https://github.com/NationalGenomicsInfrastructure/MultiQC_NGI/tree/master/multiqc_ngi/templates/ngi

Phil
