### ISSUE TITLE
If the report name have 2+ consecutive dashes, they get erased in the filename

### ISSUE THREAD

**Issue by valleema** [ewels/MultiQC#1685]
### Description of bug

If the report name has more than 1 consecutive dash in the name, they get deleted back to 1.

```
multiqc -i Test---20220512 -o multiqc . --force
```
Resulting filename is `multiqc/Test-20220512_multiqc_report.html` instead of `multiqc/Test---20220512_multiqc_report.html`

### MultiQC Error log

```console
/// MultiQC 🔍 | v1.12

|           multiqc | Report title: Test---20220512
|           multiqc | Search path : /home/valleema/
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 69/69  
|    custom_content | Couverture: Found 8 General Statistics columns
|      fastq_screen | Found 8 reports
|            fastqc | Found 8 reports
|          samtools | Found 8 stats reports
|            picard | Found 8 WgsMetrics reports
|           multiqc | Compressing plot data
|           multiqc | Deleting    : multiqc/Test-20220512_multiqc_report.html   (-f was specified)
|           multiqc | Deleting    : multiqc/Test-20220512_multiqc_report_data   (-f was specified)
|           multiqc | Report      : multiqc/Test-20220512_multiqc_report.html
|           multiqc | Data        : multiqc/Test-20220512_multiqc_report_data
|           multiqc | MultiQC complete
```

**Comment by valleema** [comment]
It is in case of analyses launched with those report titles `Test-20220512`, `Test--20220512`, or `Test---20220512` are erasing themselves with the same filename. 

I made a dirty workaround with `mv` and the wanted report name in the filename...

**Comment by ewels** [comment]
That's an amazing filename nomenclature system 😅 

If it's just the filename that's the problem, then I would recommend setting the filename in MultiQC directly as well as the title with `--filename` / `-n`. With `-i` you're setting the report title and that has different behaviour. I just tested this and it works fine for me:

```console
$ multiqc -f v0.11.2/ -i "Test----test" -n "Test----test"

  /// MultiQC 🔍 | v1.13.dev0 (b767552)

|           multiqc | Report title: Test----test
|           multiqc | Search path : /Users/phil/GitHub/MultiQC/TestData/data/modules/fastqc/v0.11.2
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1
|            fastqc | Found 1 reports
|           multiqc | Compressing plot data
|           multiqc | Report      : Test----test.html
|           multiqc | Data        : Test----test_data
|           multiqc | MultiQC complete
```

There's also `--outdir` to put the reports into a custom directory name.

I'll close the issue now, as the behaviour is expected and I think that `-n` is hopefully a simple enough solution 👍🏻 

Phil

**Comment by valleema** [comment]
Thank you for the suggestion, I will be using it. 
(Sorry for the nomenclature, but the depth of imagination for analysis names from my wetlab colleagues is limitless 😵‍)

**Comment by ewels** [comment]
At least it's not spaces or slashes.. Emoji maybe? 😆

**Comment by valleema** [comment]
Yeah I am looking forward for my next `💉 _R1.fastq` `💉 _R2.fastq` to process 🤣
