### ISSUE TITLE
is MultiQC support nextSeq or miniSeq run result 

### ISSUE THREAD

**Issue by htobenothing** [ewels/MultiQC#1690]
### Description of feature

Hi ,

I am exploring to use MultiQC for NextSeq and MiniSeq run folder, is that supported ?
Any documentation to guide me to run on those data ? 
Thank you very much

**Comment by ewels** [comment]
Hi @htobenothing,

Yes it is, via a plugin by @matthdsm - you can find it here: https://github.com/MultiQC/MultiQC_SAV

Phil
