### ISSUE TITLE
Missing Undetermined section in Sample Statistics (BCL Convert module)

### ISSUE THREAD

**Issue by plim2021** [ewels/MultiQC#1695]
### Description of feature

MultiQC report generated with the bclconvert module doesn't include the Undetermined section.
I am attaching screenshots : one report generated with the bcl convert module and one report generated with the bcl2fastq module.

**MultiQC report (bclconvert)**
![Capture du 2022-05-31 15-48-01](https://user-images.githubusercontent.com/92247364/171189327-12360c47-1151-4862-b34c-682d07661102.png)

**MultiQC report (bcl2fastq)**
![Capture du 2022-05-31 15-48-27](https://user-images.githubusercontent.com/92247364/171189341-0095ff62-26b3-46ce-9a17-037b1b57ce18.png)

**Comment by ewels** [comment]
I think that support for this was added in https://github.com/ewels/MultiQC/pull/1752 so I'll close this issue now.

Thanks for reporting it, please let me know if it should be reopened.
