### ISSUE TITLE
`bclconvert`: incorrect stats for single-read data

### ISSUE THREAD

**Issue by ajeffs** [ewels/MultiQC#1697]
### Description of bug

bcl-convert module in v1.13.dev0 reports incorrect Lane and Sample Statistics for single-read data:
1. "Yield (Mb)" is shown as twice the actual yield.
2. The actual "Yield (Mb)" is used as "Bases (Mb) >=Q30 (PF)".
3. "% Bases >= Q30 (PF)" is therefore half the correct value.

It appears the bcl-convert module is incorrectly calculating the above instead of pulling the correct data directly from the bcl-convert report file (Quality_Metrics.csv etc.)?

The bcl-convert module shows correct values for paired-end data.

Example for Lane Stats below (1x51 bp; Sample Stats behaves the same): 

**bcl-convert:**
![bcl-convert_multiqc_sr](https://user-images.githubusercontent.com/4916755/171298336-c7df4f2f-dc24-43c7-a0e9-7e95c1740aa3.png)

**bcl2fastq (correct values):**
![bcl2fastq_multiqc_sr](https://user-images.githubusercontent.com/4916755/171298395-d9bbaadf-8a1e-42bc-b926-cd997714d6a6.png)

### MultiQC Error log

```console
$ multiqc . ../../Stats -e snippy -i "OG6761 QC report" -n "OG6761-multiqc-report.html"
 /// MultiQC 🔍 | v1.13.dev0

|           multiqc | Report title: OG6761 QC report
|           multiqc | Excluding modules 'snippy'
|           multiqc | Search path : /mnt/HCS/aozan/fastq/220321_VH00684_22_AAAM322HV/bcl2fastq/OG6761/qc
|           multiqc | Search path : /mnt/HCS/aozan/fastq/220321_VH00684_22_AAAM322HV/bcl2fastq/Stats
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 152/152  
|            fastqc | Found 72 reports
|           multiqc | Compressing plot data
|           multiqc | Report      : OG6761-multiqc-report.html
|           multiqc | Data        : OG6761-multiqc-report_data
|           multiqc | MultiQC complete
```

**Comment by ewels** [comment]
Huh, that sounds odd and potentially serious. Is it just v1.13dev, not v1.12? There's been a few changes in the past months on this module - https://github.com/ewels/MultiQC/pull/1595 and (issue: https://github.com/ewels/MultiQC/issues/1563)

@andrei-seleznev / @yanick - any ideas what could be going on here?

**Comment by ajeffs** [comment]
Apologies, haven't used v1.12, only v1.13.

I note the "Yield Mb" reported by bcl-convert module is the clusters multiplied by two times​ the read length, instead of the actual read length, e.g., in the provided example for Lane 1, 585*(2*51)=59670, when it should be 585*51=29835. The %>=Q30 is then half what it should be because the reported yield is twice what it should be.
________________________________
