### ISSUE TITLE
Enable multiqc to pull nextclade quality results from nextclade csv output file

### ISSUE THREAD

**Issue by mabvakureb** [ewels/MultiQC#1706]
### Description of feature

Hi, may you enable multiqc to pull nextclade https://clades.nextstrain.org/ quality results from nextclade csv output file. Nextclade command line produces an output file which can be csv or tsv, and it has some good quality metrics that I would like to import into multiqc report.

**Comment by ewels** [comment]
Thanks for the suggestion @mabvakureb ! It would be great if you could close this issue and open a new one using the template for requesting modules if possible: https://github.com/ewels/MultiQC/issues/new?assignees=&labels=module%3A+new&template=module-request.yml

That includes fields for all of the information needed to write a new MultiQC module (most important is some example data files).

Phil
