### ISSUE TITLE
About pre-alignment QC

### ISSUE THREAD

**Issue by tom21100227** [ewels/MultiQC#1715]
### Description of feature

Hi, 

I'm not sure if this is the right place but I have gone through the documentation and I didn't find a solution to this. Currently, on our pipeline, we generate FastQC reports separately for forward (R1) and reverse (R2). However, in multiQC the software does not recognize that R1 and R2 belongs to the same sample and we ended up with something like this. The rest of the software works just fine but this is a bit unpleasant. I wonder if this could be a feature in the future or if it can be done with current parameter. 
![Screen Shot 2022-06-24 at 19 09 53](https://user-images.githubusercontent.com/103209542/175721532-5891e278-6fbf-40aa-bce9-bac7fb0a07e1.png)

Thanks in advance for your help!

**Comment by ewels** [comment]
Yeah this is a well known issue. There's no particularly satisfying solution I'm afraid, apart from ditching one of the sets of FastQC results and trimming the _R1 off the sample names.

There is an archaic (5 year old) PR I have open where I started working on a better solution. Maybe I'll finish it one day 😅 

Phil
