### ISSUE TITLE
Custom_content MultiQC module broke

### ISSUE THREAD

**Issue by matthewthefool** [ewels/MultiQC#1720]
### Description of bug

I was trying on test of pipe and this error have happened.

### File that triggers the error

Pipe [here](https://github.com/snakemake-workflows/dna-seq-gatk-variant-calling), input is .test file.
Here`s log [multiqc.log](https://github.com/ewels/MultiQC/files/9046921/multiqc.log)

**Comment by ewels** [comment]
This is an old issue that got buried, sorry. And the version of MultiQC was _very_ old (v1.10).

Closing as I think it's stale, please reopen if it still applies :)
