### ISSUE TITLE
DRAGEN's FastQC metrics

### ISSUE THREAD

**Issue by jamigo** [ewels/MultiQC#1737]
### Description of feature

DRAGEN generates multiple metrics files, some of them already supported by MultiQC. Since one of those metrics files contains FastQC information I was wondering if MultiQC would be able to deal with those *.fastqc_metrics.csv files, instead of processing the FASTQ files with FastQC if those metrics are desired.

I first thought about building a conversor from DRAGEN's FastQC format to FastQC's, but there are a few differences:
https://support-docs.illumina.com/SW/DRAGEN_v40/Content/SW/DRAGEN/FASTQC_Intro_fDG.htm
_DRAGEN's FastQC module is a complete reimplementation of the original FastQC tool developed by the Babraham Institute (BI-FastQC). The reimplementation of FastQC in DRAGEN has been modified to take advantage of the hardware-acceleration provided by DRAGEN's Field-Programmable Gate Array (FPGA) for a significant speed improvement. There are some differences in how the values are calculated and the resulting metrics will not be identical between the two tools._

**Comment by marchoeppner** [comment]
Second this request. Illumina seems to have their own custom module for this as they provide Dragen fastQC metrics in their MultiQC reports on basespace. 

Example file for the fastqc metrics attached. 
[I33974-L3.fastqc_metrics.csv](https://github.com/ewels/MultiQC/files/9564840/I33974-L3.fastqc_metrics.csv)

**Comment by ewels** [comment]
Yeah there's an epic 2-year old pull request sat, which I guess is what's being used in a fork: https://github.com/ewels/MultiQC/pull/1232

Need to get on and merge it, but it's so huge that I've never been able to find the time to review the code (it would likely take me a couple of weeks doing only this). As it's essentially already in production I am planning to merge it blind though, reviewing only the core MultiQC code edits. I've been slowly working towards this for the past year, have had a hiatus during a job change and am now starting to set my sights on the backlog. So maybe, just maybe, it might get merged one day in the not too distant future 😅

**Comment by alexiswl** [comment]
> Yeah there's an epic 2-year old pull request sat, which I guess is what's being used in a fork: #1232
> 
> Need to get on and merge it, but it's so huge that I've never been able to find the time to review the code (it would likely take me a couple of weeks doing only this). As it's essentially already in production I am planning to merge it blind though, reviewing only the core MultiQC code edits. I've been slowly working towards this for the past year, have had a hiatus during a job change and am now starting to set my sights on the backlog. So maybe, just maybe, it might get merged one day in the not too distant future 😅

Can we consider the DockerFile update PR (https://github.com/ewels/MultiQC/pull/1541) with the Dragen FastqQC PR (https://github.com/ewels/MultiQC/pull/1232). In order to build containers with the Dragen FastQC branch, I've needed to merge in the DockerFile updates branch in order for multiqc to be compiled.
