### ISSUE TITLE
error parsing RSeQC output

### ISSUE THREAD

**Issue by agata-sm** [ewels/MultiQC#174]
Hi, 
I just got the following error when attempting to include RSeQC output in the report. Thanks!
Agata

```
============================================================
Module rseqc raised an exception: Traceback (most recent call last):
  File "/Users/##/miniconda3/bin/multiqc", line 252, in multiqc
    report.modules_output.append(mod())
  File "/Users/##/miniconda3/lib/python3.5/site-packages/multiqc/modules/rseqc/rseqc.py", line 48, in __init__
    n['read_distribution'] = read_distribution.parse_reports(self)
  File "/Users/##/miniconda3/lib/python3.5/site-packages/multiqc/modules/rseqc/read_distribution.py", line 57, in parse_reports
    for k in dkeys:
RuntimeError: dictionary changed size during iteration
============================================================

```

Thanks!

**Comment by ewels** [comment]
Hi @agata-sm,

Thanks for the bug report. It's weird - I had the same error but I thought I'd fixed it. Are you definitely running the latest commit? Any chance you could send the log file in question so that I can try to replicate the error at my end?

Cheers,

Phil

**Comment by ewels** [comment]
Hi @agata-sm - I just refactored the code in question to make it a little more robust. Hopefully this will fix your problem, let me know if you still get an error.

Phil

**Comment by agata-sm** [comment]
It worked with the newest code update, thanks a lot!
Agata
