### ISSUE TITLE
example of data structure for x_y plot with button to switch among data set

### ISSUE THREAD

**Issue by lpantano** [ewels/MultiQC#175]
Hi!

I am preparing the PR for some bcbio metrics.

I want to create a section that has a x_y plot. It will contain more than one type, like one is counts/percentages, but more. I understood from the docs that the structure, for instance for 2 samples, and 2 data sets, should be:

```

data = [{
    'sample 1': {
        '<x val 1>': '<y val 1>',
        '<x val 2>': '<y val 2>',
    },
    'sample 2': {
        '<x val 1>': '<y val 1>',
        '<x val 2>': '<y val 2>',
    }
},
{
    'sample 1': {
        '<x val 1>': '<y val 1>',
        '<x val 2>': '<y val 2>',
    },
    'sample 2': {
        '<x val 1>': '<y val 1>',
        '<x val 2>': '<y val 2>',
    }
}
]

html_content = self.plot_xy_data(data)
```
Is that right? or I messed up with the order? Doing that I cannot get all samples in the sample plot, is like doing one plot for each sample for each datatype. I want to check this first, before debug further.

thanks!

**Comment by lpantano** [comment]
actually, done. That is the format. I was messing with the sample names. Now it is clear to me, and easy to get.sorry for the issue.

**Comment by ewels** [comment]
Glad you got it working :)
