### ISSUE TITLE
Sample metadata in tables

### ISSUE THREAD

**Issue by berguner** [ewels/MultiQC#1756]
### Description of feature

Hi,
It is usually helpful to have additional sample metadata (i.e. batch name, cell type, cell count, PCR cycles) in the MultiQC tables for interpreting the results. Would it be possible to add a feature which parses an input metadata file (CSV/TSV) and adds the columns to the MultiQC tables, in particular the general stats table? Rows can be matched based on a "Sample Name" column.

**Comment by ewels** [comment]
Yes, this is already possible. Please see [Custom Content](https://multiqc.info/docs/#custom-content).

For example, something like this should work (untested):

`my_custom_metadata_mqc.tsv`

```tsv
# plot_type: 'generalstats'
Sample Name	Batch	Cell Type	Cell Count	PCR Cycles
Sample_1	Batch_1	GM12878	283456	29
Sample_2	Batch_1	GM12878	276112	29
Sample_3	Batch_2	GM12878	298193	29
Sample_4	Batch_2	GM12878	218172	30
```

**Comment by berguner** [comment]
Thanks Phil, I will give that a try.

**Comment by ewels** [comment]
Mostly out of curiosity, I just tried my own example. It does work, though I found that if you run it with MultiQC and nothing else, MultiQC would refuse to save a report. So fixed than minor bug and added the above file as an example to the MultiQC_TestData repository.

Let me know how you get on :)
