### ISSUE TITLE
Grouped outputs

### ISSUE THREAD

**Issue by mstone-modulus** [ewels/MultiQC#1761]
### Description of feature

Hi,

Is it possible to have multiple groups of outputs for a single program? For example, I work with paired-end libraries where R1 and R2 are of different lengths. I'd like to view the FastQC results for R1 and R2 separately, so it's easier to compare base quality/composition.

I can generate separate multiqc reports, but it'd be convenient to have both sets of results in one location (and to be able to include upstream bcl2fastq and downstream trimming logs in the same report).

Thanks!

**Comment by ewels** [comment]
Yes you can - you do this by running a module (in this case, FastQC) multiple times with different file / sample name filters. See the docs here: https://multiqc.info/docs/#running-modules-multiple-times

Hope that helps,

Phil

**Comment by mstone-modulus** [comment]
Worked like a charm, thanks!

**Comment by ewels** [comment]
Great! 😊
