### ISSUE TITLE
Kraken module does not preserve taxonomy

### ISSUE THREAD

**Issue by schorlton** [ewels/MultiQC#1766]
### Description of bug

If there are no species in a kraken report, MultiQC pushes the genus-level classifications down to the species-level. I assume it also does this for the other ranks (eg. if there are no species or genuses detected) but haven't tested.

Here's an example where we did not classify beyond Escherichia. Note that the plot selected is the species-level plot, when it should be the genus-level plot. Proper behaviour should probably be to classify all reads as "Other" to be consistent with the other behaviour of this module?
![image](https://user-images.githubusercontent.com/10245822/190593296-25074a65-c0c4-4b16-aba5-d4b45e862031.png)

Running MultiQC 1.13 from bioconda with:
```bash
gunzip genus_only.kreport.gz
multiqc genus_only.kreport
```

### File that triggers the error

[genus_only.kreport.gz](https://github.com/ewels/MultiQC/files/9582149/genus_only.kreport.gz)

**Comment by vladsavelyev** [comment]
Thanks a lot for reporting the issue! I implemented a fix for this in https://github.com/ewels/MultiQC/pull/1979
