### ISSUE TITLE
Incorrect sequencing yield calculated by bcl convert module when using asymmetric read lengths

### ISSUE THREAD

**Issue by BigTA78** [ewels/MultiQC#1774]
### Description of bug

When invoking the bclConvert module on a sequencing run where read 1 and read 2 read-lengths differ (e.g. a 10X Genomics scRNA run, where `R1=28` cycles and `R=90`), yields are incorrectly calculated.

The assumption is `2 * R1 * # clusters` which underestimates yield. This leads to over-estimate of % bases `>Q30`, with values over `100%` (see attached report bundled with bclConvert output folder). Actual calculation should be `# cluters * (R1+R2)`

### File that triggers the error

[bclConvert_example.zip](https://github.com/ewels/MultiQC/files/9707702/bclConvert_example.zip)

### MultiQC Error log

```console
$ multiqc -m bclconvert home/user/bclConvert_example/ -n /home/user/bclConvert_example/multiQC.html

  /// MultiQC 🔍 | v1.14.dev0

|           multiqc | Only using modules: bclconvert
|           multiqc | Search path : /home/user/bclConvert_example
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 13/13
|        bclconvert | 1 lanes and 11 samples found
|           multiqc | Compressing plot data
|           multiqc | Report      : /home/user/bclConvert_example/multiQC.html
|           multiqc | Data        : /home/user/bclConvert_example/multiQC_data
|           multiqc | MultiQC complete
```

**Comment by andrei-seleznev** [comment]
Should be straightforward  enough to grab R1 and R2 length from RunInfo.xml and calculate appropriately - I can make this change next week and PR!

**Comment by ewels** [comment]
Thanks @andrei-seleznev !
