### ISSUE TITLE
Extend DRAGEN support for region-based coverage metrics

### ISSUE THREAD

**Issue by xiamaz** [ewels/MultiQC#1781]
### Description of feature

Currently running the DRAGEN pipeline with more features the following logs are not included in a QC report:

- region-based coverage metrics

These are defined using a BED file and follow a similar structure to the wgs_coverage_metrics.

**Comment by ckandoth** [comment]
MultiQC 1.13 should find and parse `*.target_bed_*.csv` files but only if you manually delete your `*.wgs_*.csv` files that Dragen always generates and there is no way to turn it off. There is a bug in MultiQC 1.14 that broke this. #1844

**Comment by xiamaz** [comment]
Thanks for the info. We would like to have both the wgs and additional region coverage metrics at the same time.

We already did some work on this issue on our own end and will open a PR soon.

**Comment by alexiswl** [comment]
@xiamaz I have a PR at https://github.com/ewels/MultiQC/pull/1854 that may resolve your issue

**Comment by ewels** [comment]
Please let me know if the merged #1854 PR does not fix the problem and we can reopen.

**Comment by your-highness** [comment]
I am answering on behalf of my colleague @xiamaz 👍🏻 

Unfortunately, #1854 is a good start but as far as I can see it does not deal with multiple qc-coverage-region files and our DRAGEN 3.10 does not create any `*.target_bed_*.csv` files. PR #1880 is a rework and takes multiple qc coverage region CSVs (DRAGEN supports up to 3) - I encourage merging PR #1880, @ewels

**Comment by ewels** [comment]
@your-highness - if you have more example reports to use as test data, that would be welcome. The DRAGEN module is huge and is relatively under represented in the [test data](https://github.com/ewels/MultiQC_TestData).

**Comment by your-highness** [comment]
Dear @ewels,

Thanks for the swift reply!

Test data was given as `test_coverage_data.zip` by @Just-Roma in PR ewels/MultiQC#1880 . I generated a PR in ewels/MultiQC_TestData#248 which adds those.

Best

**Comment by alexiswl** [comment]
> Unfortunately, https://github.com/ewels/MultiQC/pull/1854 is a good start but as far as I can see it does not deal with multiple qc-coverage-region files

@your-highness, did you have a look at the example output data I shared from #1854, two qc regions are visible in the report?

**Comment by alexiswl** [comment]
> and our DRAGEN 3.10 does not create any *.target_bed_*.csv files

What is the regex for dragen 3.10 for target bed files? I think target bed files are created only when the parameter --vc-target-bed is specified

**Comment by your-highness** [comment]
> @your-highness, did you have a look at the example output data I shared from #1854, two qc regions are visible in the report?

You are right. However, currently the module does not deal with `*.qc-coverage-region-(1|2|3)_coverage_metrics.csv` as far as I can see this.

> What is the regex for dragen 3.10 for target bed files? I think target bed files are created only when the parameter --vc-target-bed is specified

See above. I think it would be best to include both `*.target_bed_*.csv` and `*.qc-coverage-region-(1|2|3)_coverage_metrics.csv`. Maybe @Just-Roma can include both?
