### ISSUE TITLE
Set up a maintainers team

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#1787]

**Comment by multimeric** [comment]
Any particular recruitment method in mind? Asking the largest contributors?

**Comment by ewels** [comment]
Basically, yeah. Also with a pinch of how long they've been contributing for and also my experience of working with them in pull-requests (how much they seem to understand my idiosyncracies and pedantic nature on aspects of MultiQC code).

**Comment by ewels** [comment]
Since @seqeralabs is increasing support for MultiQC, having a community-maintainers team open to anyone is becoming less of a priority for the project. We are growing a team of full-time devs for MultiQC and hopefully now have resources to continue to respond to community contributions as before.

I'm not writing this off as a possibility for the future, but closing as for now I have no short-term plans to proceed with this idea.
