### ISSUE TITLE
heatmap support

### ISSUE THREAD

**Issue by lpantano** [ewels/MultiQC#179]
Hi!

We use one tool in bcbio that generate information that suits a heatmap plot. It's a distance matrix between samples.

Do you think ti could be easy added this kind of plots? If you point me to the places, I can try to do it, just want to make sure is something we can have in the future.

thanks!!!

**Comment by ewels** [comment]
Hi @lpantano,

I've been meaning to look into this too, we are building our own RNA pipeline and want exactly the same thing 😄 

Definitely possible - the FastQC module uses a custom-coded heatmap for the per-base sequence content plot (no HighCharts, pure custom JS). It would be better to add this plot type as a core plot though, so that we can have a static MatPlotLib alternative. But my point is that any module can add any custom plot type in principal - see the [docs](http://multiqc.info/docs/#adding-custom-css--javascript) about including custom CSS and JS files.

HighCharts has a [demo](http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/heatmap/) of a simple heatmap, though it requires an extra dependency which is a bit of a shame. We could probably add logic to only include this if required though.

Do you have a standard tool to generate this data, or is it from a custom script? Ours is custom so I was intending to add this to our [MultiQC plugin](https://github.com/ewels/MultiQC_NGI).

Phil

**Comment by avilella** [comment]
+1 for me, it's an important feature.

**Comment by ewels** [comment]
I can look into writing a base class heatmap function, but it's going to take me a while to get to it. I'm halfway through [another new plot type](https://github.com/ewels/MultiQC/issues/167) currently 😄 

I agree that it'd be useful for some cases though.

**Comment by lpantano** [comment]
Hi @ewels,

in this case is for qsignature, and the tool itself generate some output that I can parse here and create the plot. For now, I can even create HTML code to show only the warnings, like, these samples are too much alike... but for sure It would be great to have multiqc supporting this type of plots. As well, I can try to play with custom CSS and JS until there is something official :) 

thanks a lot!

**Comment by ewels** [comment]
Sounds good! For reference, I will probably base the new plot on that HighCharts demo mentioned above. So let's say that I'll take the data in in the following format:

```python
# xcats and ycats - lists of labels for both axes. These can be the same.
# Start bottom left and move up / to the right
xcats = ['Sample 1', 'Sample 2', ... ]
ycats = xcats

# Data - list of lists. Each sublist has three items - y position, x position, value
# Start bottom left and move up each column.
data = [
  [0,0,23],
  [0,1,43],
  ...
]

plot_heatmap(data, xcats, ycats, pconfig)
```

Does that sound sensible? It'll probably take me a couple of weeks to get to it. In the mean time you could make a heatmap table pretty quickly with the same data structures :)

**Comment by ewels** [comment]
ps. You probably figured this out already, but here's the markup for the FastQC pass / warn / fail bars:

![image](https://cloud.githubusercontent.com/assets/465550/14617380/4670736c-05ae-11e6-9959-6a4b5bcb95ec.png)

```html
<div class="progress fastqc_passfail_progress">
  <div class="progress-bar progress-bar-success" style="width: 50%" title="3 passed" data-toggle="tooltip">3</div>
  <div class="progress-bar progress-bar-warning" style="width: 33.3%" title="6 with warnings" data-toggle="tooltip">2</div>
  <div class="progress-bar progress-bar-danger" style="width: 16.6%" title="6 failed" data-toggle="tooltip">1</div>
</div>
```
This is using the [Bootstrap stacked progress bar](http://getbootstrap.com/components/#progress-stacked) classes.

**Comment by ewels** [comment]
pps. Are you going to write a module for the AdamaJava tool suite with submodules for each tool (eg. qsignature)? That would be cool! See the new [RSeQC](https://github.com/ewels/MultiQC/blob/master/multiqc/modules/rseqc/rseqc.py) module / submodules for a suggestion on how to bunch together what are essentially different modules into one.

**Comment by lpantano** [comment]
oh! nice!, well if you only need two weeks I can wait for you :) amazing. I am working in the files that bcbio generates to add it to multiqc.

For qsignature, for now only that, but I can add it in this form, so can be expanded easily.

Related to this, I have a question. You mentioned the plugin to add the report of "custom" scripts. The thing is that bcbio is used by others, is not that 'custom'  as something only running inside our cluster. In this case, is good If I add it here, to the main module?

**Comment by ewels** [comment]
Hah, that's the [second time today](https://github.com/ewels/MultiQC/issues/180#issuecomment-211450096) that this issue has come up. I will create a separate issue on the topic for discussion. For now not a problem as this is AdamaJava / qsignature though.

**Comment by lpantano** [comment]
awesome!

**Comment by ewels** [comment]
Hi @lpantano,

I've just had a crack at implementing this - I've written some documentation describing how to use the function [here](http://multiqc.info/docs/#step-7e-heatmaps). It seemed to be working ok with a few bits of demo data just now, but it's always a bit difficult to know for sure until you see it in action properly. Let me know if you're missing anything, and let me know how you get on!

Cheers,

Phil

**Comment by lpantano** [comment]
I will test it on Monday with real data :) thanks so much!

**Comment by ewels** [comment]
Not sure if you've had a chance to play with this yet, but I've just written a module in our institute-specific code that uses the new heatmap.. Seems to work well!

https://github.com/ewels/MultiQC_NGI/blob/master/multiqc_ngi/modules/ngi_rnaseq/heatmap.py

Example input file:
```
human_8	human_14	human_2	human_1	human_7	human_10	human_9	human_11	human_5	human_3	human_4	human_12	human_6	human_13
human_8	0	118.035435048698	118.035435048698	302.350113761651	302.350113761651	300.134417726832	299.018578965934	300.14631717474	300.14631717474	300.868924528241	300.868924528241	301.931776749411	300.852953343249	301.601318097725
human_14	118.035435048698	0	0	302.666197681026	302.666197681026	300.535773684601	299.650388569704	301.530708865985	301.530708865985	302.206320726006	302.206320726006	303.096345923656	302.048678453848	302.774798066333
human_2	118.035435048698	0	0	302.666197681026	302.666197681026	300.535773684601	299.650388569704	301.530708865985	301.530708865985	302.206320726006	302.206320726006	303.096345923656	302.048678453848	302.774798066333
human_1	302.350113761651	302.666197681026	302.666197681026	0	0	68.0716978377492	64.7002916865358	79.6066848463926	79.6066848463926	80.2832709054751	80.2832709054751	81.9623845925686	78.45419448351	80.9012585619235
human_7	302.350113761651	302.666197681026	302.666197681026	0	0	68.0716978377492	64.7002916865358	79.6066848463926	79.6066848463926	80.2832709054751	80.2832709054751	81.9623845925686	78.45419448351	80.9012585619235
human_10	300.134417726832	300.535773684601	300.535773684601	68.0716978377492	68.0716978377492	0	69.1358113462532	75.0518109916481	75.0518109916481	76.2850413971835	76.2850413971835	79.7194498132015	74.0836222055913	76.5818847198857
human_9	299.018578965934	299.650388569704	299.650388569704	64.7002916865358	64.7002916865358	69.1358113462532	0	76.582396161015	76.582396161015	77.5656538838401	77.5656538838401	85.8044176566693	79.8984237310206	82.2605470784442
human_11	300.14631717474	301.530708865985	301.530708865985	79.6066848463926	79.6066848463926	75.0518109916481	76.582396161015	0	0	64.3513633226639	64.3513633226639	73.0445446309927	65.9258741988526	69.9983742781403
human_5	300.14631717474	301.530708865985	301.530708865985	79.6066848463926	79.6066848463926	75.0518109916481	76.582396161015	0	0	64.3513633226639	64.3513633226639	73.0445446309927	65.9258741988526	69.9983742781403
human_3	300.868924528241	302.206320726006	302.206320726006	80.2832709054751	80.2832709054751	76.2850413971835	77.5656538838401	64.3513633226639	64.3513633226639	0	0	71.4033713401127	68.3743955193268	68.7939968472118
human_4	300.868924528241	302.206320726006	302.206320726006	80.2832709054751	80.2832709054751	76.2850413971835	77.5656538838401	64.3513633226639	64.3513633226639	0	0	71.4033713401127	68.3743955193268	68.7939968472118
human_12	301.931776749411	303.096345923656	303.096345923656	81.9623845925686	81.9623845925686	79.7194498132015	85.8044176566693	73.0445446309927	73.0445446309927	71.4033713401127	71.4033713401127	0	71.4411644647296	70.7747125022601
human_6	300.852953343249	302.048678453848	302.048678453848	78.45419448351	78.45419448351	74.0836222055913	79.8984237310206	65.9258741988526	65.9258741988526	68.3743955193268	68.3743955193268	71.4411644647296	0	67.8481509868289
human_13	301.601318097725	302.774798066333	302.774798066333	80.9012585619235	80.9012585619235	76.5818847198857	82.2605470784442	69.9983742781403	69.9983742781403	68.7939968472118	68.7939968472118	70.7747125022601	67.8481509868289	0
```

Phil

**Comment by avilella** [comment]
Can this heatmap module be copied into the main MultiQC?

I have a user case where the input is a matrix ready with the format needed
for loading into R which would be great if it would work as input in
MultiQC heatmaps:

https://github.com/ewels/MultiQC_TestData/pull/7

**Comment by ewels** [comment]
Hmm, I'm not sure how I feel about having a generic MultiQC module that doesn't know where it's input comes from. What generates the test data? Is it a standard `bedtools` command or something?

**Comment by avilella** [comment]
It's from following a tutorial about using bedtools jaccard that @arq5x wrote:
http://quinlanlab.org/tutorials/bedtools/bedtools.html#a-jaccard-statistic-for-all-400-pairwise-comparisons

So I guess it could be something like `multicorrelate_bed`
I streamlined the scripts into a perl script, which I can publish on a github gist if it helps.

**Comment by avilella** [comment]
https://gist.github.com/avilella/869c1565c5ed8ad7d176c3dc1c0ba657

**Comment by ewels** [comment]
Thanks! The problem with this is that there's no consistent file name, file structure, or meaning. So MultiQC doesn't know how to find these files, or what to attribute them to. There's not really any way around this for the core program, I think you're best off doing what we have done - make your own add on package with a module that recognises the file name that you will use with your scripts.

See the relevant script I've written in our plugin here:
https://github.com/ewels/MultiQC_NGI/blob/master/multiqc_ngi/modules/ngi_rnaseq/heatmap.py
Documentation here:
http://multiqc.info/docs/#multiqc-plugins

Phil
