### ISSUE TITLE
Whatshap module renames sample "123_4" to "1234"

### ISSUE THREAD

**Issue by Redmar-van-den-Berg** [ewels/MultiQC#1793]
### Description of bug

Sample names which are all numeric, but with underscores, get their underscores removed in the WhatsHap module. This leads to duplicates in the General Statistics table, where the stats from all other modules use the correct sample name, but WhatsHap uses the shortened sample name.

**Comment by Redmar-van-den-Berg** [comment]
This bug was caused by the fact that we attempt to convert every value in the WhatsHap tsv output to int, and `123_4` is a valid way to write the number `1234` in python (for better legibility for large numbers). The solution is to first extract the sample name (and chromosome name) from the data, and then convert only the remaining values to int.

**Comment by ewels** [comment]
> `123_4` is a valid way to write the number `1234` in python

WHAT?? 🤯  How have I never come across this before? 😅
