### ISSUE TITLE
sourmash compare module

### ISSUE THREAD

**Issue by taylorreiter** [ewels/MultiQC#1805]
### Name of the tool

sourmash

### Tool homepage

https://github.com/sourmash-bio/sourmash

### Tool description

Quickly search, compare, and analyze genomic and metagenomic data sets.

### Tool output

[comp_k31.zip](https://github.com/ewels/MultiQC/files/10106412/comp_k31.zip)

### Log filename pattern

*.labels.txt

### Data suitable for MultiQC plot(s)

sourmash compare outputs a numpy matrix. The matrix is square and it represents similarity samples. By default this matrix is printed to standard out, but the `-o` flag can be used to output two files. The first is named by the exact text given to `-o` and is a numpy matrix. The second starts with the user-specified value and ends with `.labels.txt`. 
So:

`sourmash compare -o comp_k31 *sig` would produce
- `comp_k31`: a numpy matrix representing similarity between all samples
- `comp_k31.labels.txt`: the sample labels for each sample represented in `comp_k31`. 

The command `sourmash plot` already uses python code to make plots from this data. I think it would be nice to include this type of visualization in mutliqc:
![comp_k31 matrix](https://user-images.githubusercontent.com/23057646/204351489-0e3f4ed2-550f-4fd3-a857-997abd21a866.png)

### Most interesting data for the General Stats table

Highest similarity it matrix (other than the diagonal, which will always be 1), and lowest similarity it matrix.

**Comment by taylorreiter** [comment]
I wanted to link to #986 which requested a module for the output of `sourmash sig describe`, which is different from the output of sourmash compare.

Also I've read the documentation and plan to work on this module myself, but I wanted to start this issue to 
1. document that I'm working on it and
2. check if it's ok to add this to multiqc. this output isn't technically a log file but rather a small output file that condenses a lot of comparisons between samples. I could write custom modules if this is outside of the scope of multiqc, but I'm quite excited about the built-in multiqc integration for nextflow pipelines started with `nf-core create`, and I love the idea of my high-level pipeline outputs being summarized in a single html file.

**Comment by vladsavelyev** [comment]
Fixed with https://github.com/ewels/MultiQC/pull/1812
