### ISSUE TITLE
sourmash gather module

### ISSUE THREAD

**Issue by taylorreiter** [ewels/MultiQC#1806]
### Name of the tool

sourmash

### Tool homepage

https://github.com/sourmash-bio/sourmash

### Tool description

Quickly search, compare, and analyze genomic and metagenomic data sets.

### Tool output

[SRR19888438ass-vs-genbank-2022.03-k31.csv](https://github.com/ewels/MultiQC/files/10106531/SRR19888438ass-vs-genbank-2022.03-k31.csv)

### Data suitable for MultiQC plot(s)

Sourmash gather compares a sample (usually a metagenome) against a database of reference genomes (e.g. GenBank or GTDB) and determines the minimum set of genomes in the database that "cover" (contain) all of the k-mers in the sample that are in the database.

A plot like the one below would be super helpful to visualize the fraction of the sample that was identified in the database. This plot shows the output for 6 samples
![image](https://user-images.githubusercontent.com/23057646/204355491-c9c90b17-e10c-4f4f-87fd-1c30eb291275.png)

I think the above plot would be most useful, but a table that could also be useful would be one that shows the top match or top 5 matches in a metagenome or something like that. (could be determined by `gather_rank`, largest `f_unique_to_query` (fraction unique to query) or `f_unique_weighted` (abundance-weighted fraction unique to query, or highest `f_match` (fraction of the genome match from the database that is in the query, sort of like breadth of coverage))

### Most interesting data for the General Stats table

* fraction of sample matched against database (sum of `f_unique_to_query`)
* abundance-weighted fraction of sample matched against database (sum of `f_unique_weighted`)
* Number of genomes matched against sample (number of rows in the csv file minus the header)

**Comment by taylorreiter** [comment]
Relevant to #1805 and #986 as all are output created by sourmash. Like #1805, this output isn't technically a log file but an output file, so I wanted to check that it's ok to include it as a multiqc module before I begin working on it. As an alternative, I could write custom modules if this is outside of the scope of multiqc, but I'm quite excited about the built-in multiqc integration for nextflow pipelines started with nf-core create, and I love the idea of my high-level pipeline outputs being summarized in a single html file.

Since the output files generated by sourmash gather are all user-defined, I think it might work best to look for the header of the file, which should be mostly consistent (sometimes new columns are added with different versions of sourmash, but columns aren't taken away once they've been added)

**Comment by vladsavelyev** [comment]
Fixed with https://github.com/ewels/MultiQC/pull/1816
