### ISSUE TITLE
CI Linux / Linux - Python 3.6 (pull_request) fails with error `Error: Version 3.6 with arch x64 not found`

### ISSUE THREAD

**Issue by taylorreiter** [ewels/MultiQC#1813]
### Description of bug

CI for #1812 fails for Linux / Linux - Python 3.6 (pull request) with:

```
Run actions/setup-python@v2
Version 3.6 was not found in the local cache
Error: Version 3.6 with arch x64 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

Looking at the `versions-manifest.json`, the maximum ubuntu version for python 3.6* is "platform_version": "20.04". The CI actions are running on 22.04.1, so I think this is causing the failure?

**Comment by ewels** [comment]
Thanks, I just saw the same thing. Should be fixed in 9d87325bb7a63189cd1416e874c65af9274fd738 👍🏻 

Not really a long term solution, I expect to come against this again before too long. I think when that happens I'll probably drop official support for python 3.6.
