### ISSUE TITLE
dragen_fastqc incorrectly computes N content

### ISSUE THREAD

**Issue by cpalmer718** [ewels/MultiQC#1830]
The dragen_fastqc module does not clear aggregated totals and N content across samples, causing the N content per-sample to be order-dependent and to approach a cross-sample homogenized average.  Problematic lines are [here](https://github.com/ewels/MultiQC/blob/8af61c1bde6ae0a38697e2f372866f8bc0e71a4a/multiqc/modules/dragen_fastqc/content_metrics.py#L43-L44):

https://github.com/ewels/MultiQC/blob/8af61c1bde6ae0a38697e2f372866f8bc0e71a4a/multiqc/modules/dragen_fastqc/content_metrics.py#L43-L44

This issue has been live in Illumina's for-profit Basespace multiqc module for at least a year. Unfortunately, I don't have any test data to show for this, as I originally found this problem in a prior job and the example data I was using didn't come with me; but the issue is very apparent once you know where to look.

**Comment by cpalmer718** [comment]
I can post a tiny PR if you'd prefer.

**Comment by ewels** [comment]
A tiny PR would be great, please!

**Comment by cpalmer718** [comment]
See #1831 . Apologies if I've missed anything relevant in the contributing guidelines.

**Comment by ewels** [comment]
Thanks!
