### ISSUE TITLE
Broken following one file 

### ISSUE THREAD

**Issue by sandray-imp** [ewels/MultiQC#1846]
This is the error message I got (error file is attached but not in the original format - can't upload .tab file): 

```
Please copy this log and report it at                                        │
│ https://github.com/ewels/MultiQC/issues                                      │
│ Please attach a file that triggers the error. The last file found was: /Volu │
│ mes/SandraDrive/RNAseq_Eos/IM-aligned-data/star_results/Plate2_B11_S1/._Read │
│ sPerGene.out.tab                                                             │
│                                                                              │
│ Traceback (most recent call last):                                           │
│   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site │
│     output = mod()                                                           │
│   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site │
│     parsed_data = self.parse_star_genecount_report(f)                        │
│   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site │
│     for l in f["f"]:                                                         │
│   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/code │
│     (result, consumed) = self._buffer_decode(data, self.errors, final)       │
│ UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 37: inv │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯
|           multiqc | No analysis results found. Cleaning up..
|           multiqc | MultiQC complete
```

[ReadsPerGene.out.pdf](https://github.com/ewels/MultiQC/files/10475926/ReadsPerGene.out.pdf)

**Comment by ewels** [comment]
Please zip the `.tab` file, then it'll allow you to attach it. Also please include the full MultiQC log 😊

**Comment by sandray-imp** [comment]
[ReadsPerGene.out.tab.zip](https://github.com/ewels/MultiQC/files/10476857/ReadsPerGene.out.tab.zip)

Thank you for responding. This is the zipped .tab file. How do I get the full log?

**Comment by ewels** [comment]
Thanks! I just mean copy and paste the full thing from the terminal. It's important because it includes information such as which version of MultiQC you're using..

**Comment by sandray-imp** [comment]
Oh I see. Here it is (masked personal info): 

(base) MAC307320:STAR xxx$ multiqc /Volumes/SandraDrive/RNAseq_Eos/IM-aligned-data/star_results

  /// MultiQC 🔍 | v1.11

|           multiqc | Search path : /Volumes/SandraDrive/RNAseq_Eos/IM-aligned-data/star_results
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 416/416  
╭────────────────── Oops! The 'star' MultiQC module broke... ──────────────────╮
│ Please copy this log and report it at                                        │
│ https://github.com/ewels/MultiQC/issues                                      │
│ Please attach a file that triggers the error. The last file found was: /Volu │
│ mes/SandraDrive/RNAseq_Eos/IM-aligned-data/star_results/Plate2_B11_S1/._Read │
│ sPerGene.out.tab                                                             │
│                                                                              │
│ Traceback (most recent call last):                                           │
│   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site │
│     output = mod()                                                           │
│   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site │
│     parsed_data = self.parse_star_genecount_report(f)                        │
│   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site │
│     for l in f["f"]:                                                         │
│   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/code │
│     (result, consumed) = self._buffer_decode(data, self.errors, final)       │
│ UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 37: inv │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯
|           multiqc | No analysis results found. Cleaning up..
|           multiqc | MultiQC complete

**Comment by ewels** [comment]
Thanks! So first thing to try is updating to the latest version of MultiQC, in case this is a bug that's already been fixed. If that doesn't help, I'll try to replicate the error myself with your file and fix the bug.

**Comment by ewels** [comment]
Hi @sandray-imp,

I just tried running MultiQC with the example file you uploaded and it worked fine:

```
❯ multiqc -f .

  /// MultiQC 🔍 | v1.15.dev0 (abcdcb5)

|           multiqc | Search path : /Users/ewels/GitHub/MultiQC/TestData/data/modules/star/issue_1846
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1
|              star | Found 1 gene count files
|           multiqc | Compressing plot data
|           multiqc | Report      : multiqc_report.html
|           multiqc | Data        : multiqc_data
|           multiqc | MultiQC complete
```

[multiqc_report.html.zip](https://github.com/ewels/MultiQC/files/10523030/multiqc_report.html.zip)

I'm closing this issue as "already fixed" ✅ 

Let me know if you still hit it with the latest version of MultiQC and we can reopen.

Thanks!

Phil
