### ISSUE TITLE
Divide By Zero error

### ISSUE THREAD

**Issue by treodeo** [ewels/MultiQC#1847]
### Description of bug

I think I have a BAM file for RSeQC that contains no information or zero counts of some sort. 

Everything else gets tabulated except for the Gene Coverage Profile as part of the QualiMap.

From the MutliQC.log.txt

```
╭───────────────── Oops! The 'rseqc' MultiQC module broke... ──────────────────╮
│ Please copy this log and report it at                                        │
│ https://github.com/ewels/MultiQC/issues                                      │
│ Please attach a file that triggers the error. The last file found was:       │
│ RSeQC/WT_Rot_Rep1/WT_Rot_Rep1_bam_stats_out.txt                              │
│                                                                              │
│ Traceback (most recent call last):                                           │
│   File "/ref/rmlab/software/spack/opt/spack/linux-rocky8-x86_64/gcc-8.5.0/py │
│     output = mod()                                                           │
│   File "/ref/rmlab/software/spack/opt/spack/linux-rocky8-x86_64/gcc-8.5.0/py │
│     n[sm] = getattr(module, "parse_reports")(self)                           │
│   File "/ref/rmlab/software/spack/opt/spack/linux-rocky8-x86_64/gcc-8.5.0/py │
│     d["unique_percent"] = (float(d["mapq_gte_mapq_cut_unique"]) / t) * 100.0 │
│ ZeroDivisionError: 

float division by zero                                    │
│                                                                              │
```

[MultiQC_FullReport.log.txt](https://github.com/ewels/MultiQC/files/10511354/MultiQC_FullReport.log.txt)

### File that triggers the error

[WT_Rot_Rep1_bam_stats_out.txt](https://github.com/ewels/MultiQC/files/10511362/WT_Rot_Rep1_bam_stats_out.txt)

**Comment by ewels** [comment]
Could you please check with the latest version of MultiQC? I've fixed a few of these recently. RSeQC has a lot of submodules though, so it's possible that this is another one. 

I'm on leave at the moment so will be slow, but I'll take a look otherwise when I can.

**Comment by ewels** [comment]
Just tested locally with the latest dev version and MultiQC ran fine, so closing this as already fixed ✅ 

Let me know if you are still having problems with the latest version!
