### ISSUE TITLE
Porechop bar charts result in error when no adapters found by tool

### ISSUE THREAD

**Issue by jfy133** [ewels/MultiQC#1850]
The recently added porechop module  was only tested on a log file from a file that did in fact have adapters. We've just learnt that when there are no adapters, Porechop does not report the log file sections used in the current MultiQC module (resulting in a 'no data found' error in MultiQC).

The MultiQC module should be updated to either skip the `add_section` call when the corresponding values are not found, or could have a custom HTML div + `.alert` that explains why (suggested by @ewels )

I will assign this to @sofstam and myself

**Comment by jfy133** [comment]
[Porechop_NoAdaptersFound.log](https://github.com/ewels/MultiQC/files/10546364/Porechop_NoAdaptersFound.log)

test data to go on the repo when we get to this :)

**Comment by ewels** [comment]
@jfy133 - done ✅ 😊
