### ISSUE TITLE
when fastqc reports for many samples, always miss sample 10 in the multiqc report

### ISSUE THREAD

**Issue by ShanshuoZHU** [ewels/MultiQC#1863]
### Description of bug

I was using multiqc to combine all the fastqc reports for my 32 samples with the following code:

multiqc -n fastqc-output/*_1_fastqc.zip -o multiqc-output/ -n all-1

it always generate a report for 31 samples ins
![Picture1](https://user-images.githubusercontent.com/124776861/217495196-00352f93-a51f-47ab-9199-9f9d6919f743.png)
tead of 32 and sample 10 was missed.
[multiqc.log](https://github.com/ewels/MultiQC/files/10684097/multiqc.log)

**Comment by ewels** [comment]
Just saw this in your log file:

```
This is MultiQC v1.0.dev0
```

Wow! If that's correct, your version of MultiQC is 5 years old. I would definitely also recommend updating to the latest version (v1.14).

**Comment by ShanshuoZHU** [comment]
Hi, thanks a lot for all the suggestions,
I tried "conda install -c bioconda -c conda-forge multiqc" (https://multiqc.info/docs/#installing-with-conda) and "conda install -c "bioconda/label/cf201901" multiqc" (https://anaconda.org/bioconda/multiqc). Either of them helped install the latest version. Now I only have MultiQC v1.7.

And I tired with running MultiQC with the -d and -s flags, as suggested in the troubleshooting docs. it didnot help yet

**Comment by ewels** [comment]
Oof, those docs are out of date. Sorry, I updated them in other places but apparently missed those.

For conda, first install and configure as described on their docs: https://bioconda.github.io/

```bash
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
conda config --set channel_priority strict
```

Then just do `conda install multiqc` (no `-c` anything). That should get you the latest version.

**Comment by ewels** [comment]
ps. If MultiQC doesn't generate a report when you run it on _just_ that FastQC report then please attach it so that I can try to replicate the error.

Please also try to take a look at that report manually to check that the file isn't corrupted etc.

**Comment by ShanshuoZHU** [comment]
> 



> Oof, those docs are out of date. Sorry, I updated them in other places but apparently missed those.
> 
> For conda, first install and configure as described on their docs: https://bioconda.github.io/
> 
> ```shell
> conda config --add channels defaults
> conda config --add channels bioconda
> conda config --add channels conda-forge
> conda config --set channel_priority strict
> ```
> 
> Then just do `conda install multiqc` (no `-c` anything). That should get you the latest version.

Thanks a lot! I managed to get the lasted version

**Comment by ewels** [comment]
Ok - please try to attach some files so that I can replicate the problem. I'm afraid I can't help with the information that I currently have.

**Comment by ShanshuoZHU** [comment]
> Ok - please try to attach some files so that I can replicate the problem. I'm afraid I can't help with the information that I currently have.

I am sorry... Here are more details. 
I have the original problem that I multiqc to combine reports for my 32 samples, but always the sample 10 missed.
I tried "multiqc -n fastqc-output/*L1_1*fastqc.zip -o multiqc-output/ -d -s " and I got this (below, and all the attached 1-multiqc.log)
![image](https://user-images.githubusercontent.com/124776861/218714067-797b660d-b0a4-4b70-9298-54ef3b531fc1.png)
 
when I used "multiqc -n fastqc-output/*L1_1*fastqc.zip -o multiqc-output/ -n  all_L1_1 -d -s",  I got this (below, and all the attached 2-multiqc.log)
![image](https://user-images.githubusercontent.com/124776861/218714637-10d0f2fa-d611-452b-8c1b-389ce7d32955.png)
[1-multiqc.log](https://github.com/ewels/MultiQC/files/10731608/1-multiqc.log)
[2-multiqc.log](https://github.com/ewels/MultiQC/files/10731609/2-multiqc.log)

**Comment by ShanshuoZHU** [comment]
> Ok - please try to attach some files so that I can replicate the problem. I'm afraid I can't help with the information that I currently have.

I am sorry... Here are more details.
I have the original problem that I use multiqc to combine reports for my 32 samples, but always the sample 10 missed.
I tried "multiqc -n fastqc-output/L1_1fastqc.zip -o multiqc-output/ -d -s " and I got this (below, and all the attached 1-multiqc.log)
![image](https://user-images.githubusercontent.com/124776861/218715478-1ce78008-9b33-4f62-9a2c-08e4a73f078d.png)

when I used "multiqc -n fastqc-output/L1_1fastqc.zip -o multiqc-output/ -n all_L1_1 -d -s", I got this (below, and all the attached 2-multiqc.log)

![image](https://user-images.githubusercontent.com/124776861/218715506-35b81160-363f-4bef-a0c3-8193fb79659c.png)


[1-multiqc.log](https://github.com/ewels/MultiQC/files/10731633/1-multiqc.log)
[2-multiqc.log](https://github.com/ewels/MultiQC/files/10731634/2-multiqc.log)

**Comment by ShanshuoZHU** [comment]
> Ok - please try to attach some files so that I can replicate the problem. I'm afraid I can't help with the information that I currently have.
I am sorry. Here are some details.

I have the original problem that  I use multiqc to combine all reports for my 32 samples, always the sample 10 was missing in the report.

I tried with this code "multiqc -n fastqc-output/*L1_1*fastqc.zip -o multiqc-output/ -d -s", I got this (below) and the attached (1-multiqc.log)
![image](https://user-images.githubusercontent.com/124776861/218716435-a0ab586b-d671-47e5-af00-59bd05cd64ca.png)

When I tried with this code "multiqc -n fastqc-output/*L1_1*fastqc.zip -o multiqc-output/  -n  all_L1_1 -d -s", I got this (below) and the attached (2-multiqc.log)
![image](https://user-images.githubusercontent.com/124776861/218716898-c5cf5ee6-f405-429c-8d4c-d18968d1fc19.png)



[1-multiqc.log](https://github.com/ewels/MultiQC/files/10731672/1-multiqc.log)
[2-multiqc.log](https://github.com/ewels/MultiQC/files/10731673/2-multiqc.log)

**Comment by vladsavelyev** [comment]
@ShanshuoZHU, please remove the `-n` parameter from your command. What's happening is that your shell takes the first input file as the value for the `-n` parameter instead of the input path for MultiQC. So `multiqc -n fastqc-output/*.zip` translates into `multiqc -n SZ10_EKDL220016378-1A_HKKNKDSX5_L1_1_fastqc.zip fastqc-output/SZ11_EKDL220016378-1A_HKKNKDSX5_L1_1_fastqc.zip fastqc-output/SZ12_EKDL220016378-1A_HKKNKDSX5_L1_1_fastqc.zip ...`, and the first file is used as the desired output path (as the `-n` parameter does) instead of an input.
