### ISSUE TITLE
Warn about empty rseqc genebody coverage files

### ISSUE THREAD

**Issue by jfreimer** [ewels/MultiQC#187]
I'm running version 0.6dev. When running MultiQC in a directory of RSeQC output files, it finds the duplication data output and successfully makes a report. However, MultiQC does not detect any of the files named `sample.geneBodyCoverage.txt` and include them in the report.

**Comment by ewels** [comment]
Hi @jfreimer,

Thanks for the report - what version of RSeQC are these from? The format changed at v2.4, so it's possible that there's a third variant that I haven't yet found. I'm expecting the file to start with either `Percentile` or `Total reads`. Could you post an example log file please?

Do the plots from RSeQC look sensible? The reason I ask this is that I debugged some other files the other day for ages before realising that the FastQ files had been downsampled massively and the geneBodyCoverage file only had a header line and no data.

Cheers,

Phil

**Comment by jfreimer** [comment]
Ah, it appears to be a problem with RSeQC not generating the files properly in the first place.

**Comment by ewels** [comment]
Ok great - thanks for reporting anyway. I'll get MultiQC to throw a warning if it finds a file with no data.

Phil

**Comment by ewels** [comment]
Hi @jfreimer - would you mind pulling this latest commit and checking that (a) MultiQC still runs, and (b) you get a warning about the empty file?

Cheers,

Phil

**Comment by jfreimer** [comment]
I pulled the latest commit and tried to run it in a directory with an empty geneBodyCoverage.txt file and got the following error:

`Traceback (most recent call last):
  File "/N/u/jfreimer/Mason/miniconda/bin/multiqc", line 431, in <module>
    multiqc()
  File "/N/u/jfreimer/Mason/miniconda/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/N/u/jfreimer/Mason/miniconda/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/N/u/jfreimer/Mason/miniconda/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/N/u/jfreimer/Mason/miniconda/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/N/u/jfreimer/Mason/miniconda/bin/multiqc", line 248, in multiqc
    template_mod = config.avail_templates[template].load()
  File "/N/u/jfreimer/Mason/miniconda/lib/python2.7/site-packages/distribute-0.6.10-py2.7.egg/pkg_resources.py", line 1947, in load
    if require: self.require(env, installer)
  File "/N/u/jfreimer/Mason/miniconda/lib/python2.7/site-packages/distribute-0.6.10-py2.7.egg/pkg_resources.py", line 1960, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer))
  File "/N/u/jfreimer/Mason/miniconda/lib/python2.7/site-packages/distribute-0.6.10-py2.7.egg/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pytz`

**Comment by ewels** [comment]
I think this is some kind of weird `pip` installation error? Maybe try running `python setup.py install` again and see if that fixes it. Doesn't look like the traceback is related to any of the changes I've made in the code..

**Comment by ewels** [comment]
Sorry, you're using miniconda. But same difference - some kind of installation error by the look of it.

**Comment by jfreimer** [comment]
Yeah ended up being a weird `pip` error after upgrading. Re-installed and `multiqc` is working fine. However, I'm not getting an error about an empty file.

`[jfreimer@h1 test]$ ls
multiqc_data  multiqc_report.html  sample_distribution.txt  sample.geneBodyCoverage.txt`

`[jfreimer@h1 test]$ multiqc . 
[INFO   ]         multiqc : This is MultiQC v0.6.dev0
[INFO   ]         multiqc : Searching '.'
[INFO   ]           rseqc : Found 1 read_distribution reports
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete`

**Comment by ewels** [comment]
Hi @jfreimer,

Could you send the empty file through? It's working for me:
```
[WARNING] gene_body_coverage : Empty geneBodyCoverage file found: empty_failed.geneBodyCoverage.txt
[INFO   ]           rseqc : Found 8 gene_body_coverage reports
```

Cheers,

Phil

**Comment by ewels** [comment]
Closing until I can replicate the problem.
