### ISSUE TITLE
support "same sample, same module, different analysis" use case

### ISSUE THREAD

**Issue by a-frantz** [ewels/MultiQC#1881]
### Description of feature

Current behavior: if two reports from the same module for the same sample are found, MultiQC only processes and displays one of them.

Desired behavior: We are trying to calculate coverage, using `mosdepth`, on 3 different regions (whole genome, whole exome, and whole coding domain), and would like all 3 reports included in MultiQC. In essence, we want the `mosdepth` module to appear 3 times, with the same samples (but different results) in each. The `mosdepth` entries in the general stats column should similarly appear in triplicate.

Alternatives available to us if this gets labelled as a "won't do":
* mess with the sample names so all 3 analyses get displayed at once
  * not actually an option since that would look sloppy and we're trying to present these reports, not just use them internally
* generate 3 different MultiQC reports, with the only difference being which `mosdepth` runs are displayed
  * viable alternative, though we'd much prefer to keep everything in a single report
* choose only one analysis to display in the MultiQC report, tell users to dive into the files for the other 2 analyses
  * bad user experience, not a viable solution
* fork the repo and implement it ourselves
  * certainly an option, but we would rather be using an officially released version of MultiQC in our pipelines

I'd be willing to take on some of the development behind getting this change incorporated into MultiQC. However I wanted your feedback on the concept before putting any work into the idea. And if you'd be willing to move forward with this, I imagine you'll have some thoughts on the overall design/implementation you'd like to put out there.

**Comment by ewels** [comment]
This isn't an unusual scenario, I'm pretty sure you don't need to edit any code here. Just check the docs and use whatever options / flags make sense for you (likely `--dirs`): https://multiqc.info/docs/#clashing-sample-names

Closing as I think that should solve your issue, but feel shout if not and I can reopen.

**Comment by a-frantz** [comment]
The `--dirs` option (or any of the other current options) does not produce our desired behavior. What we're looking for is that the figures from `mosdepth` repeat 3 times, only displaying a subset of the found results. We find it impossible to parse the figures when all 3 of our analyses appear in the same figures.

To try and illustrate what we're asking, imagine the following directory structure:
```
sample1.strandedness.txt
sample2.strandedness.txt
whole_genome/
    sample1.mosdepth.global.dist.txt
    sample1.mosdepth.summary.txt
    sample2.mosdepth.global.dist.txt
    sample2.mosdepth.summary.txt
exon/
    sample1.mosdepth.region.dist.txt
    sample1.mosdepth.summary.txt
    sample2.mosdepth.region.dist.txt
    sample2.mosdepth.summary.txt
CDS/
    sample1.mosdepth.region.dist.txt
    sample1.mosdepth.summary.txt
    sample2.mosdepth.region.dist.txt
    sample2.mosdepth.summary.txt
```
We'd like the resulting summary stats table to look something like this:
```
Sample Name | Strandedness | (whole_genome) >30x | (whole_genome) Mean Cov. | (whole_genome) Median | (exon) >30x | (exon) Mean Cov. | (exon) Median | (CDS) >30x | (CDS) Mean Cov. | (CDS) Median
sample1 | Unstranded | 10% | 40X | 30X | 50% | 50X | 40X | 90% | 60X | 55X
sample2 | Unstranded | 10% | 40X | 30X | 50% | 50X | 40X | 90% | 60X | 55X
```
Then the figures to appear something like this:
```
mosdepth
* (whole_genome) Cumulative coverage distribution
* (whole_genome) Coverage distribution
* (whole_genome) Average coverage per contig
* (exon) Cumulative coverage distribution
* (exon) Coverage distribution
* (exon) Average coverage per contig
* (CDS) Cumulative coverage distribution
* (CDS) Coverage distribution
* (CDS) Average coverage per contig
```
Does this make sense? We want the different analyses to be grouped under the same sample in the general stats column, but then be separate in the figures.

**Comment by ewels** [comment]
Ah ok, if you want them to be in separate plots / tables, you need to run the module multiple times and use `path_filters` to scoop up just the log files that you want each time.

Docs here: https://multiqc.info/docs/#running-modules-multiple-times

Common use case is to run FastQC before and after trimming, for example. I think that should work here?

If not then third time lucky and I can reopen 😅
