### ISSUE TITLE
Trying to use the --sample-names toggle option within custom HTML

### ISSUE THREAD

**Issue by sscho** [ewels/MultiQC#1882]
### Description of feature

Is there a way to get the sample-names toggle to also work within custom HTML files? I thought it'd be as easy as adding the data-original-sn attribute in the HTML, but doesn't seem to work. Perhaps it only works within certain div classes? Or of particular HTML elements. Thanks in advance!

samplesheet.tsv
```
ID	Other thing
testID	otherid
```

test_mqc.html:
```html
<!--
id: 'custom-html'
section_name: 'Custom HTML'
description: 'This section is created using a custom HTML file'
-->
<p class="rowheader" data-original-sn="testID">testID</p>
```

`multiqc . --interactive --sample-names samplesheet.tsv`

**Comment by ewels** [comment]
Sorry, I don't think that this is possible (easily). Custom HTML is just injected in as-is and none of the front-end tooling is aware of it at all. Of course you're welcome to try to get it working, but it's not supported.

From a quick glance, the attribute you found is only used with tables:

https://github.com/ewels/MultiQC/blob/bad886aaf2783fa753a48764000b63457282d4c3/multiqc/templates/default/assets/js/multiqc_tables.js#L208-L209

**Comment by ewels** [comment]
Closing as this isn't something that I'm going to work on any time soon, sorry. Please do post back if you get something working though!

**Comment by ewels** [comment]
Ok nice! If you don't mind getting your hands dirty with some javascript, then there are also custom listeners that you can use to tie into the toolbox functionality. See the docs: https://multiqc.info/docs/#custom-event-triggers

I wrote this stuff years ago and am not sure that I'm aware of anyone ever using it, so it would be fun if it's useful to you!

**Comment by sscho** [comment]
Oh - this is perfect! Thanks for letting me know
