### ISSUE TITLE
DRAGEN: Target Metrics doesn't handle germline data

### ISSUE THREAD

**Issue by alexiswl** [ewels/MultiQC#1884]
### Description of bug

Target metrics is blank if target metrics file does not contain a '_tumor' or '_normal' suffix.  

Steps to reproduce

## Create image

```bash
mkdir -p src/master/
(
    cd src/master/;
    git clone -b master https://github.com/ewels/multiqc
    cd multiqc; 
    docker build -t localhost/multiqc:master .
)
```

## Create test data

```bash
mkdir -p inputs/just_roma/test_data/
(
  cd inputs/just_roma/test_data/;
  wget "https://github.com/ewels/MultiQC/files/10944125/test_coverage_data.zip";
  unzip test_coverage_data.zip  
)
```

## Run image

```bash
mkdir -p outputs/master/just_roma_data_test/
docker run --rm \
  --volume "$PWD/inputs/just_roma/:/inputs" \
  --volume "$PWD/outputs/master/just_roma_data_test/:/outputs" \
  localhost/multiqc:master \
    multiqc /inputs \
      --outdir /outputs \
      --filename "master-just-roma-data-test" \
      --comment "master-with-just-roma-data-test"
```

Shows the following in the target metrics

![image](https://user-images.githubusercontent.com/8197659/225478214-fd576a72-a5dc-42aa-9a4d-7ba0ac710d20.png)

### File that triggers the error

[test_coverage_data.zip](https://github.com/ewels/MultiQC/files/10985566/test_coverage_data.zip)

### MultiQC Error log

```console
/// MultiQC 🔍 | v1.15.dev0

|           multiqc | Search path : /inputs
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 82/82
|            dragen | Found 10 reports
|           multiqc | Compressing plot data
|           multiqc | Report      : ../../outputs/master-just-roma-data-test.html
|           multiqc | Data        : ../../outputs/master-just-roma-data-test_data
|           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/#troubleshooting-1).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by Just-Roma** [comment]
I have tested both versions of code (upstream, our update) with the provided test data.

This is the output of the upstream:

![upstream](https://user-images.githubusercontent.com/64587275/225527918-2e47f52c-cc9f-4f22-9a1c-e3e0e5f3d5ae.png)

Output of the update:

![update](https://user-images.githubusercontent.com/64587275/225527972-a320df0a-34f9-4d44-b76a-5d402a6b9fd0.png)

The reason for absence of columns in the first one is simple: it can only recognize the target region from input data if that region is the "target region". The artificial test data has instead the "target bed". 
This is how it would look like for the "target region" ([PR for this data](https://github.com/ewels/MultiQC_TestData/pull/249)):

![new](https://user-images.githubusercontent.com/64587275/225529893-2bddee40-f8ce-45d7-91d3-c41b451f67a4.png)

**Comment by ewels** [comment]
@alexiswl - can this issue be closed now?

**Comment by alexiswl** [comment]
Yes this can be closed.
