### ISSUE TITLE
Picard SD_COVERAGE wrong column label in the html report

### ISSUE THREAD

**Issue by B3rse** [ewels/MultiQC#1888]
### Description of bug

multiqc, version 1.14 (1e79a52)

In the html report, the column corresponding to `SD_COVERAGE` from Picard `wgs_metrics` is wrongly labelled as `Median Coverage`.

### File that triggers the error

![Screen Shot 2023-03-21 at 11 00 34 AM](https://user-images.githubusercontent.com/11838651/226647894-c0ae61f0-3506-4728-a3b4-c6006b9abc26.png)

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/#troubleshooting-1).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by ewels** [comment]
Thanks for reporting, and thanks for the fix @pontushojer !
