### ISSUE TITLE
Add single end support for Tophat

### ISSUE THREAD

**Issue by jfreimer** [ewels/MultiQC#189]
The plot is showing input read counts, but not mapped counts.

Attached are picture of plot and tophat align_summary file.

<img width="559" alt="screen shot 2016-04-26 at 10 28 05 am" src="https://cloud.githubusercontent.com/assets/7303848/14827990/c91649f4-0b99-11e6-8be4-89f9fd247857.png">
[align_summary.txt](https://github.com/ewels/MultiQC/files/237145/align_summary.txt)

**Comment by ewels** [comment]
Aha - is this from a single end run? It looks like the [test logs](https://github.com/ewels/MultiQC_TestData/tree/master/data/modules/tophat) I have are all paired end.

I'll add your log to the test dataset and add in support for single end data. Thanks!

**Comment by jfreimer** [comment]
Yes this is single end.

**Comment by ewels** [comment]
Thanks @jfreimer - hopefully this should be fixed with the above commit. Let me know if you run into any problems.
