### ISSUE TITLE
The percentage of duplication was not the one indicated in the fastqc of the samples

### ISSUE THREAD

**Issue by cmandier** [ewels/MultiQC#1890]
### Description of bug

Hello,
I noticed when using Multiqc with the fastqc module, the percentage of duplication present in the general statistics was not the one indicated in the fastqc of the samples. In fact, it seems to me that the percentage displayed is the opposite of what it should be in reality. In my fastqc, the duplication percentage is 24% but in the multiqc it shows 76%.

Best regards

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/#troubleshooting-1).
- [X] I am using the latest release of MultiQC.
- [ ] I have included a full MultiQC log, not truncated.
- [ ] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by ewels** [comment]
Apologies for the delay in getting to this, it got lost.

It's not possible to help here without some example data. If it's still a problem, please submit a new issue using the bug template and attaching some example files, saying what you expect to see.

Thanks
