### ISSUE TITLE
No analysis results found. Cleaning up..

### ISSUE THREAD

**Issue by hsaxe** [ewels/MultiQC#1898]
![image](https://user-images.githubusercontent.com/77753815/230694998-ee096b5b-3348-4e6e-84aa-4b76b6848f56.png)
Above is the issue I'm running into. I am trying to generate an HTML report of fastq.gz files preprocessed bt HTStream. The output of HTSream are a bunch of .json files with the results of the preprocessing.  They just need to be parsed. The tool seems to identify the .json files but no report is produced.

**Comment by tamuanand** [comment]
Is HTStream a MultiQC supported tool? - https://multiqc.info/modules/

**Comment by ewels** [comment]
It's not, no. The review process went stale for a long time but has recently (by my standards 😓 ) picked back up again. 

It's a massive PR so a lot of work to review + merge. I'll get to it ASAP though. In the mean time, you can install MultiQC from the fork that the PR is coming from if you wish: https://github.com/s4hts/MultiQC

```bash
pip install --upgrade --force-reinstall git+https://github.com/s4hts/MultiQC.git
```

This is a short term fix only though, as this fork is outside of the main MultiQC development and will not get other updates. So consider it a band-aid patch only for now.

**Comment by hsaxe** [comment]
Thank you!
