### ISSUE TITLE
Use Click envvars for CLI options / env var templating in config

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#1899]
Should use `auto_envvar_prefix` from Click in the command line inferface ([docs](https://click.palletsprojects.com/en/8.1.x/options/#values-from-environment-variables)).

This would make all CLI options settable via exporting environment variables.

For example, instead of:

```bash
multiqc . --title example
```

You could do:

```bash
export MULTIQC_TITLE="example"
multiqc .
```

Could be nice for people running in automated environments / pipelines.

**Comment by jchorl** [comment]
This is a great start. It certainly allows dynamism. I think it would be well paired with string-templating. I'm envisioning:
```yaml
report_header_info:
  - Contact E-mail: "${MULTIQC_CONTACT_EMAIL}"
 ```

Of course, this adds a bunch of complexity. I suppose this would be an easier start:
```
MULTIQC_REPORT_HEADER_INFO='
  - Contact E-mail: "foo@example.com"
'
```

But then you're mixing config between cli/yaml/env-vars, instead of _only_ using env-vars for the template values and leaving the config to yaml.

**Comment by ewels** [comment]
Ok cool, thanks for the example - I understand now what you meant about string-templating 👍🏻 

I'm _slightly_ nervous about blindly replacing things that look like env vars across all config parsing, but it could be done.

What about using a [syntax like mkdocs](https://www.mkdocs.org/user-guide/configuration/#environment-variables)?

```yaml
report_header_info:
  - Contact E-mail: !ENV MULTIQC_CONTACT_EMAIL
```

or with a default:

```yaml
report_header_info:
  - Contact E-mail: !ENV [MULTIQC_CONTACT_EMAIL, "default@email.com"]
```

Same concept, but the `!ENV` prefix is a little more explicit and less likely to have off-target instances.

**Comment by ewels** [comment]
Ahh, I love Python. Someone has already made a library to handle this syntax: https://github.com/mkaranasou/pyaml_env

Also gives a nicer syntax for defaults, and the ability to handle string interpolation:

```yaml
report_header_info:
  - Contact E-mail: !ENV "${NAME:info}@${DOMAIN:example.com}"
```
