### ISSUE TITLE
not presenting STAR graph and including snippy while not doing analysis 

### ISSUE THREAD

**Issue by Mahnaz-Shemirani** [ewels/MultiQC#1916]
### Description of bug

I did MultiQC for my results including FastQC, sortmenrna, salmon, trimmomatic and STAR. The MultiQC report consists of Snippy, Salmon, STAR, FastQC. The report does not show graph for Snippy and STAR. 

FIRST, I did not have any analysis with Snippy, while it is included in the result. Also I have error message about not showing the graph.
(Snippy
[Snippy](https://github.com/tseemann/snippy) is used for rapid haploid variant calling and core genome alignment.

Snippy Variants
This plot shows the different variant types reported by snippy.

Error - was not able to plot data.)

SECOND, The STAR report has a error message about not showing the graph. 

(STAR
[STAR](https://github.com/alexdobin/STAR) is an ultrafast universal RNA-seq aligner.

Alignment Scores
Error - was not able to plot data.)

THIRD, the trimmomatic resutls are not included.   

How can I solve this problem?

### File that triggers the error

[NETseqNP1_EKDL220016460-1A_HJHHTDSX5_L1_sortmerna_trimmomatic_zero_primers_2.fq_STAR.zip](https://github.com/ewels/MultiQC/files/11331706/NETseqNP1_EKDL220016460-1A_HJHHTDSX5_L1_sortmerna_trimmomatic_zero_primers_2.fq_STAR.zip)

### MultiQC Error log

```console
Command:
#!/bin/bash -l
# safe
set -eu

# vars
in=/mnt/picea/home/mshemirani/Git/NETseq_spruce/results/final_result
out=$in/multiqc
singularity=$(realpath ../singularity/kogia/multiqc_1.11.sif)
proj=u2021014
email=mahnaz.irani-shemirani@umu.se

# setup
[[ ! -d $out ]] && mkdir $out

# env
export SINGULARITY_BINDPATH="/mnt:/mnt"

# run
sbatch -w franklin -A $proj --mail-user=$email -e $out.err -o $out.out runMultiQC.sh $singularity $in $out



Log:
+ source /mnt/picea/home/mshemirani/Git/NETseq_spruce/pipeline/../UPSCb-common/src/bash/functions.sh
++ basename /tmp/slurmd/job486090/slurm_script
+ USAGETXT='
Usage: slurm_script <singularity container> <analysis directory> <output directory>
'
+ [[ 3 -ne 3 ]]
+ [[ ! -f /mnt/picea/storage/singularity/kogia/multiqc_1.11.sif ]]
+ [[ -z /mnt:/mnt ]]
+ [[ ! -d /mnt/picea/home/mshemirani/Git/NETseq_spruce/results/final_result ]]
+ [[ ! -d /mnt/picea/home/mshemirani/Git/NETseq_spruce/results/final_result/multiqc ]]
+ singularity exec /mnt/picea/storage/singularity/kogia/multiqc_1.11.sif multiqc -o /mnt/picea/home/mshemirani/Git/NETseq_spruce/results/final_result/multiqc /mnt/picea/home/mshemirani/Git/NETseq_spruce/results/final_result

  /// MultiQC 🔍 | v1.11

|           multiqc | MultiQC Version v1.14 now available!
|           multiqc | Search path : /mnt/picea/home/mshemirani/Git/NETseq_spruce/results/final_result
|            snippy | Found 2 reports
|          bargraph | Tried to make bar plot, but had no data
|            salmon | Found 7 meta reports
|            salmon | Found 7 fragment length distributions
|              star | Found 7 reports
|          bargraph | Tried to make bar plot, but had no data
|         sortmerna | Found 14 logs
|            fastqc | Found 66 reports
|           multiqc | Compressing plot data
|           multiqc | Previous MultiQC output found! Adjusting filenames..
|           multiqc | Use -f or --force to overwrite existing reports instead
|           multiqc | Report      : ../results/final_result/multiqc/multiqc_report_4.html
|           multiqc | Data        : ../results/final_result/multiqc/multiqc_data_4
|           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/#troubleshooting-1).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by ewels** [comment]
Hi @Mahnaz-Shemirani,

You appear to have attached the raw data (CRAM file). I need the log outputs from the tools you ran to be able to replicate any errors. For example, something like [this](https://github.com/ewels/MultiQC_TestData/blob/master/data/ngi/data/STAR/P1234_1001Log.final.out) for STAR.

Please attach all log files needed to reproduce the problem, without these I can't really help. You can test yourself by putting them in a folder and running MultiQC - then zip that directory and attach it to the issue.

Note that you've ticked the _I am using the latest release of MultiQC._ checkbox, but your log output shows that you're running v1.11 of MultiQC which is over 2 years old. Please try updating as you may find this resolves your problems.

Phil

**Comment by ewels** [comment]
Closing as no response.
