### ISSUE TITLE
Remove pre-Python 3.6 style code

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#1919]
The MultiQC code base has a bunch of stuff written for Python 2 that we no longer need. We should modernise this for a cleaner, more readable, better code strucutre.

Examples, but not limited to:

- [x] Using `OrderedDict`s everywhere when we don't need to
- [x] `__future__` statements
- [x] `encode` and other pre-unicode hacks
- [x]  Format strings (run `flynt`)
- ...

**Comment by vladsavelyev** [comment]
I think those creeping back shouldn't happen often, and we can handle that manually when reviewing the old PRs. If it becomes a problem, I'd add a check.
