### ISSUE TITLE
Installation on Macbook M2

### ISSUE THREAD

**Issue by dwill023** [ewels/MultiQC#1923]
### Description of bug

Hi, I've tried to install on my apple macbook M2 using:
`conda install multiqc`
But run into the issue:
```
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - multiqc -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|3.4.*']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your system:

  - feature:/osx-arm64::__osx==13.3.1=0
  - multiqc -> git -> __osx[version='>=10.9']

Your installed version is: 13.3.1
```

The python version in my environment is 3.8 which should be satisfied but I'm not sure about the other incompatibility. I've been able to install other packages in this environment. My git version 2.39.2 (Apple Git-143).

Please advise, thanks.

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/#troubleshooting-1).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by ewels** [comment]
I suspect it's [this](https://multiqc.info/docs/getting_started/installation/#conda-1):

> The order of conda channels is important. Do not use `-c bioconda` in the installation command, weird stuff can happen (like only being able to install very old versions).

You're not using `-c bioconda`, but do you have your conda channels set up in the [correct order](https://bioconda.github.io/#usage)?

```bash
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
conda config --set channel_priority strict
```

As is often the case with conda, the error message is likely garbage. I run on an Macbook M1, using Python 3.8 - 3.11 with no problems. If you still have issues, you can try using [mamba](https://mamba.readthedocs.io/en/latest/index.html) instead which can give you more info about what's wrong.

**Comment by dwill023** [comment]
Thanks! I managed to install it with mamba. I deleted my anaconda and installed [Mambaforge](https://github.com/conda-forge/miniforge#mambaforge) instead.
