### ISSUE TITLE
error in UMI-tools module, invalid literal for int()

### ISSUE THREAD

**Issue by BenvanderVeer** [ewels/MultiQC#1929]
### Description of bug

I am trying to use MultiQC to analyze the amount of PCR duplicates that were removed with UMI-tools. I have attached the log from UMI-tools that I am trying to parse.

### File that triggers the error

[RRBS3_TP42.1_HET_M_3ppm_norm.deduplication.txt](https://github.com/ewels/MultiQC/files/11565062/RRBS3_TP42.1_HET_M_3ppm_norm.deduplication.txt)

### MultiQC Error log

```console
/// MultiQC 🔍 | v1.14

|           multiqc | Report title: RRBS deduplication and methyl quantification pipeline
|           multiqc | Search path : /staging/leuven/stg_00072/Ben/Tet1_NTD/FA/RRBS/deduplication
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 36/36
╭────────────── Oops! The 'umitools' MultiQC module broke... ──────────────╮
│ Please copy this log and report it at                                    │
│ https://github.com/ewels/MultiQC/issues                                  │
│ Please attach a file that triggers the error. The last file found was:   │
│ /staging/leuven/stg_00072/Ben/Tet1_NTD/FA/RRBS/deduplication/RRBS3_TP42. │
│ 1_HET_M_3ppm_norm.deduplication.log                                      │
│                                                                          │
│ Traceback (most recent call last):                                       │
│   File "/data/leuven/328/vsc32808/miniconda/envs/BSseq/lib/python3.7/sit │
│     output = mod()                                                       │
│   File "/data/leuven/328/vsc32808/miniconda/envs/BSseq/lib/python3.7/sit │
│     input_fname, data = self.parse_logs(f["f"])                          │
│   File "/data/leuven/328/vsc32808/miniconda/envs/BSseq/lib/python3.7/sit │
│     logdata[key] = value[1](line.partition(value[0])[2])                 │
│ ValueError: invalid literal for int() with base 10: '461533, Read pairs: │
│                                                                          │
╰──────────────────────────────────────────────────────────────────────────╯
|           multiqc | No analysis results found. Cleaning up..
|           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/#troubleshooting-1).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by pontushojer** [comment]
The UMI-tools module has been updated since `v1.14`, see https://github.com/ewels/MultiQC/commit/055b728ac894eef42d73dbdec37714a28c4a2578. Try and run the samples using the development version of MultiQC. Use the command below:

```
pip install --upgrade --force-reinstall git+https://github.com/ewels/MultiQC.git
```

**Comment by ewels** [comment]
Thanks @pontushojer 🙏🏻 Closing under the assumption that this is already fixed, let me know if that's not the case and we can reopen.

Apologies for the delay in releasing. I haven't forgotten, I hope to be able to carve out the required time before too much longer.
