### ISSUE TITLE
FastQC: `UnicodeDecodeError` with weird sequence characters

### ISSUE THREAD

**Issue by DaRoemer** [ewels/MultiQC#1941]
### Description of bug

I tried to use multiqc in windows and in ubuntu wsl2 on my data generated with FastQC. See one example file. I tried `export PYTHONIOENCODING=utf-8` but it didn't work...
Also tried to solve it in windows. In both cases a example data works without problems
Do you have a idea what the problem might be?

I get the error:
[run1_2_fastqc.zip](https://github.com/ewels/MultiQC/files/11789298/run1_2_fastqc.zip)

### File that triggers the error

[outfiles.zip](https://github.com/ewels/MultiQC/files/11789315/outfiles.zip)

### MultiQC Error log

```console
$ multiqc .
  /// MultiQC 🔍 | v1.14

←[34m|           multiqc←[0m | Search path : C:\Users\felix_9ny56v1\.01Felix\01_Studium\02_Master\Semester_2\Grundlagen_der_Bioinformatik\Assignments\A07\FastQCreport
|         searching | ---------------------------------------- 100% 12/12
┌──────────────────────────────────── Oops! The 'fastqc' MultiQC module broke... ─────────────────────────────────────┐
│ Please copy this log and report it at https://github.com/ewels/MultiQC/issues                                       │
│ Please attach a file that triggers the error. The last file found was: .\run1_1_fastqc.zip                          │
│                                                                                                                     │
│ Traceback (most recent call last):                                                                                  │
│   File "C:\Users\felix_9ny56v1\AppData\Local\Programs\Python\Python310\lib\site-packages\multiqc\multiqc.py", line  │
│     output = mod()                                                                                                  │
│   File "C:\Users\felix_9ny56v1\AppData\Local\Programs\Python\Python310\lib\site-packages\multiqc\modules\fastqc\fas │
│     r_data = fh.read().decode("utf8")                                                                               │
│ UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 5991: invalid continuation byte                │
│                                                                                                                     │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
←[34m|           multiqc←[0m | ←[33mNo analysis results found. Cleaning up..←[0m
←[34m|           multiqc←[0m | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/#troubleshooting-1).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by ewels** [comment]
Ooh, this is a good one! Replicated locally.

I guess that it's something to do with these particularly exciting overrepresented sequences:
<img src="https://github.com/ewels/MultiQC/assets/465550/7ce007f4-c0e7-4d3a-a678-56ae90482057" height=400>


```
 274   │ >>Overrepresented sequences fail
 275   │ #Sequence   Count   Percentage  Possible Source
 276   │ NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN  3   10.0    No Hit
 277   │ TGTT��CTG��^BCCGCACG�3γA���A�T�^TSSEѽC��CC�GWGGGC    1   3.3333333333333335  No Hit
 278   │ CGGTT�AG���GC�ZASSG�CA��^O�?�GTL�Z��SSTQT��~AG^WT3333333333333335  No Hit
 279   │ NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNTNNNNNNN  1   3.3333333333333335  No Hit
 280   │ ATT?��]C�C��GTQC��~A�^W�ATTACAAA�^BG�CCAATT3�C�G�T    1   3.3333333333333335  No Hit
 281   │ GCAT�^TTEAT�CTACǙWCGA}C�T^G��T�C�GAWT>AAG�T�G��GC�  1   3.3333333333333335  No Hit
```

I guess that there's probably something wrong with your data here, but either way - the module shouldn't do a hard crash. We should add in an exception catch to survive this.

**Comment by vladsavelyev** [comment]
Thanks for reporting this issue!

FastQC is a bit annoying with its quality code potentially taking an uncontrolled character code space. Added a fallback to parsing into a 8-bit encoding to make sure it works well with any codes https://github.com/ewels/MultiQC/pull/2024, and also making sure it would gracefully fail even if that fallback doesn't work for some reason.
