### ISSUE TITLE
Option to error out if a requested module was not used

### ISSUE THREAD

**Issue by LukaP-BB** [ewels/MultiQC#1948]
### Description of feature

Let's say I call `multiqc ... -m bcl2fastq -m interop -m fastp`
If no log file for the interop module are found, then it will be silently ignored and a report will be generated with fastp and fastqc.
Ideally, I would want multiqc to exit with an error similar to `No log file found for requested module 'interop'`.
Using multiqc  1.14, I could not find an option to trigger this behaviour.

Many thanks for this otherwise great tool, 
Cheers

**Comment by ewels** [comment]
Interesting idea! I think you're the first to ever request it.

I'm not keen on changing the behaviour in the way you suggest, as I think it will break a lot of people's workflows. However, adding in a new config / flag to do this could be interesting.

The easiest would be `--required bcl2fastq` and so on. It'd make for a long command is the only problem, as every module would need to be typed first.

Alternatively we could have `-m bcl2fastq --require_logs` where `--require_logs` insists that everything specified on the command line with `-m` finds something 🤔  This could probably then be combined with a new config file attribute where a list of required modules could be supplied.

**Comment by LukaP-BB** [comment]
Hi ! Thanks for your answer, the `--require_logs` flag would also be a perfectly fine option.

Just to add a bit of context, I want my workflows to be as predictable as possible and error out when something is unexpected. By using Snakemake, I'm accustomed to errors if some outputs are missing, and I consider that a module that was explicitly asked on the command line to be very similar to an output file :smile: 

Bests

**Comment by ewels** [comment]
Yup, let's go for the second implementation then: `--require-logs`. Agree that it's most user friendly and hopefully intuitive.
