### ISSUE TITLE
preseq gc_extrap module

### ISSUE THREAD

**Issue by avilella** [ewels/MultiQC#195]
## preseq gc_extrap

http://smithlabresearch.org/software/preseq/

Checklist of requirements:
- Similar to the preseq lc_extrap curve plots, there is a preseq gc_extrap module which produces a 2-column txt file: 

```
TOTAL_BASES     EXPECTED_DISTINCT
0       0
10000000.0      9668880.0
20000000.0      19156570.0
30000000.0      28533190.0
[...]
```

- [x] Log files 

https://github.com/ewels/MultiQC_TestData/pull/5/commits/f7c388a4f82ca380c201f5cb31f55511066d63b0
- [ ] Any standard log file naming patterns to get sample name (eg. `sample_name.processed.log`)
Log and err files are empty.
- [ ] Say which value is most important, to go into the General Stats table
- [x] Specify what should be plotted, if anything

- Similar to the preseq lc_extrap curve plots, but for preseq gc_extrap. TOTAL_BASES instead of TOTAL_READS.

**Comment by ewels** [comment]
Looks good, thanks! I'll probably just update the preseq module to recognise both formats if that's ok. Maybe change the graph axis labels as well.

**Comment by ewels** [comment]
Hah, the scale is a little different - I thought it had broken it for the other samples, but I just needed to zoom in.

Seems to be working anyway..
