### ISSUE TITLE
Missing Dragen qc coverage metrics 

### ISSUE THREAD

**Issue by fsharifi** [ewels/MultiQC#1952]
### Description of bug

Hello! 

I installed Multiqc V1.15.dev0 on 2/24/2023, and when I run it with qc-coverage-region-1_coverage_metrics.csv as input, I get these values in the json file under multiqc_general_stat: 

"DRAGEN coverage_mqc-generalstats-dragen_coverage-Aligned_reads_in_QC_coverage_region_pct"
"DRAGEN coverage_mqc-generalstats-dragen_coverage-Aligned_bases_in_QC_coverage_region_pct"
"DRAGEN coverage_mqc-generalstats-dragen_coverage-Average_alignment_coverage_over_QC_coverage_region"
 "DRAGEN coverage_mqc-generalstats-dragen_coverage-Uniformity_of_coverage_PCT_0_2_mean_over_QC_coverage_region" 
"DRAGEN coverage_mqc-generalstats-dragen_coverage-Mean_Median_autosomal_coverage_ratio_over_QC_coverage_region" 
                
Recently, I downloaded Multiqc V1.15.dev0 on a different computer, and from the qc-coverage-region-1_coverage_metrics file I'm only getting this one value in the json file under multiqc_general_stat: 
 
DRAGEN coverage_mqc-generalstats-dragen_coverage-qc_coverage_region_1_average_alignment_coverage_over_qc_coverage_region

In both cases I can see all those metrics (e.g. Uniformity of coverage (PCT > 0.2*mean) over QC coverage region) in the json file as dragen_qc_region_1_coverage_metrics. However, when I use TidyMultiqc to convert to csv, none of them show up in the csv output. I'm under the impression that TidyMultiqc only outputs the multiqc_general_stat values.

When I use the 2/24/2023 version on all Dragen metrics (13 files), I get a csv file with 243 columns, when I use the latest version of V1.15.dev0 I'm only getting 173 columns. 
 
A comparison between  /opt/conda/lib/python3.9/site-packages/multiqc/ in the two system is attached. 

### File that triggers the error

[diff-all.txt](https://github.com/ewels/MultiQC/files/12031252/diff-all.txt)

### MultiQC Error log

```console
multiqc .

  /// MultiQC 🔍 | v1.15.dev0

|           multiqc | Search path : /work_dir/
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 13/13  
|            dragen | Found 4 reports
|     dragen_fastqc | Found 1 reports
|           multiqc | Existing reports found, adding suffix to filenames. Use '--force' to overwrite.
|           multiqc | Report      : multiqc_report.html
|           multiqc | Data        : multiqc_data
|           multiqc | Flat-image plots used. Disable with '--interactive'. See docs.
|           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/#troubleshooting-1).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by Just-Roma** [comment]
Hi @fsharifi, the coverage_metrics.py module was rewritten recently. 
The new version only includes the "average alignment coverage over region" in the gen stats table by default, as you have noticed. Hence there are fewer metrics in total.

If you wish to have other metrics in the gen stats table, then you can adjust the "METRICS" global var in the 
dragen/coverage_metrics.py, which defines metrics' configurations. Just set the "exclude" config to False for 
metrics you want to see in the common table. After that reinstall multiqc.

I dont know what tidymultiqc is, so can not say anything about it.

**Comment by fsharifi** [comment]
Thank you so much for your prompt response! I set exclude to None and was able to get all the variables 👍
