### ISSUE TITLE
Issue with the Multiqc path

### ISSUE THREAD

**Issue by JyotsanaMehra** [ewels/MultiQC#1957]
I have integrated the multiqc process in nextflow nf script. In the cmd I have provided the absolute path where the multiqc tool has been installed, still I am getting the error saying 

Command error:
  .command.sh: line 2: /usr/local/bin/multiqc: No such file or directory

  and when I have tried running " /usr/local/bin/multiqc", the tool is working fine

<img width="939" alt="multiqc" src="https://github.com/ewels/MultiQC/assets/45169074/382d01fb-659b-4465-98ee-3fc3b1daf6f8">

**Comment by ewels** [comment]
Hi @JyotsanaMehra,

Using an absolute path for a tool in a Nextflow pipeline is generally a bad idea. Nextflow has built-in support for managing software dependencies using conda / docker / singularity / more. Using these approaches is generally much safer, more reproducible and makes your pipeline more portable between different systems.

It's extremely difficult to help with your issue based on what you've written, and it's not really anything to do with MultiQC itself but rather your Nextflow pipeline. As such, I'll close this issue now. If you need help with your Nextflow pipeline, I'd recommend our [Nextflow training material](https://training.nextflow.io/) (with [online videos](https://www.youtube.com/@nf-core/playlists?view=50&sort=dd&shelf_id=2)) and asking for help in the [Nextflow community Slack](https://www.nextflow.io/slack-invite.html).

Phil
