### ISSUE TITLE
Add `hidden` columns in general stats table

### ISSUE THREAD

**Issue by dakl** [ewels/MultiQC#197]
I'd like to be able for tools to add columns to the general stats table in a hidden state that users can show as needed. This way, the default general stats table remains relatively condensed, but additional data which is currently not shown (ex percent bases on target and mean bait coverage from picard hsmetrics) can be added if users wants to show it. 

One possible addition could be to have the default column states settable in a config file so users can change their own defaults.

**Comment by ewels** [comment]
Ok, this is now done and seems to be working! See updated docs [here](http://multiqc.info/docs/#step-4-adding-to-the-general-statistics-table). Basically just add `'hidden': True` to the header config though:

```python
headers['hidden_column'] = {
    'title': 'Hidden',
    'description': 'This column is hidden on page load',
    'hidden': True
}
```

Let me know how you get on with it @dakl!

Would be easy to add code to enable this to be overwritten by a user's config. But I'm not sure how easy it would be for users to get the column ID that they need / whether anyone would ever actually do it? I guess you think it's worth adding anyway? ;)
