### ISSUE TITLE
Reproduce samtools idxstats XY counts plot for Mosdepth module.

### ISSUE THREAD

**Issue by SpikyClip** [ewels/MultiQC#1978]
### Description of feature

![image](https://github.com/ewels/MultiQC/assets/74215773/a5368cf3-7417-4911-ac65-88635b60fdfe)

Hi,

I was wondering if it is possible to reproduce the XY counts plot used in the samtools idxstats multiqc module as an output of the mosdepth module as another means of sex QC. I currently use the `Average coverage per contig` mosdepth plot to do so in the `sarek`, however, it is very noisy and `sarek` does not run `samtools idxstats`:

![image](https://github.com/ewels/MultiQC/assets/74215773/031922e7-49f9-4940-85f2-33aef839ed69)

If there was another output of the mosdepth module that showed the average converage per contig for just X and Y chromosomes as a horizontal bar plot that would be pretty useful.

Here is the original issue where this feature was added to the samtools idxstats module:
https://github.com/ewels/MultiQC/issues/251#issuecomment-242232484

**Comment by vladsavelyev** [comment]
@SpikyClip, thanks for the request! I think we can add it, and also it would be a good opportunity to borrow some other features from the samtools module to make the mosdepth per-contig a bit cleaner (e.g. skip chromosomes).

Created a PR: https://github.com/ewels/MultiQC/pull/1982
