### ISSUE TITLE
highlighting of General Statistics dots

### ISSUE THREAD

**Issue by avilella** [ewels/MultiQC#199]
Is the highlighting of the dots in General Statistics supposed to change colours?

See screenshot...
<img width="1345" alt="screen shot 2016-05-05 at 08 21 04" src="https://cloud.githubusercontent.com/assets/158007/15038312/8df33d02-129a-11e6-9c90-35b3509b36af.png">

**Comment by ewels** [comment]
Supposed to, not written yet. See #194
