### ISSUE TITLE
[Question]: How to customize "group column name" for "Bcftools Stats"

### ISSUE THREAD

**Issue by tamuanand** [ewels/MultiQC#2032]
Hi

Given below is a snippet from my multiqc_config.yaml  

When I run MultiQC (1.15), the general stats table shows SAMTools (after Recalibrate) in the Group column, but does not show the same for BCFTools (pre-Normalization) or for BCFTools (post-Normalization) - screenshot attached. 

Do I have to do anything different for bcftools? Thanks in advance.
```yaml
- samtools:
    name: 'SAMTools (after Recalibrate)'
    info: 'This section of the report shows SAMTools results after Recalibrate'
    path_filters:
        - '*samtools_recalibrated*'
- bcftools:
    name: 'BCFTools (pre-Normalization)'
    info: 'This section of the report shows BCFTools results before normalization'
    path_filters:
        - '*bcftools_raw*'
- bcftools:
    name: 'BCFTools (post-Normalization)'
    info: 'This section of the report shows BCFTools after normalization'
    path_filters:
        - '*bcftools_normalized*'
 ```

![image](https://github.com/ewels/MultiQC/assets/8467214/b998a810-23e8-4259-a8c8-7a650ebd02e7)

**Comment by vladsavelyev** [comment]
While we are working on a bore robust solution, I added a quick fix that works for bcftools: https://github.com/ewels/MultiQC/pull/2043

**Comment by tamuanand** [comment]
Thanks a lot @vladsavelyev
