### ISSUE TITLE
Drop official support for Python 3.7

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#2039]
Python 3.7 hit EOL (end of life) in June: https://endoflife.date/python

I'm not aware of any 3.7-specific language constructs that we're specifically maintaining, but it might be nice to drop official support (CI) anyway to try to encourage users to update.

**Comment by ewels** [comment]
This needs updating in the CI, the docs, and also in the version check:
https://github.com/ewels/MultiQC/blob/f4878540c0b1e77fa419b589ec33f3a5039d17da/multiqc/multiqc.py#L477-L484

**Comment by vladsavelyev** [comment]
If we drop 3.7 support, it would simplify https://github.com/ewels/MultiQC/pull/2113 (we would be able to use `shutil.copytree(..., dirs_exist_ok=True)` introduced in 3.8).

However, we are still supporting even 3.6. I'd go with dropping both 3.6 and 3.7 in 1.17.

**Comment by ewels** [comment]
Done in https://github.com/ewels/MultiQC/pull/2121 but looks like we missed that `multiqc.py` mention..
