### ISSUE TITLE
Possible problem updating module search pattern?

### ISSUE THREAD

**Issue by lweasel** [ewels/MultiQC#208]
Hi,

Firstly, great tool - many thanks for providing it! 

I may well be doing something wrong here, but I'm trying to change the search pattern for the STAR module to match my local processing pipeline (using multiqc version 0.6). I'm using a config file with the following contents:

```
sp:
    star:
        fn: '*.log.out'
```

When I do this, I get the following error message:

```
Config error: 'dict' object has no attribute 'extend'
```

Although multiqc then continues and completes, the new search pattern isn't taken into account.

I was able to work around this by changing line 158 of MultiQC/multiqc/utils/config.py (@ a258c425cfff32f2b68a264b77170ba13f43c764) from:

```
sp.extend(v)
```

to

```
sp.update(v)
```

(although I also had to change the "if" statement on line 160 to an "elsif", or else the whole "sp" dictionary was overwritten on line 166?).

**Comment by ewels** [comment]
Hi @lweasel,

Thanks for the report - yes, definitely something funky going on in this bit of code.

Interestingly, when I [first wrote this code](https://github.com/ewels/MultiQC/commit/1f007e5322f5b31e894805d07cd2f743e8d887f3) I used `sp.update(v)`, then I later "fixed" it by [changing it to](https://github.com/ewels/MultiQC/commit/a0adcd1eb88574f576a881c0f8da8eb921166db3) `sp.extend(v)` instead. I suspect that what's going on here is that I've been treating the config variables `sp` and `fn_clean_exts` as equivalent and only testing one at a time (also evident by missing `elif`), but `sp` is a `dict` and `fn_clean_exts` is a list.

Ok, cleared up the "why" in my head now. Yes, your fixes sound like they should do the job. Do you want to submit a PR or are you happy for me to copy your edits?

Phil

**Comment by lweasel** [comment]
Hi Phil - more than happy for you to copy the edits if that's the easiest for you.

Cheers,
Owen

**Comment by ewels** [comment]
Ok, that's done. Let me know if you run into any problems with it, and thanks again!
