### ISSUE TITLE
whatshap: truncated stats file gives `KeyError`

### ISSUE THREAD

**Issue by splaisan** [ewels/MultiQC#2093]
### Description of bug

multiqc (1.14) of truncated whatshap results (head command retaining only the 23 first lines and removing all unplaced contig lines that came after that.

The inputs are attached for reproducibility

### File that triggers the error

[input.zip](https://github.com/ewels/MultiQC/files/12766475/input.zip)

### MultiQC Error log

```console
$ multiqc .

  /// MultiQC 🔍 | v1.14

|           multiqc | MultiQC Version v1.16 now available!
|           multiqc | Search path : /...../main_chr
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 10/10  
╭────────────────────────────────────────────────── Oops! The 'whatshap' MultiQC module broke... ──────────────────────────────────────────────────╮
│ Please copy this log and report it at https://github.com/ewels/MultiQC/issues                                                                    │
│ Please attach a file that triggers the error. The last file found was: ./887604734_main_stats.tsv                             │
│                                                                                                                                                  │
│ Traceback (most recent call last):                                                                                                               │
│   File "/opt/miniconda3/envs/multiqc/lib/python3.11/site-packages/multiqc/multiqc.py", line 654, in run                                          │
│     output = mod()                                                                                                                               │
│              ^^^^^                                                                                                                               │
│   File "/opt/miniconda3/envs/multiqc/lib/python3.11/site-packages/multiqc/modules/whatshap/whatshap.py", line 53, in __init__                    │
│     self.whatshap_add_general_stats()                                                                                                            │
│   File "/opt/miniconda3/envs/multiqc/lib/python3.11/site-packages/multiqc/modules/whatshap/whatshap.py", line 208, in whatshap_add_general_stats │
│     general_stats = {field: summary_data[field] for field in general_stats_headers}                                                              │
│                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                              │
│   File "/opt/miniconda3/envs/multiqc/lib/python3.11/site-packages/multiqc/modules/whatshap/whatshap.py", line 208, in <dictcomp>                 │
│     general_stats = {field: summary_data[field] for field in general_stats_headers}                                                              │
│                             ~~~~~~~~~~~~^^^^^^^                                                                                                  │
│ KeyError: 'frac_het_phased'                                                                                                                      │
│                                                                                                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
|           multiqc | No analysis results found. Cleaning up..
|           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/#troubleshooting-1).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by pontushojer** [comment]
>multiqc (1.14) of truncated whatshap results (head command retaining only the 23 first lines and removing all unplaced contig lines that came after that.

The issue here is that you are truncating the TSV files. If there are more than one chromosome in the whatshap TSV, MultiQC instead looks for the "ALL" chromosome which contains a summary values across all chromosomes. This "ALL" chromosome line appears at the bottom of the file so it has been removed in this case. 

So my suggestion would be to rerun on the full TSV. If you don't want to include some chromosomes, you could rerun `whatshap stats` with the option `--chromosome` to specify which chromosomes you are interested in. In you case something like: 

```bash
whatshap stats --chromosome chr1,chr2,...,chrX,MT --tsv my.stats.tsv my.vcf.gz 
```

We should however add a change to catch truncated `whatshap stats` files, maybe raising a debug message in that case.

**Comment by ewels** [comment]
> We should however add a change to catch truncated whatshap stats files, maybe raising a debug message in that case.

Agree 👍🏻 

And maybe add a note to the module readme..? (but maybe not, this seems like a bit of an edge case)

**Comment by splaisan** [comment]
I feel like a wierdo now 🤣

**Comment by splaisan** [comment]
I re-ran the whatshap as advised and it ran well as well as was processed by multiQC but I get a weird behaviour for one of the plots where NG50 is 0 for an entire group of samples (last 10) while all the other the metrics for that group do not differ that much from the other group (also 10 of which only few shown below).

Can you please explain why we get those 0?

I cannot share here the whole data as confidential labels are present but I can send them to you privately if needed.

![Screenshot 2023-10-02 at 09 02 31](https://github.com/ewels/MultiQC/assets/858516/704ab8b5-712b-49c6-991a-86b3e3ed22e7)

![Screenshot 2023-10-02 at 09 02 19](https://github.com/ewels/MultiQC/assets/858516/e152fff6-aeec-45f7-85f6-1cf02e2abd90)

**Comment by vladsavelyev** [comment]
I added support for truncated inputs nevertheless: https://github.com/ewels/MultiQC/pull/2095
MultiQC will summarise all available chromosomes as a fictional ALL chromosome.
