### ISSUE TITLE
Multiqc analysis report error 

### ISSUE THREAD

**Issue by aqsakhalid03** [ewels/MultiQC#2100]
### Description of bug

I have multiqc installed but when i am trying to generate output it gives me error. Although it reads fastq.gz files but does not produce analysis results. 

### MultiQC Error log

```console
multiqc /home/aqsakhalid/Documents/UWARN-SARSCoV2-DATA/library4

  /// MultiQC 🔍 | v1.14

|           multiqc | MultiQC Version v1.16 now available!
|           multiqc | Search path : /home/aqsakhalid/Documents/library4
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 140/140  
|           multiqc | No analysis results found. Cleaning up..
|           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/#troubleshooting-1).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by ewels** [comment]
From the [docs](https://multiqc.info/docs/):

![CleanShot 2023-10-04 at 10 45 08@2x](https://github.com/ewels/MultiQC/assets/465550/64a3f5a6-ab7e-46cd-a5ac-55c97cfbdedc)

MultiQC doesn't do anything with FastQ files. You need to run an analysis with one of the [supported tools](https://multiqc.info/modules/) first.
