### ISSUE TITLE
Columns unsorted in data exported from matplotlib linegraph with `--data-format tsv --export`

### ISSUE THREAD

**Issue by NicoleGruenheit** [ewels/MultiQC#2140]
### Description of bug

Hi,

I use MultiQC 1.17 with parameters --data-format tsv --export. Usually, the file mqc_dragenqc_per_sequence_quality_scores_plot_1.txt contains one column per position order from start of the read to the end. Now the header line doesn't make sense, as I have values like 591 for a 150 bp read. Also, the columns are not sorted, this makes it impossible to determine which column belongs to which position in the read. 

This was definitely not the case in version 1.15.

Cheers,
Nicole

### File that triggers the error

[test_multiQC.txt](https://github.com/ewels/MultiQC/files/13042890/test_multiQC.txt)
[sample.fastqc_metrics.csv](https://github.com/ewels/MultiQC/files/13042942/sample.fastqc_metrics.csv)

### MultiQC Error log

```console
docker run --rm -t -u $UID_USER:$GID_BFX -v `pwd`:`pwd` -w `pwd` ewels/multiqc:latest multiqc . -n "sample" -i "sample" -f --data-format tsv --export 

  /// MultiQC 🔍 | v1.17

|           multiqc | Report title: sample
|           multiqc | Search path : sample
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 180/180  
Matplotlib created a temporary cache directory at /tmp/matplotlib-tscqkodo because the default path (/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
|            dragen | Found 2 reports
|     dragen_fastqc | Found 1 reports
|           multiqc | Report      : sample.html   (overwritten)
|           multiqc | Data        : sample_data   (overwritten)
|           multiqc | Plots       : sample_plots   (overwritten)
|           multiqc | Flat-image plots used. Disable with '--interactive'. See docs.
|           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/#troubleshooting-1).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Thank you @NicoleGruenheit for reporting the issue!

See attempt to fix here: https://github.com/ewels/MultiQC/pull/2143

Though I'd need some more time to properly test it. Will update in the pull request!
