### ISSUE TITLE
Add support for Sentieon dedup report (similar to Picard MarkDuplicates)

### ISSUE THREAD

**Issue by mathiasbio** [ewels/MultiQC#2144]
### Name of the tool

Sentieon Dedup

### Tool homepage

https://support.sentieon.com/manual/usages/general/#dedup-algorithm

### Tool description

Works similar to Picard MarkDuplicates, marking or removing read / optical duplicates.

### Tool output

[normal.dedup.metrics.tsv.zip](https://github.com/ewels/MultiQC/files/13052813/normal.dedup.metrics.tsv.zip)

If I add:

`## METRICS CLASS        picard.sam.DuplicationMetrics`

Immediately above this line in the report:

`LIBRARY UNPAIRED_READS_EXAMINED READ_PAIRS_EXAMINED     SECONDARY_OR_SUPPLEMENTARY_RDS  UNMAPPED_READS  UNPAIRED_READ_DUPLICATES        READ_PAIR_DUPLICATES    READ_PAIR_OPTICAL_DUPLICATES    PERCENT_DUPLICATION     ESTIMATED_LIBRARY_SIZE`

Then multiqc detects and adds it to the json report, however it would be nice to avoid adding the wrong tool name to the report for traceability and reproducibility reasons.

### Data suitable for MultiQC plot(s)

As it contains the same summary-stats as picard markduplicates it would be nice of the report from this tool could mirror those from picard.
 
Currently when adding the line `## METRICS CLASS        picard.sam.DuplicationMetrics` I get this in the  multiqc_picard_dups.json report. If this could be outputted from the Sentieon Dedup report as well, that would be great! 

{
    "normal": {
        "LIBRARY": "Unknown Library",
        "UNPAIRED_READS_EXAMINED": 400299.0,
        "READ_PAIRS_EXAMINED": 440331782.0,
        "SECONDARY_OR_SUPPLEMENTARY_RDS": 3872761.0,
        "UNMAPPED_READS": 1264137.0,
        "UNPAIRED_READ_DUPLICATES": 146877.0,
        "READ_PAIR_DUPLICATES": 39145351.0,
        "READ_PAIR_OPTICAL_DUPLICATES": 4048209.0,
        "PERCENT_DUPLICATION": 0.089026,
        "ESTIMATED_LIBRARY_SIZE": 2564198488.0
    },
    "tumor": {
        "LIBRARY": "Unknown Library",
        "UNPAIRED_READS_EXAMINED": 193170.0,
        "READ_PAIRS_EXAMINED": 325237198.0,
        "SECONDARY_OR_SUPPLEMENTARY_RDS": 3163125.0,
        "UNMAPPED_READS": 747098.0,
        "UNPAIRED_READ_DUPLICATES": 71991.0,
        "READ_PAIR_DUPLICATES": 39186710.0,
        "READ_PAIR_OPTICAL_DUPLICATES": 3746726.0,
        "PERCENT_DUPLICATION": 0.120561,
        "ESTIMATED_LIBRARY_SIZE": 1348927846.0
    }
}

### Most interesting data for the General Stats table

READ_PAIR_DUPLICATES  (perhaps represented as % instead)
READ_PAIR_OPTICAL_DUPLICATES (perhaps represented as % instead)
PERCENT_DUPLICATION (primarily this, as for mark duplicates)

### Before submitting

- [X] I have included example data (zipped, not pasted) that can be used to write the module.

**Comment by vladsavelyev** [comment]
Thank you for creating the issue! 

This is to be resolved with, once merged :) https://github.com/ewels/MultiQC/pull/2110

**Comment by mathiasbio** [comment]
Oh great! Thanks! I'll keep an eye open for the new release : )

**Comment by vladsavelyev** [comment]
Alright, so this is addressed this by supporting Sentieon by the Picard module directly (so we can easier expand it to other Sentieon QC tools matching corresponding Picard tools): https://github.com/ewels/MultiQC/pull/2110. Hope that works!

A new MultiQC version will be released on Friday :)
