### ISSUE TITLE
maximum file size to parse option

### ISSUE THREAD

**Issue by avilella** [ewels/MultiQC#218]
I remember having seen somewhere that there is an option in a config file relating to the maximum file size threshold for MultiQC to attempt to parse that file or not.

Where is this config file in the recent version? Can this option be passed-through to the main command-line call?

My user case that I want to simplify is the following:
- I have a project folder with lots of files, some of which I want MultiQC to parse.
- I create a cloud instance where I look through the project folder and I need to decide which files I copy to the instance, so that they are visible for the next step, which is running MultiQC. I only want to download the files that MultiQC will parse. If they are too big, I don't want to download them in the first place.
- MultiQC will then run from the command-line in the cloud instance that has the files downloaded. All the files downloaded will be run with multiqc --max-file-size NNN (or with a config containing that option) to match up the steps above.

Thx

**Comment by ewels** [comment]
(Nearly?) all of the config parameters can be found in the [example config file](https://github.com/ewels/MultiQC/blob/master/multiqc_config_example.yaml#L58-L59). The one you're looking for is `log_filesize_limit`.

However, I'm a little confused about why this is needed for your use case - it sounds like if the files were too big and not downloaded then they won't be there for MultiQC to find anyway? Or maybe I am misunderstanding you.

If you're interested, you can also specify the exact files that you want MultiQC to run on. Some pipelines such as bcbio do this. You can also specify a file containing a list of filenames with `-l`/`--file-list`. See the relevant part of [the docs](http://multiqc.info/docs/#choosing-where-to-scan) for more info.

Phil
