### ISSUE TITLE
Kallisto.module

### ISSUE THREAD

**Issue by darogan** [ewels/MultiQC#219]
The sample names don't match up with the correct metric in the alignment plot. If the sample names were sorted by "...RHM0NN..." or appear in the order in the general statistics table they would match up.

![mqc_hcplot_getkiusjwd_counts](https://cloud.githubusercontent.com/assets/6408578/15469120/180debce-20e0-11e6-884c-2ecdd0c3e42e.png)

**Comment by ewels** [comment]
Huh, this isn't good. After being very confused for a bit, I think I've tracked this down to a [change](https://github.com/ewels/MultiQC/blame/master/multiqc/plots/bargraph.py#L85) that I made 5 days ago. I added a dict iteration which has the nasty side-effect of randomising the order of labels in the plot. Thanks for spotting it!

Phil

**Comment by darogan** [comment]
Perfect, I just tested the update and can confirm it fixes the bug

Many thanks!

**Comment by ewels** [comment]
Great! Travis [flagged up](https://travis-ci.org/ewels/MultiQC/jobs/132293964) that my fix broke something in some cases. Fixed in 46849c0f63826939c53f43df93d8f928eb6d60f3 and [working again](https://travis-ci.org/ewels/MultiQC/builds/132299968), so probably good to do a second `git pull`. Sorry!
