### ISSUE TITLE
Dropping quast namespace broke `table_columns_visible`

### ISSUE THREAD

**Issue by jchorl** [ewels/MultiQC#2190]
### Description of bug

We used to have a config like:
```yaml
table_columns_visible:
  QUAST:
    "# misassemblies": false
```

This commit removed the quast namespace: https://github.com/ewels/MultiQC/commit/056d21d3006561f8ce31fdea53c06a8336744ad8#diff-6d91e36cef5a41720305bb1bd9f0ab612e3830d0cce62efc0933a1d982b5296dL252

We now need to specify this config as:
```yaml
table_columns_visible:
  "":
    "# misassemblies": false
```

Is this expected/desirable?

Thanks!

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Hi @jchorl,

That worked before really by accident, as we don't normally pass the `namespace` to `table.plot()` config in modules unless we want to tell apart between different submodules/subtools (like in DRAGEN and CellRanger), and QUAST was an exception.

In the future refactoring, we'll make it more flexible, but the way it is supported now is exactly as you modified it:

```py
table_columns_visible:
  "":
    "# misassemblies": false
```

I think I'll simplify the usage to:

```py
table_columns_visible:
  "# misassemblies": false
```

**Comment by vladsavelyev** [comment]
Done (see https://github.com/ewels/MultiQC/pull/2191) - now you can also use a flat config like this:

```yaml
table_columns_visible:
  "# misassemblies": false
```

The column IDs should be unique anyway :)
