### ISSUE TITLE
Qualimap module missing "percentage_aligned" after 1.16

### ISSUE THREAD

**Issue by Stikus** [ewels/MultiQC#2199]
### Description of bug

After last Qualimap module update https://github.com/ewels/MultiQC/pull/2020 behavior changed, and we lost "percentage_aligned" sections in our reports.

Looks like the reason behind it is moving `percentage_aligned `into additional `try`:
![image](https://github.com/ewels/MultiQC/assets/41360525/a532083a-1c1d-4ac7-a91b-1f16bc2d8acf)

Our report doesn't have `Globals inside` section (due to full genome analysis) and looks like `try` causing missing entire block - not only `percentage_aligned_on_target` section.

I'm not using last version (due to Python 3.8 requirement), but according to [blame](https://github.com/ewels/MultiQC/blame/master/multiqc/modules/qualimap/QM_BamQC.py) and changelogs - nothing is changed in this part.

### File that triggers the error

[genome_results.txt](https://github.com/ewels/MultiQC/files/13460209/genome_results.txt)

### MultiQC Error log

```console
$ LC_ALL=C.UTF-8 LANG=C.UTF-8 /soft/MultiQC-1.16/bin/multiqc --fullnames --outdir /outputs --filename test_full_filtered_multiqc_report.html /outputs/inputMultiQC

  /// MultiQC 🔍 | v1.16

|           multiqc | MultiQC Version v1.17 now available!
|           multiqc | Not cleaning sample names
|           multiqc | Search path : /outputs/inputMultiQC
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 5/5  
|            picard | Found 1 MarkDuplicates reports
|          samtools | Found 2 flagstat reports
|            fastqc | Found 2 reports
|           multiqc | Report      : test_full_filtered_multiqc_report.html
|           multiqc | Data        : test_full_filtered_multiqc_report_data
|           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [x] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Thanks so much for reporting the issue, and providing a test example! 
Should be fixed in https://github.com/ewels/MultiQC/pull/2207 😌  
I added you example in the test data repo: https://github.com/ewels/MultiQC_TestData/pull/308

**Comment by Stikus** [comment]
@vladsavelyev Hello, we rechecked results after 1.19 release - looks like there is one major difference in `report_saved_raw_data` section:  
![image](https://github.com/ewels/MultiQC/assets/41360525/beca9fc9-eab4-40a5-9ef3-b21796d990a3)

`general_error_rate` changed from `0.0068` to `0.6799999999999999` (100 time more) likely due to `100` multiplier in code. It this intended? In original file (attached in issue) we have:
```
>>>>>>> Mismatches and indels

    general error rate = 0.0068
    number of mismatches = 48,036
    number of insertions = 648
    mapped reads with insertion percentage = 0.78%
    number of deletions = 734
    mapped reads with deletion percentage = 0.89%
    homopolymer indels = 57.96%
```
