### ISSUE TITLE
Add support to hisat2

### ISSUE THREAD

**Issue by pgonzale60** [ewels/MultiQC#221]
Hi Phil,

[According to JHU](https://ccb.jhu.edu/software/hisat2/index.shtml) "HISAT2 is a successor to both HISAT and TopHat2". It has the option of giving a report as [report.txt](https://github.com/ewels/MultiQC/files/285343/report.txt), but I think the most clearly useful information is what it outputs to stderr: 

[hisat2_PE.txt](https://github.com/ewels/MultiQC/files/285347/hisat2_PE.txt)
[hisat2_SE.txt](https://github.com/ewels/MultiQC/files/285348/hisat2_SE.txt)

I think the most important statistic is alignment rate, although alignment % classified by pairing also would be nice.

Bests,

Pablo

**Comment by ewels** [comment]
Hi Pablo,

Thanks for the suggestion - remarkably, the two stderr outputs that you attach are identical in format to those produced by Bowtie2. So MultiQC actually already works with HISAT2, however it will label results as coming from Bowtie2.

These logs are the worst example of output that I've seen from any bioinformatics tool (I actually [wrote a blog post](http://www.tallphil.co.uk/writing-good-log-files/) on this topic yesterday). From what I can see, there is no way to distinguish these HISAT2 logs from Bowtie2. Or tell what input file they came from. Hopefully the reports that MultiQC will still be useful though - see [this example](https://github.com/ewels/MultiQC/files/285905/multiqc_report.zip) which is based on your example files.

The `report.txt` file would be much easier to parse, however I can't see any useful fields within that file (input files, alignment rates).

If you have any ideas on how to improve this situation, let me know!

Phil

**Comment by ewels** [comment]
I've asked the authors of HISAT2 whether the reporting of summary statistics can be improved. See https://github.com/infphilo/hisat2/issues/48

**Comment by pgonzale60** [comment]
That's great! Seems like it will be possible in a near future.

Also, I checked the open and closed issues of bowtie and didn't find a reason to separate each sample summary in individual tracks. Wouldn't it be easier to inspect them if they were aggregated as in the featureCounts and STAR modules?

**Comment by ewels** [comment]
Yup, fingers crossed! 👌 

When you say "separate each sample into individual tracks" - do you mean the bar plots? This is true in the example above because one is paired end and one is single end. The categories in the logs (and plots) are different, and not really comparable as I do some nasty stuff with halving the counts of individual mate alignments for PE alignments. Typically samples will be all SE or all PE, then they will be grouped into a single plot.

Phil

**Comment by pgonzale60** [comment]
Sorry, I didn't know. I promise I won't ask for a modification without trying it with a "real" example. Thanks!

Bests,
Pablo

**Comment by ewels** [comment]
hah, no problem! Better to ask :)

**Comment by ewels** [comment]
Hi @pgonzale60,

I'll close this issue until new logs are available, then we can reopen.

PHil

**Comment by ewels** [comment]
HISAT2 summary stats output now updated, see https://github.com/infphilo/hisat2/issues/48#issuecomment-305201320

Now just waiting for the release..

**Comment by pgonzale60** [comment]
Hi, Phil!

The update seems to be officially released (https://ccb.jhu.edu/software/hisat2/index.shtml). Could you please add support for the new summary?

Bests,
Pablo

**Comment by ewels** [comment]
Yup, I saw 😁  I've just installed the new version, need to do some test runs to generate some log output and then I'll see if I can write up the module. If you have any log files already generated from the new version that would be helpful!

Phil

**Comment by ewels** [comment]
ah, just re-read the release summary:

> * Implemented `--new-summary` option to output a new style of alignment summary, which is easier to parse for programming purposes.
> * Implemented `--summary-file` option to output alignment summary to a file in addition to the terminal (e.g. stderr).

So the new release still doesn't give a nice log file output by default 😞

**Comment by pgonzale60** [comment]
Yes, that's not so cool. Still, this will allow MultiQC to distinguish hisat2 from bowtie2 :)
I see you added example output from single end libraries. I attach an example of paired end output.

[examp_hisat2_newSummary-PE.txt](https://github.com/ewels/MultiQC/files/1082654/examp_hisat2_newSummary-PE.txt)

**Comment by ewels** [comment]
Great stuff, thanks!

**Comment by zmiimz** [comment]
If logs are indistinguishable, would it be not more explanatory to add the appropriate header description like “Bowtie2 / Hisat2”?

**Comment by ewels** [comment]
Yes, we could do I suppose. Do you think this is a big enough problem to warrant a change?

**Comment by zmiimz** [comment]
I think that the clarity of the MultiQC report  is worth of any change in the code.
