### ISSUE TITLE
MultiQC broke

### ISSUE THREAD

**Issue by bioinfo-withu** [ewels/MultiQC#2219]
### Description of bug

```console
[tp59565@genossh:MultiQc] $ more MultiQcFastQc.out
Tue Dec 12 01:13:07 CET 2023
[WARNING]         multiqc : MultiQC Version v1.17 now available!
[INFO   ]         multiqc : This is MultiQC v1.8
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching   : /home/genouest/tp_rna_atac_seq_m1ibisa_40888/tp59565/TP_noté/2_FastQC
[INFO   ]          fastqc : Found 51 reports
[ERROR  ]         multiqc : Oops! The 'fastqc' MultiQC module broke...
```

### File that triggers the error

```
/home/genouest/tp_rna_atac_seq_m1ibisa_40888/tp59565/TP_noté/2_FastQC/A682-A683-A691T17.R2_fastqc.zip
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Hi @bioinfo-withu, thanks for creating an issue!

Would you be able to attach the file that causing the problem? As of now, I can see your local path to `/home/genouest/tp_rna_atac_seq_m1ibisa_40888/tp59565/TP_noté/2_FastQC/A682-A683-A691T17.R2_fastqc.zip`, but not the actual file. You can drag-and-drop it into the text field when adding a comment here.

Also, note that you are using an old MultiQC version (`v1.8` as you can see in the log you pasted). If you try to update it to the latest version with the following command, will the problem go away?

```sh
pip install multiqc==1.17
```

**Comment by bioinfo-withu** [comment]
hello, i tried to update  the version but i couldn't ( error: comand pipi
not found or  conda not found) ,  and i couldn't configure python cause im
not admin. i think ther error is coming from the zip files :[WARNING]
  multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
Wed Dec 13 10:04:11 CET 2023
***@***.***:MultiQc] $ rm
/home/genouest/tp_rna_atac_seq_m1ibisa_40888/tp59565/TP_noté/2_FastQC/A682-A683-A691T2.R1_fastqc.zip
***@***.***:MultiQc] $ sbatch --cpus-per-task=8 --mem=50G -o
MultiQcFastQc.out MultiQcFastQc.sh
Submitted batch job 12369297
***@***.***:MultiQc] $ more MultiQcFastQc.out
Wed Dec 13 10:04:50 CET 2023
[WARNING]         multiqc : MultiQC Version v1.17 now available!
[INFO   ]         multiqc : This is MultiQC v1.8
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching   :
/home/genouest/tp_rna_atac_seq_m1ibisa_40888/tp59565/TP_noté/2_FastQC
[INFO   ]          fastqc : Found 32 reports
[ERROR  ]         multiqc : Oops! The 'fastqc' MultiQC module broke...
  Please copy the following traceback and report it at
https://github.com/ewels/MultiQC/issues
  If possible, please include a log file that triggers the error - the last
file found was:

/home/genouest/tp_rna_atac_seq_m1ibisa_40888/tp59565/TP_noté/2_FastQC/A682-A683-A691T15.R2_fastqc.zip.


Le mar. 12 déc. 2023 à 15:17, Vlad Savelyev ***@***.***> a
écrit :

**Comment by ewels** [comment]
Closing as this version of MultiQC is extremely old. Please see installation instructions here: https://multiqc.info/docs/getting_started/installation/

If you need help, please ask your local sysadmins or post a question on https://community.seqera.io/c/multiqc/6

Thanks!

**Comment by ewels** [comment]
I just did a quick google and I guess you're using MultiQC v1.8 because it's pre-installed on the GenOuest cluster: https://softwaremanager.genouest.org/#/MultiQC

I found some docs suggesting that you can use Conda on this system though: https://help.genouest.org/usage/cluster/#conda

So my recommended approach would be to activate conda, create and environment and install MultiQC in it. Something like this:

```bash
. /local/env/envconda.sh
conda create -p ~/multiqc multiqc
conda activate ~/multiqc
```

That should hopefully install MultiQC v1.18. Note that you will need to load conda and activate the environment each time.

Tagging @maxulysse for visibility 😉 🇫🇷 🥖
