### ISSUE TITLE
Table problems with firefox

### ISSUE THREAD

**Issue by Hammarn** [ewels/MultiQC#230]
Hi! When trying to copy tables from the MultiQC general statistics I get some wierdly formatted tables. This is when running `Firefox 45.1.0` through X11 frowarding on Uppmax. 
**Table from MultiQC report:**
![Table from MultiQC report](https://cloud.githubusercontent.com/assets/16774076/15741011/de903598-28b7-11e6-834b-0052b60f86da.png)
**Copied table in google docs:**
![Copied table](https://cloud.githubusercontent.com/assets/16774076/15741027/f8fac4fc-28b7-11e6-8f9a-363db7ea4014.png)

**Comment by avilella** [comment]
Probably due to the name of the input files given to each of the QC tools:
maybe you have two sets of bams, with two different names? Guessing...

**Comment by Hammarn** [comment]
I doubt that that is whats causing it. Even if I only use the STAR output I still end up with an incorrectly formatted table, e.g;
![screen shot 2016-06-02 at 12 06 58](https://cloud.githubusercontent.com/assets/16774076/15741627/cabc670a-28ba-11e6-880a-3ffda1ba0348.png)

![screen shot 2016-06-02 at 12 07 36](https://cloud.githubusercontent.com/assets/16774076/15741638/d3228816-28ba-11e6-9f9c-3a6e267210d0.png)

**Comment by ewels** [comment]
What version of MultiQC are you running? The firefox display bug was fixed in #213 (still the v0.7dev version).

The copying thing is harder to explain, I'll look into that.

**Comment by ewels** [comment]
Ok, so I can replicate the copying error in the version of firefox running on the cluster, but not my local copy. I think this is a weird browser bug limited to that specific version - I get erratic and often incorrect copying with various other tables on the web from that browser.

I don't think this is something I can fix from MultiQC sorry, so closing the issue for now.
