### ISSUE TITLE
seqtk fqchk module request

### ISSUE THREAD

**Issue by avilella** [ewels/MultiQC#234]
## If you're requesting a new module

Checklist of requirements:

- [x] Description of tool, link to homepage

https://github.com/lh3/seqtk

- [x] Log files - please submit as a PR to https://github.com/ewels/MultiQC_TestData

https://github.com/ewels/MultiQC_TestData/pull/9

- [ ] Any standard log file naming patterns to get sample name (eg. `sample_name.processed.log`)

Running: `seqtk fqchk -q0 file_prefix.fastq.gz > file_prefix.seqtk_fqchk.tsv`
will produce the `file_prefix.seqtk_fqchk.tsv` ready for parsing.

- [x] Say which value is most important, to go into the General Stats table

The first line starting with `ALL...`. Most important value is the `#bases`, followed by `%N` and `%Q36`. The rest left as default untick in the table.

```
min_len: 35; max_len: 151; avg_len: 145.38; 6 distinct quality values
POS     #bases  %A      %C      %G      %T      %N      avgQ    errQ    %Q2     %Q14    %Q21    %Q27    %Q32    %Q36
ALL     1035546109      48.9    25.0    1.6     24.5    0.0     31.2    21.8    0.01    15.10   2.64    5.19    15.95   61.11
```

- [x] Specify what should be plotted, if anything

I imagine this goes all in the table, no need to plot anything. Optionally, barplot of `#bases`.

**Comment by ewels** [comment]
Nice! Do you think it's worth plotting sequence composition and quality? Same plots as from FastQC?

This file is going to be really annoying to find again 😞  No consistent filename (just stdout) and no header lines saying where the file came from. Best unique string I can see is `distinct quality values` - any ideas for something better?

Why do the `#bases` for `ALL` differ to those in `POS` `1`?

**Comment by ewels** [comment]
Hi @avilella,

I'm going to close this for now I think - I can't see much here that isn't already calculated and parsed in the FastQC module. The `fqchk` command doesn't seem to be documented anywhere either, which makes me nervous, also makes me think that not many people use this tool?

As always, you're welcome to make a pull request :)

Phil

**Comment by ewels** [comment]
Closing for now until as/when someone is working on this.
