### ISSUE TITLE
Incorrect report name parsing for fastqc reports

### ISSUE THREAD

**Issue by olegs** [ewels/MultiQC#237]
I have the following `fastqc` reports list:
```
run_XXX_sequence.txt_123_fastqc.html
run_XXX_sequence.txt_123_fastqc.zip
run_XXX_sequence.txt_456_fastqc.html
run_XXX_sequence.txt_456_fastqc.zip
```
In this case `multiqc` fill find only single report, i.e. if you launch `mutliqc` with verbose option:
`...[DEBUG  ]  Duplicate sample name found!...`
This is the consequence of the fact that `txt_123` and `txt_456` suffixes are omitted.

**Comment by ewels** [comment]
Hi @olegs,

The MultiQC module ignores the `.html` files, so it's just looking at the `.zip` files. It defaults to taking the filename but tries to look for a line in the `fastqc_data.txt` file that looks like this:
```
Filename	SRR1067503_1.fastq.gz
```
It then cleans this up to be the sample name for the MultiQC report (removing extensions etc). So, my suspicion is that your FastQC reports contain the same value on this line (presumably `run_XXX_sequence.txt`).

If the zip files are in different directories then you can keep them unique by running MultiQC with the `--dirs` flag (see the [docs](http://multiqc.info/docs/#clashing-sample-names)). You can also try the `-s` flag to stop the filenames from being cleaned up, but I don't think that this will help in your case.

Unfortunately beyond this I'm not sure how else you can keep them separate. It would require changing the way that the FastQC module parses reports, and for every person in your situation there's a corresponding person who renames all reports to `fastqc.zip` and relies on the input filename for the report to work properly.

I hope this helps to explain what's going on! Let me know if you're able to get around it or have any suggestions how MultiQC could handle this better.

Phil
