### ISSUE TITLE
TopHat2 Double Mapping 

### ISSUE THREAD

**Issue by darogan** [ewels/MultiQC#238]
Would it be possible for the TopHat report to include a feature to sum the reports from a double mapping approach (as published here http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3185964/). The second map recovers up to 10% of the reads (0.3% in the example below).

At the moment I have to ignore the second alignments stats, as MultiQC sometimes selects run 2 over run 1 so the stats look really bad.

```
$ cat tophatrun1.align_summary.txt
Left reads:
          Input     :    637921
           Mapped   :    548942 (86.1% of input)
            of these:     88001 (16.0%) have multiple alignments (32138 have >2)
Right reads:
          Input     :    637921
           Mapped   :    555483 (87.1% of input)
            of these:     88880 (16.0%) have multiple alignments (32316 have >2)
86.6% overall read mapping rate.

Aligned pairs:    522369
     of these:     83141 (15.9%) have multiple alignments
                   29693 ( 5.7%) are discordant alignments
77.2% concordant pair alignment rate.
```
```
$ cat tophatrun2.align_summary.txt
Left reads:
          Input     :     82438
           Mapped   :       250 ( 0.3% of input)
            of these:        40 (16.0%) have multiple alignments (2 have >2)
Right reads:
          Input     :     82438
           Mapped   :       282 ( 0.3% of input)
            of these:        36 (12.8%) have multiple alignments (0 have >2)
Unpaired reads:
          Input     :      6541
           Mapped   :        10 ( 0.2% of input)
            of these:         3 (30.0%) have multiple alignments (0 have >2)
 0.3% overall read mapping rate.
```

**Comment by ewels** [comment]
Hmm, this is tricky as it's entirely non-standard. How do you propose that MultiQC should know when to sum and when to ignore / overwrite? I can't think of a nice way to do it, though depending on your setup it should be possible to do with a plugin.

Approach sounds nice! Couldn't see anything about double mapping with my ten second scan of the paper though..?

Phil

**Comment by darogan** [comment]
I lazily added the ref from http://vinaykmittal.blogspot.co.uk/2013/02/how-to-improve-rna-seq-alignment-using.html which itself contains a much better description

If a sample has two files containing TopHat alignments stats that could trigger a sum, and as a sanity check make sure they don't go over 100%

My files are named in the format (via a clusterflow module...):
Sample_123456_1_val_tophat.tophatrun1.align_summary.txt
Sample_123456_1_val_tophat.tophatrun2.align_summary.txt

So if multiqc sees there are two files for Sample_123456_1_val_tophat then maybe it could make the choice to sum them

I appreciate this is very non-standard, so maybe a plugin is more appropriate.

**Comment by ewels** [comment]
Yeah, I think that this is too specific to your setup sorry.. The sample names should come back as `Sample_123456_1_val_tophat.tophatrun1` and `Sample_123456_1_val_tophat.tophatrun2` though, so it would be fairly easy to write a plugin that recognises these extensions and merges the data.

..or you could just use STAR which has two pass alignments built-in 😉
