### ISSUE TITLE
HighCharts 5

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#241]
HighCharts 5 is coming, and it looks like it will have quite a lot of features which MultiQC reports will benefit from: http://www.highcharts.com/news/215-highcharts-5-preview
- [ ] Dynamically update chart options without destroying chart (Highlighting / Renaming / Hiding?)
- [ ] Style by CSS (highlight barcharts?)

Use this issue as a reminder to keep track of progress (eg. when the stable version is released) and to keep a reminder list of things to update.

**Comment by avilella** [comment]
+1 for Dynamically updating charts.

**Comment by ewels** [comment]
@avilella: How do you mean? They already do this, it's just that they're destroyed and recreated behind the scenes. This change would just simplify the code.

**Comment by ewels** [comment]
HighCharts v5.0 is [now released](http://www.highcharts.com/news/236-highcharts-5-0)!

Lots of useful stuff, notably [css styling](http://www.highcharts.com/docs/chart-design-and-style/style-by-css) (dynamic highlighting of chart elements?) and [`chart.update`](http://api.highcharts.com/highcharts/Chart.update) (may be able to avoid destroying and replotting charts?)

**Comment by ewels** [comment]
Updated source files to HighCharts v5. Tested and seems to still work as expected, hopefully can pick up any resulting bugs before the next release.

Have not yet tried doing anything clever with new features. Notably - styling by CSS would be great, but using those source files breaks everything as none of the custom colours and stuff works any more. Would need new Python or JS code to write CSS to make all of the in build config work again.

Phil
