### ISSUE TITLE
"copy_module_files" function

### ISSUE THREAD

**Issue by vladsaveliev** [ewels/MultiQC#247]
The documentation refers to the method "copy_module_files" that does not exist in the source.

Is there any other standard method of bringing custom CSS or JS files?

**Comment by ewels** [comment]
Apologies, that's outdated. Thanks for reporting (note to self: http://multiqc.info/docs/#appendices-1 )

I'll update it when I get a chance - in the mean time you can see how the FastQC module does it here:
https://github.com/ewels/MultiQC/blob/master/multiqc/modules/fastqc/fastqc.py#L80-L82

Basically just update the `self.css` and `self.js` dicts, with the key as the filename that you want it to have in the generated report (ignored in the default template which includes the file in the HTML) and the value as the module path.
```python
# Add to self.css and self.js to be included in template
self.css = { 'assets/css/multiqc_fastqc.css' : os.path.join(os.path.dirname(__file__), 'assets', 'css', 'multiqc_fastqc.css') }
self.js = { 'assets/js/multiqc_fastqc.js' : os.path.join(os.path.dirname(__file__), 'assets', 'js', 'multiqc_fastqc.js') }
```

**Comment by vladsaveliev** [comment]
Thanks for the answer, and big thanks for MultiQC - the tool is fantastic!

**Comment by vladsaveliev** [comment]
(Sorry for closing)

**Comment by ewels** [comment]
No problem - glad you like it! Yeah, I'll close this when I've updated the docs 😉
