### ISSUE TITLE
trimmomatic-module

### ISSUE THREAD

**Issue by spooner1** [ewels/MultiQC#249]
Hi Phil,

I have recognized problems with the trimmomatic-module. My log-file looks almost like this one `MultiQC_TestData/data/modules/trimmomatic/special_cases/arizonaTrimm.txt`. The only difference is, that the percentage values for `survining` and `dropped` are with dots instead of commas. Honestly, the mentioned testfile does not work for me too. Only if I rename the commas with dots and, which is also necessary for my own log-file, attatch the second line with the arguments to the first line. So finally the file has to look like the one I have attatched. Hope you can resolve that issue. Beside of that, multiqc is a great tool! 

Thanks a lot and many regards, Michael

[arizonaTrimm_new.txt](https://github.com/ewels/MultiQC/files/346054/arizonaTrimm_new.txt)

**Comment by ewels** [comment]
Hi Michael,

Thanks for your report - is this with MultiQC v0.6 or the v0.7 development code? It sounds a lot like the problem reported in #217 which I already fixed. There was also a different bug reported in #212 which is also fixed. You can test it by grabbing the dev code from GitHub.

If it still doesn't work please let me know and upload the log file that doesn't work. I'm hoping to release v0.7 really soon though, probably today or tomorrow, so it would be good to know about any bugs before then ;)

Cheers,

Phil

ps. I'm not 100% clear about your description and the attached log file - but the file you attached seems to work fine for me...

**Comment by spooner1** [comment]
Hi Phil,

I used v0.6, with the development code it works like a charme ;) Sorry for not considering the closed bugs, and you are absolutely right, I had the same problems as mentioned. 

Regards

**Comment by ewels** [comment]
Ah great - no problem at all, it's been quite a long time between releases this time (I wanted to leave things stable whilst the paper was in review / hot off the press).
