### ISSUE TITLE
samtools "Reads Mapping" plot

### ISSUE THREAD

**Issue by MikeFirth** [ewels/MultiQC#250]
Hi

I am starting to use multiqc to summarise RNASeq analysis reports - it is amazingly useful.

I noticed though that the samtools "Reads Mapping" plot and mouseovers are slightly misleading as the categories they are displaying overlap significantly (reads paired is a superset of reads properly paired for example). This means that the %s are very misleading. Would it be possible to display and show in the mouser the %s of total reads instead?

Thank you for your attention.

Mike

**Comment by ewels** [comment]
Hi Mike,

Glad that you're finding MultiQC useful! I'm glad to say that this has been previously reported (#242) and fixed already. In fact, I released the new v0.7 of MultiQC a few minutes ago, so if you run the update then your reports should be better.

Cheers,

Phil

**Comment by ewels** [comment]
ps. I was thinking about this module recently - am I right in thinking that most people run it to get percent aligned for tools such as BWA that don't report this themselves?

If so, I could maybe remove the relevant stats from the beeswarm plot and make a bar plot (more like the bar plots for the other alignment tools). I'd need to be pretty careful that I don't fall into the trap you reported above though, and that the numbers add up properly, but it should be doable.

Is that something you'd be interested in?

Phil

**Comment by MikeFirth** [comment]
Wow - that’s what I call fast work!

**Comment by ewels** [comment]
Hah, I do my best! Though I think that releasing the fix before the bug was reported might be a record ;) I'll create a new issue for the samtools update.
