### ISSUE TITLE
New module: bcftools vcfstats

### ISSUE THREAD

**Issue by barrymoore** [ewels/MultiQC#269]
Requesting a new module for bcftools vcfstats output.  Started to add data to the TestData repo and saw someone already did that a couple weeks ago, so I'll just submit this new issue as an up vote for the previous bcftools stats module request.

**Comment by ewels** [comment]
Ah, thanks @barrymoore - this was added for a hackathon but no issue created here, so I'd forgotten about it. Thanks for reminding me!

If you have any test data for this tool, it would be great if you could still add it to [MultiQC_TestData](https://github.com/ewels/MultiQC_TestData/) - it's always nice to have more than one file to refer to / test with. Especially if it's possible to run bcftools in different ways, eg. with multiple input files.

Which stats are most important for you? Which would you like to see in the MultiQC report?

Phil

**Comment by ewels** [comment]
Note to self - example data [here](https://github.com/ewels/MultiQC_TestData/blob/master/data/modules/bcftools/Test1_stats.txt). Summary PDF generated with `plot-vcfstats` [here](https://github.com/ewels/MultiQC_TestData/blob/master/data/modules/bcftools/Test1-summary.pdf).

**Comment by ewels** [comment]
Hi @barrymoore,

I've just had a go at writing the new module. If you could grab a copy of the v0.8dev code and give it a spin, that would be great! I've basically tried to replicate the output of `plot-vcfstats`, adding some (but not all) of the summary numbers to the general stats table and plotting the indel length distribution / substitution types.

I haven't done the depth distribution as the test data I have gives a straight line of 0s, so I'm not really sure what it's meant to show. I also haven't done the Ts/Tv plot.

Let me know what you think! Happy to make any changes.

Phil

**Comment by ewels** [comment]
@lpantano - I think you added the test data for this module, so you may also be interested in having a go..

**Comment by darogan** [comment]
![screen shot 2016-07-20 at 17 19 47](https://cloud.githubusercontent.com/assets/6408578/16994190/3d3e87d2-4e9e-11e6-87c2-2cff1a6e871e.png)

Very timely new module 
'substitution types' works for me
'indel length distribution' was blank as I filtered for SNPs only - could it be turned off if no data present?

**Comment by ewels** [comment]
Hi @darogan,

Glad you like it! Apologies, I had already written the code to ignore the indel plot but it wasn't working (I add a value for 0 to prevent a connecting line between `-1` and `1`, so your report _did_ have data, just not useful data 😉 ). Can you give this a spin now? Let me know if you still have problems.

Phil

**Comment by ewels** [comment]
Ok, I'm happy with this module so will close this issue for now. Feel free to comment / reopen if anyone has any ideas for improvements!

**Comment by darogan** [comment]
I just retested - all looks good, the indel plot no longer appears. Thanks

A possible suggestion for new improvement/feature:
bcftools stats allows two vcf files to be compared (intersection and compliment), so pairwise comparisons across a bunch of samples could be summarised as e.g. a heatmap.
I'm just testing this now for the first time so not sure how useful or widely applicable it would be.

**Comment by ewels** [comment]
Thanks @darogan! Yes I did see something written about this but didn't look into it much. I've already written heatmap functionality into MultiQC so it should be fairly easy to add if you think it's useful.

**Comment by ewels** [comment]
(I should add - send me some example data if you want this to be written 😉  )

**Comment by darogan** [comment]
Will do, need to generate the data first and see if its going to be useful. I will have an 8x8 pairwise comparison ready some time next week.

**Comment by ewels** [comment]
@darogan - how did the data look? Useful?

**Comment by brentp** [comment]
Are there docs on how to run this? Does it handle the per-sample output of `bcftools stats` when it is run with the `-s` or `-S` options?

**Comment by ewels** [comment]
Hi @brentp - I wrote the module based on [this example output](https://github.com/ewels/MultiQC_TestData/blob/master/data/modules/bcftools/Test1_stats.txt), looks like it was run as follows:
```
bcftools stats Test1.vcf.gz
```

I haven't looked at any other variants of the output so I don't know if it'll work with `-s`. What does that output look like?

Phil

**Comment by ewels** [comment]
ps. "docs" are here: http://multiqc.info/docs/#bcftools (more docs from those who know the tool welcome as a PR!)

**Comment by brentp** [comment]
here is example output when run with -S samples.txt.
[stats-out.gz](https://github.com/ewels/MultiQC/files/682999/stats-out.gz)

**Comment by brentp** [comment]
sample names in that file have "PC" in them. That is from this VCF: https://raw.githubusercontent.com/arq5x/gemini/master/test/test.query.vcf

**Comment by ewels** [comment]
Thanks - working on my phone / web cafes for the next month and a half (no `gunzip`!) but will look properly when I get back. Please open a new issue for this if something needs changing.

Phil

**Comment by barrymoore** [comment]
Hey Phil,

I see back in July at the top of this thread that you replied to me the next day requesting more data.  Just wanted to let you know this thread got triaged by my mailer and I wasn't following online, so I never saw that request until Brent joined the thread last week - since he's a colleague here at Utah the whole thread was pulled back into my INBOX.

MultiQC has been a great tool for getting our investigator/analysis teams to actually review and think about QC data.  We've fully integrated it into our processing pipeline at the UCGD (http://ucgd.genetics.utah.edu/) for all projects and we're big fans.  Thanks for a great tool and if you need test data, letters of support, etc. in the future we're happy to contribute to and promote your work.

Regard,

Barry

**Comment by ewels** [comment]
Great stuff, thanks for getting back to me @barrymoore - not to worry, I have similar inbox rules set up and have missed threads in the past too. 

Great that you're using and like MultiQC and thanks for the offer - I'll try to bear that in mind as it could come in useful in the future! Short term, I try to collect a handful of the nicest testimonial tweets on the MultiQC homepage, so if you fancy tweeting something then that's always welcome :)
