### ISSUE TITLE
Z-index issue with FastQC sequence quality plot

### ISSUE THREAD

**Issue by robinandeer** [ewels/MultiQC#27]
The toolbox doesn't float above the charts, some z-index thing:

* Browser: Chrome Canary
* Modules: General and FastQC

![screen shot 2015-09-17 at 16 52 32](https://cloud.githubusercontent.com/assets/1220232/9936521/a59e6646-5d5c-11e5-901d-a6de2cf244cf.png)

**Comment by ewels** [comment]
I'm guessing that this was after you tried doing the introduction tour - I've just pushed a fix above which should sort that problem out I think (the demo changes the z-score so that the dark background sits on top of the toolbox, but it didn't change it back again when it finished).

**Comment by ewels** [comment]
Closing - let me know if you manage to replicate this bug with the current version!
