### ISSUE TITLE
module request Picard CollectRnaSeqMetrics

### ISSUE THREAD

**Issue by avilella** [ewels/MultiQC#273]
* Description of tool, link to homepage: **Picard CollectRnaSeqMetrics**
* Log files: https://github.com/ewels/MultiQC_TestData/pull/16
* Most important stats, to go into the General Stats table:
```
PCT_CODING_BASES
PCT_UTR_BASES
PCT_INTRONIC_BASES
PCT_INTERGENIC_BASES
MEDIAN_CV_COVERAGE
MEDIAN_5PRIME_BIAS
MEDIAN_3PRIME_BIAS
```
* No plots required.

Thanks!

**Comment by ewels** [comment]
Thanks @avilella - would be good to add this one. See also issue #12

**Comment by ewels** [comment]
Hi @avilella,

I just put together the first version of this code. I also added the histogram plot because the syntax was pretty much identical to another Picard submodule so I figured it didn't hurt.

Let me know if you run into any problems with it or have any suggestions for improvements..

Phil
