### ISSUE TITLE
Separate sections in report for different directories

### ISSUE THREAD

**Issue by royfrancis** [ewels/MultiQC#275]
Is it possible to provide two different directories of fastqc files and then produce a report having the two directories separately as separate sections in the report.

An application is when I have fastqc results of raw files and then I have fastqc results of trimmed files. And of course they have same sample names.

`multiqc ./raw-qc/ ./trimmed-qc/`

Currently, it does read in files from different directories, but combines all of them into one report.

**Comment by ewels** [comment]
Yes! Sort of anyway - not separate sections in the report but you can stop them from overwriting each other with the `-d` / `--dirs` command line flag. You can then use the report highlighting tools to easily discriminate between them.

Phil
