### ISSUE TITLE
kallisto single end reads

### ISSUE THREAD

**Issue by pmenzel** [ewels/MultiQC#276]
The kallisto module does not work when using single-end reads, since the output is a bit different there compared with paired-end reads. It looks like this:
```
[quant] fragment length distribution is truncated gaussian with mean = 280, sd = 20
[index] k-mer length: 31
[index] number of targets: 30,651
[index] number of k-mers: 33,222,996
[index] number of equivalence classes: 58,231
[quant] running in single-end mode
[quant] will process file 1: XXXXXXXXX.fastq.gz
[quant] finding pseudoalignments for the reads ... done
[quant] processed 86,466,052 reads, 41,391,657 reads pseudoaligned
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 1,212 rounds
[bstrp] number of EM bootstraps complete: 100
```

The main difference is probably the missing `estimated average fragment length` line, which is currently required by the multiqc module.

**Comment by ewels** [comment]
Ok, thanks for reporting this (and the example log). I'm on holiday at the moment but will try to have a look at the weekend.

Phil

**Comment by ewels** [comment]
Thanks again @pmenzel - let me know if you have any problems with this new code.

Phil

**Comment by pmenzel** [comment]
It works now!
