### ISSUE TITLE
Samtools stats: samples are mixed up in 'Stats' section

### ISSUE THREAD

**Issue by cjfields** [ewels/MultiQC#278]
I'm seeing an worrisome odd bug for `samtools stats` output in the `Stats` section with the popup IDs (doesn't seem to be a problem in other sections).   

The following two snapshots show the sample name for the highlighted spot as `C12`, but this is incorrect.  For instance, in the Total Sequences pic the highlighed number appears to correspond to sample C4.  In the 'Mapped & Paired' row the C12 sample is again incorrect and appears to correspond with N9.  Both can be seen in the attached `multiqc_samtools_stats.txt` file, which seems to have the correct data based on a cursory look.

![bad-stats](https://cloud.githubusercontent.com/assets/49265/17426259/86842722-5a9b-11e6-939f-f1db6a1abd55.png)
![bad-stats2](https://cloud.githubusercontent.com/assets/49265/17426260/86945d22-5a9b-11e6-869e-62c3879ff4fc.png)

I have also attached the MultiQC log and other output files.  The stats within appear to be parsed correctly from the reports.

[multiqc.log.txt](https://github.com/ewels/MultiQC/files/403112/multiqc.log.txt)
[multiqc_general_stats.txt](https://github.com/ewels/MultiQC/files/403111/multiqc_general_stats.txt)
[multiqc_samtools_stats.txt](https://github.com/ewels/MultiQC/files/403109/multiqc_samtools_stats.txt)
[multiqc_sources.txt](https://github.com/ewels/MultiQC/files/403110/multiqc_sources.txt)

**Comment by ewels** [comment]
Thanks for the detailed report! I'm on holiday at the moment but will look into this when I get back..

**Comment by cjfields** [comment]
@ewels not a problem, about to go on a short trip myself.  I may check into it when I get back, if I can work out the issue I may set up a pull request.

**Comment by ewels** [comment]
Hi @cjfields,

I've just spotted the same error in a different beeswarm / dot plot (this one for Bismark). So I think that this is a bug somewhere in the plotting code. Looking into it now.

Phil

**Comment by ewels** [comment]
Hi @cjfields,

I think I tracked it down - there was a sort statement in the Javascript that I'd added at some point to improve the stacking of the dots. However, this broke the association with the sample names. Nasty bug sorry, and I hadn't noticed it as the overall shape of the plot remained the same.

I just pushed a fix, it's now working as expected for me so I've closed this issue. If you could try your samples above again and confirm that it's working for you too then that would be brilliant.

Thanks again for reporting this.

Phil

**Comment by cjfields** [comment]
Not a problem, thanks for the fix @ewels !
