### ISSUE TITLE
Suggestion: link samples together?

### ISSUE THREAD

**Issue by alneberg** [ewels/MultiQC#28]
Hi, just a humble suggestion can you start a new project named MetaMultiQC (suggested by @guillermo-carrasco) (or possibly MultiMultiQC). 

Just kidding. Do you think its a good idea for support for linking samples together?

I'll try to explain what I mean:
My usecase is that I run fastqc for each sample at each step I take in the processing of the reads. Below you can see the results for three samples in two steps = 18 fastqc reports.
<img width="836" alt="screen shot 2015-09-18 at 16 22 08" src="https://cloud.githubusercontent.com/assets/1250075/9961607/9f4b6f30-5e21-11e5-8ffa-ca7e5daf7f08.png">

Would be nice to see a graph over how the stats change for a sample between the different steps for example. In order to do that I need a way to link the reports that belongs to the same sample together. 

Thanks,
Johannes

**Comment by ewels** [comment]
I've thought about this before - unfortunately, I don't think that there's any safe way to do this without making prior assumptions about sample naming conventions (and so making the tool less general use). So I'm not planning to do this any time soon I'm afraid.

However - some good news: the data within the General Statistics table is also saved to a tab delimited file within the report, so it should be pretty easy to do this in excel.

Also, you could use highlighting patterns to pull out groups of samples for easier comparison (or hiding samples).

**Comment by alneberg** [comment]
Yes I considered doing it automatic as well and then you'll run into that issue. But couldn't it be possible to do on a user defined basis? Maybe a regexp entered by the user?

**Comment by ewels** [comment]
Maybe... If you can think of how it could work then I'll think about how to build it? I still think that it would be quite a lot of work for a fairly niche use case.

See also #29 which I was thinking about earlier today - might be possible to write a plugin at generation time which would be able to use this data with that approach..?

**Comment by alneberg** [comment]
Yeah, I don't have a clear picture of how it would work, I give you that. But is it that niche? Does people just run fastqc once and then they don't care anymore? Don't you wanna fix the issues and then run it again to see that its fixed?

**Comment by ewels** [comment]
Yeah :) Can see that from the numbers though, or highlighting then looking at the plots.. But MultiQC isn't just for FastQC, so this would have to be written in such a way that any module can use it. Not so easy! (Though could restrict to the general stats table I guess)

**Comment by ewels** [comment]
Have a look again after the latest commit (e91133c010024adffe2c4f98fd36f1c4b47d1d16) - no linking between samples, but I've tried to improve how quantitative the general stats is, for better sample comparison.

Let me know what you think!

**Comment by alneberg** [comment]
Very pretty indeed! Gotta love how fast this project evolves! :+1: 
I think if I had a way to sort the rows so that individual samples ended up together, I would be satisfied, especially since I just discovered the fancy "hide samples" function. Right now I managed to do that by sorting on the MReads column, which will only work in certain cases. But it might just be enough for now. Yey!

**Comment by ewels** [comment]
Hah, enjoy it whilst it lasts! :wink: 

I could add a button above the table when highlights are created, allowing you to sort by highlights. Seems like it would be a good idea generally anyway.

**Comment by ewels** [comment]
ps. You know that you can manually sort the rows, right @alneberg?
