### ISSUE TITLE
Print / e-mail template

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#284]
It would be cool if [Cluster Flow](http://clusterflow.io) could e-mail MultiQC reports when pipelines finish. E-mailed reports would need to be totally flat with no JS though. The same goes for print / PDF reports.

Would be nice to have a template that uses flat plots only and is suitable for such uses. For example, no sidebars. Test compatibility with [Pandoc](http://pandoc.org/).

**Comment by darogan** [comment]
A further step would be to include a short description of the clusterflow pipeline used to generate the MultiQC report. Even including program version numbers as they are harvested by clusterflow anyway

**Comment by ewels** [comment]
@darogan: Yes, I was thinking the same thing only last week.

Just created a new issue for the CF module: #287

**Comment by ewels** [comment]
Ok, simplified the already existing `simple` template a lot more. Now looks pretty good for printing / PDF usage.

See example of PDF results when converting the HTML with pandoc, using the default template:
```
pandoc multiqc_report.html -o multiqc_report.pdf --latex-engine=xelatex
```

[multiqc_report.pdf](https://github.com/ewels/MultiQC/files/433684/multiqc_report.pdf)

This all came together much more quickly than expected. Could perhaps write a LaTeX template for use by pandoc now, to make the PDF look nicer.

If _that_ works, I could perhaps add a `--pdf` option that uses the `simple` template and then tries to call `pandoc` with this LaTeX template..? It would have to catch failures when pandoc isn't installed and stuff, but it should be possible to do that in a nice way.

**Comment by ewels** [comment]
Could also add hidden content to the plot generators that would be ignored in the HTML? Such as subheadings above the different plot types and stuff. Hmm.

**Comment by ewels** [comment]
This is what the simple template report looks like when printed from Chome:
[MultiQC Report.pdf](https://github.com/ewels/MultiQC/files/433697/MultiQC.Report.pdf)

Not amazing, but not terrible either. Probably better than how it looks from the default template:
[MultiQC Report_default.pdf](https://github.com/ewels/MultiQC/files/433701/MultiQC.Report_default.pdf)

Could possibly add some print-only CSS styles to the default template to improve printing performance?

**Comment by ewels** [comment]
Added a `--pdf` command which calls Pandoc. Limited customisation currently, but probably as good as I can get without diving head first into LaTeX.

For another day - could create a full MultiQC template in pure TeX! Could be nice.

**Comment by ewels** [comment]
Docs updated and available here: http://multiqc.info/docs/#pdf-reports
