### ISSUE TITLE
Parse software versions from logs

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#290]
Many (but not all) software logs contain information about what version of the tool was run. This would be nice to include in MultiQC report, for example:

> ### FastQC
> 
> All samples were run with v0.11.5 of FastQC

or for a mixture of version numbers:

> ### Kallisto
> 
> Samples were run with versions v0.42 and v0.42.5 `[ dropdown list ]`

As this will be a common feature for most modules, it could be nice to write a new common function to handle this somehow.

**Comment by darogan** [comment]
+1
This will be a great feature (esp in conjunction with clusterflow)

**Comment by ewels** [comment]
Yup, I was originally thinking of getting Cluster Flow to add specific syntax for this that MultiQC could pick up, but @Hammarn pointed out that a lot of the standard logs from tools have versions in. So hopefully for most I can add support for the tool irrespective of how it was run.

Later on I may add support for custom Cluster Flow version printing (and in our NextFlow pipelines), to pick up those tools which don't print their version numbers by default.

**Comment by ewels** [comment]
I think this would work best if it is a new object in `multiqc.report` which modules can add to with versions if they want to. Much like how _General Statistics_ works. So we start by creating an empty placeholder variable [here](https://github.com/ewels/MultiQC/blob/master/multiqc/utils/report.py#L31), then write a new function in the [base module](https://github.com/ewels/MultiQC/blob/master/multiqc/modules/base_module.py#L208) which adds information to that and is called from within modules. Finally, we update the [templates](https://github.com/ewels/MultiQC/blob/master/multiqc/templates/default/base.html#L43) to print this new object if it has data.

Phil

**Comment by apeltzer** [comment]
Sounds like a great feature - also in terms of reproducibility which lots of journals e.g. require now, you could have a single report supporting versioning information of all tools (and most tools do write their versions in a logfile).

**Comment by johandahlberg** [comment]
I was wondering if something has happened to this issue, and/or if there is any interest in a patch to add software versions to the MultiQC report? We are in the process of revamping our reports, and having the software versions in the report is something that has been requested.

**Comment by apeltzer** [comment]
Most of the pipelines we use these days do have custom sections that generate a custom section using multiqc: https://github.com/nf-core/rnaseq/blob/e8376373da8c1dfb0cae5372947cf5b241056076/main.nf#L1041-L1065

**Comment by johandahlberg** [comment]
@apeltzer Nice! Thank you. That is incredibly helpful, and pretty much exactly what we want do do.

**Comment by ewels** [comment]
You guys are running nf-core pipelines and Sarek right? So this should be in place already..

**Comment by johandahlberg** [comment]
This is for a new pipeline/report we are developing to replace our venerable software [Sisyphus](https://github.com/Molmed/sisyphus). I do think it would be a very nice feature to have built-in to MultiQC though, since I am guessing that most softwares will write their versions in the output data, parsing it in that way should be beneficial to all users.

**Comment by ewels** [comment]
I'm not sure about most tools, but some definitely.. Yeah I'm still keen to do this. Ideally with an option to also manually add versions for tools that don't have the information in the default output (to integrate nicely with the kinds of solutions linked to above).

**Comment by ewels** [comment]
Finally done in #1927! 🎉 👏🏻 

![](https://media.giphy.com/media/XeSmw0YbOEo5s89DTM/giphy.gif)
