### ISSUE TITLE
Picard CollectAlignmentSummaryMetrics

### ISSUE THREAD

**Issue by reshu23** [ewels/MultiQC#293]
Hi,

I have Picard  "CollectAlignmentSummaryMetrics" output. Which is general statistics of bam file. It is simple text file (file is attached) Can you please provide any new module for such type of reports???

[statistics.txt](https://github.com/ewels/MultiQC/files/465132/statistics.txt)

**Comment by ewels** [comment]
Hi @reshu23,

Thanks for your issue - I was already planning to add support for this output (see issue #12) but needed some example data, which you just provided! Many thanks for this, I will add support soon.

Phil

**Comment by reshu23** [comment]
OK. Thank you very much. I am waiting for module. One more thing, sometimes, we do not need all information of a statistics table. Is it a way, to exclude some column information from the final report instead of excluding whole statistics table????

**Comment by ewels** [comment]
Yes, you can choose which columns to hide using the `table_columns_visible` config options. See the documentation about it here: http://multiqc.info/docs/#customising-tables

**Comment by reshu23** [comment]
Is it gonna take long time????(new module)

**Comment by ewels** [comment]
Hi @reshu23,

You requested the module at the weekend and I've been on vacation yesterday and today. I'll get to it when I have time ;)

Phil

**Comment by ewels** [comment]
Ok, new module added! It doesn't do a great deal yet - just adds the percent aligned to the general stats table at the top. Hopefully this is useful though :) Feedback welcome!

**Comment by ewels** [comment]
Just added a bar plot of aligned / unaligned reads too. Note that Picard reports 2 reads for each PE pair, so I divided the count by two for PE data to make it comparable to other stats (usually # clusters are reported).

**Comment by Rmulet** [comment]
As I mentioned on Gitter, this submodule does not seem to be working. I have tried it with the two latests versions of MultiQC, using both my own data and the examples in your repository. I have also verified that the search pattern is right, which it is, and made sure that the Python script is where it should be. There must be something I am missing here.

**Comment by ewels** [comment]
Hi @Rmulet,

Are you able to send through one of your files so that I can try to replicate the problem? If you can't make it public then you can send it via e-mail instead.

Phil

**Comment by Rmulet** [comment]
Hi @ewels, I have been looking into it again and I suspect I know the reason behind the problem. I generated the AlignmentSummaryMetrics data with the CollectMultipleMetrics.jar tool, which allows to run in a single command several programs within the Picard package. The output of this this program is virtually identical to that of the standalone CollectAlignmentSummaryMetrics.jar, with a few differences in the headers and less empty lines at the end. Interestingly, this does not happen with CollectInsertSizeMetrics, which I generate in the exact same way but is detected anyway.

I believe your example data already reflects the differences between CollectMultipleMetrics.jar PROGRAM=CollectAlignmentSummaryMetrics and CollectAlignmentSummaryMetrics.jar, but I am attaching some examples of my own anyway.

[216_D_18666.CollectMultipleMetrics.txt](https://github.com/ewels/MultiQC/files/544380/216_D_18666.CollectMultipleMetrics.txt)
[216_D_18666.AlignmentSummaryMetrics.txt](https://github.com/ewels/MultiQC/files/544382/216_D_18666.AlignmentSummaryMetrics.txt)

**Comment by ewels** [comment]
Aha, yes that would explain it. I think I had to adjust the code for the insert size module to understand output from collectmultiplemetrics, so I'll presumably need to do the same for alignment summary metrics.

Thanks for the example files! I'll let you know when it's fixed.

Phil

**Comment by ewels** [comment]
Moving this into a new issue so that it doesn't get lost in the list of closed issues. See #327
