### ISSUE TITLE
Docs: Add basic page about WASM

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#2930]
Can move some of [the FAQ](https://github.com/MultiQC/website/blob/c13a9c36b9dc265f2fdd5a4c43a198b780ac6a4a/src/pages/run.astro#L32-L130) from the old mutliqc.info/run page over, and rewrite to make a little more complete / interesting.

We can then link to this page from seqera.io/multiqc above the run box for anyone wanting more information.

**Comment by autumnlem** [comment]
I'm interested in contributing to this.
