### ISSUE TITLE
Add ContEst and THetA2

### ISSUE THREAD

**Issue by jlac** [ewels/MultiQC#303]
Hi!

Let me first say that this tools is absolutely fantastic!

I was wondering if it would be possible to add summaries for ContEst, a tools estimating contamination in tumor samples, and THetA2, a tool capable of estimating tumor purity from paired tumor/normal samples.

Checklist:
1) Websites
   * http://compbio.cs.brown.edu/projects/theta/
   * https://software.broadinstitute.org/gatk/gatkdocs/org_broadinstitute_gatk_tools_walkers_cancer_contamination_ContEst.php

2) Log file examples for each are attached
    * [TCGA-OR-A5L9-01A-11D-A29I-10_TCGA-OR-A5L9-10B-01D-A29L-10.ContEst.txt](https://github.com/ewels/MultiQC/files/485349/TCGA-OR-A5L9-01A-11D-A29I-10_TCGA-OR-A5L9-10B-01D-A29L-10.ContEst.txt)
    * [TCGA-OR-A5L5-01A-11D-A29I-10.BEST.results.txt](https://github.com/ewels/MultiQC/files/485355/TCGA-OR-A5L5-01A-11D-A29I-10.BEST.results.txt)

3) No Standard naming convention for ContEst, but I (and many others I know using the tools) use a convention of `SAMPLENAME.ContEst.out`. For THetA2, the naming convention is `SAMPLENAME.BEST.results`

4) The most important value from ContEst is the contamination %, which is in the 4th column of the attached log file. In addition, illustration of confidence interval would be cool, but not necessity. The most important value for THetA2 is the tumor proportion, which is/are the value(s) following the first proportion given in the second column of the attached log file. Basically, the output in the second column gives: `proportion_germline,proportion_tumorClone_1,proportion_tumorClone2,...,proportion_tumorCloneN,` where a likelihood model calculate the best fit for the number of tumor "populations" in the sample. Ideally, this would be illustrated as a stacked bar (one color for a single population, two colors for two populations, etc.).

5) For ContEst, it would simply be nice to illustrate the percent contamination for each sample. For THetA2, it would be nice to illustrate the tumor purity for each sample, with the bars stacked as described above, so we can see total percent purity as well as what proportion each inferred tumor population occupies.

Thank you in advance for your help on this, and please let me know if I can provide anything else. Thanks!

Justin Lack

Justin Lack
Bioinformatic Analyst
Frederick National Laboratory for Cancer Research
Leidos Biomedical Research, Inc.
Post Office Box B
Frederick, MD  21702
Phone: 405-314-4356
justin.lack@nih.gov

**Comment by ewels** [comment]
Hi Justin,

This sounds great, thanks for the detailed issue! I'll try to take a look soon - bit of a backlog on issues at the moment but I'll get to it when I can.

Phil

**Comment by jlac** [comment]
No problem, and thanks for your work on this!

Justin

Justin Lack
Bioinformatic Analyst
Frederick National Laboratory for Cancer Research
Leidos Biomedical Research, Inc.
Post Office Box B
Frederick, MD  21702
Phone: 405-314-4356
justin.lack@nih.gov

**Comment by jlac** [comment]
Hi Phil,

Just checking on the progress on this issue. Mainly, I wanted to switch from ConTest to ConPair (https://github.com/nygenome/Conpair) for the above suggested contamination program to implement in MultiQC. Here is an example log file:

[D415+9975T.conpair.txt](https://github.com/ewels/MultiQC/files/724816/D415.9975T.conpair.txt)

Thanks!

**Comment by ewels** [comment]
Hi Justin,

Apologies, no progress yet and I'm now away on a long trip in a campervan in New Zealand (back mid-Feb). Thanks for the log file, will get to this when I can..

Phil

**Comment by jlac** [comment]
No worries, just checking in. Enjoy your trip!

Justin Lack
Bioinformatic Analyst
Frederick National Laboratory for Cancer Research
Leidos Biomedical Research, Inc.
Post Office Box B
Frederick, MD  21702
Phone: 405-314-4356
justin.lack@nih.gov

**Comment by epruesse** [comment]
Check out Kerosene Creek if you get near it. Bear in mind, though, the hot spring hasn't been commercialized for a reason, and it got its name from its smell. (Other than that it's very beautiful). 

Elmar

**Comment by ewels** [comment]
Hi @jlac,

Many apologies for the long wait! I have now written modules for Conpair and THetA2. If you could have a play with the latest development version and let me know if you run into any problems, that would be great!

You can get the latest development version through `pip` with the following command:

```
pip install --upgrade --force-reinstall git+https://github.com/ewels/MultiQC.git
```

Cheers,

Phil

**Comment by jlac** [comment]
Hi Phil,

I have tested the new modules, and they seem to be working great! Thanks for adding this functionality!

Justin Lack
Bioinformatic Analyst
Frederick National Laboratory for Cancer Research
Leidos Biomedical Research, Inc.
Post Office Box B
Frederick, MD  21702
Phone: 405-314-4356
justin.lack@nih.gov

**Comment by ewels** [comment]
Great stuff, thanks for letting me know! 👍

**Comment by jlac** [comment]
Hi Phil,

I just wanted to check on the timeline for merging these recent additions to MultiQC into a new release version? The NIH HPC folks are often apprehensive about updating an HPC module from a GitHub branch, as opposed to updating from an official release. Thanks!

Justin

Justin Lack
Bioinformatic Analyst
Frederick National Laboratory for Cancer Research
Leidos Biomedical Research, Inc.
Post Office Box B
Frederick, MD  21702
Phone: 405-314-4356
justin.lack@nih.gov

**Comment by ewels** [comment]
Hi Justin,

I was hoping to release this week but didn't quite make it. So planning to release on Monday now.

Phil
