### ISSUE TITLE
dupRadar module

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#305]
New module for [dupRadar](https://www.bioconductor.org/packages/release/bioc/html/dupRadar.html). Should have standardised output from the `analyzeDuprates` function..? Maybe?

**Comment by ewels** [comment]
Output from dupRadar is too variable. Will write this module as part of MultiQC_NGI instead.

**Comment by rspreafico-vir** [comment]
hi there, super-interested in this. No way this can make its way into the main MultiQC? :-)

**Comment by rspreafico-vir** [comment]
Ok, not sure why, but MultiQC 1.7 picked up my DupRadar report, even if dupradar is not listed as one of the supported tools. Magic! :-)

**Comment by rspreafico-vir** [comment]
I see why, I was testing out of the `nf-core` pipeline and output makes use of the custom module. Wonderful!

**Comment by ewels** [comment]
Yes! Unfortunately dupRadar doesn't really have a consistent output file format, so any central module wouldn't work for everyone. Custom modules / custom content files work well though 👍
