### ISSUE TITLE
Module picard RnaSeqMetrics raised an exception

### ISSUE THREAD

**Issue by xc611** [ewels/MultiQC#306]
```python
Module picard raised an exception: Traceback (most recent call last):
  File "/usr/local/Anaconda/envs_app/multiqc/0.8dev/lib/python3.5/site-packages/multiqc-0.8.dev0-py3.5.egg/EGG-INFO/scripts/multiqc", line 339, in multiqc
    report.modules_output.append(mod())
  File "/usr/local/Anaconda/envs_app/multiqc/0.8dev/lib/python3.5/site-packages/multiqc-0.8.dev0-py3.5.egg/multiqc/modules/picard/picard.py", line 68, in __init__
    n['RnaSeqMetrics'] = RnaSeqMetrics.parse_reports(self)
  File "/usr/local/Anaconda/envs_app/multiqc/0.8dev/lib/python3.5/site-packages/multiqc-0.8.dev0-py3.5.egg/multiqc/modules/picard/RnaSeqMetrics.py", line 81, in parse_reports
    for key in self.picard_RnaSeqMetrics_data.keys():
RuntimeError: dictionary changed size during iteration
```

**Comment by ewels** [comment]
Thanks @xc611 - looks like I never actually ran those lines with my demo data. I'll see if I can figure out how to replicate the bug and then fix it. If you're able to send me your data that would help quite a bit (either here or to phil.ewels@scilifelab.se)

Phil

**Comment by ewels** [comment]
I think I cracked it - it was Python 3 specific which made it trickier to pin down. I'd already written a workaround fix for the same bug three lines below where this broke, so a bit of a fail on my part.

Thanks for reporting! The same problem was present in several other Picard MultiQC modules, so it was a good one to fix.

Phil

**Comment by xc611** [comment]
Thank you

Get Outlook for Android<https://aka.ms/ghei36>



On Thu, Sep 22, 2016 at 4:47 PM -0400, "Phil Ewels" <notifications@github.com<mailto:notifications@github.com>> wrote:


I think I cracked it - it was Python 3 specific which made it trickier to pin down. I'd already written a workaround fix for the same bug three lines below where this broke, so a bit of a fail on my part.

Thanks for reporting! The same problem was present in several other Picard MultiQC modules, so it was a good one to fix.

Phil

-
