### ISSUE TITLE
Modules Request

### ISSUE THREAD

**Issue by jcgrenier** [ewels/MultiQC#311]
Hello there, I have some ideas of modules to add that could be really easy for you to code. 

-HTseq-count, which is pretty much the same thing as featureCount, but a slightly different output file.
-Trim Galore! module, which is using Cutadapt to automatically detect and quality trim the ends of the reads for any adapters. http://www.bioinformatics.babraham.ac.uk/projects/trim_galore/

One could think of some more high level QC. One that could use the output of relatedness, or relateness2 command from the newest version of vcftools that could be used to see if two RNASeq samples of different condition are the same individual or if they are from the same family. A simple triangular heatmap could do the job.

http://vcftools.sourceforge.net/man_latest.html#OUTPUT OPTIONS

Another useful QC that could be integrated would be one using Genotyping array data. As sometimes we like to do analysis like eQTL analysis and use both genotyping data (as it costs less than generating whole exome or whole genome sequencing data) and RNAseq data. Some summary barplots using informations from this table 

https://atgu.mgh.harvard.edu/plinkseq/stats.shtml#ind

Some information there could be useful to make sure all the samples are fine and not mixed with one another. Using the heterozygosity rate, we can detect rapidly if one or more sample could have any abnormalities. 

Thanks for your help! Your tool is amazing and will surely help a lot of labs with growing datasets to better organize their things!

**Comment by ewels** [comment]
Hi @jcgrenier,

Thanks for your request! Some great ideas here, I'll go through them in order..

- **HTSeq-Count**
  - Yes, absolutely - great suggestion. In fact I'm kind of surprised that I haven't already written this one :)
- **TrimGalore!**
  - The second module I wrote for MultiQC was TrimGalore, but I realised that all of the interesting stats were coming from the cutadapt output. So I renamed the module to `cutadapt`. My test dataset actually has [output from TrimGalore](https://github.com/ewels/MultiQC_TestData/tree/master/data/modules/trim_galore), try running MultiQC on your data and it _should_ "just work"
- **vcftools --relatedness**
  - Interesting, I'd like to know more about this. How would you use it with RNAseq data - do variant calling and then pass that to vcftools? Do you have any example output that I could see?
- **PLINK/SEQ i-stats**
  - Yup, looks nice. That should certainly be possible. As above I'm not familiar with running the tool at all, so need to look into it a little more.

To be clear - I don't write modules for MultiQC so much based on the biological need (though I do take this into account), but rather on what different tools produce as output. Many of the high-level QC methods are with tools / packages that don't have standardised output, making it impossible to write a module for MultiQC. We get around this in our group by writing non-standard MultiQC modules able to parse the output from our non-standard R scripts - see [this example report](http://multiqc.info/examples/ngi-rna/Test_NGI_Project_multiqc_report.html) and the [code that generates it](https://github.com/ewels/MultiQC_NGI). So, identifying tools such as the above which _do_ produce standardised output is great!

Phil

**Comment by jcgrenier** [comment]
Hi Phil!

Thanks a lot for answering my resquests! I'll try it ASAP for TrimGalore! 
Concerning the relatedness test on RNAseq data, as I'm only doing it on a QC basis, I'm pretty much following the recommended pipeline on GATK for SNP calling, but generate the vcf in GVCF format, and join them together after. The critical point after is the amout of missing data per SNP. As RNAseq data is pretty much variable accross the samples, and that those relatedness/IBD sharing tests are pretty much affected by the amount of missing data in the dataset. I'm normally only keeping positions with less than 50% of missing rate. What you are getting after is a tabulated file with multiple values. 

INDV1	INDV2	N_AaAa	N_AAaa	N1_Aa	N2_Aa	RELATEDNESS_PHI

Where the three columns that interests us in the end are 1,2,7. The other ones are for identical/different genotypes and the number of points in each sample in the comparison.

Here's some more interesting information (taken from that post on biostar : https://www.biostars.org/p/111573/)

First-degree relatives are ~0.25, and 2nd-degree ~0.125, and 3rd degree 0.0625.
"Unrelated" parents can reach values as high as ~0.04 in my experience.

So, in an analysis where we want to recover "identical" samples that should corresponds to the same individual, we should get something between 0.25 and 0.5 (0.5 is for identical sample). 

Hopes it will help some more people with their QCs!

Best,
JC

**Comment by jcgrenier** [comment]
OK, so I tried to use the TrimGalore report outputs but it's not working using either the automatic way to identify the outputs or to explicitely specifying "cutadapt" in the module option.

**Comment by ewels** [comment]
The module [looks for files](https://github.com/ewels/MultiQC/blob/master/multiqc/utils/search_patterns.yaml#L28-L29) based on them containing the string `This is cutadapt`. For TrimGalore, the `stderr` should contain this (if logged to a file) and also the file called `<input>_trimming_report.txt`.

You can see an example of this TrimGalore! file here, with the highlighted lines coming from cutadapt: https://github.com/ewels/MultiQC_TestData/blob/master/data/modules/trim_galore/SRR1067503_1.fastq.gz_trimming_report.txt#L19-L85

If you're sure it's not working with your `trimming_report.txt` files, please send one over and I'll have a look.

Phil

**Comment by jcgrenier** [comment]
Superb, it works now. I'm using an older version of cutadapt. I had to modify the log a bit.

From : cutadapt version 1.2.1
To : This is cutadapt 1.2.1

Thanks a lot!
JC

**Comment by ewels** [comment]
Wow, that is a bit old - released 30th Nov 2012 :) If you don't mind sending over a complete log I can try and find a search string that works with both versions so that the support is as broad as possible..?

**Comment by jcgrenier** [comment]
Hehehe, yeah that's a bit old indeed! We never really updated that part of the pipeline we are using. 

Here's a log example. Tell me if the upload worked well.

[232903252_R1.fastq.gz_trimming_report.txt](https://github.com/ewels/MultiQC/files/528170/232903252_R1.fastq.gz_trimming_report.txt)

Thanks!

**Comment by ewels** [comment]
Test data added in https://github.com/ewels/MultiQC_TestData/commit/a37cbe260944ee32285f7e59ebd7565319af5552

**Comment by ewels** [comment]
Hi @jcgrenier,

I've just been looking at the cutadapt code and I have pushed and update (see above). I don't think your log files were appearing in the General Statistics table at the top of the report, they should now do so.

I also noticed a small bug where the quality trimmed base pairs weren't being picked up in old reports (my test data didn't have any, so this line wasn't present in my other log file). So that's also now fixed.

Thanks for the log file!

Phil

**Comment by ewels** [comment]
ps. I forgot to say - I looked into getting MultiQC to recognise log files from both old and new versions of cutadapt, but there are no good text strings which are present in all versions of the logs, so I don't think it's possible.

To get MultiQC to work with very old logs such as the one you pasted, you'll need to create a config file for MultiQC. Copy and paste this into a file called `.multiqc.config` in your home directory and everything should work:

```yaml
sp:
    cutadapt:
        contents: 'cutadapt version'
```

See [the docs](http://multiqc.info/docs/#module-search-patterns) for more information.

Phil

**Comment by jcgrenier** [comment]
Hi @ewels,

I tried to add that .multiqc.config in my $HOME directory, but it didn't work. Maybe because of the way I installed it. (using pyenv) Anyway, I was able to make it work by only specifying the config file throught the -c option directly!

Thanks again,
Best,
JC

**Comment by ewels** [comment]
Apologies @jcgrenier - I told you the wrong file name. It should be `.multiqc_config.yaml`. Config file loading is described (properly!) in the docs here: http://multiqc.info/docs/#configuring-multiqc

**Comment by jcgrenier** [comment]
Thanks a lot!! It's working now!

**Comment by leipzig** [comment]
instead of `vcftools --relatedness` Peddy https://github.com/brentp/peddy would be a nice addition

**Comment by ewels** [comment]
Sounds good, thanks for the suggestion @leipzig! Could you please submit this as a new issue (I like to have one issue per module request), along with some example data if possible?

**Comment by leipzig** [comment]
ok

**Comment by jcgrenier** [comment]
Peddy looks great, however, when we don't have any pedigree information and only want to look if specific samples are linked with each other. A standard heatmap could be enough to plot the pairwise values coming from the vcftools analysis.

Thanks!
JC

**Comment by ewels** [comment]
@jcgrenier - this would be a good addition, if you could send through some example output from vcftools I can look into writing something when I get back in mid-late February.. Please add this as a new issue, dedicated to vcftools.

Cheers,

Phil

**Comment by ewels** [comment]
Ok, closing this issue and moved the outstanding requests into two new issues (#411 and #412).
