### ISSUE TITLE
HTSeq-Count

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#315]
Would be great to have a module to parse logs from [`htseq-count`](http://www-huber.embl.de/users/anders/HTSeq/doc/count.html).

Suggested by @jcgrenier in #311

**Comment by jcgrenier** [comment]
Hi @ewels,

Here's an example of htseq-count report 

[Count.genes.HTseq.232902658_R1_trimmed.star1pass.10MMAligned.sortedByCoord.out.txt](https://github.com/ewels/MultiQC/files/529724/Count.genes.HTseq.232902658_R1_trimmed.star1pass.10MMAligned.sortedByCoord.out.txt)

Thanks a lot!

**Comment by ewels** [comment]
Brilliant, thanks!

**Comment by ewels** [comment]
Hi @jcgrenier,

Thanks for the example data - these are the raw counts output though, which isn't very helpful for MultiQC. Is there some kind of summary data from HTSeq?

Cheers,

Phil

**Comment by ewels** [comment]
Ok, I didn't think of looking at the footer! Thanks for that. What version of HTSeq were you using for the above? When I run it I get a slightly different format:

```
ENSG00000273492	0
ENSG00000273493	0
__no_feature	61688
__ambiguous	1089
__too_low_aQual	0
__not_aligned	872
__alignment_not_unique	10433
```

**Comment by ewels** [comment]
Another thing - my `stdout` didn't contain the `Genes	Sample1	Sample2` header line (which would be quite useful, to get the sample names). Also I can't see anything in [the documentation](http://www-huber.embl.de/HTSeq/doc/count.html) about running with multiple input files, yet your example has two samples. Do you mean in your above comment that the example is from your custom perl script?

**Comment by ewels** [comment]
Hi @jcgrenier,

I've just put together a module for HTSeq that produces output which is very similar to featureCounts (by design). I've just pushed it to v0.9dev - would be great if you could give it a try!

Cheers,

Phil

**Comment by jcgrenier** [comment]
Hi @ewels ,

Thanks for all of this, in fact, it was not directly the output from HTSeq. It was a file that I was creating myself from HTSeq output. I was adding a header to the files and pasting them all together. I'll give it a try really soon! 

Thanks for your help! It's really appreciated!

Best,
JC

**Comment by jcgrenier** [comment]
I tried your new module and it's working like a charm!!
Thanks again!!!

JC
