### ISSUE TITLE
preseq c_curve support

### ISSUE THREAD

**Issue by janjwesselink** [ewels/MultiQC#318]
Hi,

It would be very nice if MultiQC would also support c_curve reports from preseq (I tried changing the search pattern to 'distinct_reads' but that didn't work. The c_curve output looks like this (very similar to the gc_extrap format)

```
total_reads     distinct_reads
0       0
1000000 877396
2000000 1.55371e+06
3000000 2.07948e+06
4000000 2.49116e+06
```

Thanks very much!
Jan-Jaap

**Comment by ewels** [comment]
Thanks for this suggetion @janjwesselink - sorry it took me so long to get to it. As you say, the output was very similar so it was just a case of getting the module to recognise the files.

I like preseq, but I must say that I don't like it's output. This one has lower-caps headers, why? And almost nothing to identify the files with, quite tricky. Anyway - should work now!

Phil

**Comment by janjwesselink** [comment]
Thanks very much for updating MultiQC Phil! Yes, preseq headers are a 
bit inconsistent it seems.. Unfortunately I only got to try it today but 
it works very nicely!

Jan-Jaap

**Comment by ewels** [comment]
Great, glad it works - thanks for letting me know!

Phil
