### ISSUE TITLE
Flowcell Sub-sections per project

### ISSUE THREAD

**Issue by jcgrenier** [ewels/MultiQC#319]
Hi @ewels,

Is it possible to easily create sub-sections to regroup the statistics per flowcell? It can happen that for example I would want to regroup all the flowcells for one particular project under the same page, but would want to have different tabs or sections to know if one flowcell, that was done on a different machine or using a different technology react differently.

Thanks a lot!

JC

**Comment by jcgrenier** [comment]
Hi @ewels,

I just used the -d option, that is pretty much handling that situation now. I guess I can redirect my question to the Project Level Information (report_header_info config option). One thing that could be awesome would be a section with informations about the different flowcell. 

Thanks for your help! 
JC

**Comment by ewels** [comment]
Hi @jcgrenier,

I don't totally understand what you're asking for here.. You can specify whatever key: value pairs you like in `report_header_info`, so if you have information about the flowcells then you can add that in there if you want to.

For instance, just create a file in the directory where you're running MultiQC this time called `multiqc_config.yaml` that looks like the following:

```yaml
report_header_info:
  - Flowcell XXXXX: Information AAAA
  - Flowcell YYYYY: Information BBBB
  - Flowcell ZZZZZ: Information CCCC
```

Phil

**Comment by ewels** [comment]
ps. Yes as you say - doing [`-d -dd 1`](http://multiqc.info/docs/#sample-names-prefixed-with-directories) will add on a single folder name to the samples, so if the logs are all grouped into directory by flowcells it will prepend the flowcell name. Then you can use the report [Highlighting tool](http://multiqc.info/docs/#highlight-samples) to easily visualise differences.

**Comment by jcgrenier** [comment]
Thanks @ewels,
What I was looking for was a way to do "tabs" like what's on the principal page of MultiQC. That would have been useful to do something like this when you have thousands of samples!

Thanks for you help!

JC

**Comment by ewels** [comment]
MultiQC reports should be able to handle thousands of samples in a single report, it was avoiding multiple tabs that drove me to write it in the first place ;) But you can just create multiple reports and open them in different browser tabs if you want to see them separately / side by side? This is what I do.

I'm not sure if there's anything generic that I can add to MultiQC to help here that I can think of..

Phil

**Comment by jcgrenier** [comment]
OK, no worries then! I was already opening this up in multiple tabs too. It's more because I have a ton projects containing multiple flowcells on which I want to apply your tool! That would have been a charm to have this in one page containing multiple tabs!

Thanks!
JC

**Comment by ewels** [comment]
Ok, well beyond running a single report on all flowcells and then highlighting by FC I'm not sure that there's much else I can do here..

Note that if you want to do more long-term surveillance of FC stats it's possible to write a plugin for MultiQC that could push data to a database. This is something we do (see the [MultiQC_NGI plugin](https://github.com/ewels/MultiQC_NGI)), but there isn't anything standard yet.

Phil
