### ISSUE TITLE
Salmon metrics incomplete?

### ISSUE THREAD

**Issue by tomsing1** [ewels/MultiQC#321]
I ran Multiqc (version 0.8.0) on the output for Salmon (version 0.7.2) and it collected metrics from the `libParams/flenDist.txt` file, but nothing else. E.g. the multiqc_data/multiqc_sources.txt file only lists:

> Salmon  all_sections    sample1      /home/sample1/libParams/flenDist.txt

Looking at the [source](https://github.com/ewels/MultiQC/blob/abb6dd331193ed5446ba3353b453e6a76e2edc3d/multiqc/modules/salmon/salmon.py), I think multiqc should also parse the meta information returned by Salmon, e.g. the mapping rate. This information is stored in the`aux_info/meta_info.json` file.

It seems that multiqc is looking for a directory called `aux` - not `aux_info` in [this line](https://github.com/ewels/MultiQC/blob/abb6dd331193ed5446ba3353b453e6a76e2edc3d/multiqc/modules/salmon/salmon.py#L29). Maybe that needs to be corrected?

**Comment by ewels** [comment]
Hi @tomsing1,

Thanks for your report - MultiQC should be picking up both `flenDist.txt` and `meta_info.json` (see it's [search patterns](https://github.com/ewels/MultiQC/blob/abb6dd331193ed5446ba3353b453e6a76e2edc3d/multiqc/utils/search_patterns.yaml#L106-L110)). As you pointed out though - the code looks for the subdirectory path name to get the sample name as this isn't kept in the `meta_info.json` file.

The [test data](https://github.com/ewels/MultiQC_TestData/tree/master/data/modules/salmon) that I have for Salmon has the directory called `aux` (not `aux_info`). Perhaps this is something that the Salmon authors have changed in a recent update? It should be trivial to fix anyway, that line of code doesn't need to be so stringent (or even present).

Phil

**Comment by tomsing1** [comment]
Awesome, now the Salmon metrics are complete 😃
