### ISSUE TITLE
BioBloomTools - biobloomfilter

### ISSUE THREAD

**Issue by kunzej** [ewels/MultiQC#324]
Hi Phil,

I was wondering whether it would be possible to add biobloomtools as new module. It's a fast tool for contamination filtering, avoiding real mapping and therefore saving a lot of time working on multiple samples.
The tool itself can be found on github as well: https://github.com/bcgsc/biobloom/

I added an example logfile to the test_data repository.
The naming is fairly simple, the user is allowed to set any prefix (that should be equal to the sample name in normal cases) and the output is written to “prefix_summary.tsv” 

The output itself is a result table, listing the chosen filters (organisms) and the real and relative counts for hit/miss/shared.

Plotting this values for multiple files would be great to detect differences in the contamination profiles.

Thanks!
-Jens

[Sample1_summary.tsv.txt](https://github.com/ewels/MultiQC/files/553790/Sample1_summary.tsv.txt)
[Added ".txt" to match upload criteria only]

**Comment by ewels** [comment]
Nice, thanks @kunzej! I've heard of biobloom before but never got around to testing it out myself (it's meant to give similar results to [FastQ Screen](http://www.bioinformatics.babraham.ac.uk/projects/fastq_screen/) but be much faster, right?). Looks like it should be fairly easy to add to MultiQC anyway, will try to get to this soon.

Do you have any opinion on how this should be plotted? As with the FastQ Screen module, there is too much information here to have in a single plot. With that I plot a stacked bar of percentage hits for each organism - I'm not very happy with this representation as if you have 4 organisms it can go up to 400% which isn't very intuitive. So any better suggestions are welcome!

What are `multiMatch` and `noMatch` in your example? Are they always there?

Phil

**Comment by kunzej** [comment]
Hi,

yeah, basically thats true, its a faster version of FastQ Screen.

Well, there are multiple options for plotting, as there are for the program itself. You can “avoid” mulitMatch, by ordering the organisms and the read is assigned to the first organism it matches. 

Output description by the developers:
“Tab separated file. Contains proportion information about reads mapping to each filter. Gives a overview of your results. the hits column is the number of hits to this filter, regardless if unique. The shared column a subset of hits that also hit other filter. The multiMatch entry refers to any hits are shared at least 2 genomes. The noMatch is a subset of reads that do not match any of the filters used.”

What we do by now is going for line plots across all samples to detect differences in the contamination profile. (As we expect multiple samples means multiple samples of the same project)

I would go for 2 lines per organism 1 for hits and 1 for shared, with different plotting symbols (would be great with selection options to not overload the plot). The user can turn of organisms, mouse over on plotting symbols to get the data point information. You asked for my opinion :-)

And yes, mulitMatch and noMatch are always in the table. 
Jens 

![bloomfilter](https://cloud.githubusercontent.com/assets/19553536/19759083/8cafb2ac-9c2b-11e6-8982-5e1811863fa5.png)

**Comment by ewels** [comment]
Hi @kunzej,

Apologies for the long delay - I have at last found some time to sit down and write this module for you. I ended up emulating the output that MultiQC uses for FastQ Screen. This is something that we've recently revisited as it's one of the main visualisations that we use in our sequencing facility. Hopefully you're happy with it! If you could give it a spin and let me know that would be great.

Also, if you have any more example results files, especially some with `multiMatch` reads, that would be great. Hopefully my assumptions about how these are reported are valid, but it would be good to check that the total read counts add up in these cases 😉 

Cheers,

Phil
