### ISSUE TITLE
Qualimap coverage thresholds

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#326]
> By @vladsaveliev, 30th October _(originally [issue 7](https://github.com/ewels/MultiQC/issues/7#issuecomment-257120593))_:

Hi Phil,

I wonder what was the reason behind choosing 30x as the threshold to show coverage percentage? I would personally pick 20x as from my experience many people use that as a conservative threshold to call a germline variant. So I'm interested to see how you justify 30x :-)

By the way, currently Qualimap module also reports (hidden) 1x, 5x, 10x, 50x. I think that if the coverage is high as for deep targeted sequencing experiments, it might be useful to also report 100x, 250x, 500x, 1000x, 5000x, and more (until there is coverage). Also, another idea is add a threshold related to average depth. For instance, 1/2 of average depth. What do you think of these ideas?

**Comment by ewels** [comment]
Hi @vladsaveliev,

It's a simple answer, the same for the decisions behind most modules - that's what the people first asking for the module wanted. At our sequencing core we deliver our WGS sequencing projects with a 30X guarantee, so that's the metric that was most relevant to us.

As you say - this has been discussed before and I've gone some way to making this configurable by having the General Statistics have hidden columns for different thresholds (those visible by default can then be [configured in the user config](http://multiqc.info/docs/#customising-tables)).

I was actually thinking about this issue a few days ago - looking at people's forks of the main MultiQC repo, many seem to just change the threshold shown in reports (for both Qualimap and Picard). I guess the threshold of interest is one thing that is difficult to generalise and can be different for every group.

Adding loads of different columns to the General Statistics table to cover every preference isn't really scalable and adds to the report size and complexity. One thing I haven't done much of yet but could start here is module-specific config options. Having a section in the user config which could be set to something like this:

```yaml
qualimap_config:
  general_stats_coverage:
    - 10
    - 30
    - 50
picard_config:
  general_stats_coverage: 50
```

These config variables and available options could then be documented in the [module docs](http://multiqc.info/docs/#qualimap) for reference, and would default to their current values if not specified. Would that be a useful solution?

Regarding your second idea bout average depth, you mean plotting `mean_depth` in addition to median_depth`? Why would 1/2 of average depth be interesting?

Phil

**Comment by ewels** [comment]
Hi @vladsaveliev,

I've just added in the ability to customise the coverage thresholds shown as discussed above. This is described in the [docs](http://multiqc.info/docs/#qualimap) too.

I've done a bit of testing and it seems to work well, but if you could have a go and let me know if you run into any problems that would be great.

Thanks!

Phil

**Comment by vladsaveliev** [comment]
Awesome, thanks so much for implementing this feature Phil! I'll pull and try it out.
