### ISSUE TITLE
Picard CollectAlignmentSummaryMetrics Problems

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#327]
> From @Rmulet 21st Oct 2016 ([issue 293](https://github.com/ewels/MultiQC/issues/293#issuecomment-255338584)):

As I mentioned on Gitter, this submodule does not seem to be working. I have tried it with the two latests versions of MultiQC, using both my own data and the examples in your repository. I have also verified that the search pattern is right, which it is, and made sure that the Python script is where it should be. There must be something I am missing here.

> From @Rmulet 21st Oct 2016 ([issue 293](https://github.com/ewels/MultiQC/issues/293#issuecomment-255375384)):

Hi @ewels, I have been looking into it again and I suspect I know the reason behind the problem. I generated the `AlignmentSummaryMetrics` data with the `CollectMultipleMetrics.jar` tool, which allows to run in a single command several programs within the Picard package. The output of this this program is virtually identical to that of the standalone `CollectAlignmentSummaryMetrics.jar`, with a few differences in the headers and less empty lines at the end. Interestingly, this does not happen with `CollectInsertSizeMetrics`, which I generate in the exact same way but is detected anyway.

I believe your example data already reflects the differences between `CollectMultipleMetrics.jar PROGRAM=CollectAlignmentSummaryMetrics` and `CollectAlignmentSummaryMetrics.jar`, but I am attaching some examples of my own anyway.

[216_D_18666.CollectMultipleMetrics.txt](https://github.com/ewels/MultiQC/files/544380/216_D_18666.CollectMultipleMetrics.txt)
[216_D_18666.AlignmentSummaryMetrics.txt](https://github.com/ewels/MultiQC/files/544382/216_D_18666.AlignmentSummaryMetrics.txt)

> From @ewels:

Aha, yes that would explain it. I think I had to adjust the code for the insert size module to understand output from collectmultiplemetrics, so I'll presumably need to do the same for alignment summary metrics.

Thanks for the example files! I'll let you know when it's fixed.

Phil

**Comment by ewels** [comment]
Hi @Rmulet,

Firstly - sorry it's taken me so long to get to this issue. I've just had a go with your example data and pushed an update that should fix the problem. Let me know if you still run into any problems.

Phil

**Comment by Rmulet** [comment]
Hi @ewels, thanks for fixing the issue. I will definitely tell you if I come across any other problem!
