### ISSUE TITLE
RSeQC module improvements

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#330]
Several minor tweaks for rseqc:

- [x] _Inner Distance_ shows up in general statistics for SE data (0bp)
- [x] _Proper Pairs_ shows up in general stats for SE data (0%)
- [x] Bunch of irrelevant stats in _bam stats_ also show up. Can be hidden.

**Comment by ewels** [comment]
@Hammarn - is all of this already merged?

**Comment by Hammarn** [comment]
Yes, as of PR #345
