### ISSUE TITLE
ImportError: cannot import name 'logger'

### ISSUE THREAD

**Issue by ofonov** [ewels/MultiQC#332]
I have tried to run multiqc on OSX. I am getting  an import error. In one of the other issues there was a suggestion that reinstallation of matplotlib can help, however it did not in my case. Do you have any other suggestions how to make the tool work?
```
$ multiqc --help
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/multiqc", line 34, in <module>
    from multiqc import logger, plots, __version__
ImportError: cannot import name 'logger'
```

**Comment by ewels** [comment]
Hi @ofonov,

How did you install MultiQC? Here it's saying that you don't have the `logger` Python module installed. These dependencies are usually resolved automatically when you install MultiQC, however you can install the module manually with `pip install logger` (or other equivalents).

Let me know how you get on!

Phil

**Comment by ofonov** [comment]
Thanks for the rapid response!
I have installed multiqc through pip. I have installed logger, however it did not fix the problem - I get the same error.

**Comment by ewels** [comment]
Hmm, this is difficult to debug remotely. Sometimes weird stuff happens with python paths, so worth checking that both python and pip are in the same place (eg. if you're using python with conda but pip is being called on the system python or something weird). I doubt that it's the Python version as the Travis CI testing runs on Python v3.5.2 and it installs fine. You can see the log from the latest test [here](https://travis-ci.org/ewels/MultiQC/jobs/170144610).

Can you confirm how you have python and pip installed, their paths and paste any log / errors from the installation?

**Comment by ofonov** [comment]
Hi, thanks for the tip about the python paths. It appeared that in my .bash_profile I had several paths for different installations of python. I removed the old ones and multiqc functions now!

**Comment by ewels** [comment]
Ok, great that you found it! Thanks for letting me know.. :)
