### ISSUE TITLE
Better samtools flagstat alignment plot

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#334]
Samtools flagstat seems to be the main way that people work out percentage aligned for some aligners (I'm looking at you, bwa). The current beeswarm plot is big and confusing. Add a nicer stacked barplot, comparable to those from other tools, just for percentage mapped (QC-passed / QC-failed).

**Comment by ewels** [comment]
We already have this for `samtools stats`. I can just use that instead 😄

**Comment by gk-bioin4m8x** [comment]
Hi @ewels ,

MultiQC worked great for my multiple samtools flagstat files and generated multiqc_report.html, multiqc_general_stats, multiqc_samtools_flagstat and multiqc_sources. 
However, I am unable to get any plots to visualize the data in a more clear manner. If I try to download plot images, it says "It is not possible to export dot plot images from reports". 
Please guide.

Thanks!
