### ISSUE TITLE
RSeQC gene body coverage plots

### ISSUE THREAD

**Issue by pmenzel** [ewels/MultiQC#340]
Hi,
I have one issue with the sample names being overwritten for the rseqc gene body coverage module multiqc.modules.rseqc.gene_body_coverage. 
I use multiqc -d .  and my subdirectories have the XXX.geneBodyCoverage.txt files.
What happens is that multiqc gets the sample name from inside the files, which is the same in all my directories. The problem is, that the directory name is not prepended in this case, so that the one sample is overwritten, as shown in the debug output:
```
multiqc.modules.rseqc.gene_body_coverage           [DEBUG  ]  Duplicate sample name found! Overwriting: XXXX
multiqc.modules.rseqc.gene_body_coverage           [DEBUG  ]  Duplicate sample name found! Overwriting: XXXX
multiqc.modules.rseqc.gene_body_coverage           [DEBUG  ]  Duplicate sample name found! Overwriting: XXXX

```
with XXXX being the sample name.
So yeah, please make the directory prefix working there..

thanks!
Peter

PS: multiqc is awesome :)

**Comment by ewels** [comment]
Ah, you're completely correct - sorry for this! Actually working on MultiQC now, so will push a fix straight away.

Phil

**Comment by pmenzel** [comment]
Yep, works now! Thanks for the fast fix!
