### ISSUE TITLE
module request: STAR ReadsPerGene

### ISSUE THREAD

**Issue by pmenzel** [ewels/MultiQC#342]
Hello,

when STAR is provided with a genome annotation and option `--quantMode GeneCounts`, it produces the file `ReadsPerGene.out.tab`, which contains read counts for each gene in the annotation and four extra lines for unmapped reads etc. File head looks like:
```
N_unmapped      2360828 2360828 2360828
N_multimapping  1812915 1812915 1812915
N_noFeature     935444  1064767 27174828
N_ambiguous     1210781 555786  21975
FBgn0085804     0       0       0
FBgn0267431     22      17      5
FBgn0039987     0       0       0
FBgn0058182     2       0       2
FBgn0267430     6       3       3
FBgn0266747     0       0       0
...
```
The three columns are for unstranded, stranded/first-strand, and stranded/second-strand.
There is no sample name inside the file.
The idea for a barplot here would be to have one field for each of the N_ lines and one field for the sum of the remaining lines and then probably 3 bars per file, corresponding to the 3 columns.. but maybe three bars per file does not fit into the multiqc framework..?

Thanks!

**Comment by ewels** [comment]
Hi @pmenzel,

Sounds like a plan. Is the filename always `ReadsPerGene.out.tab`? We'll have to figure out how to get the sample name if that is the case. What happens if you run STAR on several samples in one folder, do these files get overwritten?

It's not possible to have the stranded information in the same barplot (too many dimensions), but we could have tabs above the plot to switch between total / +ve / -ve / unstranded.

Phil

**Comment by pmenzel** [comment]
> Sounds like a plan. Is the filename always ReadsPerGene.out.tab? We'll have to figure out how to get the sample name if that is the case. What happens if you run STAR on several samples in one folder, do these files get overwritten?

When running STAR, one can specify the option `--outFileNamePrefix`, which can be a path and it defaults to `./`. Thus, the normal output files would be `Log.final.out`, `ReadsPerGene.out.tab`, etc. inside the directory where STAR is run.

I usually set the  `--outFileNamePrefix` to `./samplename/` so that the files end up in subdirectories.

However, one could also use  `--outFileNamePrefix ABC`, then the output files will be called `ABCLog.final.out`, `ABCReadsPerGene.out.tab`. etc.

This means that the file names are not really deterministic, but the suffix is. So one could deduce the sample name to be everything before that suffix.

**Comment by ewels** [comment]
Ok great, so perhaps I can try to take the filename prefix and if there is none I can take the directory name.. Not perfect but should work for most people I guess.

Phil

**Comment by pmenzel** [comment]
Isn't it a similar problem like the module that parses the `Log.final.out` to get mapping stats? Probably there you are just looking for files that have specific content inside.. But then you can do the same and look for the `N_unmapped` line at the beginning of the file here..

**Comment by ewels** [comment]
Yes - I just looked into the code, it looks like I just take the filename prefix there. What sample names do you get when you run MultiQC on your STAR results with `--outFileNamePrefix` set to directories?

This is a good example of where our log files always look like `samplename.Log.final.out`, and as no-one has complained (that I remember), it's just stayed that way.

Phil

**Comment by pmenzel** [comment]
I always use `-d` and thus have the directory name as sample name in the report. I can check tomorrow what happens if I omit `-d`.

**Comment by pmenzel** [comment]
Now I tested multiqc behaviour for `STAR --outFileNamePrefix ./<samplename/`.
With the option `-d` the sample names in the report are properly called `samplename |` and without `-d` the sample name is empty, and it gets overwritten by the next one and so on (` [DEBUG  ]  Duplicate sample name found! Overwriting:`)

**Comment by pmenzel** [comment]
But that makes sense, and I think the same could be applied for the ReadsPerGene.out.tab files..

**Comment by ewels** [comment]
Ok - I think that maybe I'll do the same thing for the main STAR logs too then - if the sample name comes back empty (no prefix), then I'll take the last directory name. Thanks for checking that for me!

**Comment by pmenzel** [comment]
ok, I can test once you are done. thanks.

**Comment by ewels** [comment]
Hi @pmenzel,

I've just had a proper sit down and think about this request. I think that it could be problematic, as it requires parsing what is presumably quite a large file (I'm guessing that it contains an entry for every gene). Doing this for one or two samples would be fine, but people regularly run MultiQC on very large sample numbers, and this could start being a bottleneck. I'm trying to put together some example data now to see _how_ slow it is - if you have any files you could send over that would help.

I've fixed the filename prefix issue for the main  log files (see commit reference above), so the directory name is now taken if there was no prefix.

Cheers,

Phil

**Comment by pmenzel** [comment]
Hi Phil,

actually the files are not that big, around 400kb for normal Drosophila RNA-seq run, I will send it to you by email. 

Peter

**Comment by ewels** [comment]
Hi @pmenzel,

I've just written a draft version of this and it seems to be working ok (0e120aa882885f65aed3b78d26c994fe4c06b529). I did a quick test with a single test Human dataset and it seemed to add about 1 second to the total execution time. I think that this is probably acceptable.

If you could test it and let me know how you get on that would be great. I'll come back tomorrow and tidy up the labelling and stuff but I think the core functionality is basically done.

Phil

**Comment by pmenzel** [comment]
Works well and fast for me. But please remove the "total" tab, and make "unstranded" the default, there is no meaning to have rowsums here.

**Comment by ewels** [comment]
Ok, so unstranded is just the sum of both strands? Kind of a confusing name..

**Comment by pmenzel** [comment]
The first column with numbers contains the counts for unstranded, the second column contains the counts for forward-stranded libraries and the second column contains the counts for reverse-stranded libraries, (see chapter 7 in the [STAR manual](https://github.com/alexdobin/STAR/blob/master/doc/STARmanual.pdf)). So no row-sums are needed here, because STAR calculated all three possible count values already.

**Comment by ewels** [comment]
Yeah, I found that. So the labels reflect the type of library, not the type of read - that's the bit that I found confusing. I guess I'm used to other tools that use the same labels to mean different things.

**Comment by ewels** [comment]
Ok - I've removed the total count and added a bit of explanation text / changed the labels slightly. Let me know if you agree with what I've written! :)

**Comment by pmenzel** [comment]
Looks good now. Thanks!
