### ISSUE TITLE
Export plots crops dataset

### ISSUE THREAD

**Issue by ESjokvist** [ewels/MultiQC#346]
Hello,

I have run multiqc on a star output, and get a html file with a nice plot. The entire plot is not shown initially, not all samples, but when I drag the bottom of the plot it shows all samples. When I try to export the plot only the initial subsection of the plot is exported. I can find no settings to edit this to give me the whole plot.

I would have included the html file here, but html files are not supported, something else to think about.

Thanks
Elisabet

**Comment by ewels** [comment]
Hi @ESjokvist,

Thanks for the bug report - I've not come across this behaviour before. As you guessed, I'd like to see the report if possible. GitHub won't allow you to upload HTML files as a security precaution, unfortunately there's nothing that I can do about this. You can create a `.zip` file with the report and attach that though. Alternatively, you can e-mail the report to me or send it using [gitter](https://gitter.im/ewels/MultiQC).

Also, what web browser are you using? This could be relevant.

Many thanks,

Phil

**Comment by ESjokvist** [comment]
Hi Phil,

Of course, silly of me. Attached as zip now. 
I'm using Firefox.

[Star_multiqc.zip](https://github.com/ewels/MultiQC/files/609512/Star_multiqc.zip)

**Comment by ESjokvist** [comment]
Hi again,

I just tried chromium browser with the same result.

Thanks,
Elisabet

**Comment by ewels** [comment]
Ahh, I understand - you mean that the sample labels are hidden. Note that it's not hiding any bars or data, it's just that if the text doesn't fit on the plot, every nth sample label is hidden.

This is automatic behaviour by the javascript plotting library, not something that I can easily change. However, it is possible to get them to show by making the plot taller as you found. You can also export taller plots (with all labels showing) by changing the file dimensions. For instance, I was able to generate an image with all labels just now using these settings:

![image](https://cloud.githubusercontent.com/assets/465550/20571902/88aa8810-b1a9-11e6-9db5-64cea1e0ede6.png)

1. You'll need to untick 'Aspect Ratio', as you want the plot to be tall and narrow
2. Increase the height of the plot lots
3. _Plot scaling_ defines how large the text should be relative to the chart. Usually for print you want bigger text than you have on your computer monitor, so by default this is 2. Dropping it to 1 makes the font smaller and more labels fit.

Finally - MultiQC is able to make dynamic plots like these, but it can also generate static images when it runs. These always show all sample labels. You can specify `--flat` to get a report with these (though then highlighting / hiding etc won't work), or `--export` to just create these and save them as files alongside the report.

I hope this helps! Let me know how you get on.

Phil

**Comment by ESjokvist** [comment]
Hi Phil,

Oh, I had not tried enough settings! It works now with the settings you suggest. I tried fiddling with the settings a bit, but got the same range of samples shown every time, so figured it was a bug.

Thanks!

**Comment by ewels** [comment]
No problem! Yes, if you don't untick the _Aspect Ratio_ button then the width is pushed up along with the height each time you change it. Maybe I should make it unticked by default. I might add a FAQ point on this. Thanks, and glad it's working now!
