### ISSUE TITLE
Number formatting in tooltips of barplots (and others?)

### ISSUE THREAD

**Issue by t-neumann** [ewels/MultiQC#348]
I have previously run across the issue that I am supplying already pre-calculated percentages to the barplot plotting method. These percentages are quite low and in the tooltips of the final plot, they are apparently rounded to the next integer, so most of them are either 0 or 1.

It would be cool if some number formatting could be applied to these values for the tooltip like showing more decimals.

**Comment by ewels** [comment]
Hi @t-neumann,

I've just added to the core barplot functionality. There are now a few more options, namely `tt_decimals` and `tt_suffix`, so you can now customise this. For example:

```python
pconfig = { 
    'tt_decimals': 2,
    'tt_suffix': '%',
}
```

I just implemented this for a new FastQC overrepresented sequences plot, so you can see it in action [here](https://github.com/ewels/MultiQC/blob/master/multiqc/modules/fastqc/fastqc.py#L592-L593).

Phil

**Comment by t-neumann** [comment]
Perfect - works like a charm.

**Comment by ewels** [comment]
The docs had broken and were a bit behind - now fixed and updated. New features documented here: http://multiqc.info/docs/#bar-graphs
