### ISSUE TITLE
General Statistics - custom scatter plot

### ISSUE THREAD

**Issue by avilella** [ewels/MultiQC#350]
Hi,

This is a feature request for something that may already be implicitly there, as I see this has been mentioned in the past, as a core functionality or in the context of NGI plugins:

https://github.com/ewels/MultiQC/issues/184
https://github.com/ewels/MultiQC/issues/297

My idea is to have a scatter plot (xyplot) where the x and y axes are chosen dynamically from x and y drop-down lists of values in the summary table, and the colour of the dots in the plot (z value) is also chosen from a third drop-down list that includes both categorical and numerical data.

I also got a question/feature-request about meta data, but I'll leave that for another ticket:

https://github.com/ewels/MultiQC/issues/200

**Comment by ewels** [comment]
Hi @avilella,

Can I just clarify your suggestion - you mean having a general-purpose scatter plot, where you could select data from any column in the _General Statistics_ table?

That could definitely work, and it wouldn't really add any extra bloat to the reports as everything that's required is already there. How would you handle samples that don't have all of the required values? I guess any that miss either `x` or `y` would be skipped (with a warning) and any that miss `z` would be grey or something..

Phil

**Comment by avilella** [comment]
Correct, that's what I was thinking.

**Comment by ewels** [comment]
Hi @avilella,

I've just added support for this - you should now see a new button above every table saying _"Plot"_. Hopefully everything is self-explanatory from there, please let me know if you run into any problems!

Phil

**Comment by mathieu-massaviol** [comment]
Hi @ewels 

@avilella and you both mentioned a feature i think could be interesting to implement. The possibility to color the dots thanks to a third column of the table, selected in a drop-down list like x and y axes. I think it would improve visualisation of tables' data.

Mathieu

**Comment by ewels** [comment]
Hi @mathieu-massaviol,

You can already do this somewhat, by using the Highlight Samples feature in the report. See https://multiqc.info/docs/#highlight-samples

Phil
