### ISSUE TITLE
scatter plot scaling

### ISSUE THREAD

**Issue by avilella** [ewels/MultiQC#370]
Rather than a bug or feature request, this is just to report on scalability of scatter plots with custom_data.

I created a 3x5000 file, and generated the scatter plot for it. 
Generates an html of 1.2Mb of size.
Took 1.3 seconds to generate.
Browsing over it feels snappy, no issues I can find.

```
[INFO   ]         multiqc : This is MultiQC v0.9.dev0
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
[INFO   ]  custom_content : custom_data_scatter: Found 5000 samples
[WARNING]         multiqc : Deleting    : multiqc_report.html   (-f was specified)
[INFO   ]         multiqc : Report      : multiqc_report.html
[WARNING]         multiqc : Deleting    : multiqc_data   (-f was specified)
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete

real    0m1.375s
user    0m1.274s
sys     0m0.089s
```

<img width="1283" alt="screen shot 2016-12-21 at 18 03 37" src="https://cloud.githubusercontent.com/assets/158007/21398642/5653c6f0-c7a8-11e6-847b-4b2fa0e566c1.png">

**Comment by ewels** [comment]
Hah, thanks @avilella 😉 

I'm not particularly worried about the generation time, it's more the browser speed and report file size. Also with people who are less careful for you - for example generating a report with gene counts for 100 RNA samples (2 million data points).

Phil
