### ISSUE TITLE
Different behaviour with many fastq files

### ISSUE THREAD

**Issue by annaquaglieri16** [ewels/MultiQC#385]
Hi, 

I have just ran multiqc on 560 fastqc reports. The final reports behaves a little bit differently that with only few fastq files. For example I cannot swipe onto the plot and see the name of the sample that I am looking at, or when I select the option to highlight on the plot only samples which failed a QC it does not update the plot. Have you encountered this before?

Thanks for your help, 

Anna

**Comment by annaquaglieri16** [comment]
Hi there, 

I am sorry, I have just realised about the forced interactive options in case of a great number of samples. 

Problem solved, 

Anna

**Comment by ewels** [comment]
Hi Anna,

Please see the docs here: http://multiqc.info/docs/#large-sample-numbers

Shout if you have any problems! I should probably make this more obvious - might put in a warning at the top of the report when relevant for a future release..

Cheers,

Phil

**Comment by ewels** [comment]
Ah - you got it whilst I was writing my reply :) Glad it's ok.

Phil
