### ISSUE TITLE
Check for existing report first 

### ISSUE THREAD

**Issue by Hammarn** [ewels/MultiQC#388]
It has happen numerous times that I've forgotten to add the `-f` flag when redoing a MultiQC analysis in a folder. MultiQC is nice and gives you a warning that an old report exists and does not overwrite it by default. The issue is that this is the last thing that happens in the execution, which can be after several minutes or longer for big reports.

In short;
It would make a lot more sense for MultiQC to start by checking for old reports by the same name.

**Comment by ewels** [comment]
This is already implemented. It actually does two checks - one before it runs (as suggested) for `multiqc_report.html` and then again before it actually writes the new report. I guess you're running with MultiQC_NGI which is changing the report file name. MultiQC can't know what this will be before it runs, so it can't warn about overwriting before it runs. Sorry!

If this isn't the case, please reopen :)

**Comment by ewels** [comment]
ps. You can also make MultiQC force overwrite by default with a config setting I think.
