### ISSUE TITLE
Qualimap module exception

### ISSUE THREAD

**Issue by Shellfishgene** [ewels/MultiQC#390]
Hi!
The Qualimap module has problems, see below. The qualimap report in question is attached, but I got the same error also with qualimap reports for other bam files. It's from qualimap v.2.2.1. Maybe you can have a look after the vacation :).
[qualimap_report.tar.gz](https://github.com/ewels/MultiQC/files/716936/qualimap_report.tar.gz)

```
[ERROR  ]         multiqc : Oops! The 'qualimap' MultiQC module broke...
                    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues
                    (if possible, include a log file that triggers the error)
============================================================
Module qualimap raised an exception: Traceback (most recent call last):
  File "/usr/local/bin/multiqc", line 344, in multiqc
    output = mod()
  File "/usr/local/lib/python2.7/dist-packages/multiqc/modules/qualimap/qualimap.py", line 40, in __init__
    n['BamQC'] = QM_BamQC.parse_reports(self)
  File "/usr/local/lib/python2.7/dist-packages/multiqc/modules/qualimap/QM_BamQC.py", line 54, in parse_reports
    report_sections(self)
  File "/usr/local/lib/python2.7/dist-packages/multiqc/modules/qualimap/QM_BamQC.py", line 324, in report_sections
    'extra_series': extra_series,
  File "/usr/local/lib/python2.7/dist-packages/multiqc/plots/linegraph.py", line 89, in plot
    elif type(pconfig['extra_series']) == list and type(pconfig['extra_series'][0]) == dict:
IndexError: list index out of range
============================================================

```

**Comment by sbcrg** [comment]
Hi,
I am getting exactly the same error!
My qualimap folder contains HTML and PDF results from "qualimap rnaseq" analysis. It is also from version 2.2.1.
Cheers

**Comment by vladsaveliev** [comment]
Hi all, I think this bug has already been fixed in master, see the latest commit by @chapmanb https://github.com/ewels/MultiQC/commit/123d22179e242a013ab4568cf1a34020aa4cebc1

**Comment by Shellfishgene** [comment]
Indeed, after updating to the dev version from git the error is gone.

**Comment by ewels** [comment]
Great that you managed to resolve this! Thanks for the pointer @vladsaveliev!
