### ISSUE TITLE
new module with RNA-SeQC report

### ISSUE THREAD

**Issue by emmanuelaaaaa** [ewels/MultiQC#394]
Hi Phil,

Thank you for this great QC tool! I was wondering whether it would be possible to add the output from RNA-SeQC (http://archive.broadinstitute.org/cancer/cga/rna-seqc) as a new module. It creates an html report on its own but it would be nice if we could have all the QC information in one report. I am not sure all the information that it has is necessary, but it has some key QC measures that are very handy such as the transcript-associated measures (exonic/intronic percentages, number of genes detected etc.), the strand specificity and the plots of the coverage for 3’ bias. I realise that RSeQC covers some of those measures but this has some extra features and a more complete report, in my opinion.

I am attaching an example of the pdf [RNA_Seq_metrics.pdf](https://github.com/ewels/MultiQC/files/751067/RNA_Seq_metrics.pdf) saved from the htlm report that it gives. I am also attaching the table with the metrics [metrics.txt](https://github.com/ewels/MultiQC/files/751080/metrics.txt) that includes most of the information for the html. Finally, I am also attaching an example png:

![meancoveragenorm_high](https://cloud.githubusercontent.com/assets/7386392/22600621/3b0b2408-ea33-11e6-8a07-593630cf2cc5.png)

for the coverage. If any other files would be helpful (such as the htlm that I can't directly upload) I’d be happy to send you examples of anything you may need.

Thank you!
Emmanouela

**Comment by ewels** [comment]
Hi @emmanuelaaaaa! Thanks for this - RNA-SeQC is a tool that's been in the back of my mind for a while to add to MultiQC. As I don't use it myself it's been a low priority though, as I don't have the files that it produces. So this is great, thanks! I'm away at the moment, but I'll definitely look into writing this when I'm back in a couple of weeks (after the more urgent bugs are fixed).

Are the file names that RNA-SeQC produces always the same? Does it always make all of them?

Phil

**Comment by emmanuelaaaaa** [comment]
Hi Phil, 
Thanks for getting back to me!
Yes, the naming scheme is always the same. There are some folders that are produced per sample (so depend on the name of the samples) for more detailed metrics but all the summary metrics are using the same file names always. There are a few flags for suppressing some of the output (as explained here: [rnaseqc_page](http://archive.broadinstitute.org/cancer/cga/rnaseqc_run) ) but I have never used them so I am not really sure what exactly gets suppressed. I am happy to upload a zipped folder with an example of all output for you to download, if that's going to help. Let me know when you're back and I'll produce a mini-example for you.
Emmanouela

**Comment by ewels** [comment]
Hi Emmanouela,

I'm back now and starting to work my way through MultiQC issues. If you could upload a zip file of all of the output files from RNA-SeQC as they are produced, that would be brilliant. I will add it to the [MultiQC_TestData](https://github.com/ewels/MultiQC_TestData) repo (or you can open a PR there if you prefer). Then I can write the module around that, plus it will be tested automatically every time a change is pushed to MultiQC.

Phil

**Comment by emmanuelaaaaa** [comment]
Hi Phil, 

That sounds great! I have run a mini-example with two RNA-Seq samples. I can't attach the file here because even zipped it's 60MB. I could trim it down to the most essential bits, but it will probably be more helpful if you get an exact example to what you get when you run the program. Instead I am sending you an email with oxfile and you can download it directly from there. The link will be active for 7 days. If for whatever reason you can't get it in time, let me know and I will reupload. 
 
Let me know if I can do anything else to help.
Emmanouela

**Comment by ewels** [comment]
Perfect, thanks @emmanuelaaaaa! Are you happy for me to add the key files to [ewels/MultiQC_TestData](https://github.com/ewels/MultiQC_TestData)?

**Comment by ewels** [comment]
Wow there's a lot of stuff in here. Most of the filesize seems to be within a handful of files, which contain transcript-specific / locus-specific information which MultiQC wouldn't use anyway. I'll throw the rest onto the testing repo if that's ok, doesn't hurt to have files which aren't used - good to have them there for future reference.

**Comment by emmanuelaaaaa** [comment]
Sure, no problem, it's already published data.

**Comment by djf604** [comment]
@ewels Have you made any progress in writing this module? I'm asking because I need it, and soon.
If you are nearly finished writing, then I can wait a couple days. But if not, I'd be glad to take a stab at writing it up myself. Just so we're not duplicating work here!

**Comment by ewels** [comment]
Hi @djf604,

I haven't started on the module yet, though it's [next on my list](https://github.com/ewels/MultiQC/projects/1). I've been slightly intimidated by how much there is to parse there, but I could try to make a start on it tomorrow with just a few metrics to begin with.

What exactly do you need (and what for, out of curiousity? 😉  ). Would the metrics suggested above by @emmanuelaaaaa be sufficient?

- [ ] Exonic percentage
- [ ] Intronic percentage
- [ ] Number of genes detected
- [ ] Strand specificity
- [ ] Gene coverage plot (showing 3’ bias)

Phil

**Comment by djf604** [comment]
Is there a lot to parse? I suppose I could be totally wrong, since I'm not _very_ familiar with RNA-SeQC, but the metrics.tsv files included in the top level of the output directory seems sufficient to me. It has basically everything from the high level report.html file.

I was planning to also include the bottom 1000, middle 1000, and top 1000 transcripts data as well, but that's a little less straight forward. The metrics.tsv file has those, but only for the middle 1000 (and it's also missing one of the data points. wat.), so I'd have to get a little fancier to extract those. Recreating the plots from the chart would be nice as well, but that's not an immediate need of mine.

Like I said, I'm willing to give it a go if you're swamped with other stuff (it's cool this tool is being actively developed!). At a first pass I'm really impressed with how well written and easy to extend your program is here, unfortunately I find that to be a little too rare in the bioinformatics world.

**Comment by ewels** [comment]
You can see the example files given by @emmanuelaaaaa [here](https://github.com/ewels/MultiQC_TestData/commit/ce1475cdc0a3834b900b0a05fcc2b0a423d6ad67). But as you say, starting with the main `metrics` file should cover many of the points pretty quickly.

I'm in Europe so I'm about to go to bed - if you want to have a stab at writing the module then go for it! :) Otherwise I'll try to write this tomorrow if I can - it shouldn't take me very long as I can write basic modules with my eyes closed these days. Let me know if you make a start. 

Phil

**Comment by djf604** [comment]
If that's the case then you could probably do it much faster! I would have to learn your module framework, so that would take a bit of time by itself.

If you decide you'd rather let someone else do it, let me know!

**Comment by emmanuelaaaaa** [comment]
I agree the metrics file includes most of the metrics and should be sufficient. The only thing that I would think is useful apart from that, is the coverage plots and the gap length histogram. They would also fit in well with the rest of the amazing plots of multiQC :) But if it is a pain then no worries.

**Comment by ewels** [comment]
Hi both,

No problem at all to add that stuff. I've just made a start on it, see above commit. Now adds three columns to the General Statistics table. I'll add more next week (apologies, been a busier day today than I was expecting).

Phil

**Comment by djf604** [comment]
Thanks so much, your lab is awesome. Keep up the great work!

**Comment by ewels** [comment]
Hi again,

I just wrote a bunch more for the module - it now has a plot showing the sense / antisense read counts, the high / medium / low norm coverage and a sample correlation heatmap.

Current behaviour for the heatmap is that it shows Spearman by default, Pearson if Spearman not found and nothing if neither is found. I'd like to make this default setting configurable in the MultiQC config.

Let me know how you get on with this!

Phil

**Comment by ewels** [comment]
ok, configurable! Documented here: http://multiqc.info/docs/#rna-seqc

Let me know if anything breaks or is missing and I will reopen the issue.

Cheers,

Phil

**Comment by djf604** [comment]
Wow @ewels, I'm glad you took this on, I might have still been reading the documentation! Thanks so much for doing this!

**Comment by ewels** [comment]
No problem! It's nice to get this one written, it's been in the back of my mind for a while, and wasn't too tricky at all in the end.. 😄  (well written log files!)

**Comment by pascalg** [comment]
Hi Phil,

I noticed the correlation plot is only shown for a single RNA-SeQC report. I am running RNA-SeQC every time new samples are sequenced, but can't do that on all samples ever sequenced combined. You think it would be possible to implement some sort of switch to look at plot from different report?

Cheers,
Pascal

**Comment by ewels** [comment]
Hi @pascalg,

Yes that should be possible (as separate plots of course). Please open a new issue for that.

Phil

**Comment by adomingues** [comment]
Hi @ewels,

I am coming back to this issue because `RNAeq-QC` has been re-written in python, with some added functionality. Somehow the output directory structure also changed, which means that `multiqc` not longer produces a report:

```bash
multiqc .

[INFO   ]         multiqc : This is MultiQC v1.7
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
Searching 45 files..  [####################################]  100%          
/projects/conda/envs/multiqc/bin/multiqc:495: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logger.warn("No analysis results found. Cleaning up..")
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete

rnaseqc --version
RNASeQC 2.3.4
```
Are there any plans to modify multiqc's parsing to adapt to these changes?

cheers

**Comment by ewels** [comment]
Moved discussion here: https://github.com/ewels/MultiQC/issues/1059
