### ISSUE TITLE
[ Picard module Issue ] Insert Size Metrics

### ISSUE THREAD

**Issue by Katospiegel** [ewels/MultiQC#397]
I'm trying multiqc and I got this error when applaying to a folder containing fastqc, qualimap, bowtie and picard files. The rest of the files were parsed correctly.  

```
[ERROR  ]         multiqc : Oops! The 'picard' MultiQC module broke... 
                    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
                    (if possible, include a log file that triggers the error) 
============================================================
Module picard raised an exception: Traceback (most recent call last):
  File "/mnt/home/users/pab_001_uma/vivar/programs/multiqc/scripts/multiqc", line 346, in multiqc
    output = mod()
  File "/mnt/home/users/pab_001_uma/vivar/programs/python-packages/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/multiqc/modules/picard/picard.py", line 50, in __init__
    n['InsertSizeMetrics'] = InsertSizeMetrics.parse_reports(self)
  File "/mnt/home/users/pab_001_uma/vivar/programs/python-packages/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/multiqc/modules/picard/InsertSizeMetrics.py", line 77, in parse_reports
    self.picard_insertSize_samplestats[s_name]['meansum'] += (rp * mis)
TypeError: can't multiply sequence by non-int of type 'float'
============================================================
```

Thanks

**Comment by ewels** [comment]
Thanks for the report @Katospiegel - I'm away at the moment but will have a look in a week or so when I'm back. Is it possible to send over a file which triggers this error so that I can replicate it?

Phil

**Comment by ewels** [comment]
Hi @Katospiegel,

Looking at the code and the error, I think that you must have something strange going on in your Picard input file that is breaking the parsing. This error is due to MultiQC trying to multiple a string by a number, but these two variables should both have numbers.

If you could send over your input file then I'll look into it. Without that I can't replicate the error though, so there's not much that I can do.

Cheers,

Phil

**Comment by ewels** [comment]
Hi @Katospiegel,

I'm closing this issue now as I can't do anything without some example data from you. Feel free to reopen / send through the data if you get a chance!

Phil
