### ISSUE TITLE
Overwrite click defaults from config

### ISSUE THREAD

**Issue by robinandeer** [ewels/MultiQC#40]
Something like this:

```python
# update the context with new defaults from the config file
context.default_map = context.obj
```

**Comment by ewels** [comment]
Avoids [this](https://github.com/ewels/MultiQC/blob/af0b4b43093412a6973f6fbe96cefce3f3133550/scripts/multiqc#L65-L69) chunk of code where different variable names are overwritten.

**Comment by ewels** [comment]
@robinandeer presumably referring to [this](http://click.pocoo.org/5/commands/#overriding-defaults)

Doesn't look exactly like what I had in mind though, and I'm not sure that it would make the code any less complex. Closing this issue for now until I have a better idea of how to write this nicely.
