### ISSUE TITLE
'odict_values' object does not support indexing in rseqc/junction_saturation.py module

### ISSUE THREAD

**Issue by adamlabadorf** [ewels/MultiQC#400]
Hi,

I recently ported the rseqc codebase to python3. When I used multiqc to scan through the `junction_saturation.py` output I get the error reported below. Since rseqc was never released for python3, and the offending syntax is permitted in python2, I assume this bug never arose before as people using the rseqc module were doing so with python2. I implemented a simple fix that should be cross python version compatible in my fork and would be happy to make a pull request if this seems like a good idea.

Thanks. I love MultiQC, it makes my every bioinformatic day brighter.

```
============================================================
Module rseqc raised an exception: Traceback (most recent call last):
  File "/projectnb/bubhub/conda_root/user_envs/labadorf/MultiQC_rseqc_bug/lib/python3.5/site-packages/multiqc-1.0.dev
    output = mod()
  File "/projectnb/bubhub/conda_root/user_envs/labadorf/MultiQC_rseqc_bug/lib/python3.5/site-packages/multiqc-1.0.dev
    n['junction_saturation'] = junction_saturation.parse_reports(self)
  File "/projectnb/bubhub/conda_root/user_envs/labadorf/MultiQC_rseqc_bug/lib/python3.5/site-packages/multiqc-1.0.dev
    total = self.junction_saturation_all[s_name].values()[-1]
TypeError: 'odict_values' object does not support indexing
============================================================
```

**Comment by ewels** [comment]
Hi @adamlabadorf,

Thanks for reporting this problem! It is certainly my intention that MultiQC should work with both Python 2 and 3, so please do submit a PR if it's an easy fix (I'm away at the moment but will be back next week). I'm a little surprised that it hasn't been picked up already, as I have automated runs set up on Travis for both Python versions. If you're able to send through some logs that trigger the error that would also be great, I'll add them to the ewels/MultiQC_TestData repo for the automatic testing (or feel free to submit a PR to there too).

Thanks!

Phil

**Comment by ewels** [comment]
Hi @adamlabadorf,

I've just pushed an update which should fix this. Turns out that the only test file I had for this submodule was all zeroes, so was being skipped by Travis every time. I [added a new test file](https://github.com/ewels/MultiQC_TestData/commit/c8f87ac23a5c028d0dd4953d9caefb3713970bdb) and the error then showed up for Python 3.

Anyway, fixed and seems to work now. Hopefully should spot any future problems too!

Thanks for reporting this. Let me know if you run into any other trouble.

Phil

**Comment by adamlabadorf** [comment]
@ewels Thanks, and sorry for not getting my pull request to you in time. And thanks also for the prompt fix; I use multiqc for many projects and so far this is the only instance where something hasn't "just worked", which is amazing. Cheers.

**Comment by ewels** [comment]
No problem at all! Glad it's been useful for you :)
