### ISSUE TITLE
Mark Duplicates: "Error - was not able to plot data."

### ISSUE THREAD

**Issue by astewart-twist** [ewels/MultiQC#402]
Any idea what this error means?

**Comment by ewels** [comment]
Hi @astewart-twist,

Thanks for the bug report - this error was in the HTML report, right? I think it's the super general catch-all message that tries to stop the entire page from crashing if something goes wrong with a plot. So it could be a lot of things.

Would it be possible to send through the report where you see the error? Could you give a bit more information about how you generated the report, what it contained, whether other plots loaded, what system and browser you're using? Finally, if you're able to view the browser developer console and see any other error messages, that would be helpful.

Thanks,

Phil

**Comment by astewart-twist** [comment]
Apologies @ewels , this was actually a picard tools bug.  Thanks though!

**Comment by ewels** [comment]
Ok, that's always a relief to hear! What happened, out of curiosity? Could help me in the future if someone else has the same problem, plus in an ideal world MultiQC should complain and not try to plot anything if there's a problem with the data.

Phil

**Comment by astewart-twist** [comment]
Sure, @ewels.  It turns out it had something to do with the way I was running `picard MarkDuplicates`.  There would be a row with an empty sample name and empty stats.  

I can paste an example output:

```
## htsjdk.samtools.metrics.StringHeader
# picard.sam.markduplicates.MarkDuplicates INPUT=[sample.bam] OUTPUT=sample.deduped.bam METRICS_FILE=sample.metrics VALIDATION_STRINGENCY=SILENT    MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP=50000 MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=8000 SORTING_COLLECTION_SIZE_RATIO=0.25 PROGRAM_RECORD_ID=MarkDuplicates PROGRAM_GROUP_NAME=MarkDuplicates REMOVE_DUPLICATES=false ASSUME_SORTED=false DUPLICATE_SCORING_STRATEGY=SUM_OF_BASE_QUALITIES READ_NAME_REGEX=[a-zA-Z0-9]+:[0-9]:([0-9]+):([0-9]+):([0-9]+).* OPTICAL_DUPLICATE_PIXEL_DISTANCE=100 VERBOSITY=INFO QUIET=false COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false 
## htsjdk.samtools.metrics.StringHeader
# Started on: Sat Feb 18 22:49:17 UTC 2017
## METRICS CLASS	picard.sam.DuplicationMetrics
LIBRARY	UNPAIRED_READS_EXAMINED	READ_PAIRS_EXAMINED	UNMAPPED_READS	UNPAIRED_READ_DUPLICATES	READ_PAIR_DUPLICATES	READ_PAIR_OPTICAL_DUPLICATES	PERCENT_DUPLICATION	ESTIMATED_LIBRARY_SIZE
	0	0	0	0	0	0	?	
Unknown Library	625953	71521735	741007	443560	13157921	1389354	0.186257	184872566
```

**Comment by ewels** [comment]
Interesting, thanks! I've not seen MarkDuplicates reports with more than a single sample row. As a result, MultiQC only parses the first line of these logs. Is this something I should change? Need to think how to handle the numbers then, as a single log should still be a single sample right?

For now I've updated the code to skip samples where `READ_PAIRS_EXAMINED` is `0` with a warning - hopefully better than the somewhat unintuitive error that you came across.

Phil

**Comment by asalhab** [comment]
Hi @ewels 
I think by skipping samples with READ_PAIRS_EXAMINED = 0 made a problem for single read samples.i.e, UNPAIRED_READS_EXAMINED is also needed to be visualized. It happened to me when I ran MultiQC before and after this change (please see the attachment).

Abdul

![picard_deduplication_v1 dev0](https://cloud.githubusercontent.com/assets/24413139/24353359/7ce7aba2-12ed-11e7-8005-ac14535c6799.png)
![picard_deduplication_v1 dev0_9fd1cda](https://cloud.githubusercontent.com/assets/24413139/24353360/7cea4128-12ed-11e7-8564-1d978723129f.png)

**Comment by ewels** [comment]
@asalhab - of course! My apologies, I'll check for both `READ_PAIRS_EXAMINED ` _and_ `UNPAIRED_READS_EXAMINED`..

**Comment by ewels** [comment]
Hi @asalhab - please let me know if the above change fixes it for you.

Phil

**Comment by asalhab** [comment]
@ewels  yes It worked properly :) Thanks!

Abdul
