### ISSUE TITLE
Module request: BUSCO

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#407]
BUSCO
Assessing genome assembly and annotation completeness with _Benchmarking Universal Single-Copy Orthologs_.

>  BUSCO v2 provides quantitative measures for the assessment of genome assembly, gene set, and transcriptome completeness, based on evolutionarily-informed expectations of gene content from near-universal single-copy orthologs selected from OrthoDB v9.

http://busco.ezlab.org/

Requested on twitter: https://twitter.com/whitegenomics/status/834608200297050112

**Comment by MichaelFokinNZ** [comment]
In the specified output folder, i.e. OUTPUT busco creates a bunch of results, including 
short_summary_OUTPUT.txt file as following, and at the end this file has actually all info to be plotted

# BUSCO version is: 2.0 
# The lineage dataset is: pezizomycotina_odb9 (Creation date: 2017-01-26, number of species: 50, number of BUSCOs: 3156)
# To reproduce this run: python /share/easybuild/RHEL6.3/sandybridge/software/BUSCO/2.0-gimkl-2017a/BUSCO.py -i /projects/*****/spadesf1_v21/contigs/Kall/scaffolds99all.fasta -o scaffolds99all_pezizo_v02a -l /projects/******/spadesf1_v21/contigs/busco_lineages/pezizomycotina_odb9/ -m genome -c 1 -sp aspergillus_nidulans
#
# Summarized benchmarking in BUSCO notation for file /projects/******/spadesf1_v21/contigs/Kall/scaffolds99all.fasta
# BUSCO was run in mode: genome

	C:99.1%[S:99.0%,D:0.1%],F:0.5%,M:0.4%,n:3156

	3126	Complete BUSCOs (C)
	3124	Complete and single-copy BUSCOs (S)
	2	Complete and duplicated BUSCOs (D)
	16	Fragmented BUSCOs (F)
	14	Missing BUSCOs (M)
	3156	Total BUSCO groups searched

**Comment by ewels** [comment]
Great stuff, thanks! That looks very easy to write a module for (always a relief!). I can do a bar plot showing the proportions of those for each sample. Is there any key value that would be useful to see in the General Statistics table, alongside results from other tools? Also, is it worth collecting the lineage dataset / number of species or anything? I could check that all results files have the same lineage dataset and show a warning if there's more than one, for example.

**Comment by MichaelFokinNZ** [comment]
Yes, it is a great idea to provide the name of the reference lineage dataset and group samples accordingly. As about other tools - blast and augustus are in pipeline, but BUSCO doesn't provide any informative summary output for them...

**Comment by ewels** [comment]
Hi @MichaelFokinNZ,

I've just written the new module and pushed it - if you could grab a development version of MultiQC and try it out, that would be great!

I've printed the lineage dataset name(s) above the plot, blue if there is only one and red with a warning symbol if there are more than one. I haven't ordered the samples in the plot according to this as it's kind of tricky with the way that MultiQC is set up. I can add this is if it's super important though, let me know.

Cheers,

Phil

**Comment by MichaelFokinNZ** [comment]
Hi Phil, tested. Works amazingly. With lineages - I understand that it is possible to *hide* some of them manually and get desirable plot with a single reference dataset. But for me it is a king of useless to have different ref datasets on a same plot. Can you may be plot samples with different ref lineage datasets on a different plot straightaway?   

PS Funny personal case - just today my application for QA role was rejected (after interview though), and.... I am doing kind of testing now. So, being correct - I didn't perform proper test for busco output - just tried on few datasets... :)

**Comment by ewels** [comment]
Great, thanks for the testing! 😉 

I could make one plot for each lineage, though to be honest I was assuming that people wouldn't often run with more than one lineage in a project - I added the count above the plot more as a warning if that was the case. Do you often run with more than one ref?

Phil

**Comment by MichaelFokinNZ** [comment]
I do often do more than one reference lineage set, because they are taxonomically hierarchical, i.e. I am doing one test for phylum-conservative genes (Fungi) and more tests for lower levels, such as Ascomycota(class) or Pezizomycotina(order)... That makes sense.

**Comment by ewels** [comment]
Hi @MichaelFokinNZ,

I've just updated the module so that it has a separate section and plot for each lineage. Let me know if this works as you'd like it..

Cheers,

Phil

**Comment by MichaelFokinNZ** [comment]
hm,,, not sure if I can properly download/install the last dev version.  I did it with pip before and have 1.0dev now, but id doesn't separate plots. How to uninstall multiqc completely on ubuntu?

**Comment by ewels** [comment]
Ah, this will probably be because the version number hasn't changed since you has did it. `pip` tries to be clever and doesn't do anything because it thinks that the package is already installed.

Try adding `--upgrade`, which should tell `pip` to install it anyway. You can also try adding on `--force-reinstall`.

**Comment by MichaelFokinNZ** [comment]
Done, looks nice for my datasets. Much more sense with separate plots.
Thank you.

2017-03-02 23:13 GMT+13:00 Phil Ewels <notifications@github.com>:
