### ISSUE TITLE
Module Request: Illumina Demultiplexing stats

### ISSUE THREAD

**Issue by Rmulet** [ewels/MultiQC#409]
Hi Phil,

I find it increasingly useful to have the entire quality control in one single report I can easily browse through and share with my colleagues. One of the few pieces I am now missing is the demultiplexing step, which converts data in BCL format to FASTQ in Illumina machines.

Following the requirements checklist:

- Description of the tool: bcl2fastq can be used to both demultiplex data and convert BCL files to FASTQ file formats for downstream analysis. There are two versions of this software: [bcl2fastq](https://support.illumina.com/downloads/bcl2fastq_conversion_software_184.html) for MiSeq and HiSeq sequencing systems running RTA versions earlier than `1.8`, and [bcl2fastq2](https://support.illumina.com/downloads/bcl2fastq-conversion-software-v2-18.html) for Illumina sequencing systems running RTA version `1.18.54` and above.
- Log files: the file I find more useful is `Demultiplex_Stats.htm`, which contains a summary of the number of reads and their quality score in every sequenced sample. There are other files that can be informative, though, like `BustardSummary.xml`.
- Naming patterns: as I said above, the file is usually called `Demultiplex_Stats.htm`.
- Most important value: probably the number of reads.
- What should be plotted: the number of reads could be easily represented as a stacked barplot, together with the percentage of those that are perfect index reads. It would be also nice to have their mean quality... perhaps as a red line overlaid on top of the barplot?

I hope it suffices. Thanks a lot! :)

**Comment by ewels** [comment]
Aha, I wondered when someone would request bcl2fastq as a module! Do you have some example output files from these two that I could use to write the script around? I'm hoping that all of the information it'll need will be in the xml file, as parsing html is nasty.

Phil

**Comment by Rmulet** [comment]
Hi again. Sorry for the delay, but these days have been a bit hectic! I have just added an example output file to MultiQC_TestData following the recommended procedure (i.e. fork + pull request). In the end I had to upload the htm file because the xml does not have the exact same information.

On the other hand, the file is quite easy to parse with Python modules like BeautifulSoup or similar, as it only contains three tables - and the first includes just the headers of the second. For instance, I have been able to obtain the table of interest in only two steps using the `.read_html` method from Pandas:

import pandas as pd
tables=pd.read_html("Demultiplex_Stats.htm")
tables[1].columns=tables[0].iloc[0,:] # Table 0 contains the headers, Table 1 the statistics

That was very simple and worked with my example file.

**Comment by ewels** [comment]
Great stuff, thanks @Rmulet. Thankfully this looks like the simplest HTML page I've seen in a long time! As you say, parsing should be easy (I may use nastier, more manual techniques to avoid adding new package dependencies though).

Phil

**Comment by ewels** [comment]
Note to self - rawgit of HTML file [here](https://rawgit.com/Rmulet/MultiQC_TestData/ab3599b17d33e04420924374e0f9da921de3e25c/data/modules/bcl2fastq/Demultiplex_Stats.htm)

**Comment by ewels** [comment]
bcl2fastq v2.18.0.12 now produces output in JSON format. See new files in ewels/MultiQC_TestData#39
