### ISSUE TITLE
Module request: 10X chromium

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#413]
A few people have asked for MultiQC to support output from the 10X chromium. This has three distinct sets of software:

* [`cellranger`](https://support.10xgenomics.com/single-cell/software/pipelines/latest/output/overview) (single cell)
* [`longranger`](https://support.10xgenomics.com/genome-exome/software/pipelines/latest/output/overview) (long reads)
* [`supernova`](https://support.10xgenomics.com/de-novo-assembly/software/pipelines/latest/output/overview) (de novo)

There's also the `mkfastq` commands that each tool has, which has mostly consistent stats.

We should be able to start by parsing some basic stats from the `metrics_summary.csv` file produced by both `cellranger` and `longranger`.

**Comment by ewels** [comment]
Supernova added, closing this issue now as it's pretty broad. If people are interested in the other tools, please create a new issue..

**Comment by atermanini** [comment]
cellranger mkfastq output (metrics_summary.csv) can be very useful to have
