### ISSUE TITLE
Fastq Screen simple plot is a little misleading

### ISSUE THREAD

**Issue by jfear** [ewels/MultiQC#419]
I find the `fqscreen_simple_plot` a little misleading, because of the inclusion of reads that map to multiple references. 

For example: 

If read_1 maps to ref_A and ref_B it is ambiguous, so including those in the counts make contamination seem larger. 

Would you consider only including the single references hits?

thanks
Justin

**Comment by ewels** [comment]
Hi Justin,

Yes, this bugs me as well - I think I added a warning above the plot that bars don't sum to 100%, but it's been in the back of my mind that there should be a better solution for a while. However, just plotting single reference hits alone I think is a little misleading, as then it would be impossible to discern between a sample that doesn't map to anything and a sample that maps to everything.

I guess I should be able to sum the reads that map to multiple species and put them into their own category, plotting remaining reads for each species only if they are unique to that species.

So, thinking out loud.. We have four categories:

1. Multiple Hits, Multiple Genomes
2. One Hit, Multiple Genomes
3. Multiple Hits, One Genome
4. One Hit, One Genome

I could sum categories 3 and 4 for each species. Then sum 1 and 2 for each species, take the max of these values and plot this as its own category. Does that work? I probably need to check that everything adds up as it should :)

Phil

**Comment by ewels** [comment]
Hi @jfear,

I've implemented these changes now (see #430). If you could have a play with the latest development version and let me know what you think, that would be great!

I'll close this issue for now, but feel free to re-open if you feel that there's something that could be improved.

Cheers,

Phil
