### ISSUE TITLE
errors with custom content - simple tsv example

### ISSUE THREAD

**Issue by dbrami** [ewels/MultiQC#423]
Hi, I got this error trying to test multiqc custom reporting capabilities.
my command was
`multiqc ./`
```
[INFO   ]         multiqc : This is MultiQC v1.0.dev0
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching './'
[ERROR  ]         multiqc : Oops! The 'custom_content' MultiQC module broke... 
```
```python
============================================================
Module custom_content raised an exception: Traceback (most recent call last):
  File "/usr/local/bin/multiqc", line 346, in multiqc
    output = mod()
  File "/usr/local/lib/python2.7/dist-packages/multiqc/modules/custom_content/custom_content.py", line 190, in custom_module_classes
    parsed_modules.append( MultiqcModule(k, mod) )
  File "/usr/local/lib/python2.7/dist-packages/multiqc/modules/custom_content/custom_content.py", line 221, in __init__
    self.intro += bargraph.plot(mod['data'], mod['config'].get('categories'), pconfig)
  File "/usr/local/lib/python2.7/dist-packages/multiqc/plots/bargraph.py", line 116, in plot
    if pconfig.get('hide_zero_cats', True) is False or max(x for x in thisdata if not math.isnan(x)) > 0:
  File "/usr/local/lib/python2.7/dist-packages/multiqc/plots/bargraph.py", line 116, in <genexpr>
    if pconfig.get('hide_zero_cats', True) is False or max(x for x in thisdata if not math.isnan(x)) > 0:
TypeError: a float is required
============================================================
```

**Comment by dbrami** [comment]
Original upload attempt failed
[enr - somatic_mqc.tsv.tar.gz](https://github.com/ewels/MultiQC/files/852785/enr.-.somatic_mqc.tsv.tar.gz)

**Comment by ewels** [comment]
Hi @dbrami,

Many thanks for the detailed error report and example data. In this case, MultiQC was attempting to create a bar graph for your data as there was a header row and then a numeric data row. It then ran into the `N/A` values and broke. I've made a small adjustment that checks that _all_ data is numeric before deciding on a bar graph and it works now (creating a table).

Note that the table looks a bit odd as MultiQC expects data to be grouped by column, not row. So the first row (`Total Passing`) contains much bigger numbers than the others and this is highlighted with a much longer bar. If you transpose your data then it'll probably look more as expected.

If you can't transpose the data I can look into adding this as a configuration option, but then you'll need either header rows or a MultiQC config file as this won't be default behaviour. Let me know if this is something you'd be interested in.

Cheers,

Phil
