### ISSUE TITLE
FASTQC: Tile level sequence quality

### ISSUE THREAD

**Issue by astewart-twist** [ewels/MultiQC#424]
Hi there.  Thanks for making MultiQC!

I was wondering if there's a reason why the FastQC module doesn't support the tile level sequence quality report?  http://www.bioinformatics.babraham.ac.uk/projects/fastqc/Help/3%20Analysis%20Modules/12%20Per%20Tile%20Sequence%20Quality.html

In the native FastQC report, the tiling data is presented as a heatmap:

![image](https://cloud.githubusercontent.com/assets/14282772/24163843/f07b81ac-0e28-11e7-8033-1253a74e3921.png)

**Comment by ewels** [comment]
Hi @astewart-twist,

The reason is that I haven't figured out a good way to visualise a summary of that data. It would have to be simplified somehow so that many different datasets could be assessed in a single plot.. I'm open to suggestions! :)

Phil

**Comment by astewart-twist** [comment]
Ah.  Good point.  Maybe a 3D Rubik's Cube that floats out of the browser? :)

I suppose one way to do it would be to replace the Y axis with samples and have a slider for tiles (or toggle between sliders for tile and position in read).

**Comment by ewels** [comment]
Yes, that could work but it has a few disadvantages. Main thing is that I try not to make plots _require_ interaction. There are often switches (eg. counts or percentages), but these are more to help interpretation. What you're suggesting would need people to move the slider to view all of the data. Secondly it would be a totally custom plot type and I'd need to write it from scratch, which is quite a bit of work ;) Finally, there is quite a bit of data in that plot. If that's multiplied by several thousand (_eg._ a single cell experiment), then the MultiQC report could become huge.

I guess there are a few things that we want to see in this plot - deviations across different tiles (eg. certain tiles behaving badly in comparison to the average), and continuity of these across the sequencing cycles. I could calculate the mean quality of all tiles for all bases, then plot the average deviation from this mean for each base? That would give a single line per sample which would be easy to visualise. Difficult to know how well it would work in practice though, until I try it.

Phil

**Comment by astewart-twist** [comment]
As I think about it, the more I realize I can't really imagine where
comparative tiling metrics would be useful - maybe for troubleshooting
suspected instrument error. With that said, checking the tiling heatmap is
usually an all or nothing affair. Either it's all blue or there is some
deviation.

For the sample summary table, the percent of low quality rows from fastqc's
tile section (for some threshold) would probably be easiest.  iow, how many
cells from the heatmap are non-blue.

Your suggestion for a plot sounds intereting but sounds like more work than
should be necessary for MultiQC?

Maybe the simplest plot would just be the counts of the rows from tile
metrics binned by sequence quality. That would just involve a couple
tallies and some stacked bar plots. A good run would be a solid blue bar,
for example.

Something a bit fancier might be a single heatmap covering all samples
where the color of each cell is just the lowest observed quality from all
samples at that tile/cycle.

Or, maybe tile level metrics just aren't a good fit for MultiQC.  My
motivation for the request was just that the single MultiQC report is so
darned convenient and portable, I'd like to not even bother keeping the
upstream fastqc reports around.  The most appropriate place for this is
probably some individual sample report, which is probably outside the scope
of MultiQC.


On Wed, Mar 22, 2017 at 12:57 AM Phil Ewels <notifications@github.com>
wrote:

Yes, that could work but it has a few disadvantages. Main thing is that I
try not to make plots *require* interaction. There are often switches (eg.
counts or percentages), but these are more to help interpretation. What
you're suggesting would need people to move the slider to view all of the
data. Secondly it would be a totally custom plot type and I'd need to write
it from scratch, which is quite a bit of work ;) Finally, there is quite a
bit of data in that plot. If that's multiplied by several thousand (*eg.* a
single cell experiment), then the MultiQC report could become huge.

I guess there are a few things that we want to see in this plot -
deviations across different tiles (eg. certain tiles behaving badly in
comparison to the average), and continuity of these across the sequencing
cycles. I could calculate the mean quality of all tiles for all bases, then
plot the average deviation from this mean for each base? That would give a
single line per sample which would be easy to visualise. Difficult to know
how well it would work in practice though, until I try it.

Phil

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ewels/MultiQC/issues/424#issuecomment-288323944>, or mute
the thread

**Comment by ewels** [comment]
> _The most appropriate place for this is probably some individual sample report_

You mean.. like a FastQC report? 😝 

The barplot could work, though I feel that it would take a bit of explaining and not be super intuitive. The % low quality tiles would be easier to interpret, but to be honest I'm not sure that it would tell you anything that the general quality plots don't already say. My intention with MultiQC was that it should alert you to any samples that stand out so that you can go back to the original data to look at that one sample. I think that the other plots should be able to lead you back to the original FastQC report in this case.

I think I'll close this issue for now, at least until we come up with a good solution for how to represent this data. Feel free to re-open if you'd like!

Phil

**Comment by ewels** [comment]
ps. It's probably not worth the effort here, but MultiQC is built to handle plugin code nicely too. So if you want to write your own code to generate this plot then that's entirely possible. And of course pull-requests are welcome!

**Comment by allenbaron** [comment]
I know this is closed but MultiQC does such a great job of aggregating information and it would be helpful if there was _something_ about the fastqc Per Tile Sequence Quality in MultiQC. Would it be possible to add a list of which files passed, warned, or failed this module without any plot? That would be helpful in identifying which fastqc reports to look at and could also be used to look at the subset of files that failed the tiling portion to see if they also had problems in other modules.

**Comment by ewels** [comment]
I have good news for you @allenbaron - I implemented exactly this functionality a few weeks ago:

![image](https://user-images.githubusercontent.com/465550/67106522-17b67780-f1cb-11e9-9d68-adaa5a9aa94a.png)

(cf: https://github.com/ewels/MultiQC/pull/974#issuecomment-543793107)

This is already available with v1.8dev MultiQC and will be released with 1.8 soon 😄 

Phil
