### ISSUE TITLE
picard and fastqc modules broke

### ISSUE THREAD

**Issue by aledj2** [ewels/MultiQC#427]
Hi Phil,

Following on from #426.

I am working on DNA Nexus cloud compute which use clean linux workers. I am cloning the code from github and using miniconda (2.7) python interpreter. The code to install multiQC is:

```
# install Miniconda
bash ~/Miniconda2-latest-Linux-x86_64.sh -b -p $HOME/Miniconda

#export to path
export PATH="$HOME/Miniconda/bin:$PATH"

conda install jinja2 click markupsafe simplejson freetype -y

git clone https://github.com/ewels/MultiQC.git
cd MultiQC
python setup.py install
cd ..

```

All the files to test are in a folder called to_test. This folder also contains a copy of multiqc_config.yaml

When I run MultiQC I get the below errors with picard and fastq modules.

```
++ multiqc /home/dnanexus/to_test/ -m fastqc -m picard -n /home/dnanexus/out/multiqc/QC/multiqc/170323-multiqc.html -c /home/dnanexus/to_test/multiqc_config_yaml
[INFO   ]         multiqc : This is MultiQC v1.0.dev0
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '/home/dnanexus/to_test/'
[INFO   ]         multiqc : Only using modules fastqc, picard
[INFO   ]          picard : Found 11 MarkDuplicates reports
[INFO   ]          picard : Found 11 InsertSizeMetrics reports
[INFO   ]          picard : Found 22 BaseDistributionByCycleMetrics reports
[INFO   ]          picard : Found 11 HsMetrics reportsMar 23, 2017 12:19 PM
[ERROR  ]         multiqc : Oops! The 'picard' MultiQC module broke... 
                    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
                    (if possible, include a log file that triggers the error) 
============================================================
Module picard raised an exception: Traceback (most recent call last):
  File "/home/dnanexus/Miniconda/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/EGG-INFO/scripts/multiqc", line 346, in multiqc
    output = mod()
  File "/home/dnanexus/Miniconda/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/multiqc/modules/picard/picard.py", line 76, in __init__
    n['AlignmentMetrics'] = AlignmentSummaryMetrics.parse_reports(self)
  File "/home/dnanexus/Miniconda/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/multiqc/modules/picard/AlignmentSummaryMetrics.py", line 23, in parse_reports
    for f in self.find_log_files(config.sp['picard']['alignment_metrics'], filehandles=True):
KeyError: 'alignment_metrics'
============================================================
[INFO   ]          fastqc : Found 22 reports
[ERROR  ]         multiqc : Oops! The 'fastqc' MultiQC module broke... 
                    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
                    (if possible, include a log file that triggers the error) 
============================================================
Module fastqc raised an exception: Traceback (most recent call last):
  File "/home/dnanexus/Miniconda/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/EGG-INFO/scripts/multiqc", line 346, in multiqc
    output = mod()
  File "/home/dnanexus/Miniconda/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/multiqc/modules/fastqc/fastqc.py", line 110, in __init__
    self.gc_content_plot()
  File "/home/dnanexus/Miniconda/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/multiqc/modules/fastqc/fastqc.py", line 430, in gc_content_plot
    for f in self.find_log_files(config.sp['fastqc']['theoretical_gc']):
KeyError: 'theoretical_gc'

```
All input files and the yaml file are attached.

All of these files work with a previous release of multiqc (0.8dev0). My gut was that is the yaml file is incorrect but I've also tried using the example .yaml file from github.

[for_Multiqc_issue.tar.gz](https://github.com/ewels/MultiQC/files/864579/for_Multiqc_issue.tar.gz)

Thanks!

**Comment by ewels** [comment]
Aha, I see - you have a custom MultiQC config. Ok, in that case this isn't an installation problem after all (phew 😅 ). 

When you specify a custom search pattern, the module's defaults are overwritten. So in your config, you have this:

```yaml
sp:
    fastqc:
        data:
            fn: '*.stats-fastqc.txt'
        zip:
            fn: '*_fastqc.zip'
```
which overwrites all of the [default search pattern for FastQC](https://github.com/ewels/MultiQC/blob/master/multiqc/utils/search_patterns.yaml#L50-L56):
```yaml
fastqc:
    data:
        fn: 'fastqc_data.txt'
    zip:
        fn: '*_fastqc.zip'
    theoretical_gc:
        fn: '*fastqc_theoretical_gc*'
```
Note that the default one has a third key, `theoretical_gc` - this is expected by the module. As your custom `fastqc` set doesn't have this, it causes an error.

The same is true for the `picard` search patterns - there are missing subkeys in your custom version.

This isn't an ideal setup for MultiQC - I was thinking of forcing these patterns to be "flat", that is, not have subkeys for exactly this reason. It's a tricky thing to change though, as it'll then break everyone's custom configs.

Phil

**Comment by ewels** [comment]
Apologies, I just realised that I didn't actually say how to fix this. Basically - just add in any missing keys from the default set. Hopefully I can write a better solution some time in the future, but for now this should work.

Please reopen the issue if your problems persist :)

Phil

**Comment by aledj2** [comment]
Thanks! I can confirm I've got it working and all the extra functionality that I was hoping for!
Thanks for the help - We find MultiQC very useful so thank you very much!
