### ISSUE TITLE
Improve FastQ Screen

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#430]
The FastQ Screen axis is confusing. Instead of taking total alignments, count only single-species alignments. Have a category that sums the counts of all multi-species alignments, and a category for no alignment. Then we should be able to sum to 100%.

**Comment by ewels** [comment]
Hi @Hammarn,

If you could give this a test and check that it works as expected, that would be great!

Cheers,

Phil

**Comment by Hammarn** [comment]
Well it does seem to work ok but I'm not to fond of the black colour as the no hit. It's quite psychedelic, especially when scrolling. 
Maybe switch `no hits` to white/no colour?

![image](https://cloud.githubusercontent.com/assets/16774076/24506735/b83b3322-155e-11e7-917c-ea580d56f198.png)

**Comment by ewels** [comment]
Woah, ok yes that probably needs to change :)

I thought of removing 'No hits' completely, but then the plotting percentages don't work properly as stuff doesn't add up to 100% any more. White could be good, but then the label and the hover text are impossible to read as the text is white. I've just pushed a change with light grey as a compromise - maybe see how this looks?

See e5624596d02aac9af8f4a0e0f49405bbc6a43c0f

Phil

**Comment by Hammarn** [comment]
That's a great improvement, easy on the eyes. I'm happy with this 🙂 
![image](https://cloud.githubusercontent.com/assets/16774076/24507740/97bec1ec-1561-11e7-97d5-91b0b8fb0c25.png)

**Comment by Hammarn** [comment]
I attached some reports on which it broke:
[P7604_101_S8_L003_R1_001_screen.txt](https://github.com/ewels/MultiQC/files/882556/P7604_101_S8_L003_R1_001_screen.txt)
[P7604_101_S8_L003_R2_001_screen.txt](https://github.com/ewels/MultiQC/files/882559/P7604_101_S8_L003_R2_001_screen.txt)
[P7604_102_S9_L004_R1_001_screen.txt](https://github.com/ewels/MultiQC/files/882558/P7604_102_S9_L004_R1_001_screen.txt)
[P7604_102_S9_L004_R2_001_screen.txt](https://github.com/ewels/MultiQC/files/882555/P7604_102_S9_L004_R2_001_screen.txt)
[P7604_103_S10_L005_R1_001_screen.txt](https://github.com/ewels/MultiQC/files/882554/P7604_103_S10_L005_R1_001_screen.txt)
[P7604_103_S10_L005_R2_001_screen.txt](https://github.com/ewels/MultiQC/files/882557/P7604_103_S10_L005_R2_001_screen.txt)
[P7604_104_S11_L006_R1_001_screen.txt](https://github.com/ewels/MultiQC/files/882564/P7604_104_S11_L006_R1_001_screen.txt)
[P7604_104_S11_L006_R2_001_screen.txt](https://github.com/ewels/MultiQC/files/882565/P7604_104_S11_L006_R2_001_screen.txt)
[P7604_105_S12_L007_R1_001_screen.txt](https://github.com/ewels/MultiQC/files/882560/P7604_105_S12_L007_R1_001_screen.txt)
[P7604_105_S12_L007_R2_001_screen.txt](https://github.com/ewels/MultiQC/files/882561/P7604_105_S12_L007_R2_001_screen.txt)
[P7604_106_S13_L008_R1_001_screen.txt](https://github.com/ewels/MultiQC/files/882562/P7604_106_S13_L008_R1_001_screen.txt)
[P7604_106_S13_L008_R2_001_screen.txt](https://github.com/ewels/MultiQC/files/882563/P7604_106_S13_L008_R2_001_screen.txt)

Following stack trace:
```python
Module fastq_screen raised an exception: Traceback (most recent call last):
  File "/pica/h1/richam/MultiQC/scripts/multiqc", line 346, in multiqc
    output = mod()
  File "/pica/h1/richam/MultiQC/multiqc/modules/fastq_screen/fastq_screen.py", line 33, in __init__
    parsed_data = self.parse_fqscreen(f['f'])
  File "/pica/h1/richam/MultiQC/multiqc/modules/fastq_screen/fastq_screen.py", line 87, in parse_fqscreen
    parsed_data['No hits']['counts'] = {'one_hit_one_library': int((nohits_pct/100.0) * float(reads_processed)) }
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
```

**Comment by ewels** [comment]
This seems fine, closing until we can reproduce the error.
