### ISSUE TITLE
Issue/improvement: General stats isn't useful for read numbers when these are <100k

### ISSUE THREAD

**Issue by tomrconnor** [ewels/MultiQC#431]
Using FastQC to do QC on a set of samples with low numbers of reads (<100,000) appears to pose an issue as at the moment, because MultiQC does not report back the read numbers in a meaningful way. Currently, when these sorts of samples are parsed by MultiQC, the column in the summary table for M reads is, unsurprisingly marked as "0.0". 

I can't see a setting anywhere to increase this to 2 decimal places or to allow this to scale down to thousands of reads for people with samples that are smaller in size. At present this column doesn't really make sense; and it isn't clear how I could get a summary of the number of reads in each sample using FastQC with MultiQC.

**Comment by ewels** [comment]
Hi @tomrconnor,

You're quite right, there is no way to customise this at present. I have thought about adjusting the multiplier according to the number of reads, but I don't like the idea of the numbers being inconsistent across reports. However, I could add a config setting for `read_count_multiplier`, which would then be applied to all table columns with read counts. This would keep the consistency but allow you to make meaningful reports when it's not working. Would this be ok?

If it's of any help, the raw absolute counts are saved in the `multiqc_data` files.

Phil

**Comment by ewels** [comment]
Hi @tomrconnor,

I've just added this new config option, see the [new docs](http://multiqc.info/docs/#number-base-multiplier).

In short, you can now play with the following new config options:

```yaml
read_count_multiplier: 0.000001
read_count_prefix: 'M'
read_count_desc: 'millions'
```

Let me know how you get on!

Phil
