### ISSUE TITLE
Add AppVeyor test suite

### ISSUE THREAD

**Issue by epruesse** [ewels/MultiQC#433]
Since windows is a target platform for MultiQC, testing on windows would be useful to maintain compatibility. AppVeyor comes to mind as a tool in addition to TravisCI.

**Comment by ewels** [comment]
Ah nice, I haven't heard of this before.. Looks perfect, thanks!

**Comment by ewels** [comment]
Agh, sorry - I forgot that all of these references wouldn't disappear when I rebased. Caught redhanded! 😳

**Comment by ewels** [comment]
I think it finally works!! Ok now I'm definitely going to bed. Enthusiasm has definitely turned to stubbornness / bitter determination. Apologies for the spam. And thanks for the suggestion! Definitely a cool new tool 🥇

**Comment by epruesse** [comment]
Hehe, yes, getting any of these to run always turns into a flurry of commits. You can in theory do a git reset + git push -f to get rid of them. Probably better in a dedicated branch, so that it doesn't mess up pulls by other people.

BTW: putting [skip appveyor] in a commit message skips the appveyor build and [ci skip] skips both travis and appveyor. Useful if you don't want to clog the queue with redundant builds.

**Comment by ewels** [comment]
Yes, apologies - I naïvely thought that it would be a quick job. Then it was always "just one more commit".. Is it too late for me to `git reset` now that you've pulled my changes? I guess if I did it now then it would cause even more mess? Yuk. Sorry!

Good to know about `[ci skip]`, I wasn't aware of that one!

Phil

**Comment by ewels** [comment]
Ok, _now_ it's working (`conda update` seemed to fix random error just now). Closing this issue for now.

Phil
