### ISSUE TITLE
Include GcBiasSummaryMetrics in multiqc_data output

### ISSUE THREAD

**Issue by ahvigil** [ewels/MultiQC#434]
`picard CollectGcBiasMetrics` generates both GcBiasDetailMetrics and GcBiasSummaryMetrics output. Currently GcBiasDetailMetrics is used to generate a GC coverage bias plot, but GcBiasSummaryMetrics output is ignored. To be consistent with other picard modules, multiqc should roll up gc_bias_metrics.summary.txt files into a `multiqc_picard_gcbias.txt` file or similar.

I will have a PR addressing this shortly.

**Comment by ewels** [comment]
Hi @ahvigil,

Do you have any examples of the `GcBiasSummaryMetrics` output? Picard output can be extremely heterogenous - this data doesn't seem to exist in the files that I used to write this submodule (see them [here](https://github.com/ewels/MultiQC_TestData/tree/master/data/modules/picard/GcBiasMetrics)). It would be great if we could add some to the test data repo.

Phil

**Comment by ewels** [comment]
Closed in #435
