### ISSUE TITLE
log file from Kallisto 

### ISSUE THREAD

**Issue by ale07alvarez** [ewels/MultiQC#440]
Hi, I have three output files from Kallisto:

1. `abundance.h5`
2. `abundance.txt`
3. `run_info.json`

MultiQC is supposed to be able to read a log file from Kallisto but when I run: `multiqc .`  in the directory containing these three files I get the following:
```
[INFO   ]         multiqc : This is MultiQC v1.0.dev0
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
```

**Comment by ewels** [comment]
Hi @ale07alvarez,

I just had a look at how the Kallisto module works for you. The [search pattern](https://github.com/ewels/MultiQC/blob/master/multiqc/utils/search_patterns.yaml#L72-L73) shows that it looks for any file that contains the string `[quant] finding pseudoalignments for the reads`. The [example test data](https://github.com/ewels/MultiQC_TestData/tree/master/data/modules/kallisto) that I built the module around shows the files that it's looking for.

So, MultiQC works with Kallisto logs, not output files. To get MultiQC to work with Kallisto, you need to capture the Kallisto log output (eg. `kallisto command &> samplename_kallisto.log`). MultiQC will ignore the three files that you listed (unfortunately, `run_info.json` doesn't contain much in the way of interesting information, such as pseudo-alignment rate).

I hope this helps!

Phil

**Comment by ewels** [comment]
ps. Let me know how you get on! Feel free to re-open this issue if you're still running into trouble.

Phil

**Comment by kascchmc** [comment]
I also had this problem, but `&>file.log` gives a syntax error. I don't know how else to create the log file.

**Comment by ShwetaCh** [comment]
Hello @ewels 

I have got the log files ready in the same directory however multiqc still did not recognize the files. Am I missing something?

Thanks!
Shweta

```
(base) schavan@gvl-hpc-cluster:~/projects/bulk_rna_seq/RUN1/RPTR147_PT12.4_S2.Post.QUANT$ multiqc .
[WARNING]         multiqc : MultiQC Version v1.11 now available!
[INFO   ]         multiqc : This is MultiQC v1.8
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching   : /mnt/galaxy/home/schavan/projects/bulk_rna_seq/RUN1/RPTR147_PT12.4_S2.Post.QUANT
Searching 7 files..  [####################################]  100%
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
```

**Comment by ewels** [comment]
Hi @kascchmc and @ShwetaCh,

Please make a new issue next time - spotting new messages on old closed issues is tough.

Please see the docs for the files that Kallisto uses: https://multiqc.info/docs/#kallisto

> **Note** - MultiQC parses the standard out from Kallisto, _not_ any of its output files (`abundance.h5`, `abundance.tsv`, and `run_info.json`). As such, you must capture the Kallisto stdout to a file when running to use the MultiQC module.

Capturing standard out and standard error to files is standard bash, it's nothing fancy or specific to either Kallisto or MultiQC. You should be able to find plenty of help online about it. For example: https://linuxize.com/post/bash-redirect-stderr-stdout/

Let me know if anything is unclear 🙂 

Phil

**Comment by ShwetaCh** [comment]
@ewels My bad, you may close this, this issue is now resolved for me! 
(Kallisto log files even if existing did not have the relevant info, once I fixed this, I could get MutliQC to produce appropriate reports.)
