### ISSUE TITLE
cufflinks module

### ISSUE THREAD

**Issue by ale07alvarez** [ewels/MultiQC#441]
Hi Phil,
Would it be possible to add a module for Cufflinks?
Thank you!

> **Cufflinks.**
> _Transcriptome assembly and differential expression analysis for RNA-Seq_
> http://cole-trapnell-lab.github.io/cufflinks/

* Standard file names:
    * `genes.fpkm_tracking`
    * `isoforms.fpkm_tracking`
    * `transcripts.gtf`

**Comment by ewels** [comment]
Hi @ale07alvarez,

Cufflinks would be a good module to add, yes. The filenames you listed are all results files though, right? We'd need a log file with some summary statistics preferably, and need to decide what we want to show. Do you have any runs kicking around that we could use for model data? If not I can try to dig some out from our end, we run Cufflinks in our old (still current for this week) RNA pipeline.

Phil

**Comment by ewels** [comment]
Closing due to lack of example data.
