### ISSUE TITLE
new module: Adapter Removal

### ISSUE THREAD

**Issue by alexanderscholz** [ewels/MultiQC#442]
Hello Philip,

thank you for multiqc, it is really nice to work with.

We use Adapter Removal, like the title says, to trim adapter from reads. (https://github.com/mikkelschubert/adapterremoval)

The standard log file name pattern is `*.settings`. I will submit a pull request with example log files to your MultiQC_TestData Repo.

I implemented a adapter removal module by myself. I will submit a pull request. Please let me know if the code does not meet your coding guide or something like that.

Thanks,
Alex

**Comment by alexanderscholz** [comment]
Pull request for module code: #443

**Comment by ewels** [comment]
Great stuff, thanks @alexanderscholz! We can discuss the new module on the PR, I'll close this issue for now.
