### ISSUE TITLE
Custom Content table column 1 header

### ISSUE THREAD

**Issue by mohammedkhalfan** [ewels/MultiQC#445]
Hi Phil,

Thanks for being so quick to respond to my previous requests.

I have a new issue: I am making custom table reports in tsv format, which works nicely for the most part. One issue I am having is that the header in column 1 is always 'Sample Name' in the MultiQC report. For example, here is my input (`lane_stats_mqc.tsv` or `lane_stats_mqc.txt`):

```
# plot_type: 'table'
# section_name: 'Lane Statistics'
Lane	Total # Reads	Total # PF Reads	Undetermined
1	196,298,213	186,009,926	5.45%

```
This makes a table, which is great, but column 1 header says 'Sample Name', not 'Lane' as specified in my input above. This is the case for a couple different table reports I am preparing... Is it possible to force / overwrite the default 'Sample Name' in the column 1 header?

**Comment by ewels** [comment]
Hi @mohammedkhalfan,

Another great question! Again I came across the same problem myself just the other day. Thankfully I did fix this one though. There is a new table config key called `col1_header` which you use to set this (see the [docs](http://multiqc.info/docs/#creating-a-table)). So in your case it would be _(untested)_:

```
# plot_type: 'table'
# section_name: 'Lane Statistics'
# pconfig: col1_header: 'Lane'
Lane	Total # Reads	Total # PF Reads	Undetermined
1	196,298,213	186,009,926	5.45%
```

I added this for a traditional module. I guess I could also update the Custom Content module to set this config variable if we have a header in the file for the first column. I'll look at doing this now.

Phil

**Comment by ewels** [comment]
Hi @mohammedkhalfan,

I've just updated the Custom Content module so that it uses the first table header if it's there (as would be expected really!). If you pull the development version you shouldn't need to change your data structure at all.

Let me know if you run into any problems,

Phil

**Comment by mohammedkhalfan** [comment]
Hi @ewels 

Thank you for the quick fixes! I just pulled the latest version and tried it. It works if I put in this line
`
# pconfig: col1_header: 'Lane'`

but if I don't put that line in (as per last comment), it doesn't work, the column header reads 'Library'.

It's usable for me now though, so thank you very much.

**Comment by ewels** [comment]
Hi @mohammedkhalfan,

Are you sure that you're using the latest development version of MultiQC? I just tried again with a [test file](https://github.com/ewels/MultiQC_TestData/blob/master/data/custom_content/embedded_config/test_table_mqc.txt) that I based on your example:

```
# plot_type: 'table'
# section_name: 'Lane Statistics'
Lane	Total # Reads	Total # PF Reads	Undetermined
1	196,298,213	186,009,926	5.45%
```

That seems to work fine for me:
![image](https://cloud.githubusercontent.com/assets/465550/25189573/d6db157e-2529-11e7-8615-81983c1c45b3.png)

This is with MultiQC v1.0.dev0 (652e4b2). The command to install the latest development version with `pip` is as follows:

```
pip install --upgrade --force-reinstall git+https://github.com/ewels/MultiQC.git
```

Phil

**Comment by mohammedkhalfan** [comment]
Hi @ewels 

Yes I have the latest version. There is a bug somewhere. I have two reports, if both have an 'id' and 'section_name', indeed it works correctly. But if there are some attributes missing, for example if you take out 'section_name' and 'id' from both reports, the column header from 1 report is applied to both reports. So there may be  a little bug there it seems, but I can get it to work as desired. I understand that due to the nature of the problem, it can be a little tricky to be able to accommodate all possible situations.

**Comment by ewels** [comment]
Aha, yes that is a bug - thankfully I actually fixed exactly this at the start of this week, it's currently sat in PR #202 (works fine if I run on that branch).

I'll merge that later today, then hopefully everything should work as expected.

Phil

**Comment by ewels** [comment]
So, this seems to be a firefox specific bug. It's down to the way that the javascript engine powering the plot is sorting the keys of the object.

I've just pushed a commit which should fix this. Let me know how you get on!

Phil

**Comment by ewels** [comment]
oops, wrong issue sorry..

**Comment by ewels** [comment]
@mohammedkhalfan - PR #449 now merged, which should mean that this bug is fixed..

Cheers,

Phil
