### ISSUE TITLE
Custom Content: specify order of report sections

### ISSUE THREAD

**Issue by mohammedkhalfan** [ewels/MultiQC#446]
Hi Phil,

Question: I have 2 custom reports, let's say `foo_mqc.txt` and `bar_mqc.txt`. These get parsed by MultiQC, no problem. The thing is, it would be ideal if `foo_mqc.txt` was always placed above `bar_mqc.txt`, I mean, in the MultiQC report, the table from `foo_mqc.txt` should be above the table from `bar_mqc.txt`. But, if I run MultiQC on the same directory, it appears that they are parsed at random, so the order is not consistent. 

Is there any way/trick to force the ordering? 

Thank you. We have been getting great feedback regarding MultiQC.

**Comment by jdidion** [comment]
I second this request. The Atropos module (#447) actually has three submodules. It would be great if they could always appear in a specified order. I think this could mostly be solved by respecting the order that modules are listed in the entry points.

**Comment by ewels** [comment]
Hi @mohammedkhalfan,

Great question! You're completely correct, at the moment any Custom Content files are parsed in a random order. I came across this same issue the other day in fact and it annoyed me too. Looking at the code it doesn't look like I did anything about it though :persevere:

I should be able to add a config option to specify the order of custom content sections. This would work by using section IDs. These are generated using a bit of black magic with Custom Content, so what they are depends on how you supply your data. You can find them by following a link in the side navigation and looking at the URL, eg: `multiqc_report.html#bargraph_single_samples` (where the section ID is `bargraph_single_samples`). Would this be ok?

@jdidion - your case is a little different, as you're talking about traditional MultiQC modules and not _Custom Content_ (which is in fact a single module in the eyes of MultiQC). Here, the order is set by the [`module_order `](https://github.com/ewels/MultiQC/blob/master/multiqc/utils/config_defaults.yaml#L150-L151) config variable. I seem to remember that I did think about using the order of entry points way back when I first wrote this code a couple of years ago. I think the reason that I used a config list instead was to allow people to change the order of the sections in their report if they wanted to (the config can be easily overwritten, entry points cannot).

Phil

**Comment by ewels** [comment]
Ok, I've implemented the new feature and pushed - @mohammedkhalfan, if you could install the development version of MultiQC and test it out that would be brilliant.

New documentation here: http://multiqc.info/docs/#order-of-sections

Phil

**Comment by jdidion** [comment]
Thanks - I guess we’ll take care of adding Atropos to the module order once we get the module integrated.

**Comment by ewels** [comment]
@jdidion - yes exactly, once the Atropos module is in the core we add it to the default dict of module order. You can modify this from within a plugin module as well if you like, by altering the `config` dict that has been loaded.

**Comment by mohammedkhalfan** [comment]
Tested, works. Thank you.

**Comment by ewels** [comment]
Ok great, good to hear 👍 

Thanks!
