### ISSUE TITLE
messed up Per Base Sequence Content plot

### ISSUE THREAD

**Issue by ChristelKrueger** [ewels/MultiQC#450]
Hi Phil

Weird things are happening in the Per Base Sequence Content plot for this sample:

![capture](https://cloud.githubusercontent.com/assets/27807527/25226586/73c7a576-25bd-11e7-9d99-62329d9101f5.PNG)

This is with the latest development version.
Fastqc report from the relevant sample included.
Thanks for looking into it, Christel
[A3_M16_J16_F10_I17_fastqc.zip](https://github.com/ewels/MultiQC/files/942362/A3_M16_J16_F10_I17_fastqc.zip)

**Comment by ewels** [comment]
Weirder is that it works fine for me:

![image](https://cloud.githubusercontent.com/assets/465550/25226907/df77950c-25c6-11e7-8d59-183866227873.png)

Please could you send through the MultiQC log file (`multiqc_data/multiqc.log`) and the MultiQC report HTML file?

What web browser are you using?

Cheers,

Phil

**Comment by ewels** [comment]
So, this seems to be a firefox specific bug. It's down to the way that the javascript engine powering the plot is sorting the keys of the object.

I've just pushed a commit which should fix this (c7cd38516a1fce3f6b1fdf593031bad938fedf73). Let me know how you get on!

Phil

**Comment by ChristelKrueger** [comment]
Works a treat! Thanks for the quick solution!
Christel
