### ISSUE TITLE
Report: export plot + raw data from tabbed datasets

### ISSUE THREAD

**Issue by veronikaherzog** [ewels/MultiQC#455]
Hi Phil,

I try to export raw data from plots that show + and - strand depending on the "button" activated. It displays me nicely the data but when I export, it only exports the + strand data. (I attached a screenshots that makes it hopefully more clear what I am talking about)
![screen shot 2017-04-26 at 3 54 57 pm](https://cloud.githubusercontent.com/assets/25718728/25438133/caf63832-2a98-11e7-80f1-b0d6c3f8770b.png)
Can you help me to export the data on the - strand as well?

Thanks!
Veronika

**Comment by ewels** [comment]
Hi Veronika,

What module / tool does this data come from? I have a nasty feeling that this is a core limitation of MultiQC reports at the moment though. I should be able to do something about it though - I'll take a look.

Phil

**Comment by veronikaherzog** [comment]
Hi Phil,

Thanks for the fast reply. We used the slamdunk tool for this… Is there any way you could fix this?
Many thanks!
Veronika

**Comment by ewels** [comment]
Yeah, it should be possible. Requires me to make some changes to the way that the exporting function works in the reports, but it's definitely worth doing..

**Comment by veronikaherzog** [comment]
Great!

**Comment by ewels** [comment]
Hi @veronikaherzog,

I've just refactored the report code a little and the _Data Export_ tab now downloads a file for each tab (so you get +ve strand and -ve strand). The image export already works for both tabs - it just downloads whichever is currently visible. I've also updated the docs a little to explain this.

I hope this helps! Let me know if you run into any problems with it.

Phil

**Comment by veronikaherzog** [comment]
Thanks a lot!
Veronika

**Comment by ewels** [comment]
Hi @veronikaherzog,

Apologies - a quick heads up that I've just rewritten how this works. Now instead of downloading data from all tabs when you click export (as I added in above), it just downloads the visible tab. Basically the same as the image export.

Thought I should warn you as it could be a bit confusing! Shout if you find any problems.

Phil
