### ISSUE TITLE
Add General Stats HTML markup generator to BaseModule

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#46]
Currently, each module has to write its own HTML for the general statistics table, which is messy.

Instead, write a function in the `BaseModule` to handle this.

Modules ported:

- [x] bismark
- [x] bowtie1
- [x] bowtie2
- [x] cutadapt
- [x] _(~~fastq_screen~~)_
- [x] fastqc
- [x] featureCounts
- [x] picard
- [x] qualimap
- [x] star
- [x] tophat

**Comment by guillermo-carrasco** [comment]
:+1: (why there is no vote option?)

**Comment by ewels** [comment]
How's [this](https://github.com/ewels/MultiQC/blob/master/docs/writing_python.md#adding-to-the-general-statistics-table)? Need to port all of the modules across to using it still..

**Comment by ewels** [comment]
WIP. Modules ported:

- [ ] bismark
- [ ] bowtie1
- [ ] bowtie2
- [ ] cutadapt
- [ ] fastq_screen
- [ ] fastqc
- [ ] featureCounts
- [ ] picard
- [ ] qualimap
- [ ] star
- [ ] tophat

**Comment by ewels** [comment]
Done! Even did a little trickery - pokery with `lambda` functions which was fun. First `yield` and now `lambda` - starting to feel like I understand some of what Python can do at last!

**Comment by guillermo-carrasco** [comment]
you're a pro man, a real pro

**Comment by ewels** [comment]
Hah, I don't think I get to claim that title until I can read the `statusdb` package code.. (and understand what it's doing!)
