### ISSUE TITLE
Module request: AfterQC

### ISSUE THREAD

**Issue by gk-bioin4m8x** [ewels/MultiQC#462]
Hi @ewels ,
MultiQC is an awesome tool to aggregate results from multiple samples. Recently, I came across with another nice tool AfterQC.  I was wondering if I can use MultiQC to aggregate AfterQC results, but as per MultiQC [https://github.com/ewels/MultiQC], AfterQC is not in the list of supported tools.

It would be great to have it!

Thanks!

**Comment by ewels** [comment]
Hi @gk-bioin4m8x,

Looks like a useful tool! I imagine that I can write a module for it so that MultiQC supports the output. I need the following (should have been in the template when you wrote the issue?)

- Description of tool, link to homepage
  * I guess this is it? https://github.com/OpenGene/AfterQC
- Log files - please submit as a PR to https://github.com/ewels/MultiQC_TestData
- Any standard log file naming patterns to get sample name (eg. `sample_name.processed.log`)
- Say which value is most important, to go into the General Stats table
- Specify what should be plotted, if anything

Thanks!

**Comment by gk-bioin4m8x** [comment]
@ewels Thanks! 

-  That's correct link to homepage (its for paired-end reads).
-  I tried to submit PR, but nothing came. :P
-  Features to plot (as I got from one of my RNA-seq samples):
```
1. AfterQC summary (for General Stats table):

AfterQC Version:	0.9.1
sequencing:	.......... pair end
estimated seq error:	...........%
total reads:	...........
filtered out reads:	.......... (.................%)
total bases:	..........................
filtered out bases:	........................... (.............................%)
auto trimming	front:...., tail:.... (use -f0 -t0 to disable)

2. Good reads and bad reads after filtering (filtering statistics)
3. Sequencing error transform distribution
4. Pair Overlap length histogram
5. Read1 quality curve before filtering
6. Read1 base content distribution before filtering
7. Read1 GC curve before filtering
8. Read1 per base discontinuity before filtering
9. Read1 kmer strand bias before filtering
10. Read1 quality curve after filtering
11. Read1 base content distribution after filtering
12. Read1 GC curve after filtering
13. Read1 per base discontinuity after filtering
14. Read1 kmer strand bias after filtering
15. Read2 quality curve before filtering
16. Read2 base content distribution before filtering
17. Read2 GC curve before filtering
18. Read2 per base discontinuity before filtering
19. Read2 kmer strand bias before filtering
20. Read2 quality curve after filtering
21. Read2 base content distribution after filtering
22. Read2 GC curve after filtering
23. Read2 per base discontinuity after filtering
24. Read2 kmer strand bias after filtering
```
Please let me know for any more information.

**Comment by ewels** [comment]
> I tried to submit PR, but nothing came. :P

You need to fork the repository before you can make a PR, which it doesn't look like you have done. Instructions on how to contribute test data are on the readme here: https://github.com/ewels/MultiQC_TestData

The output you pasted looks great, but I still have a few questions :)

1. Is that saved to a file?
    * What is the filename that AfterQC generates if so?
    * If not, is it standard out that you pasted?
2. Are the dots (`...........`) where you've removed values?
    * If so can I please have one (or several) files which come straight from the program without modification please?
3. Are there any other files generated?
    * There isn't much in this log, so I can't add much to MultiQC reports from it. Probably just the percentage of bases removed (in the General Stats table, as with _cutadapt_ and other read trimmers).

Cheers,

Phil

**Comment by gk-bioin4m8x** [comment]
Done.
Answers:
1 and 3. It generates:
    (i) fastq files in user-specified folders: 2 good and 2 bad each for R1 and R2.
    (ii) "QC" folder: html document for the 24 features (in the previous post) and json file.
    (iii) I pasted the features it shows at top of html document.
2. Yes, dots are the removed values. Would it be possible to use test data from AfterQC?

**Comment by ewels** [comment]
Thanks @gk-bioin4m8x :)

I'm not quite sure what you did with your fork, but it looks very strange (no history). I'll look into generating some test data. I'll get back to you when I have something to report.

**Comment by gk-bioin4m8x** [comment]
For me too, it seems strange. I don't know what happened . :P
ok, thanks!

**Comment by ewels** [comment]
Ok, I installed AfterQC and ran it on some test data. I've put this into the MultiQC_TestData repo here: https://github.com/ewels/MultiQC_TestData/tree/master/data/modules/afterqc

I will start by parsing the [`summary`](https://github.com/ewels/MultiQC_TestData/blob/master/data/modules/afterqc/PE/testdata/QC/R1.fq.gz.json#L253-L267) section of the JSON file and making a bar plot showing the breakdown of the reads (much like the pie chart at the top of the HTML report I guess).

I'll also add the % of filtered bases to the General Stats table, and the error rate if it's in the JSON file (not calculated for single-end data).

**Comment by gk-bioin4m8x** [comment]
Ok, that sounds great! :)

**Comment by gk-bioin4m8x** [comment]
@ewels MultiQC is ready to be worked on AfterQC, right?

**Comment by ewels** [comment]
Yes, along with ten other modules :) See https://github.com/ewels/MultiQC/projects/1

I will get to it, but it won't be done immediately.

Phil

**Comment by gk-bioin4m8x** [comment]
Hello Phil,

I am trying to run MultiQC on AfterQC output, but it shows following:

```
$ multiqc --file-list files.txt -n samples -o multiqc
[INFO   ]         multiqc : This is MultiQC v1.1.dev0
[INFO   ]         multiqc : Template    : default
Searching 20 files..  [####################################]  100%
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
```

Please let me know.

Thanks!

**Comment by ewels** [comment]
Hi @gk-bioin4m8x,

Please see my comment above. I have put your request in a queue, but there are lots of other people asking for me to add things to MultiQC and I have a finite amount of time that I can spend writing this code.

This module will be written, but it is likely to be several weeks before it is done. Please be patient. I will post here when there is some news.

Phil

**Comment by gk-bioin4m8x** [comment]
Ok, thanks!

**Comment by ewels** [comment]
Module being worked on by @raonyguimaraes :D

**Comment by ewels** [comment]
Done and merged 👍
