### ISSUE TITLE
Parse additional columns of Picard CollectRnaseqMetrics

### ISSUE THREAD

**Issue by kmborchert** [ewels/MultiQC#463]
Regarding parsing of Picard CollectRnaSeqMetrics output:  

Currently only seven metrics from the output are collected and summarized in General Statistics.
```
PCT_CODING_BASES
MEDIAN_CV_COVERAGE
PCT_INTRONIC_BASES
MEDIAN_3PRIME_BIAS
MEDIAN_5PRIME_BIAS
PCT_INTERGENIC_BASES
PCT_UTR_BASES
```

It would be useful to display additional metrics in the General Statistics table:
```
PCT_RIBOSOMAL_BASES
MEDIAN_5PRIME_TO_3PRIME_BIAS
```

These additional metrics cannot be added by to the output by the end user.

**Comment by ewels** [comment]
Thanks @kmborchert! I agree that those two sound useful. I try to keep the number of columns per-module in the _General Statistics_ down a bit, as it can get very wide and go off the screen. How about I create a new table for Picard CollectRnaSeqMetrics with all of these? Then show _just_ `PCT_RIBOSOMAL_BASES` and `MEDIAN_5PRIME_TO_3PRIME_BIAS` in _General Statistics_. Would that work?

**Comment by kmborchert** [comment]
@ewels, that would certainly work.  I like the idea of having a separate table for Picard CollectRnaSeqMetrics output as well.  

Thanks for the quick follow up!

**Comment by ewels** [comment]
Hi @kmborchert,

Apologies for the long delay - whilst quick to respond I'm sometimes slow to actually find time to do work on these issues!

I've just sat down to look into writing this for you, but once I got to writing it I'm getting second thoughts. This is what the module currently produces:

![-users-philewels-github-multiqc_testdata-data-modules-picard-collectrnaseqmetrics-multiqc_report html](https://user-images.githubusercontent.com/465550/28273495-d64e9574-6b0e-11e7-823e-371b3a51c551.png)

In short, I feel like nearly all of the numbers you'd like to see in a table are already represented:

* `PCT_CODING_BASES`, `PCT_INTRONIC_BASES`, `PCT_INTERGENIC_BASES`, `PCT_UTR_BASES`
    * Already in the _Assignment_ plot (tooltip or clicking _Percentages_)
* `MEDIAN_3PRIME_BIAS`, `MEDIAN_5PRIME_BIAS`
    * Gene coverage bias shown in the _Gene Coverage_ plot
* `MEDIAN_CV_COVERAGE`
    * Not shown anywhere.

So now we're left with a single value, and my gut feeling is that it's not a very commonly used one. I had to google it to find out what it meant and found quite a few posts asking the same thing. So I'm not sure it's worth prioritising (it's always available in `multiqc_data` if needed).

Is there a situation where these plots don't do what's needed for you? I could look into adding config options to let you add whatever categories you like into the General Statistics table I guess.

Phil

**Comment by kmborchert** [comment]
Thanks for the reply @ewels .  What I was looking for was something that perhaps not many users would want, so I completely understand.  The graphical display is certainly more informative -- I was looking to put the values into a table for quick consumption by an end-user.  I've since gone to creating a table with all of the Picard CollectRnaseqMetrics output and loading it into MultiQC as a custom table.  It works just fine.

**Comment by ewels** [comment]
Ok great, that's perfect! Thanks for letting me know..

Phil
