### ISSUE TITLE
Module request: HOMER findPeaks

### ISSUE THREAD

**Issue by cliu72** [ewels/MultiQC#465]
Hi Phil,

I was wondering if you could add HOMER (Hypergeometric Optimization of Motif EnRichment) to MultiQC. HOMER a suite of tools for motif discovery (http://homer.ucsd.edu/homer/) and while HOMER contains many different tools, the tool used in our particular project is the findPeaks program (http://homer.ucsd.edu/homer/ngs/peaks.html), used to identify regions in the genome where we find more sequencing reads than we would expect by chance.

I have submitted a PR to MultiQC_TestData with some example output files. The output files from findPeaks are different depending on the options used (i.e. using `-style factor` outputs a `peaks.txt` file, while using `-style histone` outputs a `regions.txt` file). In our data analysis pipeline, the output file is named `sample_name.peaks1kb.txt`.

While not a standard log file, the header of the output file contains summary information. The most important values to us (to include in the General Stats table) are `Approximate IP efficiency`, `total peaks`, and `expected tags per peak`. Those same stats would probably be the most important to be plotted as well.

Since HOMER is such a large suite of tools and has differently named output files, we realize it may be difficult to generalize MultiQC for all HOMER outputs, but having the stats mentioned above in a MultiQC report would be really helpful for us.

Thanks!

P.S. I'm not sure if I was able to fork/clone the TestData repo successfully. When I cloned the forked repo to my local PC, I got this error:

```
fatal: cannot create directory at 'data/modules/salmon/sample_1/aux': Invalid argument
warning: Clone succeeded, but checkout failed.
```

According to google, this is because aux is a reserved name on Windows. I continued adding/committing, but got some weird error messages. Please let me know if I need to do something differently.

**Comment by ewels** [comment]
Hi @cliu72,

Homer is a great tool, I think it'd be a great addition to MultiQC. As you say, there are many parts to it, so I'll structure the module in the same way that RSeQC / Picard / other multi-tool packages are handled. Even though we're only adding support for a single tool here, that will mean that it's ready for additional modules in the future.

Anyway, I'll take a look at this soon. Thanks for the detailed request!

Phil

**Comment by ewels** [comment]
Test data added in ewels/MultiQC_TestData#34

**Comment by cliu72** [comment]
Great! Thanks :)

**Comment by ewels** [comment]
Hi @cliu72,

I've just put this module together for you. As the output of HOMER is nicely formatted, it was easy enough to just parse all of the values in the file headers. So all of these are parsed into `multiqc_data/multiqc_homer_findpeaks.txt` (you can change the format of this file with the `-k` flag).

I haven't created any bar plots as the three values are fairly stand-alone. As such, I don't think that it would add anything over what's now in the General Statistics table.

If you could have a play and test it a bit that would be great! If you have any ideas for changes or more things to do with the data, let me know.

Cheers,

Phil
