### ISSUE TITLE
hts_screen - fastq_screen module crashes

### ISSUE THREAD

**Issue by oliverdrechsel** [ewels/MultiQC#467]
It seems version 1.0 of multiqc doesn't like the output of hts_screen. Version 0.4 digests the very same output well.

```
[INFO   ]         multiqc : This is MultiQC v1.0
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching 'multiqc_test_partly/'
Searching 8 files..  [####################################]  100%
[ERROR  ]         multiqc : Oops! The 'fastq_screen' MultiQC module broke... 
                    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
                    (if possible, include a log file that triggers the error) 
============================================================
Module fastq_screen raised an exception: Traceback (most recent call last):
  File "[...] software/multiqc/1.0-foss-2015a-Python-3.4.3/lib/python3.4/site-packages/multiqc-1.0-py3.4.egg/EGG-INFO/scripts/multiqc", line 373, in multiqc
    output = mod()
  File "[...] software/multiqc/1.0-foss-2015a-Python-3.4.3/lib/python3.4/site-packages/multiqc-1.0-py3.4.egg/multiqc/modules/fastq_screen/fastq_screen.py", line 33, in __init__
    parsed_data = self.parse_fqscreen(f['f'])
  File "[...] software/multiqc/1.0-foss-2015a-Python-3.4.3/lib/python3.4/site-packages/multiqc-1.0-py3.4.egg/multiqc/modules/fastq_screen/fastq_screen.py", line 68, in parse_fqscreen
    parsed_data['total_reads'] = int(l.split()[-1])
ValueError: invalid literal for int() with base 10: '${num_reads}'
============================================================

```

[offending_screen.zip](https://github.com/ewels/MultiQC/files/1031076/offending_screen.zip)

**Comment by ewels** [comment]
Thanks @oliverdrechsel, I'll take a look. What is _hts_screen_ exactly? How is this output being generated?

Phil

**Comment by oliverdrechsel** [comment]
Hi.

*hts_screen* seems to be a home grown script that mimics fastq_screen using BWA and Kraken to avoid using Bowtie.

The output is the same as fastq_screen, but with the keyword "fastq_screen" exchanged by "hts_screen"

MultiQC already seems to cleverly detect the similarity of the outputs. 

Oliver

**Comment by ewels** [comment]
Ok cool, sounds useful! Is it much faster than the regular FastQ Screen? Is it openly available anywhere?

The reason that the module is crashing is because your output has `#Reads in subset: ${num_reads}` with the `${num_reads}` placeholder instead of an integer. I've update MultiQC to handle this error, but it mostly looks like something that can be fixed in your script 😄 

Phil
