### ISSUE TITLE
Formatting when read_count_multiplier=1

### ISSUE THREAD

**Issue by vladsaveliev** [ewels/MultiQC#470]
With `config.read_count_multiplier: 1`, reports still show 2 decimal digits (`1 234 567.00`). It would be nicer to show integer values just as `1 234 567`. Also, need to make sure that empty `config.read_count_desc` will not make the descriptions look ugly, for instance `'Total raw sequences ({})'` ends up with empty parenthesis.

A quick solution would be to look through all modules that report read numbers, and add a piece of code like 
```python
read_format = '{:,.2f} ' + config.read_count_prefix
if config.read_count_multiplier == 1:
    read_format = '{:,.0f}'
```

But it doesn't look very nice because it requires to copy this bit over and over, and does not guarantee that a developer of a new module will remember to add this. 

What do you think about this, is there any nice solution? Maybe a flag like `is_reads_field` that will make multiqc implicitly fix 'format' and `description` fields according to `read_count_multiplier`?

**Comment by ewels** [comment]
Yes, when I was about halfway through my copy+paste marathon for `config.read_count_multiplier` I had the same thought - that it would be better to just add a "special case" for read counts and have the core table code set the rest of the config values automatically.

As you say, perhaps we can add a new config option (maybe `read_counts: True`?) and then set the other values accordingly.. Something like:

* `title`: prepend `config.read_count_prefix`
* `description`: add `({})` suffix
* `min`: set to `0`
* `shared_key`: set to `read_count`
* `modify`: set to `lambda x: x * config.read_count_multiplier`
* `format`: as suggested above - `{:,.2f}` or `{:,.0f}`

This also future-proofs it a little if we want to add more custom stuff in the future.

Phil

**Comment by ewels** [comment]
ps. Maybe no need for a new field (`is_reads_field`) - could just see if `shared_key` == 'reads'`?

Would probably need some extra checks to avoid duplicating `title` and `description` strings for outdated modules though..

Phil

**Comment by ewels** [comment]
This is now done and merged - thanks!
