### ISSUE TITLE
Multiple instances of module

### ISSUE THREAD

**Issue by epruesse** [ewels/MultiQC#479]
Some modules would make sense to have multiple times in one report. For example, having a `fastqc` quality report before and after read pre-processing, or even in between each processing stage, would be useful.

The first question w.r.t. implementing this would be how to figure out when the feature is desired, either by detecting it and/or by specifying it from the command line

 If all is running right, the different runs of the same module would be replicated of the same sample name, either from different directories (`raw/`, `01_filtered/`, ...) or having matching filenames (`sample1.raw`, `sample1.filtered`).

**Comment by ewels** [comment]
Many thanks for this suggestion @epruesse - it's been something on the back of my mind for a while so it's good to discuss and get it moving. Some initial thoughts on the issue.. (to get them in writing)

* Just replicating the module itself should be fairly simple
    * Modules should all now use the [`save_htmlid` function](https://github.com/ewels/MultiQC/blob/master/multiqc/utils/report.py#L236), so duplicate report IDs shouldn't happen
    * I haven't tried it, but I suspect that repeating a module name in the [`module_order`](https://github.com/ewels/MultiQC/blob/master/multiqc/utils/config_defaults.yaml#L159) config will make it run twice
* The difficult bit will be making the module do something different each time it runs
    * As it stands, the same list of input files is given to each module each time it runs.

So there are a few different ways we could go about this. We could just build a new function into the FastQC module to do something specific, but I think it'd be nicer to write a general mechanism for any module if we can. I guess we could add a nested dict underneath the module name in the `module_order` config list to filter the input files supplied based on either filename or directory name? Then the module could be specified multiple times with different filters.

This approach should be pretty flexibly and powerful (and work with any modules with no changes to module code). The downside is that it requires a bit of a messy config change to use - reconfiguring the entire module order list (requiring copy and paste). This isn't the best config list to change either, as if it's configured then it has to be updated every time new modules are added to MultiQC. So it would be nice to try to think of alternative ways to achieve this config.

**Comment by ewels** [comment]
Regarding the sorting of module output, I think it would be better to handle this separately by proving a mechanism to customise the order of [`report.modules_output`](https://github.com/ewels/MultiQC/blob/883d2781738ffd44f29f8d01b03381eaea6f3fc4/scripts/multiqc#L368), _after_ the module has run.

This has the added bonus of being able to put multiple sections in different places in the report even if they come from the same module output. I've just come across this with the `custom_content` module, which frequently runs once but generates a whole bunch of sections. These have to be bunched together currently, but with the above feature could be placed anywhere.

**Comment by ewels** [comment]
ps. Documentation [here](http://multiqc.info/docs/#order-of-sections).

**Comment by ewels** [comment]
I just tried a simple report with the following config:

```yaml
module_order:
    - 'featureCounts'
    - 'star'
    - 'fastqc'
    - 'cutadapt'
    - 'fastqc'
```

It basically worked - a few odd errors due to custom FastQC code hardcoding HTML ids, but all of the core contributed HTML ids were fine and it runs fine (after a couple of minor tweaks in the above commits). The report ordering and everything is fine too.

So now it should just be a case of adding an option to filter the input files being supplied to the module. Hopefully this can be done in the base module class, so not requiring any changes to the module code. Will try to find time to play with this soon.

Phil

**Comment by ewels** [comment]
Hi @epruesse,

I've just had a go working with this. I've refactored the way that modules are run a little, allowing additional config options to be specified in `config.module_order` and `config.top_modules`. The hardcoded module settings (such as name) can be overwritten, and an additional option `path_filters` allows the input files for the module to be filtered for each run.

This brings me to a test config which seems to work well with FastQC:

```yaml
module_order:
    - featureCounts
    - star
    - fastqc:
        name: 'FastQC (trimmed)'
        info: 'This section of the report shows FastQC results after adapter trimming.'
        target: ''
        path_filters:
            - '*_1_trimmed_fastqc.zip'
    - cutadapt
    - fastqc:
        name: 'FastQC (raw)'
        path_filters:
            - '*_1_fastqc.zip'
```

Note that there is a FastQC-specific problem with the Pass / Warn / Fail badges which I still need to fix. But I _think_ everything else works.

If you could have a play and try to break it that would be great! Also let me know if there's anything else that you'd like to modify on a per-module-run basis. Docs [here](http://multiqc.info/docs/#order-of-modules).

Phil

**Comment by ewels** [comment]
Ok, will put the FastQC thing into a separate issue and closing this for now, as I think it's working.

Phil
