### ISSUE TITLE
--filename multiqc_report.html isn't respected when --title also specified

### ISSUE THREAD

**Issue by pjbriggs** [ewels/MultiQC#480]
Hello Phil

Thanks for making `multiqc`, we have just discovered it and it is quite astonishing. I've just come across this minor bug when trying to fit into our local pipeline, details are below. Thanks for all your great work with this software.

**Description of bug:**

`--filename multiqc_report.html` isn't respected when the `--title` is option also specified; in this case the output filename is derived from the title (ignoring the `--filename` option).

**More detail:**

This bug is a peculiar corner case which can be reproduced by running a command like:

    multiqc --filename multiqc_report.html --title "My Project" qc

This generates an output HTML file called `My-Project_multiqc_report.html`.

Running:

    multiqc --filename multiqc__report.html --title "My Project" qc

generates the expected `multiqc__report.html` output file.

The bug appears to be due to this check in `scripts/multiqc` (around line 281):

            if title is not None and filename == config.output_fn_name:
                filename = re.sub('[^\w\.-]', '', re.sub('[-\s]+', '-', title) ).strip()
                filename += '_multiqc_report'

If the supplied filename is the same as the default as in `multiqc/utils/config_defaults.yaml` (i.e. `multiqc_report.html`) and the title has also been supplied then the supplied filename is ignored.

* **Operating System:**
    * Seen on various Linuxes (Fedora and Ubuntu)

* **Python Version:**
    * Python 2.7.6

* **Method of MultiQC installation:**
    * From PyPI into a virtualenv i.e. `pip install multiqc`

**Comment by ewels** [comment]
Ah yes of course - great spot! This should be fairly easy to fix, I'll take a look in the coming days (I need to finish reviewing and merging #464 which addresses similar code so will try to both at the same time).

Phil

**Comment by pjbriggs** [comment]
@ewels thanks for looking into this, it is pretty minor - in the meantime I've found it's possible to work around by adding a leading path e.g. `--filename ./multiqc_report.html`.

**Comment by ewels** [comment]
Hi @pjbriggs,

I think this should be fixed now. As would be expected, specifying anything with `-n` prevents the automatic filename behaviour from `-i`.

Thanks for reporting and let me know if you run into any problems with it!

Phil

**Comment by pjbriggs** [comment]
Hello @ewels - sorry not to respond sooner, this seems to work okay for me in `multiqc` 1.1.

Thanks for the fix!

**Comment by ewels** [comment]
Great, thanks for letting me know!
