### ISSUE TITLE
Prokka module recognises only 1 log

### ISSUE THREAD

**Issue by cyklee** [ewels/MultiQC#482]
**Description of bug:**
MultiQC Prokka module only takes in 1 log (when there are multiple logs). I thought the problem may be due to clashing sample names, and have tried using -d & -s, changing file names, directory names, organism name (within the prokka log file) without any success. No warnings of sample name clash were found in verbose mode.

Each log file can be validly recognised if I run them individually through MultiQC. If I remove the sole file recognised (e.g. megahit_10.txt), another file will be recognised (e.g. megahit_03.txt) and place into the report (but never all the files).

**Error log:**
```
multiqc *.txt

[INFO   ]         multiqc : Searching 'megahit_01.txt'
[INFO   ]         multiqc : Searching 'megahit_02.txt'
[INFO   ]         multiqc : Searching 'megahit_03.txt'
[INFO   ]         multiqc : Searching 'megahit_04.txt'
[INFO   ]         multiqc : Searching 'megahit_05.txt'
[INFO   ]         multiqc : Searching 'megahit_06.txt'
[INFO   ]         multiqc : Searching 'megahit_07.txt'
[INFO   ]         multiqc : Searching 'megahit_08.txt'
[INFO   ]         multiqc : Searching 'megahit_09.txt'
[INFO   ]         multiqc : Searching 'megahit_10.txt'
Searching 10 files..  [####################################]  100%
[INFO   ]          prokka : Found 1 logs
[INFO   ]         multiqc : Compressing plot data

Same result even if I use -d and -s
```

* **File that triggers the error:**
[test.zip](https://github.com/ewels/MultiQC/files/1100068/test.zip)

* **Operating System:**
    * Linux Debian Jesse in Virtualbox (Windows 10 host)
* **Python Version:**
    *Python 3.6, 
* **Method of MultiQC installation:**
    * MultiQC 1.0, Conda (environment for Python 3.6)

**Comment by ewels** [comment]
Hi @cyklee,

Thanks for the bug report - it looks like prokka isn't handling sample names using the central function, which is why `-d` and `-s` aren't doing anything. I'll take a look into it..

Phil

**Comment by ewels** [comment]
Hi @cyklee,

I've had a look into this for you and made a few changes to the Prokka module:

1. Duplicate sample names now trigger a `debug` log message as expected
2. Sample names are passed through the proper MultiQC function, so that directory prepending works with `-d`
3. A new optional config parameter `prokka_fn_snames` tells the module to use the filenames to get the sample names, instead of collecting them from the head of the file as is the default.
    * This behaviour is now [documented](http://multiqc.info/docs/#prokka)
    * Either add this to your MultiQC config file, or specify on the command line: `--cl_config "prokka_fn_snames: True"`

I hope this solves your problems! Have a play and let me know if you run into any problems. Thanks for reporting the error!

Phil

**Comment by cyklee** [comment]
Thanks Phil! I really appreciate your work.
I will check out the devel version and give you the feedback.

**Comment by cyklee** [comment]
Hi Phil,

1. I can confirm `-d` now works, even when the files are sitting multiple layers of directory.
2. I can confirm `--cl_config "prokka_fn_snames: True"` now works.

Thank you very much!

**Comment by ewels** [comment]
Great stuff, thanks for letting me know!

**Comment by Ikkik** [comment]
I'm so glad that someone else had this problem and that there was already a solution!

I can also confirm that adding 

--cl_config "prokka_fn_snames: True"

fixes the problem.
