### ISSUE TITLE
Table config: ceiling / floor options

### ISSUE THREAD

**Issue by Hammarn** [ewels/MultiQC#488]
Some times you end up with samples having basically the same value for a metric but the automatic colouring that there is a big difference. I'll attach an example from `dupRadar` below. 
Normal ranges from this value is 0-1.5. If all samples are good you can have situations with the maximum being 0.08 which is practically 0:
![dupRadar int values](https://user-images.githubusercontent.com/16774076/28019051-d0eb5e3a-657f-11e7-972f-9709b758fd3c.png)

Having the option to say that the max should be 1 instead of 0.08 in this case would be great!

**Comment by ewels** [comment]
Thanks! Specifically, this is an option for `ceiling` / `floor` / `minRange` config options which are different to the existing `max` and `min` values in that any detected values which are greater than `ceiling` or less than `floor` will move the `min` and `max` to their value.

Should work in the same way as the plot options `yCeiling`, `yFloor` and `yMinRange`.

Phil

**Comment by ewels** [comment]
Ok - should now work if you set `min` to `0` and `minRange` to `1`. Then the range will stretch to any number higher than 1, but will never be less than `1`.

Phil
