### ISSUE TITLE
RSEM module

### ISSUE THREAD

**Issue by noirot** [ewels/MultiQC#489]
* **RSEM**
   * RSEM (RNA-Seq by Expectation-Maximization) is a software package for"\
             "estimating gene and isoform expression levels from RNA-Seq data.
   * https://deweylab.github.io/RSEM/
* **Log filename pattern:** `*.cnt`
* **Complete path to log file:**
    * Parse file named `.cnt` created by RSEM into sub-directory `OutputPrefix.stat/`
    * Example:
        ```
        170 7208 0 7378
        7208 0 4012
        12505 3
        0	170
        1	3196
        2	2824
        3	1105
        4	69
        5	14
        Inf	0
        ```
   * Content file explanation: https://github.com/deweylab/RSEM/blob/master/cnt_file_description.txt

* **Most interesting data for General Stats table:**
    * M reads unalignable
    * M reads alignable
    * M reads filtered
    * M reads aligned uniquely
    * M reads aligned to multiple genes
    * M reads aligned to multiple locations

* **Data suitable for MultiQC plot(s):**
    * Bar plot with 
       * M reads aligned uniquely
       * M reads aligned to multiple genes
       * M reads aligned to multiple locations

**Comment by ewels** [comment]
Thanks for this @noirot! Let me know if you need any help with the example data pull-request or module code.

Phil

**Comment by noirot** [comment]
I allready pull example data.

**Comment by ewels** [comment]
Done in #563
