### ISSUE TITLE
Install Issue (Python2.7)

### ISSUE THREAD

**Issue by tonynihgov** [ewels/MultiQC#490]
**Description of bug:**
Hi I am using Conda to install and I use:
conda install -c bioconda multiqc
This might not be Multiqc related but I'm lost and can't find the solution anywhere. Any help would be appreciated. Thanks!

**Error log:**
```
distutils.errors.LinkError: Command "gcc -pthread /tmp/easy_install-ORt3Zq/numpy-1.13.1/temp/tmplOASJJ/tmp/easy_install-ORt3Zq/numpy-1.13.1/temp/tmplOASJJ/source.o
-L/usr/lib64 -lblas -o
/tmp/easy_install-ORt3Zq/numpy-1.13.1/temp/tmplOASJJ/a.out" failed with exit status 1

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-AI0gpG/matplotlib Traceback (most recent call last):
   File "./pip2.7", line 9, in <module>
     load_entry_point('pip==1.5.6', 'console_scripts', 'pip2.7')()
   File
"/opt/rh/python27/root/usr/lib/python2.7/site-packages/pip/__init__.py",
line 184, in main
     return command.main(cmd_args)
   File
"/opt/rh/python27/root/usr/lib/python2.7/site-packages/pip/basecommand.py",
line 161, in main
     text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 79: 
ordinal not in range(128)

```

* **File that triggers the error:**
    * [please drag and drop here]
* **Operating System:**
    * Linux 2.6.32-696.3.2.el6.x86_64
* **Python Version:**
    * 2.7.8
* **Method of MultiQC installation:**
    * conda

**Comment by ewels** [comment]
Hi @tonynihgov,

Did you solve your problem? It looks like a problem with the MatPlotLib installation, but that particular one is new to me I think..

Phil

**Comment by tonynihgov** [comment]
Hi phil,
yes it was related to incorrectly installed numpy and how it did not link to the blas library. thanks for responding!
