### ISSUE TITLE
Create PDF report in different output directory

### ISSUE THREAD

**Issue by sarahet** [ewels/MultiQC#495]
Hi Phil,

First of all, thanks for this handy tool, it helped me quite a lot. Second, I have a question concerning the PDF report. When I scan a directory and set a different output directory, the PDF report is still written to the scanned directory. Everything else is written to my specified output directory.
Did I miss an option specific for the PDF or is this a known problem?

My call and output: 

```
multiqc . -f --pdf -o ~/my/fav/directory

[INFO   ]         multiqc : This is MultiQC v1.0
[INFO   ]         multiqc : --pdf specified. Using non-interactive HTML template.
[INFO   ]         multiqc : Template    : simple
[INFO   ]         multiqc : Searching '.'
Searching 131 files..  [####################################]  100%
[INFO   ]         bowtie2 : Found 3 reports
[INFO   ]     trimmomatic : Found 3 logs
[INFO   ]          fastqc : Found 6 reports
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : ../../../my/fav/directory/multiqc_report.html
[INFO   ]         multiqc : Data        : ../../../my/fav/directory/multiqc_data
[INFO   ]         multiqc : PDF Report  : multiqc_report.pdf
[INFO   ]         multiqc : MultiQC complete

```

Thanks in advance,
Sara

**Comment by ewels** [comment]
Aha, so someone does use the PDF feature! I've been thinking of removing it.. Any reason you use this instead of the HTML output, out of curiosity?

Anyway yes, this is a bug sorry. The filename handling has just been rewritten though, so it may already be fixed in v1.1dev. I'll look into it now.

Phil

**Comment by ewels** [comment]
Ok - I think this should be fixed now, was simply a case of me using the wrong variable name by accident. In my testing pandoc was throwing an error, but the command looked correct so hopefully should be fine :)

Phil

**Comment by sarahet** [comment]
Thanks a lot :)

So concerning your question I must say that I use MultiQC within a pipeline and wanted to integrate this parameter in case other users might want or need it (but it was not meant to be an either/or option but rather an additional output). In general I think the PDF cannot replace the HTML document but I thought it might be a nice supplementary if someone wants a quick overview in addition.

Sara

**Comment by ewels** [comment]
Ok great :) Note that using `--pdf` changes the report template, so the HTML output when using this option will also be simplistic. To get the fully featured HTML _and_ the PDF you'll need to run MultiQC twice I'm afraid..

Phil

**Comment by sarahet** [comment]
Ah thanks for the hint, I didn't realize this until now. I will consider this :)
