### ISSUE TITLE
leeHom for ancient DNA

### ISSUE THREAD

**Issue by grenaud** [ewels/MultiQC#496]
* **Name of tool:**
    * leeHom
* **Tool description:**
    * leeHom is a maximum-likelihood tool to perform adapter removal and merge overlapping portions 
* **Tool homepage:**
    * https://github.com/grenaud/leeHom
* **Complete log file output:**
    * [temp.log](https://github.com/ewels/MultiQC/files/1155973/temp.log.txt)
* **Log filename pattern:**
    * None (`stderr` / `--log [fn]`)
* **Most interesting data for General Stats table:**
    * `Merged (trimming)`
* **Data suitable for MultiQC plot(s):**
    * None _(insert size dist after mapping)_
    * `[Phil]: insert size dist will be a different MultiQC module`

**Comment by grenaud** [comment]
[temp.log.txt](https://github.com/ewels/MultiQC/files/1155973/temp.log.txt)

**Comment by ewels** [comment]
Aha, thanks @grenaud!  It's going to be a bit tricky to find these files, as the filename is so generic and the contents don't contain anything particularly specific to the tool. I can probably look for the string `Adapter dimers/chimeras`, should hopefully be enough.

Regarding the log filename pattern - can I double check that this summary is always saved to its own file and always ends in `.log`? As in, this isn't something that the user chooses when running the tool? If the `.log` is just convention and the summary comes from `stdout` or `stderr` then this affects how I write the module.

Thanks,

Phil

**Comment by grenaud** [comment]
you can specify whatever filename you want, you just need to supply it to --log and say --log [output prefix].leehomlog

**Comment by ewels** [comment]
Ok, so the filename can be anything? In that case we can't search for files by `.log` filename. Just checked your readme and it sounds like it goes to `stderr` by default, so easiest to assume that's the case and not put any restraints on the file search.

Phil

**Comment by grenaud** [comment]
yes, the filename can be anything. It always sends to stderr but you can get the log in --log.

**Comment by ewels** [comment]
Hi @grenaud,

I've had a stab at writing this for you. If you could grab a copy of the latest dev MultiQC version and give it a try that would be great! Note that as the statistic is a number of reads, it's formatted according to the [read count config](http://multiqc.info/docs/#number-base-multiplier). For your example file it shows `0.0` by default but it should be fine for normal samples I think (and can be customised otherwise).

Please let me know if it doesn't work or you'd like anything changing and I'll reopen the issue.

Phil

**Comment by grenaud** [comment]
wow this looks great! BTW, there is the --ancientdna  option. This merges overlapping portions of the reads that a partial overlap only. Is there a way to specify this? That is the pretty much the main option.

**Comment by ewels** [comment]
I don't understand sorry? Does this change the output format? Can you send a second example if so?

Phil

**Comment by grenaud** [comment]
No you are right, the only thing that will change is that the "Merged (overlap)" becomes non 0. But the format does chance. It is just the "Merged (overlap)" is always 0 if --ancientdna is not used. But this is not a problem in terms of formatting.

**Comment by ewels** [comment]
Ok, no problem. Did you want to report this number? I could add them when parsing and just show the total Merged number perhaps?

Phil

**Comment by grenaud** [comment]
This number should always be reported, whether --ancientdna was used or not, it's simpler that way.

Congrats on the tool and the website, it looks very neat! You have inspired me to do screen capture for my next tool and post it on Youtube.

**Comment by ewels** [comment]
ok, so you want it in the general stats table alongside `Merged (trimmed)` then?

**Comment by grenaud** [comment]
yes if possible :-)

**Comment by ewels** [comment]
ok, done :)
