### ISSUE TITLE
DamageProfiler for ancient DNA

### ISSUE THREAD

**Issue by apeltzer** [ewels/MultiQC#499]
* **Name of tool:**
    * DamageProfiler
* **Tool description:**
    *  A method to create damage plots for ancient DNA analysis.
* **Tool homepage:**
    * https://github.com/apeltzer/DamageProfiler
* **Complete log file output:**
    * [`3pGtoA_freq.txt`](https://github.com/ewels/MultiQC/files/1158874/3pGtoA_freq.txt)
[`5pCtoT_freq.txt`](https://github.com/ewels/MultiQC/files/1158873/5pCtoT_freq.txt)
[`DamagePlot.pdf`](https://github.com/ewels/MultiQC/files/1158876/DamagePlot.pdf)
[`Length_plot.pdf`](https://github.com/ewels/MultiQC/files/1158877/Length_plot.pdf)
[`lgdistribution.txt`](https://github.com/ewels/MultiQC/files/1158875/lgdistribution.txt)
* **Log filename pattern:**
    * (always the same as above...)
* **Most interesting data for General Stats table:**
    * DamagePlot.pdf
    * 3pGtoA_freq (only first 1-2 bases) , 5pCtoT_freq (only first 1-2 bases)
    * LengthPlot.pdf
* **Data suitable for MultiQC plot(s):**
    * `lgdistributions.txt` (could create a fancy histogram of length distributions of these entries, with median and mean length of reads)

**Comment by ewels** [comment]
Thanks! MultiQC can't do anything with PDF files. Is the raw data saved somewhere?

**Comment by apeltzer** [comment]
The actual data is in 3pGtoA_freq.txt and 5pCtoT_freq.txt (output is in the PDF file). We just plot that internally in the application for users, but it would work well, too if people are getting this from MultiQC I suppose. There is another application (mapDamage 2.0) that is using / generating exactly the same output, so both would be supported by this module (even file names are identical).

**Comment by ewels** [comment]
Ok, sounds good 👍

**Comment by JudithNeukamm** [comment]
I added two new files to the output of DamageProfiler (v 0.3.7):
_3p_freq_misincorporations.txt_ and _5p_freq_misincorporations.txt_

They also contain the frequency of the remaining miscorporations (not only C>T and G>A as is the case for file _3pGtoA_freq.txt_ and _5pCtoT_freq.txt_). The first line is a header line depicting the position and miscorporation type. The last two columns (->ACGT and ACGT>-) stand for insertions and deletions (example files see attached).

However, these files are not generated by mapDamage2.0, the values would have to be calculated based on the total counts in file misincorporation.txt.


[3p_freq_misincorporations.txt](https://github.com/ewels/MultiQC/files/1159121/3p_freq_misincorporations.txt)

[5p_freq_misincorporations.txt](https://github.com/ewels/MultiQC/files/1159120/5p_freq_misincorporations.txt)

**Comment by ewels** [comment]
Thanks! If it's easy to calculate from the shared files then that seems like a good way to go then I guess (get maximum support). Let's see how it goes..

@apeltzer - the GitHub link above seems broken (I get a 404). Is the repo definitely public and accessible?

**Comment by apeltzer** [comment]
Thanks, forgot to do that - it is now with a GPL v3 licence.

**Comment by apeltzer** [comment]
Long done ;-)

**Comment by sagitaninta** [comment]
Hi, may I ask if this means I can integrate mapDamage log to multiqc, or is it only for DamageProfiler?

**Comment by jfy133** [comment]
@sagitaninta this particular module is only for DamageProfiler. However the output is relatively similar, you're welcome to make a mapDamage specific module.
