### ISSUE TITLE
Module(s) for some output statistics

### ISSUE THREAD

**Issue by apeltzer** [ewels/MultiQC#500]
Hi! I found your tool to be very helpful for lots of different analysis tasks and it looks really great! 

Is there a way to also specify/calculate certain statistics for the analysis out of something that other modules have been generating? 

e.g. we use Samtools flagstat to find out how many reads mapped after BWA, then state something like endogenous DNA content (%) and have some measures to calculate library complexity (e.g. how many molecules have been duplicated / total number of molecules). Is there a way to calculate something like this based on results obtained from different modules in MultiQC? 

Of course, we could write an external tool doing this, but I thought there might be a way to do it.

**Comment by ewels** [comment]
Hi @apeltzer,

Yes you can do this but it will require custom code. MultiQC comes with a bunch of different plugin hooks where you can tie in code just like this though, see http://multiqc.info/docs/#multiqc-plugins

So you could tie a function in to the `after_modules` hook, check if Samtools has run and then access that data if so. From this you can then add an additional report section.

Let me know if that makes sense - happy to help. Could be an interesting plugin to feature here if you're interested: http://multiqc.info/plugins.html

Phil

**Comment by apeltzer** [comment]
Hi Phil,

this sounds exactly like the stuff I'd like to have - I'll have a look and ask some questions here, if there is something up. Otherwise, will try to write that up and we'll see what comes out of it ;-)

**Comment by ewels** [comment]
Sounds great! 👍
