### ISSUE TITLE
General Stats: incorrect sorting of columns with unit in cells 

### ISSUE THREAD

**Issue by jfy133** [ewels/MultiQC#501]
When sorting the 'General Stats' column and the cells of a column contains a non-numeric symbol, sorting does not occur correctly.

For example, when sorting a 'coverage' column (with X-fold coverage) in descending order, 9.0X will incorrectly come before 300X 

An example can be found here:
[multiqc-mtcap.zip](https://github.com/ewels/MultiQC/files/1159230/multiqc-mtcap.zip)

As a general point, it is redundant to have the unit symbol both in each cell and also in the header. So having % next to every value in the '% GC' column is unnecessary; having just numbers in every column would also improve the sorting issue described above. Of course, I don't know how hard it would be to parse this, given you are pulling from lots of different programs.

**Comment by ewels** [comment]
Thanks @jfy133, this definitely needs to be sorted. I remember fixing it way back in the early days in fact, so I must have broken that support somewhere along the way.

The value suffixes are added back by MultiQC so it's trivial to remove them, however the general feeling that I've had from most users is that they are welcome. It should be possible to force numeric sorting (ignoring text suffixes). But perhaps I should do a twitter poll or something to gauge support more widely :)

Phil

**Comment by ewels** [comment]
> _this definitely needs to be sorted_

Apologies for the pun..

**Comment by jfy133** [comment]
No need for apologies, it was appreciated ;).

It sounds good to me, I'll look out for the poll! Looking forward to start using MultiQC to present data to our supervisors.

**Comment by ewels** [comment]
Hi @jfy133,

This bug should be resolved now with the latest dev version. Thanks for reporting it! Let me know if you run into any problems still.

Phil
