### ISSUE TITLE
Maintain absolut path in log for report output

### ISSUE THREAD

**Issue by robinandeer** [ewels/MultiQC#508]
**Description of bug:**
When I want MultiQC to output to e.g. `/tmp` it still gives me a relative path to the output:

```
[INFO   ]         multiqc : Report      : ../../../../../tmp/multiqc_report.html
[INFO   ]         multiqc : Data        : ../../../../../tmp/multiqc_data
```

**Error log:**
see above

* **File that triggers the error:**
    `multiqc`
* **Operating System:**
    macOS
* **Python Version:**
    Python 3
* **Method of MultiQC installation:**
    pip

**Comment by ewels** [comment]
So as this is just a formatting quirk and it still works fine, I think it's probably ok to leave as it is.
