### ISSUE TITLE
No plots from samtools flagstat.

### ISSUE THREAD

**Issue by gk-bioin4m8x** [ewels/MultiQC#512]
Hi @ewels ,

MultiQC worked great for my multiple samtools flagstat files and generated `multiqc_report.html`, `multiqc_general_stats`, `multiqc_samtools_flagstat` and `multiqc_sources`.
However, I am unable to get any plots to visualize the data in a more clear manner. If I try to download plot images, it says `It is not possible to export dot plot images from reports`.
Please guide.

Thanks!

**Comment by ewels** [comment]
Hi @gk-bioin4m8x,

Unfortunately dot plots (the type of plot used by samtools stats) can't be exported from reports currently, so you'll have to just use a print screen instead.

Does this answer your question? Sorry if I've misunderstood you..

Phil

**Comment by gk-bioin4m8x** [comment]
Thanks.
Would you suggest some other way?

**Comment by ewels** [comment]
What is it that you're trying to do? The raw data values should be saved in `multiqc_data` so you can always plot them again yourself in R / Excel / wherever.

Phil

**Comment by gk-bioin4m8x** [comment]
Thanks, I did. :)
