### ISSUE TITLE
JS TypeErrors in heatmap

### ISSUE THREAD

**Issue by mwhamgenomics** [ewels/MultiQC#530]
**Description of bug:**
In the highcharts heatmap for VCFTools, I'm getting Javascript TypeErrors upon mousing over a cell. It doesn't seem to break anything, but because it occurs on every mouse-over, the browser console gets spammed with error messages.

The error occurs in multiqc_plotting.js at line 1417:
```javascript
this.pointAttr.hover.fill = this.color;
```
Removing this line (and indeed the whole `point` attribute it's inside of) seems to fix it with no ill effects, but that needs to be confirmed.

* **Operating System:**
    * macOS Yosemite 10.10.3
* **Python Version:**
    * 3.6
* **Method of MultiQC installation:**
    * pip

**Comment by ewels** [comment]
Issue is now _very_ old and I'm pretty sure that I've fixed it already. But needs checking.

**Comment by ewels** [comment]
Original code that is being mentioned (with commit ref):

https://github.com/ewels/MultiQC/blob/24a20f511d3e459639c443cadf5c52b038d4172c/multiqc/templates/default/assets/js/multiqc_plotting.js#L1413-L1414

Struggling to find where it was removed, but it is no longer present. And I'm not getting any javascript errors in the console. So must be fixed I guess! 🏆
