### ISSUE TITLE
Avatar permission

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#531]
Hi @vladsaveliev @tbooth @lpantano @dakl and @HLWiencko,

I used your GitHub avatars in the final slide of my [ISBB BOSC talk](https://f1000research.com/slides/6-1177) this weekend and F1000research need your explicit permission that it's ok for your photo to be published. I'm guessing that as you all picked these images for the purpose of being identified, it's probably fine. However, could you quickly just ping this issue to say that it's ok please?

Many thanks,

Phil

**Comment by HLWiencko** [comment]
I'm okay with it, that's no problem.

I do use that avatar knowing that it's been released into the wild and
therefore I have no control over it ever again. But I appreciate you asking
-- if everyone did, then I wouldn't have to be so carefully conscious about
photos and things. :)

<> )-(eather <>
(original mail sent to timiat@yahoo.com, but this is the same person. :) )

**Comment by vladsaveliev** [comment]
Hi Phil, absolutely fine with me :)

**Comment by ewels** [comment]
Thanks both! @HLWiencko - it is a mighty fine hat after all...

**Comment by tbooth** [comment]
Yes no problem. I just updated my pic to match my current Gravatar one but using either is fine.

**Comment by ewels** [comment]
Ping @lpantano + @dakl.. Last chance before your photos are removed from my credits slide 😉

**Comment by lpantano** [comment]
sure thing!

**Comment by ewels** [comment]
Thanks all! @dakl - I'm afraid that you've been replaced by @vezzi 😉 

Phil
