### ISSUE TITLE
picard insersizemetrics report fails

### ISSUE THREAD

**Issue by cobriniklab** [ewels/MultiQC#533]
**Description of bug:**
picard insersizemetrics report fails

**Error log:**
```Module picard raised an exception: Traceback (most recent call last):
  File "/usr/local/bin/multiqc", line 364, in multiqc
    output = mod()
  File "/usr/local/lib/python2.7/dist-packages/multiqc/modules/picard/picard.py", line 51, in __init__
    n['InsertSizeMetrics'] = InsertSizeMetrics.parse_reports(self)
  File "/usr/local/lib/python2.7/dist-packages/multiqc/modules/picard/InsertSizeMetrics.py", line 60, in parse_reports
    orientation_idx = keys.index('PAIR_ORIENTATION')
ValueError: 'PAIR_ORIENTATION' is not in list


```

* **File that triggers the error:**
  [14-CL_1_ismetrics.txt](https://github.com/ewels/MultiQC/files/1177584/14-CL_1_ismetrics.txt)
* **Operating System:**
    ubuntu 16.04
* **Python Version:**
    * [eg. Python 2.7.12]
* **Method of MultiQC installation:**
   pip install

**Comment by ewels** [comment]
Thanks for this @cobriniklab - I'm unable to replicate the error with your file though. Could you please confirm what version of MultiQC you're using? Or paste the log that it produces. It should be saved in `multiqc_data/multiqc.log` as well as being printed to standard out.

Thanks,

Phil

**Comment by ewels** [comment]
Now closing this issue as I can't replicate the error. @cobriniklab - feel free to get back to me with more info and I'll happily reopen the issue.

Phil
