### ISSUE TITLE
fastq_screen KeyError

### ISSUE THREAD

**Issue by sentausa** [ewels/MultiQC#537]
**Description of bug:**
When I run MultiQC, it tells me to copy the following traceback and report it here. Attached is the multiqc.log file: [multiqc.log](https://github.com/ewels/MultiQC/files/1187098/multiqc.log.txt)

```python
Module fastq_screen raised an exception: Traceback (most recent call last):
  File "/home/es249628/bin/mypyenv-py3/bin/multiqc", line 364, in multiqc
    output = mod()
  File "/home/es249628/bin/mypyenv-py3/lib/python3.4/site-packages/multiqc/modules/fastq_screen/fastq_screen.py", line 55, in __init__
    self.add_section( plot = self.fqscreen_simple_plot() )
  File "/home/es249628/bin/mypyenv-py3/lib/python3.4/site-packages/multiqc/modules/fastq_screen/fastq_screen.py", line 213, in fqscreen_simple_plot
    data[s_name][org] = self.fq_screen_data[s_name][org]['counts']['one_hit_one_library']
KeyError: 'counts'
```

* **Operating System:**
    * Debian GNU/Linux 8.9 (jessie)
* **Python Version:**
    * Python 3.4.2
* **Method of MultiQC installation:**
    * pip

**Comment by ewels** [comment]
Thanks @sentausa - could you please send the `*_screen.txt` results files from FastQ Screen that trigger this error so that I can replicate the problem?

I'll update the issue template to make the instructions more clear..

Phil

**Comment by sentausa** [comment]
There are two such files. I don't know which one that triggered the error. Here they are:
[LIB014528_GEN00035295_TGACCA_L001_R1_screen.txt](https://github.com/ewels/MultiQC/files/1204607/LIB014528_GEN00035295_TGACCA_L001_R1_screen.txt)
[LIB014528_GEN00035295_TGACCA_L001_R2_screen.txt](https://github.com/ewels/MultiQC/files/1204608/LIB014528_GEN00035295_TGACCA_L001_R2_screen.txt)

**Comment by ewels** [comment]
Thanks! These files were generated using FastQ Screen version 0.3.1 which is really old (released March 2012) - the current version is 0.11.1 (see the [homepage](https://www.bioinformatics.babraham.ac.uk/projects/fastq_screen/)).

Is there any reason that you need to use such an old version of the tool? The logs are missing quite a lot of information used by the module, so it's quite a bit of work to add compatibility back to this version. I will add some code to handle the error more gracefully now though.

Phil

**Comment by ewels** [comment]
Hi @sentausa,

I've just updated the code so that you get a warning saying that required data is missing and suggesting that it could be due to an old version of FastQ Screen, instead of just crashing the whole module. I hope this is ok! I'm still curious as to why you're using that version of the software though? :)

Phil

**Comment by sentausa** [comment]
I received the sequencing data (together with the FastQ Screen results) from a collaborator who did the sequencing back in 2015, maybe it explains.

**Comment by ewels** [comment]
Ah ok great, makes sense 👍  Let me know if there's anything else I can do to help.. Note that currently MultiQC is able to pull out the percentage of reads that don't map to anything in the FastQ Screen results, that data can be found in `multiqc_data/multiqc_fastq_screen.txt` if it's useful..

Phil

**Comment by sentausa** [comment]
OK thanks.
