### ISSUE TITLE
Windows Chrome 60 - table cell bars don't render properly

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#545]
It looks like Windows Chrome 60 is having difficulties rendering MultiQC table background bars properly:

![image](https://user-images.githubusercontent.com/465550/29126898-e315bb98-7d1f-11e7-97c9-299c480d5233.png)

This also seems to affect Windows IE. Windows Chrome 59 and canary appear to work just fine. This can be tested using Browserling: https://www.browserling.com/browse/win/7/chrome/60/http%3A%2F%2Fmultiqc.info%2Fexamples%2Frna-seq%2Fmultiqc_report.html

Not quite sure what's going on. It appears that the `wrapper` div has zero height:
![image](https://user-images.githubusercontent.com/465550/29127168-9df27a00-7d20-11e7-9b10-bc016accd655.png)

If a fixed height of 30px is forced in the Chrome console, the bars come back:
![image](https://user-images.githubusercontent.com/465550/29127224-ca5edc1e-7d20-11e7-9be9-6a2b9c877e0c.png)

Manually assigning a height to the parent `<td>` element works even better:
![image](https://user-images.githubusercontent.com/465550/29127355-21a0a3ae-7d21-11e7-8f01-e8b0a7f947da.png)

It doesn't seem to matter what height this is for the fix to work - setting `height: 1px` makes everything work properly. Can't tell if this also fixes the IE rendering as the developer console didn't seem to work in Browserling.

Phil

**Comment by bbimber** [comment]
I can confirm that setting style="height: 1px;" on the parent <td> fixes this on both win7/chrome 60 and IE11.  Thanks for the quick investigation.

**Comment by ewels** [comment]
Yup, I think assigning any fixed height should fix it, irrespective of what that is. It's a rendering bug where the internal `100%` height doesn't have anything to go on without that. Others have come across the same thing: https://stackoverflow.com/a/22220780/713980

I'll add `height: 30px` as it shouldn't have any negative effects (that I can think of anyway) and should solve this edge case.

Phil

**Comment by ewels** [comment]
Ok, this isn't OS specific either. My version of Chrome on Mac just updated from v59 to v60 and now I get the same rendering error.
