### ISSUE TITLE
request Picard submodule for TargetedPcrMetrics

### ISSUE THREAD

**Issue by annavt** [ewels/MultiQC#549]
Hi Phil, I have a request for another Picard metrics output
* **Name of tool:**
    * Picard  TargetedPcrMetrics
* **Tool homepage:**
    * https://broadinstitute.github.io/picard/picard-metric-definitions.html#TargetedPcrMetrics
* **Most interesting data for General Stats table:**
    * `MEDIAN_TARGET_COVERAGE`
    * `PCT_AMPLIFIED_BASES`
* **Data suitable for MultiQC plot(s):**
    * dual barplot of `ON_AMPLICON_BASES` & `NEAR_AMPLICON_BASES` & `OFF_AMPLICON_BASES` (raw and as % of `PF_BASES_ALIGNED`)

many thanks
Anna

[AS-13.targetedPcrMetrics.txt](https://github.com/ewels/MultiQC/files/1223587/AS-13.targetedPcrMetrics.txt)

**Comment by ewels** [comment]
Thanks for the detailed request @annavt! I've just written this for you, if you could grab the latest development version of MultiQC and give it a try that'd be great!

Phil

**Comment by annavt** [comment]
Hi Phil,
Just tried it out and it works fine and looks great.
Thankyou
Anna
