### ISSUE TITLE
New Module: Homer tag directory

### ISSUE THREAD

**Issue by rdali** [ewels/MultiQC#550]
Hello, 

I really love MultiQC, but it can become more awesome if we can integrate Homer tag directory QC plots useful for ChIP-Seq and Hi-C.
I have filled out the information below; If there is anything I can do to help, let me know!

* **Name of tool:**
HOMER
* **Tool description:**
HOMER has many useful modules including the "tag directory" module which is used for several analyses, including ChIP-Seq and Hi-C. The tag directory creation includes several useful QC files that would help evaluate the success of experiments. 

* **Tool homepage:**
http://homer.ucsd.edu/homer/interactions/HiCtagDirectory.html

* **Complete log file output:**
[petagRestrictionDistribution.GATC.mis0.txt](https://github.com/ewels/MultiQC/files/1225368/petagRestrictionDistribution.GATC.mis0.txt)
[tagGCcontent.txt](https://github.com/ewels/MultiQC/files/1225369/tagGCcontent.txt)
[petag.FreqDistribution_1000.txt](https://github.com/ewels/MultiQC/files/1225370/petag.FreqDistribution_1000.txt)
[tagCountDistribution.txt](https://github.com/ewels/MultiQC/files/1225372/tagCountDistribution.txt)
[tagInfo.txt](https://github.com/ewels/MultiQC/files/1225374/tagInfo.txt)

* **Log filename pattern:**
    * `petagRestrictionDistribution.*.mis0.txt`
    * `tagGCcontent.txt`
    * `petag.FreqDistribution_1000.txt`
    * `tagInfo.txt`

* **Most interesting data for General Stats table:**
    * sample GC content, which can be calculated from `tagGCcontent.txt`
    * sample duplication level, which can be calculated from `tagCountDistribution.txt`

* **Data suitable for MultiQC plot(s):**
    * plotting suggestions are available on the HOMER page but here is what I do:
    * `petagRestrictionDistribution.*.mis0.txt`
        plot as line  plot to look at read distribution around restriction site. if the reads are not centered around the restriction enzyme then the experiment is inefficient.
[petagRestrictionDistribution.pdf](https://github.com/ewels/MultiQC/files/1225395/petagRestrictionDistribution.pdf)
    * `tagGCcontent.txt`
        plot as line plot to look at tag GC distribution and see if it matches genome GC distribution found in file (genomeGCcontent.txt)
[tagGCcontent.pdf](https://github.com/ewels/MultiQC/files/1225398/tagGCcontent.pdf)
    * `petag.FreqDistribution_1000.txt`
    plot as line plot of log(x), log(y) to check the read distribution as function of distance
![petag freqdistribution_1000](https://user-images.githubusercontent.com/8022125/29321137-7059d5ee-81a7-11e7-833f-f94cb98fef76.png)
    * `tagInfo.txt`
    allows to evaluate the distribution of read across chromosomes. Useful in identifying large duplications/deletions in chromosomes
[tagInfo.pdf](https://github.com/ewels/MultiQC/files/1225404/tagInfo.pdf)

**Comment by ewels** [comment]
Hi @rdali,

Thanks for the detailed issue! Everything you've proposed sounds sensible. Some of the plots will have to be simplified a little to fit in with how MultiQC works - for example, probably combining the two lines from `petagRestrictionDistribution.pdf` so that there's a single line per sample and splitting the two categories from `tagInfo.pdf` into separate plots (like with the cutadapt line plots). We'll have to simplify the line in `petag.FreqDistribution_1000.txt` to reduce the number of points to avoid crashing the browser when there are lots of samples. But this is all very achievable.

Anyway, I've labelled this issue and added it to the to-do list. If you'd like to help and would like this done quickly, you are of course welcome to have a go at writing the module yourself! Everything is documented [here](http://multiqc.info/docs/#coding-with-multiqc) and there's already a module stub for HOMER so some example code to get started with there. No worries if not, I'll get to it when I can.

Phil

**Comment by rdali** [comment]
Hey Phil, 

That sounds great. I look forward to the added module. I will take a look at the documentation and try to write it myself but it does look a little intimidating. 

Thank you very much!
Rola

**Comment by ewels** [comment]
If you're curious then the best place to start for this is actually the [existing homer code](https://github.com/ewels/MultiQC/blob/master/multiqc/modules/homer/findpeaks.py) - most of the stuff described in the docs that I linked to has already been done for homer :)

Phil

**Comment by rdali** [comment]
I will certainly take a look and try!

Rola

**Comment by rdali** [comment]
Hey Phil,
I wanted to let you know that I am working on this. When you are ready to work on it, let me know so that you dont start from scratch.
Rola

**Comment by ewels** [comment]
Great stuff, thanks for letting me know! Don't hesitate to shout if I can be of any help..

Phil

**Comment by rdali** [comment]
I did have a couple of questions:

You mentioned that for petag.FreqDistribution_1000.txt we should aim to reduce the number of points. 
a- How many points should the maximum be you think?
b- How do you recommend we reduce the points? I tried to average every 2 consecutive points into one but that seems to change the profile of some plots where the distribution in not smooth. Now I am thinking of skipping every other point? What do you think?

**Comment by ewels** [comment]
1. Needs a bit of trial and error to see at what point the data starts to look "wrong". But I'd say a starting point would be ~200 - 500 points..?
2. There is already a function to do this for you. Just specify `smooth_points` in the plot config. You probably also want to specify `smooth_points_sumcounts: False` in the config to have averages instead of summed bins. See the [docs](http://multiqc.info/docs/#line-graphs) for (a little) more info. Apologies, this functionality isn't very well documented.

**Comment by rdali** [comment]
I have added 5 plots and 7 metrics to the stats table ([example](https://drive.google.com/open?id=0B65z057gRyb3QW55S05NLW1LWlE)).
I have 3 more questions:

1- homer creates files with the exact same name. The directory name is the sample name. I am currently running multiqc as "multiqc . -d" to get the different sample names, but would like to actually automatically append the directory name to the sample name for all homer files without the need for -d option. What is the best way to do this?

2- The FreqDist plot (Frequency Distribution) should be plotted as log10(x), and log10(y).
even though I used:            
'xLog' : True,
'yLog' : True
in my config parameters, the x-axis doesn't seem to be logged. Can I log both x and y? and what do you think is happening here?
(btw, I used 2000 points and it seems fine and fairly fast)

3- What happens now? This is my first time trying to contribute to any tool. Can you walk me through the process?

**Comment by ewels** [comment]
Hi @rdali,

The example report looks great! Congrats for coming along so far with this so quickly..

1. This is no problem, you just need to pull out a sample name manually. Several other modules already do the same thing with the directory name, for example [Salmon](https://github.com/ewels/MultiQC/blob/3d0ae8881957152ea0015f2b9e44042a006f82fe/multiqc/modules/salmon/salmon.py#L30-L32)
    * Note that you need to pass this custom sample name to the `add_data_source` function as you're not using the default, as done [here](https://github.com/ewels/MultiQC/blob/3d0ae8881957152ea0015f2b9e44042a006f82fe/multiqc/modules/salmon/salmon.py#L47).
2. Yeah, I think you should be able to use both `xLog` and `yLog` as you've described. I can look into this when you submit a PR if you highlight the problematic code in a comment (see below link for description of how the review process will work).
3. I've written some contribution documentation [here](https://github.com/ewels/MultiQC/blob/master/.github/CONTRIBUTING.md). Hopefully that walks you through what to do - please ask if anything is unclear though!

Phil

**Comment by rdali** [comment]
done! 

Thanks :)

**Comment by ewels** [comment]
Module written and merged 👍
