### ISSUE TITLE
Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using ':0.0' as the value of the DISPLAY variable.

### ISSUE THREAD

**Issue by splaisan** [ewels/MultiQC#553]
I try to run qualimap bamqc
I set the display to 0 as in the FAQs-> no improvement - then I unset the DISPLAY
I also added -Djava.awt.headless=true to the launcher
I still get the X11 error when running qualimap as a given user and not as another one (the genepattern user which has probably somewhat less system access).
Would you happen to know what user-specific setting could be responsible for this? (I know I am asking a lot here ;-)
Thanks
Stephane

**Comment by ewels** [comment]
Hi Stephane,

It sounds like this is a problem with running Qualimap, not MultiQC right? I'm not involved in the Qualimap project so I can't be much help here. It looks like they have a support mailing list where you could ask though: https://groups.google.com/forum/#!forum/qualimap

Let me know if I'm misunderstanding your question..

Phil

**Comment by splaisan** [comment]
you are correct, sorry for the post here and thanks for the link, I did not find it before.

**Comment by ewels** [comment]
No problem - good luck!
