### ISSUE TITLE
Typo/error in docs

### ISSUE THREAD

**Issue by freekvh** [ewels/MultiQC#562]
Hi, just a small thing, in the docs it says:

> To avoid this, run MultiQC with the -d/--dirs parameter. This will prefix every sample name with the directory path that the log file was found within. As such, sample names will no longer be unique, and data will not be overwritten.

But I think you mean:

> To avoid this, run MultiQC with the -d/--dirs parameter. This will prefix every sample name with the directory path that the log file was found within. As such, sample names will become unique, and data will not be overwritten.
(or something similar.)

Highest regards and thank you for MultiQC.

**Comment by ewels** [comment]
Great spot, thanks! Now fixed.
