### ISSUE TITLE
AfterQC can't create bar graph

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#565]
Reported by @marchoeppner in https://github.com/ewels/MultiQC/pull/528#issuecomment-324830910:

> Not sure this is the right place, but was trying to run this module on an AfterQC Json file and got this:
> 
> ```
> multiqc F12505-L2_S32_L003_R1_001.fastq.gz.json
> 
> [INFO   ]         multiqc : This is MultiQC v1.2
> [INFO   ]         multiqc : Template    : default
> [INFO   ]         multiqc : Searching 'F12505-L2_S32_L003_R1_001.fastq.gz.json'
> Searching 1 files..  [####################################]  100%
> [INFO   ]         afterqc : Found 1 reports
> [WARNING]        bargraph : Tried to make bar plot, but had no data
> [INFO   ]         multiqc : Compressing plot data
> [INFO   ]         multiqc : Report      : multiqc_report.html
> [INFO   ]         multiqc : Data        : multiqc_data
> [INFO   ]         multiqc : MultiQC complete
> ```
> 
> AfterQC version: 0.9.6
> MultiQC: 1.2
> 
> And the JSON file definitely contains data, so unclear at the moment why this doesn't work for me. Any ideas?
>
> And the JSON file: https://pastebin.com/p5LM4yLE

**Comment by ewels** [comment]
Hi @marchoeppner,

So it looks like AfterQC have updated the JSON key that the module uses from `summary` to `afterqc_main_summary`, which broke stuff. The files don't appear to mention the AfterQC version, so I'm not sure when this happened, but I've pushed a change to accommodate both formats anyway.

It's interesting that your example file has several new keys (`gc_content`, `base_quality`) that I haven't seen before. So there is probably scope for expanding this module to plot some of this data. Would that be of interest?

Phil

**Comment by marchoeppner** [comment]
Thanks for the quick update! Figured it'd be something like this...
I suppose the other statistics would be useful as well - honestly, I just started testing AfterQC, so I wouldn't know :D . We had a sequencing project with some bad tiles (bubbles, I suspect) and other read trimmers don't seem to deal with that very well.

**Comment by ewels** [comment]
Ok great - feel free to create a new issue if you would like any new features (or a PR of course 😉 )

Phil
