### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by rekado** [ewels/MultiQC#567]
Hello there,

thank you for releasing MultiQC under a free software license, a copyleft license even!  Could you please clarify whether this is "GPL version 3 only", or "version 3 or any later version"?

The "or later" upgrade clause is designed to avoid problems in combining software under different versions of the GPL in one project.  Since the source files of MultiQC do not include license headers it is not clear to me if the upgrade clause is implied.

It would be great if you could clarify this!
Thanks!

**Comment by ewels** [comment]
Hi @rekado,

That's an excellent question - I've not come across the "or later" clause before. I don't have any problem adding it though, would a mention in the readme be sufficient? I think the GitHub tag is taken from the licence file automatically, and I can't find anything on the web about changing that to add the `+`.

As there's no GPL v4 yet, is this causing a specific problem or a hypothetical future one? Part of the reason that I ask is because I've been thinking of changing to MIT, which all of our other software packages at SciLifeLab use. But I'd need to check with the MultiQC community quite a bit first before I do anything with that.

Phil

**Comment by matheuscburger** [comment]
Hi @ewels , 
I also have a question regarding the license of MultiQC.
I would like to know if I have to buy a Higcharts license in order to use MultiQC in a for-profit organization.

Thanks

**Comment by ewels** [comment]
Eek, that's a great question @matheuscburger - it's not something that I've had to look into before. I guess that there are probably other packages that MultiQC also uses such as MatPlotLib with their own licences. I'm afraid that I don't know the answer so I can't be of much help. If you find out it would be great to know for the future though!

Phil

**Comment by rekado** [comment]
Hi Phil,

> That's an excellent question - I've not come across the "or later"
> clause before.

Thanks for the quick response!

The “or later” clause is very common.  License headers often say
something like this:

  Foo is free software; you can redistribute it and/or modify it
  under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 3 of the License, or (at
  your option) any later version.

This is also the recommended text in the license itself.

> I don't have any problem adding it though, would a
> mention in the readme be sufficient? I think the GitHub tag is taken
> from the licence file automatically, and I can't find anything on the
> web about changing that to add the `+`.

Yes, adding it to the README would be sufficient.  (The recommended way
is to add license headers to each source file under copyright to avoid
any ambiguity, but it isn’t strictly necessary.)

> As there's no GPL v4 yet, is this causing a specific problem or a
> hypothetical future one?

To this day there are problems combining software A under “GPLv2 only”
and software B “GPLv3 (or later)” or “GPLv3 only” because the licenses
are incompatible.  One famous example is Linux, which frustratingly is
under “GPLv2 only”.

This would likely also be the case if/when GPLv4 is released, because
the GPL prohibits adding additional restrictions.  Newer versions of the
GPL plug loopholes in the license text by adding explicit restrictions;
thus newer versions of the license are automatically incompatible with
previous versions.

When using the GPL it is recommended to not restrict it to one
specific version by allowing the user to upgrade to a later version of
the license, if they so choose.

> Part of the reason that I ask is because I've
> been thinking of changing to MIT, which all of our other software
> packages at SciLifeLab use. But I'd need to check with the MultiQC
> community quite a bit first before I do anything with that.

Relicensing is tough as you require permission from all past
contributors.  With the Expat license (aka “MIT license”) you don’t have
a problem with license incompatibilities, but you’ll also lose copyleft,
which ensures that the software remains software libre.

For more on license (in)compatibility and relicensing I recommend this
essay by Richard Stallman (one of the primary authors of the GPL):
https://www.gnu.org/licenses/license-compatibility.html

--
Ricardo

**Comment by uros-sipetic** [comment]
Hey, since MultiQC uses highchart.js (which is free for academic use only), is it still ok for MultiQC to be under the GPL3 license (which allows for commercial use)?
