### ISSUE TITLE
paired-end fastqc

### ISSUE THREAD

**Issue by caleblareau** [ewels/MultiQC#575]
Hey Phil,

Thanks for the great tool. I had a quick question--

I'm running fastqc on some paired-end samples alongside some other tools but ultimately want to collapse and have one fastqc output as part of my multiqc report. I noticed on all of your sample reports that you have only a single fastqc entry per sample. Currently, I wind up with something like this--

```
sample_1: fastqc results
sample_2: fastqc results
sample: bowtie results
```

whereas I'd like
```
sample: fastqc + bowtie
```
Is there any obvious way of running multiqc or fastqc to facilitate this? Sorry if I missed it. Thanks!

**Comment by ewels** [comment]
Hi @caleblareau,

Great question, this is one of my major annoyances with MultiQC and one of those problems that sounds simple but is increasingly complex the more you think about it.

Currently, I usually avoid this by specifying `_1` and `_2` in the config for [cleaning sample names](http://multiqc.info/docs/#sample-name-cleaning). This makes `sample_1` and `sample_2` both end up as `sample` - which ever file is parsed second (semi-random) will be displayed and the other ignored. It's fair from ideal, but does mean that the don't have duplicates.

However, this topic has been discussed several times (see #542) and we now have two solutions under consideration in both #576 and #566. These will hopefully be merged soon into the main branch and later make it out into a full release. When this happens, you should get a row called `sample` in the General Statistics table with average values for both reads and then tabs for each plot to show both read 1 and read 2.

Feel free to pull my [`group_samples`](https://github.com/ewels/MultiQC/tree/group_samples) branch if you want a preview of this behaviour, any comments or feedback on that PR (#576) welcome if you do.

Phil

**Comment by ewels** [comment]
Closing as essentially a dup of #542

**Comment by caleblareau** [comment]
Thanks @ewels-- very insightful; I appreciate it!
