### ISSUE TITLE
Don't prepend | with -d if samples are in the cwd

### ISSUE THREAD

**Issue by amkilpatrick** [ewels/MultiQC#578]
I'm running Rsubread::featureCounts as part of an RNA-seq pipeline, but somewhere in MultiQC, I'm getting `| ` (pipe followed by a space) prepended to the sample names, so each sample appears in the html report twice: once for featureCounts (with the extra pipe), and once for all other tools (currently TopHat, Bowtie2 and FastQC).

If it makes any difference, the extra characters also appear in my `multiqc_data/multiqc_featureCounts.txt` file. I've tried adding:

```yaml
extra_fn_clean_trim:
    - '\|'
```
to my `~/.multiqc_config.yaml` file, but without success; adding a type to this (as in the troubleshooting) seems to result in an error. This doesn't seem to have been reported before so it may well be something I've missed, any advice appreciated though. Thanks!

* **File that triggers the error:**
    * [featureCounts.summary.zip](https://github.com/ewels/MultiQC/files/1280787/featureCounts.summary.zip)
* **MultiQC Version:**
    * 1.3.dev0
* **Operating System:**
    * ubuntu 16.4
* **Python Version:**
    * 2.7.12
* **Method of MultiQC installation:**
    * manual/git

**Comment by ewels** [comment]
Hi @amkilpatrick,

You're on the right track with `extra_fn_clean_trim`, however that will only remove pipe characters from the end of the sample names. Also this type of search isn't a regex, so you don't need to escape the pipe, so the `\` character would stop it working.

There are other search types that you can use for sample name cleaning luckily (see the [docs](http://multiqc.info/docs/#other-search-types)). I think that the following should work in your case:

```yaml
extra_fn_clean_exts:
    - type: remove
      pattern: "|"
```

This will remove all pipe characters from your sample names. If you want to restrict this to just those that are at the start of the sample names, you can use the following:

```yaml
extra_fn_clean_exts:
    - type: regex
      pattern: '^\|'
```

I hope this helps! If it still doesn't work then let me know and I can try testing them myself..

Phil

**Comment by ewels** [comment]
Hi @amkilpatrick,

Sorry, quick-fire follow up. I just downloaded your example data and had a look / tried it myself. I don't get any pipe characters or see why they would be there from the file. I guess that you must be running MultiQC with the directory prepending option (`-d`/`--dirs`). This will add pipe characters as directory separators, so if your featureCounts file is in the working directory, the sample names will be prepended with `| ` as you describe.

This directory prepending happens _after_ the sample name cleaning, so none of the `extra_fn_clean_exts` stuff described above will make any difference to this pipe.

Probably the easiest fix for you is to just not specify `-d`. However, I guess that MultiQC probably should avoid adding a single pipe if samples are in the working directory, so I'll look into making that change as well.

Phil

**Comment by ewels** [comment]
Hi @amkilpatrick,

It was a quick fix to prevent the addition of the first `|` when there are no subdirectories and `-d` is specified, so I've just pushed that change to the master branch. Let me know how you get on!

Cheers,

Phil

**Comment by amkilpatrick** [comment]
Hi @ewels,
You're right, I'd used -d to fix another issue with sample names coming from TopHat, I'll need to look into that further. In the meantime I've pulled the latest version and it works perfectly - thanks for the speedy response!

All the best,
Alastair

**Comment by ewels** [comment]
Ok great, thanks for getting back to me. And if there's any generic improvements that can be made with tophat sample naming, let me know ;)

Phil
