### ISSUE TITLE
Respecting sample order in barplots

### ISSUE THREAD

**Issue by dpryan79** [ewels/MultiQC#581]
This is a non-module feature request, so I hope you won't mind if I dispense with the templates.

When creating a bargraph plot one can request a specific order of the categories within each sample. That's sufficient when the categories are all grouped together by sample. However, as is already the case in the fastq_screen module, when one instead wants to nest samples in the categories then it'd be preferable to either pass a `samples` list or, better yet, just use an `OrderedDict()` and have MultiQC respect that. As is, MultiQC is [sorting things](https://github.com/ewels/MultiQC/blob/master/multiqc/plots/bargraph.py#L98).

Below is an example demonstrating my particular use case:

```python
OrderedDict([
    ('X-intercept', {'sample1': 0.384324723042, 'sample2': 0.0105007515448}),
    ('Synthetic X-intercept', {'sample1': 0.0, 'sample2': 0.0}),
    ('Elbow Point', {'sample1': 0.80857178645, 'sample2': 0.80652591438}),
    ('Synthetic Elbow Point', {'sample1': 0.498885480302, 'sample2': 0.501149702022}),
    ...])
```

That's a snippet of what one gets from `plotFingerprint --outQualityMetrics` in deepTools, which is what I happen to be creating a module for at the moment. If I use that with `bargraph.plot()`, then it's no longer the case that the synthetic and observed metrics are next to each other. Rather, the categories are just sorted:

![image](https://user-images.githubusercontent.com/6399000/30212100-ba9f9530-94a3-11e7-9045-622a954a3b2d.png)

I would propose checking for an `OrderedDict()` in `bargraph.py` and not sorting the list of keys if one is used. In python 3.6 it happens that all dictionaries are ordered, but since (A) that isn't guaranteed to be the case in python 3.7 (though I would bet it will be) and (B) I'm not sure how many people really know that, it would suggest omitting any python version checks for the time being.

My PR for a deepTools module contains one possible implementation of this.

**Comment by ewels** [comment]
Hi @dpryan79,

Am I right in thinking that this is now implemented and can be closed since your deepTools PR was merged?

Phil

**Comment by dpryan79** [comment]
Yup, closing.
