### ISSUE TITLE
module request: rtg vcfstats

### ISSUE THREAD

**Issue by AlfredoKCL** [ewels/MultiQC#584]
Hello all,

would it be possible to have rtg vcfstats  too?

Name of tool: rtg vcfstats 

Tool homepage: https://github.com/RealTimeGenomics/rtg-tools

log: 

```
Location                     : freebayes.vcf.gz
Failed Filters               : 0
Passed Filters               : 99
SNPs                         : 75
MNPs                         : 1
Insertions                   : 1
Deletions                    : 5
Indels                       : 1
Same as reference            : 16
SNP Transitions/Transversions: 2.92 (73/25)
Total Het/Hom ratio          : 2.46 (59/24)
SNP Het/Hom ratio            : 2.26 (52/23)
MNP Het/Hom ratio            : - (1/0)
Insertion Het/Hom ratio      : - (1/0)
Deletion Het/Hom ratio       : - (5/0)
Indel Het/Hom ratio          : 0.00 (0/1)
Insertion/Deletion ratio     : 0.20 (1/5)
Indel/SNP+MNP ratio          : 0.09 (7/76)
```

**Comment by AlfredoKCL** [comment]
Hello !

I was wondering if you could let me know when (approximately) the module would be available :) 

Cheers

Alfredo

**Comment by ewels** [comment]
Hi @AlfredoKCL,

The million dollar question! Free time for me to work on MultiQC is increasingly limited and increasingly random, so I can't give you a good answer sorry. I'll try to get to it as soon as I can though.

If you could give the following information (should have been in the issue template?) then that helps a lot as I don't have to dig it out myself:

* [x] **Name of tool:** rtg vcfstats
* [ ] **Tool description:**
* [x] **Tool homepage:** https://github.com/RealTimeGenomics/rtg-tools
* [ ] **Complete log file output:**
    * As file attachment please - GitHub can alter whitespace and formatting. Just drag and drop the file onto the issue.
* [ ] **Log filename pattern:** (if any by tool - if it's user specified, stdout etc then let me know)
* [ ] **Most interesting data for General Stats table:**
* [ ] **Data suitable for MultiQC plot(s):**

Regarding the last two - looking at the log output I guess it would probably be best to just put all of those numbers into a table, then perhaps put the `Passed Filters` and `SNP Ts/Tv` into the top _General Statistics_ table alongside metrics from the other modules?

**Comment by ewels** [comment]
Note to self - docs for this tool are [here](https://cdn.rawgit.com/RealTimeGenomics/rtg-tools/master/installer/resources/tools/RTGOperationsManual/rtg_command_reference.html#vcfstats)

Unresolved questions needed before I can write this:

* [ ] How is the output saved? I'm guessing it's stdout, but this isn't mentioned anywhere.
* [ ] What happens to the output if a VCF file with multiple samples is given?
* [ ] What happens to the output if multiple VCF files are given?

Phil

**Comment by ewels** [comment]
Closing due to lack of feedback on required questions.
