### ISSUE TITLE
illumina InterOp

### ISSUE THREAD

**Issue by matthdsm** [ewels/MultiQC#585]
Hi,

I was wondering if it would be possible to expand the bcl2fastq module to include some stats from the sequencer. For example, the Illumina Hiseq series output some binary files, which are normally uploaded to BaseSpace, but can be parsed with python

* **Name of tool:**
    * [interop summary]
* **Tool description:**
    * [The Illumina InterOp libraries are a set of common routines used for reading and writing InterOp metric files. These metric files are binary files produced during a run providing detailed statistics about a run. In a few cases, the metric files are produced after a run during secondary analysis (index metrics) or for faster display of a subset of the original data (collapsed quality scores).]
* **Tool homepage:**
    * [http://illumina.github.io/interop/index.html]
* **Complete log file output:**
  
[HSQ_070.txt](https://github.com/ewels/MultiQC/files/1299265/HSQ_070.txt)

* **Log filename pattern:**
  NA

I know this info is a bit sparse, but I'm still looking into this. I do know this will become an essential part of our QC if we get it to work.

Cheers!
M

**Comment by ewels** [comment]
Hi @matthdsm,

This has been mentioned as a possibility before, but as I remember it's tricky as this isn't a tool that provides a standard output. So MultiQC would have to do quite a bit of processing itself rather than just slurping up a few summary statistics from a log file. Of course it's still possible, but needs consideration about processing time and filesizes and a bunch of other complications.

If you could provide specifics of what you'd like to see that would be helpful (especially if we can pull them from the JSON summary for example).

Cheers,

Phil

**Comment by matthdsm** [comment]
Hi Phil,

Thanks for your reply. I've been looking around a bit more and found the following:
http://illumina.github.io/interop/index.html
Apparently, Illumina has it's own executables for parsing the InterOp files, which output in csv and GNU plot format. They also provide a python interface for the C++ library.

I don't know if you're familiar with the Basespace interface from Illumina, but if possible we'd like to have the same Run and Lane metrics available in the report as are available on there.

I've included a screenshot of the basespace interface. I'll have to look into the executables some more to see which ones are needed to recreate the table.


Cheers
M

![schermafbeelding 2017-09-13 om 13 19 33](https://user-images.githubusercontent.com/11850640/30374787-6f45e134-9886-11e7-9a1c-5e4d4aeb41c4.png)

**Comment by matthdsm** [comment]
Hi again,

I've included the output of the interop summary tool. This is a simple csv file, and should include alle the metrics shown in the previous screenshot.
I suppose this should be fairly straightforward to include in MultiQC. The file however, has no standard naming, since the tool outputs to stdout.

Cheers
M

[HSQ_070.txt](https://github.com/ewels/MultiQC/files/1299251/HSQ_070.txt)

**Comment by ewels** [comment]
Great stuff, many thanks @matthdsm - I'll take a look into this when I get a chance, it looks promising.. I guess that there should be scope for generating some nice plots as well as the table? The [examples](http://illumina.github.io/interop/example_sav_analysis_example.html) look quite nice..

Phil

**Comment by ewels** [comment]
ps. I'm away travelling this week and there's quite a backlog of MultiQC issues and pull requests at the moment. So it'll probably be a little while before I can get to this sorry. If you're in a rush feel free to have a stab at writing something yourself - docs are [here](http://multiqc.info/docs/#coding-with-multiqc).

**Comment by matthdsm** [comment]
Don't mind if I do! I'll do my best to find some time to prepare a PR.

Cheers!
M

**Comment by ewels** [comment]
ok great! If you can, it's great if you could pop some example output files to https://github.com/ewels/MultiQC_TestData as a first step. This helps with the automated testing and helps me for if/when a PR comes in..

Phil

**Comment by matthdsm** [comment]
Added testdata  ewels/MultiQC_TestData#63

**Comment by matthdsm** [comment]
Also added a [PR](#589) with work in progress, all comments are welcome!

Cheers!
M

**Comment by ewels** [comment]
Done and merged.

**Comment by matthdsm** [comment]
Hi Phil, 

Great! Thanks for all your efforts!

Cheers
M
