### ISSUE TITLE
GATK 4 support (MarkDuplicates)

### ISSUE THREAD

**Issue by marchoeppner** [ewels/MultiQC#588]
Hi,

I started switching our Exome pipeline to GATK4 (including the now built-in MarkDuplicates algorithm) and found MultiQC not to be able to recognize the slightly changed metrics output. Perhaps this could be added? The full release of GATK4 is supposedly imminent, would be nice if MultiQC would work with it soon (time permitting, of course).

PIcardTools 2.x:

```
## htsjdk.samtools.metrics.StringHeader
# picard.sam.markduplicates.MarkDuplicates INPUT=[/ifs/data/nfs_share/sukmb352/projects/pipelines/exomes/trio/test/work/e5/3e34123836da8b359e6f4a53664d0d/S00113_G00078-L2_G00078-L2_1.aligned.bam] OUTPUT=S00113.dedup.bam METRICS_FILE=S00113_duplicate_metrics.txt TMP_DIR=[tmp] CREATE_INDEX=true    MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP=50000 MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=8000 SORTING_COLLECTION_SIZE_RATIO=0.25 REMOVE_SEQUENCING_DUPLICATES=false TAGGING_POLICY=DontTag REMOVE_DUPLICATES=false ASSUME_SORTED=false DUPLICATE_SCORING_STRATEGY=SUM_OF_BASE_QUALITIES PROGRAM_RECORD_ID=MarkDuplicates PROGRAM_GROUP_NAME=MarkDuplicates READ_NAME_REGEX=<optimized capture of last three ':' separated fields as numeric values> OPTICAL_DUPLICATE_PIXEL_DISTANCE=100 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
## htsjdk.samtools.metrics.StringHeader
# Started on: Wed Sep 13 12:45:47 CEST 2017
```

GATK4b5

```
## htsjdk.samtools.metrics.StringHeader
# MarkDuplicates  --input /ifs/data/nfs_share/sukmb352/projects/pipelines/exomes/trio/test_gatk4/work/18/9776617f54b6e40a5a4089cff2f663/S00111_G00076-L2_G00076$
## htsjdk.samtools.metrics.StringHeader
## Started on: September 15, 2017 11:38:03 AM CEST
[S00111_duplicate_metrics.txt](https://github.com/ewels/MultiQC/files/1306033/S00111_duplicate_metrics.txt)

```

MultiQC error:

 Command output:
```
  Searching 3 files..
  Searching 3 files..
```

Command error:
```
  [INFO   ]         multiqc : This is MultiQC v1.2
  [INFO   ]         multiqc : Template    : default
  [INFO   ]         multiqc : Searching 'S00111_duplicate_metrics.txt'
  [INFO   ]         multiqc : Searching 'S00112_duplicate_metrics.txt'
  [INFO   ]         multiqc : Searching 'S00113_duplicate_metrics.txt'
  [WARNING]         multiqc : No analysis results found. Cleaning up..
  [INFO   ]         multiqc : MultiQC complete
```

[S00111_duplicate_metrics.txt](https://github.com/ewels/MultiQC/files/1306034/S00111_duplicate_metrics.txt)

**Comment by marchoeppner** [comment]
Had to escape the hash tags (so the '\' is of course not part of the metrics report...)

**Comment by ewels** [comment]
Use three backticks on their own lines for code blocks:
```
like this
```

**Comment by ewels** [comment]
But yes - I can make those changes, no problem. Please could you attach the output of the tools as files rather than copying and pasting into the issue? GitHub formatting often changes stuff like whitespace so it's good to have the raw output if possible (or submit a PR [here](https://github.com/ewels/MultiQC_TestData/tree/master/data/modules/picard/MarkDuplicates) if you prefer).

**Comment by ewels** [comment]
Hi @marchoeppner,

Sorry for the slow responses here. Do you have some files that you could send over? I think that the change should be easy, but I'd like to have some files to test on to confirm that any new code actually works.

Thanks,

Phil

**Comment by marchoeppner** [comment]
Have been attached to the original post back when you requested them; or do you need anything more?

**Comment by ewels** [comment]
Ah yes, at the bottom! Sorry, I missed that.

**Comment by sndrtj** [comment]
This not only occurs when using GATK4. I can report the same header format occurring when calling Picard natively, on version 2.14.1 (the latest on bioconda). This may be related to [this](https://github.com/broadinstitute/picard/pull/965) change.

**Comment by ewels** [comment]
Hi all,

This should now be fixed (see #666). If you could test the latest development version and let me know that would be great.

I may still need to remove the requirement for there to be the word “Picard” in the log file I guess in the GATK case..?

Phil

**Comment by ewels** [comment]
Sorry @marchoeppner, just realised that you had attached the full output file. As I feared it didn't work with the `picard` string requirement and worse had a different format for input filenames.

Both of these issues now fixed and working with your output. Let me know if you hit any problems!

Phil

**Comment by apeltzer** [comment]
Hi Phil,
I tested the newest version (1.5-dev0, installed 2018-02-09) and it doesn't pick these up. I'll attach the files I used that are produced by GATK MarkDuplicates directly (V 4.0.0.4) .


[test1.dup_metrics.txt](https://github.com/ewels/MultiQC/files/1711716/test1.dup_metrics.txt)
[test2.dup_metrics.txt](https://github.com/ewels/MultiQC/files/1711717/test2.dup_metrics.txt)
[test3.dup_metrics.txt](https://github.com/ewels/MultiQC/files/1711718/test3.dup_metrics.txt)

**Comment by ewels** [comment]
Try again with latest commit 9e7153fc0af807be55cabfffa8708fc22ee1f067 ;)

**Comment by apeltzer** [comment]
Works now with latest commit d6ba6c3fc704cf9bc3d0a577ec4101b65afdb7c3 !
