### ISSUE TITLE
Module tweak: bcl2fastq

### ISSUE THREAD

**Issue by matthdsm** [ewels/MultiQC#590]
Hi Phil,

would it be possible to add a little tweak to the bcl2fastq module?
In its current form, the "Clusters by Sample" graph looks like this:

<img width="906" alt="schermafbeelding 2017-09-18 om 11 21 04" src="https://user-images.githubusercontent.com/11850640/30535791-bfd124b6-9c63-11e7-9bfe-5061b0f14d02.png">

Would it be possible to add some colour coding by lane to the samples? Something like this would be awesome:
<img width="606" alt="schermafbeelding 2017-09-18 om 11 22 06" src="https://user-images.githubusercontent.com/11850640/30535829-dc0adb4a-9c63-11e7-934a-c80ade0b381f.png">

The graph above is generated by a bcl2fastq wrapper found [here](https://github.com/brwnj/bcl2fastq)

Thanks a lot!
Cheers
M

**Comment by matthdsm** [comment]
ping @iimog

**Comment by ewels** [comment]
Hi @matthdsm,

I agree, looks useful! Would this be a new plot then? Keep the one showing perfect / mismatch read counts, then have this one showing total counts coloured by lane? Otherwise I think having 16 categories is probably too much..

Phil

**Comment by matthdsm** [comment]
Hi Phil,

I was thinking along the lines of enhancing the existing plot, but a new one suits our needs just fine! Thanks for your enthousiasm!

Cheers
M

**Comment by ewels** [comment]
Great - perhaps have this as one of two tabs in the same plot (colour by lane or colour by proportion of perfect index).

**Comment by matthdsm** [comment]
sounds awesome!
Thanks a lot!
M

**Comment by ewels** [comment]
Hi @matthdsm,

I've just added this for you. Let me know how you get on with it!

Phil

**Comment by matthdsm** [comment]
Hi Phil,

Great! Much appreciated!
Cheers
M
