### ISSUE TITLE
Bcl2fastq read counts

### ISSUE THREAD

**Issue by vladsaveliev** [ewels/MultiQC#591]
@iimog, @ewels,

I wanted to bring one minor issue about the demultiplexing stats: the `NumberReads` metric (reported as `Total Reads` in general stats) in reality reflects the number of pairs. So when you see columns `Total Reads` coming from bcl2fastq, and next to it the alike columns `Total seqs` from samtools or `Total reads` from qualimap - it might be confusing why the numbers are twice different. I'm not confident if it's safe to rename the bcl2fastq's column to `Total pairs`, or alternatively multiply it by 2, - any ideas? Is it an issue at all or it's just me?

Vlad

**Comment by ewels** [comment]
How about `Total Clusters`? I don't like assuming that the data is paired-end, but using the terminology `clusters` should be generic to both yet specific enough in its meaning..

Could you also dump a quick screenshot showing the numbers mismatch to make sure that I understand what you mean?

Thanks,

Phil

**Comment by vladsaveliev** [comment]
Agree, assuming data is paired that was my concern too. The word clusters sounds perfect in this context 

Here is an example:
![screen shot 2017-09-20 at 18 00 50](https://user-images.githubusercontent.com/1575412/30651047-36fc0248-9e2d-11e7-97d0-6de77aa406c0.png)

As you can see `M Total Reads` from bcl2fastq has 39.7, and `M Total seqs` from samtools stats has twice as more 79.4. So renaming `M Total Reads` to `M Clusters` would be nice (skip the word `Total` to save some horizontal space).

**Comment by ewels** [comment]
Changed in #606
