### ISSUE TITLE
Add .align (TopHat) to default filename cleaning

### ISSUE THREAD

**Issue by zhaocheng3326** [ewels/MultiQC#594]
Is there a way to remove the ".align" from the tophat report ?
I tried the "-dd" parameters. It seems to make things worse.
Thanks

**Comment by ewels** [comment]
Yes, the documentation for how to do this is [here](http://multiqc.info/docs/#sample-name-cleaning).

I should look into making this the default for tophat though.

**Comment by zhaocheng3326** [comment]
Thanks for ewels's quick reply.

**Comment by ewels** [comment]
Hi @zhaocheng3326,

I've just added this to the defaults, so you shouldn't need the custom config with version 1.3 from now on. Let me know if it doesn't work as expected!

Phil
