### ISSUE TITLE
The bcl2fastq module breaks sometimes

### ISSUE THREAD

**Issue by escudem** [ewels/MultiQC#595]
Hi, I hope I will fill in the template properly, if you need any more information let me know. 

**Description of bug:**
The bcl2fastq module breaks sometimes

**MultiQC Error log:**
```
[ERROR  ]         multiqc : Oops! The 'bcl2fastq' MultiQC module broke... 
                    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
                    (if possible, include a log file that triggers the error) 
============================================================
Module bcl2fastq raised an exception: Traceback (most recent call last):
  File "/camp/stp/babs/working/software/binaries/Python-2.7.12-foss-2016b_packages/multiqc-1.2-2016b-Python-2.7.12/lib/python2.7/site-packages/multiqc-1.2-py2.7.egg/EGG-INFO/scripts/multiqc", line 411, in multiqc
    output = mod()
  File "/camp/stp/babs/working/software/binaries/Python-2.7.12-foss-2016b_packages/multiqc-1.2-2016b-Python-2.7.12/lib/python2.7/site-packages/multiqc-1.2-py2.7.egg/multiqc/modules/bcl2fastq/bcl2fastq.py", line 21, in __init__
    self.parse_file_as_json(myfile)
  File "/camp/stp/babs/working/software/binaries/Python-2.7.12-foss-2016b_packages/multiqc-1.2-2016b-Python-2.7.12/lib/python2.7/site-packages/multiqc-1.2-py2.7.egg/multiqc/modules/bcl2fastq/bcl2fastq.py", line 120, in parse_file_as_json
    for indexMetric in demuxResult["IndexMetrics"]:
KeyError: 'IndexMetrics'
============================================================
```

* **File that triggers the error:**
I had to change the extension from .json to .txt for GitHub to accept the file
    * [Stats.txt](https://github.com/ewels/MultiQC/files/1328695/Stats.txt)
* **Command used to run MultiQC**
    * `multiqc --config multiqc_config.yaml --outdir multiqc fastq fastqc`
* **MultiQC Version:**
    * 1.2
* **Operating System:**
    * CentOS 7.3
* **Python Version:**
    * Python 2.7.12
* **Method of MultiQC installation:**
    * Manual

**Comment by ewels** [comment]
Thanks for the detailed bug report @escudem! I'll try to take a look at this soon.

Phil

**Comment by ewels** [comment]
Interesting! Lanes 6 and 7 of your file don't have any demultiplexing IndexMetrics fields. I guess these didn't have demultiplexing done or something? I'll update the code to handle this missing data without crashing.

Having fixed that, what's now _really_ weird is that your file reports having more index matches than there are reads for each demultiplexed sample:

```json
 "ConversionResults" : [
  {
   "LaneNumber" : 1,
   "DemuxResults" : [
    {
     "SampleId" : "VM1_221015",
     "SampleName" : "VM1_221015",
     "IndexMetrics" : [
      {
       "IndexSequence" : "TAAGGCGA",
       "MismatchCounts" : {
        "0" : 108483274,
        "1" : 0
       }
      }
     ],
     "NumberReads" : 101079982,
```

`NumberReads` is less than the sum of `MismatchCounts`.. Any ideas how this could happen?

Any thoughts @iimog or @vladsaveliev?

Phil

**Comment by ewels** [comment]
Closing this issue now, but if anyone has any ideas about the counts weirdness above, please open a new issue 👍
