### ISSUE TITLE
Add support for SeqControl

### ISSUE THREAD

**Issue by brainstorm** [ewels/MultiQC#6]
Great initiative Phil!

I'm not going to work on this for now, but it would be interesting to integrate this byzantine mashup of R & Perl scripts in your mix:
 
http://labs.oicr.on.ca/Boutros-lab/software/SeqControl/

It generates fairly pretty QC plots and stuff ;)

**Comment by ewels** [comment]
Nice! I'd not heard of that one.. Looks like quite an interesting work flow to get it to do anything ;)

Could you point me in the direction of some typical output that I could use for testing? I download the sample files and there's a tonne of stuff in there. Specifically, are there any single number stats to go into the 'General Statistics' table at the top, then anything to plot in the main sections below?

(seeing an [example report](https://rawgit.com/ewels/MultiQC/master/tests/multiqc_report/multiqc_report.html) will make this make more sense).

**Comment by brainstorm** [comment]
I haven't had a very close look into it, so I don't have custom reports to show from our own data. And yes, the sample reports in the web are quite gigantic, with tons of log files that are quite tricky to navigate:

http://labs.oicr.on.ca/files/6993/file/preseq_testing.tar.gz

I tried to pack it up in a docker container so that one just calls it and outputs the resulting graphs and summary stats, but the amount of flags and extra files it needs is quite daunting and would need some dedication and care.

@ohofmann, @guillermo-carrasco

**Comment by ewels** [comment]
Closing until we have some example data / desire to write this module..
