### ISSUE TITLE
General Statistics - Scrolling Header

### ISSUE THREAD

**Issue by Edoardo-Petrini** [ewels/MultiQC#60]
Hi Phil,
just started using your tool, great stuff. I was wandering if it is possible to fix the header in the General Statistics section in a way that follows you while scrolling down the page, since it easy to get lost in the middle of the sample list and forget what is what. 
Thanks a lot and all the best!
Cheers

Edo

**Comment by ewels** [comment]
Hi Edoardo! Great that you're using MultiQC and finding it helpful..

So to confirm, you're talking about when you run MultiQC with loads of samples, and the general statistics table gets so long that it's taller than the page - you'd like the header to be frozen and follow the top of the window when scrolling  - but only whilst looking at the table, not when you _keep_ scrolling and go on to the plots... Is that right?

Seems like a good suggestion! I'll look into it..

Phil

**Comment by Edoardo-Petrini** [comment]
Hi Phil,

Yes you are absolutely correct, I think it might help to spot what is wrong (or good) about a particular dataset buried in the middle of the list.

Thanks a lot for the reply!

Hope is everything good in Sweden, have a nice day.

 

Edo

**Comment by ewels** [comment]
Ok, done in 202f5b693a0571ab42fe479da8203ff522f67478

Ended up being quite complicated - had to write my own solution from scratch as I couldn't get any plugins to do it for me. Seems to work quite nicely now though!

Cheers for the suggestion @Edoardo-Petrini - let me know if you have any problems with it!

Phil

**Comment by Edoardo-Petrini** [comment]
Wow that was fast. Thanks a lot, hope was not too much hassle, I just thought it could be nice to have it.

Cheers

 

Edo

**Comment by ewels** [comment]
No worries - I just told a colleague about it and he said that he'd had the same thought but hadn't got around to putting an issue in about it yet. So it was clearly a useful thing to have!
