### ISSUE TITLE
Not processing R2 on AfterQC output from paired-end samples

### ISSUE THREAD

**Issue by gk-bioin4m8x** [ewels/MultiQC#609]
Hi @ewels,

I used AfterQCv0.9.6 on 20 paired-end samples. Then, I ran: 
`multiqc -d --config $HOME/.local/bin/multiqc_config.yaml . `  on a folder named "AfterQC" with 20 sub-folders (named as AfterQC_sample1, AfterQC_sample2, etc.) each with the following files:

```
S1_R1_001.bad.fq
S1_R1_001.fastq.gz.html
S1_R1_001.fastq.gz.json
S1_R1_001.good.fq
S1_R2_001.bad.fq
S1_R2_001.good.fq
```
After running:

```
[INFO   ]         multiqc : This is MultiQC v1.3.dev0
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Prepending directory to sample names
[INFO   ]         multiqc : Searching '.'
Searching 120 files..  [####################################]  100%
[INFO   ]         afterqc : Found 20 reports
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : Plots       : multiqc_plots
[INFO   ]         multiqc : MultiQC complete](url)
```

The issue here is that multiqc_report.html shows for R1 from all 20 folders and nothing for R2.

Please guide.

Thanks.

**Comment by gk-bioin4m8x** [comment]
@ewels @[sfchen](https://github.com/sfchen)  I realized that it shows combined (R1+R2), but write R1 while displaying because the .json file name consists of R1 and not R2. Is there a way to write like that and/or to show R2 with R1 in the html.

**Comment by Hammarn** [comment]
Hi @gk-bioin4m8x !
Phil is away on vacation this week, so he might not respond.

I think this is covered quite extensively [here](http://multiqc.info/docs/#configuring-multiqc) in the documentation. Please have a readthrough of that section and come back if you are not able to figure it out. 
/Rickard

**Comment by ewels** [comment]
Closing this issue now - please reply if your problem is not resolved or you need more help!

Phil
