### ISSUE TITLE
HiSat 2 SE - wrong titel

### ISSUE THREAD

**Issue by Xentrics** [ewels/MultiQC#611]
**Description of bug:**
When I use Single-end logs of HiSat 2, the resulting plot shows "HiSat 2 PE" instead of "HiSat 2 SE". The legend is correct.
I use both, Single and Paired end in the same dataset, if that is an issue. I append the report.html and the corresponding hisat2 logs.

* **MultiQC log:**
    * [multiqc.log](https://github.com/ewels/MultiQC/files/1382328/multiqc.log)
* **Report:**
   * [multiqc_report.html.gz](https://github.com/ewels/MultiQC/files/1382343/multiqc_report.html.gz)
* **File that triggers the error:**
    * [Jigar_V_Desai_2013_GSE45141_GSM1097839_SRR772090.trimo.non_rrna.summary.txt](https://github.com/ewels/MultiQC/files/1382321/Jigar_V_Desai_2013_GSE45141_GSM1097839_SRR772090.trimo.non_rrna.summary.txt)
    * [Jigar_V_Desai_2013_GSE45141_GSM1097840_SRR772091.trimo.non_rrna.summary.txt](https://github.com/ewels/MultiQC/files/1382322/Jigar_V_Desai_2013_GSE45141_GSM1097840_SRR772091.trimo.non_rrna.summary.txt)
    * [Jigar_V_Desai_2013_GSE45141_GSM1097845_SRR772096.trimo.non_rrna.summary.txt](https://github.com/ewels/MultiQC/files/1382323/Jigar_V_Desai_2013_GSE45141_GSM1097845_SRR772096.trimo.non_rrna.summary.txt)
    * [Jigar_V_Desai_2013_GSE45141_GSM1097846_SRR772097.trimo.non_rrna.summary.txt](https://github.com/ewels/MultiQC/files/1382324/Jigar_V_Desai_2013_GSE45141_GSM1097846_SRR772097.trimo.non_rrna.summary.txt)
* **Command used to run MultiQC**
    *  'multiqc .'
* **MultiQC Version:**
    * MultiQC v1.1
* **Operating System:**
    * SUSE Linux Enterprise Server 11 (x86_64)
* **Python Version:**
    * Python 2.7
* **Method of MultiQC installation:**
    * pip

**Comment by ewels** [comment]
Thanks @Xentrics,

It looks like this error happens when there are both SE and PE data in the same report - when I use your log files it actually works fine as they're just SE. However, I can replicate the bug with other test data that I have.

Phil

**Comment by ewels** [comment]
Ok, I think I found and fixed the bug - it seems to work for me now. If you could grab the latest v1.3dev version and give it a try to confirm then that would be great!

Phil

**Comment by Xentrics** [comment]
Works like a charm, thank you very much :).
