### ISSUE TITLE
Trim Galore Read Names Contain _val_1 and _val_2 in Report

### ISSUE THREAD

**Issue by anfederico** [ewels/MultiQC#626]
When MultiQC parses the following directory, is there anyway for it to ignore the `_val_{1,2}` in the sample name? Here is what the output directory looks like:

```
/trimgalore
- ggal_alpha_1.fq.gz_trimming_report.txt
- ggal_alpha_2.fq.gz_trimming_report.txt
- ggal_alpha_1_val_1.fq.gz
- ggal_alpha_2_val_2.fq.gz
```

In the trimming reports, the reads are not referred to as `ggal_alpha_1_val_1` for example, so is MultiQC naming the samples in the multiqc report from the name of the `.fq.gz` files themselves? Rather than the names used within the trimgalore report?

This results in the following multiqc report
https://ibb.co/nyJzyG

Issue occurs on both Mac (Sierra 10.12) and Linux (Ubuntu 16.04)

**Comment by ewels** [comment]
Hi @anfederico,

Absolutely - MultiQC has a range of options for cleaning up sample names, see http://multiqc.info/docs/#sample-name-cleaning

Note that adding `_val_1` and `_val_2` will mean that the two trimmed files share sample names and one overwrites the other. This can be done randomly. Perhaps better is to make MultiQC ignore the `_val_2` stats and trim `_val_1`. You should be able to do this with something like the following config snippet:

```yaml
extra_fn_clean_exts:
    - '_val_1'
sample_names_ignore_re:
    - '_val_2$'
```

I hope that makes sense! Note that I'm hoping to introduce new functionality to specifically handle the case of read pairs and trimmed / untrimmed pairs, but it's not ready yet. See #576 and #542 

Let me know if you need any help!

Phil

**Comment by anfederico** [comment]
Beautiful! Thank you Phil.
