### ISSUE TITLE
Axes in Picard HsPenalty plot

### ISSUE THREAD

**Issue by puva** [ewels/MultiQC#629]
Hi Phil,
Thanks for this great tool!!

**Axes in Picard HsPenalty plot**
The y-axis label should be 'Penalty' instead of 'Pct of bases'
The x-axis values are a tenth of the HS fold: 1X correspond to 'HS_PENALTY_10X', 2X to 'HS_PENALTY_20X' 

* **Command used to run MultiQC**
    * `multiqc -m picard .`
* **MultiQC Version:**
    * MultiQC v1.2
* **Operating System:**
    * CentOS 7 
* **Python Version:**
    * Python 2.7.14
* **Method of MultiQC installation:**
    * conda

**Comment by ewels** [comment]
Hi @puva,

Many thanks for the report - good spot! Should be an easy fix.

Phil

**Comment by ewels** [comment]
Hi @puva,

I've just been looking into these changes, but it looks like all of the [test data](https://github.com/ewels/MultiQC_TestData/tree/master/data/modules/picard/HsMetrics) that I have for this module has zero penalty scores, and this plot is skipped. Do you have an example file that I could use to check my changes please?

Cheers,

Phil

**Comment by ewels** [comment]
Hi @puva,

I've just pushed some changes which I hope fix the problem. If you could try the development version of the code and confirm that the plot now looks as expected that would be great!

Thanks,

Phil

**Comment by puva** [comment]
Hi Phil,
I tried the dev version:
- y-axis is OK
- values are OK, excepted for -1 value that should not be drawn.

Attached a test data with non-zero penalty scores.
[hs_metrics.txt](https://github.com/ewels/MultiQC/files/1506007/hs_metrics.txt)

Thanks,
Paolo

**Comment by ewels** [comment]
ah ok thanks, I added the -1s back in as I didn't see why they should be ignored. I'll put that back to how it was then. Thanks for the quick response with test data!

Phil

**Comment by ewels** [comment]
Hi @puva,

Changes applied - let me know if there's anything else that needs tweaks.

Cheers,

Phil
