### ISSUE TITLE
picards InsertSizeMetrics raises error

### ISSUE THREAD

**Issue by finswimmer** [ewels/MultiQC#630]
Hello,
I use multiqc 1.3 and try to run it on reports produced by picards InsertSizeMetrics (Version: 2.14.0-SNAPSHOT).

This results in this message:
```
[ERROR  ]         multiqc : Oops! The 'picard' MultiQC module broke... 
                    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
                    (if possible, include a log file that triggers the error) 
============================================================
Module picard raised an exception: Traceback (most recent call last):
  File "/usr/local/bin/multiqc", line 412, in multiqc
    output = mod()
  File "/usr/local/lib/python3.5/dist-packages/multiqc/modules/picard/picard.py", line 64, in __init__
    n['InsertSizeMetrics'] = InsertSizeMetrics.parse_reports(self)
  File "/usr/local/lib/python3.5/dist-packages/multiqc/modules/picard/InsertSizeMetrics.py", line 76, in parse_reports
    self.picard_insertSize_samplestats[s_name]['meansum'] += (rp * mis)
TypeError: can't multiply sequence by non-int of type 'float'
============================================================

```

* **Command used to run MultiQC**
    * `multiqc .`
* **MultiQC Version:**
    * MultiQC v1.3
* **Operating System:**
    * Ubuntu 17.10
* **Python Version:**
    * Python 3.5
* **Method of MultiQC installation:**
    * pip

fin swimmer

**Comment by ewels** [comment]
Hi @finswimmer,

Are you able to attach the file that generates this error so that I can replicate the error please?

Phil

**Comment by finswimmer** [comment]
Hi @ewels ,

thank you for your quick reply. Here you have one file to test.

fin swimmer

[Test-Sample.insert_size_metrics.txt](https://github.com/ewels/MultiQC/files/1516769/Test-Sample.insert_size_metrics.txt)

**Comment by ewels** [comment]
Hi @finswimmer,

It's another case of Picard using internationalised formatting for numeric fields and putting in a comma instead of a decimal place. These are almost impossible to resolve (how does MultiQC know what `306,378678` should mean?), but I'll try to add some logic to handle it.

Phil

**Comment by ewels** [comment]
Ok, I've just switched commas for points if MultiQC can't parse the number. This should fix it for you. Hopefully Picard never separates thousands with commas!

**Comment by finswimmer** [comment]
Thanks, works perfect.

fin swimmer
