### ISSUE TITLE
MACS2 reports

### ISSUE THREAD

**Issue by avilella** [ewels/MultiQC#632]
I run MultiQC on a set of folder containing gzipped versions of the MACS2 xls files, but I can't see the values reported or a `multiqc_macs2.txt` file. Is it supposed to work on `xls.gz` files?

* **Command used to run MultiQC**
    * `multiqc .`
* **MultiQC Version:**
 head master as of Thu 30 Nov 2017
* **Operating System:**
Ubuntu 14.04 in DNAnexus instance
* **Python Version:**
default in Ubuntu 14.04
* **Method of MultiQC installation:**
pip from github head master

**Comment by ewels** [comment]
Hi @avilella,

No, MultiQC ignores compressed files generally - it's too computationally expensive to uncompress them during the file searches. There are some exceptions: the FastQC module works with `.zip` files as they're standard, and we could add in gzip support for MACS2 as MultiQC finds those files based on filename instead of file contents. But I didn't think that MACS2 creates gzipped files by default? Am I wrong?

Phil

**Comment by avilella** [comment]
Not by default, but I keep them on DNAnexus compressed for smaller
footprint. I'll decompress before kicking off MultiQC and see if I get the
report.

A.

**Comment by ewels** [comment]
Sounds good 👍  Note that MultiQC looks for MACS files with a filename ending `_peaks.xls`

**Comment by avilella** [comment]
Ok, still doesn't find it even when unzipped, maybe due to a version mismatch. I will check the parsing code and the input files I have.

**Comment by ewels** [comment]
Ok - you can see the example data that we wrote the module around here: https://github.com/ewels/MultiQC_TestData/blob/master/data/modules/macs2/macs2_output_peaks.xls

Note that the filenames have to match `*_peaks.xls` and have the `#` header lines at the top of the file.

**Comment by ewels** [comment]
Closing for now - let me know if you think that there's a problem in the MultiQC code.. 👍

**Comment by avilella** [comment]
This is what I tried now locally on an Ubuntu 14.04:

```
sudo pip install git+https://github.com/ewels/MultiQC.git
[...]
avilella@avilellaM710t:/tmp$ mkdir -p /tmp/test
avilella@avilellaM710t:/tmp$ cd /tmp/test
avilella@avilellaM710t:/tmp/test$ ls -l
total 0
avilella@avilellaM710t:/tmp/test$ wget -b https://github.com/ewels/MultiQC_TestData/blob/master/data/modules/macs2/macs2_output_peaks.xls
Continuing in background, pid 22185.
Output will be written to ‘wget-log’.
avilella@avilellaM710t:/tmp/test$ sleep 10 && md5sum macs2_output_peaks.xls 
a48a103cac82d750d5bfd5808cc27fc6  macs2_output_peaks.xls
avilella@avilellaM710t:/tmp/test$ multiqc --version
multiqc, version 1.4dev
avilella@avilellaM710t:/tmp/test$ multiqc --force .
[INFO   ]         multiqc : This is MultiQC v1.4dev
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
Searching 2 files..  [####################################]  100%
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
```

**Comment by avilella** [comment]
It may be due to file size:

```
find $PWD/ -name "*.xls"
/home/avilella/CEGX_Run485/CEGX_Run485-12345678/CEG74_82_4PC-67082021/CEG74-82-4PC_S6_L00.bml.GRCh38.karyo.deduplicated.c.CEG74-78-4IP_S7_L00.bml.GRCh38.karyo.deduplicated.macs2_peaks.xls
avilella@avilellaM710t:~/CEGX_Run485$ multiqc --force .                                                                                                                                                                                                                      
[INFO   ]         multiqc : This is MultiQC v1.4dev
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
Searching 6 files..  [####################################]  100%
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
avilella@avilellaM710t:~/CEGX_Run485$ find $PWD/ -name "*.xls" | while read i; do head -n 29 $i > ${RANDOM}_peaks.xls; done
avilella@avilellaM710t:~/CEGX_Run485$ multiqc --force .
[INFO   ]         multiqc : This is MultiQC v1.4dev
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
Searching 7 files..  [####################################]  100%
[INFO   ]           macs2 : Found 1 logs
[WARNING]        bargraph : Tried to make bar plot, but had no data
[INFO   ]         multiqc : Compressing plot data
[WARNING]         multiqc : Deleting    : multiqc_report.html   (-f was specified)
[WARNING]         multiqc : Deleting    : multiqc_data   (-f was specified)
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete
```

**Comment by ewels** [comment]
The file you `wget` above is HTML and not the raw file. You want this instead:

```
wget https://raw.githubusercontent.com/ewels/MultiQC_TestData/master/data/modules/macs2/macs2_output_peaks.xls
```

**Comment by ewels** [comment]
```
$ wget https://raw.githubusercontent.com/ewels/MultiQC_TestData/master/data/modules/macs2/macs2_output_peaks.xls

$ md5 macs2_output_peaks.xls
MD5 (macs2_output_peaks.xls) = ceb2ec75584e7831f2e0a78708c0a30e

$ multiqc .
[INFO   ]         multiqc : This is MultiQC v1.4.dev0 (e757560)
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
Searching 1 files..  [####################################]  100%
[INFO   ]           macs2 : Found 1 logs
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete
```

**Comment by ewels** [comment]
...and yes, it could well be ignoring your files if they're big. See http://multiqc.info/docs/#big-log-files

Phil

**Comment by avilella** [comment]
More details:

Changing the log size limit to 9876543210, then it picks up the original file, but it won't plot anything. Is it supposed to have specific 4th column names to do any plotting?

```
Error - was not able to plot data.
```

**Comment by avilella** [comment]
Aha! Found it, I think: older versions of MACS2 use 'tags' instead of 'fragments' in the header.

**Comment by avilella** [comment]
Added modification and pull request now.

**Comment by ewels** [comment]
Ok, great spot - thanks! If you could submit a truncated example to the test data directory too that would be great...

**Comment by bharatij** [comment]
Hi,
I was using multiqc 1.3 and had a similar issue with MACS2 xls files.  It does not recognize the .xls files and gives **warning multiqc : No analysis results found. Cleaning up..**
Therefore, I upgraded multiqc to MultiQC v1.5dev. I still does not recognize the *_peaks.xls. 

I checked the .xls files and they do have 'tags' instead of 'fragments' in the header. Do I have to specifically use multiqc 1.4 version to overcome with this issue?

Thanks,
Bharati

**Comment by ewels** [comment]
Hi @bharatij,

The MultiQC code should recognise either `tags` or `fragments`:

https://github.com/ewels/MultiQC/blob/6ce7cc301cd97add6c28137a633ed07981d0b358/multiqc/modules/macs2/macs2.py#L47-L54

So it should work fine with v1.5dev. There must be something else going on with your files - are you able to attach one to this issue so that I can take a look?

Phil

**Comment by bharatij** [comment]
Hi Phil,
Thanks for confirming. Please see the attached sample file. This is a
truncated version of the original file but does have the headers as is.
Thanks,
Bharati

**Comment by ewels** [comment]
Thanks @bharatij - I guess you attached to an email? I think you have to drag and drop onto the GitHub issue webpage to attach a file.
