### ISSUE TITLE
CollectHsMetric files not found

### ISSUE THREAD

**Issue by finswimmer** [ewels/MultiQC#636]
Hello,
on my installation multiqc did not find reports by CollectHsMetrics. Am I missing something?

* **Command used to run MultiQC**
    * `multiqc .`
* **MultiQC Version:**
    * multiqc, version 1.4.dev0
* **Operating System:**
    * Ubuntu 17.10
* **Python Version:**
    * python 3.5
* **Method of MultiQC installation:**
    * pip (git)

[TestSample.HsMetrics.txt](https://github.com/ewels/MultiQC/files/1534983/TestSample.HsMetrics.txt)

fin swimmer

**Comment by ewels** [comment]
Hi @finswimmer,

I'm not sure why MultiQC doesn't pick your file up (I tried it quickly and it isn't found for me either). I'll take a look into this when I get a chance.

Phil

**Comment by ewels** [comment]
Hi @finswimmer,

I had a closer look and figured it out - Picard can put a range of different strings into its output and your file had a new variant in that I'd not seen before. I made the string matching a little less strict and it seems to work now.

Let me know if you hit any more problems!

Cheers,

Phil
