### ISSUE TITLE
How multiqc parse qualimap coverage information?

### ISSUE THREAD

**Issue by likelet** [ewels/MultiQC#640]
Hi ewels
 I am wondering how multiqc parse coverage information from qualimap result . 
I check both coverage figures and found it is different. 
In qualimap result `genome_results.txt`  there are two lines 
 mean coverageData = 142.59X
     std coverageData = 247.3603X
and in multiqc report, the coverage of this sample is 83X?

[genome_results.txt](https://github.com/ewels/MultiQC/files/1548030/genome_results.txt)
[multiqc_report.html.zip](https://github.com/ewels/MultiQC/files/1548031/multiqc_report.html.zip)
The sample is `548068_1E_1_stats`
thanks

**Comment by ewels** [comment]
Hi @likelet,

The coverage in the General Statistics table is the median coverage, calculated from the coverage histogram. This is why it's different from the mean value you saw.

On a side note - I'd recommend updating MultiQC if it's possible. There have been a few changes and bugfixes in the Qualimap module and core code since the v1.0 release.

Cheers,

Phil

**Comment by rjsicko** [comment]
Hi @ewels,

First, thanks for all your work on MultiQC - such a great tool!

Just curious why you chose to display median coverage vs mean coverage? Do you find median a more reliable/useful metric when looking at sample performance? Also, is there anyway to get MultiQC to also display QualiMap's mean coverage calculation?

Thanks,
Bob

**Comment by likelet** [comment]
hi @rjsicko, i think there is a reason that the median coverage should be more representative than mean coverage, as the median can be less influenced by samples with  extremely high or low coverage.

**Comment by rjsicko** [comment]
Hi @likelet,
Thanks for the reply. In this case, the QualiMap and MultiQC results are per sample right? So regions of very high or low coverage could make median more meaningful. If all samples in a run use the same targeted region, I wonder if mean or median is more meaningful for sample level QC

**Comment by likelet** [comment]
Yes, i ignored this. Sorry. But it may be  the same case for a single sample (outlier regions like you said). If your are going to target the same region in all samples and compare samples' coverage, there is no big difference between median and the mean for identifying bad samples from the good ones . However, median can help you to get a more reasonable coverage range of all samples in stead of mean, smaller sd, e.g.  Hope it helps.

**Comment by rjsicko** [comment]
yes, that is helpful. thanks!

**Comment by ewels** [comment]
Thanks both! 😁
