### ISSUE TITLE
Bcftools: variant quality plot

### ISSUE THREAD

**Issue by amilesj** [ewels/MultiQC#641]
It would useful to add a line plot of Variant Qualities, just like the one in the Whole-Genome Seq example on the MultiQC homepage, that plots SNP quantity as a function of quality score except using data from bcftools stats.

In the attached output file from bcftools stats, the relevant data starts on line 27 and is in the 3rd and 4th columns: [snps_vcf_stats.txt](https://github.com/ewels/MultiQC/files/1554298/snps_vcf_stats.txt)

**Comment by MaxUlysse** [comment]
I'm working on it

**Comment by ewels** [comment]
Hi @amilesj,

If you have any feedback on the new plot that would be great!

Phil

**Comment by amilesj** [comment]
Whoops, this message totally fell through the cracks. Better late than never? The plot looks great! Thanks for implementing this.

**Comment by ewels** [comment]
I have no memory of what this was 😆 But great that you're happy with it! 🎉

**Comment by MaxUlysse** [comment]
I do remember, it was our first collaboration with @Rotholandus
