### ISSUE TITLE
fastQC copy table and export plot data does not work

### ISSUE THREAD

**Issue by thkitapci** [ewels/MultiQC#645]
**Description of bug:**
I run multiQC on 24 fastQC reports. Everything works fine but when I click on the "copy table" to copy the main statistics for each fastq nothing happens. I can't paste the table in any other document. Also if I click on export plot and try to download the plot data for overrepresented sequences I get all fields "undefined" 

* **Command used to run MultiQC**
    * `multiqc --fullnames .`
* **MultiQC Version:**
    * multiqc, version 1.0.dev0 
* **Operating System:**
    * Linux
* **Python Version:**
    * Python 2.7.12
* **Method of MultiQC installation:**
    * conda install -c bioconda multiqc

Thanks!
Hamdi

**Comment by ewels** [comment]
Hi @thkitapci,

Version 1.0.dev0 of MultiQC is really quite old - could you please try again with the latest version (v1.3 or v1.4dev) and see if you get the same problem? If it still happens then I'll investigate (please attach a report to the issue if that's the case).

Thanks,

Phil

**Comment by ewels** [comment]
Hi @thkitapci,

I'm closing this issue now as it was an old version of MultiQC and I can't replicate the problem (the copy function works fine for me). Let me know if you have the same error with recent reports, eg. http://multiqc.info/examples/rna-seq/multiqc_report.html and I can reopen this issue and look into it for you.

Cheers,

Phil
