### ISSUE TITLE
Automatic colouring based on given threshold 

### ISSUE THREAD

**Issue by RoxaneLS** [ewels/MultiQC#647]
Hi Phil,
second feature request, related:

Similar question applies to other pre-made tables, such as from the fastqc module or other, can I give multiqc a threshold from which to colour in red some values? (e.g. %GC < 30% for instance)
Ideally we could do that from either the pre-made tables from various modules or from custom tables.

Your reply in Gitter: 
Second one is harder and requires me to write something for you.
Again, shouldn’t be too difficult though I think. Need to think about how to do the display though.
Maybe make another separate new issue for that one?

**Comment by ewels** [comment]
Related to #646
