### ISSUE TITLE
peddy module - het_check plot

### ISSUE THREAD

**Issue by aledj2** [ewels/MultiQC#650]
Hi Phil,

I'm looking to include a different output of peddy in the MultiQC report (the equivalent of the `het_check.png`) as this will show possible sample contamination.

Looking at the peddy module,I have written a new function which plots this (`x=median_depth`, `y=het_ratio`), based on the functions which create the other plots, however I think there's an issue with the way the data is read from the peddy files.

There are three csv files that peddy produces, and MultiQC reads. From what I can tell these are imported into the `self.peddy_data` dictionary, with the sample name as a key and then all the values from these files added to a sample specific dictionary.

The issue is that two of the peddy files have columns with the same name (but different values) so if trying to plot eg het_ratio from het_check, the value plotted is the het_ratio from the sex_check (sex_check is parsed after het_check).
 
I have got around this by emptying `self.peddy_data` and re-populating it just with the het_check file but I don't think this is ideal! 

If I get a chance I'll try and make something which prefixes the input file to the dictionary value name to make sure the correct values are plotted.

If I were to do this, and add in an extra function for the het_check plot do i need to create an anchor or something for the plot or add in an option to the config file?

I've attached what I've done so far, but this also includes removing the other plots and columns from the general statistics table.
[peddy.py.gz](https://github.com/ewels/MultiQC/files/1601291/peddy.py.gz)

Thanks!

**Comment by ewels** [comment]
Hi @aledj2,

Many thanks for this and your pull request. Looking at your PR it seems that you've answered most of the questions that you had here (it looks great!), so I'll close this issue for now. If there's something I've missed, please raise it as a comment on the PR and we can continue the discussion there.

Cheers,

Phil
