### ISSUE TITLE
Section collision in General Statistics

### ISSUE THREAD

**Issue by maressyl** [ewels/MultiQC#654]
Hej Phil,

Following up with the problem raised on Gitter, here are two example file sets triggering the problem on both versions 1.2 and 1.3 (as installed on Uppmax). Considering the local version used to produce the example I attach here, I'm operating on Ubuntu 4.4.0-104-generic 64 bits, with python 2.7.12, I can't figure out how I installed MultiQC though (using `pip` most likely). I may have just missed something in the documentation, if so any help to figure this out would be much appreciated.

[Here](https://github.com/ewels/MultiQC/files/1614399/mqc_same_group.zip) everything works as expected, except that in the "General Statistics" table clicking "Configure Columns" my two custom datasets are in the group "Secondary_section" despite both have distinct section ids in their respective configuration files. They have different colors as expected though. I could not figure out how this ID is chosen, to set it to clean and distinct values myself.

[Here](https://github.com/ewels/MultiQC/files/1614408/mqc_error.zip) I get the following error :

```
[WARNING]         multiqc : MultiQC Version v1.3 now available!
[INFO   ]         multiqc : This is MultiQC v1.2
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
Searching 12 files..  [####################################]  100%
[ERROR  ]         multiqc : Oops! The 'custom_content' MultiQC module broke...
                    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues
                    (if possible, include a log file that triggers the error)
============================================================
Module custom_content raised an exception: Traceback (most recent call last):
  File "/home/sylvain/.local/bin/multiqc", line 420, in multiqc
    for to, path in report.modules_output[-1].css.items():
IndexError: list index out of range
============================================================
[INFO   ]          picard : Found 3 RnaSeqMetrics reports
[INFO   ]            star : Found 3 reports
[INFO   ]         multiqc : Compressing plot data
[WARNING]         multiqc : Deleting    : multiqc_report.html   (-f was specified)
[WARNING]         multiqc : Deleting    : multiqc_data   (-f was specified)
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete
```

My first idea was to put extra General Stats only, but as I could not solve this error I generated section files as well. If there is a way to achieve that it could save me some pain in the future though, some of the statistics I want to add are very simple and don't deserve a whole section or a plot.

Thanks anyway for this very nice piece of software !

Best,
Sylvain

**Comment by ewels** [comment]
Ok, one problem at a time. First problem:

> _my two custom datasets are in the group "Secondary_section" despite both have distinct section ids in their respective configuration files._

Yup, I don't think this is documented anywhere and I had to dig into the code to figure out how to do this myself. It's the `namespace` key that you're looking for:

`CPM_KD.yaml`
```yaml
custom_data:
    KD_genes_stats:
        plot_type: 'generalstats'
        pconfig:
            - N:
                namespace: 'CPM_KD'
                description: 'Original sample ordering'
            - lib.size:
                namespace: 'CPM_KD'
                description: 'Total counts (reads non-ambigously assigned to a transcript)'
```

`samtools.yaml`
```yaml
custom_data:
    Secondary_stats:
        plot_type: 'generalstats'
        pconfig:
            - Secondary:
                namespace: 'Samtools stuff'
```

Solved I think, though I should probably document this somewhere. It is [already mentioned](http://multiqc.info/docs/#creating-a-table) but it's not very clear that this is used in the configure columns modal.

**Comment by maressyl** [comment]
Thanks a lot, it works indeed. Actually I tried a few things with `namespace` but I gave up reading that "It's automatically generated for the General Statistics table." [here](http://multiqc.info/docs/#step-3-adding-to-the-general-statistics-table) in the documentation.

**Comment by ewels** [comment]
Yes that's not at all clear sorry, I've just edited this a little to clarify, will push in a minute. Looking at your second error now, but about to go into a meeting.

**Comment by ewels** [comment]
Ok, the second error is an edge case I'd not encountered before where if custom content parsed only General Stats columns and no module data, it returned an empty list which triggered the error you saw. I've added a clause which catches this case and avoids the traceback.

I don't think that the traceback actually affects the report output at all, but it will now be avoided anyway.

**Comment by ewels** [comment]
Thanks for the detailed error report - let me know if you find any other weird stuff going on.

It's great to see you doing so much with Custom Content. I'm aware that the documentation especially is a bit lacking at the moment. If you fancy improving the docs at all, or writing a blog post about what you've done, or any other ideas, it would be really appreciated. Let me know!

Cheers,

Phil

**Comment by maressyl** [comment]
Thanks for this quick solving. You are right the report doesn't look so bad, I must confess I didn't bother to check when I saw the error message.

I like the way MultiQC collects everything in the same neatly formatted and filterable report, and this custom content feature has great potential. I'll consider writing something about that when I'll be a bit more familiar with the system, the documentation may indeed be a bit discouraging to newcomers as it covers a lot of related things (many formats of custom contents, developping new modules and so on).

Great job anyway !

Best,
Sylvain
