### ISSUE TITLE
Number format ignored with 'scale: False'

### ISSUE THREAD

**Issue by maressyl** [ewels/MultiQC#656]
Hi again,

Here is another minor problem I encountered with both versions 1.2 and 1.3 (as installed on Uppmax). Considering the local version used to produce the example I attach here, I'm operating on Ubuntu 4.4.0-104-generic 64 bits, with python 2.7.12, I can't figure out how I installed MultiQC though (using pip most likely).

I wanted to insert a custom ordering integer as part of my custom table section, for which a color scale doesn't make much sense. If I set `format: '{:,.0f}'` with `scale: 'Greys'` I get clean integers and the color scale, but with `scale: False` I indeed get no color but it seems that the format option is ignored as well. [Here](https://github.com/ewels/MultiQC/files/1614428/mqc_scale.zip) is an example.

Best,
Sylvain

**Comment by ewels** [comment]
Hi @maressyl,

Your example report was generated with v1.2 of MultiQC. I just ran it myself (thanks for the v. complete example zip) with the latest dev version and it worked as expected. So it's presumably been fixed at some point since v1.2.

Let me know if you run into any trouble with the latest version.

Phil

**Comment by maressyl** [comment]
Indeed I no longer have the problem with the devel version, I guess I will just have to wait for the 1.4 to arrive on Uppmax. Thanks !

**Comment by ewels** [comment]
No problem! Note that it's entirely possible to install the dev version on Uppmax yourself if you want (this is what I do). Though obviously not ideal for reproducibility etc.
