### ISSUE TITLE
Add report from Fastqc?

### ISSUE THREAD

**Issue by scholzmb** [ewels/MultiQC#660]
Hello,

I'm wondering if it would be possible to include the read counts field as a simple bar-chart as output from the parsing of FastQC (or a histogram).  I have found myself having to generate this several times recently.

Thank you,

**Comment by ewels** [comment]
Hi @scholzmb,

Yes, this would certainly be possible (and pretty easy). I'm always a fraction hesitant at changing the FastQC as it's used by so many people, but this sounds useful. I could add some other numbers as tabs above this plot too - eg. % Duplicates etc. I'll look into it.

Phil

**Comment by ewels** [comment]
Hi @scholzmb,

Sorry that this has taken a while. I've just added the new plot which show the total number of reads. This is broken down into unique and duplicate if that info was in the FastQC report (should be for all relatively recent versions).

I hope this is useful! Let me know how you get on with it.

Cheers,

Phil
