### ISSUE TITLE
MultiQC 1.3 breaks upon encountering homer output

### ISSUE THREAD

**Issue by zsteve** [ewels/MultiQC#666]
Bug: Running MultiQC on Homer tags directory (generated using `makeTagDirectory`) causes MultiQC to break.

I am aware the current release is 1.4, but the latest installed version on server is 1.3. Have tried to install 1.4 but it's a bit tricky for the time being. I've checked the CHANGELOG.md for version 1.3 -> 1.4 and there don't seem to be changes related to `homer` output. Correct me if I'm wrong and this has been addressed in version 1.4 :smile: 

**MultiQC Error log:**
```
szha0069@biomate1:~/test_seq_files/analysis/tags$ multiqc .
[WARNING]         multiqc : MultiQC Version v1.4 now available!
[INFO   ]         multiqc : This is MultiQC v1.3
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
Searching 33 files..  [####################################]  100%             
[ERROR  ]         multiqc : Oops! The 'homer' MultiQC module broke... 
                    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
                    (if possible, include a log file that triggers the error) 
============================================================
Module homer raised an exception: Traceback (most recent call last):
  File "/mnt/software/apps/multiqc-1.3/bin/multiqc", line 412, in multiqc
    output = mod()
  File "/mnt/software/apps/multiqc-1.3/lib/python3.5/site-packages/multiqc/modules/homer/homer.py", line 60, in __init__
    n['Homer_tagDir'] = self.homer_tagdirectory()
  File "/mnt/software/apps/multiqc-1.3/lib/python3.5/site-packages/multiqc/modules/homer/tagdirectory.py", line 24, in homer_tagdirectory
    self.parse_tagInfo_data()
  File "/mnt/software/apps/multiqc-1.3/lib/python3.5/site-packages/multiqc/modules/homer/tagdirectory.py", line 142, in parse_tagInfo_data
    parsed_data = self.parse_tag_info(f)
  File "/mnt/software/apps/multiqc-1.3/lib/python3.5/site-packages/multiqc/modules/homer/tagdirectory.py", line 349, in parse_tag_info
    tag_info['gsizeEstimate'] = float(s[0].strip().split("=")[1])
IndexError: list index out of range
============================================================
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete

```

* **File that triggers the error:**
Example using `head -n 10 genomeGCcontent.txt`:
```
GC%	Total	Normalized Fraction(PDF)
0.000	1675778.0	0.135020
0.009	762438.0	0.061431
0.019	502064.0	0.040452
0.028	607705.0	0.048964
0.037	729976.0	0.058815
0.046	860418.0	0.069325
0.056	1003187.0	0.080828
0.065	1141125.0	0.091942
0.074	1281986.0	0.103291

```
* **Command used to run MultiQC**
     `multiqc .`
* **MultiQC Version:**
MultiQC 1.3
* **Operating System:**
Ubuntu 16.04.3 LTS
* **Python Version:**
Python 2.7.12

**Comment by ewels** [comment]
Hi @zsteve,

I can't see a corresponding file in the test data that I have for Homer: https://github.com/ewels/MultiQC_TestData/tree/master/data/modules/homer

Is it possible for you to get an example file from the previous version of Homer as well as this one? Also, please upload as a file rather than pasting into the issue, to preserve proper whitespace.

Thanks,

Phil

**Comment by zsteve** [comment]
These were the specific files generated from running `makeTagDirectory`
[tag_files.tar.gz](https://github.com/ewels/MultiQC/files/1675796/tag_files.tar.gz)

**Comment by ewels** [comment]
Hi @zsteve,

I think this is fixed now. It wasn't the `genomeGCcontent.txt` file, but rather `tagInfo.txt` - this was in the tar file you sent though so that was fine, thanks! I've refactored the code to be more flexible and able to handle the output formats from both versions of Homer.

Let me know if you run into any problems!

Phil
