### ISSUE TITLE
feature request: methylQA module

### ISSUE THREAD

**Issue by avilella** [ewels/MultiQC#67]
Copy+pasting a methylQA .report file below (attachment did not work).

```
files provided: 1
  /foo/bar/ABC37-26-1_S13_L001_R1_001.cutB_pe.sorted.bam

uniquely mappable reads (pair): 21396
quality failed mapped reads (pair) in the bismark bam: 0
oversized mapped reads (pair) in the bismark bam: 0
total base of uniquely mapped reads (pair): 1535018
total base of uniquely mapped reads (pair) cover genome base (3088286401): 0.0X

in all uniquely mapped reads (pair), found:
    number of methylated C in CHG context (was protected): 93
    number of not methylated C in CHG context (was converted): 60583
        C->T convertion rate in CHG context: 99.85%
    number of methylated C in CHH context (was protected): 337
    number of not methylated C in CHH context (was converted): 212821
        C->T convertion rate in CHH context: 99.84%
    number of methylated C in CpG context (was protected): 6056
    number of not methylated C in CpG context (was converted): 6481
        C->T convertion rate in CpG context: 51.69%
    number of methylated C in Unknown context (was protected): 0
    number of not methylated C in Unknown context (was converted): 1
        C->T convertion rate in Unknown context: 100.00%

in the total 29401362 CpG:
  Times covered	          Count	   Percent	|
              0	       29388871	     99.96	|***************************************************************************************************
              1	          12448	      0.04	|
              2	             40	      0.00	|
              3	              3	      0.00	|
              4	              0	      0.00	|
              5	              0	      0.00	|
              6	              0	      0.00	|
              7	              0	      0.00	|
              8	              0	      0.00	|
              9	              0	      0.00	|
             10	              0	      0.00	|
          11-20	              0	      0.00	|
          21-30	              0	      0.00	|
          31-40	              0	      0.00	|
          41-50	              0	      0.00	|
         51-100	              0	      0.00	|
        101-200	              0	      0.00	|
        201-300	              0	      0.00	|
           >300	              0	      0.00	|
```

**Comment by ewels** [comment]
Nice, thanks @avilella! Writing these kinds of software really makes you appreciate a good log output - this one is really nice (includes input filename in log output, easy to parse..)

**Comment by avilella** [comment]
Bump!

To make it easy for people to run methylQA, a bed file with hg38 cpgs is needed, and a tabular file with chromosome sizes is also needed. We have a copy of each here:

https://bitbucket.org/cegx-bfx/data/get/74f7b8a61d11.zip

Just to mention that I have my own fork of the original methylqa which fixes a segfault on the original:
https://github.com/lidaof/methylQA
Here:
https://github.com/avilella/methylQA

I just PRed it now, the author is in the US, so he may reply this afternoon about it.

**Comment by ewels** [comment]
Hi @avilella,

The bed file stuff is useful - was it easy to make? Any chance of a hg37 version? :wink: 

Phil

**Comment by avilella** [comment]
I don't have one for hg37, but I do for hg38 and mm10:

https://bitbucket.org/cegx-bfx/data/downloads

I asked the author to incorporate the code for the creation of the file
into the methylqa code:

https://github.com/lidaof/methylQA/issues/4

Maybe a +1 would help?

**Comment by ewels** [comment]
Hi @avilella - try giving this a shot! Seems to be working for me now with your example data above.

**Comment by avilella** [comment]
Will do.

**Comment by avilella** [comment]
Has the version id gone backwards for head master? I did this:

```
pip install --user --upgrade git+https://github.com/ewels/MultiQC.git
multiqc --version
multiqc, version 0.3.1
```

**Comment by ewels** [comment]
Nope, not sure why that happened. I never use the `--upgrade` flag. Should be on v0.5dev

**Comment by avilella** [comment]
Ok, I uninstall'ed and install --upgraded again now.

I get data parsed, but an empty plot:

multiqc_methylQA.txt
```
Sample  CG_percent_meth CHH_count_unmeth        CG_count_meth
oversized_reads CHG_percent_meth        CHG_count_unmeth
 CN_count_meth   CN_count_unmeth mappable_reads  mapped_bases    coverage
     CHG_count_meth  CHH_count_meth  quality_failed
 CHH_percent_methCG_count_unmeth
WBGS-oxBS-vB-1000ng-PCR06-R02_S1_L001_R1_001.cutB_pe.sorted.mrgd.report
50.8    2107430.0       66133.0 0.0     99.81   683711.0        0.0     0.0
    137964.0        17019577.0      0.0     1310.0  3736.0  0.0     99.82
68294.0
```
Attached the empty plot screenshot

**Comment by ewels** [comment]
Your e-mail replies to github issues don't work sorry - no formatting and no attachment. Can you also send through `multiqc_report/.multiqc_log` and the source file please?

**Comment by ewels** [comment]
Also, [this](https://github.com/ewels/MultiQC_TestData/blob/master/data/methylQA/ABC37-26-1_S13_L001_R1_001.cutB_pe.sorted.bam.report) is the testing file that I used to build the module, based on what you submitted above.

**Comment by avilella** [comment]
I tried it with a bunch of different datasets, an unmatched one is the
first I showed.

I didn't see anything informative in the log file, I will create a fresh
one with a non-sensitive dataset.

A.

**Comment by ewels** [comment]
Ok, sounds good. I'll reopen this issue if you can provide a log file that breaks the module.
