### ISSUE TITLE
MultiQC - FASTQC sequence duplication table

### ISSUE THREAD

**Issue by Nomad360** [ewels/MultiQC#674]
Dear Phil, 

Thank you for putting in so much work to MultiQC – it has been a really useful tool for my work! I was just wondering if it would be possible to add a table for the FASTQC module stating what over-represented sequences were present within sample data? 

Thanks again, 
Andrew

**Comment by ewels** [comment]
Hi Andrew,

I'm afraid not - this is an example of something that won't scale well within MultiQC. It's pretty common for people to run with hundreds or even thousands of FastQC samples in a single report and there's no easy way to represent this information generically.

If you have an idea for how we could represent this in a scalable way then let me know!

Phil
