### ISSUE TITLE
cutadapt with paired reads - MultiQC only picks up one read

### ISSUE THREAD

**Issue by zsteve** [ewels/MultiQC#675]
**Description of bug:**
I am using `cutadapt` (multiple versions, have used 1.12, 1.15, 1.9.1) on a set of paired reads. Adapter trimming works fine and MultiQC doesn't seem to complain. However, looking at the report, MultiQC seems to only pick up on *one* of the reads (in this case, R2). This is despite information on *both* reads being present in the log file.

**File that triggers the error:**
 
[cutadapt_log.txt](https://github.com/ewels/MultiQC/files/1675876/cutadapt_log.txt)

 **Command used to run MultiQC**
     `multiqc .`
* **MultiQC Version:**
    MultiQC 1.3
* **Operating System:**
    Ubuntu 16.04
* **Python Version:**
    Python 2.7

**Comment by ewels** [comment]
Thanks @zsteve - looks like the format of the cutadapt logs changed between versions 1.8 and 1.9. Previously, the Length plot was for both reads combined, now there are two plots - one for each read. The parsing code in MultiQC is flexible enough that it picks them both up, but they'll have the same sample name, so R2 overwrites R1 and you only see R2.

Note that the value in the General Statistics table (% base pairs trimmed) is correct for both files, this is only the length plot that is affected.

I need to add in some new code to handle this case. Need to think about whether to merge the data from both reads (as in earlier versions) or whether to add more tabs to the plot.

Phil

**Comment by ewels** [comment]
Hi @zsteve,

Have a play and see what you think - the new behaviour should handle all versions of cutadapt now and give you two traces.

Phil
