### ISSUE TITLE
Specify an ID for columns from custom content to allow conditional formatting

### ISSUE THREAD

**Issue by RoxaneLS** [ewels/MultiQC#677]
Hi Phil, I've tested the conditional formatting to colour the bar plots in my tables, following your instructions here http://multiqc.info/docs/#conditional-formatting however it's not working and I think that's because the unique ID for my tables change every time.

When running the same multiqc command on the same data, I obtain 2 reports, and for the same column in the same table, when I "Inspect" the element, I get a different info:

```html
<td class="data-coloured mqc-140718333454520_total ">
  <div class="wrapper">
    <span class="bar" style="width:100.0%; background-color:#b5c6d9;"></span>
    <span class="val">1<span class="mqc_thousandSep"></span>768<span class="mqc_thousandSep"></span>890<span class="mqc_thousandSep"></span>924.0</span>
  </div>
</td>
```

second time:

```html
<td class="data-coloured mqc-139828586005672_total ">
  <div class="wrapper">
    <span class="bar" style="width:100.0%; background-color:#b5c6d9;"></span>
    <span class="val">1<span class="mqc_thousandSep"></span>768<span class="mqc_thousandSep"></span>890<span class="mqc_thousandSep"></span>924.0</span>
  </div>
</td>
```

On gitter you said that I need to specify an ID so that it’s not randomly generated, but there's no doc about it so you'll try to get it to work from my example files - see attached. (Pls note I had to add '.txt' in the files extension because it wouldn't let me attach .yaml or .tsv files)

Many thanks in advance, it would be a great feature to have!
Roxane

[08042789.data_stats.tsv.txt](https://github.com/ewels/MultiQC/files/1693501/08042789.data_stats.tsv.txt)
[multiqc_config.yaml.txt](https://github.com/ewels/MultiQC/files/1693502/multiqc_config.yaml.txt)

**Comment by ewels** [comment]
Thanks @RoxaneLS! What version of MultiQC are you using? When I run your file and config the HTML output has fixed html ID elements instead of the random ones above, so I may have already fixed this.

Phil

**Comment by RoxaneLS** [comment]
Oh. Sorry I forgot to include my version: multiqc/1.2

Which version should I use then?

**Comment by RoxaneLS** [comment]
Indeed, testing with the dev version and I get a fixed ID which I can use with `table_cond_formatting_rules`. It's not quite working yet though, like it's colouring everything green even when it hould "fail", but perhaps I'm not doing it right. Will keep playing with it and will let you know.
Cheers

**Comment by ewels** [comment]
Ok great :) Yes, see [other issue](https://github.com/ewels/MultiQC/issues/676#issuecomment-363319882) for my comment on MultiQC versions. The conditional formatting feature is very new, so more likely to be affected by changes and bugfixes in recent history.

I'll close this for now as I don't think that there's anything I need to change in the MultiQC code. However, if you keep having problems with the conditional formatting code let me know (feel free to keep commenting below) and I'll reopen the issue and look into it.

Cheers,

Phil

**Comment by RoxaneLS** [comment]
Thanks Phil. Unfortunately even when using the dev version it doesn't work quite well. It does recognise the intended column so that's good, but it doesn't seem to understand the values - it turns everything green! :) 

Perhaps I'm doing something wrong?

```
table_cond_formatting_rules:
    total:
        pass:
            - gt: 1000000
        warn:
            - lt: 1000000
        fail:
            - lt: 500000
```

![conditionalformattingallgreen](https://user-images.githubusercontent.com/13159414/35953955-4e98b6a4-0cdb-11e8-9c22-acb5aba3e1b6.png)

[NTC.data_stats.tsv.txt](https://github.com/ewels/MultiQC/files/1705618/NTC.data_stats.tsv.txt)
[NA12878.data_stats.tsv.txt](https://github.com/ewels/MultiQC/files/1705619/NA12878.data_stats.tsv.txt)
[08035117.data_stats.tsv.txt](https://github.com/ewels/MultiQC/files/1705620/08035117.data_stats.tsv.txt)
[_.multiqc_config.yaml.txt](https://github.com/ewels/MultiQC/files/1705623/_.multiqc_config.yaml.txt)



Pls note I had to add '.txt' to all attached files and '_' before '.multiqc_config.yaml' file to allow for upload -_-

**Comment by RoxaneLS** [comment]
Should have added that I was aiming for NA12878 PASS, NTC fAIL and 08035117 WARN.

**Comment by RoxaneLS** [comment]
Interestingly I tested it with another column in the general stats, from FASTQC (mqc-generalstats-total_sequences), and it worked there! Is this function limited to general stats?

**Comment by ewels** [comment]
Ok, so I tested your files with the latest v1.5dev and it mostly worked fine, except that `NTC` was labelled both in orange and in red. This shouldn't be possible and the double labelling issue is fixed in bedc9da1e887145298e6d294c1d46e3b564a3de5

I now get this, which looks correct?
<img width="406" alt="pscreen" src="https://user-images.githubusercontent.com/465550/36350433-e3874a8c-1497-11e8-8118-8a8da0b5f3c9.png">

This is with the `Raw Data Stats` table, not General Stats.

Can you try again with the latest version of MultiQC and see if you still get the error? Make sure that you pull the latest changes with the following command:

```
pip install --upgrade --force-reinstall git+https://github.com/ewels/MultiQC.git
```

Phil

**Comment by ewels** [comment]
Closing again as it seems to be working for me :) Again, let me know how you get on and we can reopen if you're still having problems. As in #682 - please zip / tar an entire directory and send that for me to replicate next time please. Then I can see the full MultiQC log file and have _all_ of the input files etc.

Phil

**Comment by RoxaneLS** [comment]
Wonderful! I've tested it with the latest dev version and it works fine in both the General Stats table and the custom content table. Thx very much.

Also if I may ask for more :) I was actually hoping that the whole bar would become red (if failed) instead of just a red circle around the text inside the blue bar. Does that make sense? Would that be possible?

**Comment by ewels** [comment]
> I was actually hoping that the whole bar would become red (if failed) instead of just a red circle around the text inside the blue bar.

The reason for doing it the way it is currently is so that the background value bar still works. I could simply recolour the bar to be red, but that probably wouldn't be great as often failing categories have low numbers and so the bar may not be visible. So to make the whole cell red I'd have to remove the numeric bar in the background. Whilst this is possible, I'd prefer not to. Do you think that the text highlight circle is insufficient?

**Comment by RoxaneLS** [comment]
I think it's sufficient, just not as aesthetic (subjective to my own taste
I guess). However you're right, if the number is too low then we won't even
see the bar at all - may it be red or blue! So yeah, let's keep it as it is
for now. :) Thanks!

2018-02-20 19:38 GMT+11:00 Phil Ewels <notifications@github.com>:
