### ISSUE TITLE
The "Read GC Content" graph has the title "RSeQC: Gene Body Coverage"

### ISSUE THREAD

**Issue by freekvh** [ewels/MultiQC#679]
The "Read GC Content" graph has the title "RSeQC: Gene Body Coverage", this screenshot says it all:

![image](https://user-images.githubusercontent.com/12241293/35861396-d58a451e-0b47-11e8-9cea-bfb32cd06ab7.png)

Other than the title the graph is showing the correct data (or at least it seem to be).

I'm using version 1.3 but I didn't see a fix in the changelog for 1.4.

Highest regards,

Freek.

**Comment by ewels** [comment]
hah, yes I see what you mean..

**Comment by ewels** [comment]
Fixed. Thanks!
