### ISSUE TITLE
Output files similar to 'multiqc_data/multiqc_general_stats.txt' for custom tables

### ISSUE THREAD

**Issue by RoxaneLS** [ewels/MultiQC#681]
Hi Phil,
would it be possible to create output files similar to `multiqc_data/multiqc_general_stats.txt` but for custom tables? As you know I am using ChronQC to display MultiQC outputs over time and it works really well for outputs from MultiQC modules (e.g. fastqc, bcl2fastq etc) but it can't display values from my custom tables (arguably the most important ones!) since there is no corresponding output files in the `multiqc_data` dir. I can 'collate' the data myself for now but it would be great if MultiQC could do it automatically for us. 

Tried it with MultiQC dev1.5 and no such files avail in `multiqc_data` dir.

**Comment by RoxaneLS** [comment]
Hi Phil, have you got an ETA on this issue? It'd be extremely useful for longitudinal QC. Thx

**Comment by ewels** [comment]
Hi @RoxaneLS,

That should do the trick. Let me know if you hit any problems.

Phil

**Comment by RoxaneLS** [comment]
This is great. Thanks a lot! I just have to clean up a few things to get SampleX_R1 and SampleX_R2 as SampleX only, so that they can all appear on the same graphs. Thanks again
