### ISSUE TITLE
Custom content module broke in v1.4

### ISSUE THREAD

**Issue by RoxaneLS** [ewels/MultiQC#682]
**Description of bug:**
Hi Phil, I installed multiqc v1.4 to take advantage of the small fixes we discussed earlier (conditional formatting etc) and tested it on my previous dataset to make sure it still worked. Unfortunately I got this error message and none of my custom tables appeared in the final report. I tried again on the exact same data using v1.2 and it worked fine.

Can you pls help me finding put what the issue is?

**MultiQC Error log:**
```
[rlegaie@vmpr-res-cluster1 ~]$ multiqc $RUNDIR/QC/MultiQC $RUNDIR/*/QC $BCL2FASTQDIR -f -o $MULTIQCDIR -n multiqc_test1_4
[INFO   ]         multiqc : This is MultiQC v1.4
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '/home/rlegaie/multiQC/171208_NS500817_0252_AHF77JBGX5/QC/MultiQC'
[INFO   ]         multiqc : Searching '/home/rlegaie/multiQC/171208_NS500817_0252_AHF77JBGX5/08021342/QC'
[INFO   ]         multiqc : Searching '/home/rlegaie/multiQC/171208_NS500817_0252_AHF77JBGX5/08027127/QC'
[INFO   ]         multiqc : Searching '/home/rlegaie/multiQC/171208_NS500817_0252_AHF77JBGX5/08029463/QC'
[INFO   ]         multiqc : Searching '/home/rlegaie/multiQC/171208_NS500817_0252_AHF77JBGX5/08035117/QC'
[INFO   ]         multiqc : Searching '/home/rlegaie/multiQC/171208_NS500817_0252_AHF77JBGX5/08042735/QC'
[INFO   ]         multiqc : Searching '/home/rlegaie/multiQC/171208_NS500817_0252_AHF77JBGX5/08044099/QC'
[INFO   ]         multiqc : Searching '/home/rlegaie/multiQC/171208_NS500817_0252_AHF77JBGX5/08066089/QC'
[INFO   ]         multiqc : Searching '/home/rlegaie/multiQC/171208_NS500817_0252_AHF77JBGX5/08069519/QC'
[INFO   ]         multiqc : Searching '/home/rlegaie/multiQC/171208_NS500817_0252_AHF77JBGX5/08086509/QC'
[INFO   ]         multiqc : Searching '/home/rlegaie/multiQC/171208_NS500817_0252_AHF77JBGX5/08104114/QC'
[INFO   ]         multiqc : Searching '/home/rlegaie/multiQC/171208_NS500817_0252_AHF77JBGX5/NA12878/QC'
[INFO   ]         multiqc : Searching '/home/rlegaie/multiQC/171208_NS500817_0252_AHF77JBGX5/NTC/QC'
[INFO   ]         multiqc : Searching '/pipeline/Runs/NextSeq/171208_NS500817_0252_AHF77JBGX5/ProjectFolders_8_0/Stats/'
Searching 608 files..  [####################################]  100%             
[INFO   ]  custom_content : seqliner_mapping_stats: Found 12 samples (table)
[INFO   ]  custom_content : seqliner_seq_stats: Found 1 samples (table)
[INFO   ]  custom_content : seqliner_cov_stats: Found 12 samples (table)
[ERROR  ]         multiqc : Oops! The 'custom_content' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    /home/rlegaie/multiQC/171208_NS500817_0252_AHF77JBGX5/NTC/QC/MultiQC/NTC.ROIcov_stats.tsv
============================================================
Module custom_content raised an exception: Traceback (most recent call last):
  File "/config/binaries/multiqc/1.4/lib/python3.4/site-packages/multiqc/plots/table.py", line 188, in make_table
    if 'lt' in cmp and cmp['lt'] > val:
TypeError: unorderable types: int() > str()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/binaries/multiqc/1.4/bin/multiqc", line 427, in multiqc
    output = mod()
  File "/config/binaries/multiqc/1.4/lib/python3.4/site-packages/multiqc/modules/custom_content/custom_content.py", line 214, in custom_module_classes
    parsed_modules.append( MultiqcModule(k, mod) )
  File "/config/binaries/multiqc/1.4/lib/python3.4/site-packages/multiqc/modules/custom_content/custom_content.py", line 257, in __init__
    self.add_section( plot = table.plot(mod['data'], headers, pconfig) )
  File "/config/binaries/multiqc/1.4/lib/python3.4/site-packages/multiqc/plots/table.py", line 44, in plot
    return make_table ( dt )
  File "/config/binaries/multiqc/1.4/lib/python3.4/site-packages/multiqc/plots/table.py", line 191, in make_table
    log.warn("Not able to apply table conditional formatting to '{}' ({})".format(val, cmp))
NameError: name 'log' is not defined
============================================================
[INFO   ]          fastqc : Found 24 reports
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : multiQC/171208_NS500817_0252_AHF77JBGX5/QC/MultiQC/multiqc_test1_4.html
[INFO   ]         multiqc : Data        : multiQC/171208_NS500817_0252_AHF77JBGX5/QC/MultiQC/multiqc_test1_4_data
[INFO   ]         multiqc : MultiQC complete
[rlegaie@vmpr-res-cluster1 ~]$ 
[rlegaie@vmpr-res-cluster1 ~]$ 

```

* **File that triggers the error:**
  
[multiqc_test1_4.html.txt](https://github.com/ewels/MultiQC/files/1718200/multiqc_test1_4.html.txt)
[NTC.cov_stats.tsv.txt](https://github.com/ewels/MultiQC/files/1718195/NTC.cov_stats.tsv.txt)
[NTC.mapping_stats.tsv.txt](https://github.com/ewels/MultiQC/files/1718196/NTC.mapping_stats.tsv.txt)
[NTC.data_stats.tsv.txt](https://github.com/ewels/MultiQC/files/1718197/NTC.data_stats.tsv.txt)
[NTC.ROIcov_stats.tsv.txt](https://github.com/ewels/MultiQC/files/1718198/NTC.ROIcov_stats.tsv.txt)
[seq_stats.tsv.txt](https://github.com/ewels/MultiQC/files/1718199/seq_stats.tsv.txt)

* **Command used to run MultiQC**
    * ` multiqc $RUNDIR/QC/MultiQC $RUNDIR/*/QC $BCL2FASTQDIR -f -o $MULTIQCDIR -n multiqc_test1_4`

* **MultiQC Version:**
    * MultiQC v1.4
* **Operating System:**
    * linux
* **Python Version:**
    * Python 3.4.5
* **Method of MultiQC installation:**
    * Donno but can find out if necessary

**Comment by RoxaneLS** [comment]
This issue might actually link to that one: https://github.com/ewels/MultiQC/issues/677 since, when I tried again running multiqc 1.4 on the same data after commenting out the conditional formatting section, the report was built correctly and no error message appeared.

So basically this bit in the config .yaml file seems to bit problematic:

```
table_cond_formatting_rules:
    mqc-generalstats-total_sequences:
        # pass:
        #     - gt: 50
        fail:
            - lt: 40
    total:
        # pass:
        #     - gt: 1000000
        warn:
            - lt: 1000000
        fail:
            - lt: 500000
```

**Comment by ewels** [comment]
> `NameError: name 'log' is not defined`

Ooh nice, this is a totally new bug - good find! 🏆 😀 

It looks like the log message that triggers the exception is trying to tell you that something didn't work though. I'll fix the log and then hopefully that can help us fix what was triggering it.

**Comment by ewels** [comment]
So I just fixed the `NameError` and forced floats which I think will hopefully fix the problem that was upstream of that in e990222

However, when I run the latest v1.5dev MultiQC with the files you uploaded (and the `multiqc_config.yml` file from #677), everything works fine. Though I don't have the bcl2fastq files that were used in the report that you pasted.

Could you try this again with v1.5dev and see if you still get the error please? If so, could you zip / tar the entire directory that you're running with and attach that please?

Cheers,

Phil
