### ISSUE TITLE
Compatibility with new versions of Picard? [GATK 4.0.0.0]

### ISSUE THREAD

**Issue by Rmulet** [ewels/MultiQC#683]
Hi Phil,

I have noticed that MultiQC does not properly detect all the log files generated by Picard Tools. I have installed the development version, which should be able to recognise the new format, but it fails to do so in several cases. Namely, at least CollectGcBiasMetrics and CollectAlignmentSummaryMetrics do not work (the latter as part of CollectMultipleMetrics), whereas MarkDuplicates does not give any problem. 

Perhaps you are already aware of this -I've seen recent changes in the Picard module-, but I still thought it might be useful to report it. I am attaching the log files of the aforementioned tools for your convenience. 

* MultiQC Version: 1.5.dev0
* OS: Ubuntu 16.05
* Python Version: 2.7.11+
* Method of MultiQC installation: pip

[Picard_Logs.zip](https://github.com/ewels/MultiQC/files/1719507/Picard_Logs.zip)

**Comment by Rmulet** [comment]
Hi @ewels,

Just a small remark which you are probably already aware of. Picard can be downloaded and run as a standalone jar, in which case it takes arguments without dashes (e.g. INPUT). Then the log files can be identified by MultiQC flawlessly regardless of the version of Picard.

However, Picard tools can also be used as a part of GATK, which takes arguments preceded by dashes (e.g. --INPUT). The log files produced in this way -like those I attached in my original post- cannot be detected by MultiQC,  Since these log files are almost identical to the former with the exception of said dashes, I suspect the "--" fails to be recognized by the regex in the code.

**Comment by ewels** [comment]
Almost - I think it's not the dashes before, but that the equals symbol afterwards. Picard seems to have `INPUT=filename` and GATK has `--input filename`

I'll update all of the regexes to match both.

**Comment by ewels** [comment]
Ok, fix pushed. Hopefully should work in v0.5dev. Would be great if you could give it a spin, hopefully should work now with all modules!

Phil

**Comment by Rmulet** [comment]
Hi @ewels,

I've tried the new version and MultiQC now detects all the reports generated by Picard tools. However, I have encountered a new issue with the GcBiasMetrics module which also seems to be related with the input file regex. Namely, whenever there is the word "input" in the name of the file (which in my case is common for ChIP-seq experiments), the string immediately afterwards is taken as the name of the sample. E.g. _HepG2_input_merged.gc_chart_ becomes _merged.gc_chart_. 

This behavior is exclusive of this module as far as I can see -- the others handle this word just fine. I am attaching a few examples for your convenience. 
[example_gcbias.zip](https://github.com/ewels/MultiQC/files/1744917/example_gcbias.zip)

Best, 

Roger

**Comment by ewels** [comment]
Ok, yes - it's because GcBiasMetrics has `OUTPUT` listed before `INPUT`, and the pattern matching takes the first match. In this case it matches the middle of the filename (`input_merged.gc_chart`) as the picard input statement, and correctly trims to `_merged.gc_chart`.

I've fixed this by requiring either a `=` or some whitespace between `input` and the string. Previously both were optional, meaning that `input fn`, `input=fn` and `input_fn` all matched. Now it's just the first two. This seems to solve the problem for your examples.

Thanks again for reporting and providing examples! These kinds of bugs are impossible to spot without this kind of help.

Once again, closed until you find another problem..! 😉 

Phil
