### ISSUE TITLE
Qualimap module in MultiQC doesn’t like it when target is 100% covered

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#686]
Via email from Miko:

> FYI, Qualimap module in MultiQC doesn’t like it when target is 100% covered, can fix with e.g. the following:

```diff
--- QM_BamQC.py 2018-02-16 17:24:21.827816318 +0200
+++ QM_BamQC.py.fix   2018-02-16 18:09:05.861937710 +0200
@@ -560,6 +560,9 @@
             bases_within_threshs[dt[c]] = bases_within_threshs[dt[c - 1]]
         if depth >= dt[c]:
             bases_within_threshs[dt[c]] += bases_by_depth[depth]
+    while c + 1 < len(dt):
+        c += 1
+        bases_within_threshs[dt[c]] = total_size
     for t in dt:
         bs = bases_within_threshs[t]
         if total_size > 0:
```

See this code: https://github.com/ewels/MultiQC/blob/5fa5e3f17dcfdcc87091b9b00eead4ed6e0c2879/multiqc/modules/qualimap/QM_BamQC.py#L568-L579

**Comment by mvalori** [comment]
Multiple depth thresholds that are under the lowest reported coverage in coverage_histogram.txt get 0% coverage even though it should be 100% in this example report: [qualimap_example.tar.gz](https://github.com/ewels/MultiQC/files/1732987/qualimap_example.tar.gz)

**Comment by ewels** [comment]
ah ok, I understand - thanks for the example report. You're talking about the step at the start of this plot...?

![qualimap_genome_fraction](https://user-images.githubusercontent.com/465550/36350467-965450c4-1498-11e8-8d54-445888f2bbf8.png)

**Comment by ewels** [comment]
Ok, fixed - many thanks for the report, example data and fix diff @mvalori!
