### ISSUE TITLE
RseQC module does not show sample names

### ISSUE THREAD

**Issue by rfenouil** [ewels/MultiQC#694]
**Description of bug:**
Hello, I used RSeQC module in one of my reports and the 'Infer experiment' section shows a nice bargraph but sample names don't seem to be reported correctly on graph axis.
Instead of sample names (as everywhere else in the report) I get things like: 'rseqc_log.102', 'rseqc_log.52', ...

I tried to look at the module code but my python is too rusty to find what happens here.

Can you reproduce the same behavior ?

Thank you !

**MultiQC Error log:**
```
[INFO   ]         multiqc : This is MultiQC v1.5.dev0
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Report title: testRun2013
[INFO   ]         multiqc : Searching '.'
[INFO   ]  custom_content : software_versions: Found 1 sample (html)
[INFO   ]  custom_content : sample-similarity: Found 8 samples (heatmap)
[INFO   ]  custom_content : biotype-counts: Found 8 samples (bargraph)
[INFO   ]  custom_content : DupRadar: Found 8 samples (linegraph)
[INFO   ]  custom_content : edgeR-sample-distances: Found 8 samples (scatter)
[INFO   ]          fastqc : Found 16 reports
[INFO   ]          fastqc : Found 16 reports
[INFO   ]            star : Found 8 reports
[INFO   ]           rseqc : Found 8 infer_experiment reports
[INFO   ]          preseq : Found 8 reports
[INFO   ]          picard : Found 8 MarkDuplicates reports
[INFO   ]  feature_counts : Found 8 reports
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : testRun2013_multiqc_report.html
[INFO   ]         multiqc : Data        : testRun2013_multiqc_report_data
[INFO   ]         multiqc : MultiQC complete
```

* **Command used to run MultiQC**
    * `multiqc -f --title "testRun2013" --filename testRun2013_multiqc_report --config multiQC_configFinal.yaml --sample-names sampleRename.txt .`
* **MultiQC Version:**
    * MultiQC v1.5dev
* **Operating System:**
    * Ubuntu 17.10
* **Python Version:**
    * Python 2.7.12
* **Method of MultiQC installation:**
    * pip

**Comment by ewels** [comment]
Hi @rfenouil,

Are you able to share the input files that you're using here so that I can try to replicate this?

Thanks,

Phil

**Comment by rfenouil** [comment]
Dear Phil,

my apologies, once again I noticed that the problem comes from a bad file renaming on my side, which prevents correct parsing...
I'll try to be more careful before triggering the issue button.

Thank you very much for your reactivity !

**Comment by ewels** [comment]
Aha! No problem 👍 Thanks for letting me know..
