### ISSUE TITLE
Add Qualimap support

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#7]
[Qualimap](http://qualimap.bioinfo.cipf.es/) is widely used for data QC and would be a good addition to MultiQC. It has a number of data outputs that could be used, but I think it would be good to start with those plotted in [ngi_visualizations](https://github.com/ewels/ngi_visualizations/tree/master/ngi_visualizations/qualimap)...

General stats table:
- [x] Median coverage
- [x] Median insert size
- [x] % of genome >= 30x coverage
- [x] mapped reads avg. GC

Main sections:
- [x] Coverage Histogram
- [x] Insert Size Histogram
- [x] Genome Fraction Coverage
- [x] GC distribution

**Comment by guillermo-carrasco** [comment]
Oh, lucky me I read the issues list first, I was going to open this same issue :stuck_out_tongue: .

@ewels I can have a look at this module and ask you if I get stuck.

**Comment by ewels** [comment]
I added the issue after you mentioned this to me on slack :wink: 

Yup - have a go! Though I can't promise that I won't go crazy with pedantic tweaks.. Sorry in advance :grin: Check out the [contributing notes](https://github.com/ewels/MultiQC/blob/master/CONTRIBUTING.md) first though, these are currently the docs. I might make a github wiki instead if I start writing much more.

**Comment by guillermo-carrasco** [comment]
I'm ready for this, I know how picky you are :sweat_smile:

**Comment by ewels** [comment]
@guillermo-carrasco: I just pushed a commit with an experimental generalised Python function for doing XY plots, see 5f6f86ac8bc7b3661c74fa344e9df22110c55cad

Note that the Qualimap module was the only module that didn't need a rewrite to use this, and I don't have any Qualimap data to test with. So it might not work :grin:

On that note, if you could add a couple of example Qualimap output files to the `tests/data` directory that would be ace.

**Comment by guillermo-carrasco** [comment]
@ewels does the following list correspond with what needs to be finished? 
- [ ] Coverage histogram: Convert bin counts into % of the genome instead 
- [ ] Add median coverage to the general stats table 
- [ ] Shorten the coverage plot like its done in [ngi_visualizations](https://github.com/NationalGenomicsInfrastructure/ngi_visualizations/blob/master/examples/qualimap_coverage.png)
- [ ] Insert size histogram
- [ ] Genome fraction coverage GC distribution

Also I have a question, how to we deal with information that is redundant between different QC tools? i.e both `FastQC` and `Qualimap` give you a plot for the GC content. Do we still generate a plot per tool? Only one? I would say a plot per tool, because no one ensures that the user is using both. Eller?

**Comment by guillermo-carrasco** [comment]
hmm also, did you mean median total coverage, or mean coverage per sample?

**Comment by ewels** [comment]
Yeah, see my check list at the top of this thread ;) I'm not sure about shortening the coverage plot, I think maybe leave that as it is as it's easy enough to zoom in.

Definitely keep both - there are already a few modules that duplicate stats like this. Remember that FastQC is before alignment and Qualimap after, so the numbers may differ (and the difference may be interesting). Plus as you say, each module should work independently of all others as we don't know what people will have.

**Comment by guillermo-carrasco** [comment]
:+1: thanks, good point about before and after alignment, didn't think about that!

**Comment by ewels** [comment]
Cool, I think this is done now!

**Comment by vladsaveliev** [comment]
Hi Phil,

I wonder what was the reason behind choosing 30x as the threshold to show coverage percentage? I would personally pick 20x as from my experience many people use that as a conservative threshold to call a germline variant. So I'm interested to see how you justify 30x :-)

By the way, currently Qualimap module also reports (hidden) 1x, 5x, 10x, 50x. I think that if the coverage is high as for deep targeted sequencing experiments, it might be useful to also report 100x, 250x, 500x, 1000x, 5000x, and more (until there is coverage). Also, another idea is add a threshold related to average depth. For instance, 1/2 of average depth. What do you think of these ideas?

**Comment by ewels** [comment]
Hi @vladsaveliev,

I've moved this into a new issue (#326) - hope that's ok. Easier for me to keep track of then. I'll reply there.

Phil

**Comment by vladsaveliev** [comment]
Cool, sure, thanks!
