### ISSUE TITLE
calculate_clip_overlap module

### ISSUE THREAD

**Issue by avilella** [ewels/MultiQC#70]
Maybe it's easier from the output file of a perl script that produces the output like this:

https://github.com/avilella/calculate_clip_overlap/raw/master/NTC-1_S3_L001_R1_001.cutB_pe.sorted.mrgd.bam.clip_overlap.txt

```
column -t NTC-1_S3_L001_R1_001.cutB_pe.sorted.mrgd.bam.clip_overlap.txt 
SEQ    read_PE  scov     total_nuc  mapped_nuc  lost_nuc  effic_pc
2x75   279      0.00001  20850      19712       1482      92.89
2x100  279      0.00001  27800      19712       3595      87.07
2x125  279      0.00001  34750      19712       6905      80.13
2x150  279      0.00001  41700      19712       11763     71.79
2x250  279      0.00002  69500      19712       38101     45.18
```

**Comment by avilella** [comment]
Here SEQ is the simulated type of cycles, read_PE is total read pairs, ..., last column is efficiency pct: a given bam would have 92.89% efficiency after clipping the overlapping bases.

**Comment by ewels** [comment]
No input filenames printed again.. Though it's a fair assumption that files will typically be called `input.bam.clip_overlap.txt`? Maybe better to test by file contents though as `$tag` can be changed, but then try to take the sample name from the filename still.

Nice script by the way! I might just go and use that myself right now :)

**Comment by avilella** [comment]
Added a couple of key=value pairs on top of the outputfile now.

```
#inputfile=/bi/group/cegx/CEGX_Run113/CEGX_Run113-25578593/NTC_1-29425996/Data/Intensities/BaseCalls/NTC-1_S3_L001_R1_001.cutB_pe.sorted.mrgd.bam
#avg_tlen=225.89
SEQ     read_PE scov    total_nuc       mapped_nuc      lost_nuc
 effic_pc
2x75    279     0.00001 20850   19712   1482    92.89
2x100   279     0.00001 27800   19712   3595    87.07
2x125   279     0.00001 34750   19712   6905    80.13
2x150   279     0.00001 41700   19712   11763   71.79
2x250   279     0.00002 69500   19712   38101   45.18
```

**Comment by ewels** [comment]
Nice! Annoyingly GitHub doesn't parse markdown from e-mails, but I get the idea..

What would you like plotted here? A [grouped bar plot](http://www.highcharts.com/demo/bar-basic) of the different _in-silico_ read lengths?

It'd be cool if there was a row for the numbers for the observed data perhaps. I'm a little wary of plotting multiple things per sample in reports as the plots can get very cramped quite quickly when running many samples. Single metrics could be put in the general statistics table easily.

Also you could use this data to plot a histogram of read overlap lengths too - kind of the same as insert size metrics I guess though ([coming soon](https://github.com/ewels/MultiQC/issues/12)). Just an idea.

Phil

**Comment by avilella** [comment]
A grouped bar plot would be great to start with :-)

We could definitely have a row with the observed data, I'll add that as
'obs' in the SEQ column.

**Comment by avilella** [comment]
https://github.com/avilella/calculate_clip_overlap/blob/master/NTC-1_S3_L001_R1_001.cutB_pe.sorted.mrgd.bam.clip_overlap.txt

now with 'obs'

**Comment by ewels** [comment]
Nice! That was fast :) How come the numbers look like `2x75` when `avg_tlen=225.89`? I would expect it to look more like `2x250`.. Or is this just dummy data?

**Comment by avilella** [comment]
It's dummy data.

In real life there is a real difference between 'obs' and 2x75, which
relates to trimming before alignment. This is, a sample is sent for
sequencing at 2x75, it's trimmed, probably giving something like an average
of 2x73.5, but the relevant output of this experiment still relates to the
observed sequencing, which was 2x75. So at the moment 'obs' is a parameter
that is passed on and duplicates one of the entries.

With a bit more work, I should be able to turn it into the "real" obs,
after trimming.

**Comment by ewels** [comment]
Ah ok, so the script looks at the total length of the aligned pair fragment, rather than directly observing the overlapping single reads? Gotcha.

**Comment by ewels** [comment]
Also, might be better to have one bar graph (not grouped) but with buttons along the top for the different datasets. Like `counts` and `obs/exp` for cutadapt, or the different cytosine contexts in the bismark module. Still have all of the data, but don't have the crowding problem.

**Comment by avilella** [comment]
Yes, that would work very well.

**Comment by ewels** [comment]
Cool - I'll see what I can do. Quite a few module requests now though and I need to actually do some analysis work of my own, so might be a few weeks before I get to it.

If you fancy having a go yourself, the plotting should be pretty much the same as [this bismark plot](https://github.com/ewels/MultiQC/blob/master/multiqc/modules/bismark/bismark.py#L252-L276). There are docs about [finding log files](https://github.com/ewels/MultiQC/blob/master/docs/writing_python.md#finding-log-files) and [adding to the general stats table](https://github.com/ewels/MultiQC/blob/master/docs/writing_python.md#adding-to-the-general-statistics-table).

**Comment by avilella** [comment]
Ok, so if I start from bismark.py, I should be able to modify it to the
needs of this ticket?

Any other source file I should look for example's sake?

A.

**Comment by ewels** [comment]
Yeah, pretty much. The bismark module isn't the simplest in the pack, as it parses three different log files which complicates things a little. So maybe take a look at [preseq](https://github.com/ewels/MultiQC/blob/master/multiqc/modules/preseq/preseq.py) or [star](https://github.com/ewels/MultiQC/blob/master/multiqc/modules/star/star.py) first if you want to get an overview of how a simpler module works.

**Comment by avilella** [comment]
What's a good example of a parser that does read the sample name from the file? Thx

**Comment by ewels** [comment]
This is already built into the function that searches for files (see [docs](https://github.com/ewels/MultiQC/blob/master/docs/writing_python.md#finding-log-files)):

```python
for f in self.find_log_files('_my_prog.txt'):
    print f['s_name']   # Sample name (from cleaned fn)
```

**Comment by avilella** [comment]
I was trying to hack something up together yesterday, but half-way through
I got confused with the dictionary with s_names:

https://github.com/avilella/MultiQC/blob/master/multiqc/modules/calculate_clip_overlap/calculate_clip_overlap.py

A.

**Comment by avilella** [comment]
The input file name is prefix.bam and the output is prefix.clip_overlap.txt

**Comment by ewels** [comment]
Ok - so what's contained within `f['s_name']`? The full filename?

You can add `.clip_overlap.txt` to [`config.fn_clean_exts`](https://github.com/ewels/MultiQC/blob/master/multiqc/utils/config.py#L34) - then `f['s_name']` should come back as just `prefix`.

Phil

**Comment by avilella** [comment]
Hmmm, I think I need to study the code a bit more rather than doing a lot
of copy+pasting and shuffling, as I did.

I also want to hook-up a horizontal barplot with multiple tabs for each of
the columns in the clip_overlap.txt file, similar to the "number of reads"
vs "percentage" tab options in bismark/bowtie2. Currently I started by just
looking at the last column.

**Comment by ewels** [comment]
Ok, well free free to shout if I can help. Bar plot will be cool - I would start exactly as you have though, get it working with one column first and then extend.

**Comment by ewels** [comment]
Hi @avilella - I've just rewritten the documentation about how to create new modules: [`docs/modules.md`](https://github.com/ewels/MultiQC/blob/master/docs/modules.md)

It's now a lot more extensive, and works through the process in sequence. Hopefully it should help!

Let me know if you have any comments or suggestions..

**Comment by avilella** [comment]
@ewels sorry this is not ready yet, reflecting how grindingly slow I am at writing python -- I am from the perl era of bioinformatics :-p

**Comment by ewels** [comment]
Hi @avilella,

I'm closing this issue now as it's been sitting around for a while. Feel free to reopen if you still want to create a module for this tool, however as its your own script I think it should be easier to parse the output using [MultiQC Custom Content](http://multiqc.info/docs/#custom-content).

Shout if you need any pointers!

Phil
