### ISSUE TITLE
Categorical axis labels not updated when switching between datasets

### ISSUE THREAD

**Issue by rfenouil** [ewels/MultiQC#702]
Dear Phil,

I am trying to develop a new module to plot FPKM/TPM distributions, based on StringTie output.
For an easy comparison between samples, I decided to plot these distributions as lines instead of bargraphs/histogram.

The idea is to compute myself the histogram counts using `numpy.histogram` function, and generate the resulting counts figure with `linegraph.plot` function. However, as I tried to use text (string) for x axis, and the `categories: True` option, I noticed some unexpected output.

**Description of bug:**

After some testing, I think that I can summarize the problem in two points:

1. Using text for tickmarks is not fully supported.
    * As I am trying to use the list of data dictionaries below, **without** `categories : True` option, the tickmarks on x axis are shown as numbers (probably indexes). That might be an expected behavior but I think that the function would benefit from allowing text entries there (OrderedDict can be used to guarantee correct ordering).

2. `categories : True` option is not fully supported
     * **With** the `categories : True` option, categories names appear as text under the tickmarks, but are not updated when switching from one dataset to another with the buttons (see `data_labels`). 
Apparently, only names from the last sample in the list are used (and when a dataset has more categories than the last one,  missing values are replaced by numbers, probably indexes).

* **File that triggers the error:**
    * Data list, then `data_labels` option in config dictionary:: 

```python
[ { '2_S2': {
        '[3.39 - 4.52)': 116, 
        '[9.04 - 10.17)': 19, 
        '[5.65 - 6.78)': 628, 
        '[7.91 - 9.04)': 128, 
        '[1.13 - 2.26)': 7, 
        '[2.26 - 3.39)': 15, 
        '[10.17 - 11.30]': 3, 
        '[6.78 - 7.91)': 419, 
        '[4.52 - 5.65)': 378, 
        '[0.00 - 1.13)': 425} },
  { '2_S2': {
        '[9.06 - 11.33]': 23, 
        '[6.80 - 9.06)': 552, 
        '[4.53 - 6.80)': 1002, 
        '[2.27 - 4.53)': 131, 
        '[0.00 - 2.27)': 430} }, 
  {  '2_S2': {
        '[2.48 - 3.73)': 198, 
        '[3.73 - 4.97)': 30, 
        '[4.97 - 6.21]': 6, 
        '[0.00 - 1.24)': 1258, 
        '[1.24 - 2.48)': 646} } ]
```

```python
[ {  'xlab': 'TPM values (asinh)', 
     'ylab': 'Count (asinh)', 
     'name': 'TPM' }, 
  {  'xlab': 'FPKM values (asinh)', 
     'ylab': 'Count (asinh)', 
     'name': 'FPKM' }, 
  {  'xlab': 'Coverage values (asinh)', 
     'ylab': 'Count (asinh)', 
     'name': 'Coverage' } ]
```

* **Command used to run MultiQC**
    * `multiqc -m stringtie --filename report.html -f .`
* **MultiQC Version:**
    * MultiQC v1.5dev0
* **Operating System:**
    * Ubuntu 17.10
* **Python Version:**
    * Python 2.7.14
* **Method of MultiQC installation:**
    * conda

**Comment by ewels** [comment]
Hi @rfenouil,

Before we go into the issue in more detail, I'm a little worried about your first couple of sentences. Typically, I explicitly avoid doing _any_ kind of computation within MultiQC modules - they should just parse text summary output from tools.

The important question here is speed - I'm sure everything works fine with 2 samples or 10, but if someone runs this on 20,000 single cell RNA seq datasets, will it still run in seconds / minutes with minimal compute requirements?

Phil

**Comment by rfenouil** [comment]
Hello @ewels,

thank you for your feedback, that's a good point indeed and I need to keep that in mind.
In the context of StringTie output though, I did not imagine it used simultaneously for millions of samples (and therefore millions of output files), but I can be wrong.
A graph with millions of lines would not be useful anyway, and that would defeat the purpose of the whole module.

As for the number of data points to process for each sample, I think some applications could reach the million(s) of values. The point of using numpy.histogram is to summarize this mass of data to something useable for a density plot. As such, numpy.histogram is very efficient (probably much faster than the file reading step) and can therefore be considered more like a formatting step than a heavy computation one.

In brief, I think that the impact of numpy.histogram is negligible when compared to the rest of the module code, but that could/should be tested against big RNA-seq datasets (I guess you have good examples in mind).

I mostly use this module as a python/multiqc dev exercise so your piece of advice is appreciated. If the module appears not to be useful or too heavy for the multiqc context, it is not a problem because I will be able to use the code as a separate script in the pipeline.

Romain.

**Comment by ewels** [comment]
> probably much faster than the file reading step

Yes - it's usually the reading of the file that I have a problem with. This is why I prefer MultiQC modules to read a pre-computed summary file rather than compute anything. I'm not worried about the `numpy.histogram` call itself, more the general point of reading in large files and doing anything with them.

Let's continue for now, but keep an eye on performance (see the [docs](http://multiqc.info/docs/#profiling-performance)). If the new execution is too slow, we can disable it by default and add a config option to enable it for users who want this output. I've already taken this approach with one or two other modules. Then we have the best of both worlds!

Phil

**Comment by ewels** [comment]
ps. In case you're curious - people with huge datasets (eg. single cell RNA) can still run MultiQC even though the HTML plots are not useful. MultiQC generates homogenous parsed data files in `multiqc_data` which are useful for downstream analysis. There's also JSON output which can be used by the MegaQC project for interactive querying on large datasets.

**Comment by ewels** [comment]
Regarding your initial post:

1. Using text for tickmarks is not fully supported, without `categories : True`
    * If `categories : True` is not specified, the axis is handled as a continuous numeric axis. Text labels do not really make sense in this context - they are discrete and have no associated linear spacing information. I don't really understand why you don't want to specify `categories : True` here?
2. Axis labels not updating when switching between categories
    * Yes, this is likely a bug. There have been similar minor bugs around the dataset switching functionality. The numeric categories is the HighCharts plotting library trying to cope with the incorrectly shaped data, this will be resolved if the code handles the switching of axis category data properly.

Phil

**Comment by ewels** [comment]
Hi @rfenouil,

Any updates on this old issue? I'm just doing some housecleaning and wondering if I can close it.

Thanks,

Phil

**Comment by rfenouil** [comment]
Hi @ewels,

I am sorry I did not follow up on this issue but I moved on to another project and I did not really find time to come back to it.

I'm sure I'll use MultiQC for future projects and give feedback, but I think you can close this (very specific) issue for now. Thank you again for the great work and support !

**Comment by ewels** [comment]
Sounds good, thanks for getting back to me :)
