### ISSUE TITLE
Fastq_Screen row order

### ISSUE THREAD

**Issue by johnscrn** [ewels/MultiQC#712]
I recently upgraded from multiqc .9 to 1.4.  The FastQ Screen plot is no longer in an expected order. What controls the order and what, if anything, can I do to fix it? Example attached. I would like it ordered by user (the first directory name). 
![fastq_screen-1-2](https://user-images.githubusercontent.com/10601647/37729536-9f532d2e-2d13-11e8-9e89-4a07bc1ddd72.png)

Version .9 had them in the same order as the "General Statistics" table which still orders by directory name.

**Comment by ewels** [comment]
Hi @johnscrn,

This is odd. I would expect the samples to be sorted alphabetically still. I’ll take a look into it.

Phil

**Comment by hassanfa** [comment]
I'm working on this.
