### ISSUE TITLE
Always export plot data to files

### ISSUE THREAD

**Issue by xiekunwhy** [ewels/MultiQC#717]
Hi,
I used MultiQC to create multiple sample fastqc report,  but I can not find the combined text table(NOT those in json file) corresponding to each multi-sample FastQC plot like <Sequence Quality Histograms>, <Per Base Sequence Content>. I need the data table to re-plot them, but I can not find them any where.

Best wishes,
Kun

**Comment by cpavanrun** [comment]
Hi Kun,

I can confirm there is only a single `write_data_file()` call in the FastQC module (which generates the tab-delimited text file for the table only).

One could add a `write_data_file()` for each section that FastQC. However, there might be a reason this was not done in the first place and FastQC is one of the more complex modules. Hence, I'm leaving it for @ewels to answer =P

Cheers,
Chris

**Comment by ewels** [comment]
To do:

- [ ] Always save plot data to files, perhaps in a subdirectory: `multiqc_data/plot_data`
- [ ] Update docs accordingly
- [ ] Make docs about exporting data from reports a little more verbose

**Comment by xiekunwhy** [comment]
Hi both,
Many thanks, I found the datas in multiqc_data when use p parameters, but still missing some useful data like per base ATCG(N) content (corresponding to <Per Base Sequence Content> plot, I need them to draw the plot below, which can show me the A-T, C-G segregation and N content in one plot
![r02 acgtn](https://user-images.githubusercontent.com/17738229/38142449-ebd58964-346e-11e8-851f-a829af156454.png)
).
By the way, "export the data from the HTML report itself" is not convenient to me because I am packaging a re-sequencing data analysis pipeline and multiqc is just a little part.

Thank you two again!
Kun

**Comment by xiekunwhy** [comment]
Done by my self codes, many thanks!
Kun
