### ISSUE TITLE
Error of featureCounts module for paired-end input

### ISSUE THREAD

**Issue by tomsing1** [ewels/MultiQC#72]
The featureCounts module failed with `KeyError: 'Unassigned_FragementLength'` when parsing the following `_counts.txt.summary` file generated by `featureCounts` version `v1.4.6-p5`:

```
Status	EPF1_S19/bams/EPF1_S19.bam
Assigned	16290
Unassigned_Ambiguity	1461
Unassigned_MultiMapping	5753
Unassigned_NoFeatures	2921
Unassigned_Unmapped	1746
Unassigned_MappingQuality	0
Unassigned_FragmentLength	0
Unassigned_Chimera	0
Unassigned_Secondary	0
Unassigned_Nonjunction	0
Unassigned_Duplicate	0
```

Error message:
```
============================================================
Module featureCounts raised an exception: Traceback (most recent call last):
  File "/usr/local/bin/multiqc", line 107, in multiqc
    modules_output.append(mod.MultiqcModule())
  File "/usr/local/lib/python2.7/dist-packages/multiqc/featureCounts/__init__.py", line 55, in __init__
    self.intro += self.featureCounts_chart()
  File "/usr/local/lib/python2.7/dist-packages/multiqc/featureCounts/__init__.py", line 114, in featureCounts_chart
    return self.plot_bargraph(self.featurecounts_data, keys, config)
  File "/usr/local/lib/python2.7/dist-packages/multiqc/__init__.py", line 244, in plot_bargraph
    thisdata.append(d[s][c])
KeyError: 'Unassigned_FragementLength'
============================================================
```

**Comment by tomsing1** [comment]
It seems there is a typo in the featureCounts module:

```
'Unassigned_FragementLength': r"Unassigned_FragementLength\s+(\d+)"
```

should read 
```
'Unassigned_FragmentLength': r"Unassigned_FragmentLength\s+(\d+)"
```
(removed extra `e` in both instances of FragmentLength)

**Comment by ewels** [comment]
Great spot! Thanks for reporting. Not sure why that didn't trigger an error with my test data..

**Comment by ewels** [comment]
Hah, ok - my log files [do have that typo](https://github.com/ewels/MultiQC_TestData/blob/master/data/SRR1067503_1_trimmed_star_aligned.bam_counts.txt.summary#L8)! So I must have copied and pasted it from there. I guess that an update to featureCounts may have corrected that.

I've pushed a second change that allows the typo (https://github.com/ewels/MultiQC/commit/128c4ca3161e12badae0094c21d1fceb17379915), so it should work with both now.
