### ISSUE TITLE
Modules are stealing files from each other.

### ISSUE THREAD

**Issue by cpavanrun** [ewels/MultiQC#724]
I developed a new Picard extension (ValidateSamFile; PR to follow). When I did a practical test and switched from `multiqc -m picard` call to `multiqc` (all modules). My test files where suddenly ignored!

After some investigation I found out that the module `featurecount` *ate* my test files. The search_pattern of `featurecount` is:
```yaml
featurecounts:
    fn: '*.summary'
```
Which is a lack-luster pattern that is too general for ANY module to have and it just so happens to collide with my test files (e.g. 'sample3.one-errors-one-warning.picard.ValidateSamFile.summary'). Grmbl.

However, the point I want to make is not that the featurecounts' search pattern should be changed. No. With new modules being added the odds of these kinds of collions occuring in the future will only increase.

I argue that modules should share the files by default rather than not. And that sharing should only be disabled if the search pattern for a module is thought to be specific enough.

Thoughts?

**Comment by ewels** [comment]
I guess it comes down to how many modules have semi-ambiguous search patterns. But yes, featureCounts should be updated to have `shared: true` at the very least.

The downside of having this as the default / set for many modules is that it will impact the speed of MultiQC. Usually, the file searching step is the stage where I've been able to have most impact on run time. Every time a file is skipped like this we recoup large savings, especially if it hasn't had to have its file contents searched. So changing the default isn't for free (this was the original default behaviour).

Phil

**Comment by cpavanrun** [comment]
On a theoretical level it bugs me that a module is at the mercy of other modules's configuration to even get a look at files bugs me. Independence feels like such fundamental part of having modules.

I understand the point about performance. Perhaps it's, on a practical level, enough to filter out the too global search patterns. I'll create a PR request that sets `shared: true` for some obvious too-global search patterns. 

Brain fart: perhaps, somewhere in the future the `parse_reports()` of a module should be expected to return a list with files it has fully parsed and incorporated into the report. The list could then be used to speed up things by removing the files from a general pool.

**Comment by ewels** [comment]
I like these brain farts / ideas for improvements :)

The modules actually already produce lists of the files that they have successfully parsed - this information is saved in `multiqc_data/` (maybe called `multiqc_files.txt` perhaps?). However, the searching and running modules is currently in two separate phases, so this would have to be refactored. This is a huge job and would affect (that is, break) a tonne of stuff.
