### ISSUE TITLE
Required Version of matplotlib

### ISSUE THREAD

**Issue by finswimmer** [ewels/MultiQC#725]
Hello,

as a required dependency for multiqc matplotlib must have version <=2.1.0 Is this still correct or does newer version work either?

fin swimmer

**Comment by ewels** [comment]
Hi @finswimmer,

It looks like it should be - see the bug report here: https://github.com/matplotlib/matplotlib/issues/10784

I haven't tried the latest versions of MatPlotLib yet, but I'll remove the dependency and we can see if the tests fail again!

Phil
