### ISSUE TITLE
bcl2fastq module fails when some samples have zero reads.

### ISSUE THREAD

**Issue by PaulAONeill** [ewels/MultiQC#731]
**Description of bug:**

 multiqc : Oops! The 'bcl2fastq' MultiQC module broke...

bcl2fastq module fails when some samples have zero reads.
In a run with 384 samples 4 have 0 reads assigned.  
bcl2fastq module throws a `ZeroDivisionError: float division by zero`  

manually removing those samples with `--ignore-samples` avoids the error.

thanks

**MultiQC Error log:**
```
multiqc --outdir x .
[INFO   ]         multiqc : This is MultiQC v1.5
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
Searching 770 files..  [####################################]  100%
[ERROR  ]         multiqc : Oops! The 'bcl2fastq' MultiQC module broke...
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues
  If possible, please include a log file that triggers the error - the last file found was:
    ./Stats/Stats.json
============================================================
Module bcl2fastq raised an exception: Traceback (most recent call last):
  File "/bioseqfs/home/sequencing/opt/miniconda2/envs/sequencing/bin/multiqc", line 442, in multiqc
    output = mod()
  File "/bioseqfs/home/sequencing/opt/miniconda2/envs/sequencing/lib/python2.7/site-packages/multiqc/modules/bcl2fastq/bcl2fastq.py", line 44, in __init__
    self.add_general_stats()
  File "/bioseqfs/home/sequencing/opt/miniconda2/envs/sequencing/lib/python2.7/site-packages/multiqc/modules/bcl2fastq/bcl2fastq.py", line 275, in add_general_stats
    } for key in self.bcl2fastq_bysample.keys()
  File "/bioseqfs/home/sequencing/opt/miniconda2/envs/sequencing/lib/python2.7/site-packages/multiqc/modules/bcl2fastq/bcl2fastq.py", line 275, in <dictcomp>
    } for key in self.bcl2fastq_bysample.keys()
ZeroDivisionError: float division by zero
============================================================
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
```

* **File that triggers the error:**
Stats.json:
[Stats.zip](https://github.com/ewels/MultiQC/files/1914986/Stats.zip)

* **Command used to run MultiQC**
    * `multiqc --outdir multiqc .`  
Removing the samples with 0 reads fixed the problem.
    * `multiqc --outdir multiqc . --ignore-samples 2695_3_PA8 --ignore-samples 2695_3_PC8 --ignore-samples 2695_3_PD5 --ignore-samples 2695_pcrBLANK2`  

* **MultiQC Version:**
    * multiqc, version 1.5
* **Operating System:**
    * CentOS Linux release 7.4.1708 (Core)
* **Python Version:**
    * Python 2.7.14 :: Anaconda, Inc.
* **Method of MultiQC installation:**
    * conda

**Comment by ewels** [comment]
Thanks for the detailed bug report and test data! Now fixed in the development version 👍 

Let me know if you run into any others..

**Comment by PaulAONeill** [comment]
Thanks Phil,

great program and what a turnround on the bug!

Paul

**Comment by ewels** [comment]
Thanks! No problem - detailed bug reports make all the difference 😀
