### ISSUE TITLE
bowtie2 module runs for bismark analyses

### ISSUE THREAD

**Issue by avilella** [ewels/MultiQC#74]
The bowtie2 reports parse entries containing `reads; of these:`

But it only parses it once, giving a discordance between the bowtie2 alignment rates and the bismark alignment rates. E.g. below, in MultiQC shows the bowtie2 rates in the thirties range, and the bismark rates in the seventies range.

Not saying it's wrong, but it confuses people to see one log reporting alignment rates around 35% and the other showing around 70%...

```
16415504 reads; of these:
  16415504 (100.00%) were paired; of these:
    10294839 (62.71%) aligned concordantly 0 times
    5594600 (34.08%) aligned concordantly exactly 1 time
    526065 (3.20%) aligned concordantly >1 times
37.29% overall alignment rate
16415504 reads; of these:
  16415504 (100.00%) were paired; of these:
    10174324 (61.98%) aligned concordantly 0 times
    5676554 (34.58%) aligned concordantly exactly 1 time
    564626 (3.44%) aligned concordantly >1 times
38.02% overall alignment rate
Processed 16415504 sequences in total


Successfully deleted the temporary files CEG12-15-20_S4_L004_R1_001.cutB.fq.gz_C_to_T.fastq and CEG12-15-20_S4_L004_R2_001.cutB.fq.gz_G_to_A.fastq

Final Alignment report
======================
Sequence pairs analysed in total:       16415504
Number of paired-end alignments with a unique best hit: 11163058
Mapping efficiency:     68.0%

Sequence pairs with no alignments under any condition:  4649458
Sequence pairs did not map uniquely:    602988
Sequence pairs which were discarded because genomic sequence could not be extracted:    4

Number of sequence pairs with unique best (first) alignment came from the bowtie output:
CT/GA/CT:       5528557 ((converted) top strand)
GA/CT/CT:       0       (complementary to (converted) top strand)
GA/CT/GA:       0       (complementary to (converted) bottom strand)
CT/GA/GA:       5634497 ((converted) bottom strand)

Number of alignments to (merely theoretical) complementary strands being rejected in total:     0
```

**Comment by ewels** [comment]
Yeah, generally having bowtie results mixed into bismark output is confusing I think. I added [these lines](https://github.com/ewels/MultiQC/blob/master/multiqc/modules/bowtie2/bowtie2.py#L55-L56) to try to skip bowtie when it's a bismark log.

Is that not working when you run the bismark module?

**Comment by avilella** [comment]
Should those lines be prompted by bismark?

They aren't in my logs, and I can't find them in the bismark code:

```
[bismark_v0.14.5]$ grep 'for aligning with bismark' * -Rin
```

**Comment by ewels** [comment]
Damn, you're right - looks like [clusterflow writes these lines](https://github.com/ewels/clusterflow/blob/master/modules/bismark_align.cfmod.pl#L105-L116).

Does your bismark output mention anywhere whether it's using bowtie for alignment? Or maybe I can just search for the word `bismark` instead.

**Comment by avilella** [comment]
Ah, I see what you mean... Hmmm, not sure what would be the best way, maybe
try to find this line?

```
Now starting a Bowtie 2 paired-end alignment for
```

**Comment by ewels** [comment]
Hmm, I don't have that line in my single-end test data log file :)

I think maybe just look for the word `/bismark/i`? I can't see why that would ever come up in a bowtie alignment log that wasn't running bismark..?

**Comment by avilella** [comment]
That sounds wise...

**Comment by ewels** [comment]
Done - not case sensitive but hopefully should work anyway.
