### ISSUE TITLE
Module request: Longranger

### ISSUE THREAD

**Issue by remiolsen** [ewels/MultiQC#740]
Related to #413 . This one is more specific for Longranger (version >= 2.2) and writing a module for the WGS sub-pipeline. I will also take a look at the exome ("targeted") pipeline, but I am missing example data. 

* **Name of tool:**
    * Longranger wgs (targeted?)
* **Tool description:**
    * "A set of analysis pipelines that perform sample demultiplexing, barcode processing, alignment, quality control, variant calling, phasing, and structural variant calling."
* **Tool homepage:**
    * https://www.10xgenomics.com/
* **Log filename pattern:**
    * `summary.csv`
* **Most interesting data for General Stats table:**
    * molecule_length,number_reads,mean_depth,phaseblock_n50

**Comment by remiolsen** [comment]
Example data. I am starting work on this @ewels 

[P5357_1006_grch38_gatk.zip](https://github.com/ewels/MultiQC/files/1938008/P5357_1006_grch38_gatk.zip)

**Comment by ewels** [comment]
Added test data to the MultiQC_TestData repository 👍
