### ISSUE TITLE
Apply color in sample selection in Toolbox not using the correct color

### ISSUE THREAD

**Issue by kjellp** [ewels/MultiQC#742]
**Description of bug:**
I wanted to change the colors of the selected sample lines in FastQC: Adapter content. But discovered that the desired colors were not applied when following this procedure:
1) Changing the color in the Toolbox user interface (highlight section)
2) then selecting the samples to highlight in the color coded Samples summary behind the "Adapter Content" header, using "Highlight these samples" in the context menu of 2 failed samples
The samples were highlighted, but seems to be using the color pre-selected in the toolbox UI before changing it in step 1).

**MultiQC Error log:**
nothing relevant

* **File that triggers the error:**
    * http://multiqc.info/SBW/data/basic_RNAseq.tar.gz
* **Command used to run MultiQC**
    * `multiqc basic_RNAseq`
* **MultiQC Version:**
    * MultiQC v1.5
* **Operating System:**
    * Xubuntu 14.04
* **Python Version:**
    * Python 2.7.12
* **Method of MultiQC installation:**
    * pip

**Comment by ewels** [comment]
I've finally come to fixing this issue! After a quick bit of digging, I realise that this is a FastQC specific request - from this dialogue only:
![image](https://user-images.githubusercontent.com/465550/69193707-ae0dee00-0b27-11ea-97fe-104da63867af.png)

And as you say, this highlight feature does not respect the colour that has been chosen in the toolbox.

**Comment by ewels** [comment]
Ok, only a tiny change for the fix, but now done. Sorry that it took me over a year!
