### ISSUE TITLE
flags combo for faster multiqc on large dataset

### ISSUE THREAD

**Issue by avilella** [ewels/MultiQC#748]
This is a feature/parameters request: I have a large folder with lots of log files associated with about 200 samples and running multiqc with the options above is too slow.

The instance where we are running this can have between 4-36 CPUs, and we want to get a multiqc html report with the results. Are there any flags that can be used to speed up processing?

**Comment by ewels** [comment]
Hi @avilella,

Sure - unfortunately MultiQC doesn't have any support for parallelisation, so the extra cores won't help. But there are a few flags which should help:

* `-m, --module [module name]` - Use only this module. Can specify multiple times.
   * So if you know that you're only reporting on FastQC and STAR, do `multiqc -m fastqc -m star data/`
* `--tag TEXT` - Use only modules which tagged with this keyword, eg. RNA
    * This is essentially shorthand for the above, where different modules have been given keywords to bunch them together. Use `--view-tags` to see what they are.
* `-x, --ignore TEXT` - Ignore analysis files (glob expression)
    * If there are a lot of files that you know aren't useful for the MultiQC run, tell it not to bother looking at them.

Using the above flags wisely can hugely reduce the amount of searching and parsing that MultiQC has to do, and speed up execution significantly.

I hope this helps!

Phil
