### ISSUE TITLE
Module request: CellRanger VDJ

### ISSUE THREAD

**Issue by santiagorevale** [ewels/MultiQC#752]
Related to #413.

* **Name of tool:**
    * CellRanger VDJ (from 10X Genomics)
* **Tool description:**
    * "The Chromium Single Cell Immune Profiling Solution is a comprehensive, scalable tool for profiling full-length paired V(D)J transcripts from hundreds to millions of lymphocytes. The new solution enables assembly of full-length V(D)J sequences on a cell-by-cell basis, providing high resolution insights into the adaptive immune system."
* **Tool homepage:**
    * https://support.10xgenomics.com/single-cell-vdj/software/overview/welcome
* **Complete log file output:**
    * Attached file [web_summary.TCR.html.gz](https://github.com/ewels/MultiQC/files/1971170/web_summary.TCR.html.gz). GZipped only for uploading. This file has some specific metrics for T-Cells.
    * Attached file [web_summary.BCR.html.gz](https://github.com/ewels/MultiQC/files/1971172/web_summary.BCR.html.gz). GZipped only for uploading. This file has some specific metrics for B-Cells.
* **Log filename pattern:**
    * `web_summary.html`
       The only way of distinguishing between a T-Cell and B-Cell report is by checking for the presence of specifics fields, like _Reads Mapped to TRB_ for T-Cells and _Reads Mapped to IGH_ for B-Cells.
* **Most interesting data for General Stats table:**
    * Most of the data on the _Summary_ tab
* **Data suitable for MultiQC plot(s):**
    * From _Summary_ tab:
        * _Knee_ plot (Barcodes vs UMI counts)
        * Mapping data could be somehow turned into a stacked column plot
    * From _Analysis_ tab:
        * Maybe there's a way for aggregating the data for the _Top 10 Clonotype Frequencies_ plot?

**Comment by ewels** [comment]
Thanks! As with #751, the HTML is a last resort..

**Comment by santiagorevale** [comment]
Hi Phil,

Similar reply as in #751. I'm also attaching the CSV file from 10X for the General Metrics. Again, the interesting data for _plotting_ is in the HTML file.

* **Complete log file output:**
    Here are the metrics text files for the previous HTML reports, also provided by 10X. I renamed them from CSV to TXT to be able to uploaded them here.
    * [metrics_summary.TCR.txt](https://github.com/ewels/MultiQC/files/1984120/metrics_summary.TCR.txt). This file has some specific metrics for T-Cells.
    * [metrics_summary.BCR.txt](https://github.com/ewels/MultiQC/files/1984119/metrics_summary.BCR.txt). This file has some specific metrics for B-Cells.
    * Some more examples can be downloaded from 10X website [here](https://support.10xgenomics.com/single-cell-vdj/datasets)
* **Log filename pattern:**
    The only way of distinguishing between a T-Cell and B-Cell report (in both files) is by checking for the presence of specifics fields, like Reads Mapped to TRB for T-Cells and Reads Mapped to IGH for B-Cells.
    * `metrics_summary.csv`
    * `web_summary.html`
* **Most interesting data for General Stats table:**
    * Most data from `metrics_summary.csv`.
* **Data suitable for MultiQC plot(s):**
    * From `metrics_summary.csv`:
        * Mapping data could be somehow turned into a stacked column plot
    * From `web_summary.html`:
        * From Summary tab:
            * Knee plot (Barcodes vs UMI counts)
        * From Analysis tab:
            * Maybe there's a way for aggregating the data for the Top 10 Clonotype Frequencies plot?

**Comment by ewels** [comment]
Finally added in #1689 and #1821! 🎉  Thanks @edg1983!
