### ISSUE TITLE
Adding database functionality?

### ISSUE THREAD

**Issue by santiagorevale** [ewels/MultiQC#756]
Hi Phil,

I'm not entirely sure, but I seem to remember reading it somewhere or having heard it from someone that you were working on adding to MultiQC a database functionality, is that so? Or maybe it's a parallel project you are working on, a metrics database? Because it would amazing to be able to collect the metrics from several projects and then be able to query/retrieve them. Even better, to be able to aggregate their metrics, etc.

Please, let me know what you think about this and if it would be feasible or not.

Keep up with the good work!

Cheers,
Santiago

**Comment by ewels** [comment]
You are correct! It's called MegaQC, it's a parallel project: https://github.com/ewels/MegaQC

Please note that it's very much in beta at the moment and not at all stable code. There are now several groups interested in working with it though, so hopefully we'll be able to work towards a first release in the not-too-distant future.

Phil
