### ISSUE TITLE
New feature request: Conditional formatting for whole tables

### ISSUE THREAD

**Issue by RoxaneLS** [ewels/MultiQC#761]
Hi Phil,
as discussed on Gitter, just requesting a new feature to allow for conditional formatting at the **table level** (instead of per-column).

More specifically, I would like to have all values greater than X in my custom table highlighted in red (which I can do per-column using the `table_cond_formatting_rules` in the config file). However in my use case, the column names will be different for every new run, so I can't use that.

From our chat:
> _Phil:_
> Conditional formatting for whole table - I don’t think that this is possible currently.. Will need to add it as a new feature.
> Should be doable - just need a special case “column name” (eg. `all_columns`)

Thanks a lot in advance!
Roxane

**Comment by ewels** [comment]
I did it again! Suggested a feature that I have already written. And even with exactly the same config name 🤣 At least I'm consistent!

This feature already exists - just specify `all_columns` instead of a column key. See the docs: http://multiqc.info/docs/#conditional-formatting

> Rules can be applied to every table column, or to specific columns only, using that column's unique ID.
> To have matches for a specific column, use that column's ID instead of `all_columns`.

**Comment by RoxaneLS** [comment]
ahah Ok, so yes sorry I should have clarified. I did see that, but then it applies the formatting to ALL columns in the report - which is not good either. I need to be able to specify all_columns in that_table.

```
table_cond_formatting_rules:
    all_columns:
        pass:
            - s_eq: 'pass'
            - s_eq: 'true'
        warn:
            - s_eq: 'warn'
            - s_eq: 'unknown'
        fail:
            - s_eq: 'fail'
            - s_eq: 'false'
```

For instance, I'd need something like that:
```
table_cond_formatting_rules:
    **my_table_X**:
        all_columns:
            pass:
                - lt: 0.5
            warn:
                 - gt: 6
             fail:
                 - gt: 8
```

**Comment by ewels** [comment]
Thanks for the clarification! I’ll take a look. Should be possible to specify just the table ID - they should be unique so MultiQC can check the column IDs first then the table IDs I think..

**Comment by RoxaneLS** [comment]
Cool. I leave it with you!

2018-05-21 14:37 GMT+10:00 Phil Ewels <notifications@github.com>:

**Comment by ewels** [comment]
@RoxaneLS it's finally done! Sorry that it took... 3 years, 5 months and 25 days!!

What's worse is that in the end it only took [a few keystrokes](https://github.com/ewels/MultiQC/commit/575f39a58bd037c98209fd224d09bc86ed1c3144#diff-e0dbf56121deccef096a816c2a757b4b62b95e7c668f816b08da84deba88d4c8R203): `, table_id` 😆 

Hopefully it'll still be useful, and thanks @ErikDanielsson for taking a look at this even though I didn't use your PR.

**Comment by ewels** [comment]
Updated docs: https://multiqc.info/docs/#conditional-formatting

**Comment by RoxaneLS** [comment]
Ah! Better late than never ;)  Thanks!

Le mer. 10 nov. 2021 à 20:27, Phil Ewels ***@***.***> a
écrit :
