### ISSUE TITLE
Label Bowtie2 module as "Bowtie2 / HiSAT2"

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#765]
The old style log output from HiSAT2 is identical to that from Bowtie 2. So, if not run with the appropriate command line flags, that's what it shows up as in MultiQC reports.

For clarity, the module header should be labelled as `Bowtie 2 / HiSAT 2` with some `description` and `helptext` to explain.

From https://github.com/ewels/MultiQC/issues/221#issuecomment-384932596

**Comment by marcos-lozalva** [comment]
Hi Phil,

Firstly thank you for this great tool, please I have an issue regarding my .summary output files from HISAT2, they're not recognized by MultiQC, I show you an example of this files,
Total_fragments	62736799
Mapped_fragments	61845090
Uniquely_mapped_fragments	55601438
Multi_mapping_fragments	6243652
Unmapped_fragments	891709
Properly_paired_fragments	52083870
Singleton_fragments	2908999
More_than_one_chr_fragments	2255641
Unexpected_strandness_fragments	113039
Unexpected_template_length	4402557
Inversed_mapping	80984
Indels	504889

Please can you help me?

Thank you

Marcos

**Comment by ewels** [comment]
Hi @marcos-lozalva - I've moved your question to a new issue. Please see #1036
