### ISSUE TITLE
Picard WGS Coverage Counts Histogram

### ISSUE THREAD

**Issue by julien-kann** [ewels/MultiQC#766]
The Picard WGS Coverage "Counts Histogram" doesn't seem to work. This is using the test data from his git. 

![image](https://user-images.githubusercontent.com/17205894/40500795-ea6e9b46-5f53-11e8-9c10-ed1686f02c93.png)

![image](https://user-images.githubusercontent.com/17205894/40500818-fd2a258e-5f53-11e8-9ef8-3b2270b97c86.png)

**Comment by julien-kann** [comment]
Ignore the genecards screen, still getting used to using two monitors. Forgot that both would be included in screenshot.

**Comment by cpavanrun** [comment]
I can add that this also seems to not work in:
- v1.4
- v1.6dev (near latest)

**Comment by cpavanrun** [comment]
`'ymax': 100,` on line 168 in picard/WgsMetrics.py is not being overwritten by the `ymax` in:
```python
'data_labels': [
                    {'name': 'Percentage Drop-Off', 'ylab': 'Percentage of Bases', 'ymax': 100},
                    {'name': 'Counts Histogram', 'ylab': 'Coverage', 'ymax': maxval}
                ]
```

The simple solution is to remove `'ymax': 100,` from the top dict. However, I ran into a similar problem before and want to delve deeper into WHY it isn't overwritten... will follow up.
