### ISSUE TITLE
no output on a fastq file

### ISSUE THREAD

**Issue by dcopetti** [ewels/MultiQC#767]
**Description of bug:**
I don't get any output. A colleague was able to run it from his own profile and Bioconda/Multiqc installation.
Thanks,

Dario

**MultiQC Error log:**
```
[INFO   ]         multiqc : This is MultiQC v1.5
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching 'PE460/'
Searching 2 files..  [####################################]  100%
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
[copettid@kp141-242 ncbi]$ ls -lrth PE460/
total 118G
-rw-r--r-- 1 copettid mpb 59G May 24 17:20 Species_SG470bp_CGATGT_L00M_R2_001.fastq.gz
-rw-r--r-- 1 copettid mpb 59G May 24 17:41 Species_SG470bp_CGATGT_L00M_R1_001.fastq.gz
```

* **File that triggers the error:**
    * Species_SG470bp_CGATGT_L00M_R2_001.fastq.gz
* **Command used to run MultiQC**
    * `multiqc PE460/`
* **MultiQC Version:**
    * [MultiQC v1.5]
* **Operating System:**
    * [Fedora release 25 (Twenty Five)]
* **Python Version:**
    * [Python 2.7.11]
* **Method of MultiQC installation:**
    * [bioconda]

**Comment by ewels** [comment]
Hi @dcopetti,

MultiQC understands the output from other bioinformatics tools. It doesn't process FastQ files itself. So for example you'll want to run FastQC or samtools or one of the 61 other supported tools first.

Please have a look at the website and documentation for more information: http://multiqc.info/

Let me know if you have any questions,

Phil

**Comment by dcopetti** [comment]
ah, now it makes sense!
Thanks Phil,

Dario

**Comment by ewels** [comment]
No problem! 😄👍
