### ISSUE TITLE
Sample name variation

### ISSUE THREAD

**Issue by tsnowlan** [ewels/MultiQC#772]
Is there a reason for using `s_name` with `pair_orientation` as the output sample key in [picard.InsertSizeMetrics](https://github.com/ewels/MultiQC/blob/df89937e037ac1e895f10ea51f4821aa4a3576cf/multiqc/modules/picard/InsertSizeMetrics.py#L63-L81)?

We're ending up with double sample counts in MegaQC after importing picard runs: the bulk of the data using `s_name`, and separate samples for this module named `"{}_FR".format(s_name)`.

**Comment by ewels** [comment]
Sure - those data points are not sample specific, but read specific. So it's not accurate to label them just as the sample.

This isn't the only case - there are lots of modules that manipulate sample names. They are certainly not an accurate science, often they will get different names from different modules too, so the total sample count in MegaQC is not necessarily useful for counting samples...!

**Comment by tsnowlan** [comment]
I figured something along those lines.

More of a MegaQC question then, is there much utility altering the data loading mechanism to map the variations to a canonical `sample_name` that is the same throughout? Not necessarily just for accurate counts, but for tracking a sample across modules / reports.

**Comment by tsnowlan** [comment]
Just trying to figure out how all the data is flowing through and how we can minimize the noise in it, ideally in an automated manner. I agree though, this would be a bit a of stretch. The common substring is likely to be the best method, and certainly the most feasible to implement. Could probably try form some magic with [difflib](https://docs.python.org/3/library/difflib.html#difflib.SequenceMatcher.find_longest_match), but don't think the gain would be very significant relative to the time sink.

All set here. :+1:
