### ISSUE TITLE
Help with input folders with spaces in the folder name

### ISSUE THREAD

**Issue by r0sies** [ewels/MultiQC#774]
Hi,
I was wondering how to input folders with spaces in the name

I have tried `"folder name"` and `folder\ name` but receive:
```
Invalid value for "analysis_dir": Path "/project/run2/folder\" does not exist.
```

Thanks!

**Comment by cpavanrun** [comment]
Using Bash this works for me:
`multiqc /tmp/run2\ folder`
and also this:
`multiqc "/tmp/run2 folder"`

Are you 100% sure you did not misstyped something? ;-)

What happends if you create a space-containing directory and then try to have multiqc run over it:
```bash
mkdir "/tmp/foo bar"
multiqc "/tmp/foo bar"
```

A possible but very rare caveat: some filesystems handle spaces in filenames differently. This can be a problem if you cross filesystem boundaries (_e.g._ `/` is one filesystem but `projects` is a symlink to another filesystem.)

**Comment by ewels** [comment]
As @cpavanrun - I've not had problems with this before. What operating system are you using? Does the file path auto-expand with tab when you type it for the MultiQC command?

**Comment by r0sies** [comment]
Hi @cpavanrun, @ewels,
Thanks for the quick reply.

Yes, you are right. It works directly in bash.
When I embed the command as part of a script using variables, it doesn't seem to work.

e.g. for two folders: "m chimera" and "neg_control"

```
ls
m chimera neg_control

samples=$(ls)
multiqc $samples

```


```
Usage: multiqc [OPTIONS] <analysis directory>
Error: Invalid value for "analysis_dir": Path "M" does not exist.
This is MultiQC v1.5
For more help, run 'multiqc --help' or visit http://multiqc.info

```

**Comment by cpavanrun** [comment]
To fix it replace:
`multiqc $samples`
with
`multiqc "$samples"`

And consider this your welcome to the wonderfull world of filenames with spaces and shell scripts =).

However, I recommend avoiding using `ls` to generate a list of files to use within a shell script. I think it is better to either use `find . -exec multiqc {} +;` or in this case just do `multiqc .` to have multiqc search the current directory.

**Comment by r0sies** [comment]
Fantastic thanks! I didn't realise the ```multiqc .``` was recursive!

**Comment by ewels** [comment]
Aha! Yes, nothing special required 😉 

For any future googlers, there's also the `--file-list` option, where MultiQC can take a text file of input paths to use. This was developed for bcbio (I think? or galaxy?) where recursive searching isn't possible and one has to manually specify a very large number of file paths.

Glad you got it working @r0sies and thanks for the help @cpavanrun!
