### ISSUE TITLE
Per Base Sequence Content not clickable with MultiQC_NGI plugin

### ISSUE THREAD

**Issue by Hammarn** [ewels/MultiQC#776]
The `Per Base Sequence Content` plot is normaly clickable - you get to see the indivdual orignal graphs that the table is based on.
If the report was generated with the NGI plugin and you have selected the user supplied names instead of the NGI names then you can't click into to plot anymore.

Problem description and possible solution from @ewels here:

Relevant code [here](https://github.com/ewels/MultiQC/blob/2d873203de31dbfe3ff0bfc3852c040937a4b212/multiqc/modules/fastqc/assets/js/multiqc_fastqc.js#L309)

```
The sample names aren't updated when things are renamed in the report.
So it can't reference the underlying data
We probably need to add another listener that fills a new variable that is basically a lookup table to go from old name to new name. 
That listener should fire whenever there's a change in renaming
```

**Comment by ewels** [comment]
Dup of #777
