### ISSUE TITLE
MultiQC not running on Windows

### ISSUE THREAD

**Issue by mackellardrew** [ewels/MultiQC#783]
Hey Phil,

I'm trying to use MultiQC to help wrap some FastQC results on some NGS reads in a Jupyter notebook.  
Maybe I missed something very simple (like there is no Windows support for this tool), but I can't get MultiQC to run.  I'll try to fit the info to the template below, but I'll also add more detail here.  I tried installing multiqc both via pip and from git-cloning; doing so makes the simple `multiqc .` work to parse the FastQC data on my Mac, but not on PC.

I'm aware that either installation method won't automatically add the script to the Windows path, but even specifying the absolute path to the multiqc script and running `python C:\the_whole_path\multiqc` (with or without the trailing period to indicate the current dir that contains the fastqc data) returns an error:

```python
Traceback (most recent call last):
  File "multiqc", line 89, in <module>
    callback = util_functions.view_all_tags,
AttributeError: module 'multiqc.utils.util_functions' has no attribute 'view_all_tags'
```

I'm familiar enough with Python to see that the `util_functions.py` does indeed have the indicated function, and it's being added via a decorator to give the script the desired command-line interface behavior with the arg `--view_tags`, but accessing multiqc via Python directly on Windows seems not to be working (for me, anyways).  I get that you went through a lot of trouble to make multiqc command-line-native (instead of being run as an explicit Python module); am I overthinking this?

Thanks,
Drew

**Description of bug:**
Can't start multiqc: `multiqc .` doesn't work on Windows.  `python multiqc` doesn't either.
* **Command used to run MultiQC**
    * `multiqc .`; 'python multiqc'
* **MultiQC Version:**
    * I believe it's v1.6dev
* **Operating System:**
    * Microsoft Windows Version 10.0.17134 Build 17134
* **Python Version:**
    * Python 3.6.5 :: Anaconda custom (64-bit)
* **Method of MultiQC installation:**
    * pip, manual

**Comment by ewels** [comment]
Hi @mackellardrew,

Sorry you're having problems. MultiQC _should_ work on Windows - I have automated CI tests set up with AppVeyor which tests it there. It may be helpful to take a look at the AppVeyor config file: https://github.com/ewels/MultiQC/blob/master/appveyor.yml (it's a bit messy sorry).

Anyway, the error indicates that the Python module system doesn't think that MultiQC is installed. This could be down to several reasons, but is most likely that the Python version you're running is not the same one that you're installing MultiQC with. I'd recommend using [Miniconda](https://conda.io/miniconda.html) if possible, I often find this fixes most installation problems for people.

Note that using MultiQC within Jupyter notebooks is something I've been thinking about for ages, but not really something that I have tried. As you say - MultiQC is predominantly a command line tool, but I guess it should be possible (though not necessarily simple) to use the functions within in a more interactive manner; for example, to generate a single plot. But I suspect that this will require some more work to get it to work nicely.

Phil

**Comment by mackellardrew** [comment]
Hmm... Thanks for getting back to me quickly.  The issue isn't with mismatched python versions installing and running multiqc; I'm using a personal computer that only has one version of Python (3.6).

I do have Anaconda, but the bioconda repo [appears to lack a Windows version for multiqc](https://anaconda.org/bioconda/multiqc).  Running `conda install -c bioconda multiqc` returns a `PackagesNotFoundError`.  Any other ideas?

I tried stepping through the individual lines of code in your appveyor example script, in case some dependency was out of whack on my system, but I can't find the actual \scripts\multiqc file in the MultiQC_Testdata-master archive downloaded on line 32 from that test, which is puzzling.  It's clear that the test worked on the site on which you ran it, however.

Yeah, it would be nice to have the functionality to call multiqc from within Jupyter directly, but I'm fine running it with the `subprocess` module, and importing the data, if only I can get the package to run.

**Comment by ewels** [comment]
Yeah, bioconda doesn’t have support for windows, so you’ll need to set up conda then install MultiQC manually, or perhaps use `pip`.

The `MultiQC` file isn’t in the TestData repo, it’s in the main repo. Both are downloaded in that script though which can be confusing (the main repo is automatically there as that’s what the CI is triggered with).

**Comment by mackellardrew** [comment]
Sorry, I'm still confused.  Like I said, I've tried both the pip install and git clone approaches to getting MultiQC, and they both yield the same error when calling Python directly on the \scripts\multiqc file.  I thought that you when you suggested using Miniconda you meant to try `conda install -c bioconda multiqc` on my PC.  If Bioconda doesn't support Windows, did you mean that Miniconda could be of help in some other way?

For your second paragraph, I take it that you mean that the `appveyor.yml` file is actually run by copying the entire repo to your Appveyor instance, and then running the test `appveyor.yml` script from within it.  That's unfortunate; I was kind of hoping the test script was downloading a different version of the MultiQC code that I could then try in turn, but it appears that me copying the exact same git repo as was successful in your test just doesn't work on my machine.  Perhaps there's something specifically different about my...

**Never mind, I figured it out:** I looked again at the `multiqc` script, noticed that the offending line (#89) was the only instance in that file of a "callback" arg being set that referenced the util_functions file that my local installation can't find, and reasoned that commenting it out might recover functionality.  It does; I can now run multiqc on Windows with this single modification to the script.  I have no idea if this will break anything down the road for me (or if anything else will ultimately come up); I haven't played around yet with the `view-all-tags` option yet, but will continue without it for now.

I'm not sure, but perhaps something is breaking with the decorator-function setting of that arg to preserve the CLI-based nature of the script?  [This post](https://hynek.me/articles/decorators/) mentions some things that might be relevant, but it's just a hunch.  Alternatively, there may be something wonky with my local environment that your wasn't captured by the Appveyor test.  Anyways, I appreciate your responses in helping me track down the problem.

**Comment by ewels** [comment]
> If Bioconda doesn't support Windows, did you mean that Miniconda could be of help in some other way?

Yes sorry, just having an isolated Python environment to install MultiQC and its dependencies into (via pip or manually) can sometimes help.

So with this callback commented out, you're saying that everything works?
https://github.com/ewels/MultiQC/blob/29aa610204ce2de294032f9f223f822ff987229e/scripts/multiqc#L89

Interesting! Is this for all MultiQC commands?

**Comment by mackellardrew** [comment]
Yes.  Commenting out that single line in the multiqc script sufficed to get MultiQC to work on my PC, where previously it would not.  It should've occurred to me to attempt that solution sooner, as the response python gives when attempting to call the script from the command line specifically mentioned that line as the problem; I had just been concerned that, if Python couldn't find the `util_functions` file, commenting out line #89 would just have caused some subsequent part of the script to fail, instead.  But, while I'm unfamiliar with the structure of the rest of your code base, it appears that whatever was problematic about its functioning in my environment was solved by editing that single line.

> Interesting! Is this for all MultiQC commands?

I don't really know.  The exact context in which I'm calling MultiQC up until now is in a Jupyter notebook, with the following lines:

`multiqc = 'python {} .'.format(os.path.join(*[paths['multiqc_dir'], 'scripts', 'multiqc']))
p = subprocess.Popen(multiqc, stdout=subprocess.PIPE, 
                         stderr=subprocess.PIPE, shell=True)
out, err = p.communicate()` 

where `paths['multiqc_dir']` is just a variable storing my local path to the main repo; i.e., I'm using subprocess to run it from the command line with no other arguments.  I haven't tried more complex sets of tags and options, and currently the only reports that I'm using MultiQC to aggregate are generated by FastQC.  If I run into additional issues, I can post them here or in a separate thread, but I would consider this problem solved for me.

FYI, when viewing the resulting report, I tried just using

`from IPython.display import HTML
HTML('path/to/report)`

to view the results inline with the other data, but found that some of the formatting you added to the HTML report to make it easier to navigate conflicts with/overrides some of the Jupyter notebook's formatting, making the result kinda unusable.  Instead I currently use the `webbrowser` package to open the report in a new tab.  This might be something to keep in mind if you do ultimately decide to integrate Jupyter functionality into MultiQC at some point in the future (but, as I said previously, I'm happy enough just to have it working).

**Comment by ewels** [comment]
Ok, nice! Yes if it runs with that command then it should mostly work - I was curious to see if the imports would break elsewhere as you say, but the problem must be specific to the `click` callback handling as you say.

I figured that Jupyter would sanitise the HTML and break some functionality. One alternative would be to use `--export` to save flat image versions of the plots in the `multiqc_data` directory. These could then easily be displayed in Jupyter, but of course are no longer interactive.

Getting interactive plots into Jupyter is harder, but possible. My favourite approach is to switch the plotting library from HighCharts to Plot.ly. That has a nice feature to return a chunk of HTML and JavaScript for stand alone interactive plots (I use this with an API call in [MegaQC](https://github.com/ewels/MegaQC) for example). Unfortunately, switching from HighCharts to Plot.ly is an enormous task.

Anyway, unless you have a suggestion for how to fix this broken behaviour, I'm going to class this problem as an edge-case / one off and close the issue. Thanks for reporting it! Hopefully anyone who runs into it in the future can refer to this issue to find the workaround.

Phil
