### ISSUE TITLE
Point release of current master branch?

### ISSUE THREAD

**Issue by avilella** [ewels/MultiQC#79]
Hi @ewels , would it be possible to make a release of the current master branch?

We have tested it here, and would like to put it in our Data Analysis recommendations.

Cheers

**Comment by ewels** [comment]
Hey @avilella - yes! I ticked off the last issue assigned to v0.3 yesterday in fact, so was planning to release it this week.

I pushed some fairly major changes to the javascript plotting code yesterday (see #78 and #34) so just wanted to get a few people to check it for bugs before I released it. If you could pull and bug test at your end as well that would be welcome!

Cheers,

Phil

**Comment by avilella** [comment]
Tested on a bunch of folders and it does work flawlessly :+1:

**Comment by ewels** [comment]
Nice, thanks!

**Comment by ewels** [comment]
Hi @avilella,

Version 0.3 now released and available on PyPI.

**Comment by avilella** [comment]
Cool! I'll point our Data Analysis document to that version. Thx!

**Comment by ewels** [comment]
Ah crap, I think I might have just found a bug already (FastQC not picking up zip files). I hate releasing stuff! Stay tuned for a v0.3.1!

**Comment by avilella** [comment]
Lol! No worries :-)

**Comment by ewels** [comment]
Ok, v0.3.1 released. I threw in a couple of new bits along with it so that I didn't feel so guilty ;)
