### ISSUE TITLE
Skewer: don't use fixed ymax 100 for percentage plot

### ISSUE THREAD

**Issue by lucacozzuto** [ewels/MultiQC#794]
Plots with percentage should NOT have a fixed of Y limit 100%. It is better to have a variable value depending on the highest value (i.e. like having the function Y-limits off).

A test case could be the Skewer plot.

**Comment by ewels** [comment]
See discussion on Gitter: https://gitter.im/ewels/MultiQC?at=5b45cfab0a17e01fccd719eb

Specifically the Skewer `Read length after trimming` plot:

![screen-shot-2018-07-11-at-11 37 20](https://user-images.githubusercontent.com/465550/42564533-4c60075e-8501-11e8-85d0-a637e325fa9a.png)

![screen-shot-2018-07-11-at-11 37 27](https://user-images.githubusercontent.com/465550/42564528-497d8a5c-8501-11e8-8780-06983091b7fe.png)

Other plots may also need updating in a similar way. Fix is to not specify a fixed `ymax` but instead use `yCeiling` and `yMinRange`

**Comment by vpresnyak** [comment]
I would love to not have a fixed yMax for the FastQC Sequence Duplication Levels plot as well - I'm getting plots that look like this:

![image](https://user-images.githubusercontent.com/36459283/42847669-a8f11c86-89ea-11e8-9e19-2ad21194d7fd.png)

The corresponding plot in FastQC itself looks much more interpretable with a higher y limit.

![image](https://user-images.githubusercontent.com/36459283/42847684-c21ecdb6-89ea-11e8-8074-5650bbb18e7e.png)

**Comment by vpresnyak** [comment]
Working to implement these changes. The simplest solution seems to be simply remove the ymax limit and allow it to adjust to the ymax of the data. Is that an acceptable solution?

**Comment by ewels** [comment]
Hi @vpresnyak,

> I would love to not have a fixed yMax for the FastQC Sequence Duplication Levels plot as well 

This is super weird! I've not seen this before. What version of FastQC are you using? I thought that plot always gave a maximum of 100% - not sure how you can have 2500% duplicate reads?

> Is there a specific reason to use yCeiling and yMinRange here?

Setting `yCeiling` to `100` prevents HighCharts from autoscaling the axis beyond that. So you don't get a percentage axis that goes to 120%.

Setting `yMinRange` prevents the plot from scaling too far - eg. if you have changes of only 0.0001% difference then it could look like a mountain when really it's super insignificant. So I usually set this if I think that a difference of under say 5% is not biologically interesting.

**Comment by vpresnyak** [comment]
Yep, it's a FastQC issue - v0.10 did not scale it the same way. v0.11+ gives a plot normalized to a sum of 100%, which functions appropriately as is

**Comment by ewels** [comment]
Ok - good to know! We could probably test for for totals that are over 100% and then change the axis config accordingly. Wouldn't be very difficult...

**Comment by ewels** [comment]
Fixed and merged in #803
