### ISSUE TITLE
MultiQC is not recognising two folders argument

### ISSUE THREAD

**Issue by TainVelasco-Luquez** [ewels/MultiQC#795]
**Description of bug:**
MultiQC, when two or more folders supplied, is not recognising the `.json` from fastp

**MultiQC Error log:**
```
cat .command.log
[INFO   ]         multiqc : This is MultiQC v1.6.dev0
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
[INFO   ]         multiqc : Only using modules fastqc, fastp
Searching 9 files..
[INFO   ]          fastqc : Found 2 reports
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete
```

**File that triggers the error:**
MultiQC is being used as a step in a Nextflow pipelines that generates two folders with the respective output files from fastp and fastQC ([nextflow_output.tar.gz](https://github.com/ewels/MultiQC/files/2185303/nextflow_output.tar.gz)) to be supplied to multiQC.

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC: `multiqc fastp/ fastQC/`
 - MultiQC Version: MultiQC vv1.6.dev0
 - Operating System: GNU/Linux 4.15.0-24-generic x86_64
 - Python Version:  Python 3.6.5
 - Method of MultiQC installation: pip3

 **Additional context**
When I mix both the fastQC .zip and the fastp .josn reports in the same folder I get what I want: A multiQC report with both reports (see [multiqc_report_same_folder.html.zip](https://github.com/ewels/MultiQC/files/2185379/multiqc_report_same_folder.html.zip)). However, if I specified two directories to search reports in `multiqc fastp/ fastQC/` it seems to recognise only the fastQC reports, thus getting a multiQC report like [multiqc_report_different_folder.html.zip](https://github.com/ewels/MultiQC/files/2185360/multiqc_report_different_folder.html.zip).

The nextflow pipeline is [fastq_test.nf.zip](https://github.com/ewels/MultiQC/files/2185396/fastq_test.nf.zip).

**Comment by ewels** [comment]
Hi @TainVelasco-Luquez,

MultiQC finds fastp files by specifically looking for a filename `fastp.json`. Your nextflow results files however are called `SRR5442949_fastp.json`. As a result, MultiQC ignores it and only processes the FastQC results.

My suspicion is that you were adjusting the output filenames at the same time as the directory structure? I can't test my hypothesis unfortunately as the results files you sent are symlinks and not the actual output from FastQC / fastp.

You _should_ find that if you keep the default fastp filename of just `fastp.json` then it should work again. However, it would make sense for me to change the pattern to match `*fastp.json`, so I'll do that now as well...

Let me know if you make any progress!

Phil

**Comment by ewels** [comment]
Ok, I pushed the change, so if you pull the latest version of MultiQC it should now work. I'll close this issue now, but please let me know if you're still having problems.

Cheers,

Phil

**Comment by TainVelasco-Luquez** [comment]
Hello @ewels !

Thank you again for the quick feedback. 

Your suspicion was right. In the beginning I was using the raw `fastp.json`files, however nextflow complained about conflicting file names, when using more than two different files. So I was forced to add the `sample name_fastp.json`hoping MultiQC were able to recognise the `fastp.json`(that now it does :exclamation: :raised_hands:).

After updating MultiQC I got exactly what I was looking for => [multiqc_report.html.zip](https://github.com/ewels/MultiQC/files/2189670/multiqc_report.html.zip).

Thank you very much for your help.

Cheers,

Tain

**Comment by ewels** [comment]
Great! Thanks for letting me know 👍
