### ISSUE TITLE
Custom content type: image

### ISSUE THREAD

**Issue by lucacozzuto** [ewels/MultiQC#798]
Dear all, I would like to have an easy way to embed single picture inside the report as a custom content. Sometimes is nice to add a dendrogram, an heatmap or the results of the clustering.

I would love to have a file where I can specify the name of the image and some description for the equivalent section.

Thanks

**Comment by ewels** [comment]
It should be possible to implement this as a content type with custom content.

**Comment by ewels** [comment]
I'm pleased to say that MultiQC now support images through custom content! See https://multiqc.info/docs/#images

> As of MultiQC v1.7, you can import custom images into your MultiQC reports.
> Simply add `_mqc` to the end of the filename for `.png`, `.jpg` or `.jpeg` files, for example:
> `my_image_file_mqc.png` or `summmary_diagram.jpeg`.
> 
> Images will be embedded within the HTML file, so will be self contained.
> Note that this means that it's very possible to make the HTML file very very large if abused!
> 
> The report section name and description will be automatically based on the filename.

If you can give it a whirl, that'd be great - it could be a little buggy still...

**Comment by lucacozzuto** [comment]
Best developer ever. :)

**Comment by ewels** [comment]
Sssh, @pditommaso might get jealous! 😆

**Comment by pditommaso** [comment]
Because I always reject @lucacozzuto feature requests 😆

**Comment by stevekm** [comment]
> I'm pleased to say that MultiQC now support images through custom content! See https://multiqc.info/docs/#images
> 
> > As of MultiQC v1.7, you can import custom images into your MultiQC reports.
> > Simply add `_mqc` to the end of the filename for `.png`, `.jpg` or `.jpeg` files, for example:
> > `my_image_file_mqc.png` or `summmary_diagram.jpeg`.
> > Images will be embedded within the HTML file, so will be self contained.
> > Note that this means that it's very possible to make the HTML file very very large if abused!
> > The report section name and description will be automatically based on the filename.
> 
> If you can give it a whirl, that'd be great - it could be a little buggy still...

it seems like this does not work with PDF files?
