### ISSUE TITLE
Add a doesn't match option to toolbox

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#80]
Currently, hiding samples works by matching names. It would be nice to have a "show only these" option, where anything that _doesn't_ match a string is hidden.

**Comment by avilella** [comment]
+1 on this feature. I was just demoing MultiQC to someone who mentioned if
it would be possible to do such highlighting of a subset.

**Comment by ewels** [comment]
Ah ok - negative highlighting is quite easy to do already actually, just leave the search string blank and it will highlight everything. Then use subsequent searches to "de-highlight" stuff.

Previously it would show an error if you entered an empty search string, I've just pushed an update that removes this so that it's allowed.

**Comment by ewels** [comment]
Sorry, missed this issue. Done in 8c2849fdd6879038806d834fd3ef98232af4bad3
