### ISSUE TITLE
License issue between MultiQC and Highcharts

### ISSUE THREAD

**Issue by daissi** [ewels/MultiQC#800]
Hi,

I attempt to package MultiQC for Debian Med but in the state it is not possible because the license of MultiQC (GPL-3.0+) is not compatible with the license of Highcharts (CC BY-NC 3.0).
So, currently MultiQC is not legally distributable. Here [1-3] a small non exhaustive list of similar problem with Highcharts and free software.

There are many other free and compatible replacement for Highcharts, for example Mozilla [1] switched from Highcharts to D3.js (BSD 3-Clause).

It would be great if MultiQC can move to a free replacement.

Best,
Dylan

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=841397
[2] https://github.com/globocom/megadraft-chart-plugin/issues/1
[3] https://github.com/sebastianbergmann/php-code-coverage/issues/192

**Comment by ewels** [comment]
Hi @daissi,

Thanks for this. I'm aware of the licensing issues surrounding HighCharts (indeed, I now avoid using it in other projects for this reason). I would love to switch to plot.ly or another library instead, however it would be a huge task. MultiQC has thousands of lines of custom code tied into HighCharts customisations, and much of the MultiQC module code follows HighCharts syntax. To switch the library would take months and I simply don't have the time for such a project.

Apologies for the inconvenience and for not considering this problem back when I started the project,

Phil

**Comment by tillea** [comment]
Hi,
I wonder in how far it is appropriate to close this issue.  I understood that you do not have time to solve it but the problem persists.  Simply closing the issue will keep away helping hands on one hand and might bring other distributors who might overlook the issue into licensing trouble.  Please simply leave the issue open to document the licensing problem.
Thank you, Andreas.

**Comment by johanneskoester** [comment]
I think a simple solution would be to remove highcharts from assets, and download it on the fly when creating the report. Am I right?
