### ISSUE TITLE
Some concern for users with colourblindness 

### ISSUE THREAD

**Issue by evelii** [ewels/MultiQC#805]
**Is your feature request related to a problem? Please describe.**
Hello. While I am using reports generated by MultiQC, I found that some modules like FastQC use a colour combination of red and green. The colour distinctions might not be obvious enough for users with colourblindness. For example, with the help of a browser extension, here is what a report will be like for people with deuteranomaly (green):
![deuteranomaly green](https://user-images.githubusercontent.com/39169776/43160806-38bd0e2e-8f54-11e8-873b-c0530cb6d293.png)

**Describe the solution you'd like**
Changing green to blue could resolve this issue as the colour distinction will be more clear:
![comparison](https://user-images.githubusercontent.com/39169776/43160947-9c3e341e-8f54-11e8-8eb5-39c49420074b.png). 
If it helps, I wrapped these changes into a commit (for the FastQC module): https://github.com/evelii/MultiQC/commit/183ce04ac28ca53d6f0d61127b0c14075b9b7159

**Additional context**
I was wondering if you'd like these changes to be included into MultiQC.
Please let me know if there is any question.

**Comment by ewels** [comment]
Hi @evelii,

Thanks for reporting this. Whilst I'm certainly sympathetic to people suffering from colour blindness, I have some reservations about changing this. The colours are directly copied from the FastQC reports and I'm not super keen about deviating from that. The similarity helps to identify the plot and I worry that changing the colours would negatively impact this implicit association.

I'm not _super_ bothered about the background colours either, as they're only for help with quick interpretation of the axis and are not encoding any data. So colour blind users aren't missing anything, it's just slightly harder for them to interpret the plot quickly.

Finally, the changes to the heatmap in your commit can't happen I'm afraid. The red-green-blue-black colour scheme is the only method I could think of to encode the four different numeric variables in a single colour. The black is calculated numerically and so isn't something that can be easily changed.

Does this all make sense? Let me know what your thoughts are on this...

Cheers,

Phil

**Comment by evelii** [comment]
Hi @ewels ,

Thanks for the detailed explanations. I am still not very clear why the colour scheme of the heatmap cannot be changed. Chould you please give a further introduction about the "black is calculated numerically"?

Thank you very much.

**Comment by ewels** [comment]
So we have four percentages for the four bases: A, C, T and G. To get a single colour, I use RGB colour space and make use of the fact that the four percentages must sum to 100%.

By making %A into 0-255 red, %C into 0-255 green, %T into 0-255 blue, we get full data representation where:

* pure red `rgb(255,0,0)` = 100% A
* pure green `rgb(0,255,0)` = 100% C
* pure blue `rgb(0,0,255)` = 100% T
* pure black `rgb(0,0,0)` = 100% G

(I can't remember if these associations are correct, this is off the top of my head).

Regular heatmaps encode a single value over a colour range and you can choose what colours to use. But this heatmap encodes four different values so we don't have the same choice. Does that make sense?

**Comment by evelii** [comment]
Yes, it makes sense. I'll keep changes locally then.
Thanks for making these explanations :)
