### ISSUE TITLE
shebang for multiqc not detected correctly

### ISSUE THREAD

**Issue by mh00h** [ewels/MultiQC#813]
**Description of bug:**
The shebang calculated during a pip install is not calculated correctly.

To reproduce this bug, try the following:

- compile Python 3.6.0 from source into a directory
- create a venv using the built in module of the compiled python executable
- activate the new venv
- `pip install multiqc==1.6`
- locate the multiqc direct executable in `/path/to/venv/bin/multiqc`
- observe that the shebang of this file points to `/path/to/compiled/python`, instead of `/path/to/venv/python`
- changing to `/usr/bin/env python` fixes the problem

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC: multiqc
 - MultiQC Version: 1.6
 - Operating System: CentOS 7
 - Python Version: Python 3.6.0
 - Method of MultiQC installation: pip

**Comment by ewels** [comment]
Hi @mh00h,

Thanks for the report - I’m a little confused though, the shebang looks fine in the source code: 
https://github.com/ewels/MultiQC/blob/2ccda53608771d73a3392841d5a44114daed772a/scripts/multiqc#L1

Is this the script that you’re talking about?

Phil

**Comment by ewels** [comment]
After looking into this a bit, I think it's probably a compiled version of the main `multiqc` script. The shebang in this file is not controlled by any code in this repository, and is not something I can affect I'm afraid, so I don't think that there's anything I can do sorry.

If there is, please let me know and I'll reopen the issue!
