### ISSUE TITLE
CLI max_table_rows (snakemake)

### ISSUE THREAD

**Issue by thierryjanssens** [ewels/MultiQC#823]
When using
```
multiqc . --cl_config '{{max_table_rows: 10000}}'
```
in a snakemake rule the workflow stops because of a non-zero exit status, while this is not the case when running it crude on the commandline (with single braces then).

Kind regards,

Thierry

**Comment by ewels** [comment]
Thanks @thierryjanssens - are you able to see the exact compiled command that snakemake runs? Could you please send through the MultiQC (stdout preferably with the `-v` verbose flag).

Thanks,

Phil

**Comment by thierryjanssens** [comment]
Hi @ewels ,

here it is:


multiqc . --cl_config '{max_table_rows: 10000}'

[INFO   ]         multiqc : This is MultiQC v1.6.dev0
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
Searching 39602 files..  [####################################]  100%
[INFO   ]        samtools : Found 1 flagstat reports
[INFO   ]         bowtie2 : Found 7 reports
[ERROR  ]         multiqc : Oops! The 'adapterRemoval' MultiQC module broke...
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues
  If possible, please include a log file that triggers the error - the last file found was:
    ./.snakemake/conda/5030de85/lib/libhdf5.settings
============================================================
Module adapterRemoval raised an exception: Traceback (most recent call last):
  File "/data/anaconda3/envs/PZN/bin/multiqc", line 440, in multiqc
    output = mod()
  File "/data/anaconda3/envs/PZN/lib/python3.6/site-packages/multiqc/modules/adapterRemoval/adapterRemoval.py", line 47, in __init__
    parsed_data = self.parse_settings_file(f)
  File "/data/anaconda3/envs/PZN/lib/python3.6/site-packages/multiqc/modules/adapterRemoval/adapterRemoval.py", line 103, in parse_settings_file
    self.set_result_data(settings_data)
  File "/data/anaconda3/envs/PZN/lib/python3.6/site-packages/multiqc/modules/adapterRemoval/adapterRemoval.py", line 109, in set_result_data
    self.set_ar_type(settings_data['Length distribution'])
KeyError: 'Length distribution'
============================================================
[INFO   ]     trimmomatic : Found 7 logs
[INFO   ]          fastqc : Found 42 reports
[INFO   ]         multiqc : Compressing plot data
[WARNING]         multiqc : Previous MultiQC output found! Adjusting filenames..
[WARNING]         multiqc : Use -f or --force to overwrite existing reports instead
[INFO   ]         multiqc : Report      : multiqc_report_1.html
[INFO   ]         multiqc : Data        : multiqc_data_1
[INFO   ]         multiqc : MultiQC complete
    Error in rule multiqc:
        jobid: 170
        output: PZN/multiQC/multiqc.html
        log: PZN/multiQC/multiqc.log

RuleException:
CalledProcessError in line 262 of /data/path_to/Snakefile:
Command ' set -euo pipefail;  multiqc . --cl_config '{max_table_rows: 10000}' ' returned non-zero exit status 1.
  File "/data/path_to/Snakefile", line 262, in __rule_multiqc
  File "/data/anaconda3/envs/env/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Job failed, going on with independent jobs.
Exiting because a job execution failed. Look above for error message
Complete log: /data/path_to/.snakemake/log/2018-09-03T114830.377193.snakemake.log

**Comment by ewels** [comment]
Ah, this doesn't look like it's related to your command line config, it's the `adapterRemoval` module breaking on an input file.

The suggested file responsible is `./.snakemake/conda/5030de85/lib/libhdf5.settings`, which matches  the [pattern used by the module](https://github.com/ewels/MultiQC/blob/56d2b69a1b68b65b3ff70b4e2b5f87010d80fef2/multiqc/utils/search_patterns.yaml#L5-L8) to find files. I'm not sure what this file is, or if you're running the [Adapter Removal tool](http://multiqc.info/docs/#adapter-removal).

Long term, I should make the module more robust to finding incorrect files without crashing.

Short term, you can probably fix this by using the extra command line parameter `-x adapterRemoval`, to skip this module.

Phil

**Comment by ewels** [comment]
Hi @thierryjanssens,

Great, making progress! This new error is because of a mistake in the snakemake wrapper. The log says that it's looking for a missing file called `path/multiQC/multiqc.html`. The MultiQC log says that it's created `multiqc_report.html`.

You should be able to edit the snakemake rules to expect the correct output file then I guess it'll work.

Phil

**Comment by ewels** [comment]
To be more specific: MultiQC isn't taking a long time / having a long latency - it finishes quickly as normal. But because snakemake is expecting an output file that is never created, it just waits and waits and waits...

**Comment by thierryjanssens** [comment]
Hello ewels,

thank you for your informative help.

The issue is solved now.

Kind regards,

Thierry

**Comment by ewels** [comment]
Ok great! Thanks for letting me know. I've made a new issue to fix the adapterRemoval problem in the longer term (see #824).

Phil
