### ISSUE TITLE
Support for ShortRead package

### ISSUE THREAD

**Issue by chenb14** [ewels/MultiQC#825]
Could you add support for the ShortRead package (https://kasperdanielhansen.github.io/genbioconductor/html/ShortRead.html) and parse the outputs, especially the readOcurrances graphs, to your reports?

**Comment by ewels** [comment]
Hi @chenb14,

I'm afraid that R packages are very difficult to support in MultiQC, as the output is not consistent between users. I'd recommend looking into the [Custom Content](https://multiqc.info/docs/#custom-content) feature of MultiQC as a way to get the plots into your MultiQC reports. This makes it easy to generate output from custom scripts which can be recognised by MultiQC.

If I'm wrong about this tool then please let me know details of the files it produces - file name conventions, example contents and so on and I'll look into it.

Cheers,

Phil

**Comment by chenb14** [comment]
Thanks for your reply, Phil! I will look into the Custom Content feature.

Regards,

Bing
