### ISSUE TITLE
Columns ordering & hiding from custom content not working

### ISSUE THREAD

**Issue by RoxaneLS** [ewels/MultiQC#841]
**Description of bug:**
Hi Phil, I'm having problems with ordering and hiding columns form my custom content tables.

 - Command used to run MultiQC:
    ```
    multiqc . -f -o . -n multiqc_test -c ./multiqc_config.test.yaml 
    ```
 - MultiQC Version: MultiQC v1.6
 - Operating System: on linux
 - Python Version: Python 2.7.5 (default, Jul 13 2018, 13:06:57) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux2
 - Method of MultiQC installation: pip I think

 **Additional context**
 See input & output files and config file attached. 

[for Phil.zip](https://github.com/ewels/MultiQC/files/2448796/for.Phil.zip)

**Comment by RoxaneLS** [comment]
Ok, solved it. I was using the `table_columns_placement` section in my config file, but that actually only works for columns in the General Stats table. 

To order or hide columns in custom made tables, one needs to use the `headers` sub-section in the `custom_data` section. It all makes sense now! :) 

e.g.
 ```
           Clusters Passing Filter:
                description: 'Clsuter passing filter (from bcl2fastq)'
                format: '{:,.2f}'
                group: sequencing_stats
                placement: 900
                hidden: True

```

**Comment by ewels** [comment]
Hi @RoxaneLS,

I figured it out. The `table_columns_placement` config uses the table column _Namespace_, not the Table ID as you were using. In your table, `namespace` wasn't set, so you couldn't access those columns.

I've updated the code to look for namespace first and then table ID, so your example code does now work as expected. I've also added a little to the docs explaining this.

Cheers,

Phil
