### ISSUE TITLE
featureCounts: Stacked bar plot of chromosomes

### ISSUE THREAD

**Issue by mGauder** [ewels/MultiQC#842]
Hi @ewels,

I was wondering if it would be possible to integrate a new plot to the `featureCounts` section of the MultiQC report, which would look similar to the already existing one.

I attached an [exemplary stacked bar plot](https://github.com/ewels/MultiQC/files/2450324/count_summary_per_chromosome.pdf), where the x-axis shows the different samples, the y-axis represents the counts and the different colors depict the existing chromosomes.

All the necessary information is already given in the `results/featureCounts/gene_counts` folder.
Do you think it would be possible to implement this?

Best,

Marie

**Comment by ewels** [comment]
Hi Marie,

Are those counts already in the form of a summary statistic? The plot sounds good, but summing all gene counts is too computationally intensive for MultiQC to do (imagine that it's running on 30k samples and needs to finish in only a few minutes).

If we need to calculate them, then we can always do that as part of a pipeline (I'm guessing this is in relation to [nf-core/rnaseq](https://github.com/nf-core/rnaseq)?) and then pull that into MultiQC as a custom-content file.

Phil

**Comment by mGauder** [comment]
Hi Phil,

thanks for your quick reply!

Yes, there is already a summary statistic available (`merged_gene_counts.txt`) from which the information could be extracted. In this table, the different `ENSEMBL_IDs` are listed and the gene counts are given for each sample. From the `ENSEMBL_IDs`, the respective chromosome can be identified.

Other than that additional statistic files exist for each sample where the chromosomes are listed individually, but of course, when having many samples it would not be feasible to go over all of them separately.

I was indeed thinking of integrating that plot into the [nf-core/rnaseq](https://github.com/nf-core/rnaseq) pipeline. :grin: 

Best,

Marie

**Comment by mGauder** [comment]
Snap, I did not think about that.

Well, do you think the Python script would result in a lot of work then or be even worth implementing it as this feature could not be used outside of the pipeline?

Best, Marie

**Comment by ewels** [comment]
No, shouldn't be too tricky :) Please make a new issue on the pipeline repo for that...
