### ISSUE TITLE
FastQC heatmap doesn't work when present in a report twice

### ISSUE THREAD

**Issue by crickbabs** [ewels/MultiQC#843]
Hi Phil. I am having some problems getting custom content integrated into my multiqc report. The results were generated from the nf-core/atacseq pipeline in the same way that they are generated for the nf-core/rnaseq pipeline.

I am generating separate sections for the raw and trimmed fastqc reports but for some reason the "Per Sequence Base Content" is never rendered in the trimmed section.

All of the custom content sections I define arent in the report either.

I have provided the nextflow work directory (MultiQC gitter channel) for the multiqc process which should contain all the files required to reproduce the problem with MultiQC v1.6.

All of the custom content is in the "macs" directory.

**Comment by ewels** [comment]
This is a MultiQC bug: that plot is a custom one and when there are two in the same report then have an identical HTML ID, so they both end up plotting in the same div, which is the first one in the page.

To fix it, MultiQC needs some code refactoring to use a random unique identifier, with the custom javascript also updating to ensure that everything is correctly targeted to the relevant plot.

Test data: [multiqc_test.zip](https://github.com/ewels/MultiQC/files/2470580/multiqc_test.zip)

**Comment by ewels** [comment]
Just had a play with this and it quickly became a world of pain. I think that this is going to require some serious refactoring and rewriting. Unfortunately I don't have time for this now, but I'll leave it here for the future...
