### ISSUE TITLE
Oops! The 'fastp' MultiQC module broke...

### ISSUE THREAD

**Issue by Lucas-Maciel** [ewels/MultiQC#845]
I was trying to use multiqc to summarize my fastp reports but I got an error

```
lucas-maciel@lucasmaciel-Inspiron-7472:~/QC_fastq/fastp$ multiqc .
[INFO   ]         multiqc : This is MultiQC v1.7.dev0
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
[ERROR  ]         multiqc : Oops! The 'fastp' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    ./ERR1702979_fastp.json
============================================================
Module fastp raised an exception: Traceback (most recent call last):
  File "/home/lucas-maciel/.local/bin/multiqc", line 440, in multiqc
    output = mod()
  File "/home/lucas-maciel/.local/lib/python2.7/site-packages/multiqc/modules/fastp/fastp.py", line 43, in __init__
    self.parse_fastp_log(f)
  File "/home/lucas-maciel/.local/lib/python2.7/site-packages/multiqc/modules/fastp/fastp.py", line 237, in parse_fastp_log
    self.fastp_insert_size_data[s_name][i+1] = (float(v) / float(total_reads)) * 100.0
ZeroDivisionError: float division by zero
============================================================
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
```

 - Python Version: Python 2.7.15rc1
 - Method of MultiQC installation: pip

**Comment by ewels** [comment]
Thanks @Lucas-Maciel - looks like a simple bug caused by not handling samples with 0 reads in some fields.

Would it be possible for you to attach `ERR1702979_fastp.json` to this issue please, so that I can use it for testing when fixing the bug? You should be able to just drag and drop it into a comment. If GitHub complains about the format, you can zip it first.

Thanks,

Phil

**Comment by Lucas-Maciel** [comment]
[ERR1702979_fastp.zip](https://github.com/ewels/MultiQC/files/2496160/ERR1702979_fastp.zip)

Thank you for your attention Phil

**Comment by ewels** [comment]
Thanks for this! I'd not seen Fastp files like this before.

The error should now be fixed. Try pulling the latest dev version of the code, and let me know if you have and further problems.

Thanks!
