### ISSUE TITLE
Missing data in the InterOp module

### ISSUE THREAD

**Issue by vang42** [ewels/MultiQC#846]
**Description of bug:**

In the InterOp table "Read Metrics per Lane" and "Read Metrics Summary" some of the values are 0.0. In the underlying csv file the values are correct, and the background  barplot in the table, the bar sizes also look right. 

![image](https://user-images.githubusercontent.com/10140666/47202257-f97e2780-d37c-11e8-983e-1c55a0f37af7.png)

**Comment by ewels** [comment]
Hi @vang42,

Do you have a file I can use to replicate this please? What are the background numbers - is it just a rounding error? (`0.001` being rounded to `0.0` because it forces one decimal place)

Phil

**Comment by ewels** [comment]
Ah, this bug has already been fixed - see #817

The fix will go out in the next release, but before then you can get v1.7dev of MultiQC and it should work. See [the docs](https://github.com/ewels/MultiQC#installation) for how to do this.

Phil
