### ISSUE TITLE
cutadapt module doesn't respect -d directive

### ISSUE THREAD

**Issue by sprouffske** [ewels/MultiQC#848]
**Description of bug:**
Prepending the directory to the sample name doesn't work for the `cutadapt` module.  

As a result, I only retain the information from one cutadapt log file. 

It looks like the sample name is obtained from the cutadapt log file itself by parsing the command line call for cutadapt. However, I give all of my samples the same file names and distinguish between them by directory structure. As a result, the filename looks the same in the cutadapt logs for all of my samples.

The relevant contents of the two log files for the s_name are:

s1 log file: `/MYPATH/logs/s1/cutadapt.log `
```
This is cutadapt 1.18 with Python 3.6.6
Command line parameters:  -o /MYPATH/samples/s1/trimmed.fastq.gz /MYPATH/samples/s1/1.fastq.gz
```

s2 log file: `/MYPATH/logs/s2/cutadapt.log`
```

This is cutadapt 1.18 with Python 3.6.6
Command line parameters:  -o /MYPATH/samples/s2/trimmed.fastq.gz /MYPATH/samples/s2/1.fastq.gz

```
Only one sample named `1` is found.

**MultiQC Error log:**
```
[2018-10-18 23:00:22,896] multiqc                                            [WARNING]  MultiQC Version v1.6 now available!
[2018-10-18 23:00:22,896] multiqc                                            [INFO   ]  This is MultiQC v1.5 (bf9e745)
[2018-10-18 23:00:22,896] multiqc                                            [INFO   ]  Template    : default
[2018-10-18 23:00:22,897] multiqc                                            [INFO   ]  Prepending directory to sample names
...
[2018-10-18 23:00:39,014] multiqc.modules.cutadapt.cutadapt                  [DEBUG  ]  Duplicate sample name found! Overwriting: 1
[2018-10-18 23:00:39,022] multiqc.modules.cutadapt.cutadapt                  [INFO   ]  Found 1 reports
...
```

**MultiQC run details:**
 - Command used to run MultiQC: `multiqc --verbose -f -d -o MYDIR /MYPATH/logs/s1/cutadapt.log /MYPATH/logs/s2/cutadapt.log`
 - MultiQC Version: v1.5
 - Operating System: Linux 
 - Python Version: Python 3.6.3
 - Method of MultiQC installation: conda

**Comment by ewels** [comment]
Hi @sprouffske,

You are completely correct, it's missing the required function call to prepend the directory. This is in error, I'll fix it quickly for you now.

Phil

**Comment by ewels** [comment]
Hi @sprouffske,

I was wrong - it wasn't quite that simple. After a bit of debugging I found that for some cases, the sample cleanup was removing the directory prefixes again after they'd been added. I switched the order of execution a little and now it works, at least for me.

If you could please upgrade to the latest development version and test the change, that would be great!

Thanks,

Phil

**Comment by sprouffske** [comment]
Hi @ewels,
I tested the latest development version, and it works for me now too. Thanks very much!
