### ISSUE TITLE
RSeQC and multiQC under snakemake

### ISSUE THREAD

**Issue by splaisan** [ewels/MultiQC#852]
Hi 

I do not know where to post this (here or at snakemake) so I will [crosspost](https://bitbucket.org/snakemake/snakemake/issues/1010/rseqc-and-multiqc-under-snakemake) and feed back here (sorry for that)

I want to include RSeQC results in my multiQC run under snakemake
For that I need to give the SM module the name of the inputs.

Can you share on what . to put in the snakemake call to give multiQC the right data
I have two analyses and have kept only these two in the **multiqc_config.yaml** (should I load this yaml with include?)

```
# MultiQC configuration

rseqc_sections:
    - gene_body_coverage
    - junction_saturation
```

snakemake rule

```
rule multiqc_global:
    """
    Aggregate all MultiQC reports
    """
    input:
        expand("results/rseqc/{smp}.geneBodyCoverage.curves.pdf", smp=SAMPLES),
        expand("results/rseqc/{smp}.junctionSaturation_plot.pdf", smp=SAMPLES),
    output:
        html = "results/global_multiqc.html",
        stats = "intermediate/global_multiqc_general_stats.txt"
    log:
        "logs/multiqc/global_multiqc.log"
    version: "1.0"
    shadow: "minimal"
    shell: """
        # Run multiQC and keep the html report
        multiqc -n multiqc.html {input} 2> {log}
        mv multiqc.html {output.html}
        mv multiqc_data/multiqc_general_stats.txt {output.stats}
        """
```

is it the PDF I need to include or the .r and .txt ?

**Comment by splaisan** [comment]
I have now these two working (but not yet others - new ticket), thanks for your help

**Comment by ewels** [comment]
Hi @splaisan,

As was on the other post - you need the `.r` file not the PDF. Glad you got it working! Also as on the other post, there's a MultiQC chat thread where you can go for help :) https://gitter.im/ewels/MultiQC

Phil

**Comment by splaisan** [comment]
Thanks a lot Phil,
I will post an example for the clipping profile data which would be great to have too.
BTW cold you (I do not have enough credits) make that MultiQC be added as a TAG on StackOverflow. Snakemake is tagged there but not MultiQC which definitely deserves it; especially since I did not discover your linked site above myself in the doc (gitter!!? never heard of this).
All the best

**Comment by ewels** [comment]
Yeah, I have a big button for gitter, but it's perhaps something that could be improved..

<img src="https://user-images.githubusercontent.com/465550/48407479-2da7f680-e737-11e8-9f2f-b7d9bd91a83d.png" width=400>

StackOverflow tag is a good idea, I'll look into it.
