### ISSUE TITLE
multiQC histo from text file with one value per line

### ISSUE THREAD

**Issue by splaisan** [ewels/MultiQC#853]
HI
Thanks for the great tool I just discovered!!!
I have scripts that count features and return a list of values (one per line) for each sample.
How difficult would it be to run multiQC from these text outputs and make an overlay hist density plot of it. Is there a generic module for this purpose?
Is there an easy way to encode this in snakemake (sorry to link to it but they really make a pair)
Thanks

**Comment by ewels** [comment]
Very easy! See https://multiqc.info/docs/#custom-content

An example of a bar graph generated like this is [here](https://github.com/ewels/MultiQC_TestData/blob/master/data/custom_content/embedded_config/test_bargraph_mqc.txt) (click around surrounding folders for more examples).

Have a play and let me know if you need any help (happy to reopen issue for more questions). You can also ask on Gitter: https://gitter.im/ewels/MultiQC

Phil

**Comment by ewels** [comment]
ps. We use nextflow instead of snakemake so don't have much experience there sorry. Maybe post in gitter for questions though, there may be other snakemake users there.
