### ISSUE TITLE
RSeQC not reporting results for several parts

### ISSUE THREAD

**Issue by splaisan** [ewels/MultiQC#856]
I finally could get three QC to be found but no success yet for clipping_profile although it is in my config and RSeQC has run it

```
clipping_profile.py -i ${bam} \
        -q 30 \
        -s PE \
        -o ${smp}
```

my last run

`multiqc -f -n multiqc .
`

```
[INFO   ]         multiqc : This is MultiQC v1.6
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
[INFO   ]           rseqc : Found 9 read_distribution reports
[INFO   ]           rseqc : Found 9 gene_body_coverage reports
[INFO   ]           rseqc : Found 9 junction_saturation reports
[INFO   ]         multiqc : Compressing plot data
[WARNING]         multiqc : Deleting    : multiqc.html   (-f was specified)
[WARNING]         multiqc : Deleting    : multiqc_data   (-f was specified)
[INFO   ]         multiqc : Report      : multiqc.html
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete
```

the missed data (one of the 9 samples)

```
S3.clipping_profile.r
S3.clipping_profile.R1.pdf
S3.clipping_profile.R2.pdf
S3.clipping_profile.xls
```

I noticed that the data file is named .xls although it is a tsv file but copying it to .txt or .tsv does not help (not shown here)

multiqc_config.yaml

```
rseqc_sections:
    - gene_body_coverage
    - junction_saturation
    - clipping_profile
    - read_distribution
```

Any idea?

**Comment by ewels** [comment]
Yes - I'm afraid that MultiQC does not (yet) support all of the different RSeQC scripts. See the [documentation](https://multiqc.info/docs/#rseqc) for a list.

If you'd like this added, please attach some example outputs from those scripts and I'll add it to the to-do queue.

Phil

**Comment by splaisan** [comment]
Here a pair of example using PE and SE (merged) reads and the commands on STAR BAM data:

* RSeQC clipping_profile.py 3.0.0

```
clipping_profile.py -i se_UG1_S12/Aligned.out.bam         -q 30         -s SE         -o SE_output
clipping_profile.py -i pe_UG1_S12/Aligned.out.bam         -q 30         -s PE         -o PE_output

```
[clipping_profile_examples.zip](https://github.com/ewels/MultiQC/files/2575358/clipping_profile_examples.zip)

The .xls is in fact a tsv file with plotting values in one or two blocks.
thanks Phil for looking into this
