### ISSUE TITLE
SnpEff module.

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#86]
http://snpeff.sourceforge.net/

**Comment by guillermo-carrasco** [comment]
+1

**Comment by ewels** [comment]
Now have some [example data](https://github.com/ewels/MultiQC_TestData/tree/master/data/snpEff). Next need to figure out which information is useful.

Note that these two files are produced by our analysis pipeline and will overwrite each other in MultiQC, so may need some thought to figure out how to deal with this. Perhaps a new plugin hook in the `clean_s_name` so that the NGI plugin can alter how the sample names are generated?

**Comment by ewels** [comment]
Hi @guillermo-carrasco and @parlundin,

Please could you have a go at running this new module and let me know if you find any bugs? I have added quite a few plots, let me know if I should add or remove anything else. There's also a new option here to have a Log10 axis (all plots) which I thought would be useful to see the smaller categories. Let me know if you find any bugs with that.

Phil
