### ISSUE TITLE
The peddy MultiQC module broke with bcbio-nextgen pipeline

### ISSUE THREAD

**Issue by Fazulur** [ewels/MultiQC#860]
Dear MultiQC team,

I am getting MultiQC related error when I run whole exome analysis using bcbio-nextgen variant calling pipeline. Some how MultiQC peddy module was broken. Peddy ran without errors with bcbio pipleline. Please find below the error log.

```
[2018-11-15T06:36Z]local: KeyError: 'ancestry-prediction'
[2018-11-15T06:36Z]local: ============================================================
[2018-11-15T06:36Z]local: [INFO   ]        bcftools : Found 1 stats reports
[2018-11-15T06:36Z]local: [INFO   ]          snpeff : Found 1 reports
[2018-11-15T06:36Z]local: [INFO   ]          fastqc : Found 1 reports
[2018-11-15T06:36Z]local: [INFO   ]         multiqc : Compressing plot data
[2018-11-15T06:36Z]local: [INFO   ]         multiqc : Report      : ../../bcbiotx/tmpCENQTL/multiqc_report.html
[2018-11-15T06:36Z]local: [INFO   ]         multiqc : Data        : ../../bcbiotx/tmpCENQTL/multiqc_data
[2018-11-15T06:36Z]local: [INFO   ]         multiqc : MultiQC complete
[2018-11-15T06:36Z]local: Uncaught exception occurred
Traceback (most recent call last):
  File "bcbio-v1.0.8/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "bcbio-v1.0.8/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; export PATH=bcbio-v1.0.8/anaconda/bin:$PATH &&  bcbio-v1.0.8/anaconda/bin/multiqc -f -l
[INFO   ]         multiqc : This is MultiQC v1.6.dev0
[INFO   ]         multiqc : Template    : default
Searching 25 files..
[INFO   ]     verifybamid : Found 1 reports
[INFO   ]           bcbio : Found 1 reports
[INFO   ]        samtools : Found 1 stats reports
[INFO   ]        samtools : Found 1 idxstats reports
[INFO   ]           peddy : Found 2 reports
[ERROR  ]         multiqc : Oops! The 'peddy' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    peddy/sample.background_pca.json
============================================================
Module peddy raised an exception: Traceback (most recent call last):
  File "bcbio-v1.0.8/anaconda/bin/multiqc", line 440, in multiqc
    output = mod()
  File "bcbio-v1.0.8/anaconda/lib/python2.7/site-packages/multiqc/modules/peddy/peddy.py", line 87, in __init__
    self.peddy_pca_plot()
  File "bcbio-v1.0.8/anaconda/lib/python2.7/site-packages/multiqc/modules/peddy/peddy.py", line 219, in peddy_pca_plot
    'color': ancestry_colors.get(d['ancestry-prediction'], default_color)
KeyError: 'ancestry-prediction'
============================================================

```

**File that triggers the error:**
Please drag and drop (and upload to the GitHub issue) an input file that I can use to replicate the error.
[sample.background_pca.json.txt](https://github.com/ewels/MultiQC/files/2587936/sample.background_pca.json.txt)

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC: [eg. `bcbio-v1.0.8/anaconda/bin/multiqc -f -l multiqc/list_files.txt  -o bcbiotx/tmpCENQTL`]
 - MultiQC Version: [eg. MultiQC v1.6]
 - Operating System: [eg. Linux]
 - Python Version: [eg. Python 2.7.15]
 - Method of MultiQC installation: [eg. conda]

 Please suggest me how to resolve this.

Thanks In Advance
Fazulur Rehaman

**Comment by ewels** [comment]
Hi @Fazulur,

No team really sorry, just me :) The file that you attached looks very strange - can I confirm that it's definitely the raw output directly from Peddy? The top of the file looks like this:

```
{\rtf1\ansi\ansicpg1252\cocoartf1504\cocoasubrtf830
{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\margl1440\margr1440\vieww25400\viewh13480\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0
```

My guess is that you've saved it from a rich text editor or something. If you could have another go at attaching the raw JSON file (maybe zip it if the file format is a problem) that would be great.

Thanks,

Phil

**Comment by Fazulur** [comment]
Hi ewels,

Thanks a lot for your quick response and I am sorry for corrupted file. Please find below the compressed one.
[sample.background_pca.json.txt.zip](https://github.com/ewels/MultiQC/files/2590190/sample.background_pca.json.txt.zip)

Please suggest me how to resolve issues with peddy.
Thanks In Advance
Fazulur Rehaman

**Comment by ewels** [comment]
Hi Fazulur,

This appears to be the same file, but zipped. I followed up on my hunch that you've saved this file in a word processor and I think I was right - I was able to open it in MS Word and re-save the contents in a plain text format. See attached (compressed to allow upload to GitHub): 
[sample.background_pca.json.zip](https://github.com/ewels/MultiQC/files/2592233/sample.background_pca.json.zip)

Trying this new file on MultiQC, it runs without any problems. However, I realise now that this JSON file is only the background data for a single plot, so the resulting report doesn't contain and sample-specific information from your project. The MultiQC peddy module looks for the following files:

```yaml
peddy/summary_table:
    fn: '*.peddy.ped'
peddy/het_check:
    fn: '*.het_check.csv'
peddy/ped_check:
    fn: '*.ped_check.csv'
peddy/sex_check:
    fn: '*.sex_check.csv'
peddy/background_pca:
    fn: '*.background_pca.json'
```

So that I can replicate this error, please try to copy out just the peddy result files from your bcbio run that match the above patterns. Then try running MultiQC on them manually and see if they trigger the same error. If so, please attach them so that I can try to replicate the error and then fix it.

I hope this makes sense. Let me know if you need further pointers.

Thanks,

Phil

**Comment by Fazulur** [comment]
Hi ewels,

Thanks a lot for your suggestions.
Sorry for giving json file in wrong format. 

I ran multiqc manually on peddy results. After further looking into results, i realized that error is due to "sampleID".Peddy is ignoring leading '0' in .ped file. Actually, sample Id for our samples starts with leading '0' e.g. 021001.

When I reran Peddy , it is giving warnings like below

**2018-11-18 09:04:04 ngslogin1 peddy.cli[13805] WARNING 1 samples in vcf not in ped:
02003
2018-11-18 09:04:04 ngslogin1 peddy.cli[13805] WARNING 1 samples in ped not in vcf:
2003**

It will be solved if I add some extra prefix to description part of bcbio configuration.

Thanks & Regards
Fazulur Rehaman

**Comment by ewels** [comment]
Thanks @Fazulur - these are log messages from Peddy and not MultiQC, so I'll close this now. Glad you got it sorted!
