### ISSUE TITLE
MultiQC does not install properly on Windows 10

### ISSUE THREAD

**Issue by agniukaitis** [ewels/MultiQC#863]
**Description of bug:**
Hi Phil,

I have tried to install MultiQC on my desktop running Windows 10. So far, all three methods of installation (conda, pip, and manual) lead to exactly same and reproducible problem of not being able to simply execute `multiqc .` command directly in cmd. However, executing `python absolute\path\to\python\scripts\multiqc .` works just fine.

I have also tried executing `python multiqc .`, which returns an error message `python.exe: can't find '__main__' module in 'multiqc'`

**MultiQC run details:**
 - Command used to run MultiQC: `multiqc .`
 - MultiQC Version: MultiQC v1.6
 - Operating System: Windows 10 Pro
 - Python Version: Python 3.7.0
 - Method of MultiQC installation: pip, conda, and manual

**Comment by ewels** [comment]
Hi @agniukaitis,

Thanks for this - it sounds familiar. Note that the automatic windows tests also have to specify the complete path to work:
https://github.com/ewels/MultiQC/blob/9b00ad63cf25ec2b1f875ebfcd632f83feac2751/appveyor.yml#L40-L45

Windows support for MultiQC is limited at best and I haven't spent lots of time working with it there. It's especially difficult as I don't have access to a windows machine, and I'm afraid that it's a pretty low priority as the majority of MultiQC users are running on unix systems.

Is there a problem with using the entire path when you want to run MultiQC? If that works then I'm relatively happy.

Phil

**Comment by agniukaitis** [comment]
Dear @ewels,

Thank you for the reply. I suppose there is no real problems using absolute path, other than being a bit more tedious every time I want to run the script. After all, running the script in such way appears to be working as intended. Perhaps addressing this minor problem in a form of a small troubleshoot for other windows users could be of potential use? :P

**Comment by ewels** [comment]
I would love to address it - I just have no idea how 😆 Perhaps your google-foo is stronger than mine? I had a look around and couldn't find anything that sounded relevant.. I remember fighting with the same problem when setting up the testing and coming up blank then too.

In the mean time, can you use an equivalent of the unix `alias` or something to make a shortcut to the path?
