### ISSUE TITLE
Installation problem with matplotlib

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#865]
```
$ multiqc .
```
```python
Traceback (most recent call last):
  File "/usr/local/bin/multiqc", line 4, in <module>
    __import__('pkg_resources').run_script('multiqc==1.7.dev0', 'multiqc')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 637, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 650, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'matplotlib<3.0.0,>=2.1.1' distribution was not found and is required by multiqc
```

_Originally posted by @padafa in https://github.com/ewels/MultiQC/issues/226#issuecomment-441143028_

**Comment by ewels** [comment]
Hi @padafa,

Please can you pass on additional information about how you have been running MultiQC:

**Description of bug:**
A clear and concise description of what the bug is.

**File that triggers the error:**
Please drag and drop (and upload to the GitHub issue) an input file that I can use to replicate the error.

**MultiQC run details (please complete the following):**
 - MultiQC Version: [eg. MultiQC v1.1]
 - Operating System: [eg. macOS Sierra 10.12.5]
 - Python Version: [eg. Python 2.7.12]
 - Method of MultiQC installation: [eg. pip, conda, manual]

 **Additional context**
 Add any other context about the problem here.

**Comment by ewels** [comment]
Looking at the error log, it seems to be a problem with installing the MatPlotLib dependency. I'd recommend uninstalling any previous installations of this and reinstalling it manually:

```
pip uninstall matplotlib
pip install matplotlib==2.2.3
```

This is assuming that you have used `pip` to install MultiQC.

**Comment by fgvieira** [comment]
Does MultiQC

**Comment by fgvieira** [comment]
I'm using anaconda3 v4.4.0

**Comment by ewels** [comment]
And you get the exact same traceback? That's weird. Could you please do `conda list` and attach the results here so that I can see what Python packages you have installed in your environment?

My guess is still that you have a later version of matplotlib and conda doesn't want to go backwards from that. Have you tried uninstalling matplotlib and then installing MultiQC?

**Comment by fgvieira** [comment]
Well, not exactly the same as @padafa. Mine has the latest version of `matplotlib` installed (I am using python3) and complaints about it:
`pkg_resources.VersionConflict: (matplotlib 3.0.2, Requirement.parse('matplotlib<3.0.0,>=2.1.1'))`

While @padafa didn't have it installed:
`pkg_resources.DistributionNotFound: The 'matplotlib<3.0.0,>=2.1.1' distribution was not found and is required by multiqc`

I am working on a cluster, so can not really uninstall matplotlib... I guess they updated the matplotlib package because of another dependency, and broke multiqc, but here is the list of packages:
[conda_list.txt](https://github.com/ewels/MultiQC/files/2722962/conda_list.txt)

**Comment by ewels** [comment]
Hmm, I hadn't really thought about this set of circumstances. I wonder if I can set the dependencies on the conda package in a way that is dependent on python version (eg. remove that limit for py3).

**Comment by fgvieira** [comment]
That'd be perfect. :+1:

**Comment by ewels** [comment]
@bgruening - sorry for all of the questions today! 😅 This is a totally separate one. Is it possible to have varying package dependencies based on the version of python being used?

Specifically, we're talking about `matplotlib`, which [I've set to](https://github.com/bioconda/bioconda-recipes/blob/876c35ae9e465b9c17d35a2f4416c62490a613e6/recipes/multiqc/meta.yaml#L26) `matplotlib >=2.1.1,<3.0.0` so that version 3 doesn't force all MultiQC users to use python 3.

Is it possible to have something like this?
```yml
requirements:
  run:
    matplotlib >=2.1.1          # [py3]
    matplotlib >=2.1.1,<3.0.0   # [py2]
```
...or is there any other way to achieve this?

Thanks,

Phil

**Comment by jhangyu** [comment]
Hi, I've encounter to this problem in my miniconda3 container too.
Maybe I should downgrade the matplotlib to version 3.0.0 to solve this problem?

**Comment by ewels** [comment]
Hi @jhangyu,

Yes, hopefully that will fix it. I closed the above PR because I didn't think that it would affect so many people, but maybe I should reopen it.

Phil

**Comment by ewels** [comment]
See #928 and #973 - I'd like to remove these dependencies if I can.
