### ISSUE TITLE
samtools flagstat weird plot

### ISSUE THREAD

**Issue by splaisan** [ewels/MultiQC#866]
This has been posted by others in galaxy pages and probably relates to #334.
Just to be sure that what I get is the intended output as it seems a bit weird with very small data dots on top of a 'table' with repeated scale values on each row which make it less readable overall. 
Thanks in advance
![screen shot 2018-11-29 at 12 07 10](https://user-images.githubusercontent.com/858516/49218038-a1046600-f3cf-11e8-9947-5a89f0ff2f83.png)

**Comment by ewels** [comment]
This is working as expected. It's a beewarm plot, though it looks a little strange with just one sample.

This plot is one of my least favourite in MultiQC. If you have any suggestions for how to improve it, they would be welcome.

**Comment by splaisan** [comment]
Thanks Phil,
I fully agree with plot being better than table.
Would it be possible to make the dots larger and remove the numbers across the plotting area (they are identical after all) and leaving them only as x-axis?

**Comment by splaisan** [comment]
Hi Phil,
You can forget about my remarks, it is indeed pretty with multiple samples ;-)
Thanks for the great tool!

**Comment by ewels** [comment]
Thanks for the suggestions! 👍
