### ISSUE TITLE
FastQC summary boxes (progress bar) misplaced when plotting report twice

### ISSUE THREAD

**Issue by fgvieira** [ewels/MultiQC#871]
**Description of bug:**
When plotting FastQC, there are summary boxes (progress bar) that show up above the plots.
However, when plotting reports twice:
```
module_order:
    - fastqc:
        name: 'FastQC (trimmed)'
        info: 'This section of the report shows FastQC results after adapter trimming.'
        target: ''
        path_filters:
            - '*fastqc_post*'     

    - fastqc:
        name: 'FastQC (raw)'
        path_filters:
            - '*fastqc_pre*'
```

They are plotted twice only above one report.

***After Trimming***
![image](https://user-images.githubusercontent.com/1151762/49579005-6ceaf100-f94b-11e8-81e2-ad020e887060.png)

***Before Trimming***
![pasted_image_at_2018-12-06__11_33_am](https://user-images.githubusercontent.com/1151762/49578992-63618900-f94b-11e8-93d8-2b1cceecf940.png)

**MultiQC Error log:**
```
No error message.
```

**File that triggers the error:**
[Example.tar.gz](https://github.com/ewels/MultiQC/files/2652736/Example.tar.gz)

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC: `multiqc .`
 - MultiQC Version: `1.6 / 1.7dev0`
 - Operating System: `Linux`
 - Python Version: `Python 3.4.5`
 - Method of MultiQC installation: `manual`

 **Additional context**

**Comment by ewels** [comment]
Yes, this is a known bug. It's a bit of a hassle to fix, which is why it's persisted so long. Thanks for reporting, I'll add it to the list :)

**Comment by ewels** [comment]
Hi @fgvieira,

This bug is finally fixed! It's been bothering me for ages and was amazingly difficult to resolve given how simple it seems on the surface. Please let me know how you get on with the fix anyway 👍 

Phil
