### ISSUE TITLE
fastp module: find *fastp.json?

### ISSUE THREAD

**Issue by jdrnevich** [ewels/MultiQC#872]
We are using MultiQC v. 1.6 to summarize fastp results for many samples. It appears that the MultiQC fastp module looks for files called fastp.json. This requires us to make separate folders for each sample to contain the `fastp.json` which we'd rather not do. Could the fastp module instead look for files names `*fastp.json` so we can name them individually? Thanks!

**Comment by ewels** [comment]
Hi @jdrnevich,

You can do this yourself: https://multiqc.info/docs/#module-search-patterns

However, it's probably not a bad idea to put in the wildcard as it's still pretty specific 👍 

Phil
