### ISSUE TITLE
htseq-count module doc

### ISSUE THREAD

**Issue by mhebrard** [ewels/MultiQC#873]
htseq-count do not "force" any name for its output file.it is up to the user to define it.

I did not find any mention of what pattern is used by multiQC to identify the htseq-count result.

If I looked at the good place in the code source, mqc is looking for ```"*htseq*"```. it would be nice to specify that in the documentation of the module.

**Comment by ewels** [comment]
Hi @mhebrard,

MultiQC finds htseq-count files not by file name, but by file contents. Specifically, it looks for the string `__too_low_aQual`:

https://github.com/ewels/MultiQC/blob/358327b358658c4fa1b42d3973be57269128c224/multiqc/utils/search_patterns.yaml#L259-L260

See the documentation [here](https://multiqc.info/docs/#module-search-patterns) and [here](https://multiqc.info/docs/#step-1-find-log-files) for more information.

Phil
