### ISSUE TITLE
samtools flagstat beeswarm: use read_count_multiplier

### ISSUE THREAD

**Issue by jfy133** [ewels/MultiQC#881]
(apologies if this is in the wrong issue section)

**Issue**
When working with ancient DNA, we often have very low endogenous DNA and we get very few on-target reads to our organism (hundreds/thousands max).

The [nf-core/eager](https://github.com/nf-core/eager) pipeline utilises samtools for some of the statistics generation, however the samtools MultiQC module reports all numbers in millions of reads (e.g. 0.0M).

Thus, when I have e.g. 3,000 mapped reads  (example stats file attached), the plot cannot display the number and could misdirect a user to believe there is no mapping reads. The same also goes to the 'general statistics' table.

**Request**
Provide an option (or auto-detect) to show 'real numbers' rather than in millions of reads for the samtools module and/or general statistics table.

**Additional Info**
samtools flagstat: [ABM006.A0101_S0_L002_R1_001.sorted.stats.txt](https://github.com/ewels/MultiQC/files/2706060/ABM006.A0101_S0_L002_R1_001.sorted.stats.txt)

multiqc report: [multiqc_report.zip](https://github.com/ewels/MultiQC/files/2706061/multiqc_report.zip)

**Comment by ewels** [comment]
Good news - this feature already exists! 🎉 

https://multiqc.info/docs/#number-base-multiplier

**Comment by jfy133** [comment]
Does this also apply to the samtools plots though? 

When I tested those parameters with MultiQC 1.7 (with the above file) it only changed the general statistics table, and not the samtools plots).

**Comment by ewels** [comment]
There has to be support written into the module code, so it's possible that it's lacking that.

..yes, this needs modifying: https://github.com/ewels/MultiQC/blob/c89816e5e47a7c2d7514c0f7be470f18ffd2f14a/multiqc/modules/samtools/flagstat.py#L54

**Comment by jfy133** [comment]
Great thanks!
