### ISSUE TITLE
Export static plots from fastqc results in incorrect colour assignment to background

### ISSUE THREAD

**Issue by abeu1990** [ewels/MultiQC#886]
**Description of bug:**
When using the export function in multiqc to get png files from fastqc output the colour assignment for pass/fail is incorrect. 0-10 is red, 10-15 is green, 15-25 is yellow and 25-40 is green. This does not seem to be a problem if you generate the html without static images.  

See attached file. 

![mqc_fastqc_per_base_sequence_quality_plot_1](https://user-images.githubusercontent.com/46658905/51091826-38891100-17e4-11e9-9c75-50d5ebc8d407.png)

**Comment by ewels** [comment]
Fixed in #916 by @epakarin
