### ISSUE TITLE
MultiQC not running on windows

### ISSUE THREAD

**Issue by adirot** [ewels/MultiQC#891]
Hi!
I installed multiqc using git, and also using conda, I followed the installation instructions on the multiqc site.
I tried running "multiqc ." in my cmd but I receive the following error:

'multiqc' is not recognized as an internal or external command,
operable program or batch file.

What is wrong?

OS: windows 10

**Comment by ewels** [comment]
See #863 - I guess you need to use the full path to MultiQC.

I should add something to the documentation about this.

**Comment by ewels** [comment]
I added some new documentation about this: https://multiqc.info/docs/#installing-on-windows

Let me know if this doesn't fix your problem and we can reopen this issue.

**Comment by ewels** [comment]
No idea sorry, I haven't touched a windows machine in about 5 years so I'm out of practice 😀
