### ISSUE TITLE
Ensembl-VEP annotation stats

### ISSUE THREAD

**Issue by fgvieira** [ewels/MultiQC#892]
**Tool Details**
 - Name of tool: Ensembl Variant Effect Predictor
 - Tool homepage: http://www.ensembl.org/info/docs/tools/vep/index.html
 - Tool description: VEP determines the effect of variants (SNPs, insertions, deletions, CNVs or structural variants) on genes, transcripts, and protein sequence, as well as regulatory regions. 
 - Data suitable for MultiQC plot(s): mostly pie charts and histograms (as in example [here](https://github.com/ewels/MultiQC/files/2791993/example.vcf.gz_summary.pdf); originally it is an HTML, but converted to PDF so it could be uploaded to GitHub)
 - Most interesting data for General Stats table: all/some of the pie charts in the example above

**Tool output:**
 - Log filename pattern: `*_summary.txt` (default, but can be specified by the user)
 - File contents: VEP allows for both HTML and TXT output, but uploading here the TXT.
[example.vcf.gz_summary.txt](https://github.com/ewels/MultiQC/files/2791994/example.vcf.gz_summary.txt)

**Comment by fgvieira** [comment]
Sure, here is the example in HTML:
[example.vcf.gz_summary.zip](https://github.com/ewels/MultiQC/files/2796550/example.vcf.gz_summary.zip)

**Comment by ewels** [comment]
Thanks!

**Comment by stefandiederich** [comment]
Hi @ewels 
I am interested in using a VEP module as well. Did you make any efforts implementing it?
Bests
Stefan

**Comment by a-frantz** [comment]
Just bumping this @ewels 
I'm also interested in being able to aggregate VEP summaries.
Thanks,
Andrew

**Comment by ewels** [comment]
@fgvieira / @stefandiederich / @a-frantz - your requests have been answered! @berguner has submitted a new module for VEP in https://github.com/ewels/MultiQC/pull/1419 (and I've just been messing around with his code).

Should be merged into the dev version of MultiQC shortly. Would be great if you could test and try to break it 👍🏻

**Comment by fgvieira** [comment]
Hi all,

I just gave it a try and must say that it looks very nice!
Thanks a lot @berguner 

I'll see if I can break it.

**Comment by fgvieira** [comment]
Dear all,

I just tried running MultiQC with a VEP stats file from yeast, and got an error:
```
[2021-04-30 01:02:18,231] multiqc.modules.vep.vep                            [INFO   ]  Found 2 VEP summaries
╭─────────────────────────────────────────────────────────────────── Oops! The 'vep' MultiQC module broke... ───────────────────────────────────────────────────────────────────╮
│ Please copy this log and report it at https://github.com/ewels/MultiQC/issues                                                                                                 │
│ Please attach a file that triggers the error. The last file found was: stats/variants/freebayes/sim.annot_vep.stats                                                           │
│                                                                                                                                                                               │
│ Traceback (most recent call last):                                                                                                                                            │
│   File "cache/conda/721fc9c93a6154ffea30f47745fbf77d/lib/python3.9/site-packages/multiqc/multiqc.py", line 604, in run                        │
│     output = mod()                                                                                                                                                            │
│   File "cache/conda/721fc9c93a6154ffea30f47745fbf77d/lib/python3.9/site-packages/multiqc/modules/vep/vep.py", line 57, in __init__            │
│     self.bar_graph_polyphen()                                                                                                                                                 │
│   File "cache/conda/721fc9c93a6154ffea30f47745fbf77d/lib/python3.9/site-packages/multiqc/modules/vep/vep.py", line 275, in bar_graph_polyphen │
│     plot_data, plot_cats, plot_config = self._prep_bar_graph(title)                                                                                                           │
│   File "cache/conda/721fc9c93a6154ffea30f47745fbf77d/lib/python3.9/site-packages/multiqc/modules/vep/vep.py", line 347, in _prep_bar_graph    │
│     plot_data[s_name] = self.vep_data[s_name][title]                                                                                                                          │
│ KeyError: 'PolyPhen summary'                                                                                                                                                  │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

I think it is because the Polyphen section is not available in this file.

**Comment by berguner** [comment]
Dear @fgvieira,

Thanks for testing the module. I added a checkpoint in 3681001517448140bc0eb274a8d23e078479cc5c for handling such a problem, so line 347 should be: https://github.com/ewels/MultiQC/blob/1c3670c2e968ae51deaf4ec72286df350d1eab87/multiqc/modules/vep/vep.py#L347 Are you sure you are running the latest version of the code?

**Comment by ewels** [comment]
Also, if you are sure then if you could attach a report that triggers the error that would be great 👍🏻

**Comment by fgvieira** [comment]
Hi both, it seems I was using an older version.
After updating, all good!
