### ISSUE TITLE
bamsormadup (read sorting and marking of duplicates)

### ISSUE THREAD

**Issue by fgvieira** [ewels/MultiQC#895]
**Tool Details**
 - Name of tool: bamsormadup (biobambam2)
 - Tool homepage: https://github.com/gt1/biobambam2
 - Tool description: Tool for read sorting and marking of duplicates on a BAM file
 - Data suitable for MultiQC plot(s): the same as for picard MarkDuplicates
 - Most interesting data for General Stats table: the same as for picard MarkDuplicates

**Tool output:**
 - Log filename pattern: specified by the user without any default
 - File contents:
[example.txt](https://github.com/ewels/MultiQC/files/2811332/example.txt)

The output log file is very similar to that from picard MarkDuplicates, so maybe it is possible to use the same module? I tried, but could not get it to work...

**Comment by ewels** [comment]
Thanks for the request @fgvieira - you managed to include everything that I need in these issues! 🎉  (I know there's a template, but still - you'd be surprised..)

I'll take a look when I get a chance.

**Comment by fgvieira** [comment]
not sure if it helps, but I've managed to 'trick' MultiQC by replacing, in the header of the metrics file:
```
##METRICS
```
with:
```
# MarkDuplicates INPUT={output.bam}
## METRICS CLASS\tDuplicationMetrics
```

Either way, still think it would be nice to have it properly implemented.

**Comment by ewels** [comment]
Thanks @fgvieira - if this is all it took to make it work then it should be very easy to add. I'll take a look.

Phil

**Comment by fgvieira** [comment]
@ewels it iseems to be working fine!
thanks,

**Comment by ewels** [comment]
Great! Thanks for letting me know :)
