### ISSUE TITLE
Not parsing STAR output ".ReadsPerGene.out.tab" files

### ISSUE THREAD

**Issue by Sumeet460** [ewels/MultiQC#899]
**Description of bug:**
Running multiQC to parse .ReadsPerGene.out.tabl files results in the files being found, however, a no-analysis results found error is returned. The files do contain the appropriate columns. 

**MultiQC Error log:**
```
[INFO ] multiqc : This is MultiQC v0.7
[INFO ] multiqc : Searching './SRR5031378.ReadsPerGene.out.tab'
[INFO ] multiqc : Searching './SRR5031379.ReadsPerGene.out.tab'
[INFO ] multiqc : Searching './SRR5031380.ReadsPerGene.out.tab'
[INFO ] multiqc : Searching './SRR5031381.ReadsPerGene.out.tab'
[INFO ] multiqc : Searching './SRR5031382.ReadsPerGene.out.tab'
[INFO ] multiqc : Searching './SRR5031383.ReadsPerGene.out.tab'
[INFO ] multiqc : Searching './SRR5031384.ReadsPerGene.out.tab'
[INFO ] multiqc : Searching './SRR5031385.ReadsPerGene.out.tab'
[INFO ] multiqc : Searching './SRR5031386.ReadsPerGene.out.tab'
[INFO ] multiqc : Searching './SRR5031387.ReadsPerGene.out.tab'
[INFO ] multiqc : Searching './SRR5031388.ReadsPerGene.out.tab'
[INFO ] multiqc : Searching './SRR5031389.ReadsPerGene.out.tab'
[INFO ] multiqc : Searching './SRR5031390.ReadsPerGene.out.tab'
[INFO ] multiqc : Searching './SRR5031391.ReadsPerGene.out.tab'
[INFO ] multiqc : Searching './SRR5031392.ReadsPerGene.out.tab'
[INFO ] multiqc : Searching './SRR5031393.ReadsPerGene.out.tab'
[INFO ] multiqc : Searching './SRR5031394.ReadsPerGene.out.tab'
[INFO ] multiqc : Searching './SRR5031395.ReadsPerGene.out.tab'
[INFO ] multiqc : Searching './SRR5031396.ReadsPerGene.out.tab'
[INFO ] multiqc : Searching './SRR5031397.ReadsPerGene.out.tab'
[INFO ] multiqc : Searching './SRR5031398.ReadsPerGene.out.tab'
[INFO ] multiqc : Searching './SRR5031399.ReadsPerGene.out.tab'
[WARNING] multiqc : No analysis results found. Cleaning up..
[INFO ] multiqc : MultiQC complete
```

**File that triggers the error:**
Please drag and drop (and upload to the GitHub issue) an input file that I can use to replicate the error.

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC: `multiqc ./*.ReadsPerGene.out.tab -o ./ -n star_readsPerGene`
 - MultiQC Version: "MultiQC v0.7"
 - Operating System: "Linux version 2.6.32-696.28.1.el6.x86_64 (mockbuild@x86-033.build.eng.bos.redhat.com) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC) )"
 - Python Version: "Python-2.7.3"
 - Method of MultiQC installation: installed on cluster by admin

 **Additional context**

[SRR5062796.ReadsPerGene.out.tab.txt](https://github.com/ewels/MultiQC/files/2836844/SRR5062796.ReadsPerGene.out.tab.txt)
[SRR5062774.ReadsPerGene.out.tab.txt](https://github.com/ewels/MultiQC/files/2836845/SRR5062774.ReadsPerGene.out.tab.txt)

**Comment by Sumeet460** [comment]
Sorry, ReadsPerGene.out.tabl files are under "Additional context" subheading

**Comment by ewels** [comment]
Aha, I think found your problem!
```
This is MultiQC v0.7
```

Version 0.7 of MultiQC was released way back, 4th July 2016. Try updating to the latest version (v1.7) - I would guess this will solve the problem. You'll also get a tonne of new and improved functionality :)

Phil

**Comment by ewels** [comment]
Confirmed - this functionality was added on 6th Dec 2016 in this commit: 0e120aa882885f65aed3b78d26c994fe4c06b529

**Comment by Sumeet460** [comment]
Perfect! Thanks very much

best,
Sumeet
