### ISSUE TITLE
MultiQC can't find FastQC results 

### ISSUE THREAD

**Issue by MaryamQ6** [ewels/MultiQC#908]
**Description of bug:**
Hi,
I have used MultiQC multiple times on FastQC (v0.11.5) reports generated for RNA seq data, it worked fine on MacPro. the same QC version used for Exome Seq data and when I run MultiQC , the log was;

**MultiQC Error log:**
```
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/multiqc-1.8.dev0-py3.6.egg/multiqc/utils/config.py:45: YAMLLoadWarning: 
  *** Calling yaml.load() without Loader=... is deprecated.
  *** The default Loader is unsafe.
  *** Please read https://msg.pyyaml.org/load for full details.
  configs = yaml.load(f)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/multiqc-1.8.dev0-py3.6.egg/multiqc/utils/config.py:51: YAMLLoadWarning: 
  *** Calling yaml.load() without Loader=... is deprecated.
  *** The default Loader is unsafe.
  *** Please read https://msg.pyyaml.org/load for full details.
  sp = yaml.load(f)
[INFO   ]         multiqc : This is MultiQC v1.8.dev0
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching 'QC/'
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete

```

 the command was :
``` 
multiqc .
```
info:
 - MultiQC Version: 1.8.dev0
 - Operating System: macOS Mojave 10.14.2
 - Python Version: python3.6.3
 - Method of MultiQC installation: pip3

thanks,
I have attached couple of the files used. 
[Archive.zip](https://github.com/ewels/MultiQC/files/2922880/Archive.zip)

**Comment by ewels** [comment]
Hi @MaryamQ6,

Sorry to hear you're having problems. The zip file you attached only contains the HTML reports from FastQC, not the `fastqc_data.txt` or the original zip output with all files (including `fastqc_data.txt`), so that could be why it's not working for you. See https://multiqc.info/docs/#fastqc for details.

Let me know if this is not the case and I'll reopen the issue :)

Phil

**Comment by MaryamQ6** [comment]
Hi Phil 
apologies for wasting ur time on this. it worked perfectly. 
but i'm sure it worked before without it , I will keep it in mind and read the docs thoroughly next time  :D 
thank  you 
maryam

**Comment by ewels** [comment]
No problem at all! Glad that its working again :)
