### ISSUE TITLE
Samtools stats on nested directories

### ISSUE THREAD

**Issue by BELKHIR** [ewels/MultiQC#918]
**Description of bug:**
Running multiqc -m samtools will not find all the samtools stat files if they are nested in sub-directories.
ex: 
<pre>
/samtools_statsDir
       |
       sample1
           |
           samtoolsStats.txt
      sample2
          |
          samtoolsStats.txt
     sample3
     .....
</pre>
**MultiQC Error log:**
```
[INFO   ]        samtools : Found 1 stats reports
```

**File that triggers the error:**

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC: 

multiqc -m samtools samtools_statsDir

 - MultiQC Version:MultiQC v1.7
 - Operating System: Ubuntu 18.10
 - Python Version: Python 3.7.1 (default, Dec 14 2018, 19:28:38)
 - Method of MultiQC installation: pip

**Comment by ewels** [comment]
Hi @BELKHIR,

Have you tried using the `-d`/`--dirs` option? See https://multiqc.info/docs/#not-enough-samples-found

Phil

**Comment by BELKHIR** [comment]
This option solved the problem !
Thank's

**Comment by ewels** [comment]
Let me know if this works for you. If you're still having problems I'll reopen the issue..

Phil

**Comment by ewels** [comment]
Ah great! We simul-closed the issue 😆
