### ISSUE TITLE
Module request: add module for Mosdepth

### ISSUE THREAD

**Issue by fgvieira** [ewels/MultiQC#924]
**Tool Details**
 - Name of tool: Mosdepth
 - Tool homepage: https://github.com/brentp/mosdepth
 - Tool description: fast BAM/CRAM depth calculation for WGS, exome, or targeted sequencing
 - Data suitable for MultiQC plot(s): cumulative coverage density plot, coverage density plot (not calculated by `mosdepth`, but can be inferred; see code below)
 - Most interesting data for General Stats table: fraction of sites above X coverage; it is not given by `mosdepth` but can be calculated from `*.thresholds.bed.gz`

**Tool output:**
 - Log filename pattern: `*.mosdepth.region.dist.txt` if available. If previous not available, then `*.mosdepth.global.dist.txt`. And also `*.thresholds.bed.gz`
 - File contents

[$prefix.mosdepth.region.dist.txt](https://github.com/ewels/MultiQC/files/2957217/mosdepth.mosdepth.region.dist.txt)

[$prefix.mosdepth.global.dist.txt](https://github.com/ewels/MultiQC/files/2957222/mosdepth.mosdepth.global.dist.txt)

[$prefix.thresholds.bed.txt](https://github.com/ewels/MultiQC/files/2957224/mosdepth.thresholds.bed.txt)

**NOTES**

* To increase precision, mosdepth should be run as:
```
MOSDEPTH_PRECISION=5 mosdepth <args>
```

* It seems that someone already tried to include `mosdepth` into MultiQC on the repo [bcbio](https://github.com/MultiQC/MultiQC_bcbio/blob/master/multiqc_bcbio/bcbio.py)

* Here is some R code to illustrate the plotting of both distributions
```r
#!/usr/bin/env Rscript

library(ggplot2)

input_file <- "$prefix.mosdepth.global.dist.txt"

df <- read.table(input_file, sep = "\t", header = FALSE, col.names = c("chr", "coverage", "percent"))
df <- subset(df, chr == "total")
df$diff <- c(df$percent[1], diff(df$percent))

## Cumulative sum plot
ggplot(data = subset(df, percent > 0.02)) + geom_line(aes(x = coverage, y = percent))

## Histogram-like plot
ggplot(data = subset(df, percent > 0.02)) + geom_line(aes(x = coverage, y = diff))
```

**Comment by ewels** [comment]
Thanks @fgvieira!

@vladsaveliev - any thoughts about porting the bcbio code into a new stand-alone MultiQC module?

**Comment by vladsaveliev** [comment]
Good idea, makes sense to move it from bcbio into a separate module. I'll take a look at it!

**Comment by ewels** [comment]
Added in https://github.com/ewels/MultiQC/pull/928
