### ISSUE TITLE
Problem installing latest dev version

### ISSUE THREAD

**Issue by guidohooiveld** [ewels/MultiQC#925]
**Description of bug:**
I installed the latest release version of MultiQC, and then I would like to 'update' it by installing the latest development version. This last step doesn't work.
Since I am relatively new to all this, it likely could be that I overlooked something... Any pointer would be appreciated.

**MultiQC Error log:**
```
# install 'release' version (#worked fine!):
[guidoh@localhost guido$ pip install --user multiqc 
[guidoh@localhost guido]$  multiqc --version
multiqc, version 1.7
   

# then tried to upgrade to development version (#gave problem):
[guidoh@localhost guid $ pip install --user --upgrade --force-reinstall git+https://github.com/ewels/MultiQC.git

LOG:
[guidoh@localhost guido]$ pip install --user --upgrade --force-reinstall git+https://github.com/ewels/MultiQC.git
Collecting git+https://github.com/ewels/MultiQC.git
  Cloning https://github.com/ewels/MultiQC.git to /tmp/pip-req-build-PsLJep
Collecting click (from multiqc==1.8.dev0)
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
Collecting future>0.14.0 (from multiqc==1.8.dev0)
  Using cached https://files.pythonhosted.org/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz
Collecting lzstring (from multiqc==1.8.dev0)
  Using cached https://files.pythonhosted.org/packages/ab/0c/28347673b45e5f0975cdf1f6d69ede6ad049be873194c4e164d79aecd34c/lzstring-1.0.4.tar.gz
Collecting jinja2>=2.9 (from multiqc==1.8.dev0)
  Using cached https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl
Collecting matplotlib<3.0.0,>=2.1.1 (from multiqc==1.8.dev0)
  Using cached https://files.pythonhosted.org/packages/32/6b/0368cfa5e1d1ae169ab7dc78addda3fd5e6262e48d7373a9114bac7caff7/matplotlib-2.2.4-cp27-cp27mu-manylinux1_x86_64.whl
Collecting markdown (from multiqc==1.8.dev0)
  Using cached https://files.pythonhosted.org/packages/7a/6b/5600647404ba15545ec37d2f7f58844d690baf2f81f3a60b862e48f29287/Markdown-3.0.1-py2.py3-none-any.whl
Collecting numpy (from multiqc==1.8.dev0)
  Using cached https://files.pythonhosted.org/packages/c4/33/8ec8dcdb4ede5d453047bbdbd01916dbaccdb63e98bba60989718f5f0876/numpy-1.16.2-cp27-cp27mu-manylinux1_x86_64.whl
Collecting pyyaml>=4 (from multiqc==1.8.dev0)
  Could not find a version that satisfies the requirement pyyaml>=4 (from multiqc==1.8.dev0) (from versions: 3.10, 3.11, 3.12, 3.13b1, 3.13rc1, 3.13, 4.2b1, 4.2b2, 4.2b4, 5.1b1, 5.1b3, 5.1b5)
No matching distribution found for pyyaml>=4 (from multiqc==1.8.dev0)
[guidoh@localhost guido]$ 

```

**File that triggers the error:**
The error is triggered by the version of pyyaml that is installed on my machine. See last line of log above.
```
Collecting pyyaml>=4 (from multiqc==1.8.dev0)
  Could not find a version that satisfies the requirement pyyaml>=4 (from multiqc==1.8.dev0) (from versions: 3.10, 3.11, 3.12, 3.13b1, 3.13rc1, 3.13, 4.2b1, 4.2b2, 4.2b4, 5.1b1, 5.1b3, 5.1b5)
No matching distribution found for pyyaml>=4 (from multiqc==1.8.dev0)
```

Interestingly, installed version of pyyaml is 4.2b4, which fulfills the requirement of MultiqQC1.8dev...???
Updating pyyaml doesn't work either (latest version is already installed)...
```
[guidoh@localhost guido]$ pip install --user pyyaml
Requirement already satisfied: pyyaml in /usr/lib64/python2.7/site-packages (4.2b4)
```

**MultiQC run details (please complete the following):**
 - MultiQC Version: [multiqc, version 1.7]
 - Operating System: [Fedora 29 (Twenty Nine); Fedora Scientific Spin]
 - Python Version: [Python 2.7.15]
 - Method of MultiQC installation: [pip; see above]

**Comment by ewels** [comment]
Hi @guidohooiveld,

Sorry about this - it's due to a change I implemented recently because of an update that was rolled out in the PyYAML package. In short, it's a bit of a mess currently but should all be ironed out in a few days when v5.1 is released (see https://github.com/yaml/pyyaml/issues/193#issuecomment-468161506). The version you have installed is a beta version, which pip is probably ignoring.

I probably should remove that requirement, but it fixes another nasty error message and I hope that the problem you're seeing now will vanish any day now. In the mean time, I _think_ you should be able to install the dev version by cloning the files and installing manually:

```bash
git clone https://github.com/ewels/MultiQC.git
cd MultiQC
python setup.py install
```

I hope this helps - let me know how you get on!

Phil

**Comment by guidohooiveld** [comment]
Thanks for your prompt reply!
Manually installing did work for me (added also the  `--user` flag in the last line).
Thanks!

```
[guidoh@localhost MultiQC]$ python setup.py install --user
[guidoh@localhost MultiQC]$ multiqc --version
multiqc, version 1.8.dev0
```
