### ISSUE TITLE
Not sure why I didn't get an error

### ISSUE THREAD

**Issue by hepcat72** [ewels/MultiQC#931]
**Is your feature request related to a problem? Please describe.**

I have a workflow where I made a connection mistake.  I dragged the html output of FastQC to the multiQC's FastQC input.  When I ran the workflow, there was no error, but I couldn't understand why there was no multiQC record in my history (hidden or visible).  (There weren't hidden FastQC entries either, though I don't know if there should have been.)

**Describe the solution you'd like**

It took me awhile and a number of runs to realize the mistaken connection.  I'm not certain this is a problem caused by multiQC or something else, but I just thought there should be a parse error or something to indicate it failed.

**Describe alternatives you've considered**

Going "Doh!" and moving on.

**Additional context**

The mistake happened when I removed a step between FastQC and MultiQC where I flattened a paired collection.  I moved it to before FastQC and when I connected the 2, I dragged the wrong FastQC output.  There are other outputs in the workflow that are not getting into the history as well.  This is just the first one I've found a plausible reason for.  If I find out this was the side-effect of another issue, I'll close the issue.

**Comment by ewels** [comment]
Hi @hepcat72,

To clarify - you're requesting that MultiQC lets you know when it encounters a file that it can't do anything with? I don't think I really want to do that sorry. MultiQC was originally designed to be run on a folder full of results files, so it's very (very) common for it to encounter irrelevant files.

Let me know if I misunderstood your request..

Phil

**Comment by hepcat72** [comment]
I just ruled out MultiQC as the issue anyway.  I removed everything in a copy of the workflow except the multiqc portion and it worked fine.  But to clarify - I wasn't getting any MultiQC output in my history.

**Comment by ewels** [comment]
ok, sounds good. If MultiQC doesn't find any files to make a report with then it doesn't generate files. It still gives some stdout though.
