### ISSUE TITLE
Option to turn off target and href display in custom content module.

### ISSUE THREAD

**Issue by zxl124** [ewels/MultiQC#934]
**Is your feature request related to a problem? Please describe.**
Right now, the custom content module prints section name again before the text description. For example, using your example JSON file, after section header "Custom JSON File", the text description says "Custom JSON File This plot is a self-contained JSON file." The section name is unnecessarily repeated before the intended text description. 
![image](https://user-images.githubusercontent.com/37191025/55033430-6488f580-4fd0-11e9-8add-eaae6478c102.png)

**Describe the solution you'd like**
My understanding is that the custom content module does not currently offer a way to modify the `target` variable. It is always `None`. Therefore, according to the base module code, by default, the section name is printed before the text description. A solution would be to allow the custom content module to change the `target` variable to empty string.

**Describe alternatives you've considered**
I've tried to turn this off by adding some code in the config file. It didn't work.

**Comment by ewels** [comment]
Thanks for reporting this @zxl124, sorry that it's taken so long for me to get to! This has now been resolved by the recent work on Custom Content today:

![image](https://user-images.githubusercontent.com/465550/83194271-ab283180-a138-11ea-8995-1e0604dae6e2.png)

**Comment by zxl124** [comment]
Great. Thanks.
