### ISSUE TITLE
fastp after_filtering_q30_rate shows zero in the General Statistics table

### ISSUE THREAD

**Issue by pixuenan** [ewels/MultiQC#936]
**Description of bug:**
When show fastp data in the General Statistics table, the column of fastp `M Q30 reads` (`after_filtering_q30_rate`) showed zero. Besides, if you open the `Config Columns` table, you willl find the column `M Q30 reads` with description `Reads > Q30 after filtering (millions)` has an ID `after_filtering_q30_rate`, which seems incorrect.

**File that triggers the error:**
[fastp_failure.zip](https://github.com/ewels/MultiQC/files/3017073/fastp_failure.zip)

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC: `multiqc . -c multiqc_config.yaml -o multiqc`
 - MultiQC Version: v1.7dev0, v1.7
 - Operating System: CentOS 7, Ubuntu 16.04.5
 - Python Version: 3.6.7
 - Method of MultiQC installation: conda

**Comment by ewels** [comment]
Hi @pixuenan,

Thanks for reporting this. You're completely right - looks like a mistake when writing the module.

Header config:
https://github.com/ewels/MultiQC/blob/d4a622d837a76c8a17d7d0213f3f83dad5a61e0f/multiqc/modules/fastp/fastp.py#L288-L296

[Example input data](https://github.com/ewels/MultiQC_TestData/blob/ee428b87ce434bfbd69019804200689a4624818f/data/modules/fastp/fastp.json#L12-L20):
```json
"after_filtering": {
    "total_reads":16034314,
    "total_bases":1722358455,
    "q20_bases":1659758686,
    "q30_bases":1622286535,
    "q20_rate":0.963655,
    "q30_rate":0.941898,
    "gc_content":0.467941
}
```

So yeah - the `_rate` field is incorrectly being labelled and treated as a read count. Should be an easy fix.

Phil

**Comment by ewels** [comment]
Hi @pixuenan,

I've updated the code, it should make more sense now. If you could give it a spin and let me know how you get on, that would be great.

Thanks!

Phil

**Comment by pixuenan** [comment]
Hi @ewels,

The statistics of fastp Q30 is correct now, thanks for the quick reply and fix.

Regards,

Xuenan

**Comment by ewels** [comment]
Great! Thanks for getting back to me 👍
