### ISSUE TITLE
No multiqc_*.txt file for DamageProfiler

### ISSUE THREAD

**Issue by jfy133** [ewels/MultiQC#938]
**Description of bug:**

[This bug report is for/at the request of @apeltzer]

MultiQC does not generate a `multiqc_damageprofiler.txt` file in the `multiqc_data` directory.

Currently the only data from DamageProfiler module is recorded `multiqc_general_stats.txt`. 

Reason for the request is that it would be nice to have the option to get extra data for displaying (e.g. with qualimap_config in a `Multiqc_config.yml` file), but for this the column IDs are required.

 **Additional context**
Qualimap config documentation: https://multiqc.info/docs/#qualimap

**Comment by ewels** [comment]
You can tell @apeltzer that he should have written his data to a file then 😉 

Docs here: https://multiqc.info/docs/#step-4-writing-data-to-a-file

**Comment by apeltzer** [comment]
I will do that pretty soon ;-)

**Comment by apeltzer** [comment]
Done!

**Comment by apeltzer** [comment]
https://github.com/ewels/MultiQC/pull/939#discussion_r271218673

Maybe we should add the `--export` option first to our config and see whether this helps?
