### ISSUE TITLE
X axis label disappears from scatter plots if there are multiple data sets

### ISSUE THREAD

**Issue by berguner** [ewels/MultiQC#940]
Hello,

I have multiple data sets which I want to plot in the same section with switching buttons. I set up the `data_labels` list according to documentation with both `xlab` and `ylab` values. Y axis labels appear as they should but the X axis labels are ignored.

I inserted this code:
```python
try:
    xlab = 'data-xlab="{}"'.format(pconfig['data_labels'][k]['xlab'])
except:
    xlab = 'data-xlab="{}"'.format(name) if name != k+1 else ''
```
before this line: https://github.com/ewels/MultiQC/blob/9e58729dcc28ebef974561fed0aee026a0f3b3a4/multiqc/plots/scatter.py#L122

and updated that line as following:
```python
html += '<button class="btn btn-default btn-sm {a}" data-action="set_data" {y} {ym} {xl} data-newdata="{k}" data-target="{id}">{n}</button>\n'.format(a=active, id=pconfig['id'], n=name, y=ylab, ym=ymax, xl=xlab, k=k)
```
which seemed to fix the issue.

Best,
Bekir

**Comment by ewels** [comment]
Hi @berguner,

Nice catch! Would you mind submitting this change as a pull-request please?

Thanks!

Phil
