### ISSUE TITLE
No multiqc_report.html file after the run

### ISSUE THREAD

**Issue by BabaSaraki** [ewels/MultiQC#945]
**Description of bug:**

**MultiQC Error log:**
```
AttributeError: module 'matplotlib' has no attribute 'artist'
[INFO   ]          fastqc : Found 24 reports
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
```
```python
Traceback (most recent call last):
  File "/anaconda3/bin/multiqc", line 4, in <module>
    __import__('pkg_resources').run_script('multiqc==1.0.dev0', 'multiqc')
  File "/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/anaconda3/lib/python3.6/site-packages/multiqc-1.0.dev0-py3.6.egg/EGG-INFO/scripts/multiqc", line 581, in <module>
    multiqc()
  File "/anaconda3/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/anaconda3/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/anaconda3/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/multiqc-1.0.dev0-py3.6.egg/EGG-INFO/scripts/multiqc", line 509, in multiqc
    report_output = j_template.render(report=report, config=config)
  File "/anaconda3/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/anaconda3/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/anaconda3/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/var/folders/k3/w52kql1n5j35zrr6xdkl__s80000gn/T/tmp94ij4z2m/base.html", line 19, in top-level template code
    {% include 'includes.html' %}
  File "/var/folders/k3/w52kql1n5j35zrr6xdkl__s80000gn/T/tmp94ij4z2m/includes.html", line 33, in top-level template code
    <style type="text/css">{{ include_file(css_href, None) }}</style>
  File "/anaconda3/lib/python3.6/site-packages/multiqc-1.0.dev0-py3.6.egg/EGG-INFO/scripts/multiqc", line 496, in include_file
    with io.open (os.path.join(fdir, name), "r", encoding='utf-8') as f:
  File "/anaconda3/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
(base) 
```

**File that triggers the error:**
[Data.zip](https://github.com/ewels/MultiQC/files/3042011/Data.zip)

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC: multiqc .
 - MultiQC Version: Multiqc v1.7
 - Operating System: macOS Mojave 10.14.3
 - Python Version: Python 3.6.8
 - Method of MultiQC installation: conda

 **Additional context**

**Comment by ewels** [comment]
Hi @BabaSaraki,

Thanks for this! It's a very strange bug. When I test your data it runs fine for me:

```console
$ multiqc -f fastqc/
[INFO   ]         multiqc : This is MultiQC v1.8.dev0 (a5c095b)
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching 'fastqc/'
Searching 48 files..  [####################################]  100%
[INFO   ]          fastqc : Found 24 reports
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete
```

Correctly generating the HTML report (attached here for your convenience: 
[multiqc_report.html.zip](https://github.com/ewels/MultiQC/files/3043351/multiqc_report.html.zip)).

The log you pasted still looks a little incomplete though - it's missing the first two lines which confirm the need the complete log though, it looks like you're missing the first few lines out output here. It would also be useful to have the _verbose_ output with all the debug messages. To get this you need to add the flag `-v` to the command:

```bash
multiqc -v .
```

This will give a large amount of output on the screen, so you can write this directly to a file using bash redirection (see [this link](https://www.brianstorti.com/understanding-shell-script-idiom-redirect/) for an explanation):

```bash
multiqc -v . &> multiqc_log.txt
```

If you can then attach that `multiqc_log.txt` file to this issue, it will help me to debug your problem..

One hint that something strange is going on is the fact that you say you're running MultiQC v1.7, but that the error traceback lists the following file path:
```
/anaconda3/lib/python3.6/site-packages/multiqc-1.0.dev0-py3.6.egg/
```
Suggesting MultiQC v1.0dev (which is super old now).

Any more information about exactly how you installed MultiQC using conda would also be good.

Thanks!

Phil

**Comment by BabaSaraki** [comment]
Hi @ewels,

Thank you for the guidance. I am glad that I finally got the HTML file report from your end. I downloaded it and open. It works well. 

Regarding the log, I followed the steps you mentioned above and here is the [multiqc_log.txt] file attached 
[multiqc_log.txt](https://github.com/ewels/MultiQC/files/3045011/multiqc_log.txt).

As for the MultiQC version, I mistakenly assumed v1.7 from this output:

[[WARNING]         multiqc : MultiQC Version v1.7 now available!
[INFO   ]         multiqc : This is MultiQC v1.0.dev0
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
]

I installed MultiQC using conda as provided from multiqc site (https://multiqc.info/docs/#installing-multiqc) using the command line  [conda install -c bioconda multiqc
].

Thank you so much for your time and mentorship. Hopefully I will be able to use my system to run multiqc after debug. 

Best regards 

Umar.

**Comment by ewels** [comment]
Aha! Yes, v1.0 is pretty old now so I'm not surprised that it broke in weird and wonderful ways. Very strange that conda gave you that though, it should use the latest version by default... The single command approach is maybe a little too simplistic now perhaps (it used to work), you can see more comprehensive documentation about using bioconda here: https://bioconda.github.io/index.html#using-bioconda

I'll close this issue now, but let me know if you run in to further problems - we can always reopen it :+1:

Phil
