### ISSUE TITLE
Handling multiple featureCounts summary files

### ISSUE THREAD

**Issue by cashoes** [ewels/MultiQC#947]
I routinely summarize at both the gene and exon level using featureCounts (using `-g 'gene_id'` or `'exon_id'`). This results in separate summary files (`gene_counts.summary` and `exon_counts.summary`) and MultiQC appears to only recognize one of those 2 files.

Is there currently support for creating report output for multiple distinct featureCounts summary outputs?

**Comment by ewels** [comment]
Hi @cashoes,

Is the output file format different between the two? Could you post a couple of example files please? I guess it must be, as MultiQC looks for anything called `*.summary` to find the files.

Phil

**Comment by ewels** [comment]
File parsing code is here if you're curious:
https://github.com/ewels/MultiQC/blob/1f78c5a2441e0f6842aac0d7fdfa45d89a943219/multiqc/modules/featureCounts/feature_counts.py#L52-L78

**Comment by ewels** [comment]
Closing this issue now due to lack of response. But I'm 90% sure that this issue can be resolved with `-d` or something similar. See the docs: https://multiqc.info/docs/#clashing-sample-names
