### ISSUE TITLE
Make a bioconda package

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#95]
Build a conda package based on the PyPI distribution and submit to Anaconda.org

Tutorial here: http://conda.pydata.org/docs/build_tutorials/pkgs.html

**Comment by ewels** [comment]
Or bioconda perhaps: https://github.com/bioconda/recipes

**Comment by dakl** [comment]
I might be able to do some work on this if that's ok.

**Comment by ewels** [comment]
Absolutely - as you may have guessed by the repeatedly changing milestone for this issue, I haven't got around to figuring out how this works yet.. I'd be interested to know what's required!

**Comment by ewels** [comment]
Pull request [now open](https://github.com/bioconda/bioconda-recipes/pull/887)..

**Comment by ewels** [comment]
And merged! https://github.com/bioconda/bioconda-recipes/pull/887#event-567454518
