### ISSUE TITLE
Bulk sample renaming breaks when sample IDs start with a number

### ISSUE THREAD

**Issue by RoxaneLS** [ewels/MultiQC#951]
**Description of bug:**
It seems that the annotation does not work if a sample name is a number (unfortunately that's our case for all clinical de-identified samples). And I can confirm that there is no whitespace hidden in my data.

It wasn't an issue before as our numbers started with '0', which I suspect MultiQC would have treated as strings to avoid losing the leading 0 in the sample names. I tried having the sample names between quotes in the annotation file but that didn't work.

Interestingly, samples are annotated fine (if they do not start with [1-9]) as long as they appear BEFORE the samples starting with [1-9]. Annotation for sample names which are string does not work if they appear AFTER a sample name starting with [1-9].

I can send through some examples if you wanna have a look. Reproduced the bug with both multiqc 1.5 and 1.6.

I've got the feeling it could be an easy fix by setting the sample names to string by default.

**MultiQC run details:**
 - Command used to run MultiQC:

```bash
$ multiqc \
  /pathology/NGS/Samples/Testing/rlegaie//190312_NS500817_0475_TEST2/QC/MultiQC \
  /pathology/NGS/Samples/Testing/rlegaie//190312_NS500817_0475_TEST2/2345678/QC \
  /pathology/NGS/Samples/Testing/rlegaie//190312_NS500817_0475_TEST2/A1000093/QC \
  /pathology/NGS/Samples/Testing/rlegaie//190312_NS500817_0475_TEST2/NA12878/QC \
  /pathology/NGS/Samples/Testing/rlegaie//190312_NS500817_0475_TEST2/NTC/QC \
  /pathology/NGS/Samples/Testing/rlegaie//190312_NS500817_0475_TEST2/SampleB/QC \
  /pathology/NGS/Samples/Testing/rlegaie//190312_NS500817_0475_TEST2/SampleD/QC \
  -f \
  -o /pathology/NGS/Samples/Testing/rlegaie//190312_NS500817_0475_TEST2/QC/MultiQC \
  -n multiqc_test \
  -c /researchers/roxane.legaie/pmc-scripts//config_files/multiqc_config.PHCP.yaml \
  --sample-names /pathology/NGS/Samples/Testing/rlegaie//190312_NS500817_0475_TEST2/QC/MultiQC/multiqc_sample_names.tsv
```

 - MultiQC Version: multiqc/1.6
 - Operating System: linux
 - Python Version: Python 3.6.5 
 - Method of MultiQC installation: not sure

See screenshot and input / output files attached.

![annotation_bug_screenshot](https://user-images.githubusercontent.com/13159414/56108203-dfb94800-5f8d-11e9-9ddf-96ee29ada6cc.png)

[190312_NS500817_0475_TEST2.tar.gz](https://github.com/ewels/MultiQC/files/3078478/190312_NS500817_0475_TEST2.tar.gz)

**Comment by RoxaneLS** [comment]
Hi @ewels , how is parenthood going? :)  I was wondering if you'd have any chance to look into this issue in the coming weeks, as it's a major blocker for us to use MultiQC in our clinical lab - and I've got the feeling it could be a quick & easy fix.

**Comment by ewels** [comment]
Good thanks! Unfortunately for you, Sweden has fantastic parental leave though I'm afraid. My priority when I do get time to sit down with MultiQC code (as opposed to replying to issue comments on my phone) will be to go through the pull-requests that people have submitted. After that I'll go through the bug issues such as this one.

Also, I'm not actually sure how to fix this one. I guess that it's jQuery automatically parsing the strings in these lines:
https://github.com/ewels/MultiQC/blob/39d83c2e5991f8911e7f522987a1c8f5851c9c5b/multiqc/templates/default/assets/js/multiqc_toolbox.js#L620-L621

..and I don't know how to prevent jQuery from automatically typing these values. Any ideas welcome!

**Comment by RoxaneLS** [comment]
Hi Phil, looks like you're back to working on MultiQC, which is great news! :)
Are you able to look into this bug now?

**Comment by ewels** [comment]
Added to the v1.8 release milestone 😄

**Comment by RoxaneLS** [comment]
Best news today!! Thank you!

Any ETA? :)

Le mer. 13 nov. 2019 à 20:08, Phil Ewels <notifications@github.com> a
écrit :

**Comment by ewels** [comment]
Nope, sorry.. You can watch the progress bar creep forward though: https://github.com/ewels/MultiQC/milestone/14

**Comment by ewels** [comment]
Ok, when I open your example report in Chrome and view the web inspector, I can see that there is a javascript error when applying the sample renaming rules:

![image](https://user-images.githubusercontent.com/465550/68764196-89db7a00-061a-11ea-978d-53e871ba3ee1.png)

This comes to this line of code, where we're trying to do a string replacement on the sample names within tables:

![image](https://user-images.githubusercontent.com/465550/68764237-9e1f7700-061a-11ea-80ee-d221ae6332ba.png)

Sure enough, the error is that the string `.replace()` function doesn't exist for the name variable. And that's because JavaScript is typing it as a number when it dynamically types the variable. If I force it to be a string, the error goes away and I think everything seems to work. Fixed MultiQC report: 
[multiqc_testannot.html.zip](https://github.com/ewels/MultiQC/files/3841115/multiqc_testannot.html.zip)

If this really is the full extend of the problem, then it's almost embarrassingly easy and quick for me to fix... 🙄 Sorry, I thought it would take me a lot longer than this! 😅

**Comment by ewels** [comment]
Yup - an extra 8 characters...!

If you could have a go with the v1.8dev code and confirm that the problem is fixed, that would be perfect. Let me know if you hit any problems.

Phil

**Comment by RoxaneLS** [comment]
OK I'll have a try. Thanks!

Le mer. 13 nov. 2019 à 23:42, Phil Ewels <notifications@github.com> a
écrit :
