### ISSUE TITLE
 Oops! The 'bbmap' MultiQC module broke... 

### ISSUE THREAD

**Issue by magruca** [ewels/MultiQC#952]
**Description of bug:**
I run bbduk for trimming which generates trim reports. MutliQC finds them, but then breaks with the following error. I'm using version 1.7

**MultiQC Error log:**
```
[INFO   ]         multiqc : This is MultiQC v1.7
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching 'qc/'
Searching 252 files..  [####################################]  100%          
[INFO   ]          preseq : Found 24 reports
[INFO   ]           rseqc : Found 12 read_distribution reports
[INFO   ]           rseqc : Found 12 read_duplication reports
[INFO   ]           rseqc : Found 12 infer_experiment reports
[INFO   ]        samtools : Found 12 flagstat reports
[INFO   ]           bbmap : Found 12 reports
[ERROR  ]         multiqc : Oops! The 'bbmap' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    qc/trimstats/41_DMSO_rep_2_S12_R1_001.refstats.txt
============================================================
Module bbmap raised an exception: Traceback (most recent call last):
  File "/Users/magr0763/.local/bin/multiqc", line 440, in multiqc
    output = mod()
  File "/Users/magr0763/.local/lib/python3.6/site-packages/multiqc/modules/bbmap/bbmap.py", line 62, in __init__
    plot = self.plot(file_type)
  File "/Users/magr0763/.local/lib/python3.6/site-packages/multiqc/modules/bbmap/bbmap.py", line 155, in plot
    plot_params=plot_params)
  File "/Users/magr0763/.local/lib/python3.6/site-packages/multiqc/modules/bbmap/plot_basic_hist.py", line 37, in plot_basic_hist
    'xmax': xmax
UnboundLocalError: local variable 'xmax' referenced before assignment
============================================================
[INFO   ]          fastqc : Found 24 reports
[INFO   ]         multiqc : Compressing plot data
```

**File that triggers the error:**
Please drag and drop (and upload to the GitHub issue) an input file that I can use to replicate the error.

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC: [eg. `multiqc .`]
 - MultiQC Version: [eg. MultiQC v1.1]
 - Operating System: [eg. macOS Sierra 10.12.5]
 - Python Version: [eg. Python 2.7.12]
 - Method of MultiQC installation: [eg. pip, conda, manual]

 **Additional context**
Thanks for the help!

**Comment by ewels** [comment]
Calling @boulund ☎️ 🆘 😅

**Comment by boulund** [comment]
Rats. It's a quick fix, but I'd love to see the file causes the issue.

**Comment by magruca** [comment]
Not entirely sure which file it is -- I have a few spitting out in the pipeline, so I've attached all of them. If you want me to go through one by one and figure out which it is, let me know.

[SRR1105736.ehist.txt](https://github.com/ewels/MultiQC/files/3103793/SRR1105736.ehist.txt)
[SRR1105736.refstats.txt](https://github.com/ewels/MultiQC/files/3103794/SRR1105736.refstats.txt)
[SRR1105736.trimstats.txt](https://github.com/ewels/MultiQC/files/3103795/SRR1105736.trimstats.txt)

I'd love to see some of the trimstats stuff included in the report.

Thanks!

**Comment by boulund** [comment]
@magruca I would also like to see trimstats stuff included in the report (I'd like to see stats both before and after as well). How would you like to see that information presented? We already have an issue for BBMap's `pileup.sh` (#768) that I think would be a similar visualization problem.

**Comment by magruca** [comment]
In terms of the trimstats, I was mostly just thinking a similar setup to trimmomatic/cutadapt with it being presented in the general summary stats table (% trimmed). Maybe that's what it's supposed to do currently? I haven't actually pried into the code to see what the functionality is supposed to be. Obviously the refstats are a lot more similar to the pileup.sh issue you referenced. I agree that the stacked bar gets kind of messy (like the one attached here) and liked the line plot idea. 
![stacked_bar_coverage](https://user-images.githubusercontent.com/37707530/56615270-f851df80-65d7-11e9-8fde-611969ee6d17.png)

Alternatively, just a simple summary table/column of % total coverage, RPKM, etc. per sample would be nice. I tend to do a lot of nascent data processing, but it's actually super helpful to get at ChIP and ATAC quality, too.

I just tend to like the flexibility with BBMap utilities which is why I go to them a lot. I also have them both incorporated into the nascent pipeline which we just published to nfcores (https://github.com/nf-core/nascent), so it would be nice to tack those outputs onto the final report.

**Comment by boulund** [comment]
I checked the files you provided. It's pretty obvious which one caused the issue: the ehist file contains no data for plotting, just the header and one empty line. I've made a fix for that issue now (in the general bbmap file parser, so it's used for all file types), will push it to the PR branch soon.

The trimstats file is parsed and presented in the report already, and shows a table with % trimmed per sample, so I guess that's what you wanted? It's not in the general summary table, however. 

I unfortunately pretty much have a negative amount of time to work on the other issues at the moment, so unless anyone else is willing to chip in I cannot give an estimate of when I'd be able to make any progress on them :(.

**Comment by magruca** [comment]
Well I feel pretty silly now for not checking that, sorry! Thanks for adding the bug checker, though. I'll have to go back and see if I can figure out what's causing the error because it's only in about half of my projects.

The trimstats % in a table now is fine, thanks! It just hasn't been showing up because of this error.

No worries about the rest -- like Phil mentioned this is pretty similar to another issue I had opened.

**Comment by tamuanand** [comment]
I have a similar request - would like to see MultiQC produce results for bbduk log files.  I am currently using MultiQC 1.7  

Given below is a sample output from the log file after running bbduk.sh

Input is being processed as unpaired
Started output streams: 0.020 seconds.
Processing time:                26.261 seconds.

Input:                          25397904 reads          1890020301 bases.
QTrimmed:                       5607 reads (0.02%)      129652 bases (0.01%)
KTrimmed:                       720994 reads (2.84%)    6414649 bases (0.34%)
Total Removed:                  21148 reads (0.08%)     6544301 bases (0.35%)
Result:                         25376756 reads (99.92%)         1883476000 bases (99.65%)

Time:                           26.552 seconds.
Reads Processed:      25397k    956.53k reads/sec
Bases Processed:       1890m    71.18m bases/sec

**Comment by boulund** [comment]
I agree, I would also want that. I haven't got a time plan for implementing it though. Feel free to make a PR if you want to! :)

**Comment by ewels** [comment]
Hi all,

I think that the original error reported in this issue is now fixed by @boulund (thanks!). There are a few other feature requests, one that I moved into its own issue (#1053). If there's anything else, please make a new issue about it with all of the required information about what you would like to see along with some example data.

Thanks,

Phil
