### ISSUE TITLE
multiQC run on several qualimap reports

### ISSUE THREAD

**Issue by jpflorido** [ewels/MultiQC#960]
Hi!

**Description of bug:**
MultiQC run on several qualimap reports does not produce information on each sample

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC: ```multiqc -o /home/petete/output//multiqc_bamqc/ /path/to/input/samples/qc/```
 - MultiQC Version: [eg. MultiQC v1.1]
 - Operating System: Red Hat 7.3
 - Python Version: Python 2.7.12
 - Method of MultiQC installation: pip

Although multiQC log says
[INFO   ]        qualimap : Found 2 BamQC reports

multiqc report does not produce information per sample. For general statistics, it produces this strange output, with three rows (the first two are sample names and the third is named qualimap)

![image](https://user-images.githubusercontent.com/5921257/56747986-4a813500-677f-11e9-8e1b-e3245c333197.png)

And for coverage histogram (similar for the rest of plots), if you click on the curve, it provides values on a sample named "qualimap."
![image](https://user-images.githubusercontent.com/5921257/56748007-566cf700-677f-11e9-8b86-fd9fa3406e4e.png)

Any ideas?
Thanks!
Javier

**Comment by fortuno** [comment]
Not sure if related but just in case. I saw similar behavior for other tools. In my case with Salmon, Fragment Length Distribution plot.

Logs:
[INFO   ]          salmon : Found 6 fragment length distributions

Plot:
![salmon_plot](https://user-images.githubusercontent.com/18450901/56795410-bd86bc00-6810-11e9-90ad-f7a56d40ba62.png)

Only one of the 6 found distributions (one per sample) is plotted.

Thanks in advance,
Francisco

**Comment by ewels** [comment]
Hi @jpflorido,

Please see the documentation:
https://multiqc.info/docs/#not-enough-samples-found
https://multiqc.info/docs/#clashing-sample-names

If this doesn't solve the issue, let me know and I can take a closer look.

@fortuno - are you sure that only one sample is plotted? I'm pretty sure that all are plotted there, but just have identical profiles _(I can spot some blue anti-aliasing behind the pink line, sometime tells me that I've spent too long staring at MultiQC plots..!)_. I'd recommend taking a look at the raw data to check.

Phil
