### ISSUE TITLE
Sample renaming via command line vs Toolbox

### ISSUE THREAD

**Issue by jpflorido** [ewels/MultiQC#962]
**Description of bug:**
I'm trying to rename sample names from command line, but the conversion is not working for me. However, via MultiQC toolbox  ("Rename Samples") it works.

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC: [eg. `multiqc --sample-names /path/to/renaming.txt -o /home/petete/output//multiqc_bamqc/ /path/to/input/samples/qc/`]
 - MultiQC Version: 1.7
 - Operating System:Red Hat 7.3
 - Python Version: Python 2.7.12
 - Method of MultiQC installation: pip

where `renaming.txt` is a tab delimited file with the following content:
```
MultiQC_Names	Original_Names
qG1231231_R1_JOINED	NA12878
```

In the report generated by MultiQC, it appears at the top of it `MultiQC_Names` and `Original_Names` buttons for sample renaming, but no action is performed, that is, the sample name remains the same.

However, when editing the _MultiQC Toolbox -> Renaming Samples_, if the content of `renaming.txt` (without the header) is pasted into the text area provided when clicking on `Click here for bulk input`, the sample names change when clicking on the buttons.

Probably, I am missing something, My question is, why `--sample-names` is not working (for me)?
Thanks!

**Comment by ewels** [comment]
Hi @jpflorido,

Is it possible to upload a set of files so that I can run MultiQC myself and reproduce the problem? Or even just the `multiqc_report.html` would be useful.

Thanks,

Phil

**Comment by ewels** [comment]
Hi @jpflorido,

Just revisiting old issues - are you able to provide any more information / help / files about this issue? I'll try to take a look but it's usually pretty difficult to replicate (and thus fix) these kinds of issues without files that trigger the problem.

Thanks,

Phil

**Comment by ewels** [comment]
Hi @jpflorido,

I've just gone back and tested this again. I also tried to use your file as closely as I could, though switching for some names that I had in the report. Everything worked and I couldn't find any problems.

I'll close this issue now, but if you're still having problems with the latest version of the code and you have a complete set of files that I can try running to replicate the error, I'd be happy to reopen it.

Thanks,

Phil
