### ISSUE TITLE
GATK module doesn't parse picard CollectWgsMetrics output

### ISSUE THREAD

**Issue by btrspg** [ewels/MultiQC#966]
**Description of bug:**

I have two collectwgsmetrics files, one of them was from GATK4 and the other one was from picard.

command like 

```
# gatk4
gatk CollectWgsMetrics --INPUT bam --OUTPUT wgs.metrics --REFERENCE_SEQUENCE hg19.fasta
# picard
picard CollectWgsMetrics  \
    I=test.bam \
    O=test.collect_wgs_metrics.txt \
    R=hg19.fasta
```

**MultiQC Error log:**
```

[INFO   ]         multiqc : This is MultiQC v1.7
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching './'
Searching 3 files..  [####################################]  100%
[INFO   ]          picard : Found 1 WgsMetrics reports
[INFO   ]         multiqc : Compressing plot data
[WARNING]         multiqc : Deleting    : multiqc_report.html   (-f was specified)
[WARNING]         multiqc : Deleting    : multiqc_data   (-f was specified)
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete

```

**File that triggers the error:**
But the multiqc can only recognize the GATK-file. Here are the two files:

[test1.wgs.metrics.txt](https://github.com/ewels/MultiQC/files/3155375/test1.wgs.metrics.txt)
[test2.wgs.metrics.txt](https://github.com/ewels/MultiQC/files/3155376/test2.wgs.metrics.txt)

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC: [`multiqc -f ./`]
 - MultiQC Version: [ MultiQC v1.7]
 - Operating System: [Linux archer 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux]
 - Python Version: [Python 3.5.6 :: Anaconda, Inc.]
 - Method of MultiQC installation: [pipl]

 **Additional context**

**Comment by ewels** [comment]
Many thanks for reporting this @btrspg and apologies for the very long time it took to get to it.

Thankfully this has now been fixed in #1114 - tested on your example files and confirmed 👍 

Phil
