### ISSUE TITLE
Bamtools stats module not finding results

### ISSUE THREAD

**Issue by fhorvat** [ewels/MultiQC#978]
**Description of bug:**
After running bamtools stats on my bam files and then running multiqc, there is no report generated. 

**MultiQC Error log:**
```
[INFO   ]         multiqc : This is MultiQC v1.7
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
[INFO   ]         multiqc : Only using modules bamtools
Searching 19 files..  [####################################]  100%
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
```

**File that triggers the error:**
[s_1C_KO_r1.PE.log](https://github.com/ewels/MultiQC/files/3290105/s_1C_KO_r1.PE.log)

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC:
```
bamtools stats -in $FILE > ${BASE}.log
multiqc . -m bamtools
```
 - MultiQC Version: MultiQC v1.7
 - Operating System: SUSE Linux Enterprise Server 12
 - Python Version: Python 3.6.5 
 - Method of MultiQC installation: pip

 **Additional context**
I didn't touch any of the config files or created my config.yaml. Multiqc works properly on other files (e. g. STAR Log.final.out, fastqc output...) and creates a report.

**Comment by ewels** [comment]
Hi @fhorvat,

It looks like the bamtools search pattern only looks in the first two lines of every file:
https://github.com/ewels/MultiQC/blob/505e01963d803b8bd76a067ac749515ebe946cbc/multiqc/utils/search_patterns.yaml#L12-L15

Your file has an extra blank newline at the top, meaning that it doesn't get to the pattern properly. Removing this should make everything work.

This pattern is probably a little excessively strict, so I've pushed it from two lines to 10 lines in 98f19ad. This will go out in the next release, but I'm not sure when that will be (I'm on paternity leave at the moment). In the mean time, you can use a custom MultiQC config to overwrite the defaults search pattern:

```yaml
sp:
  bamtools/stats: 
      contents: 'Stats for BAM file(s):' 
      shared: true 
      num_lines: 10 
```

I hope this helps - thanks for reporting!

Phil
