### ISSUE TITLE
Oops! The 'fastqc' MultiQC module broke...

### ISSUE THREAD

**Issue by dongxuzheng** [ewels/MultiQC#983]
**Description of bug:**
multiqc : Oops! The 'fastqc' MultiQC module broke...
**MultiQC Error log:**
```
Module fastqc raised an exception: Traceback (most recent call last):
  File "/home/u2125/anaconda3/bin/multiqc", line 440, in multiqc
    output = mod()
  File "/home/u2125/anaconda3/lib/python3.6/site-packages/multiqc/modules/fastqc/fastqc.py", line 65, in __init__
    r_data = fh.read().decode('utf8')
  File "/home/u2125/anaconda3/lib/python3.6/zipfile.py", line 835, in read
    buf += self._read1(self.MAX_N)
  File "/home/u2125/anaconda3/lib/python3.6/zipfile.py", line 939, in _read1
    self._update_crc(data)
  File "/home/u2125/anaconda3/lib/python3.6/zipfile.py", line 867, in _update_crc
    raise BadZipFile("Bad CRC-32 for file %r" % self.name)
zipfile.BadZipFile: Bad CRC-32 for file 's42008_1_paired_fastqc/fastqc_data.txt'
```

**File that triggers the error:**
Please drag and drop (and upload to the GitHub issue) an input file that I can use to replicate the error.

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC: [ `multiqc ./`]
 - MultiQC Version: [ MultiQC v1.7]
 - Operating System: [Ubuntu 16.04.6 LTS]
 - Python Version: [python3.6]
 - Method of MultiQC installation: [conda install multiqc]

 **Additional context**
My fastqc reports come from FastQC v0.11.4.
I use another machine for multiqc and the FastQC is v0.11.8
I noticed someone had raised the same problem but it was four years ago. So I do not know how to figure it out. Thanks in advanced.

**Comment by ewels** [comment]
x-ref https://github.com/ewels/MultiQC/issues/943 and https://github.com/ewels/MultiQC/issues/959

Basically, I think that your zip files are corrupted for some reason. If you uncompress and recompress them it should work.

If you think that this is a problem with MultiQC itself, please let me know and I'll reopen the issue.

Phil

**Comment by dongxuzheng** [comment]
I will double check my zip files. Thanks for your time and reply.

Phil Ewels <notifications@github.com> 于 2019年7月2日周二 下午11:31写道：
