### ISSUE TITLE
MultiQC not running 

### ISSUE THREAD

**Issue by thesimpleton** [ewels/MultiQC#993]
Hi, I am completely new to coding and would appreciate anyone's help. I tried to run Multiqc after downloading it on Anaconda but not sure why it just stopped running with the following output. 

```console
(py3.6) HQHongs-MacBook-Air:~ hqhong$ multiqc .
/anaconda3/envs/py3.6/lib/python3.6/site-packages/multiqc-1.0.dev0-py3.6.egg/multiqc/utils/config.py:44: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  configs = yaml.load(f)
/anaconda3/envs/py3.6/lib/python3.6/site-packages/multiqc-1.0.dev0-py3.6.egg/multiqc/utils/config.py:50: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  sp = yaml.load(f)
[WARNING]         multiqc : MultiQC Version v1.7 now available!
[INFO   ]         multiqc : This is MultiQC v1.0.dev0
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
```

**Comment by ewels** [comment]
Hi @thesimpleton,

I'm not sure how you fetched MultiQC from Anaconda or why you got this version, but you're running version 1.0dev which is very old. I'd recommend getting at least version 1.7, or preferably v1.8dev (I'm due to do a new release of v1.8 pretty soon, but it's been delayed because I'm currently away on paternity leave).

As to why it would stop at that point - this seems pretty strange. Usually if it crashes it will throw an error instead of exiting silently. But let's get you upgraded first and then if it still happens we can look into it..

Phil

**Comment by thesimpleton** [comment]
Thank you for the prompt reply, Phil. Congrats on your newborn too. 

Sure, I will try it out again after downloading a newer version of Anaconda.

**Comment by thesimpleton** [comment]
Hi Phil,

I am still facing issues with my download. I basically followed the instruction “Installing with conda https://multiqc.info/docs/#installing-with-conda <https://multiqc.info/docs/#installing-with-conda> “ after installing python, and the version I get is 1.0.dev. I tried to update using pip --update multiqc

but I get such error
Usage:   
  pip <command> [options]

no such option: --update

In addition, I also used 'conda update multiqc’. This command works but the version remains 1.0.dev. 

Would deeply appreciate if you could advise. 

Many thanks in advance.

**Comment by ewels** [comment]
Hi @thesimpleton,

Is this an otherwise empty conda environment? There could be some strange dependency resolution going on.

Try forcing conda to use a specific version:

```bash
conda install multiqc=1.7
```

Phil

**Comment by thesimpleton** [comment]
Dear Phil,

Yeap, it is an otherwise empty environment. When I tried to specify the version, I encounter these. 

(conda_test2) HQHongs-MacBook-Air:~ hqhong$ conda install -c bioconda multiqc=1.7
Collecting package metadata (current_repodata.json): done
Solving environment: failed with current_repodata.json, will retry with next repodata source.
Initial quick solve with frozen env failed.  Unfreezing env and trying again.
Solving environment: failed with current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed
Initial quick solve with frozen env failed.  Unfreezing env and trying again.
Solving environment: failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:



Package libffi conflicts for:
python=3.6 -> libffi[version='3.2.*|>=3.2.1,<4.0a0']
Package tk conflicts for:
python=3.6 -> tk[version='8.6.*|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0']
Package requests conflicts for:
multiqc=1.7 -> requests
Package markdown conflicts for:
multiqc=1.7 -> markdown
Package sqlite conflicts for:
python=3.6 -> sqlite[version='>=3.20.1,<4.0a0|>=3.22.0,<4.0a0|>=3.23.1,<4.0a0|>=3.24.0,<4.0a0|>=3.25.2,<4.0a0|>=3.26.0,<4.0a0']
Package spectra conflicts for:
multiqc=1.7 -> spectra[version='>=0.0.10']
Package readline conflicts for:
python=3.6 -> readline[version='7.*|>=7.0,<8.0a0']
Package click conflicts for:
multiqc=1.7 -> click
Package libcxx conflicts for:
python=3.6 -> libcxx[version='>=4.0.1']
Package pip conflicts for:
python=3.6 -> pip
Package openssl conflicts for:
python=3.6 -> openssl[version='1.0.*|1.0.*,>=1.0.2l,<1.0.3a|>=1.0.2m,<1.0.3a|>=1.0.2n,<1.0.3a|>=1.0.2o,<1.0.3a|>=1.1.1a,<1.1.2a']
Package xz conflicts for:
python=3.6 -> xz[version='>=5.2.3,<6.0a0|>=5.2.4,<6.0a0']
Package jinja2 conflicts for:
multiqc=1.7 -> jinja2[version='>=2.9']
Package future conflicts for:
multiqc=1.7 -> future[version='>0.14.0']
Package ncurses conflicts for:
python=3.6 -> ncurses[version='>=6.0,<7.0a0|>=6.1,<7.0a0']
Package setuptools conflicts for:
multiqc=1.7 -> setuptools
Package zlib conflicts for:
python=3.6 -> zlib[version='>=1.2.11,<1.3.0a0']
Package numpy conflicts for:
multiqc=1.7 -> numpy
Package simplejson conflicts for:
multiqc=1.7 -> simplejson
Package pyyaml conflicts for:
multiqc=1.7 -> pyyaml
Package lzstring conflicts for:
multiqc=1.7 -> lzstring
Package matplotlib conflicts for:
multiqc=1.7 -> matplotlib[version='>=2.1.1|>=2.1.1,<3.0.0']


I also tried “condo install multiqc=1.7 
….
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:
- multiqc=1.7 

Sorry for pasting the whole chunk of error messages as I do not know what will be useful for troubleshooting.

**Comment by ewels** [comment]
Sigh, apologies for this. One or two other people have reported a similar error. There's something weird about matplotlib requirements (not my favourite dependency!). If you first install an older version of matplotlib it should work:

```
conda install matplotlib=3.0.3
conda install multiqc=1.7
```

In the v1.8dev we've added these matplotlib requirements, so it should be fixed in the next version:
https://github.com/ewels/MultiQC/blob/f2ec3d488c9acffdd30e280f04abd8ab0c58de72/setup.py#L36-L40

Hopefully that should do it... Let me know how you get on!

**Comment by thesimpleton** [comment]
Hi Phil,

I managed to download v1.8 using the git clone instead of conda. I was able
to get it to run for a bit until I encounter another issue.

(base) Hqhongis-MacBook-Pro:MultiQC hqhong$ multiqc .

[INFO   ]         multiqc : This is MultiQC v1.8.dev0

[INFO   ]         multiqc : Template    : default

[INFO   ]         multiqc : Searching '.'

Searching 307 files..  [####################################]  100%


[ERROR  ]         multiqc : Oops! The 'gatk' MultiQC module broke...

  Please copy the following traceback and report it at
https://github.com/ewels/MultiQC/issues

  If possible, please include a log file that triggers the error - the last
file found was:

    ./modules/gatk/varianteval.py

============================================================

Module gatk raised an exception: Traceback (most recent call last):

  File
"/anaconda3/lib/python3.7/site-packages/multiqc-1.8.dev0-py3.7.egg/EGG-INFO/scripts/multiqc",
line 440, in multiqc

    output = mod()

  File
"/anaconda3/lib/python3.7/site-packages/multiqc-1.8.dev0-py3.7.egg/multiqc/modules/gatk/gatk.py",
line 41, in __init__

    n_reports_found += self.parse_gatk_varianteval()

  File
"/anaconda3/lib/python3.7/site-packages/multiqc-1.8.dev0-py3.7.egg/multiqc/modules/gatk/varianteval.py",
line 20, in parse_gatk_varianteval

    parsed_data = parse_single_report(f['f'])

  File
"/anaconda3/lib/python3.7/site-packages/multiqc-1.8.dev0-py3.7.egg/multiqc/modules/gatk/varianteval.py",
line 106, in parse_single_report

    d[headers[i]] = s

IndexError: list index out of range

============================================================

[INFO   ]          picard : Found 1 ValidateSamFile reports

[INFO   ]        samtools : Found 1 rmdup reports

[INFO   ]         multiqc : Compressing plot data

[INFO   ]         multiqc : Report      : multiqc_report.html

[INFO   ]         multiqc : Data        : multiqc_data

[INFO   ]         multiqc : MultiQC complete

Do you have any idea how to fix this? So sorry for having to trouble you
again! Not sure why we fixed one, and come another.

**Comment by ewels** [comment]
Hi @thesimpleton,

It looks like you're running MultiQC on the installation directory. You need to give it a path to your analysis files. See https://multiqc.info/docs/#running-multiqc

Phil

**Comment by ewels** [comment]
NB: You're not the first person to do this. For v1.8dev I've just added a check (see 391ae6707cbd9f827c40f024ce5d28079a6e1ce9) that throws an error message and skips the directory if it appears to contain the MultiQC source code.

```
$ multiqc .
[INFO   ]         multiqc : This is MultiQC v1.8.dev0 (391ae67)
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching   : /Users/philewels/GitHub/MultiQC
[ERROR  ]          report : Error: MultiQC is running in source code directory! .
[WARNING]          report : Please see the docs for how to use MultiQC: https://multiqc.info/docs/#running-multiqc
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
```

Hopefully this will help people avoid this error in the future 😃
