### ISSUE TITLE
Installing MultiQC 1.8dev via conda

### ISSUE THREAD

**Issue by hreinwal** [ewels/MultiQC#996]
Dear MultiQC Team, 
I am using MultiQC 1.7 and qorts 1.3.0 and I just ran in the same error message as posted in #821 .
I know you already fixed this bug (#821 ) in the current dev version 1.8. However I am having problems installing this version via conda. 

I checked via `conda search multiqc`  and the latest available packages are the following:

> multiqc 1.6a0 py36h24bf2e0_1 bioconda
> multiqc 1.6a0 py36h24bf2e0_2 bioconda
> multiqc 1.6 py27h24bf2e0_0 bioconda
> multiqc 1.6 py35h24bf2e0_0 bioconda
> multiqc 1.6 py36h24bf2e0_0 bioconda
> multiqc 1.7 py_0 bioconda
> multiqc 1.7 py_1 bioconda
> multiqc 1.7 py_2 bioconda
> multiqc 1.7 py_3 bioconda
> multiqc 1.7 py_4 bioconda

Could someone give me some guideline on how to implement Phil's bug fix?

**Comment by ewels** [comment]
Hello! MultiQC team here 😁 

Looks like v1.8dev of MultiQC isn't on conda yet (I haven't added it, sometimes other people do dev version releases there though). But you can still install the dev version fairly easily into a conda environment. Either using `pip` as follows:

```bash
pip install git+https://github.com/ewels/MultiQC.git
```
 (See https://multiqc.info/docs/#installation-with-pip)

Or by manually cloning and installing - see https://multiqc.info/docs/#manual-installation

Phil

**Comment by hreinwal** [comment]
Awesome thank you so much for your constant and quick support Phil. Highly appreciated 😁!
