### ISSUE TITLE
scientific notation for very small numbers in table 

### ISSUE THREAD

**Issue by zyqfrog10** [ewels/MultiQC#997]
Hello,

I am trying to add a table including p-values for DEGs. But the numbers are shown up as zeros.
It would nice if multiqc stats table allow scientific notation.
Thanks.
YZ

**Comment by zyqfrog10** [comment]
Figured it out. You need to specify it in a configuration file with ```format: '{.0000f}'```. 
It would be handy if multiqc can output the scientific small numbers directly from a table.

**Comment by ewels** [comment]
Hi @zyqfrog10,

Which tables are you talking about? Is this with custom content? Those format strings are directly passed on to the Python `format` function, so you can use `{.2E}` instead of `f` if you want scientific notation instead of a float.

Phil

**Comment by N-damo** [comment]
how to  specify it  in a configuration file?

**Comment by ewels** [comment]
I believe that this was specifically for "Custom Content" tables. So this is in the configuration for table headers. See https://multiqc.info/docs/#creating-a-table for details.
