### ISSUE TITLE
fastp sample names

### ISSUE THREAD

**Issue by jprnz** [ewels/MultiQC#998]
Currently the way sample names are determined in the fastp module will break when a sample has been piped to fastp (using --stdin) or when entered via bash process substitution (ex, `<(zcat fq1.fastq.gz)`).

The latter will result in a command like `fasp --i /dev/fd/64` and will result in an erroneous filename.

I would propose that fastp derive its sample names from the name of the .json file itself.
This would be in keeping with many of the other modules that do the same.

Thank you!

**Comment by ewels** [comment]
Hi @jprnz,

I think that the reason I didn't do this is that in all of the examples I found, the JSON file was just called `fastp.json` - see https://github.com/ewels/MultiQC_TestData/tree/master/data/modules/fastp

This is the code that grabs the sample name from the command:
https://github.com/ewels/MultiQC/blob/f2ec3d488c9acffdd30e280f04abd8ab0c58de72/multiqc/modules/fastp/fastp.py#L147-L154

I propose two alternatives:

1. If the filename is _not_ just `fastp.json`, use that
2. If the sample name from the command looks odd (`--` or whatever it is that you're getting), use the json filename

When you use `--stdin` am I wrong in thinking that `-i` is not specified? If so, I'm kind of surprised that the code isn't already working as you suggest, as it should be looking only for `-i` in the command (specifically `-i`, not `--i` as in your example command). What is your exact command and what sample name do you get?

Cheers,

Phil

**Comment by jprnz** [comment]
@ewels thank you for your kind suggestions and prompt response!

I think your proposal sounds good and would work in my case.

I am using bash's process substitution as an argument to -i. My command looks like this:
`fastp -i <(zcat a.fq.gz b.fq.gz c.fq.gz)`

This similar in spirit to creating a named pipe, but bash creates these output streams under /dev/fd/<number>. <number> will be, at least to my mind, a random number.

I have not tested this with --stdin, you might be right about this behavior. 

Thanks again for your help with this minor edge case.

**Comment by ewels** [comment]
Would it be possible for you to attach a `fastp.json` file to this issue for me to take a look at please?

**Comment by jprnz** [comment]
Sure thing.

[fastp_json.zip](https://github.com/ewels/MultiQC/files/3469136/fastp_json.zip)

**Comment by ewels** [comment]
Hi @jprnz,

I have added new functionality to take the log filename as the sample name as a general feature for any module / file search pattern in fa84c47f7d77284ee8fe1335132af5a6e6b4c5e2 and will be included in the MultiQC v1.11 release.

The documentation for this new feature is here: https://multiqc.info/docs/#using-log-filenames-as-sample-names

I think this should solve the issue you were getting above. I know it's an old issue, sorry for the delay. If you or any googlers find any problems, let me know.

Cheers,

Phil
